/** Godot 4 export: the generic envelope with `engineTarget:"godot-4"`, plus the two or three
 * numbers Godot needs in its own units, plus a readable GDScript helper that builds a real
 * `SpriteFrames` resource through the engine API.
 *
 * No `.tres` or `.tscn` text is ever written by this file. A hand-written resource look-alike is a
 * guess at a format that changes between versions; a script that calls `SpriteFrames.add_frame`
 * and `ResourceSaver.save` produces whatever the installed Godot actually writes.
 *
 * What had to be checked against the engine rather than assumed (Godot 4.7.2, see docs/SPRITE-LAB.md):
 *  * `SpriteFrames.add_frame(anim, texture, duration := 1.0, at_position := -1)` — the duration is
 *    **relative**: 1.0 means one tick at the animation's own speed, so a 250 ms frame in a 12 fps
 *    animation is 250 × 12 / 1000 = 3.0. There is no `set_frame_duration`, so it must be passed at
 *    `add_frame` time.
 *  * `AtlasTexture.margin` restores a trimmed frame's full size when it is
 *    `Rect2(offset.x, offset.y, sourceSize.w − region.w, sourceSize.h − region.h)`: measured
 *    `get_size() == (32, 24)` for a 20×14 region trimmed out of a 32×24 frame at offset (5, 7).
 *  * A new `SpriteFrames` already owns an animation called `default`; the helper removes it when
 *    the project does not define one, or the resource ships with an empty animation.
 *  * Godot 3.x has no per-frame duration at all and uses `AnimatedSprite` rather than
 *    `AnimatedSprite2D`; this export targets 4.x only. */
import {playbackOrder,playbackTimes} from '../model.js';
import {exportProject,frameNames,TOOL,TOOL_VERSION} from './generic-json.js';
export const GODOT_TARGET='godot-4';
export const GODOT_ADDON_PATH='res://addons/nerulio_sprite';
export const GODOT_VERSION_NOTES=Object.freeze([
 'Godot 4.x only. add_frame(anim, texture, duration, at_position) takes a duration relative to the animation speed.',
 'Godot 3.x SpriteFrames has no per-frame duration and the node is AnimatedSprite, not AnimatedSprite2D: a 3.x import would lose every per-frame timing.',
 'AtlasTexture cannot rotate a region, which is why this tool never packs rotated.',
 'Playback direction is baked: godot.animations[].frames is already in playback order, because SpriteFrames has no direction of its own.']);
/** @returns the generic envelope plus a `godot` block, and per-frame/per-animation `godot` fields. */
export function godotProject(project,options={}){
 const {frames=[],animations=[]}=project;
 const names=options.names||frameNames(frames);
 const data=exportProject(project,{...options,names,engineTarget:GODOT_TARGET,
  meta:{godot:{version:'4',addonPath:GODOT_ADDON_PATH,helper:'nerulio_sprite_frames.gd',notes:GODOT_VERSION_NOTES,...(options.meta?.godot||{})},...(options.meta||{})}});
 for(const f of frames){
  const entry=data.frames[names.get(f.id)],{rect,sourceSize,offset}=entry;
  entry.godot={margin:[offset.x,offset.y,sourceSize.w-rect.w,sourceSize.h-rect.h],filterClip:true};
 }
 for(const a of animations){
  const order=playbackOrder(a),times=playbackTimes(a,frames),tick=1000/a.fps;
  data.animations[a.name].godot={speed:a.fps,loop:a.loop,
   frames:order.map((id,i)=>({frame:names.get(id),duration:+(times[i]/tick).toFixed(6)}))};
 }
 data.godot={version:'4',images:data.meta.images,animations:Object.fromEntries(Object.entries(data.animations).map(([name,a])=>[name,a.godot]))};
 return data;
}
export const godotJson=(project,options)=>JSON.stringify(godotProject(project,options),null,2);
/** The builder: static functions only, so the editor script and the headless runner share one
 * implementation and neither depends on `class_name` being registered. */
export const GODOT_HELPER=`# nerulio_sprite_frames.gd - builds a SpriteFrames resource from a Nerulio Sprite Lab export.
# Generated by ${TOOL} v${TOOL_VERSION}. Drop this folder into your project at
# ${GODOT_ADDON_PATH}/ next to the exported .json and .png files, then either
#   * run nerulio_sprite_import.gd from the editor (File > Run, or the Script editor's Run button), or
#   * run it headless:  godot --headless --path . --script res://addons/nerulio_sprite/nerulio_sprite_import_cli.gd -- <export.json> <out.tres>
#
# Nothing here writes resource text by hand: the engine saves whatever format this version uses.
extends RefCounted


static func load_data(json_path: String) -> Dictionary:
	var text := FileAccess.get_file_as_string(json_path)
	if text.is_empty():
		push_error("Cannot read %s" % json_path)
		return {}
	var parsed: Variant = JSON.parse_string(text)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("%s is not a Sprite Lab export" % json_path)
		return {}
	var data: Dictionary = parsed
	if int(data.get("meta", {}).get("schemaVersion", 0)) != 1:
		push_warning("Unexpected schemaVersion; this helper was written for 1.")
	return data


# The atlas pages, in page order. ResourceLoader is tried first (an imported texture keeps the
# project's filter and mipmap settings); a raw PNG that the editor has not imported yet - the
# usual case in a headless run - is read straight off disk instead.
static func load_textures(data: Dictionary, base_dir: String) -> Array[Texture2D]:
	var textures: Array[Texture2D] = []
	for name: String in data.get("meta", {}).get("images", []):
		var path := base_dir.path_join(name)
		var texture: Texture2D = null
		if ResourceLoader.exists(path):
			texture = ResourceLoader.load(path) as Texture2D
		if texture == null:
			var image := Image.load_from_file(path)
			if image == null:
				push_error("Cannot read atlas page %s" % path)
				return []
			texture = ImageTexture.create_from_image(image)
		textures.append(texture)
	return textures


static func atlas_texture(data: Dictionary, frame_name: String, textures: Array[Texture2D]) -> AtlasTexture:
	var frame: Dictionary = data.get("frames", {}).get(frame_name, {})
	if frame.is_empty():
		push_error("The export has no frame called %s" % frame_name)
		return null
	var page := int(frame.get("page", 0))
	if page >= textures.size():
		push_error("Frame %s wants atlas page %d, which was not loaded" % [frame_name, page])
		return null
	var rect: Dictionary = frame["rect"]
	var margin: Array = frame.get("godot", {}).get("margin", [0, 0, 0, 0])
	var texture := AtlasTexture.new()
	texture.atlas = textures[page]
	texture.region = Rect2(rect["x"], rect["y"], rect["w"], rect["h"])
	# position = where the trimmed pixels sit on the frame canvas, size = the trimmed-away slack.
	# Together they make get_size() report the frame's original canvas size again.
	texture.margin = Rect2(margin[0], margin[1], margin[2], margin[3])
	texture.filter_clip = true
	return texture


static func build(data: Dictionary, textures: Array[Texture2D]) -> SpriteFrames:
	var frames := SpriteFrames.new()
	var cache := {}
	var animations: Dictionary = data.get("godot", {}).get("animations", {})
	for anim_name: String in animations:
		var anim: Dictionary = animations[anim_name]
		if not frames.has_animation(anim_name):
			frames.add_animation(anim_name)
		frames.set_animation_speed(anim_name, float(anim.get("speed", 12.0)))
		frames.set_animation_loop(anim_name, bool(anim.get("loop", true)))
		for step: Dictionary in anim.get("frames", []):
			var frame_name := String(step["frame"])
			if not cache.has(frame_name):
				cache[frame_name] = atlas_texture(data, frame_name, textures)
			if cache[frame_name] == null:
				continue
			# The duration is relative to the animation speed, not seconds, and can only be given here.
			frames.add_frame(anim_name, cache[frame_name], float(step.get("duration", 1.0)))
	if not animations.has("default") and frames.has_animation("default"):
		frames.remove_animation("default")
	# Pivots, hitboxes and collision polygons have nowhere to live on SpriteFrames itself, so they
	# ride along as metadata. build_scene() below turns the collision data into real nodes.
	var extras := {}
	for frame_name: String in data.get("frames", {}):
		var frame: Dictionary = data["frames"][frame_name]
		extras[frame_name] = {
			"pivot": frame.get("pivot", {"x": 0.5, "y": 1.0}),
			"source_size": frame.get("sourceSize", {}),
			"offset": frame.get("offset", {}),
			"tag": frame.get("tag", ""),
			"boxes": frame.get("boxes", []),
			"collision": frame.get("collision", []),
		}
	frames.set_meta("nerulio", {"tool": data.get("meta", {}).get("tool", ""), "frames": extras})
	return frames


static func import(json_path: String, out_path: String = "") -> SpriteFrames:
	var data := load_data(json_path)
	if data.is_empty():
		return null
	var textures := load_textures(data, json_path.get_base_dir())
	if textures.is_empty():
		return null
	var frames := build(data, textures)
	if out_path != "":
		var error := ResourceSaver.save(frames, out_path)
		if error != OK:
			push_error("ResourceSaver.save(%s) failed with error %d" % [out_path, error])
			return null
	return frames


# An AnimatedSprite2D playing one animation, with the frame's collision polygons as child
# CollisionPolygon2D nodes under a StaticBody2D. Built through the API and returned as a node, so
# the caller can add it to a scene or pack it with PackedScene - never written out as .tscn text.
static func build_scene(data: Dictionary, frames: SpriteFrames, anim_name: String) -> Node2D:
	var root := Node2D.new()
	root.name = anim_name
	var sprite := AnimatedSprite2D.new()
	sprite.name = "Sprite"
	sprite.sprite_frames = frames
	sprite.animation = anim_name
	sprite.centered = false
	var animations: Dictionary = data.get("godot", {}).get("animations", {})
	var first: String = ""
	if animations.has(anim_name) and not animations[anim_name].get("frames", []).is_empty():
		first = String(animations[anim_name]["frames"][0]["frame"])
	if first != "":
		var frame: Dictionary = data["frames"][first]
		var size: Dictionary = frame.get("sourceSize", {"w": 0, "h": 0})
		var pivot: Dictionary = frame.get("pivot", {"x": 0.5, "y": 1.0})
		# The pivot is normalised on the frame canvas, y down; offset the sprite so the pivot
		# lands on the node's origin, which is what every engine means by a pivot.
		sprite.offset = Vector2(-float(pivot["x"]) * float(size["w"]), -float(pivot["y"]) * float(size["h"]))
		var polygons: Array = frame.get("collision", [])
		if not polygons.is_empty():
			var body := StaticBody2D.new()
			body.name = "Collision"
			root.add_child(body)
			for polygon: Array in polygons:
				var points := PackedVector2Array()
				for point: Array in polygon:
					points.append(Vector2(float(point[0]), float(point[1])) + sprite.offset)
				var shape := CollisionPolygon2D.new()
				shape.polygon = points
				body.add_child(shape)
	root.add_child(sprite)
	return root


# Reads the built resource back and reports anything that does not match the JSON. Useful after an
# import, and it is what the tool's own Godot test asserts on.
static func verify(data: Dictionary, frames: SpriteFrames) -> PackedStringArray:
	var problems := PackedStringArray()
	var animations: Dictionary = data.get("godot", {}).get("animations", {})
	for anim_name: String in animations:
		var anim: Dictionary = animations[anim_name]
		if not frames.has_animation(anim_name):
			problems.append("missing animation %s" % anim_name)
			continue
		var expected: Array = anim.get("frames", [])
		if frames.get_frame_count(anim_name) != expected.size():
			problems.append("%s has %d frames, expected %d" % [anim_name, frames.get_frame_count(anim_name), expected.size()])
			continue
		if absf(frames.get_animation_speed(anim_name) - float(anim["speed"])) > 0.001:
			problems.append("%s speed is %f, expected %f" % [anim_name, frames.get_animation_speed(anim_name), float(anim["speed"])])
		if frames.get_animation_loop(anim_name) != bool(anim["loop"]):
			problems.append("%s loop is %s" % [anim_name, str(frames.get_animation_loop(anim_name))])
		for i in expected.size():
			var step: Dictionary = expected[i]
			if absf(frames.get_frame_duration(anim_name, i) - float(step["duration"])) > 0.001:
				problems.append("%s frame %d duration is %f, expected %f" % [anim_name, i, frames.get_frame_duration(anim_name, i), float(step["duration"])])
			var texture := frames.get_frame_texture(anim_name, i) as AtlasTexture
			if texture == null:
				problems.append("%s frame %d is not an AtlasTexture" % [anim_name, i])
				continue
			var frame: Dictionary = data["frames"][String(step["frame"])]
			var rect: Dictionary = frame["rect"]
			var want := Rect2(rect["x"], rect["y"], rect["w"], rect["h"])
			if texture.region != want:
				problems.append("%s frame %d region is %s, expected %s" % [anim_name, i, str(texture.region), str(want)])
			var size: Dictionary = frame["sourceSize"]
			if texture.get_size() != Vector2(size["w"], size["h"]):
				problems.append("%s frame %d reports size %s, expected %s" % [anim_name, i, str(texture.get_size()), str(Vector2(size["w"], size["h"]))])
	return problems
`;
export const GODOT_EDITOR_SCRIPT=`# nerulio_sprite_import.gd - run this from the Godot editor (Script editor > File > Run).
# It reads the Sprite Lab export next to itself and saves a SpriteFrames resource you can drop on
# an AnimatedSprite2D. Change the two paths below to match your project.
@tool
extends EditorScript

const Builder := preload("res://addons/nerulio_sprite/nerulio_sprite_frames.gd")
const EXPORT_JSON := "res://addons/nerulio_sprite/atlas.json"
const OUTPUT_RESOURCE := "res://addons/nerulio_sprite/sprite_frames.tres"


func _run() -> void:
	var data: Dictionary = Builder.load_data(EXPORT_JSON)
	if data.is_empty():
		return
	var frames: SpriteFrames = Builder.import(EXPORT_JSON, OUTPUT_RESOURCE)
	if frames == null:
		return
	var problems: PackedStringArray = Builder.verify(data, frames)
	if problems.is_empty():
		print("Nerulio: saved %s with %d animation(s), all frames matching the export." % [OUTPUT_RESOURCE, frames.get_animation_names().size()])
	else:
		for problem: String in problems:
			push_error("Nerulio: %s" % problem)
`;
export const GODOT_CLI_SCRIPT=`# nerulio_sprite_import_cli.gd - the same import, headless.
#   godot --headless --path . --script res://addons/nerulio_sprite/nerulio_sprite_import_cli.gd -- atlas.json sprite_frames.tres
extends SceneTree

const Builder := preload("res://addons/nerulio_sprite/nerulio_sprite_frames.gd")


func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	if args.size() < 1:
		print("usage: --script nerulio_sprite_import_cli.gd -- <export.json> [out.tres]")
		quit(2)
		return
	var json_path: String = args[0]
	var out_path: String = args[1] if args.size() > 1 else ""
	var data: Dictionary = Builder.load_data(json_path)
	if data.is_empty():
		quit(1)
		return
	var frames: SpriteFrames = Builder.import(json_path, out_path)
	if frames == null:
		quit(1)
		return
	var problems: PackedStringArray = Builder.verify(data, frames)
	for problem: String in problems:
		printerr("MISMATCH %s" % problem)
	print("animations=%s" % str(frames.get_animation_names()))
	for anim_name: String in frames.get_animation_names():
		print("%s frames=%d speed=%f loop=%s" % [anim_name, frames.get_frame_count(anim_name), frames.get_animation_speed(anim_name), str(frames.get_animation_loop(anim_name))])
	print("problems=%d" % problems.size())
	quit(0 if problems.is_empty() else 1)
`;
export const GODOT_README=`# Godot 4 import

1. Copy \`nerulio_sprite/\` into your project's \`addons/\` folder, together with the exported
   \`.json\` and the \`atlas*.png\` pages.
2. Editor: open \`nerulio_sprite_import.gd\`, set \`EXPORT_JSON\` and \`OUTPUT_RESOURCE\`, then
   File > Run. Headless:
   \`godot --headless --path . --script res://addons/nerulio_sprite/nerulio_sprite_import_cli.gd -- addons/nerulio_sprite/atlas.json addons/nerulio_sprite/sprite_frames.tres\`
3. Drop the saved \`.tres\` on an \`AnimatedSprite2D\`'s **Sprite Frames** property.

Notes
* Per-frame durations are **relative** to each animation's speed: a frame with duration 3.0 in a
  12 fps animation lasts 250 ms. The exporter has already converted your millisecond values.
* Reverse and ping-pong are baked into the frame order, because \`SpriteFrames\` has no direction.
* Trimmed frames keep their original size through \`AtlasTexture.margin\`, so a frame still lines
  up with the others even though only its opaque pixels are stored.
* Pivots, tags, hitboxes and collision polygons are stored as metadata under the \`nerulio\` key
  (\`sprite_frames.get_meta("nerulio")\`). \`build_scene()\` turns the collision polygons into real
  \`CollisionPolygon2D\` nodes under a \`StaticBody2D\`.
* Godot 3.x is not supported: its \`SpriteFrames\` has no per-frame duration and the node is
  \`AnimatedSprite\`.
`;
/** Every file a Godot export writes, beside the atlas page images. */
export function godotBundle(project,options={}){
 const data=godotProject(project,options);
 const stem=data.meta.image.replace(/\.[^.]*$/,'').replace(/-0$/,'');
 return [{name:`${stem}.json`,text:JSON.stringify(data,null,2),type:'application/json'},
  {name:'addons/nerulio_sprite/nerulio_sprite_frames.gd',text:GODOT_HELPER,type:'text/plain'},
  {name:'addons/nerulio_sprite/nerulio_sprite_import.gd',text:GODOT_EDITOR_SCRIPT,type:'text/plain'},
  {name:'addons/nerulio_sprite/nerulio_sprite_import_cli.gd',text:GODOT_CLI_SCRIPT,type:'text/plain'},
  {name:'addons/nerulio_sprite/README.md',text:GODOT_README,type:'text/markdown'}];
}
