/** Studio UI copy (ko/en/ja). Same pattern as src/task/strings.js: nested keys, {name} slots,
 * English fallback. tests/studio.test.mjs checks that all three languages have the same keys
 * and placeholders. Heuristics are never called "AI"; guesses always say how sure they are. */
const bgs=(a)=>({checker:a[0],light:a[1],black:a[2],white:a[3],magenta:a[4],gray:a[5]});
const S={
en:{
 app:{title:'Studio',description:'Nerulio Studio: a full-screen editor for 2D game assets in your browser. Nothing is uploaded.',loading:'Loading Studio…',noscript:'Nerulio Studio needs JavaScript. Your files never leave this device.'},
 project:{untitled:'Untitled'},
 status:{label:'Status',zoom:'{z}%',memory:'{mb}',memoryHint:'Images kept once: {stored} stored · {decoded} decoded for display',image:'{w}×{h} px',cursor:'x {x}  y {y}',importing:'Importing {i}/{n}…',frameSel:'{name} · {w}×{h}',framesSel:'{n} frames · {w}×{h}'},
 save:{autosaveFailed:'Autosave failed',saving:'Saving…',empty:'No project yet',autosaved:'Autosaved {time}',unsaved:'Not saved',saved:'Saved to file',hintDirty:'Changes are autosaved in this browser but not yet saved to a .nerulio file (File › Save).',hintClean:'Everything is saved to a .nerulio file.'},
 error:{decode:'Could not read {name} as an image.',unsupported:'Not an image this Studio can open: {names}',tooBig:'{name} is {w}×{h} — too large for a browser canvas.',open:'Could not open the project: {reason}',nothingToSave:'Add an image first — there is nothing to save yet.'},
 toast:{imported:'Imported {n} image(s).',opened:'Opened {name}.',saved:'Saved {name}.',removed:'Removed {name} ({undo} to undo).',restored:'Project restored from autosave.',previousKept:'Your previous autosave is kept under File › Autosaved versions.',gridReplaced:'{n} frames cut (replaced {old}; {undo} to undo).',gridApplied:'{n} frames cut from the grid.',cleared:'Cleared {n} frames ({undo} to undo).',handoffFrames:'Brought {n} frames over from Sprite Lab.'},
 confirm:{replaceTitle:'Replace the open project?',replace:'"{name}" has changes that are not saved to a file. They stay available under File › Autosaved versions.',continue:'Continue',cancel:'Cancel',ok:'OK',close:'Close'},
 dialog:{saveAsTitle:'Save project as',projectName:'Project name',renameAsset:'Rename image',name:'Name',renameProject:'Rename project'},
 cmd:{importN:'Import {n} image(s)',renameAsset:'Rename image',removeAsset:'Remove {name}',
  file:{new:'New project',open:'Open project…',import:'Import images…',save:'Save',saveAs:'Save as…',rename:'Rename project…',versions:'Autosaved versions…'},
  edit:{undo:'Undo',undoX:'Undo {what}',redo:'Redo',redoX:'Redo {what}',selectAll:'Select all frames',deselect:'Deselect',delete:'Delete selection'},
  app:{palette:'Command palette…',shortcuts:'Keyboard shortcuts',history:'Show history'},
  view:{zoomIn:'Zoom in',zoomOut:'Zoom out',zoom100:'Actual pixels (100%)',fit:'Fit on screen',zoomN:'Zoom {z}%',pixelGrid:'Pixel grid',grid:'Cell grid',rulers:'Rulers',rightDock:'Inspector panels',bottomDock:'Bottom panel',resetLayout:'Reset panel layout',
   bg:bgs(['Dark checker','Light checker','Black','White','Magenta','Gray']),wheel:{auto:'Wheel: auto (mouse zooms, trackpad pans)',zoom:'Wheel always zooms',pan:'Wheel always pans'},theme:{dark:'Dark',light:'Light'}},
  help:{about:'About Studio'},
  nudge:{left:'Nudge left 1 px',right:'Nudge right 1 px',up:'Nudge up 1 px',down:'Nudge down 1 px',left10:'Nudge left 10 px',right10:'Nudge right 10 px',up10:'Nudge up 10 px',down10:'Nudge down 10 px'},
  frame:{prev:'Previous frame',next:'Next frame'},
  frames:{detect:'Suggest grid',apply:'Apply grid as frames',clear:'Clear frames',reveal:'Show selection',move:'Move frames',resize:'Resize frame',add:'Add frame',applyGrid:'Cut {n} frames ({w}×{h})',rename:'Rename frame',edit:'Edit frame',delete:'Delete {n} frame(s)',nudge:'Nudge frames',fromHandoff:'{n} frames from Sprite Lab'}},
 tool:{hand:'Hand',handHint:'drag to pan; Space+drag works with any tool',zoom:'Zoom',zoomHint:'click to zoom in, Alt+click to zoom out',select:'Select',selectHint:'click, Shift+click, drag handles to resize',frame:'Frame',frameHint:'drag on empty canvas to add a frame'},
 toolbar:{label:'Tools'},
 menu:{bar:'Main menu',more:'Menu',file:'File',edit:'Edit',view:'View',zoomLevels:'Zoom level',background:'Background',wheel:'Mouse wheel',theme:'Theme',workspace:'Workspace',help:'Help',language:'Language',frames:'Frames'},
 ws:{viewer:'Viewer',viewerSummary:'import, view, cut frames',sprite:'Sprite',spriteSummary:'timeline, tags, pivots and hitboxes, pack and engine export',pixel:'Pixel',pixelSummary:'pencil, palette and cleanup tools',tile:'Tile',tileSummary:'tilesets, autotile rules and a map painter',texture:'Texture',textureSummary:'normal maps, channels and light preview',ui:'UI',uiSummary:'9-slice, button states and bitmap fonts',coming:'{name} workspace is coming in {phase}: {what}.',comingShort:'coming ({phase})'},
 panel:{assets:'Assets',history:'History',grid:'Grid',frame:'Frame',frames:'Frames',toBottom:'Move to bottom panel',toRight:'Move to right panels',up:'Move up',down:'Move down',expand:'Expand',collapse:'Collapse',resetLayout:'Reset layout',hideBottom:'Hide bottom panel',showBottom:'Show bottom panel',options:'{name} panel options',all:'Panels'},
 assets:{empty:'No images yet. Drop PNG, JPG, WebP or GIF files anywhere.',remove:'Remove {name}',frames:'{n} frames'},
 history:{start:'Opened project'},
 group:{file:'File',edit:'Edit',view:'View',tools:'Tools',frames:'Frames',navigate:'Navigate',app:'Studio',help:'Help',workspace:'Workspace',other:'Other',pointer:'Mouse, pen and touch'},
 keys:{title:'Keyboard shortcuts',wheel:'Zoom at the cursor (mouse wheel)',wheelKey:'Wheel',ctrlWheel:'Zoom at the cursor (any wheel or trackpad)',spaceDrag:'Pan',drag:'drag',middleDrag:'Pan',middle:'Middle-button drag',pinch:'Zoom and pan (touch, trackpad)',pinchKey:'Two-finger pinch / scroll',shiftClick:'Add or remove from selection',click:'click',escDrag:'Cancel a drag in progress'},
 palette:{placeholder:'Type a command…',title:'Command palette',none:'No matching command.'},
 about:{title:'About Nerulio Studio',body:'A browser app for 2D game assets. Images are processed on this device only; projects autosave to this browser and save to .nerulio files.',renderer:'Renderer: {r}{why}',dpr:'Device pixel ratio: {dpr} (zoom is measured in screen pixels, so pixels stay square and sharp)',memory:'Images in memory: {n} ({stored} stored, {decoded} decoded)',local:'No uploads: nothing in this app sends your files anywhere.',rendererShort:'Canvas renderer'},
 versions:{none:'No autosaved versions in this browser yet.',title:'Autosaved versions',hint:'The last 10 autosaves of each project are kept in this browser. Images are stored once for all of them.',meta:'{assets} image(s) · {frames} frames'},
 empty:{import:'Import images…',open:'Open project…',keys:'Keyboard shortcuts',title:'Drop images or a .nerulio project anywhere',formats:'PNG · JPG · WebP · GIF (first frame) · several at once',local:'Nothing is uploaded'},
 canvas:{label:'Canvas. Wheel zooms, Space or middle-drag pans, arrow keys nudge the selection.'},
 drop:{hint:'Drop to import images · .nerulio to open'},
 recover:{title:'Restore your last session?',body:'"{name}" was autosaved {time}: {assets} image(s), {frames} frames.',hint:'Start fresh keeps it under File › Autosaved versions.',discard:'Start fresh',restore:'Restore'},
 grid:{noImage:'Import an image to cut frames.',detecting:'Looking for a grid…',detectFailed:'Grid suggestion failed: {reason}',noSuggestion:'No grid stood out. Enter the cell size yourself.',transparent:'The image is fully transparent — nothing to measure.',cells:'{c}×{r} cells',margin:'margin {v}',gap:'gap {v}',
  conf:{high:'high',medium:'medium',low:'low'},why:'Why?',w:'W',h:'H',ox:'Offset X',oy:'Offset Y',sx:'Gap X',sy:'Gap Y',show:'Show grid on canvas',skipEmpty:'Skip empty cells',replace:'Replace frames with grid',apply:'Apply grid as frames',detect:'Suggest again',
  stateApplied:'Applied: {n} frames were cut with this grid.',statePreview:'Preview only — not applied. Check it on the canvas, then Apply.',stateNone:'No grid yet.',suggested:'Suggested grids',cellTitle:'Cell grid',countPending:'{c}×{r} = {n} cells',tooMany:'{n} cells is too many for frames — use a larger cell.',count:'{c}×{r} = {n} cells · {filled} with pixels',noCells:'Every cell is empty with these settings.',
  reason:{separator:'{n} gap lines, {pct} of them fully transparent',noSeparator:'cells touch edge to edge, so there are no gap lines to check',period:'content repeats every {px}×{py} px (autocorrelation {ax} / {ay})',bounds:'content sits alike in each cell ({pct})',cross:'content crosses cell edges in {n} places',noCross:'no content crosses a cell edge',split:'blank lines still split content inside cells — the cell may be too large',uncommon:'uncommon cell size, so it needed stronger evidence',outside:'{n} opaque pixels fall outside the cells',filled:'{filled} of {cells} cells hold pixels'}},
 frame:{noImage:'No image open.',hint:'Click a frame to select it ({v}). Drag its handles to resize, arrows to nudge.',none:'No frames yet. Apply a grid, or draw one with the Frame tool ({m}).',deleteN:'Delete {n} frames',multi:'{n} frames selected · bounds {x}, {y}, {w}×{h}',name:'Name',x:'X',y:'Y',w:'W',h:'H',index:'Frame {i} of {n}'},
 strip:{empty:'Frames appear here once a grid is applied or drawn.',more:'+{n} more'}
},
ko:{
 app:{title:'스튜디오',description:'Nerulio 스튜디오: 브라우저에서 쓰는 2D 게임 에셋 전용 전체 화면 편집기. 파일은 업로드되지 않습니다.',loading:'스튜디오를 여는 중…',noscript:'Nerulio 스튜디오는 JavaScript가 필요합니다. 파일은 이 기기 밖으로 나가지 않습니다.'},
 project:{untitled:'제목 없음'},
 status:{label:'상태 표시줄',zoom:'{z}%',memory:'{mb}',memoryHint:'이미지는 한 번만 보관: 저장 {stored} · 표시용 디코딩 {decoded}',image:'{w}×{h} px',cursor:'x {x}  y {y}',importing:'가져오는 중 {i}/{n}…',frameSel:'{name} · {w}×{h}',framesSel:'프레임 {n}개 · {w}×{h}'},
 save:{autosaveFailed:'자동 저장 실패',saving:'저장 중…',empty:'프로젝트 없음',autosaved:'자동 저장됨 {time}',unsaved:'저장 안 됨',saved:'파일에 저장됨',hintDirty:'변경 내용은 이 브라우저에 자동 저장되지만 아직 .nerulio 파일로 저장되지 않았습니다 (파일 › 저장).',hintClean:'모든 내용이 .nerulio 파일에 저장되었습니다.'},
 error:{decode:'{name} 파일을 이미지로 읽을 수 없습니다.',unsupported:'스튜디오에서 열 수 없는 파일입니다: {names}',tooBig:'{name}은(는) {w}×{h}로 브라우저 캔버스에 비해 너무 큽니다.',open:'프로젝트를 열 수 없습니다: {reason}',nothingToSave:'먼저 이미지를 추가하세요. 아직 저장할 내용이 없습니다.'},
 toast:{imported:'이미지 {n}개를 가져왔습니다.',opened:'{name}을(를) 열었습니다.',saved:'{name}(으)로 저장했습니다.',removed:'{name}을(를) 제거했습니다 ({undo}로 되돌리기).',restored:'자동 저장본에서 프로젝트를 복원했습니다.',previousKept:'이전 자동 저장본은 파일 › 자동 저장 버전에 남아 있습니다.',gridReplaced:'프레임 {n}개를 잘랐습니다 (기존 {old}개 교체, {undo}로 되돌리기).',gridApplied:'그리드로 프레임 {n}개를 잘랐습니다.',cleared:'프레임 {n}개를 지웠습니다 ({undo}로 되돌리기).',handoffFrames:'스프라이트 랩에서 프레임 {n}개를 가져왔습니다.'},
 confirm:{replaceTitle:'열려 있는 프로젝트를 바꿀까요?',replace:'"{name}"에 파일로 저장되지 않은 변경 내용이 있습니다. 이 내용은 파일 › 자동 저장 버전에서 계속 열 수 있습니다.',continue:'계속',cancel:'취소',ok:'확인',close:'닫기'},
 dialog:{saveAsTitle:'다른 이름으로 프로젝트 저장',projectName:'프로젝트 이름',renameAsset:'이미지 이름 바꾸기',name:'이름',renameProject:'프로젝트 이름 바꾸기'},
 cmd:{importN:'이미지 {n}개 가져오기',renameAsset:'이미지 이름 바꾸기',removeAsset:'{name} 제거',
  file:{new:'새 프로젝트',open:'프로젝트 열기…',import:'이미지 가져오기…',save:'저장',saveAs:'다른 이름으로 저장…',rename:'프로젝트 이름 바꾸기…',versions:'자동 저장 버전…'},
  edit:{undo:'실행 취소',undoX:'실행 취소: {what}',redo:'다시 실행',redoX:'다시 실행: {what}',selectAll:'모든 프레임 선택',deselect:'선택 해제',delete:'선택 항목 삭제'},
  app:{palette:'명령 팔레트…',shortcuts:'키보드 단축키',history:'작업 기록 보기'},
  view:{zoomIn:'확대',zoomOut:'축소',zoom100:'실제 픽셀 (100%)',fit:'화면에 맞추기',zoomN:'{z}%로 보기',pixelGrid:'픽셀 격자',grid:'셀 그리드',rulers:'눈금자',rightDock:'오른쪽 패널',bottomDock:'아래 패널',resetLayout:'패널 배치 초기화',
   bg:bgs(['어두운 체커','밝은 체커','검정','흰색','마젠타','회색']),wheel:{auto:'휠: 자동 (마우스는 확대, 트랙패드는 이동)',zoom:'휠로 항상 확대/축소',pan:'휠로 항상 이동'},theme:{dark:'어둡게',light:'밝게'}},
  help:{about:'스튜디오 정보'},
  nudge:{left:'왼쪽으로 1px 이동',right:'오른쪽으로 1px 이동',up:'위로 1px 이동',down:'아래로 1px 이동',left10:'왼쪽으로 10px 이동',right10:'오른쪽으로 10px 이동',up10:'위로 10px 이동',down10:'아래로 10px 이동'},
  frame:{prev:'이전 프레임',next:'다음 프레임'},
  frames:{detect:'그리드 추천',apply:'그리드를 프레임으로 적용',clear:'프레임 모두 지우기',reveal:'선택 항목 보기',move:'프레임 이동',resize:'프레임 크기 조절',add:'프레임 추가',applyGrid:'프레임 {n}개 자르기 ({w}×{h})',rename:'프레임 이름 바꾸기',edit:'프레임 수정',delete:'프레임 {n}개 삭제',nudge:'프레임 미세 이동',fromHandoff:'스프라이트 랩의 프레임 {n}개'}},
 tool:{hand:'손',handHint:'드래그해서 화면 이동. 어떤 도구에서든 Space+드래그도 됩니다',zoom:'돋보기',zoomHint:'클릭하면 확대, Alt+클릭하면 축소',select:'선택',selectHint:'클릭, Shift+클릭, 핸들을 끌어 크기 조절',frame:'프레임',frameHint:'빈 곳을 드래그해 프레임 추가'},
 toolbar:{label:'도구'},
 menu:{bar:'주 메뉴',more:'메뉴',file:'파일',edit:'편집',view:'보기',zoomLevels:'배율',background:'배경',wheel:'마우스 휠',theme:'테마',workspace:'작업 공간',help:'도움말',language:'언어',frames:'프레임'},
 ws:{viewer:'뷰어',viewerSummary:'가져오기, 보기, 프레임 자르기',sprite:'스프라이트',spriteSummary:'타임라인, 태그, 피벗·히트박스, 패킹과 엔진 내보내기',pixel:'픽셀',pixelSummary:'연필, 팔레트, 정리 도구',tile:'타일',tileSummary:'타일셋, 오토타일 규칙, 맵 페인터',texture:'텍스처',textureSummary:'노멀 맵, 채널, 조명 미리보기',ui:'UI',uiSummary:'9-슬라이스, 버튼 상태, 비트맵 폰트',coming:'{name} 작업 공간은 {phase}에서 제공됩니다: {what}.',comingShort:'준비 중 ({phase})'},
 panel:{assets:'에셋',history:'작업 기록',grid:'그리드',frame:'프레임 속성',frames:'프레임',toBottom:'아래 패널로 옮기기',toRight:'오른쪽 패널로 옮기기',up:'위로',down:'아래로',expand:'펼치기',collapse:'접기',resetLayout:'배치 초기화',hideBottom:'아래 패널 숨기기',showBottom:'아래 패널 보이기',options:'{name} 패널 옵션',all:'패널'},
 assets:{empty:'아직 이미지가 없습니다. PNG, JPG, WebP, GIF 파일을 아무 곳에나 놓으세요.',remove:'{name} 제거',frames:'프레임 {n}개'},
 history:{start:'프로젝트 열림'},
 group:{file:'파일',edit:'편집',view:'보기',tools:'도구',frames:'프레임',navigate:'이동',app:'스튜디오',help:'도움말',workspace:'작업 공간',other:'기타',pointer:'마우스, 펜, 터치'},
 keys:{title:'키보드 단축키',wheel:'커서 위치 기준 확대/축소 (마우스 휠)',wheelKey:'휠',ctrlWheel:'커서 위치 기준 확대/축소 (모든 휠·트랙패드)',spaceDrag:'화면 이동',drag:'드래그',middleDrag:'화면 이동',middle:'가운데 버튼 드래그',pinch:'확대/축소와 이동 (터치, 트랙패드)',pinchKey:'두 손가락 핀치 / 스크롤',shiftClick:'선택에 추가하거나 빼기',click:'클릭',escDrag:'진행 중인 드래그 취소'},
 palette:{placeholder:'명령을 입력하세요…',title:'명령 팔레트',none:'맞는 명령이 없습니다.'},
 about:{title:'Nerulio 스튜디오 정보',body:'2D 게임 에셋을 위한 브라우저 앱입니다. 이미지는 이 기기에서만 처리되고, 프로젝트는 이 브라우저에 자동 저장되며 .nerulio 파일로 저장할 수 있습니다.',renderer:'렌더러: {r}{why}',dpr:'기기 픽셀 비율: {dpr} (배율은 화면 픽셀 기준이라 픽셀이 항상 정사각형으로 선명합니다)',memory:'메모리의 이미지: {n}개 (저장 {stored}, 디코딩 {decoded})',local:'업로드 없음: 이 앱은 파일을 어디에도 보내지 않습니다.',rendererShort:'캔버스 렌더러'},
 versions:{none:'이 브라우저에 자동 저장 버전이 아직 없습니다.',title:'자동 저장 버전',hint:'프로젝트마다 최근 자동 저장 10개를 이 브라우저에 보관합니다. 이미지는 모든 버전에 대해 한 번만 저장됩니다.',meta:'이미지 {assets}개 · 프레임 {frames}개'},
 empty:{import:'이미지 가져오기…',open:'프로젝트 열기…',keys:'키보드 단축키',title:'이미지나 .nerulio 프로젝트를 아무 곳에나 놓으세요',formats:'PNG · JPG · WebP · GIF(첫 프레임) · 여러 개 한 번에',local:'업로드 없음'},
 canvas:{label:'캔버스. 휠로 확대/축소, Space나 가운데 버튼 드래그로 이동, 방향키로 선택 항목을 미세 이동합니다.'},
 drop:{hint:'놓으면 이미지를 가져옵니다 · .nerulio는 프로젝트로 엽니다'},
 recover:{title:'지난 작업을 복원할까요?',body:'"{name}"이(가) {time}에 자동 저장되었습니다: 이미지 {assets}개, 프레임 {frames}개.',hint:'새로 시작해도 파일 › 자동 저장 버전에 남아 있습니다.',discard:'새로 시작',restore:'복원'},
 grid:{noImage:'프레임을 자르려면 이미지를 가져오세요.',detecting:'그리드를 찾는 중…',detectFailed:'그리드 추천 실패: {reason}',noSuggestion:'뚜렷한 그리드를 찾지 못했습니다. 셀 크기를 직접 입력하세요.',transparent:'이미지가 완전히 투명해서 측정할 것이 없습니다.',cells:'{c}×{r}칸',margin:'여백 {v}',gap:'간격 {v}',
  conf:{high:'높음',medium:'보통',low:'낮음'},why:'근거',w:'W',h:'H',ox:'오프셋 X',oy:'오프셋 Y',sx:'간격 X',sy:'간격 Y',show:'캔버스에 그리드 표시',skipEmpty:'빈 칸 건너뛰기',replace:'그리드로 프레임 교체',apply:'그리드를 프레임으로 적용',detect:'다시 추천',
  stateApplied:'적용됨: 이 그리드로 프레임 {n}개를 잘랐습니다.',statePreview:'미리보기일 뿐 아직 적용되지 않았습니다. 캔버스에서 확인한 뒤 적용하세요.',stateNone:'아직 그리드가 없습니다.',suggested:'추천 그리드',cellTitle:'셀 그리드',countPending:'{c}×{r} = {n}칸',tooMany:'{n}칸은 프레임으로 쓰기에 너무 많습니다. 셀을 더 크게 하세요.',count:'{c}×{r} = {n}칸 · 픽셀 있는 칸 {filled}개',noCells:'이 설정에서는 모든 칸이 비어 있습니다.',
  reason:{separator:'간격 줄 {n}개 중 {pct}가 완전히 투명',noSeparator:'칸이 맞붙어 있어 확인할 간격 줄이 없음',period:'내용이 {px}×{py}px마다 반복됨 (자기상관 {ax} / {ay})',bounds:'칸마다 내용 위치가 비슷함 ({pct})',cross:'내용이 칸 경계를 {n}곳에서 넘음',noCross:'칸 경계를 넘는 내용 없음',split:'칸 안에서 빈 줄이 내용을 나눔 — 셀이 너무 클 수 있음',uncommon:'흔하지 않은 셀 크기라 더 강한 근거가 필요했음',outside:'불투명 픽셀 {n}개가 칸 밖에 있음',filled:'{cells}칸 중 {filled}칸에 픽셀이 있음'}},
 frame:{noImage:'열린 이미지가 없습니다.',hint:'프레임을 클릭해 선택하세요 ({v}). 핸들을 끌면 크기 조절, 방향키로 미세 이동.',none:'아직 프레임이 없습니다. 그리드를 적용하거나 프레임 도구({m})로 그리세요.',deleteN:'프레임 {n}개 삭제',multi:'프레임 {n}개 선택 · 범위 {x}, {y}, {w}×{h}',name:'이름',x:'X',y:'Y',w:'W',h:'H',index:'{n}개 중 {i}번 프레임'},
 strip:{empty:'그리드를 적용하거나 프레임을 그리면 여기에 표시됩니다.',more:'+{n}개 더'}
},
ja:{
 app:{title:'スタジオ',description:'Nerulio スタジオ：ブラウザで使える2Dゲームアセット用のフルスクリーンエディター。ファイルはアップロードされません。',loading:'スタジオを読み込み中…',noscript:'Nerulio スタジオには JavaScript が必要です。ファイルがこの端末の外に出ることはありません。'},
 project:{untitled:'無題'},
 status:{label:'ステータスバー',zoom:'{z}%',memory:'{mb}',memoryHint:'画像は1回だけ保持：保存 {stored} · 表示用デコード {decoded}',image:'{w}×{h} px',cursor:'x {x}  y {y}',importing:'読み込み中 {i}/{n}…',frameSel:'{name} · {w}×{h}',framesSel:'{n}フレーム · {w}×{h}'},
 save:{autosaveFailed:'自動保存に失敗',saving:'保存中…',empty:'プロジェクトなし',autosaved:'自動保存 {time}',unsaved:'未保存',saved:'ファイルに保存済み',hintDirty:'変更はこのブラウザに自動保存されていますが、まだ .nerulio ファイルには保存されていません（ファイル › 保存）。',hintClean:'すべて .nerulio ファイルに保存されています。'},
 error:{decode:'{name} を画像として読み込めません。',unsupported:'スタジオで開けないファイルです：{names}',tooBig:'{name} は {w}×{h} で、ブラウザのキャンバスには大きすぎます。',open:'プロジェクトを開けません：{reason}',nothingToSave:'先に画像を追加してください。まだ保存するものがありません。'},
 toast:{imported:'画像を{n}枚読み込みました。',opened:'{name} を開きました。',saved:'{name} として保存しました。',removed:'{name} を削除しました（{undo} で元に戻す）。',restored:'自動保存からプロジェクトを復元しました。',previousKept:'以前の自動保存は ファイル › 自動保存の履歴 に残っています。',gridReplaced:'{n}フレームを切り出しました（既存の{old}個を置き換え、{undo} で元に戻す）。',gridApplied:'グリッドから{n}フレームを切り出しました。',cleared:'{n}フレームを消去しました（{undo} で元に戻す）。',handoffFrames:'スプライトラボから{n}フレームを引き継ぎました。'},
 confirm:{replaceTitle:'開いているプロジェクトを置き換えますか？',replace:'「{name}」にはファイルに保存されていない変更があります。変更は ファイル › 自動保存の履歴 から引き続き開けます。',continue:'続ける',cancel:'キャンセル',ok:'OK',close:'閉じる'},
 dialog:{saveAsTitle:'名前を付けてプロジェクトを保存',projectName:'プロジェクト名',renameAsset:'画像の名前を変更',name:'名前',renameProject:'プロジェクト名を変更'},
 cmd:{importN:'画像を{n}枚読み込み',renameAsset:'画像の名前を変更',removeAsset:'{name} を削除',
  file:{new:'新規プロジェクト',open:'プロジェクトを開く…',import:'画像を読み込む…',save:'保存',saveAs:'名前を付けて保存…',rename:'プロジェクト名を変更…',versions:'自動保存の履歴…'},
  edit:{undo:'元に戻す',undoX:'元に戻す：{what}',redo:'やり直す',redoX:'やり直す：{what}',selectAll:'すべてのフレームを選択',deselect:'選択を解除',delete:'選択を削除'},
  app:{palette:'コマンドパレット…',shortcuts:'キーボードショートカット',history:'作業履歴を表示'},
  view:{zoomIn:'ズームイン',zoomOut:'ズームアウト',zoom100:'実際のピクセル (100%)',fit:'画面に合わせる',zoomN:'{z}% で表示',pixelGrid:'ピクセルグリッド',grid:'セルグリッド',rulers:'定規',rightDock:'右パネル',bottomDock:'下パネル',resetLayout:'パネル配置をリセット',
   bg:bgs(['暗いチェッカー','明るいチェッカー','黒','白','マゼンタ','グレー']),wheel:{auto:'ホイール：自動（マウスはズーム、トラックパッドは移動）',zoom:'ホイールで常にズーム',pan:'ホイールで常に移動'},theme:{dark:'ダーク',light:'ライト'}},
  help:{about:'スタジオについて'},
  nudge:{left:'左へ1px移動',right:'右へ1px移動',up:'上へ1px移動',down:'下へ1px移動',left10:'左へ10px移動',right10:'右へ10px移動',up10:'上へ10px移動',down10:'下へ10px移動'},
  frame:{prev:'前のフレーム',next:'次のフレーム'},
  frames:{detect:'グリッドを提案',apply:'グリッドをフレームとして適用',clear:'フレームをすべて消去',reveal:'選択を表示',move:'フレームを移動',resize:'フレームのサイズ変更',add:'フレームを追加',applyGrid:'{n}フレームを切り出し ({w}×{h})',rename:'フレーム名を変更',edit:'フレームを編集',delete:'{n}フレームを削除',nudge:'フレームを微調整',fromHandoff:'スプライトラボの{n}フレーム'}},
 tool:{hand:'手のひら',handHint:'ドラッグで移動。どのツールでも Space+ドラッグで移動できます',zoom:'ズーム',zoomHint:'クリックでズームイン、Alt+クリックでズームアウト',select:'選択',selectHint:'クリック、Shift+クリック、ハンドルのドラッグでサイズ変更',frame:'フレーム',frameHint:'空いている場所をドラッグしてフレームを追加'},
 toolbar:{label:'ツール'},
 menu:{bar:'メインメニュー',more:'メニュー',file:'ファイル',edit:'編集',view:'表示',zoomLevels:'倍率',background:'背景',wheel:'マウスホイール',theme:'テーマ',workspace:'ワークスペース',help:'ヘルプ',language:'言語',frames:'フレーム'},
 ws:{viewer:'ビューア',viewerSummary:'読み込み、表示、フレームの切り出し',sprite:'スプライト',spriteSummary:'タイムライン、タグ、ピボット・当たり判定、パッキングとエンジン書き出し',pixel:'ピクセル',pixelSummary:'鉛筆、パレット、クリーンアップツール',tile:'タイル',tileSummary:'タイルセット、オートタイルのルール、マップペインター',texture:'テクスチャ',textureSummary:'法線マップ、チャンネル、ライトのプレビュー',ui:'UI',uiSummary:'9スライス、ボタンの状態、ビットマップフォント',coming:'{name} ワークスペースは {phase} で提供予定：{what}。',comingShort:'準備中（{phase}）'},
 panel:{assets:'アセット',history:'作業履歴',grid:'グリッド',frame:'フレーム情報',frames:'フレーム',toBottom:'下パネルへ移動',toRight:'右パネルへ移動',up:'上へ',down:'下へ',expand:'展開',collapse:'折りたたむ',resetLayout:'配置をリセット',hideBottom:'下パネルを隠す',showBottom:'下パネルを表示',options:'{name} パネルのオプション',all:'パネル'},
 assets:{empty:'まだ画像がありません。PNG、JPG、WebP、GIF をどこにでもドロップしてください。',remove:'{name} を削除',frames:'{n}フレーム'},
 history:{start:'プロジェクトを開いた'},
 group:{file:'ファイル',edit:'編集',view:'表示',tools:'ツール',frames:'フレーム',navigate:'移動',app:'スタジオ',help:'ヘルプ',workspace:'ワークスペース',other:'その他',pointer:'マウス、ペン、タッチ'},
 keys:{title:'キーボードショートカット',wheel:'カーソル位置でズーム（マウスホイール）',wheelKey:'ホイール',ctrlWheel:'カーソル位置でズーム（すべてのホイール・トラックパッド）',spaceDrag:'画面の移動',drag:'ドラッグ',middleDrag:'画面の移動',middle:'中ボタンでドラッグ',pinch:'ズームと移動（タッチ、トラックパッド）',pinchKey:'2本指のピンチ／スクロール',shiftClick:'選択に追加・選択から除外',click:'クリック',escDrag:'ドラッグ中の操作を取り消す'},
 palette:{placeholder:'コマンドを入力…',title:'コマンドパレット',none:'一致するコマンドがありません。'},
 about:{title:'Nerulio スタジオについて',body:'2Dゲームアセットのためのブラウザアプリです。画像はこの端末内だけで処理され、プロジェクトはこのブラウザに自動保存され、.nerulio ファイルとして保存できます。',renderer:'レンダラー：{r}{why}',dpr:'デバイスピクセル比：{dpr}（倍率は画面のピクセル基準なので、ピクセルは常に正方形でくっきり表示されます）',memory:'メモリ内の画像：{n}枚（保存 {stored}、デコード {decoded}）',local:'アップロードなし：このアプリはファイルをどこにも送信しません。',rendererShort:'キャンバスのレンダラー'},
 versions:{none:'このブラウザにはまだ自動保存の履歴がありません。',title:'自動保存の履歴',hint:'プロジェクトごとに直近10件の自動保存をこのブラウザに保持します。画像はすべての履歴で1回だけ保存されます。',meta:'画像{assets}枚 · {frames}フレーム'},
 empty:{import:'画像を読み込む…',open:'プロジェクトを開く…',keys:'キーボードショートカット',title:'画像や .nerulio プロジェクトをどこにでもドロップ',formats:'PNG · JPG · WebP · GIF（最初のフレーム）· 複数まとめて',local:'アップロードなし'},
 canvas:{label:'キャンバス。ホイールでズーム、Space か中ボタンのドラッグで移動、矢印キーで選択を微調整します。'},
 drop:{hint:'ドロップで画像を読み込み · .nerulio はプロジェクトとして開きます'},
 recover:{title:'前回の作業を復元しますか？',body:'「{name}」は {time} に自動保存されました：画像{assets}枚、{frames}フレーム。',hint:'新しく始めても ファイル › 自動保存の履歴 に残ります。',discard:'新しく始める',restore:'復元'},
 grid:{noImage:'フレームを切り出すには画像を読み込んでください。',detecting:'グリッドを探しています…',detectFailed:'グリッドの提案に失敗：{reason}',noSuggestion:'はっきりしたグリッドが見つかりません。セルサイズを入力してください。',transparent:'画像が完全に透明で、測れるものがありません。',cells:'{c}×{r}セル',margin:'余白 {v}',gap:'間隔 {v}',
  conf:{high:'高',medium:'中',low:'低'},why:'根拠',w:'W',h:'H',ox:'オフセット X',oy:'オフセット Y',sx:'間隔 X',sy:'間隔 Y',show:'キャンバスにグリッドを表示',skipEmpty:'空のセルを飛ばす',replace:'グリッドでフレームを置き換え',apply:'グリッドをフレームとして適用',detect:'もう一度提案',
  stateApplied:'適用済み：このグリッドで{n}フレームを切り出しました。',statePreview:'プレビューのみで、まだ適用されていません。キャンバスで確認してから適用してください。',stateNone:'まだグリッドがありません。',suggested:'提案されたグリッド',cellTitle:'セルグリッド',countPending:'{c}×{r} = {n}セル',tooMany:'{n}セルはフレームとして多すぎます。セルを大きくしてください。',count:'{c}×{r} = {n}セル · ピクセルのあるセル {filled}',noCells:'この設定ではすべてのセルが空です。',
  reason:{separator:'間隔の線{n}本のうち{pct}が完全に透明',noSeparator:'セルが隙間なく並んでいるため、確認できる間隔の線がない',period:'内容が{px}×{py}pxごとに繰り返す（自己相関 {ax} / {ay}）',bounds:'各セル内の内容の位置が似ている（{pct}）',cross:'内容がセルの境界を{n}か所で越えている',noCross:'セルの境界を越える内容はない',split:'セル内で空の行が内容を分けている — セルが大きすぎる可能性',uncommon:'一般的でないセルサイズのため、より強い根拠が必要だった',outside:'不透明なピクセル{n}個がセルの外にある',filled:'{cells}セル中{filled}セルにピクセルがある'}},
 frame:{noImage:'画像が開かれていません。',hint:'フレームをクリックして選択（{v}）。ハンドルのドラッグでサイズ変更、矢印キーで微調整。',none:'まだフレームがありません。グリッドを適用するか、フレームツール（{m}）で描いてください。',deleteN:'{n}フレームを削除',multi:'{n}フレームを選択 · 範囲 {x}, {y}, {w}×{h}',name:'名前',x:'X',y:'Y',w:'W',h:'H',index:'{n}フレーム中 {i}番'},
 strip:{empty:'グリッドを適用するかフレームを描くと、ここに表示されます。',more:'ほか{n}件'}
}};
export function st(locale,key,vars={}){
 const get=o=>key.split('.').reduce((a,k)=>a?.[k],o);
 const v=get(S[locale]||S.en)??get(S.en)??key;
 return String(v).replace(/\{(\w+)\}/g,(_,k)=>vars[k]??'');
}
export const STUDIO_STRINGS=S;
