/** Tile workspace copy (ko/en/ja), merged into the Studio strings under `tile` (and `group.tile`)
 * so st() finds it; tests/studio-tile.test.mjs checks key and placeholder parity. */
import {STUDIO_STRINGS} from '../../strings.js';
const src={'rpgmaker-a2':0,blobsmith:1,'rpgmaker-a4-wall':2,five:3,rim:4,'rpgmaker-a4':5};
const pick=(o,a)=>Object.fromEntries(Object.keys(o).map((k,i)=>[k,a[i]]));
export const TILE_STRINGS={
en:{
 menu:'Tile',noImage:'Open a tileset image to start (File › Import, or drop a PNG).',needTileset:'Set up this image as a tileset first (Tileset panel).',notTerrain:'no terrain',tiles:'tiles',
 panel:{set:'Tileset',layout:'Layout & bits',tile:'Tile',map:'Test map',gen:'Generator',export:'Export',check:'Check'},
 tool:{select:'Select tiles',selectHint:'click or drag a rectangle; Shift adds',bits:'Paint bits',bitsHint:'click or drag over the 9 zones of a tile; right-click or Alt clears',brush:'Terrain brush',brushHint:'paint terrain on the test map; right-click erases',eraser:'Eraser',eraserHint:'erase terrain from the test map',bucket:'Fill',bucketHint:'fill a connected area with the terrain',picker:'Pick terrain',pickerHint:'click a cell to paint with its terrain'},
 mode:{'corners-and-sides':'Corners and sides (47 blob)',sides:'Sides only (16 / 3×3)',corners:'Corners only (16 / dual grid)'},
 modeHelp:{'corners-and-sides':'Each tile says what it expects on all 8 neighbours. Godot: Match Corners and Sides · Tiled: mixed Wang set.','sides':'Only the 4 sides count. Godot: Match Sides · Tiled: edge Wang set.','corners':'Only the 4 corners count; on a dual grid the tiles sit on grid points. Godot: Match Corners · Tiled: corner Wang set.'},
 zone:{c:'centre'},
 status:{sel:'{n} tile(s) selected',tile:'tile {c},{r} · {what} · zone {zone}',cell:'cell {x},{y} · tile {tile} {what} {problem}'},
 set:{setup:'Set up as a tileset',lead:'Measured from the pixels. Nothing is applied until you press “Use this grid”.',noGrid:'No clear grid. Type the tile size below.',fits:'{layout} fits exactly',pick:'Pick a suggestion or type the tile size.',count:'{c}×{r} = {n} tiles',apply:'Use this grid',this:'This tileset',name:'Name',summary:'{w}×{h} px tiles · {c}×{r} grid · {n} with bits · {blank} blank · margin {m} · spacing {s}',mode:'Match mode',regrid:'Change grid…',list:'Tilesets in this project ({n})'},
 terrain:{title:'Terrains',use:'Paint with this terrain',color:'Colour',name:'Terrain name',remove:'Remove terrain',add:'Add terrain',hint:'[ and ] switch terrain. Several terrains in one set give transitions (grass → sand → water).',next:'Next terrain',prev:'Previous terrain'},
 layout:{found:'Recognised layout',running:'Comparing the sheet with every known layout…',tooMany:'This sheet has too many tiles to compare as a whole; blocks on the layout grid were checked.',useHint:'Assemble from this block',bySize:'by sheet size',none:'No known layout fits. Paint the bits, or let the pixels suggest them.',meta:'seam score {score}% · at {col},{row} · {cells} cells · {missing} missing · {extra} extra',blocks:'{n} blocks, {t} terrains',unsure:'Not sure: compare the preview with the art before applying.',previewLayout:'Preview: {name} on {n} tiles. Not applied yet.',previewSuggest:'Preview: bits for {n} tiles read from the pixels (edge contrast {sep}%). Not applied yet.',apply:'Apply',discard:'Discard',rerun:'Identify again',other:'Other ways',template:'Fill from a template',templatePick:'Choose a layout…',templateHint:'Lays the layout’s bits onto the sheet starting at the first selected tile (or the top-left). You see a preview first.',suggest:'Suggest bits from pixels',suggesting:'Reading the pixels…',suggestHint:'Select the full interior tile first for the best result; otherwise the Studio picks the reference that explains the seams best.',notMeasurable:{'no-full-tile':'No interior tile to compare with: select one and try again.','sides-look-alike':'Open and connected sides look the same in this art, so the pixels cannot tell. Paint the bits.',x:'The pixels cannot tell here. Paint the bits.'}},
 tile:{none:'Select a tile ({v}) or paint bits directly ({b}).',bits:'Peering bits',one:'Tile {c},{r}',many:'{n} tiles',help:'Click a square to set it to the active terrain; click again or Alt+click to clear. Applies to every selected tile.',prob:'Probability',full:'Full',clear:'Clear',rotate:'Rotate',mirror:'Mirror',copy:'Copy bits',paste:'Paste bits'},
 check:{empty:'No tile has bits yet: nothing can be checked.',have:'{a}/{b} combinations',missing:'{n} combination(s) have no tile: the engine will substitute another tile or leave the cell empty.',allPatterns:'Every combination has a tile.',dupes:'{n} combination(s) have more than one tile',dupesHint:'Engines pick among duplicates at random (by probability). Fine for variants, a mistake otherwise.',invalid:'{n} tile(s) have a corner bit behind an open side (no map ever asks for that).',art:'Art vs bits',artRunning:'Comparing each tile’s edges with its bits…',artNot:{'no-full-tile':'Not measured: no tile is marked as full interior.','connected-and-open-look-alike':'Not measured: open and connected edges look alike in this art.',x:'Not measured.'},artBad:'{n} tile(s) are drawn differently from what their bits say (✗ should connect, ○ should be open):',artOk:'Every edge matches its bits (separation {auc}%).',verdictOk:'Complete: every combination has one tile and the art agrees with the bits.',verdictOpen:'Not complete yet — see below.'},
 map:{title:'Test map',none:'No test map yet.',intro:'Paint terrain on a small map and see which tile the engine picks for every cell — before you open the engine.',needSet:'Set up a tileset first.',new:'New test map',defaultName:'Map {n}',w:'W',h:'H',rule:'Engine rule',layers:'Layers',visible:'Show layer',layerTileset:'Tileset of this layer',layerNoSet:'This layer has no tileset.',addLayer:'Add layer',removeLayer:'Remove layer',brush:'Brush',showCells:'Show painted terrain',random:'Random',clear:'Clear layer',showSheet:'Back to the sheet',showMap:'Show the test map',remove:'Delete map',paletteHint:'P brush · E eraser · G fill · I pick · Shift+[ ] brush size',paintFirst:'Paint some terrain on the map.',ok:'All {n} painted cells get a correct tile ({rule}).',bad:'{w} cell(s) get a substituted tile, {m} cell(s) stay empty ({rule}).',bigger:'Bigger brush',smaller:'Smaller brush',ruleHelp:{godot:'Exactly what Godot 4 draws: one set_cells_terrain_connect per terrain, row by row (checked against Godot 4.7.2 cell by cell).',tiled:'Tiled’s terrain brush: a tile whose Wang colours match exactly; corner sets sit on grid points.'}},
 rule:{godot:'Godot 4',tiled:'Tiled'},
 problem:{missing:'empty (no tile fits)',wrong:'substituted tile',gap:'no exact Wang tile'},
 source:pick(src,['RPG Maker A2 block (2×3)','Blobsmith base (2×3)','RPG Maker A4 wall (2×2)','Five tiles (1×5)','One tile + rim','RPG Maker A4 sheet']),
 gen:{title:'Generate a full set',lead:'Draw a few pieces, get the whole set, pixel for pixel. The result is a new image that stays linked to its source.',kind:'Source',kindHelp:{'rpgmaker-a2':'{w}×{h} tiles: top-left preview, top-right the four inner corners, bottom 2×2 a box (corners, edges, centre).','blobsmith':'{w}×{h} tiles like A2 with the top two swapped: inner corners top-left.','rpgmaker-a4-wall':'{w}×{h} tiles: a box whose corners and edges give 16 side-only tiles.','five':'{w}×{h} tiles in a row: isolated, full, inner corners (all four sides), horizontal strip, vertical strip.','rim':'The selected full tile; every open side gets a rim.'},useSelection:'Use selection as the source block',pickFirst:'Select the top-left tile of the source block first.',origin:'Source block: {w}×{h} tiles from {c},{r}.',originBad:'A {w}×{h} block from {c},{r} does not fit on the sheet.',noOrigin:'Select the top-left tile of a {w}×{h} block.',rimWidth:'Rim px',rimColor:'Rim colour',dual:'Dual-grid set (16 corner tiles) instead of 47',layout:'Output layout',bg:'Transition over terrain B:',bgTile:'tile {c},{r}',bgNone:'none (transparent)',bgUse:'Use selected tile as B',bgPick:'Select exactly one tile (terrain B’s full tile).',bgClear:'No B',go:'Generate',busy:'Generating…',sourceSet:'{kind}: pick the block and press Generate.',needSet:'Open a tileset (or set one up) to use it as a source.',linked:'Generated set',linkedFrom:'From {name} ({kind}).',stale:'The source changed since this set was made.',fresh:'Up to date with its source.',openSource:'Open the source',regen:'Regenerate',editTitle:'Edit the source',editHint:'Draw on the source: every generated tile that uses that quarter updates. Alt/right-click picks a colour.',colour:'Colour',uses:'This quarter is used by {n} generated tile(s).',sourceGone:'The source image is no longer in the project.'},
 export:{title:'Export',na:'n/a',verified:'verified',unverified:'unverified',t:{godot:'Godot 4 TileSet (terrains + peering bits)',tiled:'Tiled .tsx Wang set + sample .tmx',ldtk:'LDtk project (IntGrid + auto-layer rules)',unity:'Unity Rule Tiles (2D Tilemap Extras)',generic:'PNG + JSON (generic)'},collision:'Collision (Godot)',col:{none:'None',box:'Box',rects:'Exact rectangles',outline:'Outline polygon'},colHelp:'From the tile’s alpha; written as a Godot physics layer.',sample:'Sample maps use the active test map when it uses this tileset.',go:'Download ZIP ({n} tiles)',local:'Made in your browser; nothing is uploaded.',nothing:'Choose at least one target.'},
 cmd:{bits:'Paint bits',fill:'Fill terrain',erase:'Erase terrain',paint:'Paint terrain',rename:'Rename tileset',mode:'Change match mode',removeTs:'Remove tileset',terrain:'Edit terrains',makeTs:'Set up tileset ({w}×{h})',applyLayout:'Apply {name}',applySuggest:'Apply suggested bits ({n})',prob:'Tile probability',newMap:'New test map',pickMap:'Switch map',resize:'Resize map',rule:'Engine rule',layer:'Edit layers',random:'Random terrain',clearMap:'Clear layer',removeMap:'Delete map',generate:'Generate {n} tiles',regen:'Regenerate set',editSource:'Edit source pixels'},
 toast:{tileset:'Tileset ready: {n} tiles. Looking for its layout…',applied:'Applied. Undo brings the previous bits back.',copied:'Copied {what}',generated:'Generated {n} tiles into {name}',exported:'Exported {n} target(s).'}
},
ko:{
 menu:'타일',noImage:'타일셋 이미지를 열어 시작하세요 (파일 › 가져오기, 또는 PNG를 끌어다 놓기).',needTileset:'먼저 이 이미지를 타일셋으로 설정하세요 (타일셋 패널).',notTerrain:'지형 없음',tiles:'타일',
 panel:{set:'타일셋',layout:'레이아웃·비트',tile:'타일',map:'테스트 맵',gen:'생성기',export:'내보내기',check:'검사'},
 tool:{select:'타일 선택',selectHint:'클릭하거나 사각형으로 드래그, Shift로 추가',bits:'비트 칠하기',bitsHint:'타일의 9개 구역을 클릭하거나 드래그, 오른쪽 클릭 또는 Alt로 지우기',brush:'지형 브러시',brushHint:'테스트 맵에 지형을 칠하기, 오른쪽 클릭으로 지우기',eraser:'지우개',eraserHint:'테스트 맵에서 지형 지우기',bucket:'채우기',bucketHint:'이어진 영역을 지형으로 채우기',picker:'지형 고르기',pickerHint:'칸을 클릭해 그 지형으로 칠하기'},
 mode:{'corners-and-sides':'모서리와 변 (47 블롭)',sides:'변만 (16 / 3×3)',corners:'모서리만 (16 / 듀얼 그리드)'},
 modeHelp:{'corners-and-sides':'각 타일이 이웃 8칸 모두에 무엇을 기대하는지 적습니다. Godot: Match Corners and Sides · Tiled: mixed 왕 세트.','sides':'4개의 변만 셉니다. Godot: Match Sides · Tiled: edge 왕 세트.','corners':'4개의 모서리만 셉니다. 듀얼 그리드에서는 타일이 격자점에 놓입니다. Godot: Match Corners · Tiled: corner 왕 세트.'},
 zone:{c:'가운데'},
 status:{sel:'타일 {n}개 선택',tile:'타일 {c},{r} · {what} · 구역 {zone}',cell:'칸 {x},{y} · 타일 {tile} {what} {problem}'},
 set:{setup:'타일셋으로 설정',lead:'픽셀에서 측정했습니다. “이 격자 사용”을 누르기 전에는 아무것도 적용되지 않습니다.',noGrid:'뚜렷한 격자가 없습니다. 아래에 타일 크기를 입력하세요.',fits:'{layout}이(가) 정확히 맞음',pick:'제안을 고르거나 타일 크기를 입력하세요.',count:'{c}×{r} = 타일 {n}개',apply:'이 격자 사용',this:'이 타일셋',name:'이름',summary:'{w}×{h}px 타일 · {c}×{r} 격자 · 비트 있음 {n} · 빈 칸 {blank} · 여백 {m} · 간격 {s}',mode:'매칭 방식',regrid:'격자 바꾸기…',list:'이 프로젝트의 타일셋 ({n})'},
 terrain:{title:'지형',use:'이 지형으로 칠하기',color:'색',name:'지형 이름',remove:'지형 삭제',add:'지형 추가',hint:'[ 와 ] 로 지형을 바꿉니다. 한 세트에 지형이 여럿이면 전환 타일(풀 → 모래 → 물)이 됩니다.',next:'다음 지형',prev:'이전 지형'},
 layout:{found:'인식한 레이아웃',running:'알려진 모든 레이아웃과 시트를 비교하는 중…',tooMany:'타일이 너무 많아 시트 전체를 비교하지 않았습니다. 레이아웃 격자 위의 블록을 확인했습니다.',useHint:'이 블록으로 조립',bySize:'시트 크기로 판단',none:'맞는 레이아웃이 없습니다. 비트를 칠하거나 픽셀에서 제안을 받으세요.',meta:'이음새 점수 {score}% · 위치 {col},{row} · {cells}칸 · 빠짐 {missing} · 남음 {extra}',blocks:'블록 {n}개, 지형 {t}개',unsure:'확실하지 않습니다. 적용하기 전에 미리보기를 그림과 비교하세요.',previewLayout:'미리보기: 타일 {n}개에 {name}. 아직 적용하지 않았습니다.',previewSuggest:'미리보기: 픽셀에서 읽은 타일 {n}개의 비트 (가장자리 대비 {sep}%). 아직 적용하지 않았습니다.',apply:'적용',discard:'버리기',rerun:'다시 인식',other:'다른 방법',template:'템플릿으로 채우기',templatePick:'레이아웃 선택…',templateHint:'첫 번째 선택 타일(또는 왼쪽 위)부터 레이아웃의 비트를 시트에 놓습니다. 먼저 미리보기가 보입니다.',suggest:'픽셀에서 비트 제안',suggesting:'픽셀을 읽는 중…',suggestHint:'가장 좋은 결과를 위해 먼저 속이 꽉 찬 타일을 선택하세요. 선택하지 않으면 이음새를 가장 잘 설명하는 기준 타일을 고릅니다.',notMeasurable:{'no-full-tile':'비교할 속 타일이 없습니다. 하나를 선택하고 다시 시도하세요.','sides-look-alike':'이 그림에서는 열린 변과 이어진 변이 똑같아 보여 픽셀로 구분할 수 없습니다. 비트를 칠하세요.',x:'여기서는 픽셀로 판단할 수 없습니다. 비트를 칠하세요.'}},
 tile:{none:'타일을 선택하거나({v}) 바로 비트를 칠하세요({b}).',bits:'피어링 비트',one:'타일 {c},{r}',many:'타일 {n}개',help:'칸을 클릭하면 현재 지형으로, 다시 클릭하거나 Alt+클릭하면 지워집니다. 선택한 모든 타일에 적용됩니다.',prob:'확률',full:'가득',clear:'지우기',rotate:'회전',mirror:'뒤집기',copy:'비트 복사',paste:'비트 붙여넣기'},
 check:{empty:'비트가 있는 타일이 없어 검사할 것이 없습니다.',have:'조합 {a}/{b}',missing:'조합 {n}개에 타일이 없습니다. 엔진은 다른 타일로 대신하거나 칸을 비워 둡니다.',allPatterns:'모든 조합에 타일이 있습니다.',dupes:'조합 {n}개에 타일이 둘 이상 있습니다',dupesHint:'엔진은 중복 타일 중 하나를 (확률에 따라) 무작위로 고릅니다. 변형이라면 괜찮지만 아니라면 실수입니다.',invalid:'타일 {n}개에 열린 변 뒤의 모서리 비트가 있습니다 (어떤 맵도 요구하지 않음).',art:'그림과 비트',artRunning:'각 타일의 가장자리를 비트와 비교하는 중…',artNot:{'no-full-tile':'측정 안 함: 속이 꽉 찬 타일로 표시된 것이 없습니다.','connected-and-open-look-alike':'측정 안 함: 이 그림에서는 열린 가장자리와 이어진 가장자리가 비슷해 보입니다.',x:'측정 안 함.'},artBad:'타일 {n}개가 비트와 다르게 그려져 있습니다 (✗ 이어져야 함, ○ 열려야 함):',artOk:'모든 가장자리가 비트와 맞습니다 (구분도 {auc}%).',verdictOk:'완성: 모든 조합에 타일이 하나씩 있고 그림이 비트와 일치합니다.',verdictOpen:'아직 완성되지 않았습니다 — 아래를 보세요.'},
 map:{title:'테스트 맵',none:'테스트 맵이 없습니다.',intro:'작은 맵에 지형을 칠하고, 엔진을 열기 전에 각 칸에 엔진이 어떤 타일을 고르는지 확인하세요.',needSet:'먼저 타일셋을 설정하세요.',new:'새 테스트 맵',defaultName:'맵 {n}',w:'가로',h:'세로',rule:'엔진 규칙',layers:'레이어',visible:'레이어 표시',layerTileset:'이 레이어의 타일셋',layerNoSet:'이 레이어에 타일셋이 없습니다.',addLayer:'레이어 추가',removeLayer:'레이어 삭제',brush:'브러시',showCells:'칠한 지형 표시',random:'무작위',clear:'레이어 비우기',showSheet:'시트로 돌아가기',showMap:'테스트 맵 보기',remove:'맵 삭제',paletteHint:'P 브러시 · E 지우개 · G 채우기 · I 고르기 · Shift+[ ] 브러시 크기',paintFirst:'맵에 지형을 칠해 보세요.',ok:'칠한 {n}칸 모두 올바른 타일을 받습니다 ({rule}).',bad:'{w}칸은 대신한 타일, {m}칸은 비어 있습니다 ({rule}).',bigger:'브러시 크게',smaller:'브러시 작게',ruleHelp:{godot:'Godot 4가 그리는 그대로입니다: 지형마다 set_cells_terrain_connect를 한 번씩, 행 순서로 (Godot 4.7.2와 칸 단위로 대조함).',tiled:'Tiled의 지형 브러시: 왕 색이 정확히 맞는 타일. 모서리 세트는 격자점에 놓입니다.'}},
 rule:{godot:'Godot 4',tiled:'Tiled'},
 problem:{missing:'비어 있음 (맞는 타일 없음)',wrong:'대신한 타일',gap:'정확한 왕 타일 없음'},
 source:pick(src,['RPG 만들기 A2 블록 (2×3)','Blobsmith 기본 (2×3)','RPG 만들기 A4 벽 (2×2)','타일 5개 (1×5)','타일 1개 + 테두리','RPG 만들기 A4 시트']),
 gen:{title:'전체 세트 생성',lead:'몇 조각만 그리면 전체 세트가 픽셀 그대로 만들어집니다. 결과는 원본과 연결된 새 이미지입니다.',kind:'원본',kindHelp:{'rpgmaker-a2':'{w}×{h} 타일: 왼쪽 위 미리보기, 오른쪽 위 안쪽 모서리 4개, 아래 2×2 상자(모서리, 변, 가운데).','blobsmith':'A2처럼 {w}×{h} 타일이지만 위 두 칸이 바뀜: 안쪽 모서리가 왼쪽 위.','rpgmaker-a4-wall':'{w}×{h} 타일: 상자의 모서리와 변으로 변 전용 타일 16개.','five':'한 줄에 {w}×{h} 타일: 외톨이, 가득, 안쪽 모서리(네 변 모두), 가로 띠, 세로 띠.','rim':'선택한 가득 찬 타일. 열린 변마다 테두리가 생깁니다.'},useSelection:'선택을 원본 블록으로 사용',pickFirst:'먼저 원본 블록의 왼쪽 위 타일을 선택하세요.',origin:'원본 블록: {c},{r}부터 {w}×{h} 타일.',originBad:'{c},{r}부터 {w}×{h} 블록은 시트를 벗어납니다.',noOrigin:'{w}×{h} 블록의 왼쪽 위 타일을 선택하세요.',rimWidth:'테두리 px',rimColor:'테두리 색',dual:'47개 대신 듀얼 그리드 세트 (모서리 타일 16개)',layout:'출력 레이아웃',bg:'지형 B 위의 전환:',bgTile:'타일 {c},{r}',bgNone:'없음 (투명)',bgUse:'선택한 타일을 B로 사용',bgPick:'타일을 정확히 하나(지형 B의 가득 찬 타일) 선택하세요.',bgClear:'B 없음',go:'생성',busy:'생성 중…',sourceSet:'{kind}: 블록을 고르고 생성을 누르세요.',needSet:'원본으로 쓸 타일셋을 열거나 설정하세요.',linked:'생성된 세트',linkedFrom:'원본: {name} ({kind}).',stale:'이 세트를 만든 뒤 원본이 바뀌었습니다.',fresh:'원본과 일치합니다.',openSource:'원본 열기',regen:'다시 생성',editTitle:'원본 편집',editHint:'원본에 그리면 그 사분면을 쓰는 모든 생성 타일이 바뀝니다. Alt/오른쪽 클릭으로 색 고르기.',colour:'색',uses:'이 사분면은 생성 타일 {n}개에 쓰입니다.',sourceGone:'원본 이미지가 더 이상 프로젝트에 없습니다.'},
 export:{title:'내보내기',na:'해당 없음',verified:'검증됨',unverified:'미검증',t:{godot:'Godot 4 TileSet (지형 + 피어링 비트)',tiled:'Tiled .tsx 왕 세트 + 샘플 .tmx',ldtk:'LDtk 프로젝트 (IntGrid + 자동 레이어 규칙)',unity:'Unity 룰 타일 (2D Tilemap Extras)',generic:'PNG + JSON (범용)'},collision:'충돌 (Godot)',col:{none:'없음',box:'상자',rects:'정확한 사각형들',outline:'외곽선 다각형'},colHelp:'타일의 알파에서 만들어 Godot 물리 레이어로 씁니다.',sample:'샘플 맵은 이 타일셋을 쓰는 현재 테스트 맵을 사용합니다.',go:'ZIP 다운로드 (타일 {n}개)',local:'브라우저에서 만들어지며 아무것도 업로드되지 않습니다.',nothing:'대상을 하나 이상 고르세요.'},
 cmd:{bits:'비트 칠하기',fill:'지형 채우기',erase:'지형 지우기',paint:'지형 칠하기',rename:'타일셋 이름 바꾸기',mode:'매칭 방식 바꾸기',removeTs:'타일셋 제거',terrain:'지형 편집',makeTs:'타일셋 설정 ({w}×{h})',applyLayout:'{name} 적용',applySuggest:'제안된 비트 적용 ({n})',prob:'타일 확률',newMap:'새 테스트 맵',pickMap:'맵 바꾸기',resize:'맵 크기 바꾸기',rule:'엔진 규칙',layer:'레이어 편집',random:'무작위 지형',clearMap:'레이어 비우기',removeMap:'맵 삭제',generate:'타일 {n}개 생성',regen:'세트 다시 생성',editSource:'원본 픽셀 편집'},
 toast:{tileset:'타일셋 준비: 타일 {n}개. 레이아웃을 찾는 중…',applied:'적용했습니다. 실행 취소로 이전 비트를 되돌릴 수 있습니다.',copied:'{what} 복사',generated:'{name}에 타일 {n}개 생성',exported:'대상 {n}개 내보냄.'}
},
ja:{
 menu:'タイル',noImage:'タイルセット画像を開いて始めてください（ファイル › 読み込み、または PNG をドロップ）。',needTileset:'まずこの画像をタイルセットとして設定してください（タイルセットパネル）。',notTerrain:'地形なし',tiles:'タイル',
 panel:{set:'タイルセット',layout:'レイアウト・ビット',tile:'タイル',map:'テストマップ',gen:'ジェネレーター',export:'書き出し',check:'チェック'},
 tool:{select:'タイル選択',selectHint:'クリックまたは矩形ドラッグ、Shift で追加',bits:'ビットを塗る',bitsHint:'タイルの 9 区画をクリックまたはドラッグ、右クリックか Alt で消去',brush:'地形ブラシ',brushHint:'テストマップに地形を塗る、右クリックで消去',eraser:'消しゴム',eraserHint:'テストマップから地形を消す',bucket:'塗りつぶし',bucketHint:'つながった範囲を地形で塗る',picker:'地形を拾う',pickerHint:'セルをクリックしてその地形で塗る'},
 mode:{'corners-and-sides':'角と辺（47 ブロブ）',sides:'辺のみ（16 / 3×3）',corners:'角のみ（16 / デュアルグリッド）'},
 modeHelp:{'corners-and-sides':'各タイルが周囲 8 マスすべてに何を期待するかを持ちます。Godot: Match Corners and Sides · Tiled: mixed ワングセット。','sides':'4 辺だけを見ます。Godot: Match Sides · Tiled: edge ワングセット。','corners':'4 つの角だけを見ます。デュアルグリッドではタイルが格子点に置かれます。Godot: Match Corners · Tiled: corner ワングセット。'},
 zone:{c:'中央'},
 status:{sel:'{n} タイル選択中',tile:'タイル {c},{r} · {what} · 区画 {zone}',cell:'セル {x},{y} · タイル {tile} {what} {problem}'},
 set:{setup:'タイルセットとして設定',lead:'ピクセルから測定しました。「このグリッドを使う」を押すまで何も適用されません。',noGrid:'はっきりしたグリッドがありません。下にタイルサイズを入力してください。',fits:'{layout} がぴったり合う',pick:'候補を選ぶかタイルサイズを入力してください。',count:'{c}×{r} = {n} タイル',apply:'このグリッドを使う',this:'このタイルセット',name:'名前',summary:'{w}×{h}px タイル · {c}×{r} グリッド · ビットあり {n} · 空 {blank} · 余白 {m} · 間隔 {s}',mode:'マッチ方式',regrid:'グリッドを変更…',list:'このプロジェクトのタイルセット（{n}）'},
 terrain:{title:'地形',use:'この地形で塗る',color:'色',name:'地形名',remove:'地形を削除',add:'地形を追加',hint:'[ と ] で地形を切り替えます。1 つのセットに複数の地形があると遷移タイル（草 → 砂 → 水）になります。',next:'次の地形',prev:'前の地形'},
 layout:{found:'認識したレイアウト',running:'既知のすべてのレイアウトとシートを比較しています…',tooMany:'タイルが多すぎるためシート全体は比較していません。レイアウトグリッド上のブロックを確認しました。',useHint:'このブロックから組み立てる',bySize:'シートサイズで判断',none:'合う既知レイアウトがありません。ビットを塗るか、ピクセルから提案させてください。',meta:'継ぎ目スコア {score}% · 位置 {col},{row} · {cells} セル · 欠け {missing} · 余り {extra}',blocks:'{n} ブロック、{t} 地形',unsure:'確実ではありません。適用前にプレビューを絵と比べてください。',previewLayout:'プレビュー：{n} タイルに {name}。まだ適用していません。',previewSuggest:'プレビュー：ピクセルから読んだ {n} タイルのビット（縁のコントラスト {sep}%）。まだ適用していません。',apply:'適用',discard:'破棄',rerun:'再認識',other:'ほかの方法',template:'テンプレートで埋める',templatePick:'レイアウトを選択…',templateHint:'最初に選んだタイル（なければ左上）からレイアウトのビットをシートに置きます。まずプレビューが表示されます。',suggest:'ピクセルからビットを提案',suggesting:'ピクセルを読み取り中…',suggestHint:'最良の結果のため、先に中身の詰まったタイルを選んでください。選ばない場合は継ぎ目を最もよく説明する基準を選びます。',notMeasurable:{'no-full-tile':'比較する内側タイルがありません。1 つ選んでもう一度試してください。','sides-look-alike':'この絵では開いた辺とつながった辺が同じに見えるため、ピクセルでは判別できません。ビットを塗ってください。',x:'ここではピクセルで判断できません。ビットを塗ってください。'}},
 tile:{none:'タイルを選択（{v}）するか、直接ビットを塗って（{b}）ください。',bits:'ピアリングビット',one:'タイル {c},{r}',many:'{n} タイル',help:'マスをクリックすると現在の地形に、もう一度クリックか Alt+クリックで消えます。選択中のすべてのタイルに適用されます。',prob:'確率',full:'全面',clear:'消去',rotate:'回転',mirror:'反転',copy:'ビットをコピー',paste:'ビットを貼り付け'},
 check:{empty:'ビットのあるタイルがないため、チェックできるものがありません。',have:'組み合わせ {a}/{b}',missing:'{n} 個の組み合わせにタイルがありません。エンジンは別のタイルで代用するかセルを空にします。',allPatterns:'すべての組み合わせにタイルがあります。',dupes:'{n} 個の組み合わせに複数のタイルがあります',dupesHint:'エンジンは重複からランダム（確率順）に選びます。バリエーションなら問題ありませんが、そうでなければミスです。',invalid:'{n} タイルに、開いた辺の奥の角ビットがあります（どのマップも要求しません）。',art:'絵とビット',artRunning:'各タイルの縁をビットと比較しています…',artNot:{'no-full-tile':'未測定：内側全面のタイルがありません。','connected-and-open-look-alike':'未測定：この絵では開いた縁とつながった縁が似ています。',x:'未測定。'},artBad:'{n} タイルがビットと違って描かれています（✗ つながるべき、○ 開くべき）：',artOk:'すべての縁がビットと一致します（分離度 {auc}%）。',verdictOk:'完成：すべての組み合わせにタイルが 1 つずつあり、絵がビットと一致しています。',verdictOpen:'まだ完成していません — 下を見てください。'},
 map:{title:'テストマップ',none:'テストマップがまだありません。',intro:'小さなマップに地形を塗り、エンジンを開く前に各セルでエンジンが選ぶタイルを確認します。',needSet:'先にタイルセットを設定してください。',new:'新しいテストマップ',defaultName:'マップ {n}',w:'幅',h:'高さ',rule:'エンジンの規則',layers:'レイヤー',visible:'レイヤーを表示',layerTileset:'このレイヤーのタイルセット',layerNoSet:'このレイヤーにはタイルセットがありません。',addLayer:'レイヤーを追加',removeLayer:'レイヤーを削除',brush:'ブラシ',showCells:'塗った地形を表示',random:'ランダム',clear:'レイヤーを消去',showSheet:'シートに戻る',showMap:'テストマップを表示',remove:'マップを削除',paletteHint:'P ブラシ · E 消しゴム · G 塗りつぶし · I 拾う · Shift+[ ] ブラシサイズ',paintFirst:'マップに地形を塗ってください。',ok:'塗った {n} セルすべてが正しいタイルになります（{rule}）。',bad:'{w} セルは代用タイル、{m} セルは空のままです（{rule}）。',bigger:'ブラシを大きく',smaller:'ブラシを小さく',ruleHelp:{godot:'Godot 4 が描くとおりです：地形ごとに set_cells_terrain_connect を 1 回、行順に（Godot 4.7.2 とセル単位で照合済み）。',tiled:'Tiled の地形ブラシ：ワング色が完全一致するタイル。角セットは格子点に置かれます。'}},
 rule:{godot:'Godot 4',tiled:'Tiled'},
 problem:{missing:'空（合うタイルなし）',wrong:'代用タイル',gap:'完全一致のワングタイルなし'},
 source:pick(src,['RPG ツクール A2 ブロック（2×3）','Blobsmith ベース（2×3）','RPG ツクール A4 壁（2×2）','5 タイル（1×5）','1 タイル + 縁','RPG ツクール A4 シート']),
 gen:{title:'フルセットを生成',lead:'数個のパーツを描くだけで、セット全体がピクセル単位で作られます。結果は元とリンクした新しい画像です。',kind:'元',kindHelp:{'rpgmaker-a2':'{w}×{h} タイル：左上はプレビュー、右上は内角 4 つ、下の 2×2 は箱（角・辺・中央）。','blobsmith':'A2 と同じ {w}×{h} タイルで上の 2 つが入れ替わり：内角が左上。','rpgmaker-a4-wall':'{w}×{h} タイル：箱の角と辺から辺のみのタイル 16 個。','five':'1 列の {w}×{h} タイル：孤立、全面、内角（4 辺とも）、横の帯、縦の帯。','rim':'選択した全面タイル。開いた辺ごとに縁が付きます。'},useSelection:'選択を元ブロックにする',pickFirst:'先に元ブロックの左上タイルを選んでください。',origin:'元ブロック：{c},{r} から {w}×{h} タイル。',originBad:'{c},{r} からの {w}×{h} ブロックはシートからはみ出します。',noOrigin:'{w}×{h} ブロックの左上タイルを選んでください。',rimWidth:'縁 px',rimColor:'縁の色',dual:'47 の代わりにデュアルグリッドセット（角タイル 16）',layout:'出力レイアウト',bg:'地形 B の上の遷移：',bgTile:'タイル {c},{r}',bgNone:'なし（透明）',bgUse:'選択タイルを B にする',bgPick:'タイルを 1 つだけ（地形 B の全面タイル）選んでください。',bgClear:'B なし',go:'生成',busy:'生成中…',sourceSet:'{kind}：ブロックを選んで生成を押してください。',needSet:'元にするタイルセットを開くか設定してください。',linked:'生成したセット',linkedFrom:'元：{name}（{kind}）。',stale:'このセットを作った後に元が変わりました。',fresh:'元と一致しています。',openSource:'元を開く',regen:'再生成',editTitle:'元を編集',editHint:'元に描くと、その 4 分の 1 を使う生成タイルがすべて更新されます。Alt/右クリックで色を拾います。',colour:'色',uses:'この 4 分の 1 は生成タイル {n} 個で使われています。',sourceGone:'元の画像はもうプロジェクトにありません。'},
 export:{title:'書き出し',na:'対象外',verified:'検証済み',unverified:'未検証',t:{godot:'Godot 4 TileSet（地形 + ピアリングビット）',tiled:'Tiled .tsx ワングセット + サンプル .tmx',ldtk:'LDtk プロジェクト（IntGrid + オートレイヤー規則）',unity:'Unity ルールタイル（2D Tilemap Extras）',generic:'PNG + JSON（汎用）'},collision:'コリジョン（Godot）',col:{none:'なし',box:'ボックス',rects:'正確な矩形',outline:'外形ポリゴン'},colHelp:'タイルのアルファから作り、Godot の物理レイヤーとして書き出します。',sample:'サンプルマップは、このタイルセットを使う現在のテストマップを使います。',go:'ZIP をダウンロード（{n} タイル）',local:'ブラウザ内で作成し、何もアップロードしません。',nothing:'出力先を 1 つ以上選んでください。'},
 cmd:{bits:'ビットを塗る',fill:'地形で塗りつぶし',erase:'地形を消す',paint:'地形を塗る',rename:'タイルセット名を変更',mode:'マッチ方式を変更',removeTs:'タイルセットを削除',terrain:'地形を編集',makeTs:'タイルセットを設定（{w}×{h}）',applyLayout:'{name} を適用',applySuggest:'提案ビットを適用（{n}）',prob:'タイルの確率',newMap:'新しいテストマップ',pickMap:'マップを切り替え',resize:'マップサイズ変更',rule:'エンジンの規則',layer:'レイヤーを編集',random:'ランダム地形',clearMap:'レイヤーを消去',removeMap:'マップを削除',generate:'{n} タイルを生成',regen:'セットを再生成',editSource:'元のピクセルを編集'},
 toast:{tileset:'タイルセット準備完了：{n} タイル。レイアウトを探しています…',applied:'適用しました。元に戻すと前のビットに戻ります。',copied:'{what} をコピー',generated:'{name} に {n} タイルを生成',exported:'{n} 個の出力先を書き出しました。'}
}};
export const TILE_GROUP={en:'Tile',ko:'타일',ja:'タイル'};
for(const l of Object.keys(TILE_STRINGS)){if(!STUDIO_STRINGS[l])continue;STUDIO_STRINGS[l].tile=TILE_STRINGS[l];STUDIO_STRINGS[l].group={...(STUDIO_STRINGS[l].group||{}),tile:TILE_GROUP[l]};}
