// @ts-check
import {html} from './html.js';
import {page} from './ui.js';
import {icon} from './icons.js';
import DATA from '../../data/hardware/blender.js';
import {gpuPhoto} from '../hardware-photos.js';
import {MARKETS,marketOf,marketLinks} from '../../src/hardware/market.js';

/** @param {string} l @param {string} active */
export function hardwareToolLinks(l,active=''){
 const ko=l==='ko';
 return html`<nav class="mtabs hw-tabs" aria-label="${ko?'PC 도구':'PC tools'}">${[['used-prices',ko?'국가별 중고 시세':'Used prices'],['performance',ko?'GPU·CPU 성능 비교':'GPU / CPU comparison'],['',ko?'GPU 공식 스펙':'GPU specifications']].map(([id,name])=>html`<a href="/${l}/hardware/${id?id+'/':'?type=gpu'}"${id===active?html` class="on" aria-current="page"`:''}>${name}</a>`)}</nav>`;
}
/** @param {string} l @param {string} country */
function countryOptions(l,country){return MARKETS.map(m=>html`<option value="${m.id}"${m.id===country?html` selected`:''}>${l==='ko'?m.ko:m.en} · ${m.currency}</option>`);}
/** @param {any} o @param {string} title @param {string} description @param {unknown} body */
function shell(o,title,description,body){
 const base=`/${o.l}/hardware/${o.tool}/`,ko=o.l==='ko';
 return page({l:o.l,title:title+' | Nerulio',description,canonical:o.origin+base,alternates:{ko:o.origin+`/ko/hardware/${o.tool}/`,en:o.origin+`/en/hardware/${o.tool}/`},noindex:!!o.query,channels:o.channels,
  body:html`<div class="hw-tool"><header class="box chh hw-heading"><span class="tile t-hw" aria-hidden="true">${icon('chip',22)}</span><div class="chm"><div class="chn1"><h1>${title}</h1></div><p class="hw-lead">${description}</p></div><div class="cha"><a class="btn" href="/${o.l}/community/hw/">${ko?'PC·하드웨어 채널':'PC community'} ›</a></div></header>${hardwareToolLinks(o.l,o.tool)}${body}</div>`});
}
/** @param {ReturnType<typeof gpuPhoto>} p @param {boolean} ko */
function photo(p,ko){return p?html`<figure class="hw-photo"><img src="${p.src}" width="960" height="${p.src.endsWith('rx-6600-xt.jpg')||p.src.endsWith('arc-a770.jpg')?720:540}" alt="${p.board}${ko?' 실물':' graphics card'}" decoding="async"><figcaption>${p.board}</figcaption></figure>`:'';}
/** @param {ReturnType<typeof gpuPhoto>[]} photos @param {boolean} ko */
function photoCredits(photos,ko){
 const unique=[...new Set(photos.filter(Boolean))];
 return unique.length?html`<details class="hw-details hw-credits"><summary>${ko?'사진 출처·라이선스':'Photo credits & licenses'}</summary><ul>${unique.map(p=>p&&html`<li>${p.board} — <a href="${p.source}" target="_blank" rel="noopener noreferrer">${p.author}</a> · <a href="${p.licenseUrl}" target="_blank" rel="noopener noreferrer">${p.license}</a>${p.original?html` · <a href="${p.original}" target="_blank" rel="noopener noreferrer">${ko?'원본 영상':'Original video'}</a>`:''}</li>`)}</ul><p>${ko?'Wikimedia 축소본 사용, 추가 편집 없음. 실물 제품의 외형 예시이며 측정에 사용된 개별 장치 사진은 아닙니다. 같은 GPU라도 제조사·쿨러·메모리 구성은 다를 수 있습니다.':'Wikimedia thumbnails, no further edits. Retail-board examples, not photographs of individual benchmark submissions. Board maker, cooler and memory configuration may vary.'}</p></details>`:'';
}
/** @param {boolean} ko */
function priceGuide(ko){return html`<section class="box hw-section"><h2>${ko?'비교할 매물 고르기':'Choose comparable listings'}</h2><ul class="hw-guide"><li>${ko?'모델명과 메모리 용량이 같은 제품':'Same model and memory capacity'}</li><li>${ko?'상태·배송비 포함 기준 통일':'Consistent condition and shipping basis'}</li><li>${ko?'완본체·부품용·박스만·중복 제외':'Exclude full PCs, broken parts, boxes and duplicates'}</li></ul><details class="hw-details"><summary>${ko?'호가와 실거래가의 차이':'Asking vs. sale prices'}</summary><p>${ko?'호가는 실거래가가 아닙니다. 판매 완료 표시 가격도 할인 협상 등으로 최종 결제액과 다를 수 있습니다. 국가 선택은 현지 사이트·통화 기준이며 판매자의 실제 위치는 매물에서 확인하세요.':'Asking prices are not sale prices. Sold displayed prices may differ from final negotiated payments. Country selects the local site and currency; check seller location in each listing.'}</p></details></section>`;}
/** @param {{l:string,origin:string,tool:string,query:string,q:URLSearchParams,channels:any[]}} o */
export function renderUsedPrices(o){
 const ko=o.l==='ko',m=marketOf(o.q.get('country')||(ko?'KR':'US')),q=o.q.get('q')||'',links=marketLinks(m.id,q),p=gpuPhoto(q);
 const kind=(/** @type {string} */ k)=>ko?({asking:'판매 중 · 호가',sold:'판매 완료 · 표시 가격',mixed:'판매 중·완료 필터 확인'}[k]||k):({asking:'Active · asking',sold:'Sold · displayed',mixed:'Check active / sold filters'}[k]||k);
 return shell(o,ko?'국가별 중고 시세':'Used prices by country',ko?'현지 장터에서 같은 조건의 가격을 확인하고, 중앙값과 가격 범위를 비교하세요.':'Check comparable prices on local marketplaces, then compare their median and range.',html`
 <div class="cols hw-layout"><main class="mainc"><section class="box hw-section"><h2>${ko?'국가·모델 검색':'Country & model'}</h2><form method="get" class="hw-form"><label>${ko?'국가 · 통화':'Country · currency'}<select name="country">${countryOptions(o.l,m.id)}</select></label><label class="hw-wide">${ko?'부품 모델명':'Hardware model'}<input name="q" type="search" maxlength="80" required value="${q}" placeholder="RTX 4060 8GB / Ryzen 5 5600"></label><button class="btn p" type="submit">${ko?'검색':'Search'}</button></form>
 ${links.length?html`<div class="hw-market-links">${links.map(x=>html`<a href="${x.url}" target="_blank" rel="noopener noreferrer"><strong>${x.name} ↗</strong><span>${kind(x.kind)}</span></a>`)}</div>`:html`<p class="hw-help">${ko?'모델명을 입력하면 현지 중고장터 검색 링크가 나옵니다.':'Enter a model to open searches on local marketplaces.'}</p>`}
 <p class="hw-help">${ko?'시세 자동 수집 미연결 · 외부 장터 검색 후 확인한 가격을 아래에 입력하세요.':'Automatic feeds are not connected. Check external listings and enter their prices below.'}</p></section>
 <section class="box hw-section" data-island="used-prices" data-country="${m.id}"><h2>${ko?'확인한 가격으로 계산':'Calculate from checked prices'}</h2>
 <div class="hw-price-workspace"><form class="hw-price-form"><fieldset disabled data-hw-enable><div class="hw-form"><label>${ko?'가격 종류':'Price basis'}<select name="basis"><option value="asking">${ko?'판매 중 호가':'Active asking prices'}</option><option value="sold">${ko?'판매 완료 표시 가격':'Sold displayed prices'}</option></select></label><label>${ko?'상태':'Condition'}<select name="condition"><option>${ko?'정상 중고':'Working used'}</option><option>${ko?'미개봉':'Unopened'}</option><option>${ko?'리퍼':'Refurbished'}</option></select></label></div>
 <label class="hw-price-label">${ko?`가격 (${m.currency}) · 한 줄에 하나`:`Prices (${m.currency}) · one per line`}<textarea name="prices" rows="6" maxlength="8000" required placeholder="${m.id==='KR'?'200,000\n230,000\n250,000':m.id==='DE'||m.id==='FR'?'200,50\n230,50\n250,50':'200\n230\n250'}" aria-describedby="hw-price-help"></textarea></label>
 <p class="hw-help" id="hw-price-help">${ko?'최대 200개 · 입력한 가격은 저장하지 않습니다.':'Up to 200 entries · prices are not saved.'}</p><div class="hw-actions"><button class="btn p" type="submit">${ko?'시세 계산':'Calculate'}</button><button class="btn" type="reset">${ko?'초기화':'Clear'}</button></div></fieldset></form><div class="hw-price-output" data-price-result role="status" aria-live="polite"><h3>${ko?'계산 결과':'Results'}</h3><p class="hw-empty">${ko?'확인한 가격을 입력하면 중앙값·가격 범위·표본 수가 표시됩니다.':'Enter checked prices to see the median, range and sample count.'}</p></div></div>
 <noscript><p>${ko?'가격 계산에는 JavaScript가 필요합니다. 위 검색 링크는 그대로 사용할 수 있습니다.':'Enable JavaScript to calculate prices. Marketplace links above still work.'}</p></noscript>
 <details class="hw-details"><summary>${ko?'숫자 형식·계산 기준':'Number format & calculation'}</summary><p>${ko?'독일 1.234,50 / 프랑스 1 234,50 / 미국 1,234.50처럼 현지 숫자 형식을 사용하세요. 중앙값은 입력한 표본 기준이며 시장 전체의 확정 시세가 아닙니다. 중앙 50% 범위는 Q1–Q3입니다. 이상값을 자동 제외하지 않습니다.':'Use local separators: Germany 1.234,50 / France 1 234,50 / US 1,234.50. Statistics represent your inputs, not a definitive market price. The central 50% range is Q1–Q3. Outliers are not automatically removed.'}</p></details></section></main>
 <aside class="side">${p?html`<section class="box hw-section"><h2>${ko?'찾는 GPU':'GPU you searched for'}</h2>${photo(p,ko)}${photoCredits([p],ko)}</section>`:''}${priceGuide(ko)}<section class="box hw-section"><h2>${ko?'성능도 비교하기':'Compare performance'}</h2><p>${ko?'같은 Blender 버전의 렌더링 실측값과 구매 가격을 비교할 수 있습니다.':'Compare rendering measurements and value at your purchase prices.'}</p><a class="hw-text-link" href="/${o.l}/hardware/performance/?country=${m.id}">${ko?'GPU·CPU 성능 비교':'GPU / CPU comparison'} ›</a></section></aside></div>`);
}

/** @param {{l:string,origin:string,tool:string,query:string,q:URLSearchParams,channels:any[]}} o */
export function renderPerformance(o){
 const ko=o.l==='ko',type=o.q.get('type')==='cpu'?'cpu':'gpu',devices=DATA.devices.filter(d=>d.type===type),m=marketOf(o.q.get('country')||(ko?'KR':'US'));
 const defaults=type==='gpu'?['NVIDIA GeForce RTX 3060','NVIDIA GeForce RTX 4060']:['AMD Ryzen 5 5600 6-Core Processor','AMD Ryzen 5 7600 6-Core Processor'];
 const choose=(/** @type {string} */ id,/** @type {number} */ i)=>id?devices.find(d=>d.id===id):devices.find(d=>d.name===defaults[i]&&(type==='cpu'||d.backend==='OPTIX'))||devices[i];
 const a=choose(o.q.get('a')||'',0),b=choose(o.q.get('b')||'',1),selected=[a,b],photos=selected.map(d=>d?gpuPhoto(d.name):null);
 const short=(/** @type {string} */ n)=>n.replace(/^(NVIDIA GeForce |AMD )/,'').replace(/ \d+-Core Processor$/,'');
 const options=(/** @type {any} */ current)=>devices.map(d=>html`<option value="${d.id}"${current?.id===d.id?html` selected`:''}>${short(d.name)} · ${d.backend}</option>`);
 const max=Math.max(a?.score||0,b?.score||0),same=a?.id===b?.id;
 const result=a&&b?html`<section class="box hw-section"><h2>${ko?'비교 결과':'Comparison results'} <span class="hw-help">Blender ${DATA.version} · Cycles</span></h2><p class="hw-verdict">${same?(ko?'같은 장치를 선택했습니다.':'You selected the same device.'):html`<strong>${short((a.score>=b.score?a:b).name)}</strong>${ko?'의 렌더링 중앙값이 ':' has a '}<strong>${(Math.max(a.score,b.score)/Math.min(a.score,b.score)).toFixed(2)}${ko?'배':'×'}</strong>${ko?' 높습니다.':' higher rendering median.'}`}</p>
 <table class="mt hw-comparison"><caption class="sr-only">${ko?'Blender 렌더링 성능 비교':'Blender rendering performance comparison'}</caption><colgroup><col class="hw-metric"><col><col></colgroup><thead><tr><th scope="col">${ko?'항목':'Metric'}</th>${selected.map((d,i)=>d&&html`<th scope="col" class="hw-device"><span class="hw-marker">${i===0?'A':'B'}</span><span class="hw-device-name">${short(d.name)}</span>${photos[i]?photo(photos[i],ko):type==='gpu'?html`<p class="hw-no-photo">${ko?'이 모델의 실물 사진 준비 중':'Photo not available for this model'}</p>`:''}</th>`)}</tr></thead><tbody>
 <tr class="hw-score-row"><th scope="row">${ko?'렌더링 점수':'Rendering score'}<small>samples/min</small></th>${selected.map(d=>d&&html`<td><strong class="hw-score">${d.score.toLocaleString(ko?'ko-KR':'en-US',{maximumFractionDigits:1})}</strong><progress max="${max}" value="${d.score}" aria-label="${d.name}"></progress></td>`)}</tr>
 <tr><th scope="row">${ko?'상대 성능':'Relative score'}</th>${selected.map(d=>d&&html`<td>${(d.score/a.score*100).toFixed(0)}%${d.id===a.id?html` <small>${ko?'기준':'baseline'}</small>`:''}</td>`)}</tr>
 <tr><th scope="row">${ko?'측정 표본':'Submissions'}</th>${selected.map(d=>d&&html`<td>${d.samples.toLocaleString()}${ko?'개':''}${d.samples<10?html` <small>${ko?'표본 적음':'small sample'}</small>`:''}</td>`)}</tr>
 <tr><th scope="row">${ko?'백엔드':'Backend'}</th>${selected.map(d=>d&&html`<td>${d.backend}</td>`)}</tr>
 <tr><th scope="row">${ko?'중고 가격':'Used prices'}</th>${selected.map(d=>d&&html`<td><a class="hw-text-link" href="/${o.l}/hardware/used-prices/?country=${m.id}&q=${encodeURIComponent(short(d.name))}">${ko?'시세 확인':'Check prices'} ↗</a></td>`)}</tr></tbody></table>
 ${photoCredits(photos,ko)}${a.backend!==b.backend?html`<p class="hw-help">${ko?'백엔드가 달라 최적화 차이도 결과에 포함됩니다.':'Different backends: results include differences in optimization.'}</p>`:''}</section>
 <section class="box hw-section" data-island="hardware-value" data-country="${m.id}" data-a="${a.score}" data-b="${b.score}"><h2>${ko?'구매 가격으로 가성비 비교':'Value at your purchase prices'}</h2><form class="hw-form"><fieldset class="hw-form" disabled data-hw-enable><label>A · ${m.currency}<input name="price-a" inputmode="decimal" maxlength="30" placeholder="${ko?'구매 가격':'Purchase price'}" aria-label="${ko?'A 구매 가격':'A purchase price'}"></label><label>B · ${m.currency}<input name="price-b" inputmode="decimal" maxlength="30" placeholder="${ko?'구매 가격':'Purchase price'}" aria-label="${ko?'B 구매 가격':'B purchase price'}"></label><button class="btn" type="submit">${ko?'가성비 계산':'Compare value'}</button></fieldset></form><p data-value-result role="status" class="hw-help">${ko?'배송비를 포함한 현지 가격으로 렌더링 성능/가격을 비교합니다.':'Compares rendering score per price using local prices including shipping.'}</p></section>`:html`<section class="box hw-section"><p>${ko?'이 종류에 해당하는 측정 결과가 없습니다. 장치를 다시 선택하세요.':'No matching measurement in this device type. Choose devices again.'}</p></section>`;
 return shell(o,ko?'GPU·CPU 성능 비교':'GPU / CPU performance',ko?'모델 두 개를 고르고 렌더링 성능과 구매 가격을 나란히 비교하세요.':'Choose two models to compare rendering performance and purchase value.',html`
 <div class="cols hw-layout"><main class="mainc"><section class="box hw-section hw-selection"><form method="get" class="hw-form"><div class="hw-type-row"><label>${ko?'부품 종류':'Component'}<select name="type" data-hw-type><option value="gpu"${type==='gpu'?html` selected`:''}>GPU</option><option value="cpu"${type==='cpu'?html` selected`:''}>CPU</option></select></label><label>${ko?'국가 · 통화':'Country · currency'}<select name="country">${countryOptions(o.l,m.id)}</select></label><button class="btn" type="submit" name="reset" value="1" data-hw-reset>${ko?'적용':'Apply'}</button></div>
 <div class="hw-select-pair">${['a','b'].map((id,i)=>html`<div class="hw-model-select"><label for="hw-${id}-filter"><span class="hw-marker">${id.toUpperCase()}</span> ${ko?'비교할 모델':'Choose model'}</label><input id="hw-${id}-filter" type="search" data-hw-filter="${id}" placeholder="${ko?'모델 검색 (예: 4060, 5600)':'Filter models (e.g. 4060, 5600)'}" aria-label="${ko?`${id.toUpperCase()} 모델 검색`:`Filter ${id.toUpperCase()} models`}"><label class="sr-only" for="hw-${id}-model">${id.toUpperCase()} ${ko?'모델·백엔드':'model & backend'}</label><select id="hw-${id}-model" name="${id}" required>${options(selected[i])}</select></div>`)}</div><div class="hw-compare-action"><span class="hw-help">${ko?`${devices.length}개 측정 조합 · 모델 / 백엔드`:`${devices.length} measured combinations · model / backend`}</span><button class="btn p" type="submit">${ko?'성능 비교':'Compare'}</button></div></form></section>${result}</main>
 <aside class="side"><section class="box hw-section"><h2>${ko?'측정 기준':'Benchmark'}</h2><dl class="hw-meta"><div><dt>${ko?'출처':'Source'}</dt><dd><a href="https://opendata.blender.org/about/" target="_blank" rel="noopener noreferrer">Blender Open Data ↗</a></dd></div><div><dt>${ko?'버전':'Version'}</dt><dd>${DATA.version} · CC0</dd></div><div><dt>${ko?'기준일':'Snapshot'}</dt><dd>${DATA.asOf}</dd></div><div><dt>${ko?'점수':'Score'}</dt><dd>${ko?'samples/min · 높을수록 좋음':'samples/min · higher is better'}</dd></div></dl><p class="hw-help hw-scope">${ko?'Cycles 렌더링 기준입니다. 게임 FPS·싱글코어·AI 추론 성능 수치는 아직 제공하지 않습니다.':'Cycles rendering only. Gaming FPS, single-core and AI inference metrics are not available yet.'}</p>
 <details class="hw-details hw-method"><summary>${ko?'자세한 데이터·계산 기준':'Detailed methodology'}</summary><p>${ko?'monster·junkshop·classroom 세 장면의 samples/min을 제출별로 합산한 뒤, 장치명·백엔드별 중앙값을 냈습니다. 단일 장치·단일 CPU 소켓의 완전한 제출만 사용하며 최소 표본은 3개입니다. OS는 합쳐져 있고 클럭·전력·드라이버·냉각 조건은 통제하지 않았습니다. 30일이 지난 데이터는 과거 스냅샷으로 보세요.':'Sum samples/min across monster, junkshop and classroom per submission, then take the median by device name and backend. Only complete single-device, single-socket submissions with at least 3 samples. OSes are pooled; clock, power, drivers and cooling are uncontrolled. Treat snapshots older than 30 days as historical.'}</p><a class="hw-text-link" href="https://opendata.blender.org/benchmarks/query/" target="_blank" rel="noopener noreferrer">${ko?'원본 결과 검색':'Explore original results'} ↗</a></details></section><section class="box hw-section"><h2>${ko?'구매 전에':'Before buying'}</h2><p>${ko?'구매 국가의 중고장터에서 같은 모델·상태의 가격도 확인하세요.':'Check comparable used listings in your purchase country.'}</p><a class="hw-text-link" href="/${o.l}/hardware/used-prices/?country=${m.id}">${ko?'국가별 중고 시세':'Used prices by country'} ›</a><a class="hw-text-link" href="/${o.l}/hardware/?type=gpu">${ko?'GPU 공식 스펙':'GPU specifications'} ›</a></section></aside></div>`);
}
