// @ts-check
import {html} from './html.js';
import {page} from './ui.js';
import DATA from '../../data/hardware/blender.js';
import {MARKETS,marketOf,marketLinks} from '../../src/hardware/market.js';

/** @param {string} l @param {string} active */
export function hardwareToolLinks(l,active=''){
 const ko=l==='ko';
 return html`<nav class="hw-tabs" aria-label="${ko?'PC 도구':'PC tools'}"><a href="/${l}/hardware/used-prices/"${active==='used-prices'?html` aria-current="page"`:''}>${ko?'국가별 중고 시세':'Used prices by country'}</a><a href="/${l}/hardware/performance/"${active==='performance'?html` aria-current="page"`:''}>${ko?'GPU·CPU 성능 비교':'GPU / CPU performance'}</a><a href="/${l}/hardware/?type=gpu">${ko?'GPU 공식 스펙':'GPU specifications'}</a></nav>`;
}
/** @param {string} l @param {string} country */
function countryOptions(l,country){return MARKETS.map(m=>html`<option value="${m.id}"${m.id===country?html` selected`:''}>${l==='ko'?m.ko:m.en} · ${m.currency}</option>`);}
/** @param {any} o @param {string} title @param {string} description @param {unknown} body */
function shell(o,title,description,body){
 const base=`/${o.l}/hardware/${o.tool}/`;
 return page({l:o.l,title:title+' | Nerulio',description,canonical:o.origin+base,alternates:{ko:o.origin+`/ko/hardware/${o.tool}/`,en:o.origin+`/en/hardware/${o.tool}/`},noindex:!!o.query,channels:o.channels,
  body:html`<div class="hw-tool"><header class="box hw-heading"><span class="hw-kicker">PC TOOLS</span><h1>${title}</h1><p>${description}</p>${hardwareToolLinks(o.l,o.tool)}</header>${body}</div>`});
}
/** @param {{l:string,origin:string,tool:string,query:string,q:URLSearchParams,channels:any[]}} o */
export function renderUsedPrices(o){
 const ko=o.l==='ko',m=marketOf(o.q.get('country')||(ko?'KR':'US')),q=o.q.get('q')||'',links=marketLinks(m.id,q);
 const kind=(/** @type {string} */ k)=>ko?({asking:'판매 중 · 호가',sold:'판매 완료 · 표시 가격',mixed:'판매 중·완료 필터 확인'}[k]||k):({asking:'Active · asking prices',sold:'Sold · displayed prices',mixed:'Check active / sold filters'}[k]||k);
 return shell(o,ko?'국가별 중고 시세 확인':'Used hardware prices by country',ko?'나라와 모델을 고르고, 현지 중고장터에서 가격을 확인하세요. 같은 조건의 가격을 모으면 중앙값과 가격 범위를 계산합니다.':'Choose a country and model, check local marketplaces, then calculate the median and range of comparable prices.',html`
 <section class="box hw-section"><h2>${ko?'1. 국가와 모델 선택':'1. Choose a country and model'}</h2><form method="get" class="hw-form"><label>${ko?'시장 · 현지 통화':'Market · local currency'}<select name="country">${countryOptions(o.l,m.id)}</select></label><label class="hw-wide">${ko?'부품 모델명':'Hardware model'}<input name="q" type="search" maxlength="80" required value="${q}" placeholder="RTX 4060 8GB / Ryzen 5 5600"></label><button class="btn p" type="submit">${ko?'중고장터 찾기':'Find marketplaces'}</button></form>
 ${links.length?html`<div class="hw-market-links">${links.map(x=>html`<a href="${x.url}" target="_blank" rel="noopener noreferrer"><strong>${x.name} ↗</strong><span>${kind(x.kind)}</span></a>`)}</div>`:html`<p class="fine">${ko?'모델명을 입력하면 선택한 국가의 검색 링크가 나옵니다.':'Enter a model to see search links for this market.'}</p>`}
 <p class="hw-note">${ko?'자동 시세 수집은 연결되어 있지 않습니다. 링크는 외부 검색을 엽니다. 국가 선택은 현지 사이트·통화 기준이며 판매자의 실제 위치는 매물에서 확인하세요.':'Automatic price feeds are not connected. Links open external searches. Country selects the local site and currency; check seller location in each listing.'}</p></section>
 <section class="box hw-section" data-island="used-prices" data-country="${m.id}"><h2>${ko?'2. 확인한 가격으로 시세 계산':'2. Calculate from prices you checked'}</h2><p class="fine">${ko?'동일 모델·메모리·정상 작동·비슷한 상태의 단품만 골라 주세요. 완본체, 부품용, 박스만, 신품, 중복 매물은 섞지 마세요. 배송비 포함 여부도 맞춰 주세요.':'Use standalone parts with the same model, memory and similar working condition. Exclude full PCs, broken parts, empty boxes, new items and duplicates. Use a consistent shipping basis.'}</p>
 <form class="hw-price-form"><fieldset disabled data-hw-enable><div class="hw-form"><label>${ko?'가격 종류':'Price basis'}<select name="basis"><option value="asking">${ko?'판매 중 호가':'Active asking prices'}</option><option value="sold">${ko?'판매 완료 표시 가격':'Sold displayed prices'}</option></select></label><label>${ko?'상태 (기록용)':'Condition (for your record)'}<select name="condition"><option>${ko?'정상 중고':'Working used'}</option><option>${ko?'미개봉':'Unopened'}</option><option>${ko?'리퍼':'Refurbished'}</option></select></label></div>
 <label class="hw-price-label">${ko?`확인한 가격 (${m.currency}) · 한 줄에 하나, 최대 200개`:`Checked prices (${m.currency}) · one per line, up to 200`}<textarea name="prices" rows="6" maxlength="8000" required placeholder="${ko?'숫자만 한 줄씩 입력하세요':'Enter one numeric price per line'}" aria-describedby="hw-price-help"></textarea></label>
 <p class="fine" id="hw-price-help">${ko?'국가별 숫자 형식을 사용합니다. 독일: 1.234,50 / 프랑스: 1 234,50 / 미국: 1,234.50. 입력값은 자동 저장하지 않습니다.':'Use local separators: Germany 1.234,50 / France 1 234,50 / US 1,234.50. Inputs are not automatically saved.'}</p>
 <button class="btn p" type="submit">${ko?'시세 계산':'Calculate prices'}</button><button class="btn" type="reset">${ko?'초기화':'Clear'}</button></fieldset></form><div data-price-result role="status" aria-live="polite"><p class="hw-empty">${ko?'확인한 가격을 입력하면 결과가 여기에 표시됩니다.':'Your calculated results will appear here.'}</p></div><noscript><p>${ko?'가격 계산에는 JavaScript가 필요합니다. 위 검색 링크는 그대로 사용할 수 있습니다.':'Enable JavaScript to calculate prices. Marketplace links above still work.'}</p></noscript>
 <p class="hw-note">${ko?'입력한 표본의 참고 통계입니다. 호가는 실거래가가 아니며, 판매 완료의 표시 가격도 할인 협상 등으로 최종 결제액과 다를 수 있습니다. 중앙 50% 범위는 Q1–Q3이고, 표본의 최솟값·최댓값도 따로 보여 줍니다.':'These are reference statistics from your inputs. Asking prices are not sale prices; sold displayed prices may differ from final negotiated payments. The central 50% range is Q1–Q3; minimum and maximum are shown separately.'}</p></section>`);
}

/** @param {{l:string,origin:string,tool:string,query:string,q:URLSearchParams,channels:any[]}} o */
export function renderPerformance(o){
 const ko=o.l==='ko',type=o.q.get('type')==='cpu'?'cpu':'gpu',devices=DATA.devices.filter(d=>d.type===type),m=marketOf(o.q.get('country')||(ko?'KR':'US'));
 const defaults=type==='gpu'?['NVIDIA GeForce RTX 3060','NVIDIA GeForce RTX 4060']:['AMD Ryzen 5 5600 6-Core Processor','AMD Ryzen 5 7600 6-Core Processor'];
 const choose=(/** @type {string} */ id,/** @type {number} */ i)=>id?devices.find(d=>d.id===id):devices.find(d=>d.name===defaults[i]&&(type==='cpu'||d.backend==='OPTIX'))||devices[i];
 const a=choose(o.q.get('a')||'',0),b=choose(o.q.get('b')||'',1),selected=[a,b];
 const options=(/** @type {any} */ current)=>devices.map(d=>html`<option value="${d.id}"${current?.id===d.id?html` selected`:''}>${d.name} · ${d.backend} · n=${d.samples}</option>`);
 const max=Math.max(a?.score||0,b?.score||0),same=a?.id===b?.id;
 const result=a&&b?html`<section class="box hw-section"><h2>${ko?'Blender 렌더링 성능':'Blender rendering performance'}</h2><p class="hw-verdict">${same?(ko?'같은 장치를 선택했습니다.':'You selected the same device.'):ko?`${(a.score>=b.score?a:b).name}의 중앙값이 ${(Math.max(a.score,b.score)/Math.min(a.score,b.score)).toFixed(2)}배 높습니다.`:`${(a.score>=b.score?a:b).name} has a ${(Math.max(a.score,b.score)/Math.min(a.score,b.score)).toFixed(2)}× higher median.`}</p><div class="hw-comparison">${selected.map((d,i)=>d&&html`<article class="hw-device"><span class="hw-kicker">${i===0?'A':'B'} · ${d.backend}</span><h3>${d.name}</h3><strong class="hw-score">${d.score.toLocaleString(ko?'ko-KR':'en-US',{maximumFractionDigits:1})}</strong><span class="fine">${ko?'samples/min · 높을수록 좋음':'samples/min · higher is better'}</span><progress max="${max}" value="${d.score}" aria-label="${d.name}"></progress><p class="fine">${ko?`완전한 제출 ${d.samples}개 · 중앙값`:`${d.samples} complete submissions · median`}${d.samples<10?ko?' · 표본 적음':' · small sample':''}</p><a href="/${o.l}/hardware/used-prices/?country=${m.id}&q=${encodeURIComponent(d.name.replace(/^(NVIDIA GeForce |AMD )/,'').replace(/ \d+-Core Processor$/,''))}">${ko?'이 부품 중고 시세 확인':'Check used prices for this part'} ›</a></article>`)}</div>
 ${a.backend!==b.backend?html`<p class="hw-note">${ko?'렌더링 백엔드가 다릅니다. 이 결과에는 각 백엔드의 최적화 차이도 포함됩니다.':'Rendering backends differ. These results include differences in backend optimization.'}</p>`:''}
 <div data-island="hardware-value" data-country="${m.id}" data-a="${a.score}" data-b="${b.score}"><h3>${ko?'내 구매 가격으로 가성비 비교':'Compare value at your purchase prices'}</h3><form class="hw-form"><fieldset class="hw-form" disabled data-hw-enable><label>A · ${m.currency}<input name="price-a" inputmode="decimal" maxlength="30" aria-label="${ko?'A 구매 가격':'A purchase price'}"></label><label>B · ${m.currency}<input name="price-b" inputmode="decimal" maxlength="30" aria-label="${ko?'B 구매 가격':'B purchase price'}"></label><button class="btn" type="submit">${ko?'가성비 계산':'Calculate value'}</button></fieldset></form><p data-value-result role="status" class="fine">${ko?'동일 통화의 배송비 포함 가격을 넣으세요. 성능/가격 비율을 비교합니다.':'Enter total prices including shipping in the same currency. Compares score per unit of money.'}</p></div></section>`:html`<section class="box hw-section"><p>${ko?'이 종류에 해당하는 측정 결과가 없습니다. 장치를 다시 선택하세요.':'No matching measurement in this device type. Choose devices again.'}</p></section>`;
 return shell(o,ko?'GPU·CPU 성능 비교':'GPU / CPU performance comparison',ko?'같은 Blender 버전의 실측 중앙값을 나란히 비교하세요. 국가별 구매 가격을 넣으면 렌더링 가성비도 비교할 수 있습니다.':'Compare measured medians from the same Blender version, then compare rendering value using purchase prices in your local currency.',html`
 <section class="box hw-section"><form method="get" class="hw-form"><label>${ko?'부품 종류':'Component'}<select name="type" data-hw-type><option value="gpu"${type==='gpu'?html` selected`:''}>GPU</option><option value="cpu"${type==='cpu'?html` selected`:''}>CPU</option></select></label><label>${ko?'구매 국가 · 통화':'Purchase market · currency'}<select name="country">${countryOptions(o.l,m.id)}</select></label><button class="btn" type="submit" name="reset" value="1" data-hw-reset>${ko?'종류 변경':'Change type'}</button>
 <div class="hw-select-pair"><label>A<input type="search" data-hw-filter="a" placeholder="${ko?'모델 검색 (예: 4060, 5600)':'Filter models (e.g. 4060, 5600)'}" aria-label="${ko?'A 모델 검색':'Filter A models'}"><select name="a" required>${options(a)}</select></label><label>B<input type="search" data-hw-filter="b" placeholder="${ko?'모델 검색 (예: 4060, 5600)':'Filter models (e.g. 4060, 5600)'}" aria-label="${ko?'B 모델 검색':'Filter B models'}"><select name="b" required>${options(b)}</select></label></div><button class="btn p" type="submit">${ko?'성능 비교':'Compare performance'}</button></form><p class="fine">${ko?`GPU·CPU 중 한 종류 안에서 비교합니다. 현재 ${devices.length}개 장치/백엔드 조합.`:`Compare within either GPU or CPU. ${devices.length} device/backend combinations available.`}</p></section>${result}
 <section class="box hw-section hw-method"><h2>${ko?'데이터와 측정 기준':'Data and methodology'}</h2><p><a href="https://opendata.blender.org/about/" target="_blank" rel="noopener noreferrer">Blender Open Data ↗</a> · CC0 · Blender ${DATA.version} · ${ko?'데이터 기준일':'Snapshot'} ${DATA.asOf}</p><p>${ko?'monster·junkshop·classroom 세 장면의 samples/min을 제출별로 합산한 뒤, 장치명·백엔드별 중앙값을 냈습니다. 단일 장치·단일 CPU 소켓의 완전한 제출만 사용하며 최소 표본은 3개입니다. OS는 합쳐져 있고 클럭·전력·드라이버·냉각 조건은 통제하지 않았습니다.':'We sum samples/min across monster, junkshop and classroom for each submission, then take the median by device name and backend. Only complete, single-device, single-socket submissions are included, with at least 3 samples. Operating systems are pooled; clock, power, driver and cooling conditions are not controlled.'}</p><p class="hw-note">${ko?'Cycles 렌더링 성능이며 게임 FPS·싱글코어·AI 추론 성능을 뜻하지 않습니다. 게임·AI 성능 수치는 아직 제공하지 않습니다. 30일이 지난 데이터는 과거 스냅샷으로 보세요.':'Measures Cycles rendering, not gaming FPS, single-core speed or AI inference. Gaming and AI metrics are not available yet. Treat snapshots older than 30 days as historical.'}</p><a href="https://opendata.blender.org/benchmarks/query/" target="_blank" rel="noopener noreferrer">${ko?'원본 결과 검색':'Explore original results'} ↗</a></section>`);
}
