// @ts-check
import {html} from './html.js';
import {page} from './ui.js';
import {icon} from './icons.js';
import DATA from '../../data/hardware/blender.js';
import {gpuPhoto} from '../hardware-photos.js';
import {MARKETS,marketOf,marketLinks,localMoney} from '../../src/hardware/market.js';

/** @param {string} l @param {string} active */
export function hardwareToolLinks(l,active=''){
 const ko=l==='ko';
 return html`<nav class="mtabs hw-tabs" aria-label="${ko?'PC 도구':'PC tools'}">${[['used-prices',ko?'국가별 중고 시세':'Used prices'],['performance',ko?'GPU·CPU 성능 비교':'GPU / CPU comparison'],['',ko?'GPU 공식 스펙':'GPU specifications']].map(([id,name])=>html`<a href="/${l}/hardware/${id?id+'/':'?type=gpu'}"${id===active?html` class="on" aria-current="page"`:''}>${name}</a>`)}</nav>`;
}
/** @param {string} l @param {string} country */
function countryOptions(l,country){return MARKETS.map(m=>html`<option value="${m.id}"${m.id===country?html` selected`:''}>${l==='ko'?m.ko:m.en} · ${m.currency}</option>`);}
/** @param {any} o @param {string} title @param {string} description @param {unknown} body */
function shell(o,title,description,body){
 const base=`/${o.l}/hardware/${o.tool}/`,ko=o.l==='ko';
 return page({l:o.l,title:title+' | Nerulio',description,canonical:o.origin+base,alternates:{ko:o.origin+`/ko/hardware/${o.tool}/`,en:o.origin+`/en/hardware/${o.tool}/`},noindex:!!o.query,channels:o.channels,
  body:html`<div class="hw-tool"><header class="box chh hw-heading"><span class="tile t-hw" aria-hidden="true">${icon('chip',22)}</span><div class="chm"><div class="chn1"><h1>${title}</h1></div><p class="hw-lead">${description}</p></div><div class="cha"><a class="btn" href="/${o.l}/community/hw/">${ko?'PC·하드웨어 채널':'PC community'} ›</a></div></header>${hardwareToolLinks(o.l,o.tool)}${body}</div>`});
}
/** @param {ReturnType<typeof gpuPhoto>} p @param {boolean} ko */
function photo(p,ko){return p?html`<figure class="hw-photo"><img src="${p.src}" width="960" height="${p.src.endsWith('rx-6600-xt.jpg')||p.src.endsWith('arc-a770.jpg')?720:540}" alt="${p.board}${ko?' 실물':' graphics card'}" decoding="async"><figcaption>${p.board}</figcaption></figure>`:'';}
/** @param {ReturnType<typeof gpuPhoto>[]} photos @param {boolean} ko */
function photoCredits(photos,ko){
 const unique=[...new Set(photos.filter(Boolean))];
 return unique.length?html`<details class="hw-details hw-credits"><summary>${ko?'사진 출처·라이선스':'Photo credits & licenses'}</summary><ul>${unique.map(p=>p&&html`<li>${p.board} — <a href="${p.source}" target="_blank" rel="noopener noreferrer">${p.author}</a> · <a href="${p.licenseUrl}" target="_blank" rel="noopener noreferrer">${p.license}</a>${p.original?html` · <a href="${p.original}" target="_blank" rel="noopener noreferrer">${ko?'원본 영상':'Original video'}</a>`:''}</li>`)}</ul><p>${ko?'Wikimedia 축소본 사용, 추가 편집 없음. 실물 제품의 외형 예시이며 측정에 사용된 개별 장치 사진은 아닙니다. 같은 GPU라도 제조사·쿨러·메모리 구성은 다를 수 있습니다.':'Wikimedia thumbnails, no further edits. Retail-board examples, not photographs of individual benchmark submissions. Board maker, cooler and memory configuration may vary.'}</p></details>`:'';
}
/** @param {boolean} ko */
function priceGuide(ko){return html`<section class="box hw-section"><h2>${ko?'비교할 매물 고르기':'Choose comparable listings'}</h2><ul class="hw-guide"><li>${ko?'모델명과 메모리 용량이 같은 제품':'Same model and memory capacity'}</li><li>${ko?'상태·배송비 포함 기준 통일':'Consistent condition and shipping basis'}</li><li>${ko?'완본체·부품용·박스만·중복 제외':'Exclude full PCs, broken parts, boxes and duplicates'}</li></ul><details class="hw-details"><summary>${ko?'호가와 실거래가의 차이':'Asking vs. sale prices'}</summary><p>${ko?'호가는 실거래가가 아닙니다. 판매 완료 표시 가격도 할인 협상 등으로 최종 결제액과 다를 수 있습니다. 국가 선택은 현지 사이트·통화 기준이며 판매자의 실제 위치는 매물에서 확인하세요.':'Asking prices are not sale prices. Sold displayed prices may differ from final negotiated payments. Country selects the local site and currency; check seller location in each listing.'}</p></details></section>`;}
/** @param {{l:string,origin:string,tool:string,query:string,q:URLSearchParams,channels:any[],market?:import('../../server/platform/hardware-market.js').Snapshot}} o */
export function renderUsedPrices(o){
 const ko=o.l==='ko',m=marketOf(o.q.get('country')||(ko?'KR':'US')),q=o.q.get('q')||'',links=marketLinks(m.id,q),p=gpuPhoto(q);
 const basis=o.q.get('basis')==='sold'?'sold':'asking',days=o.q.get('days')||'30';
 const result=o.market,available=result?.status==='available',money=(/** @type {number} */ n)=>localMoney(n,m.id);
 const kind=(/** @type {string} */ k)=>ko?({asking:'판매 중 · 호가',sold:'판매 완료 · 표시 가격',mixed:'판매 중·완료 필터 확인'}[k]||k):({asking:'Active · asking',sold:'Sold · displayed',mixed:'Check active / sold filters'}[k]||k);
 const states=/** @type {Record<string,string>} */(ko?{stale:'최근 수집에 실패했거나 데이터가 오래되어 가격을 표시하지 않습니다. 다음 수집에서 다시 확인합니다.',idle:'국가와 GPU·CPU 모델을 선택하면 연결된 장터의 가격을 자동 조회합니다.',invalid_query:'GPU·CPU 모델명을 확인하세요. 예: RTX 4060, RX 6600 XT, Ryzen 5 5600, i5-12400F.',not_connected:'이 국가의 자동 가격 조회는 아직 연결되지 않았습니다.',access_denied:'장터 데이터 접근이 거절되어 가격을 가져오지 못했습니다.',rate_limited:'조회가 잠시 많습니다. 잠시 후 다시 검색하세요.',upstream_error:'장터에서 가격을 가져오지 못했습니다. 잠시 후 다시 검색하세요.',no_results:'검색 결과에서 비교 가능한 중고 단품을 찾지 못했습니다.'}:{stale:'Collection failed or data is stale. Prices are hidden until the next successful collection.',idle:'Choose a country and GPU / CPU model to fetch prices from connected marketplaces.',invalid_query:'Enter a GPU / CPU model, such as RTX 4060, RX 6600 XT, Ryzen 5 5600 or i5-12400F.',not_connected:'Automatic prices for this country are not connected yet.',access_denied:'The marketplace denied data access. Prices could not be retrieved.',rate_limited:'Too many lookups. Please search again shortly.',upstream_error:'Could not retrieve marketplace prices. Please try again shortly.',no_results:'No comparable used standalone parts were found in the returned results.'});
 return shell(o,ko?'국가별 중고 시세':'Used prices by country',ko?'국가와 모델명으로 중고 매물 가격을 자동 조회합니다.':'Automatically look up used listings by country and hardware model.',html`
 <div class="cols hw-layout"><main class="mainc"><section class="box hw-section"><h2>${ko?'국가·모델 검색':'Country & model'}</h2><form method="get" class="hw-form"><label>${ko?'국가 · 통화':'Country · currency'}<select name="country">${countryOptions(o.l,m.id)}</select></label><label class="hw-wide">${ko?'부품 모델명':'Hardware model'}<input name="q" type="search" maxlength="80" required value="${q}" placeholder="RTX 4060 8GB / Ryzen 5 5600"></label><label>${ko?'가격 기준':'Price basis'}<select name="basis"><option value="asking"${basis==='asking'?html` selected`:''}>${ko?'판매 중 호가':'Active asking'}</option><option value="sold"${basis==='sold'?html` selected`:''}>${ko?'판매 완료 표시가':'Sold displayed'}</option></select></label><label>${ko?'가격 관측 기간':'Price observation window'}<select name="days">${['7','30','90'].map(d=>html`<option value="${d}"${d===days?html` selected`:''}>${d}${ko?'일':' days'}</option>`)}</select></label><button class="btn p" type="submit">${ko?'검색':'Search'}</button></form>
 </section><section class="box hw-section" data-market-status="${result?.status||'idle'}"><h2>${ko?'자동 조회 결과':'Automatic results'}</h2>
 ${available?html`<p class="hw-help"><strong>${result.source} · ${kind(result.basis||'asking')}</strong> · ${result.items.length}${ko?'개':' listings'}</p>`:html`<p class="hw-empty">${states[result?.status||'idle']||states.upstream_error}</p>`}
 ${result?.status==='not_connected'?html`<p class="hw-help">${ko?'연결이 완료되면 가격을 입력할 필요 없이 이곳에서 매물 가격과 출처를 볼 수 있습니다. 현재는 아래 원본 장터에서 확인할 수 있습니다.':'Once connected, listing prices and sources will appear here automatically. You can currently check the original marketplaces below.'}</p>`:''}
 ${result?.observedAt?html`<p class="hw-help">${ko?'조회 시각':'Retrieved'} <time datetime="${result.observedAt}">${new Intl.DateTimeFormat(ko?'ko-KR':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Seoul'}).format(new Date(result.observedAt))} KST</time> · ${result.community?(ko?'매시간 정기 수집 · 스케줄 지연 가능':'Scheduled hourly; execution can be delayed'):(ko?'최대 5분 간격으로 갱신':'Refreshed on search, cached up to 5 minutes')}</p>`:''}
 ${result?.summary?html`<dl class="hw-stats"><div><dt>${ko?'조회 매물의 중앙값':'Median of fetched listings'}</dt><dd>${money(result.summary.median)}</dd></div><div><dt>${ko?'중앙 50% 범위 (Q1–Q3)':'Central 50% (Q1–Q3)'}</dt><dd>${money(result.summary.q1)} – ${money(result.summary.q3)}</dd></div><div><dt>${ko?'표본 수':'Sample count'}</dt><dd>${result.summary.count}</dd></div></dl>`:''}
 ${available?html`<ul class="hw-listings">${result.items.map(item=>html`<li><a href="${item.url}" target="_blank" rel="noopener noreferrer"><span>${item.title}</span><strong>${money(item.price)} ↗</strong></a><p class="hw-help">${item.source?item.source+' · ':''}${result.community&&item.shipping===0?(ko?'배송 포함 표시':'Shipping included in displayed price'):item.shipping===null?(ko?'배송비 확인 필요':'Check shipping cost'):item.shipping===0?(ko?'무료배송':'Free shipping'):(ko?'배송비 ':'Shipping ')+money(item.shipping)}</p></li>`)}</ul><p class="hw-help">${result.community?(ko?'판매글의 표시 가격이며 최종 결제액은 아닙니다. 배송 포함 여부는 매물마다 확인하세요.':'Displayed post prices, not final payments. Check shipping basis for each listing.'):(ko?'판매 중 호가이며 실거래가는 아닙니다. 배송비는 위 가격에 포함되지 않습니다.':'Active asking prices, not actual transaction prices. Prices above exclude shipping.')}</p>`:''}
 ${result?.community?html`<details class="hw-details"><summary>${ko?'수집·비교 기준':'Collection & matching'}</summary><p class="hw-help">${ko?`최근 ${result.days}일 안에 처음 관측하거나 가격이 변경된 매물입니다. 국가 구분은 커뮤니티·통화 기준이며 판매자의 실제 위치를 보증하지 않습니다. 같은 글의 반복 수집은 한 표본으로 유지합니다. 판매 완료는 수집 중 판매 상태로 전환된 경우만 표시합니다. 재게시·다른 사이트의 동일 매물은 중복일 수 있습니다. 원문이나 사용자 연락처는 저장하지 않습니다.`:`Prices first observed or changed within ${result.days} days. Country groups communities and currencies; seller location is not guaranteed. Repeated observations of a post count once; sold results require an observed transition from asking. Reposts and cross-site ads may duplicate a listing. Bodies and contacts are not retained.`}</p></details>${available&&!result.summary?html`<p class="hw-help">${ko?'같은 용량·배송 기준의 표본 5개 이상일 때 중앙값을 표시합니다.':'A median requires at least five samples with the same capacity and shipping basis.'}</p>`:''}`:''}
 ${result?.observedAt&&!result.community?html`<details class="hw-details"><summary>${ko?'수집·비교 기준':'Collection & matching'}</summary><p>${ko?`검색 결과 첫 50개에서 같은 모델의 현지 통화·현지 판매 중 중고 단품을 비교합니다. 모델 변형, 완본체, 부품용·박스만·미개봉·구매글과 중복 ID는 제목 기준으로 제외합니다. 이번 결과에서 ${result.excluded}개 제외. 제목만으로 상태를 보증할 수 없으며 가격 이상값은 임의로 제거하지 않습니다. 중앙값은 최소 5개이며 해당 표본에만 해당합니다.`:`Checks the first 50 results for the same model, local currency and seller country, active used standalone parts. Excludes variants, full systems, parts, boxes, sealed items, wanted ads and duplicate IDs by title. ${result.excluded} results excluded. Titles do not guarantee condition. Prices are not discarded as outliers. A median needs at least five listings and describes only that sample.`}</p></details>`:''}
 ${links.length?html`<details class="hw-details"${available?'':html` open`}><summary>${ko?'원본 장터에서 확인':'Check original marketplaces'}</summary><div class="hw-market-links">${links.map(x=>html`<a href="${x.url}" target="_blank" rel="noopener noreferrer"><strong>${x.name} ↗</strong><span>${kind(x.kind)}</span></a>`)}</div></details>`:''}</section></main>
 <aside class="side">${p?html`<section class="box hw-section"><h2>${ko?'찾는 GPU':'GPU you searched for'}</h2>${photo(p,ko)}${photoCredits([p],ko)}</section>`:''}${priceGuide(ko)}<section class="box hw-section"><h2>${ko?'성능도 비교하기':'Compare performance'}</h2><p>${ko?'같은 Blender 버전의 렌더링 실측값과 구매 가격을 비교할 수 있습니다.':'Compare rendering measurements and value at your purchase prices.'}</p><a class="hw-text-link" href="/${o.l}/hardware/performance/?country=${m.id}">${ko?'GPU·CPU 성능 비교':'GPU / CPU comparison'} ›</a></section></aside></div>`);
}

/** @param {{l:string,origin:string,tool:string,query:string,q:URLSearchParams,channels:any[]}} o */
export function renderPerformance(o){
 const ko=o.l==='ko',type=o.q.get('type')==='cpu'?'cpu':'gpu',devices=DATA.devices.filter(d=>d.type===type),m=marketOf(o.q.get('country')||(ko?'KR':'US'));
 const defaults=type==='gpu'?['NVIDIA GeForce RTX 3060','NVIDIA GeForce RTX 4060']:['AMD Ryzen 5 5600 6-Core Processor','AMD Ryzen 5 7600 6-Core Processor'];
 const choose=(/** @type {string} */ id,/** @type {number} */ i)=>id?devices.find(d=>d.id===id):devices.find(d=>d.name===defaults[i]&&(type==='cpu'||d.backend==='OPTIX'))||devices[i];
 const a=choose(o.q.get('a')||'',0),b=choose(o.q.get('b')||'',1),selected=[a,b],photos=selected.map(d=>d?gpuPhoto(d.name):null);
 const short=(/** @type {string} */ n)=>n.replace(/^(NVIDIA GeForce |AMD )/,'').replace(/ \d+-Core Processor$/,'');
 const options=(/** @type {any} */ current)=>devices.map(d=>html`<option value="${d.id}"${current?.id===d.id?html` selected`:''}>${short(d.name)} · ${d.backend}</option>`);
 const max=Math.max(a?.score||0,b?.score||0),same=a?.id===b?.id;
 const result=a&&b?html`<section class="box hw-section"><h2>${ko?'비교 결과':'Comparison results'} <span class="hw-help">Blender ${DATA.version} · Cycles</span></h2><p class="hw-verdict">${same?(ko?'같은 장치를 선택했습니다.':'You selected the same device.'):html`<strong>${short((a.score>=b.score?a:b).name)}</strong>${ko?'의 렌더링 중앙값이 ':' has a '}<strong>${(Math.max(a.score,b.score)/Math.min(a.score,b.score)).toFixed(2)}${ko?'배':'×'}</strong>${ko?' 높습니다.':' higher rendering median.'}`}</p>
 <table class="mt hw-comparison"><caption class="sr-only">${ko?'Blender 렌더링 성능 비교':'Blender rendering performance comparison'}</caption><colgroup><col class="hw-metric"><col><col></colgroup><thead><tr><th scope="col">${ko?'항목':'Metric'}</th>${selected.map((d,i)=>d&&html`<th scope="col" class="hw-device"><span class="hw-marker">${i===0?'A':'B'}</span><span class="hw-device-name">${short(d.name)}</span>${photos[i]?photo(photos[i],ko):type==='gpu'?html`<p class="hw-no-photo">${ko?'이 모델의 실물 사진 준비 중':'Photo not available for this model'}</p>`:''}</th>`)}</tr></thead><tbody>
 <tr class="hw-score-row"><th scope="row">${ko?'렌더링 점수':'Rendering score'}<small>samples/min</small></th>${selected.map(d=>d&&html`<td><strong class="hw-score">${d.score.toLocaleString(ko?'ko-KR':'en-US',{maximumFractionDigits:1})}</strong><progress max="${max}" value="${d.score}" aria-label="${d.name}"></progress></td>`)}</tr>
 <tr><th scope="row">${ko?'상대 성능':'Relative score'}</th>${selected.map(d=>d&&html`<td>${(d.score/a.score*100).toFixed(0)}%${d.id===a.id?html` <small>${ko?'기준':'baseline'}</small>`:''}</td>`)}</tr>
 <tr><th scope="row">${ko?'측정 표본':'Submissions'}</th>${selected.map(d=>d&&html`<td>${d.samples.toLocaleString()}${ko?'개':''}${d.samples<10?html` <small>${ko?'표본 적음':'small sample'}</small>`:''}</td>`)}</tr>
 <tr><th scope="row">${ko?'백엔드':'Backend'}</th>${selected.map(d=>d&&html`<td>${d.backend}</td>`)}</tr>
 <tr><th scope="row">${ko?'중고 가격':'Used prices'}</th>${selected.map(d=>d&&html`<td><a class="hw-text-link" href="/${o.l}/hardware/used-prices/?country=${m.id}&q=${encodeURIComponent(short(d.name))}">${ko?'시세 확인':'Check prices'} ↗</a></td>`)}</tr></tbody></table>
 ${photoCredits(photos,ko)}${a.backend!==b.backend?html`<p class="hw-help">${ko?'백엔드가 달라 최적화 차이도 결과에 포함됩니다.':'Different backends: results include differences in optimization.'}</p>`:''}</section>
 <section class="box hw-section" data-island="hardware-value" data-country="${m.id}" data-a="${a.score}" data-b="${b.score}"><h2>${ko?'구매 가격으로 가성비 비교':'Value at your purchase prices'}</h2><form class="hw-form"><fieldset class="hw-form" disabled data-hw-enable><label>A · ${m.currency}<input name="price-a" inputmode="decimal" maxlength="30" placeholder="${ko?'구매 가격':'Purchase price'}" aria-label="${ko?'A 구매 가격':'A purchase price'}"></label><label>B · ${m.currency}<input name="price-b" inputmode="decimal" maxlength="30" placeholder="${ko?'구매 가격':'Purchase price'}" aria-label="${ko?'B 구매 가격':'B purchase price'}"></label><button class="btn" type="submit">${ko?'가성비 계산':'Compare value'}</button></fieldset></form><p data-value-result role="status" class="hw-help">${ko?'배송비를 포함한 현지 가격으로 렌더링 성능/가격을 비교합니다.':'Compares rendering score per price using local prices including shipping.'}</p></section>`:html`<section class="box hw-section"><p>${ko?'이 종류에 해당하는 측정 결과가 없습니다. 장치를 다시 선택하세요.':'No matching measurement in this device type. Choose devices again.'}</p></section>`;
 return shell(o,ko?'GPU·CPU 성능 비교':'GPU / CPU performance',ko?'모델 두 개를 고르고 렌더링 성능과 구매 가격을 나란히 비교하세요.':'Choose two models to compare rendering performance and purchase value.',html`
 <div class="cols hw-layout"><main class="mainc"><section class="box hw-section hw-selection"><form method="get" class="hw-form"><div class="hw-type-row"><label>${ko?'부품 종류':'Component'}<select name="type" data-hw-type><option value="gpu"${type==='gpu'?html` selected`:''}>GPU</option><option value="cpu"${type==='cpu'?html` selected`:''}>CPU</option></select></label><label>${ko?'국가 · 통화':'Country · currency'}<select name="country">${countryOptions(o.l,m.id)}</select></label><button class="btn" type="submit" name="reset" value="1" data-hw-reset>${ko?'적용':'Apply'}</button></div>
 <div class="hw-select-pair">${['a','b'].map((id,i)=>html`<div class="hw-model-select"><label for="hw-${id}-filter"><span class="hw-marker">${id.toUpperCase()}</span> ${ko?'비교할 모델':'Choose model'}</label><input id="hw-${id}-filter" type="search" data-hw-filter="${id}" placeholder="${ko?'모델 검색 (예: 4060, 5600)':'Filter models (e.g. 4060, 5600)'}" aria-label="${ko?`${id.toUpperCase()} 모델 검색`:`Filter ${id.toUpperCase()} models`}"><label class="sr-only" for="hw-${id}-model">${id.toUpperCase()} ${ko?'모델·백엔드':'model & backend'}</label><select id="hw-${id}-model" name="${id}" required>${options(selected[i])}</select></div>`)}</div><div class="hw-compare-action"><span class="hw-help">${ko?`${devices.length}개 측정 조합 · 모델 / 백엔드`:`${devices.length} measured combinations · model / backend`}</span><button class="btn p" type="submit">${ko?'성능 비교':'Compare'}</button></div></form></section>${result}</main>
 <aside class="side"><section class="box hw-section"><h2>${ko?'측정 기준':'Benchmark'}</h2><dl class="hw-meta"><div><dt>${ko?'출처':'Source'}</dt><dd><a href="https://opendata.blender.org/about/" target="_blank" rel="noopener noreferrer">Blender Open Data ↗</a></dd></div><div><dt>${ko?'버전':'Version'}</dt><dd>${DATA.version} · CC0</dd></div><div><dt>${ko?'기준일':'Snapshot'}</dt><dd>${DATA.asOf}</dd></div><div><dt>${ko?'점수':'Score'}</dt><dd>${ko?'samples/min · 높을수록 좋음':'samples/min · higher is better'}</dd></div></dl><p class="hw-help hw-scope">${ko?'Cycles 렌더링 기준입니다. 게임 FPS·싱글코어·AI 추론 성능 수치는 아직 제공하지 않습니다.':'Cycles rendering only. Gaming FPS, single-core and AI inference metrics are not available yet.'}</p>
 <details class="hw-details hw-method"><summary>${ko?'자세한 데이터·계산 기준':'Detailed methodology'}</summary><p>${ko?'monster·junkshop·classroom 세 장면의 samples/min을 제출별로 합산한 뒤, 장치명·백엔드별 중앙값을 냈습니다. 단일 장치·단일 CPU 소켓의 완전한 제출만 사용하며 최소 표본은 3개입니다. OS는 합쳐져 있고 클럭·전력·드라이버·냉각 조건은 통제하지 않았습니다. 30일이 지난 데이터는 과거 스냅샷으로 보세요.':'Sum samples/min across monster, junkshop and classroom per submission, then take the median by device name and backend. Only complete single-device, single-socket submissions with at least 3 samples. OSes are pooled; clock, power, drivers and cooling are uncontrolled. Treat snapshots older than 30 days as historical.'}</p><a class="hw-text-link" href="https://opendata.blender.org/benchmarks/query/" target="_blank" rel="noopener noreferrer">${ko?'원본 결과 검색':'Explore original results'} ↗</a></details></section><section class="box hw-section"><h2>${ko?'구매 전에':'Before buying'}</h2><p>${ko?'구매 국가의 중고장터에서 같은 모델·상태의 가격도 확인하세요.':'Check comparable used listings in your purchase country.'}</p><a class="hw-text-link" href="/${o.l}/hardware/used-prices/?country=${m.id}">${ko?'국가별 중고 시세':'Used prices by country'} ›</a><a class="hw-text-link" href="/${o.l}/hardware/?type=gpu">${ko?'GPU 공식 스펙':'GPU specifications'} ›</a></section></aside></div>`);
}
