// @ts-check
/** UI copy of the platform pages (ko/en). Data labels (properties, enums, verification) live in the
 * vertical configs and platform/labels.js; this file only holds chrome and panel wording. */

const S={
 ko:{
  search:'채널, 게임, 모델, GPU, 글 검색',searchIn:(/** @type {string} */ n)=>`${n} 채널에서 검색`,
  radar:'레이더',tools:'도구',login:'로그인',write:'글쓰기',home:'홈',allBest:'전체 베스트',allChannels:'전체 채널',
  channel:(/** @type {string} */ n)=>`${n} 채널`,followers:'구독',today:'오늘 글',posts:'글',follow:'구독',following:'✓ 구독 중',alerts:'알림 설정',
  live:'LIVE',wiki:(/** @type {string} */ n)=>`${n} 위키`,history:'기록',edit:'편집',docs:'위키 문서',official:'공식 링크',related:'관련 채널',toolsBox:'도구',
  trending:'지금 많이 말하는 것',newPosts:(/** @type {number} */ n)=>`↑ 새 글 ${n}개 · 눌러서 보기`,
  all:'전체',sortNew:'최신',sortHot:'인기',sortTop:'추천순',sortActivity:'최근 댓글',best:'★ 념글',
  colNo:'번호',colTitle:'제목',colAuthor:'글쓴이',colDate:'작성일',colViews:'조회',colUp:'추천',
  emptyBoard:'아직 글이 없습니다. 첫 글을 남겨 주세요.',emptyKind:'이 말머리에는 아직 글이 없습니다.',more:'더보기',prev:'이전',next:'다음',page:'페이지',
  bot:'레이더봇',anonymous:'탈퇴한 사용자',
  tier:{new:'',contributor:'◇ 기여자',trusted:'◆ 신뢰',maintainer:'⚑ 제작자',curator:'✎ 큐레이터'},
  bestRule:'★ 념글: 24시간 안에 추천 10 이상, 추천 비율 70% 이상',
  sourceChecked:(/** @type {string} */ d)=>`${d} 확인`,
  // post view
  list:'목록',editedAt:(/** @type {string} */ t)=>`(수정 ${t})`,up:'추천',down:'비추천',views:'조회',comments:'댓글',share:'공유',copyLink:'링크 복사',flag:'신고',
  commentsN:(/** @type {number} */ n)=>`댓글 ${n}`,byOrder:'등록순',byNew:'최신순',byTop:'추천순',writeComment:'댓글 입력 (로그인 필요)',submit:'등록',reply:'답글',op:'글쓴이',bestComment:'베스트',deletedComment:'삭제된 댓글입니다.',
  channelList:(/** @type {string} */ n)=>`${n} 채널 글 목록`,moreList:'목록 더 보기',
  report:{target:'대상',version:'버전',result:'결과',env:'환경',metrics:'측정값'},
  sameHere:'나도 같아요',notRepro:'재현 안 됨',
  needMore:(/** @type {number} */ n)=>`${n}명 더 확인하면 ● 커뮤니티 검증`,
  // front
  liveBest:'실시간 베스트',changingNow:'지금 바뀌는 것',changingNote:'레이더봇이 공식·자동 감지로 올린 소식 — 댓글로 확인과 제보',
  newReports:'새 리포트',openQuestions:'답을 기다리는 질문',popularChannels:'인기 채널',
  loginTitle:'Nerulio에 로그인',loginNote:'채널 구독, 변경 알림, 리포트·댓글 작성. 글 읽기는 로그인 없이 됩니다.',
  continueWith:(/** @type {string} */ p)=>`${p}로 계속`,
  frontEmpty:'아직 글이 없습니다.',
  // panels
  panel:{
   status:'서비스 상태',statusSrc:'공식 상태 페이지',noIncident:'보고된 장애 없음',incident:'장애 조사 중',resolved:'해결됨',statusOpen:'상태 페이지 ↗',
   statusNote:'상태 페이지의 장애 기록 기준 · 실시간 측정 아님',lastChecked:(/** @type {string} */ t)=>`${t} 확인`,
   justChanged:'방금 바뀐 것',justChangedSrc:'공식 발표 · 자동 감지',nothingNew:'최근 90일 동안 기록된 변경이 없습니다.',
   models:'지금 쓸 수 있는 모델',modelCol:'모델',ctxCol:'컨텍스트',priceCol:'API 입력 / 출력 (100만 토큰)',releasedCol:'출시',newBadge:'NEW',
   modelDocs:'모델·가격 문서',
   rollout:'롤아웃 중인 기능',haveIt:'있어요',notYet:'아직',reports:(/** @type {number} */ n)=>`리포트 ${n}`,rolloutNote:'Nerulio 사용자 리포트 기준 · 전체 통계 아님',noRollout:'지금 롤아웃 중으로 표시된 기능이 없습니다.',
   plans:'요금제 (월)',apps:'앱',developer:'개발자',provider:'제공사',priceNote:'세금 별도 · 공식 요금 페이지 기준',
   // game
   latestUpdate:'최신 업데이트',currentVersion:'현재 버전',previous:(/** @type {string} */ v,/** @type {number} */ d)=>`이전 ${v} · ${d}일 만`,patchNotes:'패치 노트 원문 ↗',noVersion:'수집된 업데이트 기록이 없습니다.',
   koreanOfficial:'공식 한국어',koreanPatch:'한글패치',noPatch:'등록된 한글패치 없음',patchAuthor:'제작자',linkOnly:'배포처로 이동',
   compatWith:(/** @type {string} */ v)=>`${v} 호환`,works:'✓ 작동',partial:'◐ 일부',broken:'✕ 안 됨',thisWeek:'이번 주',noEvents:'예정된 공식 일정 없음',
   compatTable:'한글패치 호환표',lastUpdate:'마지막 업데이트',
   // gpu
   driver:'최신 드라이버',driverOk:'업데이트 후 괜찮나요?',noProblem:'문제 없음',problem:'문제 있음',noDriver:'드라이버 정보 없음',
   localAi:'이 카드로 로컬 AI',estimateMethod:'≈ 추정 · 방법 보기',fits:'맞음',tight:'빠듯함',noFit:'안 맞음',measured:(/** @type {number} */ n)=>`측정 ${n}건`,noMeasure:'측정 리포트 없음',
   benchBoard:'커뮤니티 벤치 보드',benchNote:'환경이 제각각 — 중앙값과 건수를 함께 봄',benchEmpty:'아직 벤치 리포트가 없습니다. 첫 측정을 올려 주세요.',task:'모델',setting:'설정',median:'중앙값',count:'건수',
   similar:'비슷한 카드',postBench:'벤치 올리기',
   // studio
   upgrade:'업그레이드해도 될까?',osCompat:'OS 호환',pluginCompat:'플러그인 호환',latestVersion:'최신 버전',plugins:(/** @type {number} */ n)=>`이 앱에서 쓰는 플러그인 ${n}개`,
   // ip
   nextUp:'다음 일정',countdown:{d:'일',h:'시간',m:'분'},schedule:'다가오는 일정',goods:'굿즈 · 예약 현황',goodsNote:'제조사 공식 상품 페이지만',preorderEnds:(/** @type {string} */ d)=>`마감 ${d}`,releases:(/** @type {string} */ d)=>`발매 ${d}`,
   cast:'등장인물 · 성우',worksList:'작품',noUpcoming:'발표된 다음 일정이 없습니다.',
   facts:'정보',
  },
  kind:{notice:'공지',news:'소식',report:'리포트',patch:'한글패치',question:'질문',guide:'공략',benchmark:'벤치',screenshot:'스샷',free:'자유'},
 },
 en:{
  search:'Search channels, games, models, GPUs, posts',searchIn:(/** @type {string} */ n)=>`Search in ${n}`,
  radar:'Radar',tools:'Tools',login:'Sign in',write:'Write',home:'Home',allBest:'Best of all',allChannels:'All channels',
  channel:(/** @type {string} */ n)=>n,followers:'followers',today:'posts today',posts:'posts',follow:'Follow',following:'✓ Following',alerts:'Alerts',
  live:'LIVE',wiki:(/** @type {string} */ n)=>`${n} wiki`,history:'History',edit:'Edit',docs:'Wiki pages',official:'Official links',related:'Related channels',toolsBox:'Tools',
  trending:'Talked about now',newPosts:(/** @type {number} */ n)=>`↑ ${n} new posts · show`,
  all:'All',sortNew:'New',sortHot:'Hot',sortTop:'Top',sortActivity:'Active',best:'★ Best',
  colNo:'No.',colTitle:'Title',colAuthor:'Author',colDate:'Date',colViews:'Views',colUp:'Up',
  emptyBoard:'No posts yet. Start the first one.',emptyKind:'No posts with this tag yet.',more:'More',prev:'Previous',next:'Next',page:'Page',
  bot:'Radar bot',anonymous:'Deleted user',
  tier:{new:'',contributor:'◇ Contributor',trusted:'◆ Trusted',maintainer:'⚑ Maintainer',curator:'✎ Curator'},
  bestRule:'★ Best: 10+ upvotes and 70%+ upvote ratio within 24 hours',
  sourceChecked:(/** @type {string} */ d)=>`checked ${d}`,
  list:'List',editedAt:(/** @type {string} */ t)=>`(edited ${t})`,up:'Up',down:'Down',views:'views',comments:'comments',share:'Share',copyLink:'Copy link',flag:'Report',
  commentsN:(/** @type {number} */ n)=>`${n} comments`,byOrder:'Oldest',byNew:'Newest',byTop:'Top',writeComment:'Write a comment (sign-in required)',submit:'Post',reply:'Reply',op:'OP',bestComment:'Best',deletedComment:'This comment was deleted.',
  channelList:(/** @type {string} */ n)=>`More in ${n}`,moreList:'More posts',
  report:{target:'Target',version:'Version',result:'Result',env:'Setup',metrics:'Measured'},
  sameHere:'Same here',notRepro:'Can’t reproduce',
  needMore:(/** @type {number} */ n)=>`${n} more confirmation${n===1?'':'s'} for ● community verified`,
  liveBest:'Best right now',changingNow:'Changing now',changingNote:'News the Radar bot posted from official and auto-detected changes',
  newReports:'New reports',openQuestions:'Unanswered questions',popularChannels:'Popular channels',
  loginTitle:'Sign in to Nerulio',loginNote:'Follow channels, get change alerts, post reports and comments. Reading needs no account.',
  continueWith:(/** @type {string} */ p)=>`Continue with ${p}`,
  frontEmpty:'No posts yet.',
  panel:{
   status:'Service status',statusSrc:'Official status page',noIncident:'No reported incident',incident:'Investigating',resolved:'Resolved',statusOpen:'Status page ↗',
   statusNote:'From the status page’s incident history · not a live probe',lastChecked:(/** @type {string} */ t)=>`checked ${t}`,
   justChanged:'Just changed',justChangedSrc:'Official · auto-detected',nothingNew:'No recorded changes in the last 90 days.',
   models:'Models available now',modelCol:'Model',ctxCol:'Context',priceCol:'API input / output (per 1M tokens)',releasedCol:'Released',newBadge:'NEW',
   modelDocs:'Models & pricing docs',
   rollout:'Rolling out',haveIt:'I have it',notYet:'Not yet',reports:(/** @type {number} */ n)=>`${n} reports`,rolloutNote:'Nerulio user reports · not population statistics',noRollout:'No feature is marked as rolling out right now.',
   plans:'Plans (monthly)',apps:'Apps',developer:'Developers',provider:'Provider',priceNote:'Tax not included · from the official pricing page',
   latestUpdate:'Latest update',currentVersion:'Current version',previous:(/** @type {string} */ v,/** @type {number} */ d)=>`previous ${v} · ${d} days before`,patchNotes:'Patch notes ↗',noVersion:'No update history collected yet.',
   koreanOfficial:'Official Korean',koreanPatch:'Korean patch',noPatch:'No Korean patch listed',patchAuthor:'Author',linkOnly:'Link to the author only',
   compatWith:(/** @type {string} */ v)=>`with ${v}`,works:'✓ Works',partial:'◐ Issues',broken:'✕ Broken',thisWeek:'This week',noEvents:'No official events scheduled',
   compatTable:'Korean patch compatibility',lastUpdate:'Last update',
   driver:'Latest driver',driverOk:'Any problems after updating?',noProblem:'No problems',problem:'Problems',noDriver:'No driver data',
   localAi:'Local AI on this card',estimateMethod:'≈ Estimate · method',fits:'Fits',tight:'Tight',noFit:'No',measured:(/** @type {number} */ n)=>`${n} measured`,noMeasure:'No measurements yet',
   benchBoard:'Community benchmarks',benchNote:'Setups differ — read the median with the count',benchEmpty:'No benchmark reports yet. Post the first measurement.',task:'Model',setting:'Setup',median:'Median',count:'Reports',
   similar:'Similar cards',postBench:'Post a benchmark',
   upgrade:'Safe to upgrade?',osCompat:'OS compatibility',pluginCompat:'Plugin compatibility',latestVersion:'Latest version',plugins:(/** @type {number} */ n)=>`${n} plugins used in this app`,
   nextUp:'Next up',countdown:{d:'d',h:'h',m:'m'},schedule:'Upcoming',goods:'Merchandise & pre-orders',goodsNote:'Official product pages only',preorderEnds:(/** @type {string} */ d)=>`closes ${d}`,releases:(/** @type {string} */ d)=>`ships ${d}`,
   cast:'Characters & voices',worksList:'Works',noUpcoming:'No announced upcoming date.',
   facts:'Facts',
  },
  kind:{notice:'Notice',news:'News',report:'Report',patch:'Korean patch',question:'Question',guide:'Guide',benchmark:'Benchmark',screenshot:'Screenshot',free:'Talk'},
 },
};
/** @typedef {typeof S.ko} Strings */
/** @param {string} l @returns {Strings} */
export const t=l=>/** @type {any} */(S)[l]||S.en;
