import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {estimateTempo,estimateKey,fft,monoView} from '../src/audio-lab/analysis.js';
import {edit,loudness,nearestZeroCrossing,normalize,protectSamplePeakInPlace,shift,silenceBounds,validateAudio} from '../src/audio-lab/dsp.js';
import {encodeWav} from '../src/audio-lab/encode.js';
const sr=22050;
function music(bpm=120,seconds=16){const out=new Float32Array(sr*seconds),freqs=[[261.63,329.63,392],[349.23,440,523.25],[392,493.88,587.33],[261.63,329.63,392]];
 for(let i=0;i<out.length;i++){const t=i/sr,beat=Math.floor(t*bpm/60),phase=(t*bpm/60)%1,chord=freqs[Math.floor(t/4)%4],click=phase<.012?(.4*(1-phase/.012)*Math.sin(2*Math.PI*1800*t))*(beat%4===0?1.2:1):0;out[i]=.12*chord.reduce((a,f)=>a+Math.sin(2*Math.PI*f*t),0)+click;}return out;}
function tone(hz=440,seconds=2){return Float32Array.from({length:Math.round(sr*seconds)},(_,i)=>.2*Math.sin(2*Math.PI*hz*i/sr));}
function frequency(samples,sampleRate){let best={f:0,m:0};for(let f=180;f<1100;f+=.5){let re=0,im=0;for(let i=0;i<Math.min(samples.length,4096);i++){re+=samples[i]*Math.cos(2*Math.PI*f*i/sampleRate);im-=samples[i]*Math.sin(2*Math.PI*f*i/sampleRate);}const m=re*re+im*im;if(m>best.m)best={f,m};}return best.f;}
test('radix FFT locates a bin-aligned sine',()=>{const re=Float64Array.from({length:1024},(_,i)=>Math.sin(2*Math.PI*32*i/1024)),im=new Float64Array(1024);fft(re,im);const peak=Array.from(re.slice(0,512),(_,i)=>Math.hypot(re[i],im[i])).indexOf(Math.max(...Array.from(re.slice(0,512),(_,i)=>Math.hypot(re[i],im[i]))));assert.equal(peak,32);});
test('known 120 BPM and C major fixture, including half-time alternative',()=>{const x=music(),t=estimateTempo(x,sr),k=estimateKey(x,sr);assert.ok(Math.abs(t.bpm-120)<1,JSON.stringify(t));assert.ok(t.candidates.some(n=>Math.abs(n-60)<1));assert.equal(k.key,'C major');assert.ok(k.confidence>0&&k.confidence<1);});
test('CC0 WAV corpus is intact and constructed tempo/key cases meet the stated synthetic gate',()=>{
 const dir=new URL('./fixtures/audio-lab/',import.meta.url),manifest=JSON.parse(readFileSync(new URL('manifest.json',dir),'utf8'));
 assert.equal(manifest.cases.length,13);
 for(const entry of manifest.cases){const bytes=readFileSync(new URL(entry.file,dir));assert.equal(createHash('sha256').update(bytes).digest('hex'),entry.sha256,entry.file);assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.readUInt32LE(24),sr);const n=bytes.readUInt32LE(40)/2,x=new Float32Array(n);for(let i=0;i<n;i++)x[i]=bytes.readInt16LE(44+i*2)/32768;
  const tempo=estimateTempo(x,sr),key=estimateKey(x,sr);if(entry.constructionTempoBpm!==null)assert.ok(Math.abs(tempo.bpm-entry.constructionTempoBpm)<=1,`${entry.file}: ${tempo.bpm}`);else assert.equal(tempo.bpm,null,entry.file);
  assert.equal(key.key,entry.constructionKey,entry.file);
 }
});
test('silent and short inputs report uncertainty',()=>{assert.equal(estimateTempo(new Float32Array(sr),sr).reason,'too-short');assert.equal(estimateKey(new Float32Array(sr*3),sr).key,null);assert.throws(()=>validateAudio([new Float32Array(sr*181)],sr),/3 minute/);});
test('non-finite decoded samples fail before analysis or export',()=>{const x=Float32Array.of(0,NaN,1);assert.throws(()=>validateAudio([x],sr),/non-finite/);assert.throws(()=>edit([x],sr),/non-finite/);});
test('a single sustained pitch is not assigned a major or minor key',()=>{const result=estimateKey(tone(440,4),sr);assert.equal(result.key,null);assert.equal(result.reason,'insufficient-harmony');});
test('opposed stereo channels keep an analyzable signal',()=>{const left=tone(440,2),right=Float32Array.from(left,v=>-v),mono=monoView([left,right]);assert.ok(mono.reduce((p,v)=>p+v*v,0)>100);});
test('speed changes length while preserving a steady tone',()=>{const out=shift([tone()],{speed:1.5,semitones:0})[0];assert.ok(Math.abs(out.length/sr-2/1.5)<.001);assert.ok(Math.abs(1200*Math.log2(frequency(out.subarray(4000,15000),sr)/440))<10);});
test('slowed export is rejected before allocating more than the output budget',()=>{const source=new Float32Array(sr*100);assert.throws(()=>edit([source],sr,{start:0,end:100,speed:.5}),/Output exceeds/);});
test('pitch raises a tone without changing length',()=>{const out=shift([tone()],{speed:1,semitones:12})[0];assert.ok(Math.abs(out.length/sr-2)<.001);assert.ok(Math.abs(1200*Math.log2(frequency(out.subarray(4000,15000),sr)/880))<10);});
test('moderate WSOLA speed change keeps impulse onsets within 20 ms',()=>{const x=new Float32Array(sr*4);for(let sec=0;sec<4;sec++)for(let i=0;i<200;i++)x[sec*sr+i]=.8*Math.exp(-i/20);for(const speed of [.8,1.2]){const y=shift([x],{speed})[0];for(let sec=1;sec<4;sec++){const expected=sec/speed,from=Math.max(0,Math.round((expected-.05)*sr)),to=Math.min(y.length,Math.round((expected+.05)*sr));let best=from;for(let i=from+1;i<to;i++)if(y[i]>y[best])best=i;assert.ok(Math.abs(best/sr-expected)<.02,`${speed}x beat ${sec}: ${best/sr-expected}s`);}}});
test('trim, silence bounds and fades are explicit',()=>{const x=new Float32Array(sr*2);x.set(tone(440,1),sr/2);const bound=silenceBounds([x],sr,{padMs:0});assert.ok(Math.abs(bound.start/sr-.5)<.02);assert.ok(Math.abs(bound.end/sr-1.5)<.02);const y=edit([x],sr,{start:0,end:2,removeSilence:true,fadeIn:.1,fadeOut:.1})[0];assert.ok(Math.abs(y.length/sr-1)<.05);assert.equal(y[0],0);assert.ok(Math.abs(y.at(-1))<1e-4);});
test('silence trim refuses an empty export with an actionable error',()=>{assert.throws(()=>edit([new Float32Array(sr)],sr,{removeSilence:true}),/Selected range is silent/);});
test('zero crossing snap reduces trimmed edge discontinuity and stays local',()=>{const x=tone(440,1),a=Math.round(.101*sr),b=Math.round(.777*sr),left=nearestZeroCrossing([x],sr,a),right=nearestZeroCrossing([x],sr,b);assert.ok(Math.abs(left-a)<=sr*.01);assert.ok(Math.abs(right-b)<=sr*.01);const raw=edit([x],sr,{start:a/sr,end:b/sr})[0],snapped=edit([x],sr,{start:a/sr,end:b/sr,snapToZero:true})[0];assert.ok(Math.abs(snapped[0])<Math.abs(raw[0])+.005);assert.ok(Math.abs(snapped.at(-1))<Math.abs(raw.at(-1))+.005);});
test('LUFS meter is finite, silent material is unmeasurable, normalization limits peak',()=>{const x=tone(440,2),m=loudness([x],sr);assert.ok(Number.isFinite(m.integrated));assert.equal(loudness([new Float32Array(sr)],sr).integrated,null);const n=normalize([x],sr,{targetLufs:-14,ceilingDb:-1});assert.ok(n.after.integrated>m.integrated);assert.ok(Math.abs(n.after.integrated+14)<.2);assert.ok(n.channels[0].every(Number.isFinite));assert.ok(n.channels[0].reduce((a,v)=>Math.max(a,Math.abs(v)),0)<=10**(-1/20)+1e-6);});
test('momentary, short-term and short-clip peak are reported separately',()=>{const x=tone(440,4),m=loudness([x],sr);assert.ok(Math.abs(m.momentary-m.integrated)<.2);assert.ok(Math.abs(m.shortTerm-m.integrated)<.2);const short=loudness([tone(440,.2)],sr);assert.equal(short.integrated,null);assert.equal(short.shortTerm,null);assert.ok(Number.isFinite(short.samplePeak));});
test('floating-point decoder over-peak is reduced before integer or lossy export',()=>{const x=Float32Array.of(-1.31,.4,1.27),result=protectSamplePeakInPlace([x]);assert.ok(result.inputPeakDb>0&&result.appliedDb<0);assert.ok(Math.max(...x.map(Math.abs))<=1+1e-6);assert.equal(protectSamplePeakInPlace([x]).appliedDb,0);});
test('WAV output has independently readable PCM header and exact frames',()=>{const bytes=encodeWav([tone(440,1)],sr),d=new DataView(bytes.buffer);assert.equal(String.fromCharCode(...bytes.slice(0,4)),'RIFF');assert.equal(d.getUint32(4,true),bytes.length-8);assert.equal(d.getUint16(20,true),1);assert.equal(d.getUint32(24,true),sr);assert.equal(d.getUint32(40,true),sr*2);assert.ok(d.getInt16(44+Math.floor(sr/4)*2,true)>-32768);});
