import test from 'node:test';
import assert from 'node:assert/strict';
import {estimateTempo,estimateKey,fft} from '../src/audio-lab/analysis.js';
import {edit,loudness,normalize,shift,silenceBounds,validateAudio} from '../src/audio-lab/dsp.js';
const sr=22050;
function music(bpm=120,seconds=16){const out=new Float32Array(sr*seconds),freqs=[[261.63,329.63,392],[349.23,440,523.25],[392,493.88,587.33],[261.63,329.63,392]];
 for(let i=0;i<out.length;i++){const t=i/sr,beat=Math.floor(t*bpm/60),phase=(t*bpm/60)%1,chord=freqs[Math.floor(t/4)%4],click=phase<.012?(.4*(1-phase/.012)*Math.sin(2*Math.PI*1800*t))*(beat%4===0?1.2:1):0;out[i]=.12*chord.reduce((a,f)=>a+Math.sin(2*Math.PI*f*t),0)+click;}return out;}
function tone(hz=440,seconds=2){return Float32Array.from({length:Math.round(sr*seconds)},(_,i)=>.2*Math.sin(2*Math.PI*hz*i/sr));}
function frequency(samples,sampleRate){let best={f:0,m:0};for(let f=180;f<1100;f+=.5){let re=0,im=0;for(let i=0;i<Math.min(samples.length,4096);i++){re+=samples[i]*Math.cos(2*Math.PI*f*i/sampleRate);im-=samples[i]*Math.sin(2*Math.PI*f*i/sampleRate);}const m=re*re+im*im;if(m>best.m)best={f,m};}return best.f;}
test('radix FFT locates a bin-aligned sine',()=>{const re=Float64Array.from({length:1024},(_,i)=>Math.sin(2*Math.PI*32*i/1024)),im=new Float64Array(1024);fft(re,im);const peak=Array.from(re.slice(0,512),(_,i)=>Math.hypot(re[i],im[i])).indexOf(Math.max(...Array.from(re.slice(0,512),(_,i)=>Math.hypot(re[i],im[i]))));assert.equal(peak,32);});
test('known 120 BPM and C major fixture, including half-time alternative',()=>{const x=music(),t=estimateTempo(x,sr),k=estimateKey(x,sr);assert.ok(Math.abs(t.bpm-120)<1,JSON.stringify(t));assert.ok(t.candidates.some(n=>Math.abs(n-60)<1));assert.equal(k.key,'C major');assert.ok(k.confidence>0&&k.confidence<1);});
test('silent and short inputs report uncertainty',()=>{assert.equal(estimateTempo(new Float32Array(sr),sr).reason,'too-short');assert.equal(estimateKey(new Float32Array(sr*3),sr).key,null);assert.throws(()=>validateAudio([new Float32Array(sr*181)],sr),/3 minute/);});
test('a single sustained pitch is not assigned a major or minor key',()=>{const result=estimateKey(tone(440,4),sr);assert.equal(result.key,null);assert.equal(result.reason,'insufficient-harmony');});
test('speed changes length while preserving a steady tone',()=>{const out=shift([tone()],{speed:1.5,semitones:0})[0];assert.ok(Math.abs(out.length/sr-2/1.5)<.001);assert.ok(Math.abs(frequency(out.subarray(4000,15000),sr)-440)<8);});
test('pitch raises a tone without changing length',()=>{const out=shift([tone()],{speed:1,semitones:12})[0];assert.ok(Math.abs(out.length/sr-2)<.001);assert.ok(Math.abs(frequency(out.subarray(4000,15000),sr)-880)<15);});
test('trim, silence bounds and fades are explicit',()=>{const x=new Float32Array(sr*2);x.set(tone(440,1),sr/2);const bound=silenceBounds([x],sr,{padMs:0});assert.ok(Math.abs(bound.start/sr-.5)<.02);assert.ok(Math.abs(bound.end/sr-1.5)<.02);const y=edit([x],sr,{start:0,end:2,removeSilence:true,fadeIn:.1,fadeOut:.1})[0];assert.ok(Math.abs(y.length/sr-1)<.05);assert.equal(y[0],0);assert.ok(Math.abs(y.at(-1))<1e-4);});
test('LUFS meter is finite, silent material is unmeasurable, normalization limits peak',()=>{const x=tone(440,2),m=loudness([x],sr);assert.ok(Number.isFinite(m.integrated));assert.equal(loudness([new Float32Array(sr)],sr).integrated,null);const n=normalize([x],sr,{targetLufs:-14,ceilingDb:-1});assert.ok(n.after.integrated>m.integrated);assert.ok(Math.abs(n.after.integrated+14)<.2);assert.ok(n.channels[0].every(Number.isFinite));assert.ok(n.channels[0].reduce((a,v)=>Math.max(a,Math.abs(v)),0)<=10**(-1/20)+1e-6);});
