import test from 'node:test';import assert from 'node:assert/strict';
import {integer,dimensions,safeName,fit,parsePages,route,paletteOf,quantize,removeConnected,addOutline,inversePoint,crc32,zip,gif,typeOf} from '../src/core.js';
import {ROUTES,entry} from '../tools/build.mjs';
const data=(list)=>new Uint8ClampedArray(list.flat());
test('integer rejects invalid sizes',()=>{for(const x of [NaN,-1,0,513,4.5])assert.throws(()=>integer(x,1,512));assert.equal(integer('32',1,512),32);});
test('pixel and side limits',()=>{assert.throws(()=>dimensions(8193,1));assert.throws(()=>dimensions(5000,5000));assert.deepEqual(dimensions(1024,768),{w:1024,h:768});});
test('safe names do not create paths',()=>{assert.equal(safeName('../a/b\\c.png'),'.._a_b_c.png');assert(!safeName('<script>').includes('<'));});
test('contain preserves ratio and pads',()=>{assert.deepEqual(fit(200,100,32,32),{w:32,h:16,x:0,y:8});});
test('cover fills and crops',()=>{assert.deepEqual(fit(200,100,32,32,true),{w:64,h:32,x:-16,y:0});});
test('page range and deduplication',()=>{assert.deepEqual(parsePages('1,3-5,3',5),[0,2,3,4]);assert.deepEqual(parsePages('',2),[0,1]);});
test('invalid ranges rejected',()=>{for(const s of ['0','2-1','1,a','1-9','1.5','-3'])assert.throws(()=>parsePages(s,5));});
for(const[p,e,t]of[['/image/compress/','image','export'],['/my-first-repo/image/pixel/','pixel',''],['/pdf/merge/','pdf',''],['/pdf/split','pdf','export'],['/pdf-to-jpg','pdf','export'],['/jpg-to-pdf','pdf',''],['/video/to-mp3/','media','export'],['/pixel','pixel',''],['/image/crop','image','crop'],['/image/remove-bg','image','background']])test(`route ${p}`,()=>{const r=route(p);assert.equal(r.editor,e);assert.equal(r.tool,t);});
test('route sanitizes query',()=>{const r=route('/pixel','?n=9999&format=exe&kb=-5');assert.equal(r.n,512);assert.equal(r.format,'png');assert.equal(r.kb,0);});
test('shared links reopen panel',()=>assert.equal(route('/image/editor','?tool=upscale').tool,'upscale'));
test('library aliases select real output format',()=>{assert.equal(route('/video/to-mp3').mediaFormat,'mp3');assert.equal(route('/pdf-to-jpg').pdfFormat,'jpeg');assert.equal(route('/pdf/compress').pdfRaster,true);});
test('file detection',()=>{assert.equal(typeOf({name:'PHOTO.HEIC'}),'image');assert.equal(typeOf({name:'a.PDF'}),'pdf');assert.equal(typeOf({name:'a.mp4'}),'media');assert.equal(typeOf({name:'bad.exe'}),null);});
test('palette count is bounded',()=>{const a=data([[255,0,0,255],[0,255,0,255],[0,0,255,255],[100,20,30,255]]);assert.equal(paletteOf(a,2).length,2);});
test('palette ignores fully transparent pixels',()=>assert.deepEqual(paletteOf(data([[255,0,0,0],[10,20,30,255]]),2),[[10,20,30]]));
test('quantize only emits requested colors',()=>{const a=new Uint8ClampedArray(16*16*4);for(let i=0;i<a.length;i+=4){a.set([(i*7)%256,(i*3)%256,i%256,255],i);}const out=quantize(a,16,16,8,1),set=new Set();for(let i=0;i<out.length;i+=4)set.add([...out.slice(i,i+3)].join(','));assert(set.size<=8);assert.equal(out.length,a.length);});
test('quantize clears transparent pixel RGB',()=>assert.deepEqual([...quantize(data([[255,0,0,0]]),1,1,8,1)],[0,0,0,0]));
test('unlimited palette preserves original alpha',()=>assert.deepEqual([...quantize(data([[1,2,3,77]]),1,1,0)], [1,2,3,77]));
test('background removal is boundary-connected',()=>{const a=new Uint8ClampedArray(5*5*4);for(let i=0;i<25;i++)a.set([255,255,255,255],i*4);for(const i of [6,7,8,11,13,16,17,18])a.set([0,0,0,255],i*4);const out=removeConnected(a,5,5,[255,255,255],0);assert.equal(out[3],0);assert.equal(out[12*4+3],255);assert.equal(out[6*4+3],255);});
test('outline does not overwrite subject',()=>{const a=new Uint8ClampedArray(3*3*4);a.set([255,0,0,255],16);const out=addOutline(a,3,3);assert.deepEqual([...out.slice(16,20)],[255,0,0,255]);assert.equal(out[3],255);});
test('rotation inverse points',()=>{assert.deepEqual(inversePoint(.2,.3,90),[.3,.8]);assert.deepEqual(inversePoint(.2,.3,180),[.8,.7]);assert.deepEqual(inversePoint(.2,.3,270),[.7,.2]);});
test('CRC-32 known vector',()=>assert.equal(crc32(new TextEncoder().encode('123456789')),0xcbf43926));
test('ZIP headers and case-insensitive uniqueness',async()=>{const b=await zip([{name:'a.png',blob:new Blob(['ABC'])},{name:'A.png',blob:new Blob(['DEF'])}]),a=new Uint8Array(await b.arrayBuffer()),v=new DataView(a.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint16(a.length-14,true),2);assert(new TextDecoder().decode(a).includes('A-2.png'));});
test('empty ZIP is rejected',async()=>assert.rejects(()=>zip([])));
test('GIF valid signature and terminator',()=>{const out=gif([data([[255,0,0,255],[0,255,0,255],[0,0,255,255],[255,255,255,255]])],2,2);assert.equal(new TextDecoder().decode(out.slice(0,6)),'GIF89a');assert.equal(out.at(-1),0x3b);});
for(const p of ROUTES)test(`static route base ${p}`,()=>{assert(entry('<base href="./">',p).includes('../'.repeat(p.split('/').length)));});
