import test from 'node:test';import assert from 'node:assert/strict';
import {outline,outlineMask,OUTLINE_MODES} from '../src/game/outline.js';
import {defringe,detectFringe,edgeClasses,HALO_TYPES} from '../src/game/defringe.js';
import {distanceField} from '../src/game/pixels.js';
import {canvas,box,disc,haloedSprite,walker,opaque,at} from './game-fixtures.mjs';
const rgba=(img,x,y)=>[...img.data.subarray((y*img.width+x)*4,(y*img.width+x)*4+4)];
const luma=([r,g,b])=>.2126*r+.7152*g+.0722*b;

test('an outer outline is exactly the band the distance says, with no blending',()=>{
 const img=canvas(11,11);box(img,5,5,1,1,[200,50,50,255]);
 const one=outline(img,{radius:1,colour:[0,0,0,255]});
 assert.deepEqual([one.width,one.height,one.offsetX],[11,11,0]);
 assert.deepEqual(rgba(one,5,5),[200,50,50,255],'the sprite itself is untouched');
 assert.deepEqual(rgba(one,4,5),[0,0,0,255]);
 assert.deepEqual(rgba(one,4,4),[0,0,0,255],'8-connectivity fills the diagonal');
 assert.deepEqual(rgba(one,3,5),[0,0,0,0],'and stops at the radius');
 assert.equal(one.changed,8,'a 1px 8-connected ring around one pixel is 8 pixels');
 const four=outline(img,{radius:1,connectivity:4});
 assert.deepEqual(rgba(four,4,4),[0,0,0,0],'4-connectivity leaves the diagonal alone');
 assert.equal(four.changed,4);
 assert.equal(outline(img,{radius:2,connectivity:8}).changed,24,'radius 2 Chebyshev is a 5x5 square minus the pixel');
 assert.equal(outline(img,{radius:2,connectivity:4}).changed,12,'radius 2 Manhattan is a diamond');
 assert.deepEqual(OUTLINE_MODES,['outer','inner','both']);
});
test('outlines never anti-alias: every painted pixel holds the exact colour given',()=>{
 const img=canvas(24,24);disc(img,12,12,7,[30,200,120,255]);
 const out=outline(img,{radius:2,colour:[17,34,51,200]});
 const painted=new Set();
 for(let y=0;y<24;y++)for(let x=0;x<24;x++)if(out.mask[y*24+x]===1)painted.add(rgba(out,x,y).join());
 assert.deepEqual([...painted],['17,34,51,200'],'one colour, one alpha, no gradient');
 assert.throws(()=>outline(img,{colour:[1,2]}),/\[r,g,b\]/);
 assert.throws(()=>outline(img,{colour:[1,2,3,300]}),/bytes/);
 assert.throws(()=>outline(img,{radius:0}),/1…64/);
 assert.throws(()=>outline(img,{radius:1.5}),/whole pixels/);
 assert.throws(()=>outline(img,{mode:'glow'}),/Outline mode/);
 assert.throws(()=>outline(img,{connectivity:6}),/Connectivity is 4 or 8/);
});
test('expand grows the canvas so an edge-touching sprite is not clipped',()=>{
 const img=canvas(8,8);box(img,0,0,8,8,[255,255,255,255]);
 const tight=outline(img,{radius:2});
 assert.equal(tight.changed,0,'a sprite filling its canvas has nowhere to put an outer outline');
 const grown=outline(img,{radius:2,expand:true});
 assert.deepEqual([grown.width,grown.height,grown.offsetX,grown.offsetY],[12,12,2,2]);
 assert.deepEqual(grown.grown,{left:2,top:2,right:2,bottom:2});
 assert.deepEqual(rgba(grown,2,2),[255,255,255,255],'the original sits at the offset');
 assert.deepEqual(rgba(grown,0,0),[0,0,0,255]);
 assert.equal(grown.changed,12*12-8*8);
 assert.equal(outline(img,{radius:2,mode:'inner',expand:true}).width,8,'an inner outline needs no room');
});
test('an inner outline recolours the sprite edge and leaves the silhouette alone',()=>{
 const img=canvas(12,12);box(img,2,2,8,8,[10,120,240,255]);
 const inner=outline(img,{radius:1,mode:'inner',colour:[255,255,0,255]});
 assert.deepEqual(rgba(inner,2,2),[255,255,0,255]);
 assert.deepEqual(rgba(inner,3,3),[10,120,240,255],'one pixel in is still the body');
 assert.equal(opaque({data:inner.data,width:12,height:12}),64,'the silhouette is unchanged');
 assert.equal(inner.changed,64-36,'the 8x8 block loses its 6x6 core to the band');
 const both=outline(img,{radius:1,mode:'both',colour:[0,0,0,255],innerColour:[255,255,255,255]});
 assert.deepEqual(rgba(both,1,1),[0,0,0,255],'outside band');
 assert.deepEqual(rgba(both,2,2),[255,255,255,255],'inside band uses innerColour');
 assert.deepEqual([...new Set(both.mask)].sort(),[0,1,2],'the mask says which band a pixel belongs to');
 const preview=outlineMask(img,{radius:1,mode:'both'});
 assert.equal(preview.count,both.changed);
});
test('a white-haloed sprite is detected as a white halo, with the numbers behind it',()=>{
 const img=haloedSprite();
 const found=detectFringe(img);
 assert.equal(found.type,'white',JSON.stringify(found));
 assert(found.delta>20,`the edge is much lighter than the interior (${found.delta.toFixed(1)})`);
 assert(found.confidence>.4);
 assert(found.edgePixels>20&&found.interiorPixels>200);
 assert.deepEqual(HALO_TYPES,['none','white','black','colour']);
 const dark=detectFringe(haloedSprite({halo:[0,0,0],body:[200,200,120]}));
 assert.equal(dark.type,'black');assert(dark.delta<-20);
 const clean=canvas(20,20);disc(clean,10,10,7,[40,90,60,255]);
 assert.equal(detectFringe(clean).type,'none');
 assert.match(detectFringe(clean).reason,/Too few partly transparent/);
 assert.throws(()=>edgeClasses(img,{solidAlpha:4}),/above the transparency threshold/);
});
test('de-fringing drops the edge luminance toward the interior and touches no alpha byte',()=>{
 const img=haloedSprite();
 const before=detectFringe(img);
 const fixed=defringe(img,{radius:3});
 assert.equal(fixed.alphaUnchanged,true);
 for(let i=3;i<img.data.length;i+=4)assert.equal(fixed.data[i],img.data[i]);
 assert(fixed.after.meanEdgeLuma<before.meanEdgeLuma,`edge luma ${before.meanEdgeLuma.toFixed(1)} → ${fixed.after.meanEdgeLuma.toFixed(1)}`);
 assert(Math.abs(fixed.after.delta)<Math.abs(before.delta)/4,`the gap to the interior shrank by more than 4x (${before.delta.toFixed(1)} → ${fixed.after.delta.toFixed(1)})`);
 assert(fixed.after.meanEdgeLuma-fixed.after.meanInteriorLuma<6,'the edge now reads as the same colour as the interior');
 assert.equal(fixed.after.type,'none','and no halo is detected any more');
 assert(fixed.changed.count>20&&fixed.changed.maxDelta>40);
 assert.equal(fixed.changed.mask.length,img.width*img.height);
 assert.equal(fixed.width,img.width);
});
test('strength blends, bleed reaches the transparent pixels, and a flat sprite is a no-op',()=>{
 const img=haloedSprite();
 const half=defringe(img,{radius:3,strength:.5}),full=defringe(img,{radius:3,strength:1});
 assert(half.after.meanEdgeLuma>full.after.meanEdgeLuma&&half.after.meanEdgeLuma<detectFringe(img).meanEdgeLuma,'half strength lands between');
 assert.equal(defringe(img,{radius:2,strength:0}).changed.count,0,'zero strength changes nothing');
 const bled=defringe(img,{radius:3,bleed:true});
 assert(bled.changed.count>full.changed.count,'bleeding also rewrites fully transparent pixels');
 for(let i=3;i<img.data.length;i+=4)assert.equal(bled.data[i],img.data[i],'still not one alpha byte');
 const flat=canvas(16,16);box(flat,4,4,8,8,[90,90,90,255]);
 const noop=defringe(flat,{radius:2});
 assert.equal(noop.changed.count,0);
 assert(noop.warnings.some(w=>/No halo was detected/.test(w)));
 const soft=canvas(8,8);for(let p=0;p<64;p++)soft.data.set([255,0,0,120],p*4);
 assert(defringe(soft).warnings.some(w=>/no interior colour/.test(w)));
 assert.throws(()=>defringe(img,{strength:2}),/0…1/);
 assert.throws(()=>defringe(img,{radius:0}),/1…64/);
});
test('a coloured halo is corrected per channel, not just darkened',()=>{
 const img=haloedSprite({halo:[20,40,255],body:[210,160,40]});
 const before=detectFringe(img);
 assert(['colour','black'].includes(before.type),`a blue rim on a warm body is not "white" (${before.type})`);
 const fixed=defringe(img,{radius:3});
 const chan=i=>{const vals=[];for(let p=0;p<img.width*img.height;p++){const a=img.data[p*4+3];if(a>8&&a<250)vals.push(fixed.data[p*4+i]);}return vals.reduce((s,v)=>s+v,0)/vals.length;};
 assert(chan(2)<80,`the blue the backdrop left is gone (mean blue ${chan(2).toFixed(1)})`);
 assert(chan(0)>150,`and the body's own red is what took its place (mean red ${chan(0).toFixed(1)})`);
 assert.equal(fixed.alphaUnchanged,true);
});
test('the shared distance field is Chebyshev at 8 and Manhattan at 4',()=>{
 const bits=new Uint8Array(25);bits[12]=1;
 const eight=distanceField({bits,width:5,height:5},{radius:2});
 assert.equal(eight.dist[0],2,'the far corner is two diagonal steps');
 const four=distanceField({bits,width:5,height:5},{radius:2,connectivity:4});
 assert.equal(four.dist[0],-1,'and four Manhattan steps, so out of range');
 assert.equal(four.dist[2],2);
 assert.equal(eight.order.length,24);assert.equal(eight.seeds.length,1);
 assert.throws(()=>distanceField({bits,width:5,height:5},{radius:-1}),/0…4096/);
});
