import {modernMedia,releaseOutput} from '../src/media-modern.js';
import * as B from '../assets/vendor/mediabunny-1.58.1/mediabunny.min.mjs';
const base64=blob=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(blob);});
export async function run({largeFile}={}){const checks=[],rows=[],check=(s,b)=>{if(!b)throw Error(s);checks.push(s);},file=new File([await(await fetch('/test-results/quality/signal-1080p.mp4')).blob()],'signal.mp4',{type:'video/mp4'}),probe=await modernMedia('probe',file);rows.push({case:'codec support',...probe});check('input duration and dimensions',Math.abs(probe.duration-6)<.05&&probe.w===1920&&probe.h===1080&&probe.audio);
 let ticks=0;const timer=setInterval(()=>ticks++,10);try{for(const options of [{mode:'fast',format:'mp4',start:1,end:4},{mode:'precise',format:probe.mp4?'mp4':'webm',width:640,fps:24,start:1.25,end:3.75,preset:'balanced',bitrate:400000},{mode:'precise',format:probe.mp4?'mp4':'webm',width:640,fps:30,start:0,end:4,targetMB:.35},{format:'mp3',start:.5,end:4.5,audioBitrate:192},{format:'wav',start:.5,end:4.5,sampleRate:44100}]){const result=await modernMedia('convert',file,options);try{const r=result.report;check(`${options.mode||options.format} preserves audio`,r.audio);check(`${options.mode||options.format} duration`,Math.abs(r.duration-(options.end-options.start))<(options.mode==='fast'?1.1:.12));if(options.width&&!options.targetMB)check('compression actual size and resolution',r.w===640&&r.outputBytes<file.size);if(options.targetMB)check('measured target strategy produces near-target output',r.targetMet&&r.outputBytes<=options.targetMB*1024**2&&r.outputBytes>options.targetMB*1024**2*.2&&r.passes>=1&&r.w<=options.width&&r.w>=options.width/2);rows.push({case:options.targetMB?'target-size':options.mode||options.format,...r,_data:await base64(result.blob),_extension:options.format});}finally{await releaseOutput(result.blob);}}
 const silent=new File([await(await fetch('/test-results/quality/signal-60-noaudio.webm')).blob()],'silent.webm'),silentResult=await modernMedia('convert',silent,{mode:'precise',format:probe.mp4?'mp4':'webm',start:0,end:1,width:1280,fps:60});try{check('60 fps VP9 input without audio converts without invented audio',!silentResult.report.audio&&Math.abs(silentResult.report.duration-1)<.05);rows.push({case:'60fps-no-audio',decodedFramesExpected:60,...silentResult.report,_data:await base64(silentResult.blob),_extension:probe.mp4?'mp4':'webm'});}finally{await releaseOutput(silentResult.blob);}
 for(const options of [{case:'muted',mode:'precise',format:probe.mp4?'mp4':'webm',start:0,end:2,width:640,fps:30,mute:true},{case:'normalized',format:'mp3',start:.5,end:4.5,audioBitrate:192,normalize:true},{case:'faded',format:'mp3',start:.5,end:4.5,audioBitrate:192,fadeIn:1,fadeOut:1}]){
  const result=await modernMedia('convert',file,options);
  try{const r=result.report;
   if(options.mute)check('mute removes the audio track instead of silencing it',r.audio===false&&r.muted===true);
   if(options.normalize)check('audio normalisation scales by the measured peak',r.audioPeak>0&&r.audioPeak<.2&&r.audioGain>2);
   if(options.fadeIn)check('fades are applied without changing the section length',Math.abs(r.duration-4)<.12);
   rows.push({case:options.case,decodedFramesExpected:60,...r,_data:await base64(result.blob),_extension:options.format});
  }finally{await releaseOutput(result.blob);}}
 const four=new File([await(await fetch('/test-results/quality/signal-4k.mp4')).blob()],'4k.mp4'),frame=await modernMedia('frame',four,{time:1,format:'png'}),bitmap=await createImageBitmap(frame.blob);check('actual 4K frame preserves source dimensions',bitmap.width===3840&&bitmap.height===2160);bitmap.close();rows.push({case:'4K frame',...frame.report,outputBytes:frame.blob.size});
 const jpeg=await modernMedia('frame',four,{time:1,format:'jpeg'});check('frame format is honoured at source resolution',jpeg.report.format==='image/jpeg'&&jpeg.report.w===3840&&jpeg.blob.size<frame.blob.size);rows.push({case:'4K frame JPEG',...jpeg.report,outputBytes:jpeg.blob.size});
 const gif=await modernMedia('gif',file,{start:0,end:2,width:640,fps:12,colors:128,dither:0});check('GIF exceeds legacy 320px',gif.report.width===640&&gif.report.frames===24);rows.push({case:'GIF',...gif.report,_data:await base64(gif.blob),_extension:'gif'});
 const target=await modernMedia('gif',file,{start:0,end:2,width:480,fps:15,colors:256,targetMB:.25});
 try{check('GIF size target is reached by measured passes',target.report.targetMet&&target.report.outputBytes<=.25*1024**2&&target.report.passes>=1);rows.push({case:'GIF target',...target.report,_data:await base64(target.blob),_extension:'gif'});}finally{await releaseOutput(target.blob);}
 const fancy=await modernMedia('gif',file,{start:0,end:1,width:240,fps:10,colors:64,reverse:true,speed:2,crop:'1:1'});
 try{check('reversed, sped-up, square-cropped GIF keeps the planned frames',fancy.report.frames===5&&fancy.report.width===fancy.report.height&&fancy.report.reversed);rows.push({case:'GIF reverse',...fancy.report,_data:await base64(fancy.blob),_extension:'gif'});}finally{await releaseOutput(fancy.blob);}
 const estimate=await modernMedia('estimate',file,{start:0,end:2,width:640,fps:12,colors:128});check('GIF size estimate is within 25% of the encoded result',estimate.report.frames===gif.report.frames&&Math.abs(estimate.report.bytes-gif.report.outputBytes)<gif.report.outputBytes*.25);rows.push({case:'GIF estimate',...estimate.report,encodedBytes:gif.report.outputBytes});
 const strip=await modernMedia('thumbs',file,{start:0,end:6,count:8,width:120});check('timeline strip decodes one thumbnail per slot',strip.thumbs.length===8&&strip.thumbs.every(x=>x.blob.size>200));rows.push({case:'timeline strip',...strip.report,outputBytes:strip.thumbs.reduce((n,x)=>n+x.blob.size,0)});
 const abort=new AbortController();let canceled=false;const task=modernMedia('convert',file,{mode:'precise',format:'webm',start:0,end:6,width:1920},()=>abort.abort(),abort.signal);try{await task;}catch(e){canceled=e.name==='AbortError';}check('cancel closes conversion',canceled);check('UI timers advance',ticks>20);
 if(largeFile){const info=await modernMedia('probe',largeFile);check('actual large-file hour duration',largeFile.size>500*1024**2&&info.duration>=3599);const cut=await modernMedia('convert',largeFile,{format:'mp4',mode:'fast',start:3540,end:3600});try{check('late section of 1h file',Math.abs(cut.report.duration-60)<1&&cut.report.audio);rows.push({case:'actual 500MiB+ 1h ranged input and late remux',inputBytes:largeFile.size,inputDuration:info.duration,...cut.report});}finally{await releaseOutput(cut.blob);}}
 }finally{clearInterval(timer);}return {checks,rows,scope:'Synthetic testsrc2 + sine; output independently checked with FFprobe/Pillow by runner. Codec availability is environment-specific.'};}
