import {PDFWorkspace} from '../src/pdf.js';
import * as L from '../assets/vendor/pdf-lib-1.17.1/pdf-lib.esm.min.js';
import {canvas,blobOf,release} from '../src/image.js';
export async function run(){const checks=[],rows=[],check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);},doc=await L.PDFDocument.create(),font=await doc.embedFont(L.StandardFonts.Helvetica),photo=await createImageBitmap(await(await fetch('/tests/fixtures/astronaut.png')).blob()),c=canvas(2400,2400);c.getContext('2d').drawImage(photo,0,0,2400,2400);photo.close();const jpg=await doc.embedJpg(await(await blobOf(c,'image/jpeg',.99)).arrayBuffer());release(c);
 for(let i=0;i<320;i++){const p=doc.addPage([600,800]);p.drawText(`Searchable source page ${i+1}`,{x:40,y:760,size:20,font});p.drawRectangle({x:20,y:20,width:200,height:100,color:L.rgb(.2,.5,.9)});if(i<3)p.drawImage(jpg,{x:50,y:200,width:500,height:500});}doc.getPage(1).setRotation(L.degrees(90));doc.getPage(2).setCropBox(20,30,500,700);
 const file=new File([await doc.save()], '320-pages.pdf',{type:'application/pdf'}),w=new PDFWorkspace();let ticks=0;const timer=setInterval(()=>ticks++,10),start=performance.now();try{await w.add([file]);check('320 pages loaded without bitmap previews',w.pages.length===320&&w.pages.every(p=>!p.thumb));rows.push({case:'320-page open',inputBytes:file.size,elapsedMs:performance.now()-start,uiTimerTicks:ticks});check('PDF parsing does not block all UI timers',ticks>0);
 let renders=0;const get=w.sources[0].reader.getPage.bind(w.sources[0].reader);w.sources[0].reader.getPage=async n=>{renders++;return get(n);};const p=w.pages[0];p.marks=[{type:'text',text:'Native annotation',x:.1,y:.1,size:20,color:'#ff0000'},{type:'pen',points:[[.1,.2],[.5,.2]],size:3,color:'#ff0000'},{type:'rect',x:.1,y:.3,w:.2,h:.1,size:2,color:'#008800'},{type:'highlight',x:.1,y:.4,w:.3,h:.03,color:'#ffff00'}];w.pages[1].marks=[{type:'text',text:'Rotated annotation',x:.1,y:.1,size:20}];w.pages[2].marks=[{type:'text',text:'한글 日本語',x:.1,y:.1,size:20}];
 const before=performance.now(),optimized=await w.export({optimize:true,maxSide:1200,quality:.75});check('preserve export does not render pages',renders===0);console.log(JSON.stringify(w.lastReport));check('image optimization reduces actual PDF bytes',optimized.size<file.size);check('image object actually recompressed',w.lastReport.optimizedImages>0);const result=new PDFWorkspace();try{await result.add([new File([optimized],'result.pdf',{type:'application/pdf'})]);check('preserved page count',result.pages.length===320);for(const [i,text] of [[0,'Native annotation'],[1,'Rotated annotation'],[2,'한글 日本語'],[319,'Searchable source page 320']]){const page=await result.sources[0].reader.getPage(i+1),data=await page.getTextContent();check(`page ${i+1} searchable text`,data.items.map(x=>x.str).join(' ').includes(text));page.cleanup();}const native=await L.PDFDocument.load(await optimized.arrayBuffer());check('rotation and crop preserved',native.getPage(1).getRotation().angle===90&&native.getPage(2).getCropBox().x===20);const rendered=await result.render(result.pages[0],600);const red=rendered.getContext('2d').getImageData(Math.round(rendered.width*.25),Math.round(rendered.height*.2),1,1).data;check('native pen is at normalized source position',red[0]>220&&red[1]<80);release(rendered);}finally{await result.clear();}rows.push({case:'preserve compression and native annotations',...w.lastReport,inputBytes:file.size,outputBytes:optimized.size,elapsedMs:performance.now()-before});
 const groups=await w.split({mode:'groups',groups:'1-2; 320'});check('custom split groups preserve counts',(await L.PDFDocument.load(await groups[0].blob.arrayBuffer())).getPageCount()===2&&(await L.PDFDocument.load(await groups[1].blob.arrayBuffer())).getPageCount()===1);
 const raster=await w.export({range:'1',raster:true,maxSide:800});const rr=new PDFWorkspace();try{await rr.add([new File([raster],'raster.pdf',{type:'application/pdf'})]);const text=await(await rr.sources[0].reader.getPage(1)).getTextContent();check('aggressive mode honestly removes searchable text',text.items.length===0&&w.lastReport.textPreserved===false);}finally{await rr.clear();}
 const abort=new AbortController();abort.abort();try{await w.export({},()=>{},abort.signal);throw Error('did not cancel');}catch(e){check('PDF export cancellation',e.name==='AbortError');}
 }finally{clearInterval(timer);await w.clear();}return {checks,rows,scope:'320-page synthetic document; mixed JPEG, native text/vector, rotated/cropped pages and CJK annotations. Arbitrary real PDF fidelity remains unverified.'};}
