/** UI workspace copy (ko/en/ja), merged into the Studio strings under `ui` (and `group.ui`) so st()
 * finds it; tests/studio-ui.test.mjs checks key and placeholder parity. Guesses always say how sure
 * they are; nothing is called "AI". */
import {STUDIO_STRINGS} from '../../strings.js';
const sides=a=>({left:a[0],right:a[1],top:a[2],bottom:a[3]});
const states=a=>({normal:a[0],hover:a[1],pressed:a[2],disabled:a[3],focus:a[4]});
const presets=a=>({ascii:a[0],latin1:a[1],digits:a[2],'latin-ext-a':a[3],'cjk-punct':a[4],kana:a[5],'hangul-jamo':a[6],'ks-x-1001-hangul':a[7],'jis-x-0208-kanji-1':a[8],'hangul-all':a[9]});
const modes=a=>({bitmap:a[0],mono:a[1],sdf:a[2],psdf:a[3],msdf:a[4],mtsdf:a[5]});
export const UI_STRINGS={
en:{
 menu:'UI',modeLabel:'UI mode',
 mode:{nine:'9-Slice',states:'States',atlas:'Atlas',font:'Font'},
 modeHint:{nine:'Stretch borders, content padding, previews at every size',states:'Button states: hover, pressed, disabled, focus',atlas:'Split a UI sheet into elements',font:'Bitmap, SDF and MSDF game fonts from a font file or a glyph sheet'},
 tool:{edit:'Edit',editHint:'drag guides (9-Slice), move and draw elements (Atlas), pick glyphs (Font)'},
 panel:{main:'UI',nine:'9-Slice',preview:'Previews',kitExport:'Export UI kit',states:'Button states',live:'Live button',atlas:'Elements',fontSource:'Font source',charset:'Character set',render:'Atlas',metrics:'Metrics & kerning',fontExport:'Export font',textPreview:'Text preview'},
 list:{elements:'Elements',buttons:'Buttons',fonts:'Fonts'},
 conf:{high:'high confidence',medium:'medium confidence',low:'low confidence',none:'no evidence'},
 side:sides(['Left','Right','Top','Bottom']),
 stretch:{stretch:'Stretch','tile':'Tile','tile-fit':'Tile fit'},
 state:states(['Normal','Hover','Pressed','Disabled','Focus']),
 engine:{ideal:'Exact plan',godot:'Godot 4',unity:'Unity',css:'CSS border-image',phaser:'Phaser',pixi:'PixiJS',android:'Android 9-patch'},
 verify:{verified:'verified',partial:'partly verified',unverified:'unverified',na:'data'},
 nine:{
  noElements:'No elements yet. Drop a panel or button PNG, or split a sheet in Atlas.',pick:'Select an element to set its 9-slice.',useWhole:'Use “{name}” as one element',name:'Element name',
  chipOn:'9-slice L {l} R {r} T {t} B {b}',chipOff:'No 9-slice yet',
  suggested:'Suggested: L {l} · R {r} · T {t} · B {b}',apply:'Apply suggestion',applied:'Applied',
  whyCols:'{n} identical columns',whyRows:'{n} identical rows',whyPeriod:'{axis}: a pattern repeating every {p} px',whyNoneH:'no stretchable columns',whyNoneV:'no stretchable rows (a gradient?)',
  axisH:'Horizontal',axisV:'Vertical',tileSuggested:'The middle repeats: tile keeps the pattern intact.',noSuggestion:'No stretchable band found in the pixels. Drag the guides or type the borders.',
  stretchBorders:'Stretch borders (never scaled)',dragHint:'Drag the blue guides on the canvas · Shift = both sides · arrow keys nudge the last guide',
  paddingOn:'Separate content padding (where text and icons go)',paddingOff:'Content area = the stretch borders (Android and Godot default).',
  middle:'Middle',drawCenter:'Draw the centre',checks:'Checks',clean:'✓ No bad patches: the stretched bands are uniform.',notSet:'Set borders to check the stretched bands.',
  fixGuide:'Move guide to {v}',engineNumbers:'The same numbers per engine',clear:'Remove the 9-slice',
  guideHint:'drag: {what}',borders:'L {l} · R {r} · T {t} · B {b}',
  border:sides(['left stretch border','right stretch border','top stretch border','bottom stretch border']),padding:sides(['left content padding','right content padding','top content padding','bottom content padding'])},
 issue:{'gradient.h':'The horizontal band has {n} different columns: stretching distorts it. Use tile, or narrow the band.','gradient.v':'The vertical band has {n} different rows (a gradient?): stretching changes it. Use tile, or narrow the band.',
  'cut-corner':'{side}: the corner art continues {k} px past the guide, so part of the corner would stretch.','seam.h':'Tiling shows a seam: the band’s last column does not continue into its first (step {step}).','seam.v':'Tiling shows a seam: the band’s last row does not continue into its first (step {step}).',
  padding:'The content padding leaves no room for content.',empty:'This element is fully transparent.'},
 preview:{engine:'Draw as',scales:'DPI scales',custom:'Custom',customW:'Width',customH:'Height',content:'Content area',slices:'Slice lines',size:'Size',
  noMode:'{engine} has no {mode}: shown stretched',warn:{narrow:'narrower than its corners: corners squashed',short:'shorter than its corners: corners squashed',fractional:'fractional scale: corners are not whole pixels',tileLimit:'too many tiles: stretched'}},
 kit:{name:'File name',export:'Export {n} element(s)',exporting:'Exporting…',atlas:'Pack into one atlas (Godot, Unity, generic)',noNine:'{n} element(s) have no 9-slice yet and export as plain images.',done:'Exported {name} ({n} files)',
  target:{generic:'Generic JSON + PNG',godot:'Godot 4 StyleBoxTexture + Theme',unity:'Unity sprite borders (importer)',android:'Android .9.png',css:'CSS border-image',phaser:'Phaser NineSlice atlas',pixi:'PixiJS NineSliceSprite atlas'}},
 states:{none:'No buttons yet.',pick:'Select or make a button.',fromElement:'New button from “{name}”',needElement:'Select an element (9-Slice) to make a button from it.',
  suggest:'Button “{name}” with {states} (from file names)',suggestHint:'The file names say these images are states of one button. Nothing is paired until you click.',
  count:'{n} states',remove:'Remove {name}',source:'{state} comes from',none1:'— not used —',genFrom:'generated from {state}',name:'Button name',
  lead:'Each state is its own art or is generated from another state by the numbers below — nothing is invented.',
  borders:'borders L {l} R {r} T {t} B {b}',noBorders:'no 9-slice',grown:'canvas +{n} px each side',ownNoNine:'This state’s art has no 9-slice: set it in 9-Slice.',
  labelText:'Label',liveLabel:'Live button: hover, press, Tab to focus',liveHint:'Hover, press and Tab to it: it switches state like a real button.'},
 op:{brightness:'Brightness',contrast:'Contrast',saturation:'Saturation',alpha:'Opacity',offsetX:'Offset X',offsetY:'Offset Y',outline:'Outline px',outlineColor:'Outline colour',overlayColor:'Overlay colour',overlayAlpha:'Overlay'},
 atlas:{noImage:'Open a UI sheet image first.',lead:'Elements are alpha islands, joined when closer than the merge distance. Detection is a preview until you add it.',threshold:'Alpha >',merge:'Merge ≤ px',minArea:'Min area',
  detect:'Detect elements',detecting:'Detecting…',found:'{n} element(s) found ({islands} islands)',preview:'{n} detected (dashed)',previewHint:'Add the ones that do not overlap existing elements, or replace them all.',addNew:'Add {n}',replace:'Replace all',discard:'Discard',
  draw:'Draw element',suggestAll:'Suggest 9-slices for all',suggestSel:'Suggest 9-slices for {n} selected',editNine:'Edit 9-slice',delete:'Delete ({n})',count:'{n} element(s), {nine} with a 9-slice',
  noneConfident:'No element has a confident suggestion.',suggested:'Borders set on {n} of {of} element(s) (medium or high confidence).',noRegions:'This atlas file has no regions.',noSheet:'No image in the project matches this atlas file.',imported:'{n} element(s) from {name}',listHint:'Drag to move, handles resize; Draw element adds one.'},
 font:{none:'No fonts yet.',pick:'Select or add a font.',addFile:'Add font file…',fromImage:'Pixel font from “{name}”',fromSheet:'glyph sheet',remove:'Remove {name}',
  woff2:'WOFF2 is not supported: convert it to TTF or OTF first.',notFont:'Not a TTF, OTF, TTC or WOFF font.',bitmapOnly:'{name} has only embedded bitmaps (no outlines) and cannot be rendered.',needFontFirst:'Add a font first, then its translation files.',
  addedFiles:'{n} translation file(s), {strings} strings',gridFound:'Grid {w}×{h}, {n} glyphs ({conf}). Check the order below.',gridNone:'No clear glyph grid: type the cell size.',sheetGone:'The glyph sheet image is no longer in the project.',
  info:'{glyphs} glyphs · {cps} characters · {type} · Hangul {hangul} · kana {kana} · kanji {han}',pixelGrid:'Pixel font: {px} px grid — crisp at {sizes} px',pixelWhy:'every outline point is a multiple of {q} font units ({n} points in {g} glyphs)',usePixel:'Use {px} px, 1-bit',
  instance:'Named instance',licence:'Licence (from the font)',gridGuess:'Grid {w}×{h}, {c}×{r} cells',keyFound:'Background colour {color} made transparent ({conf}).',
  cellW:'Cell W',cellH:'Cell H',cols:'Columns',rows:'Rows',ox:'Offset X',oy:'Offset Y',sx:'Gap X',sy:'Gap Y',order:'Character order (one per cell)',orderAscii:'ASCII from space',orderAscii33:'ASCII from !',orderCount:'{n} characters for {cells} cells',
  measure:'Widths',measureInk:'Measured from ink',measureFixed:'Fixed cell width',baseline:'Baseline',lineHeight:'Line height',letterSpacing:'Letter spacing',spaceAdvance:'Space width',key:'Background colour',white:'White glyphs (tint in engine)',
  pageStatus:'page {n}/{of} · {w}×{h}',export:'Export font',binNoField:'Binary .fnt has no field for distance fields; skipped for this mode.',fntLater:'Opening an existing .fnt is not supported yet.',
  target:{'bmfont-text':'BMFont text .fnt','bmfont-xml':'BMFont XML .fnt','bmfont-bin':'BMFont binary .fnt','msdf-json':'msdf-atlas-gen JSON',godot:'Godot 4 FontFile',unity:'Unity TextMeshPro',phaser:'Phaser BitmapText',pixi:'PixiJS BitmapText'}},
 charset:{remove:'Remove',text:'Characters',strings:'{n} strings',newGlyphs:'+{n} glyphs',addFile:'Translation file…',addPreset:'Add a set…',addText:'Add text',strip:'Ignore placeholders and markup ({0}, %s, <b>, [color])',
  removed:'Removed: {list}',order:'Glyph order',byFrequency:'Most used first',byCode:'By code point',exclude:'Exclude',stats:'{n} glyphs · Latin {latin} · Hangul {hangul} · kana {kana} · kanji {han} · other {other}',
  missing:'{n} character(s) are not in the font',allPresent:'✓ The font has every character of the set.'},
 strip:{icu:'ICU',braces:'{…}',printf:'%…',dollar:'$…',markup:'<tags>',bbcode:'[tags]'},
 preset:presets(['ASCII (95)','Latin-1 (191)','Digits','Latin Extended-A','CJK punctuation','Kana (hiragana + katakana)','Hangul compatibility jamo','KS X 1001 Hangul (2,350)','JIS level 1 kanji (2,965)','All Hangul (11,172)']),
 render:{mode:'Render',m:modes(['Bitmap (smooth)','Pixel (1-bit)','SDF','PSDF','MSDF','MTSDF']),size:'Size (px/em)',range:'Distance range px',threshold:'1-bit threshold',padding:'Padding',spacing:'Spacing',page:'Page',sizeMode:'Page size',pot:'Power of two',auto:'Tight',fixed:'Fixed',kerning:'Kerning',alphaOnly:'Distance in alpha (TextMeshPro)',
  hint:modes(['Anti-aliased coverage, white glyphs in alpha.','Every pixel on or off: pixel fonts at their grid size stay crisp.','One-channel signed distance: scalable, rounds sharp corners.','Pseudo-distance: like SDF, better at edges.','Multi-channel: sharp corners at any size. Needs an MSDF shader.','MSDF + true distance in alpha (outlines, glow).']),
  gridNote:'A pixel font ships its sheet as drawn: the page is the image itself.',phase:{start:'Building…',render:'Rendering glyphs {done}/{total}',pack:'Packing {total} glyphs',encode:'Encoding pages'},
  result:'{g} glyphs · {p} page(s) of {w}×{h} · {eff}% used · {k} kerning pairs · {ms} ms',pageN:'Page {n}'},
 metrics:{line:'Line height {lh} · baseline {base} · ascender {asc} · descender {desc}',glyph:'Glyph {c} (U+{u})',xadvance:'Advance',xoffset:'X offset',yoffset:'Y offset',overridden:'Overridden by hand.',clickGlyph:'Click a glyph on the canvas to adjust it.',
  kerning:'Kerning pairs',kernCount:'{n} pair(s) from the font ({px} not zero at this size)',first:'First character',second:'Second character',amount:'Amount px',addPair:'Add pair',
  suggest:'Suggest pairs from glyph shapes',noSuggest:'No pair is looser than the typical gap.',suggested:'{n} pair(s) sit wider apart than the typical {gap} px gap',applyAll:'Add {n} pairs'},
 tp:{text:'Sample text',sizes:'Sizes px',color:'Colour',background:'Background',outline:'Outline',outlineColor:'Outline colour',shadow:'Shadow',raw:'Raw field',
  bitmapNote:'Drawn from the atlas like an engine: sharp at {size} px and whole multiples, filtered in between.',fieldNote:'Distance-field shader (range {range} px): sharp at every size.',missing:'{n} missing: {chars}',
  sample:'The quick brown fox jumps over the lazy dog. 0123456789',sampleKo:'새 게임 · 이어하기 · 설정 · 종료\n체력 100 / 공격 25 — 레벨 업!'},
 cmd:{import:'Import {n} file(s)',export:'Export',suggest:'Apply the suggestion',addFont:'Add font file…',moveGuide:'Move 9-slice guide',border:'Set border',padding:'Set content padding',stretch:'Set stretch mode',center:'Draw centre',
  applySuggestion:'Apply suggested borders',fixGuide:'Move guide',clearNine:'Remove 9-slice',addElement:'Add element',rename:'Rename',removeElement:'Remove {name}',removeElements:'Remove {n} element(s)',moveElement:'Move element',
  detected:'Add {n} detected element(s)',suggestAll:'Suggested borders for {n} element(s)',importAtlas:'Import {n} element(s) from {name}',kit:'Change UI kit export',newButton:'New button',removeButton:'Remove {name}',state:'Set {state} state',
  pixelFont:'Pixel font from image',removeFont:'Remove font {name}',addTranslations:'Add {n} translation file(s)',axis:'Set axis {axis}',grid:'Set glyph grid',order:'Set character order',key:'Set background colour',
  charset:'Change character set',render:'Change atlas settings',glyph:'Adjust glyph',kern:'Change kerning',exportName:'Change font export'},
 error:{missingBlob:'A file of this project is not loaded.',unsupported:'Not a file the UI workspace can open: {names}',multiRun:'{name} has several stretch runs on one side; the Studio keeps the outermost band.'}
},
ko:{
 menu:'UI',modeLabel:'UI 모드',
 mode:{nine:'9-슬라이스',states:'상태',atlas:'아틀라스',font:'폰트'},
 modeHint:{nine:'늘어나는 테두리, 콘텐츠 여백, 모든 크기의 미리보기',states:'버튼 상태: 호버, 눌림, 비활성, 포커스',atlas:'UI 시트를 요소로 나누기',font:'폰트 파일이나 글리프 시트로 비트맵·SDF·MSDF 게임 폰트 만들기'},
 tool:{edit:'편집',editHint:'가이드 드래그(9-슬라이스), 요소 이동·그리기(아틀라스), 글리프 선택(폰트)'},
 panel:{main:'UI',nine:'9-슬라이스',preview:'미리보기',kitExport:'UI 키트 내보내기',states:'버튼 상태',live:'실제 버튼',atlas:'요소',fontSource:'폰트 소스',charset:'문자 집합',render:'아틀라스',metrics:'메트릭 · 커닝',fontExport:'폰트 내보내기',textPreview:'텍스트 미리보기'},
 list:{elements:'요소',buttons:'버튼',fonts:'폰트'},
 conf:{high:'신뢰도 높음',medium:'신뢰도 중간',low:'신뢰도 낮음',none:'근거 없음'},
 side:sides(['왼쪽','오른쪽','위','아래']),
 stretch:{stretch:'늘이기','tile':'타일','tile-fit':'타일 맞춤'},
 state:states(['기본','호버','눌림','비활성','포커스']),
 engine:{ideal:'정확한 계획',godot:'Godot 4',unity:'Unity',css:'CSS border-image',phaser:'Phaser',pixi:'PixiJS',android:'Android 9-patch'},
 verify:{verified:'검증됨',partial:'일부 검증',unverified:'미검증',na:'데이터'},
 nine:{
  noElements:'아직 요소가 없습니다. 패널이나 버튼 PNG를 놓거나 아틀라스에서 시트를 나누세요.',pick:'9-슬라이스를 설정할 요소를 선택하세요.',useWhole:'“{name}” 전체를 요소로 사용',name:'요소 이름',
  chipOn:'9-슬라이스 L {l} R {r} T {t} B {b}',chipOff:'아직 9-슬라이스 없음',
  suggested:'제안: L {l} · R {r} · T {t} · B {b}',apply:'제안 적용',applied:'적용됨',
  whyCols:'똑같은 열 {n}개',whyRows:'똑같은 행 {n}개',whyPeriod:'{axis}: {p} px마다 반복되는 무늬',whyNoneH:'늘릴 수 있는 열 없음',whyNoneV:'늘릴 수 있는 행 없음(그라데이션?)',
  axisH:'가로',axisV:'세로',tileSuggested:'가운데가 반복됩니다: 타일로 두면 무늬가 그대로 유지됩니다.',noSuggestion:'픽셀에서 늘릴 수 있는 띠를 찾지 못했습니다. 가이드를 끌거나 숫자를 입력하세요.',
  stretchBorders:'늘어나는 테두리(크기가 바뀌지 않음)',dragHint:'캔버스의 파란 가이드를 끄세요 · Shift = 양쪽 함께 · 방향키로 마지막 가이드 미세 이동',
  paddingOn:'콘텐츠 여백 따로 지정(글자와 아이콘이 들어갈 곳)',paddingOff:'콘텐츠 영역 = 늘어나는 테두리(Android·Godot 기본값).',
  middle:'가운데',drawCenter:'가운데 그리기',checks:'점검',clean:'✓ 나쁜 패치 없음: 늘어나는 띠가 균일합니다.',notSet:'테두리를 정하면 늘어나는 띠를 점검합니다.',
  fixGuide:'가이드를 {v}로 이동',engineNumbers:'엔진별 같은 숫자',clear:'9-슬라이스 제거',
  guideHint:'드래그: {what}',borders:'L {l} · R {r} · T {t} · B {b}',
  border:sides(['왼쪽 늘이기 테두리','오른쪽 늘이기 테두리','위쪽 늘이기 테두리','아래쪽 늘이기 테두리']),padding:sides(['왼쪽 콘텐츠 여백','오른쪽 콘텐츠 여백','위쪽 콘텐츠 여백','아래쪽 콘텐츠 여백'])},
 issue:{'gradient.h':'가로 띠에 서로 다른 열이 {n}개 있어 늘이면 모양이 변합니다. 타일을 쓰거나 띠를 좁히세요.','gradient.v':'세로 띠에 서로 다른 행이 {n}개 있어(그라데이션?) 늘이면 달라집니다. 타일을 쓰거나 띠를 좁히세요.',
  'cut-corner':'{side}: 모서리 그림이 가이드 밖으로 {k} px 이어져 모서리 일부가 늘어납니다.','seam.h':'타일에 이음새가 보입니다: 띠의 마지막 열이 첫 열로 이어지지 않습니다(차이 {step}).','seam.v':'타일에 이음새가 보입니다: 띠의 마지막 행이 첫 행으로 이어지지 않습니다(차이 {step}).',
  padding:'콘텐츠 여백 때문에 내용이 들어갈 자리가 없습니다.',empty:'이 요소는 완전히 투명합니다.'},
 preview:{engine:'그리기 방식',scales:'DPI 배율',custom:'직접 입력',customW:'너비',customH:'높이',content:'콘텐츠 영역',slices:'슬라이스 선',size:'크기',
  noMode:'{engine}에는 {mode}가 없어 늘여서 표시합니다',warn:{narrow:'모서리보다 좁음: 모서리가 눌림',short:'모서리보다 낮음: 모서리가 눌림',fractional:'소수 배율: 모서리가 픽셀에 맞지 않음',tileLimit:'타일이 너무 많아 늘여서 표시'}},
 kit:{name:'파일 이름',export:'요소 {n}개 내보내기',exporting:'내보내는 중…',atlas:'하나의 아틀라스로 묶기(Godot, Unity, 범용)',noNine:'요소 {n}개는 아직 9-슬라이스가 없어 일반 이미지로 내보냅니다.',done:'{name} 내보냄(파일 {n}개)',
  target:{generic:'범용 JSON + PNG',godot:'Godot 4 StyleBoxTexture + Theme',unity:'Unity 스프라이트 테두리(임포터)',android:'Android .9.png',css:'CSS border-image',phaser:'Phaser NineSlice 아틀라스',pixi:'PixiJS NineSliceSprite 아틀라스'}},
 states:{none:'아직 버튼이 없습니다.',pick:'버튼을 선택하거나 만드세요.',fromElement:'“{name}”으로 새 버튼',needElement:'버튼으로 만들 요소를 선택하세요(9-슬라이스).',
  suggest:'버튼 “{name}”: {states} (파일 이름 기준)',suggestHint:'파일 이름으로 보아 한 버튼의 상태들입니다. 누르기 전에는 묶지 않습니다.',
  count:'상태 {n}개',remove:'{name} 삭제',source:'{state} 상태의 출처',none1:'— 사용 안 함 —',genFrom:'{state}에서 생성',name:'버튼 이름',
  lead:'각 상태는 따로 그린 그림이거나, 아래 숫자대로 다른 상태에서 만든 것입니다. 없는 그림을 지어내지 않습니다.',
  borders:'테두리 L {l} R {r} T {t} B {b}',noBorders:'9-슬라이스 없음',grown:'캔버스 양쪽 +{n} px',ownNoNine:'이 상태 그림에는 9-슬라이스가 없습니다. 9-슬라이스에서 설정하세요.',
  labelText:'글자',liveLabel:'실제 버튼: 호버, 누르기, Tab으로 포커스',liveHint:'마우스를 올리고 누르고 Tab으로 이동해 보세요. 실제 버튼처럼 상태가 바뀝니다.'},
 op:{brightness:'밝기',contrast:'대비',saturation:'채도',alpha:'불투명도',offsetX:'X 이동',offsetY:'Y 이동',outline:'외곽선 px',outlineColor:'외곽선 색',overlayColor:'덧칠 색',overlayAlpha:'덧칠'},
 atlas:{noImage:'먼저 UI 시트 이미지를 여세요.',lead:'요소는 알파 섬이며, 병합 거리보다 가까우면 합칩니다. 추가하기 전까지 감지는 미리보기입니다.',threshold:'알파 >',merge:'병합 ≤ px',minArea:'최소 면적',
  detect:'요소 감지',detecting:'감지 중…',found:'요소 {n}개 발견(섬 {islands}개)',preview:'{n}개 감지됨(점선)',previewHint:'기존 요소와 겹치지 않는 것만 추가하거나 전부 바꾸세요.',addNew:'{n}개 추가',replace:'전부 바꾸기',discard:'버리기',
  draw:'요소 그리기',suggestAll:'모두 9-슬라이스 제안',suggestSel:'선택한 {n}개 9-슬라이스 제안',editNine:'9-슬라이스 편집',delete:'삭제({n})',count:'요소 {n}개, 9-슬라이스 {nine}개',
  noneConfident:'확신할 만한 제안이 있는 요소가 없습니다.',suggested:'요소 {of}개 중 {n}개에 테두리를 설정했습니다(신뢰도 중간 이상).',noRegions:'이 아틀라스 파일에는 영역이 없습니다.',noSheet:'이 아틀라스 파일에 맞는 이미지가 프로젝트에 없습니다.',imported:'{name}에서 요소 {n}개',listHint:'드래그로 이동, 핸들로 크기 조절, 요소 그리기로 추가.'},
 font:{none:'아직 폰트가 없습니다.',pick:'폰트를 선택하거나 추가하세요.',addFile:'폰트 파일 추가…',fromImage:'“{name}”으로 픽셀 폰트',fromSheet:'글리프 시트',remove:'{name} 삭제',
  woff2:'WOFF2는 지원하지 않습니다. 먼저 TTF나 OTF로 바꾸세요.',notFont:'TTF, OTF, TTC, WOFF 폰트가 아닙니다.',bitmapOnly:'{name}에는 내장 비트맵만 있고 윤곽선이 없어 렌더링할 수 없습니다.',needFontFirst:'먼저 폰트를 추가한 다음 번역 파일을 넣으세요.',
  addedFiles:'번역 파일 {n}개, 문자열 {strings}개',gridFound:'격자 {w}×{h}, 글리프 {n}개({conf}). 아래 순서를 확인하세요.',gridNone:'뚜렷한 글리프 격자가 없습니다. 칸 크기를 입력하세요.',sheetGone:'글리프 시트 이미지가 프로젝트에 없습니다.',
  info:'글리프 {glyphs}개 · 문자 {cps}개 · {type} · 한글 {hangul} · 가나 {kana} · 한자 {han}',pixelGrid:'픽셀 폰트: {px} px 격자 — {sizes} px에서 선명',pixelWhy:'모든 윤곽점이 {q} 폰트 단위의 배수입니다(글리프 {g}개의 점 {n}개)',usePixel:'{px} px, 1비트로 사용',
  instance:'이름 있는 인스턴스',licence:'라이선스(폰트에 기록된 내용)',gridGuess:'격자 {w}×{h}, {c}×{r}칸',keyFound:'배경색 {color}을 투명하게 했습니다({conf}).',
  cellW:'칸 W',cellH:'칸 H',cols:'열',rows:'행',ox:'오프셋 X',oy:'오프셋 Y',sx:'간격 X',sy:'간격 Y',order:'문자 순서(칸마다 하나)',orderAscii:'공백부터 ASCII',orderAscii33:'!부터 ASCII',orderCount:'{cells}칸에 문자 {n}개',
  measure:'너비',measureInk:'잉크로 측정',measureFixed:'칸 너비 고정',baseline:'기준선',lineHeight:'줄 높이',letterSpacing:'자간',spaceAdvance:'공백 너비',key:'배경색',white:'흰 글리프(엔진에서 색 입히기)',
  pageStatus:'페이지 {n}/{of} · {w}×{h}',export:'폰트 내보내기',binNoField:'바이너리 .fnt에는 디스턴스 필드 항목이 없어 이 모드에서는 건너뜁니다.',fntLater:'기존 .fnt 열기는 아직 지원하지 않습니다.',
  target:{'bmfont-text':'BMFont 텍스트 .fnt','bmfont-xml':'BMFont XML .fnt','bmfont-bin':'BMFont 바이너리 .fnt','msdf-json':'msdf-atlas-gen JSON',godot:'Godot 4 FontFile',unity:'Unity TextMeshPro',phaser:'Phaser BitmapText',pixi:'PixiJS BitmapText'}},
 charset:{remove:'삭제',text:'문자',strings:'문자열 {n}개',newGlyphs:'글리프 +{n}',addFile:'번역 파일…',addPreset:'집합 추가…',addText:'텍스트 추가',strip:'자리표시자와 마크업 무시({0}, %s, <b>, [color])',
  removed:'제거됨: {list}',order:'글리프 순서',byFrequency:'많이 쓰는 순',byCode:'코드 포인트 순',exclude:'제외',stats:'글리프 {n}개 · 라틴 {latin} · 한글 {hangul} · 가나 {kana} · 한자 {han} · 기타 {other}',
  missing:'폰트에 없는 문자 {n}개',allPresent:'✓ 폰트에 집합의 모든 문자가 있습니다.'},
 strip:{icu:'ICU',braces:'{…}',printf:'%…',dollar:'$…',markup:'<태그>',bbcode:'[태그]'},
 preset:presets(['ASCII(95)','Latin-1(191)','숫자','라틴 확장-A','CJK 문장부호','가나(히라가나+가타카나)','한글 호환 자모','KS X 1001 한글(2,350)','JIS 1수준 한자(2,965)','한글 전체(11,172)']),
 render:{mode:'렌더링',m:modes(['비트맵(부드럽게)','픽셀(1비트)','SDF','PSDF','MSDF','MTSDF']),size:'크기(px/em)',range:'디스턴스 범위 px',threshold:'1비트 임계값',padding:'패딩',spacing:'간격',page:'페이지',sizeMode:'페이지 크기',pot:'2의 거듭제곱',auto:'딱 맞게',fixed:'고정',kerning:'커닝',alphaOnly:'알파 채널에 거리 저장(TextMeshPro)',
  hint:modes(['안티앨리어싱 커버리지, 흰 글리프를 알파에.','픽셀마다 켜짐/꺼짐: 격자 크기의 픽셀 폰트가 선명하게 유지됩니다.','단일 채널 부호 거리: 확대 가능, 날카로운 모서리는 둥글어집니다.','의사 거리: SDF와 비슷하지만 가장자리가 더 좋습니다.','멀티채널: 어떤 크기에서도 모서리가 날카롭습니다. MSDF 셰이더가 필요합니다.','MSDF + 알파에 실제 거리(외곽선, 글로우).']),
  gridNote:'픽셀 폰트는 그린 그대로의 시트를 씁니다: 페이지가 이미지 자체입니다.',phase:{start:'만드는 중…',render:'글리프 렌더링 {done}/{total}',pack:'글리프 {total}개 배치 중',encode:'페이지 인코딩 중'},
  result:'글리프 {g}개 · {w}×{h} 페이지 {p}장 · 사용률 {eff}% · 커닝 {k}쌍 · {ms} ms',pageN:'페이지 {n}'},
 metrics:{line:'줄 높이 {lh} · 기준선 {base} · 어센더 {asc} · 디센더 {desc}',glyph:'글리프 {c} (U+{u})',xadvance:'진행 폭',xoffset:'X 오프셋',yoffset:'Y 오프셋',overridden:'직접 수정한 값입니다.',clickGlyph:'캔버스에서 글리프를 클릭해 조정하세요.',
  kerning:'커닝 쌍',kernCount:'폰트의 쌍 {n}개(이 크기에서 0이 아닌 것 {px}개)',first:'앞 문자',second:'뒤 문자',amount:'값 px',addPair:'쌍 추가',
  suggest:'글리프 모양으로 쌍 제안',noSuggest:'보통 간격보다 넓은 쌍이 없습니다.',suggested:'{n}쌍이 보통 간격 {gap} px보다 넓습니다',applyAll:'{n}쌍 추가'},
 tp:{text:'예시 문장',sizes:'크기 px',color:'색',background:'배경',outline:'외곽선',outlineColor:'외곽선 색',shadow:'그림자',raw:'필드 그대로',
  bitmapNote:'엔진처럼 아틀라스에서 그립니다: {size} px와 정수배에서 선명하고 그 사이는 필터링됩니다.',fieldNote:'디스턴스 필드 셰이더(범위 {range} px): 모든 크기에서 선명합니다.',missing:'없는 글자 {n}개: {chars}',
  sample:'The quick brown fox jumps over the lazy dog. 0123456789',sampleKo:'새 게임 · 이어하기 · 설정 · 종료\n체력 100 / 공격 25 — 레벨 업!'},
 cmd:{import:'파일 {n}개 가져오기',export:'내보내기',suggest:'제안 적용',addFont:'폰트 파일 추가…',moveGuide:'9-슬라이스 가이드 이동',border:'테두리 설정',padding:'콘텐츠 여백 설정',stretch:'늘이기 방식 설정',center:'가운데 그리기',
  applySuggestion:'제안 테두리 적용',fixGuide:'가이드 이동',clearNine:'9-슬라이스 제거',addElement:'요소 추가',rename:'이름 바꾸기',removeElement:'{name} 삭제',removeElements:'요소 {n}개 삭제',moveElement:'요소 이동',
  detected:'감지된 요소 {n}개 추가',suggestAll:'요소 {n}개에 제안 테두리',importAtlas:'{name}에서 요소 {n}개 가져오기',kit:'UI 키트 내보내기 설정',newButton:'새 버튼',removeButton:'{name} 삭제',state:'{state} 상태 설정',
  pixelFont:'이미지로 픽셀 폰트',removeFont:'폰트 {name} 삭제',addTranslations:'번역 파일 {n}개 추가',axis:'{axis} 축 설정',grid:'글리프 격자 설정',order:'문자 순서 설정',key:'배경색 설정',
  charset:'문자 집합 변경',render:'아틀라스 설정 변경',glyph:'글리프 조정',kern:'커닝 변경',exportName:'폰트 내보내기 설정'},
 error:{missingBlob:'이 프로젝트의 파일 하나가 로드되지 않았습니다.',unsupported:'UI 워크스페이스에서 열 수 없는 파일: {names}',multiRun:'{name}은 한쪽에 늘이기 구간이 여러 개입니다. 가장 바깥 띠만 사용합니다.'}
},
ja:{
 menu:'UI',modeLabel:'UI モード',
 mode:{nine:'9スライス',states:'ステート',atlas:'アトラス',font:'フォント'},
 modeHint:{nine:'伸縮ボーダー、コンテンツ余白、あらゆるサイズのプレビュー',states:'ボタンのステート：ホバー、押下、無効、フォーカス',atlas:'UI シートを要素に分割',font:'フォントファイルやグリフシートからビットマップ・SDF・MSDF のゲームフォント'},
 tool:{edit:'編集',editHint:'ガイドのドラッグ（9スライス）、要素の移動と描画（アトラス）、グリフの選択（フォント）'},
 panel:{main:'UI',nine:'9スライス',preview:'プレビュー',kitExport:'UI キットを書き出し',states:'ボタンのステート',live:'実物のボタン',atlas:'要素',fontSource:'フォントソース',charset:'文字セット',render:'アトラス',metrics:'メトリクスとカーニング',fontExport:'フォントを書き出し',textPreview:'テキストプレビュー'},
 list:{elements:'要素',buttons:'ボタン',fonts:'フォント'},
 conf:{high:'信頼度 高',medium:'信頼度 中',low:'信頼度 低',none:'根拠なし'},
 side:sides(['左','右','上','下']),
 stretch:{stretch:'伸縮','tile':'タイル','tile-fit':'タイル（フィット）'},
 state:states(['通常','ホバー','押下','無効','フォーカス']),
 engine:{ideal:'正確なプラン',godot:'Godot 4',unity:'Unity',css:'CSS border-image',phaser:'Phaser',pixi:'PixiJS',android:'Android 9-patch'},
 verify:{verified:'検証済み',partial:'一部検証',unverified:'未検証',na:'データ'},
 nine:{
  noElements:'要素がまだありません。パネルやボタンの PNG をドロップするか、アトラスでシートを分割してください。',pick:'9スライスを設定する要素を選んでください。',useWhole:'「{name}」全体を要素にする',name:'要素名',
  chipOn:'9スライス L {l} R {r} T {t} B {b}',chipOff:'9スライス未設定',
  suggested:'提案：L {l} · R {r} · T {t} · B {b}',apply:'提案を適用',applied:'適用済み',
  whyCols:'同一の列が {n} 本',whyRows:'同一の行が {n} 本',whyPeriod:'{axis}：{p} px ごとに繰り返す模様',whyNoneH:'伸ばせる列なし',whyNoneV:'伸ばせる行なし（グラデーション？）',
  axisH:'横',axisV:'縦',tileSuggested:'中央が繰り返しています：タイルにすれば模様が保たれます。',noSuggestion:'ピクセルから伸ばせる帯が見つかりません。ガイドをドラッグするか数値を入力してください。',
  stretchBorders:'伸縮ボーダー（拡大されない部分）',dragHint:'キャンバスの青いガイドをドラッグ · Shift＝両側 · 矢印キーで最後のガイドを微調整',
  paddingOn:'コンテンツ余白を別に指定（文字やアイコンの位置）',paddingOff:'コンテンツ領域＝伸縮ボーダー（Android と Godot の既定）。',
  middle:'中央',drawCenter:'中央を描く',checks:'チェック',clean:'✓ 問題のあるパッチはありません：伸びる帯は均一です。',notSet:'ボーダーを設定すると伸びる帯をチェックします。',
  fixGuide:'ガイドを {v} へ',engineNumbers:'エンジンごとの同じ数値',clear:'9スライスを削除',
  guideHint:'ドラッグ：{what}',borders:'L {l} · R {r} · T {t} · B {b}',
  border:sides(['左の伸縮ボーダー','右の伸縮ボーダー','上の伸縮ボーダー','下の伸縮ボーダー']),padding:sides(['左のコンテンツ余白','右のコンテンツ余白','上のコンテンツ余白','下のコンテンツ余白'])},
 issue:{'gradient.h':'横の帯に異なる列が {n} 本あり、伸ばすと形が崩れます。タイルにするか帯を狭めてください。','gradient.v':'縦の帯に異なる行が {n} 本あり（グラデーション？）、伸ばすと変わります。タイルにするか帯を狭めてください。',
  'cut-corner':'{side}：角の絵がガイドの外へ {k} px 続いていて、角の一部が伸びます。','seam.h':'タイルに継ぎ目が出ます：帯の最後の列が最初の列につながりません（差 {step}）。','seam.v':'タイルに継ぎ目が出ます：帯の最後の行が最初の行につながりません（差 {step}）。',
  padding:'コンテンツ余白のせいで中身の入る場所がありません。',empty:'この要素は完全に透明です。'},
 preview:{engine:'描画方式',scales:'DPI 倍率',custom:'カスタム',customW:'幅',customH:'高さ',content:'コンテンツ領域',slices:'スライス線',size:'サイズ',
  noMode:'{engine} には{mode}がないため伸縮で表示しています',warn:{narrow:'角より狭い：角が縮みます',short:'角より低い：角が縮みます',fractional:'小数倍率：角がピクセルに揃いません',tileLimit:'タイルが多すぎるため伸縮で表示'}},
 kit:{name:'ファイル名',export:'要素 {n} 個を書き出し',exporting:'書き出し中…',atlas:'1 枚のアトラスにまとめる（Godot、Unity、汎用）',noNine:'{n} 個の要素はまだ 9スライスがなく、普通の画像として書き出されます。',done:'{name} を書き出しました（{n} ファイル）',
  target:{generic:'汎用 JSON + PNG',godot:'Godot 4 StyleBoxTexture + Theme',unity:'Unity スプライトのボーダー（インポーター）',android:'Android .9.png',css:'CSS border-image',phaser:'Phaser NineSlice アトラス',pixi:'PixiJS NineSliceSprite アトラス'}},
 states:{none:'ボタンがまだありません。',pick:'ボタンを選ぶか作成してください。',fromElement:'「{name}」から新しいボタン',needElement:'ボタンにする要素を選んでください（9スライス）。',
  suggest:'ボタン「{name}」：{states}（ファイル名から）',suggestHint:'ファイル名から、1 つのボタンのステートと考えられます。クリックするまで組み合わせません。',
  count:'ステート {n} 個',remove:'{name} を削除',source:'{state} の取得元',none1:'— 使わない —',genFrom:'{state} から生成',name:'ボタン名',
  lead:'各ステートは個別の絵か、下の数値で別のステートから作ったものです。ない絵を作り出しません。',
  borders:'ボーダー L {l} R {r} T {t} B {b}',noBorders:'9スライスなし',grown:'キャンバス両側 +{n} px',ownNoNine:'このステートの絵には 9スライスがありません。9スライスで設定してください。',
  labelText:'ラベル',liveLabel:'実物のボタン：ホバー、押下、Tab でフォーカス',liveHint:'ホバー、押下、Tab で移動してみてください。本物のボタンのようにステートが変わります。'},
 op:{brightness:'明るさ',contrast:'コントラスト',saturation:'彩度',alpha:'不透明度',offsetX:'X 移動',offsetY:'Y 移動',outline:'アウトライン px',outlineColor:'アウトラインの色',overlayColor:'重ねる色',overlayAlpha:'重ね'},
 atlas:{noImage:'まず UI シートの画像を開いてください。',lead:'要素はアルファの島で、結合距離より近いものはまとめます。追加するまで検出はプレビューです。',threshold:'アルファ >',merge:'結合 ≤ px',minArea:'最小面積',
  detect:'要素を検出',detecting:'検出中…',found:'要素 {n} 個を検出（島 {islands} 個）',preview:'{n} 個を検出（点線）',previewHint:'既存の要素と重ならないものを追加するか、すべて置き換えてください。',addNew:'{n} 個を追加',replace:'すべて置き換え',discard:'破棄',
  draw:'要素を描く',suggestAll:'すべてに 9スライスを提案',suggestSel:'選択した {n} 個に 9スライスを提案',editNine:'9スライスを編集',delete:'削除（{n}）',count:'要素 {n} 個、9スライス {nine} 個',
  noneConfident:'確かな提案のある要素がありません。',suggested:'{of} 個中 {n} 個の要素にボーダーを設定しました（信頼度 中以上）。',noRegions:'このアトラスファイルには領域がありません。',noSheet:'このアトラスファイルに合う画像がプロジェクトにありません。',imported:'{name} から要素 {n} 個',listHint:'ドラッグで移動、ハンドルでサイズ変更、要素を描くで追加。'},
 font:{none:'フォントがまだありません。',pick:'フォントを選ぶか追加してください。',addFile:'フォントファイルを追加…',fromImage:'「{name}」からピクセルフォント',fromSheet:'グリフシート',remove:'{name} を削除',
  woff2:'WOFF2 には対応していません。先に TTF か OTF に変換してください。',notFont:'TTF、OTF、TTC、WOFF のフォントではありません。',bitmapOnly:'{name} には埋め込みビットマップしかなく、アウトラインがないため描画できません。',needFontFirst:'先にフォントを追加してから翻訳ファイルを入れてください。',
  addedFiles:'翻訳ファイル {n} 個、文字列 {strings} 個',gridFound:'グリッド {w}×{h}、グリフ {n} 個（{conf}）。下の順序を確認してください。',gridNone:'はっきりしたグリフのグリッドがありません。セルサイズを入力してください。',sheetGone:'グリフシートの画像がプロジェクトにありません。',
  info:'グリフ {glyphs} · 文字 {cps} · {type} · ハングル {hangul} · かな {kana} · 漢字 {han}',pixelGrid:'ピクセルフォント：{px} px グリッド — {sizes} px でくっきり',pixelWhy:'すべてのアウトライン点が {q} フォント単位の倍数（グリフ {g} 個の点 {n} 個）',usePixel:'{px} px・1 ビットで使う',
  instance:'名前付きインスタンス',licence:'ライセンス（フォント内の記載）',gridGuess:'グリッド {w}×{h}、{c}×{r} セル',keyFound:'背景色 {color} を透明にしました（{conf}）。',
  cellW:'セル W',cellH:'セル H',cols:'列',rows:'行',ox:'オフセット X',oy:'オフセット Y',sx:'間隔 X',sy:'間隔 Y',order:'文字の順序（1 セルに 1 文字）',orderAscii:'スペースから ASCII',orderAscii33:'! から ASCII',orderCount:'{cells} セルに {n} 文字',
  measure:'幅',measureInk:'インクから測定',measureFixed:'セル幅で固定',baseline:'ベースライン',lineHeight:'行の高さ',letterSpacing:'字間',spaceAdvance:'スペースの幅',key:'背景色',white:'白いグリフ（エンジンで着色）',
  pageStatus:'ページ {n}/{of} · {w}×{h}',export:'フォントを書き出し',binNoField:'バイナリ .fnt にはディスタンスフィールドの項目がないため、このモードでは省きます。',fntLater:'既存の .fnt を開く機能はまだありません。',
  target:{'bmfont-text':'BMFont テキスト .fnt','bmfont-xml':'BMFont XML .fnt','bmfont-bin':'BMFont バイナリ .fnt','msdf-json':'msdf-atlas-gen JSON',godot:'Godot 4 FontFile',unity:'Unity TextMeshPro',phaser:'Phaser BitmapText',pixi:'PixiJS BitmapText'}},
 charset:{remove:'削除',text:'文字',strings:'文字列 {n} 個',newGlyphs:'グリフ +{n}',addFile:'翻訳ファイル…',addPreset:'セットを追加…',addText:'テキストを追加',strip:'プレースホルダーとマークアップを無視（{0}、%s、<b>、[color]）',
  removed:'除去：{list}',order:'グリフの順序',byFrequency:'よく使う順',byCode:'コードポイント順',exclude:'除外',stats:'グリフ {n} · ラテン {latin} · ハングル {hangul} · かな {kana} · 漢字 {han} · その他 {other}',
  missing:'フォントにない文字が {n} 個',allPresent:'✓ フォントにはセットのすべての文字があります。'},
 strip:{icu:'ICU',braces:'{…}',printf:'%…',dollar:'$…',markup:'<タグ>',bbcode:'[タグ]'},
 preset:presets(['ASCII（95）','Latin-1（191）','数字','ラテン拡張A','CJK 句読点','かな（ひらがな＋カタカナ）','ハングル互換字母','KS X 1001 ハングル（2,350）','JIS 第1水準漢字（2,965）','ハングル全体（11,172）']),
 render:{mode:'描画',m:modes(['ビットマップ（なめらか）','ピクセル（1 ビット）','SDF','PSDF','MSDF','MTSDF']),size:'サイズ（px/em）',range:'ディスタンス範囲 px',threshold:'1 ビットのしきい値',padding:'パディング',spacing:'間隔',page:'ページ',sizeMode:'ページサイズ',pot:'2 のべき乗',auto:'ぴったり',fixed:'固定',kerning:'カーニング',alphaOnly:'アルファに距離を格納（TextMeshPro）',
  hint:modes(['アンチエイリアスのカバレッジ、白いグリフをアルファに。','ピクセルごとにオン／オフ：グリッドサイズのピクセルフォントはくっきり。','1 チャンネルの符号付き距離：拡大できるが鋭い角は丸くなる。','擬似距離：SDF に近く、縁がよりきれい。','マルチチャンネル：どのサイズでも角が鋭い。MSDF シェーダーが必要。','MSDF ＋ アルファに実距離（アウトライン、グロー）。']),
  gridNote:'ピクセルフォントは描いたままのシートを使います：ページは画像そのものです。',phase:{start:'作成中…',render:'グリフを描画 {done}/{total}',pack:'グリフ {total} 個を配置中',encode:'ページをエンコード中'},
  result:'グリフ {g} · {w}×{h} ページ {p} 枚 · 使用率 {eff}% · カーニング {k} 組 · {ms} ms',pageN:'ページ {n}'},
 metrics:{line:'行の高さ {lh} · ベースライン {base} · アセンダー {asc} · ディセンダー {desc}',glyph:'グリフ {c}（U+{u}）',xadvance:'送り幅',xoffset:'X オフセット',yoffset:'Y オフセット',overridden:'手動で上書きした値です。',clickGlyph:'キャンバスでグリフをクリックして調整します。',
  kerning:'カーニングペア',kernCount:'フォントのペア {n} 組（このサイズで 0 でないもの {px} 組）',first:'前の文字',second:'後の文字',amount:'値 px',addPair:'ペアを追加',
  suggest:'グリフの形からペアを提案',noSuggest:'標準の間隔より広いペアはありません。',suggested:'{n} 組が標準の {gap} px より広く空いています',applyAll:'{n} 組を追加'},
 tp:{text:'サンプル文',sizes:'サイズ px',color:'色',background:'背景',outline:'アウトライン',outlineColor:'アウトラインの色',shadow:'影',raw:'フィールドそのまま',
  bitmapNote:'エンジンと同じくアトラスから描きます：{size} px とその整数倍でくっきり、その間はフィルタされます。',fieldNote:'ディスタンスフィールドのシェーダー（範囲 {range} px）：どのサイズでもくっきり。',missing:'ない文字 {n} 個：{chars}',
  sample:'The quick brown fox jumps over the lazy dog. 0123456789',sampleKo:'ニューゲーム · つづきから · 設定 · 終了\nHP 100 / 攻撃 25 — レベルアップ！'},
 cmd:{import:'ファイル {n} 個を読み込み',export:'書き出し',suggest:'提案を適用',addFont:'フォントファイルを追加…',moveGuide:'9スライスのガイドを移動',border:'ボーダーを設定',padding:'コンテンツ余白を設定',stretch:'伸縮方法を設定',center:'中央を描く',
  applySuggestion:'提案のボーダーを適用',fixGuide:'ガイドを移動',clearNine:'9スライスを削除',addElement:'要素を追加',rename:'名前を変更',removeElement:'{name} を削除',removeElements:'要素 {n} 個を削除',moveElement:'要素を移動',
  detected:'検出した要素 {n} 個を追加',suggestAll:'要素 {n} 個に提案のボーダー',importAtlas:'{name} から要素 {n} 個を読み込み',kit:'UI キットの書き出し設定',newButton:'新しいボタン',removeButton:'{name} を削除',state:'{state} ステートを設定',
  pixelFont:'画像からピクセルフォント',removeFont:'フォント {name} を削除',addTranslations:'翻訳ファイル {n} 個を追加',axis:'軸 {axis} を設定',grid:'グリフのグリッドを設定',order:'文字の順序を設定',key:'背景色を設定',
  charset:'文字セットを変更',render:'アトラス設定を変更',glyph:'グリフを調整',kern:'カーニングを変更',exportName:'フォントの書き出し設定'},
 error:{missingBlob:'このプロジェクトのファイルが読み込まれていません。',unsupported:'UI ワークスペースで開けないファイル：{names}',multiRun:'{name} は片側に伸縮区間が複数あります。いちばん外側の帯だけを使います。'}
}};
export const UI_GROUP={en:'UI',ko:'UI',ja:'UI'};
for(const l of Object.keys(UI_STRINGS)){if(!STUDIO_STRINGS[l])continue;STUDIO_STRINGS[l].ui=UI_STRINGS[l];STUDIO_STRINGS[l].group={...(STUDIO_STRINGS[l].group||{}),ui:UI_GROUP[l]};}
