export const COPY={
 en:{lead:'Make a pixel character from original CC0 parts. Everything renders on this device.',face:'Face',hair:'Hair',eyes:'Eyes',outfit:'Outfit',accessory:'Accessory',background:'Background',round:'Round',angular:'Angular',bob:'Bob',swept:'Swept',bright:'Bright',sleepy:'Sleepy',hoodie:'Hoodie',jacket:'Jacket',none:'None',earring:'Earrings',glasses:'Glasses',transparent:'Transparent',sky:'Sky',plum:'Plum',dark:'Slate',red:'Coral',blue:'Teal',gold:'Gold',hairPalette:'Hair color',outfitPalette:'Outfit color',lock:'Lock',unlock:'Unlock',random:'Random',undo:'Undo',redo:'Redo',reset:'Reset',png:'Download PNG',gif:'Download blinking GIF',card:'Download share card',link:'Copy settings link',x:'Share link on X',line:'Share link on LINE',local:'Your avatar and exports stay on this device. A settings link reconstructs built-in parts; it does not contain an image.',license:'Original parts are CC0. You may use exports commercially. Shared links show a generic site preview; attach a downloaded card yourself for an avatar image.',gifNote:'GIF: eight exact-palette frames; eyes blink. Motion is never started automatically.',size:'Export size',statusReady:'Avatar ready.',statusExport:'Rendering on this device…',statusDone:'File saved.',statusCancel:'Export canceled.',statusLink:'Settings link copied.',statusBadURL:'Some link settings were invalid and were reset.',statusError:'Could not export: ',cancel:'Cancel export',preview:'Pixel avatar preview',motion:'Preview animation',motionOff:'Stop animation',version:'Part catalog v1 · 16 px source grid'},
 ko:{lead:'직접 제작한 CC0 파츠로 픽셀 캐릭터를 만드세요. 작업은 이 기기에서 처리됩니다.',face:'얼굴',hair:'머리',eyes:'눈',outfit:'의상',accessory:'장신구',background:'배경',round:'둥근형',angular:'각진형',bob:'단발',swept:'옆가르마',bright:'또렷한 눈',sleepy:'졸린 눈',hoodie:'후드',jacket:'재킷',none:'없음',earring:'귀걸이',glasses:'안경',transparent:'투명',sky:'하늘',plum:'자두색',dark:'슬레이트',red:'코랄',blue:'청록',gold:'금색',hairPalette:'머리 색',outfitPalette:'의상 색',lock:'잠금',unlock:'잠금 해제',random:'랜덤',undo:'실행 취소',redo:'다시 실행',reset:'초기화',png:'PNG 다운로드',gif:'눈 깜박임 GIF 다운로드',card:'공유 카드 다운로드',link:'설정 링크 복사',x:'X에 링크 공유',line:'LINE에 링크 공유',local:'아바타와 출력물은 이 기기에 남습니다. 설정 링크는 기본 파츠만 복원하며 이미지는 담지 않습니다.',license:'원본 파츠는 CC0입니다. 출력물을 상업적으로 사용할 수 있습니다. 공유 링크에는 공통 사이트 미리보기가 표시되므로 아바타 이미지는 다운로드한 카드를 직접 첨부하세요.',gifNote:'GIF는 정확한 팔레트로 8프레임을 만들고 눈이 깜박입니다. 미리보기 애니메이션은 자동으로 시작되지 않습니다.',size:'출력 크기',statusReady:'아바타 준비 완료.',statusExport:'이 기기에서 렌더링 중…',statusDone:'파일을 저장했습니다.',statusCancel:'출력을 취소했습니다.',statusLink:'설정 링크를 복사했습니다.',statusBadURL:'잘못된 링크 설정은 기본값으로 복원했습니다.',statusError:'출력 실패: ',cancel:'출력 취소',preview:'픽셀 아바타 미리보기',motion:'애니메이션 보기',motionOff:'애니메이션 중지',version:'파츠 카탈로그 v1 · 원본 16px 격자'},
 ja:{lead:'オリジナルのCC0パーツでピクセルキャラクターを作成。処理はこの端末上で行います。',face:'顔',hair:'髪',eyes:'目',outfit:'服',accessory:'アクセサリー',background:'背景',round:'丸顔',angular:'角顔',bob:'ボブ',swept:'流し髪',bright:'明るい目',sleepy:'眠そうな目',hoodie:'フード',jacket:'ジャケット',none:'なし',earring:'イヤリング',glasses:'メガネ',transparent:'透明',sky:'空色',plum:'プラム',dark:'スレート',red:'コーラル',blue:'青緑',gold:'金色',hairPalette:'髪の色',outfitPalette:'服の色',lock:'固定',unlock:'固定解除',random:'ランダム',undo:'元に戻す',redo:'やり直す',reset:'初期化',png:'PNGを保存',gif:'まばたきGIFを保存',card:'共有カードを保存',link:'設定リンクをコピー',x:'Xでリンク共有',line:'LINEでリンク共有',local:'アバターと出力はこの端末に残ります。設定リンクは標準パーツのみを復元し、画像を含みません。',license:'オリジナルパーツはCC0です。出力は商用利用できます。共有リンクには共通サイトプレビューが表示されます。アバター画像は保存したカードを添付してください。',gifNote:'GIFは正確なパレットの8フレームでまばたきします。プレビュー動画は自動再生しません。',size:'出力サイズ',statusReady:'アバターを準備しました。',statusExport:'この端末で描画中…',statusDone:'ファイルを保存しました。',statusCancel:'出力を中止しました。',statusLink:'設定リンクをコピーしました。',statusBadURL:'無効なリンク設定は初期値に戻しました。',statusError:'出力失敗: ',cancel:'出力を中止',preview:'ピクセルアバタープレビュー',motion:'アニメーションを見る',motionOff:'アニメーションを停止',version:'パーツカタログ v1 · 元画像16px'},
};

Object.assign(COPY.en,{pickBackground:'Choose local background',removeBackground:'Remove local background',backgroundLoaded:'Local background: ',backgroundHint:'A local image overrides the built-in background. It is reduced to the 16 px grid and never included in a settings link.',backgroundError:'Use a PNG, JPEG or WebP under 20 MiB and 8192 pixels per side.'});
Object.assign(COPY.ko,{pickBackground:'로컬 배경 선택',removeBackground:'로컬 배경 제거',backgroundLoaded:'로컬 배경: ',backgroundHint:'로컬 이미지는 기본 배경보다 우선하며 16px 격자로 축소됩니다. 설정 링크에는 포함되지 않습니다.',backgroundError:'20MiB 이하, 한 변 8192px 이하의 PNG·JPEG·WebP를 선택하세요.'});
Object.assign(COPY.ja,{pickBackground:'端末の背景を選択',removeBackground:'端末の背景を削除',backgroundLoaded:'端末の背景: ',backgroundHint:'端末の画像が標準背景より優先され、16pxグリッドに縮小されます。設定リンクには含まれません。',backgroundError:'20MiB以下、各辺8192px以下のPNG・JPEG・WebPを選んでください。'});
Object.assign(COPY.en,{nativeShare:'Share card file',shareUnavailable:'This browser cannot share image files; download the card instead.',shareCanceled:'Sharing was canceled.'});
Object.assign(COPY.ko,{nativeShare:'카드 파일 공유',shareUnavailable:'이 브라우저는 이미지 파일 공유를 지원하지 않습니다. 카드를 다운로드하세요.',shareCanceled:'공유를 취소했습니다.'});
Object.assign(COPY.ja,{nativeShare:'カード画像を共有',shareUnavailable:'このブラウザは画像ファイルの共有に非対応です。カードを保存してください。',shareCanceled:'共有を中止しました。'});
Object.assign(COPY.en,{skinPalette:'Skin tone',skin:'Light',skinTan:'Tan',skinDeep:'Deep'});
Object.assign(COPY.ko,{skinPalette:'피부 색',skin:'밝은 피부',skinTan:'중간 피부',skinDeep:'짙은 피부'});
Object.assign(COPY.ja,{skinPalette:'肌の色',skin:'明るい肌',skinTan:'中間の肌',skinDeep:'濃い肌'});
