import {locale,onLocale,page,toast} from './shell.js';
export const accept='.txt,.md,.text,text/plain';
const COPY={
 en:{input:'Your text',hint:'Type, paste, drop a UTF-8 text file, or choose one. Text stays on this device.',pick:'Choose text file',clear:'Clear',undo:'Undo',redo:'Redo',copy:'Copy text',count:'Visible characters',noSpaces:'Without whitespace',utf8:'UTF-8 bytes',advanced:'More counts and settings',settings:'Count settings',include:'Include spaces and line breaks',limit:'Custom limit',rate:'Reading speed (words/min)',metrics:'Detailed counts',graphemes:'Grapheme clusters',points:'Unicode code points',units:'UTF-16 code units',spaces:'Whitespace clusters',lines:'Lines',nonblank:'Nonblank lines',paragraphs:'Paragraphs',words:'Words',sentences:'Sentences',reading:'Reading time (estimate)',seconds:'sec',x:'X ordinary post',remaining:'remaining',xSource:'Official twitter-text 3.1.0, config v3. URLs and emoji have special weights. Posting eligibility depends on your account.',bytes:'Legacy encoding bytes',sjis:'Shift_JIS',euckr:'Strict EUC-KR',cp949:'CP949',unmappable:'Cannot encode {n} character(s); no byte number shown.',paper:'Manuscript volume estimate',jaPaper:'Japanese 400-cell pages',koPaper:'Korean 200-cell pages',paperNote:'Arithmetic estimate: non-whitespace graphemes ÷ 400 or 200, rounded up. It does not model line breaks or punctuation placement.',width:'Width categories',half:'Half-width',full:'Full-width',other:'Other / ambiguous',scripts:'Letter scripts',repeat:'Adjacent repeated words',none:'None found',working:'Counting…',empty:'Start typing to see counts.',fileError:'Choose a UTF-8 text file up to 8 MiB. Invalid UTF-8 is rejected.',private:'Only settings are put in the URL; text and undo history are held in memory.',apply:'Apply',explain:'Graphemes use Intl.Segmenter. Legacy bytes use explicit mappings; unmappable characters never become a guessed byte count.'},
 ko:{input:'계산할 글',hint:'직접 쓰거나 붙여넣고, UTF-8 텍스트 파일을 놓거나 선택하세요. 내용은 기기에만 남습니다.',pick:'텍스트 파일 선택',clear:'지우기',undo:'되돌리기',redo:'다시 실행',copy:'글 복사',count:'보이는 글자',noSpaces:'공백 제외',utf8:'UTF-8 바이트',advanced:'다른 기준과 설정',settings:'계산 설정',include:'공백·줄바꿈 포함',limit:'사용자 지정 한도',rate:'읽기 속도(분당 단어)',metrics:'상세 계산',graphemes:'문자소',points:'유니코드 코드 포인트',units:'UTF-16 코드 단위',spaces:'공백 문자소',lines:'줄',nonblank:'내용이 있는 줄',paragraphs:'문단',words:'단어',sentences:'문장',reading:'읽는 시간(추정)',seconds:'초',x:'X 일반 게시물',remaining:'남음',xSource:'공식 twitter-text 3.1.0, 설정 v3 기준. URL과 이모지에는 별도 가중치가 적용됩니다. 게시 가능 여부는 계정에 따라 다릅니다.',bytes:'기존 인코딩 바이트',sjis:'Shift_JIS',euckr:'엄격한 EUC-KR',cp949:'CP949',unmappable:'{n}개 문자를 인코딩할 수 없어 바이트 수를 표시하지 않습니다.',paper:'원고지 분량 추정',jaPaper:'일본 400칸 원고지',koPaper:'한국 200칸 원고지',paperNote:'공백을 뺀 문자소를 400 또는 200으로 나눠 올림한 분량 추정입니다. 줄바꿈·문장부호 배치는 반영하지 않습니다.',width:'너비 범주',half:'반각',full:'전각',other:'기타·모호',scripts:'문자 종류',repeat:'이어진 중복 단어',none:'없음',working:'계산 중…',empty:'글을 입력하면 결과가 나옵니다.',fileError:'8MiB 이하 UTF-8 텍스트 파일을 선택하세요. 잘못된 UTF-8은 읽지 않습니다.',private:'URL에는 설정만 들어갑니다. 글과 되돌리기 기록은 메모리에만 둡니다.',apply:'적용',explain:'문자소는 Intl.Segmenter로 셉니다. 기존 인코딩은 명시적 매핑을 쓰고, 표현할 수 없는 문자의 바이트 수는 추정하지 않습니다.'},
 ja:{input:'数える文章',hint:'入力・貼り付け、またはUTF-8のテキストファイルをドロップ・選択してください。本文は端末内で処理します。',pick:'テキストファイルを選ぶ',clear:'消去',undo:'元に戻す',redo:'やり直す',copy:'本文をコピー',count:'見た目の文字数',noSpaces:'空白を除く',utf8:'UTF-8バイト',advanced:'ほかの数え方と設定',settings:'カウント設定',include:'空白・改行を含める',limit:'任意の上限',rate:'読む速さ（語/分）',metrics:'詳しい集計',graphemes:'書記素クラスタ',points:'Unicodeコードポイント',units:'UTF-16コード単位',spaces:'空白の書記素',lines:'行数',nonblank:'空行を除く行数',paragraphs:'段落数',words:'語数',sentences:'文数',reading:'読む時間（目安）',seconds:'秒',x:'Xの通常投稿',remaining:'残り',xSource:'公式twitter-text 3.1.0・設定v3による計算です。URLと絵文字には別の重みがあります。投稿できるかはアカウントによります。',bytes:'旧来の文字コードのバイト数',sjis:'Shift_JIS',euckr:'厳密なEUC-KR',cp949:'CP949',unmappable:'{n}文字を符号化できないため、バイト数を表示しません。',paper:'原稿用紙の分量目安',jaPaper:'日本語400字詰め',koPaper:'韓国語200字詰め',paperNote:'空白を除く書記素数を400または200で割り、切り上げた目安です。改行や句読点の配置は反映しません。',width:'文字幅の分類',half:'半角',full:'全角',other:'その他・曖昧',scripts:'文字種',repeat:'連続して重複する語',none:'見つかりません',working:'集計中…',empty:'文章を入力すると結果が表示されます。',fileError:'8MiB以下のUTF-8テキストファイルを選んでください。不正なUTF-8は読み込みません。',private:'URLには設定だけを入れ、本文と履歴はメモリにのみ保持します。',apply:'適用',explain:'書記素はIntl.Segmenterで数えます。旧来の符号化では対応しない文字を推定のバイト数に置き換えません。'}
};
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const tr=(k,vars={})=>String((COPY[locale()]||COPY.en)[k]||k).replace(/\{(\w+)\}/g,(_,x)=>vars[x]??'');
let worker=null,revision=0,timer=0,last=null,history=[''],cursor=0,composing=false;
let settings={include:true,limit:280,readRate:250};
function settingURL(){const u=new URL(location.href);u.searchParams.set('spaces',settings.include?'1':'0');u.searchParams.set('limit',String(settings.limit));u.searchParams.set('rate',String(settings.readRate));historyReplace(u);}
function historyReplace(url){window.history.replaceState({},'',url.pathname+url.search+url.hash);}
function readURL(){const q=page.query;settings.include=q.get('spaces')!=='0';const limit=Number(q.get('limit')),rate=Number(q.get('rate'));if(Number.isInteger(limit)&&limit>0&&limit<=1000000)settings.limit=limit;if(Number.isInteger(rate)&&rate>=50&&rate<=1500)settings.readRate=rate;}
function push(value){if(history[cursor]===value)return;history=history.slice(Math.max(0,cursor-49),cursor+1);history.push(value);cursor=history.length-1;}
function schedule(){clearTimeout(timer);const text=$('#characterInput').value;const rev=++revision;$('#characterStatus').textContent=tr('working');timer=setTimeout(()=>worker.postMessage({revision:rev,text,settings:{locale:locale(),limit:settings.limit,readRate:settings.readRate}}),text.length>200000?120:35);}
function metric(label,value,extra=''){return `<div class="cc-metric"><dt>${esc(label)}</dt><dd>${esc(value)}</dd>${extra?`<small>${esc(extra)}</small>`:''}</div>`;}
function render(){const r=last;if(!r)return;const f=n=>new Intl.NumberFormat(locale()).format(n),main=settings.include?r.graphemes:r.content;
 $('#characterPrimary').textContent=f(main);$('#characterStatus').textContent=r.graphemes?`${tr('graphemes')} · ${f(r.graphemes)}`:tr('empty');
 $('#characterProgress').value=Math.min(main,settings.limit);$('#characterProgress').max=settings.limit;$('#characterLimitResult').textContent=`${f(main)} / ${f(settings.limit)}`;
 $('#characterQuick').innerHTML=metric(tr('noSpaces'),f(r.content))+metric(tr('utf8'),f(r.utf8))+metric(tr('x'),f(r.x.weighted),`${f(r.x.remaining)} ${tr('remaining')}`);
 $('#characterMetrics').innerHTML=[['graphemes',r.graphemes],['points',r.codePoints],['units',r.utf16],['spaces',r.spaces],['lines',r.lines],['nonblank',r.nonblankLines],['paragraphs',r.paragraphs],['words',r.words],['sentences',r.sentences],['reading',`${f(r.readSeconds)} ${tr('seconds')}`]].map(([k,v])=>metric(tr(k),typeof v==='number'?f(v):v)).join('');
 $('#characterBytes').innerHTML=[['sjis','shift_jis'],['euckr','euc_kr'],['cp949','cp949']].map(([label,key])=>{const v=r.legacy[key];return metric(tr(label),v.bytes===null?'—':f(v.bytes),v.unmappable?tr('unmappable',{n:f(v.unmappable)}):'');}).join('');
 $('#characterPaper').innerHTML=metric(tr('jaPaper'),f(r.paper.ja))+metric(tr('koPaper'),f(r.paper.ko));
 $('#characterWidth').innerHTML=metric(tr('half'),f(r.width.half))+metric(tr('full'),f(r.width.full))+metric(tr('other'),f(r.width.other));
 $('#characterScripts').innerHTML=Object.entries(r.scripts).map(([k,v])=>metric(k,f(v))).join('');
 $('#characterRepeats').textContent=r.repetitions.length?r.repetitions.map(x=>`${x.phrase} ×${x.count+1}`).join(', '):tr('none');
}
function relabel(){for(const node of document.querySelectorAll('[data-cc]'))node.textContent=tr(node.dataset.cc);if(last)render();else $('#characterStatus').textContent=tr('empty');}
function changeText(value,{record=true}={}){$('#characterInput').value=value;if(record)push(value);schedule();}
export function mount({el}){
 readURL();const link=document.createElement('link');link.rel='stylesheet';link.href='src/task/character-counter.css';document.head.append(link);
 el.innerHTML=`<section class="cc"><div class="cc-editor"><label for="characterInput" data-cc="input"></label><textarea id="characterInput" spellcheck="false" aria-describedby="characterHint characterStatus"></textarea><p id="characterHint" data-cc="hint"></p><div class="cc-toolbar"><button type="button" id="characterPick" data-cc="pick"></button><button type="button" id="characterUndo" data-cc="undo"></button><button type="button" id="characterRedo" data-cc="redo"></button><button type="button" id="characterCopy" data-cc="copy"></button><button type="button" id="characterClear" data-cc="clear"></button></div></div><div class="cc-results" aria-live="polite"><div class="cc-total"><span data-cc="count"></span><strong id="characterPrimary">0</strong><small id="characterStatus"></small></div><progress id="characterProgress" value="0" max="280"></progress><small id="characterLimitResult">0 / 280</small><dl id="characterQuick" class="cc-grid"></dl></div><details class="cc-details"><summary data-cc="advanced"></summary><div class="cc-settings"><h2 data-cc="settings"></h2><label><input id="characterInclude" type="checkbox"> <span data-cc="include"></span></label><label><span data-cc="limit"></span><input id="characterLimit" type="number" min="1" max="1000000"></label><label><span data-cc="rate"></span><input id="characterRate" type="number" min="50" max="1500"></label><p data-cc="private"></p><p data-cc="explain"></p></div><h2 data-cc="metrics"></h2><dl id="characterMetrics" class="cc-grid"></dl><h2 data-cc="x"></h2><p data-cc="xSource"></p><h2 data-cc="bytes"></h2><dl id="characterBytes" class="cc-grid"></dl><h2 data-cc="paper"></h2><dl id="characterPaper" class="cc-grid"></dl><p data-cc="paperNote"></p><h2 data-cc="width"></h2><dl id="characterWidth" class="cc-grid"></dl><h2 data-cc="scripts"></h2><dl id="characterScripts" class="cc-grid"></dl><h2 data-cc="repeat"></h2><p id="characterRepeats"></p></details></section>`;
 $('#characterInclude').checked=settings.include;$('#characterLimit').value=settings.limit;$('#characterRate').value=settings.readRate;relabel();onLocale(()=>{relabel();schedule();});
 worker=new Worker(new URL('./character-worker.js',import.meta.url),{type:'module'});worker.onmessage=e=>{if(e.data.revision!==revision)return;if(e.data.error){$('#characterStatus').textContent=e.data.error;return;}last=e.data.result;render();};
 $('#characterInput').addEventListener('compositionstart',()=>{composing=true;});$('#characterInput').addEventListener('compositionend',()=>{composing=false;push($('#characterInput').value);schedule();});
 $('#characterInput').addEventListener('input',()=>{if(composing)return;push($('#characterInput').value);schedule();});
 $('#characterInput').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();const next=e.shiftKey?Math.min(history.length-1,cursor+1):Math.max(0,cursor-1);cursor=next;changeText(history[cursor],{record:false});}});
 $('#characterUndo').onclick=()=>{cursor=Math.max(0,cursor-1);changeText(history[cursor],{record:false});};$('#characterRedo').onclick=()=>{cursor=Math.min(history.length-1,cursor+1);changeText(history[cursor],{record:false});};
 $('#characterClear').onclick=()=>changeText('');$('#characterCopy').onclick=()=>navigator.clipboard.writeText($('#characterInput').value).catch(()=>{});
 $('#characterPick').onclick=()=>$('#fileInput').click();for(const [id,key,min,max] of [['characterLimit','limit',1,1000000],['characterRate','readRate',50,1500]])$('#'+id).onchange=e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<min||n>max){e.target.value=settings[key];return;}settings[key]=n;settingURL();schedule();};
 $('#characterInclude').onchange=e=>{settings.include=e.target.checked;settingURL();render();};schedule();
 return {async add(files){const file=files[0];try{if(file.size>8*1024*1024)throw Error('too large');const bytes=await file.arrayBuffer();const value=new TextDecoder('utf-8',{fatal:true}).decode(bytes);changeText(value);$('#characterInput').focus();}catch{toast(tr('fileError'),{error:true});}}};
}
