/** UI copy for the home directory and task pages (ko/en/ja). Tool titles and descriptions
 * still come from the shared intent messages; this file holds only the new shell's words. */
const S={
 ko:{homeTitle:'어떤 파일 작업을 할까요?',homeLead:'설치·가입·업로드 없이, 파일은 내 기기 안에서만 처리됩니다.',dropTitle:'파일을 여기에 놓으세요',dropHint:'종류를 알아보고 맞는 도구를 바로 엽니다 · 여러 개 가능',pick:'파일 선택',search:'도구 검색 — 예: pdf 합치기, png jpg, 배경 제거',searchLabel:'도구 검색',noResult:'맞는 도구가 없습니다. 다른 말로 찾아보세요.',
  cat:{image:'이미지',pdf:'PDF',video:'영상·오디오',game:'게임 에셋'},suggest:'{n}개 파일 · 어떤 작업을 할까요?',suggestMixed:'종류가 다른 파일이 섞여 있습니다. 한 종류씩 놓아 주세요.',suggestUnknown:'지원하지 않는 파일 형식입니다.',clear:'취소',
  allTools:'모든 도구',local:'업로드 없음 · 이 기기에서 처리',sample:'샘플로 해보기',paste:'붙여넣기(Ctrl+V)도 됩니다',taskDrop:'{kind}을(를) 여기에 놓으세요',kinds:{image:'이미지',pdf:'PDF',media:'영상'},multi:'여러 개를 한 번에 처리할 수 있습니다',
  add:'+ 파일 추가',removeAll:'모두 지우기',remove:'목록에서 빼기',download:'다운로드',downloadAll:'모두 다운로드 ({n}개 · ZIP)',saveOne:'이 파일만 저장',advanced:'고급 설정',openEditor:'고급 편집기에서 열기',next:'이어서 하기',
  waiting:'대기 중',working:'처리 중…',failed:'실패',compareHint:'가운데 선을 좌우로 끌어 원본과 결과를 비교하세요.',before:'원본',after:'결과',compare:'원본과 결과 비교',files:'{n}개 파일',calculating:'계산 중…',
  wrongKind:'이 도구는 {kind} 파일만 처리합니다.',zipping:'ZIP 파일을 만드는 중…',
  compress:{small:'가장 작게',smallHint:'공유·업로드용',balanced:'균형',balancedHint:'추천',high:'고화질',highHint:'인쇄·보관용',format:'저장 형식',auto:'자동 (가장 작은 형식)',target:'목표 용량 (KB)',targetHint:'0이면 화질 기준으로만 압축합니다',maxWidth:'최대 너비 (px)',maxWidthHint:'0이면 원본 크기 유지',quality:'화질',shrink:'목표 용량을 못 맞추면 크기도 줄이기',bg:'JPG 배경색',kept:'이미 충분히 작아 원본을 유지했습니다',missed:'목표 용량에 맞추지 못했습니다. 크기 줄이기를 켜 보세요.',saved:'{a} → {b}',samePixels:'해상도 {w}×{h} 유지',newPixels:'{w}×{h}로 축소',meta:'위치 정보 등 메타데이터는 저장되지 않습니다.'}},
 en:{homeTitle:'What do you need to do with your file?',homeLead:'No install, no sign-up, no upload — files are processed on your device.',dropTitle:'Drop files here',dropHint:'We detect the type and open the right tool · multiple files welcome',pick:'Choose files',search:'Search tools — e.g. merge pdf, png to jpg, remove background',searchLabel:'Search tools',noResult:'No matching tool. Try different words.',
  cat:{image:'Image',pdf:'PDF',video:'Video & audio',game:'Game assets'},suggest:'{n} file(s) · what would you like to do?',suggestMixed:'These files are of different kinds. Drop one kind at a time.',suggestUnknown:'This file type is not supported.',clear:'Cancel',
  allTools:'All tools',local:'No upload · processed on this device',sample:'Try a sample',paste:'You can also paste (Ctrl+V)',taskDrop:'Drop {kind} files here',kinds:{image:'image',pdf:'PDF',media:'video'},multi:'Process many files at once',
  add:'+ Add files',removeAll:'Clear all',remove:'Remove from list',download:'Download',downloadAll:'Download all ({n} · ZIP)',saveOne:'Save this file',advanced:'Advanced settings',openEditor:'Open in the advanced editor',next:'Continue with',
  waiting:'Waiting',working:'Working…',failed:'Failed',compareHint:'Drag the divider to compare original and result.',before:'Original',after:'Result',compare:'Compare original and result',files:'{n} file(s)',calculating:'Calculating…',
  wrongKind:'This tool only handles {kind} files.',zipping:'Building ZIP…',
  compress:{small:'Smallest',smallHint:'sharing, uploads',balanced:'Balanced',balancedHint:'recommended',high:'High quality',highHint:'print, archive',format:'Output format',auto:'Auto (smallest format)',target:'Target size (KB)',targetHint:'0 compresses by quality only',maxWidth:'Max width (px)',maxWidthHint:'0 keeps the original size',quality:'Quality',shrink:'Reduce dimensions if the target cannot be met',bg:'JPG background',kept:'Already small — original kept',missed:'Target size not reached. Try allowing smaller dimensions.',saved:'{a} → {b}',samePixels:'{w}×{h} kept',newPixels:'resized to {w}×{h}',meta:'Metadata such as location is not written to the result.'}},
 ja:{homeTitle:'どんなファイル作業をしますか？',homeLead:'インストール・登録・アップロード不要。ファイルは端末の中だけで処理されます。',dropTitle:'ここにファイルをドロップ',dropHint:'種類を判別して合うツールを開きます · 複数可',pick:'ファイルを選択',search:'ツールを検索 — 例: pdf 結合, png jpg, 背景削除',searchLabel:'ツールを検索',noResult:'該当するツールがありません。別の言葉でお試しください。',
  cat:{image:'画像',pdf:'PDF',video:'動画・音声',game:'ゲーム素材'},suggest:'{n}個のファイル · 何をしますか？',suggestMixed:'種類の違うファイルが混ざっています。1種類ずつドロップしてください。',suggestUnknown:'対応していないファイル形式です。',clear:'キャンセル',
  allTools:'すべてのツール',local:'アップロードなし · この端末で処理',sample:'サンプルで試す',paste:'貼り付け(Ctrl+V)もできます',taskDrop:'{kind}をここにドロップ',kinds:{image:'画像',pdf:'PDF',media:'動画'},multi:'複数のファイルをまとめて処理できます',
  add:'+ ファイルを追加',removeAll:'すべて消去',remove:'リストから外す',download:'ダウンロード',downloadAll:'すべてダウンロード（{n}個 · ZIP）',saveOne:'このファイルだけ保存',advanced:'詳細設定',openEditor:'高度なエディターで開く',next:'続けて作業',
  waiting:'待機中',working:'処理中…',failed:'失敗',compareHint:'中央の線を左右に動かして元と結果を比べてください。',before:'元',after:'結果',compare:'元と結果を比較',files:'{n}個のファイル',calculating:'計算中…',
  wrongKind:'このツールは{kind}ファイルだけ処理します。',zipping:'ZIPを作成中…',
  compress:{small:'最小',smallHint:'共有・アップロード用',balanced:'バランス',balancedHint:'おすすめ',high:'高画質',highHint:'印刷・保管用',format:'保存形式',auto:'自動（最も小さい形式）',target:'目標サイズ (KB)',targetHint:'0なら画質だけで圧縮します',maxWidth:'最大幅 (px)',maxWidthHint:'0なら元のサイズのまま',quality:'画質',shrink:'目標に届かない場合はサイズも縮小',bg:'JPGの背景色',kept:'すでに十分小さいため元のままです',missed:'目標サイズに届きませんでした。サイズの縮小を許可してみてください。',saved:'{a} → {b}',samePixels:'解像度 {w}×{h} を維持',newPixels:'{w}×{h}に縮小',meta:'位置情報などのメタデータは保存されません。'}}
};
Object.assign(S.ko,{
 convert:{jpeg:'사진·호환성',png:'무손실·투명',webp:'웹용·작은 용량',avif:'최신·가장 작음',qualityHint:'JPG·WebP·AVIF에만 적용됩니다. PNG는 항상 무손실입니다.',alpha:'JPG는 투명을 지원하지 않아 투명한 부분이 배경색으로 채워집니다.'},
 resize:{byPercent:'비율(%)로',bySize:'픽셀로',width:'너비 (px)',height:'높이 (px)',auto:'자동',preset:'SNS·플랫폼 규격',fit:'너비·높이를 둘 다 정했을 때',contain:'전체가 보이게 맞춤',cover:'꽉 채우고 넘치는 부분 자르기',stretch:'비율 무시하고 늘리기',fitHint:'한쪽만 입력하면 원본 비율을 유지합니다.',keep:'원본 형식 유지',noEnlarge:'원본보다 크게 만들지 않기',bg:'여백 색',bgOn:'여백 채우기',mixed:'{n}가지 크기'}});
Object.assign(S.en,{
 convert:{jpeg:'photos, compatibility',png:'lossless, transparency',webp:'web, smaller files',avif:'newest, smallest',qualityHint:'Applies to JPG, WebP and AVIF. PNG is always lossless.',alpha:'JPG has no transparency; transparent areas are filled with the background colour.'},
 resize:{byPercent:'By percent',bySize:'By pixels',width:'Width (px)',height:'Height (px)',auto:'auto',preset:'Social & platform sizes',fit:'When both width and height are set',contain:'Fit inside (show everything)',cover:'Fill and crop the overflow',stretch:'Stretch, ignore ratio',fitHint:'Enter only one side to keep the original ratio.',keep:'Keep original format',noEnlarge:'Never make images larger than the original',bg:'Margin colour',bgOn:'Fill margins',mixed:'{n} different sizes'}});
Object.assign(S.ja,{
 convert:{jpeg:'写真・互換性',png:'可逆・透明',webp:'Web向け・小さい',avif:'最新・最小',qualityHint:'JPG・WebP・AVIFにだけ適用されます。PNGは常に可逆です。',alpha:'JPGは透明を扱えないため、透明部分は背景色で塗られます。'},
 resize:{byPercent:'割合(%)で',bySize:'ピクセルで',width:'幅 (px)',height:'高さ (px)',auto:'自動',preset:'SNS・各サービスの規格',fit:'幅と高さを両方指定したとき',contain:'全体が見えるように収める',cover:'埋めて、はみ出しを切り取る',stretch:'比率を無視して伸ばす',fitHint:'片方だけ入力すると元の比率を保ちます。',keep:'元の形式のまま',noEnlarge:'元より大きくしない',bg:'余白の色',bgOn:'余白を塗る',mixed:'{n}種類のサイズ'}});
S.ko.pdf={drop:'PDF를 여기에 놓으세요',dropHint:'여러 파일을 한 번에 · 이미지도 페이지로 넣을 수 있습니다',tools:'페이지 도구',pages:'페이지 목록',hint:'페이지를 끌어서 순서를 바꾸세요. 클릭으로 선택, Shift·Ctrl로 여러 장 선택, Delete로 삭제, Ctrl+Z로 되돌리기.',selectAll:'전체 선택',rotateLeft:'왼쪽으로 회전',rotateRight:'오른쪽으로 회전',moveBack:'앞으로 옮기기',moveForward:'뒤로 옮기기',duplicate:'복제',delete:'삭제',undo:'되돌리기',
 selectedN:'{n}쪽 선택됨',noneSelected:'페이지를 클릭해 선택하세요',pagesN:'{n}쪽',pageN:'{n}쪽',outputs:'파일 {n}개로 저장',part:'파일 {n}',addFiles:'+ PDF·이미지 추가',sortAZ:'파일 이름순 정렬',fileName:'저장할 파일 이름',optimize:'이미지를 최적화해 용량 줄이기',removeMeta:'문서 정보(작성자 등) 지우기',
 mode:{each:'한 쪽씩',every:'N쪽마다',ranges:'범위 지정','selected':'선택한 쪽만','odd-even':'홀수·짝수'},everyLabel:'몇 쪽마다 나눌까요?',rangesLabel:'나눌 범위',rangesHint:'세미콜론(;)으로 파일을 나눕니다. 예: 1-3; 4-8; 9',selectedHint:'왼쪽에서 고른 페이지만 새 PDF 하나로 저장합니다.',
 runMerge:'PDF 합치기 · 다운로드',runSplit:'PDF {n}개로 나누기 · 다운로드',working:'처리 중…',partProgress:'{a} / {b} 파일 만드는 중…',badRanges:'범위를 확인하세요',needSelection:'페이지를 먼저 선택하세요',doneMerge:'합치기 완료',doneSplit:'나누기 완료',again:'다시 다운로드'};
S.en.pdf={drop:'Drop PDF files here',dropHint:'Several files at once · images can be added as pages too',tools:'Page tools',pages:'Pages',hint:'Drag pages to reorder. Click to select, Shift/Ctrl for several, Delete to remove, Ctrl+Z to undo.',selectAll:'Select all',rotateLeft:'Rotate left',rotateRight:'Rotate right',moveBack:'Move earlier',moveForward:'Move later',duplicate:'Duplicate',delete:'Delete',undo:'Undo',
 selectedN:'{n} page(s) selected',noneSelected:'Click pages to select them',pagesN:'{n} pages',pageN:'Page {n}',outputs:'{n} output file(s)',part:'File {n}',addFiles:'+ Add PDFs or images',sortAZ:'Sort files A–Z',fileName:'Output file name',optimize:'Optimise images to reduce size',removeMeta:'Remove document info (author…)',
 mode:{each:'Every page',every:'Every N pages',ranges:'Custom ranges','selected':'Selected only','odd-even':'Odd / even'},everyLabel:'Split after every … pages',rangesLabel:'Ranges',rangesHint:'Separate files with semicolons, e.g. 1-3; 4-8; 9',selectedHint:'Only the pages you selected are saved, as one new PDF.',
 runMerge:'Merge PDF · Download',runSplit:'Split into {n} PDF(s) · Download',working:'Working…',partProgress:'Creating file {a} / {b}…',badRanges:'Check the ranges',needSelection:'Select pages first',doneMerge:'Merged',doneSplit:'Split complete',again:'Download again'};
S.ja.pdf={drop:'ここにPDFをドロップ',dropHint:'複数ファイルをまとめて · 画像もページとして追加できます',tools:'ページツール',pages:'ページ一覧',hint:'ページをドラッグして並べ替え。クリックで選択、Shift・Ctrlで複数選択、Deleteで削除、Ctrl+Zで元に戻す。',selectAll:'すべて選択',rotateLeft:'左に回転',rotateRight:'右に回転',moveBack:'前へ移動',moveForward:'後ろへ移動',duplicate:'複製',delete:'削除',undo:'元に戻す',
 selectedN:'{n}ページ選択中',noneSelected:'ページをクリックして選択',pagesN:'{n}ページ',pageN:'{n}ページ',outputs:'{n}個のファイルに保存',part:'ファイル{n}',addFiles:'+ PDF・画像を追加',sortAZ:'ファイル名順に並べる',fileName:'保存するファイル名',optimize:'画像を最適化して容量を減らす',removeMeta:'文書情報（作成者など）を削除',
 mode:{each:'1ページずつ',every:'Nページごと',ranges:'範囲を指定','selected':'選択のみ','odd-even':'奇数・偶数'},everyLabel:'何ページごとに分けますか？',rangesLabel:'分割する範囲',rangesHint:'セミコロン(;)でファイルを区切ります。例: 1-3; 4-8; 9',selectedHint:'選んだページだけを1つの新しいPDFとして保存します。',
 runMerge:'PDFを結合 · ダウンロード',runSplit:'{n}個のPDFに分割 · ダウンロード',working:'処理中…',partProgress:'{a} / {b} ファイルを作成中…',badRanges:'範囲を確認してください',needSelection:'先にページを選択してください',doneMerge:'結合しました',doneSplit:'分割しました',again:'もう一度ダウンロード'};
Object.assign(S.ko.pdf,{dropImages:'사진·이미지를 여기에 놓으세요',dropImagesHint:'여러 장을 한 PDF로 · 순서는 끌어서 바꿀 수 있습니다',size:{a4:'A4',letter:'Letter',fit:'사진 크기 그대로'},margin:{0:'여백 없음',24:'좁은 여백',48:'넓은 여백'},runPdf:'PDF 만들기 · 다운로드',donePdf:'PDF 완성'});
Object.assign(S.en.pdf,{dropImages:'Drop photos or images here',dropImagesHint:'Many images into one PDF · drag to change the order',size:{a4:'A4',letter:'Letter',fit:'Same as image'},margin:{0:'No margin',24:'Small margin',48:'Large margin'},runPdf:'Create PDF · Download',donePdf:'PDF ready'});
Object.assign(S.ja.pdf,{dropImages:'ここに写真・画像をドロップ',dropImagesHint:'複数の画像を1つのPDFに · ドラッグで順番を変えられます',size:{a4:'A4',letter:'Letter',fit:'画像サイズのまま'},margin:{0:'余白なし',24:'狭い余白',48:'広い余白'},runPdf:'PDFを作成 · ダウンロード',donePdf:'PDFができました'});
Object.assign(S.ko,{pdfc:{light:'약하게',lightHint:'화질 우선',balanced:'권장',balancedHint:'화질·용량 균형',strong:'강하게',strongHint:'가장 작게',raster:'페이지를 이미지로 바꿔서 더 줄이기',rasterWarn:'이 옵션을 켜면 글자 선택·검색이 되지 않습니다. 스캔 문서처럼 이미 이미지인 PDF에만 권합니다.',how:'PDF 안의 사진만 다시 압축하고 글자·도형·검색은 그대로 둡니다. 사진이 없는 PDF는 거의 줄지 않습니다.',kept:'이미 충분히 작아 원본을 유지했습니다',textKept:'글자·검색 유지',textLost:'글자 선택 불가(이미지 PDF)',images:'사진 {n}개 최적화'},
 p2i:{screen:'화면용',screenHint:'가볍게',standard:'표준',standardHint:'추천',print:'인쇄용',printHint:'가장 선명',range:'변환할 페이지',rangeHint:'비워 두면 전체. 예: 1,3-5',maxSide:'긴 변 픽셀 직접 지정',made:'{f} {n}장',images:'이미지 {n}장'}});
Object.assign(S.en,{pdfc:{light:'Light',lightHint:'best quality',balanced:'Recommended',balancedHint:'quality and size',strong:'Strong',strongHint:'smallest',raster:'Flatten pages to images for extra reduction',rasterWarn:'Text can no longer be selected or searched. Only recommended for PDFs that are already scans.',how:'Only the photos inside the PDF are recompressed; text, vectors and search stay as they are. PDFs without photos barely shrink.',kept:'Already small — original kept',textKept:'text and search kept',textLost:'text not selectable (image PDF)',images:'{n} image(s) optimised'},
 p2i:{screen:'Screen',screenHint:'lightweight',standard:'Standard',standardHint:'recommended',print:'Print',printHint:'sharpest',range:'Pages to convert',rangeHint:'Empty = all. Example: 1,3-5',maxSide:'Exact longest side in pixels',made:'{n} {f} image(s)',images:'{n} image(s)'}});
Object.assign(S.ja,{pdfc:{light:'弱め',lightHint:'画質優先',balanced:'おすすめ',balancedHint:'画質と容量のバランス',strong:'強め',strongHint:'最小',raster:'ページを画像化してさらに小さくする',rasterWarn:'文字の選択・検索ができなくなります。すでにスキャン画像のPDFにだけおすすめします。',how:'PDF内の写真だけを再圧縮し、文字・図形・検索はそのままです。写真のないPDFはほとんど小さくなりません。',kept:'すでに十分小さいため元のままです',textKept:'文字・検索を維持',textLost:'文字選択不可（画像PDF）',images:'写真{n}点を最適化'},
 p2i:{screen:'画面用',screenHint:'軽い',standard:'標準',standardHint:'おすすめ',print:'印刷用',printHint:'最も鮮明',range:'変換するページ',rangeHint:'空欄は全ページ。例: 1,3-5',maxSide:'長辺のピクセルを直接指定',made:'{f} {n}枚',images:'画像{n}枚'}});
export function ui(locale,key,vars={}){
 let v=key.split('.').reduce((o,k)=>o?.[k],S[locale]||S.en)??key.split('.').reduce((o,k)=>o?.[k],S.en)??key;
 return String(v).replace(/\{(\w+)\}/g,(_,k)=>vars[k]??'');
}
export const UI_LOCALES=Object.keys(S);
export const UI_STRINGS=S;
