/** UI copy for the home directory and task pages (ko/en/ja). Tool titles and descriptions
 * still come from the shared intent messages; this file holds only the new shell's words. */
const S={
 ko:{homeTitle:'어떤 파일 작업을 할까요?',homeLead:'설치·가입·업로드 없이, 파일은 내 기기 안에서만 처리됩니다.',dropTitle:'파일을 여기에 놓으세요',dropHint:'종류를 알아보고 맞는 도구를 바로 엽니다 · 여러 개 가능',pick:'파일 선택',search:'도구 검색 — 예: pdf 합치기, png jpg, 배경 제거',searchLabel:'도구 검색',noResult:'맞는 도구가 없습니다. 다른 말로 찾아보세요.',
  cat:{image:'이미지',pdf:'PDF',video:'영상·오디오',game:'게임 에셋'},suggest:'{n}개 파일 · 어떤 작업을 할까요?',suggestMixed:'종류가 다른 파일이 섞여 있습니다. 한 종류씩 놓아 주세요.',suggestUnknown:'지원하지 않는 파일 형식입니다.',clear:'취소',
  allTools:'모든 도구',local:'업로드 없음 · 이 기기에서 처리',sample:'샘플로 해보기',paste:'붙여넣기(Ctrl+V)도 됩니다',taskDrop:'{kind}을(를) 여기에 놓으세요',kinds:{image:'이미지',pdf:'PDF',media:'영상'},multi:'여러 개를 한 번에 처리할 수 있습니다',
  add:'+ 파일 추가',removeAll:'모두 지우기',remove:'목록에서 빼기',download:'다운로드',downloadAll:'모두 다운로드 ({n}개 · ZIP)',saveOne:'이 파일만 저장',advanced:'고급 설정',openEditor:'고급 편집기에서 열기',next:'이어서 하기',
  waiting:'대기 중',working:'처리 중…',failed:'실패',compareHint:'가운데 선을 좌우로 끌어 원본과 결과를 비교하세요.',before:'원본',after:'결과',compare:'원본과 결과 비교',files:'{n}개 파일',calculating:'계산 중…',
  wrongKind:'이 도구는 {kind} 파일만 처리합니다.',zipping:'ZIP 파일을 만드는 중…',
  compress:{small:'가장 작게',smallHint:'공유·업로드용',balanced:'균형',balancedHint:'추천',high:'고화질',highHint:'인쇄·보관용',format:'저장 형식',auto:'자동 (가장 작은 형식)',target:'목표 용량 (KB)',targetHint:'0이면 화질 기준으로만 압축합니다',maxWidth:'최대 너비 (px)',maxWidthHint:'0이면 원본 크기 유지',quality:'화질',shrink:'목표 용량을 못 맞추면 크기도 줄이기',bg:'JPG 배경색',kept:'이미 충분히 작아 원본을 유지했습니다',missed:'목표 용량에 맞추지 못했습니다. 크기 줄이기를 켜 보세요.',saved:'{a} → {b}',samePixels:'해상도 {w}×{h} 유지',newPixels:'{w}×{h}로 축소',meta:'위치 정보 등 메타데이터는 저장되지 않습니다.'}},
 en:{homeTitle:'What do you need to do with your file?',homeLead:'No install, no sign-up, no upload — files are processed on your device.',dropTitle:'Drop files here',dropHint:'We detect the type and open the right tool · multiple files welcome',pick:'Choose files',search:'Search tools — e.g. merge pdf, png to jpg, remove background',searchLabel:'Search tools',noResult:'No matching tool. Try different words.',
  cat:{image:'Image',pdf:'PDF',video:'Video & audio',game:'Game assets'},suggest:'{n} file(s) · what would you like to do?',suggestMixed:'These files are of different kinds. Drop one kind at a time.',suggestUnknown:'This file type is not supported.',clear:'Cancel',
  allTools:'All tools',local:'No upload · processed on this device',sample:'Try a sample',paste:'You can also paste (Ctrl+V)',taskDrop:'Drop {kind} files here',kinds:{image:'image',pdf:'PDF',media:'video'},multi:'Process many files at once',
  add:'+ Add files',removeAll:'Clear all',remove:'Remove from list',download:'Download',downloadAll:'Download all ({n} · ZIP)',saveOne:'Save this file',advanced:'Advanced settings',openEditor:'Open in the advanced editor',next:'Continue with',
  waiting:'Waiting',working:'Working…',failed:'Failed',compareHint:'Drag the divider to compare original and result.',before:'Original',after:'Result',compare:'Compare original and result',files:'{n} file(s)',calculating:'Calculating…',
  wrongKind:'This tool only handles {kind} files.',zipping:'Building ZIP…',
  compress:{small:'Smallest',smallHint:'sharing, uploads',balanced:'Balanced',balancedHint:'recommended',high:'High quality',highHint:'print, archive',format:'Output format',auto:'Auto (smallest format)',target:'Target size (KB)',targetHint:'0 compresses by quality only',maxWidth:'Max width (px)',maxWidthHint:'0 keeps the original size',quality:'Quality',shrink:'Reduce dimensions if the target cannot be met',bg:'JPG background',kept:'Already small — original kept',missed:'Target size not reached. Try allowing smaller dimensions.',saved:'{a} → {b}',samePixels:'{w}×{h} kept',newPixels:'resized to {w}×{h}',meta:'Metadata such as location is not written to the result.'}},
 ja:{homeTitle:'どんなファイル作業をしますか？',homeLead:'インストール・登録・アップロード不要。ファイルは端末の中だけで処理されます。',dropTitle:'ここにファイルをドロップ',dropHint:'種類を判別して合うツールを開きます · 複数可',pick:'ファイルを選択',search:'ツールを検索 — 例: pdf 結合, png jpg, 背景削除',searchLabel:'ツールを検索',noResult:'該当するツールがありません。別の言葉でお試しください。',
  cat:{image:'画像',pdf:'PDF',video:'動画・音声',game:'ゲーム素材'},suggest:'{n}個のファイル · 何をしますか？',suggestMixed:'種類の違うファイルが混ざっています。1種類ずつドロップしてください。',suggestUnknown:'対応していないファイル形式です。',clear:'キャンセル',
  allTools:'すべてのツール',local:'アップロードなし · この端末で処理',sample:'サンプルで試す',paste:'貼り付け(Ctrl+V)もできます',taskDrop:'{kind}をここにドロップ',kinds:{image:'画像',pdf:'PDF',media:'動画'},multi:'複数のファイルをまとめて処理できます',
  add:'+ ファイルを追加',removeAll:'すべて消去',remove:'リストから外す',download:'ダウンロード',downloadAll:'すべてダウンロード（{n}個 · ZIP）',saveOne:'このファイルだけ保存',advanced:'詳細設定',openEditor:'高度なエディターで開く',next:'続けて作業',
  waiting:'待機中',working:'処理中…',failed:'失敗',compareHint:'中央の線を左右に動かして元と結果を比べてください。',before:'元',after:'結果',compare:'元と結果を比較',files:'{n}個のファイル',calculating:'計算中…',
  wrongKind:'このツールは{kind}ファイルだけ処理します。',zipping:'ZIPを作成中…',
  compress:{small:'最小',smallHint:'共有・アップロード用',balanced:'バランス',balancedHint:'おすすめ',high:'高画質',highHint:'印刷・保管用',format:'保存形式',auto:'自動（最も小さい形式）',target:'目標サイズ (KB)',targetHint:'0なら画質だけで圧縮します',maxWidth:'最大幅 (px)',maxWidthHint:'0なら元のサイズのまま',quality:'画質',shrink:'目標に届かない場合はサイズも縮小',bg:'JPGの背景色',kept:'すでに十分小さいため元のままです',missed:'目標サイズに届きませんでした。サイズの縮小を許可してみてください。',saved:'{a} → {b}',samePixels:'解像度 {w}×{h} を維持',newPixels:'{w}×{h}に縮小',meta:'位置情報などのメタデータは保存されません。'}}
};
Object.assign(S.ko,{
 convert:{jpeg:'사진·호환성',png:'무손실·투명',webp:'웹용·작은 용량',avif:'최신·가장 작음',qualityHint:'JPG·WebP·AVIF에만 적용됩니다. PNG는 항상 무손실입니다.',alpha:'JPG는 투명을 지원하지 않아 투명한 부분이 배경색으로 채워집니다.'},
 resize:{byPercent:'비율(%)로',bySize:'픽셀로',width:'너비 (px)',height:'높이 (px)',auto:'자동',preset:'SNS·플랫폼 규격',fit:'너비·높이를 둘 다 정했을 때',contain:'전체가 보이게 맞춤',cover:'꽉 채우고 넘치는 부분 자르기',stretch:'비율 무시하고 늘리기',fitHint:'한쪽만 입력하면 원본 비율을 유지합니다.',keep:'원본 형식 유지',noEnlarge:'원본보다 크게 만들지 않기',bg:'여백 색',bgOn:'여백 채우기',mixed:'{n}가지 크기'}});
Object.assign(S.en,{
 convert:{jpeg:'photos, compatibility',png:'lossless, transparency',webp:'web, smaller files',avif:'newest, smallest',qualityHint:'Applies to JPG, WebP and AVIF. PNG is always lossless.',alpha:'JPG has no transparency; transparent areas are filled with the background colour.'},
 resize:{byPercent:'By percent',bySize:'By pixels',width:'Width (px)',height:'Height (px)',auto:'auto',preset:'Social & platform sizes',fit:'When both width and height are set',contain:'Fit inside (show everything)',cover:'Fill and crop the overflow',stretch:'Stretch, ignore ratio',fitHint:'Enter only one side to keep the original ratio.',keep:'Keep original format',noEnlarge:'Never make images larger than the original',bg:'Margin colour',bgOn:'Fill margins',mixed:'{n} different sizes'}});
Object.assign(S.ja,{
 convert:{jpeg:'写真・互換性',png:'可逆・透明',webp:'Web向け・小さい',avif:'最新・最小',qualityHint:'JPG・WebP・AVIFにだけ適用されます。PNGは常に可逆です。',alpha:'JPGは透明を扱えないため、透明部分は背景色で塗られます。'},
 resize:{byPercent:'割合(%)で',bySize:'ピクセルで',width:'幅 (px)',height:'高さ (px)',auto:'自動',preset:'SNS・各サービスの規格',fit:'幅と高さを両方指定したとき',contain:'全体が見えるように収める',cover:'埋めて、はみ出しを切り取る',stretch:'比率を無視して伸ばす',fitHint:'片方だけ入力すると元の比率を保ちます。',keep:'元の形式のまま',noEnlarge:'元より大きくしない',bg:'余白の色',bgOn:'余白を塗る',mixed:'{n}種類のサイズ'}});
S.ko.pdf={drop:'PDF를 여기에 놓으세요',dropHint:'여러 파일을 한 번에 · 이미지도 페이지로 넣을 수 있습니다',tools:'페이지 도구',pages:'페이지 목록',hint:'페이지를 끌어서 순서를 바꾸세요. 클릭으로 선택, Shift·Ctrl로 여러 장 선택, Delete로 삭제, Ctrl+Z로 되돌리기.',selectAll:'전체 선택',rotateLeft:'왼쪽으로 회전',rotateRight:'오른쪽으로 회전',moveBack:'앞으로 옮기기',moveForward:'뒤로 옮기기',duplicate:'복제',delete:'삭제',undo:'되돌리기',
 selectedN:'{n}쪽 선택됨',noneSelected:'페이지를 클릭해 선택하세요',pagesN:'{n}쪽',pageN:'{n}쪽',outputs:'파일 {n}개로 저장',part:'파일 {n}',addFiles:'+ PDF·이미지 추가',sortAZ:'파일 이름순 정렬',fileName:'저장할 파일 이름',optimize:'이미지를 최적화해 용량 줄이기',removeMeta:'문서 정보(작성자 등) 지우기',
 mode:{each:'한 쪽씩',every:'N쪽마다',ranges:'범위 지정','selected':'선택한 쪽만','odd-even':'홀수·짝수'},everyLabel:'몇 쪽마다 나눌까요?',rangesLabel:'나눌 범위',rangesHint:'세미콜론(;)으로 파일을 나눕니다. 예: 1-3; 4-8; 9',selectedHint:'왼쪽에서 고른 페이지만 새 PDF 하나로 저장합니다.',
 runMerge:'PDF 합치기 · 다운로드',runSplit:'PDF {n}개로 나누기 · 다운로드',working:'처리 중…',partProgress:'{a} / {b} 파일 만드는 중…',badRanges:'범위를 확인하세요',needSelection:'페이지를 먼저 선택하세요',doneMerge:'합치기 완료',doneSplit:'나누기 완료',again:'다시 다운로드'};
S.en.pdf={drop:'Drop PDF files here',dropHint:'Several files at once · images can be added as pages too',tools:'Page tools',pages:'Pages',hint:'Drag pages to reorder. Click to select, Shift/Ctrl for several, Delete to remove, Ctrl+Z to undo.',selectAll:'Select all',rotateLeft:'Rotate left',rotateRight:'Rotate right',moveBack:'Move earlier',moveForward:'Move later',duplicate:'Duplicate',delete:'Delete',undo:'Undo',
 selectedN:'{n} page(s) selected',noneSelected:'Click pages to select them',pagesN:'{n} pages',pageN:'Page {n}',outputs:'{n} output file(s)',part:'File {n}',addFiles:'+ Add PDFs or images',sortAZ:'Sort files A–Z',fileName:'Output file name',optimize:'Optimise images to reduce size',removeMeta:'Remove document info (author…)',
 mode:{each:'Every page',every:'Every N pages',ranges:'Custom ranges','selected':'Selected only','odd-even':'Odd / even'},everyLabel:'Split after every … pages',rangesLabel:'Ranges',rangesHint:'Separate files with semicolons, e.g. 1-3; 4-8; 9',selectedHint:'Only the pages you selected are saved, as one new PDF.',
 runMerge:'Merge PDF · Download',runSplit:'Split into {n} PDF(s) · Download',working:'Working…',partProgress:'Creating file {a} / {b}…',badRanges:'Check the ranges',needSelection:'Select pages first',doneMerge:'Merged',doneSplit:'Split complete',again:'Download again'};
S.ja.pdf={drop:'ここにPDFをドロップ',dropHint:'複数ファイルをまとめて · 画像もページとして追加できます',tools:'ページツール',pages:'ページ一覧',hint:'ページをドラッグして並べ替え。クリックで選択、Shift・Ctrlで複数選択、Deleteで削除、Ctrl+Zで元に戻す。',selectAll:'すべて選択',rotateLeft:'左に回転',rotateRight:'右に回転',moveBack:'前へ移動',moveForward:'後ろへ移動',duplicate:'複製',delete:'削除',undo:'元に戻す',
 selectedN:'{n}ページ選択中',noneSelected:'ページをクリックして選択',pagesN:'{n}ページ',pageN:'{n}ページ',outputs:'{n}個のファイルに保存',part:'ファイル{n}',addFiles:'+ PDF・画像を追加',sortAZ:'ファイル名順に並べる',fileName:'保存するファイル名',optimize:'画像を最適化して容量を減らす',removeMeta:'文書情報（作成者など）を削除',
 mode:{each:'1ページずつ',every:'Nページごと',ranges:'範囲を指定','selected':'選択のみ','odd-even':'奇数・偶数'},everyLabel:'何ページごとに分けますか？',rangesLabel:'分割する範囲',rangesHint:'セミコロン(;)でファイルを区切ります。例: 1-3; 4-8; 9',selectedHint:'選んだページだけを1つの新しいPDFとして保存します。',
 runMerge:'PDFを結合 · ダウンロード',runSplit:'{n}個のPDFに分割 · ダウンロード',working:'処理中…',partProgress:'{a} / {b} ファイルを作成中…',badRanges:'範囲を確認してください',needSelection:'先にページを選択してください',doneMerge:'結合しました',doneSplit:'分割しました',again:'もう一度ダウンロード'};
Object.assign(S.ko.pdf,{dropImages:'사진·이미지를 여기에 놓으세요',dropImagesHint:'여러 장을 한 PDF로 · 순서는 끌어서 바꿀 수 있습니다',size:{a4:'A4',letter:'Letter',fit:'사진 크기 그대로'},margin:{0:'여백 없음',24:'좁은 여백',48:'넓은 여백'},runPdf:'PDF 만들기 · 다운로드',donePdf:'PDF 완성'});
Object.assign(S.en.pdf,{dropImages:'Drop photos or images here',dropImagesHint:'Many images into one PDF · drag to change the order',size:{a4:'A4',letter:'Letter',fit:'Same as image'},margin:{0:'No margin',24:'Small margin',48:'Large margin'},runPdf:'Create PDF · Download',donePdf:'PDF ready'});
Object.assign(S.ja.pdf,{dropImages:'ここに写真・画像をドロップ',dropImagesHint:'複数の画像を1つのPDFに · ドラッグで順番を変えられます',size:{a4:'A4',letter:'Letter',fit:'画像サイズのまま'},margin:{0:'余白なし',24:'狭い余白',48:'広い余白'},runPdf:'PDFを作成 · ダウンロード',donePdf:'PDFができました'});
Object.assign(S.ko,{pdfc:{light:'약하게',lightHint:'화질 우선',balanced:'권장',balancedHint:'화질·용량 균형',strong:'강하게',strongHint:'가장 작게',raster:'페이지를 이미지로 바꿔서 더 줄이기',rasterWarn:'이 옵션을 켜면 글자 선택·검색이 되지 않습니다. 스캔 문서처럼 이미 이미지인 PDF에만 권합니다.',how:'PDF 안의 사진만 다시 압축하고 글자·도형·검색은 그대로 둡니다. 사진이 없는 PDF는 거의 줄지 않습니다.',kept:'이미 충분히 작아 원본을 유지했습니다',textKept:'글자·검색 유지',textLost:'글자 선택 불가(이미지 PDF)',images:'사진 {n}개 최적화'},
 p2i:{screen:'화면용',screenHint:'가볍게',standard:'표준',standardHint:'추천',print:'인쇄용',printHint:'가장 선명',range:'변환할 페이지',rangeHint:'비워 두면 전체. 예: 1,3-5',maxSide:'긴 변 픽셀 직접 지정',made:'{f} {n}장',images:'이미지 {n}장'}});
Object.assign(S.en,{pdfc:{light:'Light',lightHint:'best quality',balanced:'Recommended',balancedHint:'quality and size',strong:'Strong',strongHint:'smallest',raster:'Flatten pages to images for extra reduction',rasterWarn:'Text can no longer be selected or searched. Only recommended for PDFs that are already scans.',how:'Only the photos inside the PDF are recompressed; text, vectors and search stay as they are. PDFs without photos barely shrink.',kept:'Already small — original kept',textKept:'text and search kept',textLost:'text not selectable (image PDF)',images:'{n} image(s) optimised'},
 p2i:{screen:'Screen',screenHint:'lightweight',standard:'Standard',standardHint:'recommended',print:'Print',printHint:'sharpest',range:'Pages to convert',rangeHint:'Empty = all. Example: 1,3-5',maxSide:'Exact longest side in pixels',made:'{n} {f} image(s)',images:'{n} image(s)'}});
Object.assign(S.ja,{pdfc:{light:'弱め',lightHint:'画質優先',balanced:'おすすめ',balancedHint:'画質と容量のバランス',strong:'強め',strongHint:'最小',raster:'ページを画像化してさらに小さくする',rasterWarn:'文字の選択・検索ができなくなります。すでにスキャン画像のPDFにだけおすすめします。',how:'PDF内の写真だけを再圧縮し、文字・図形・検索はそのままです。写真のないPDFはほとんど小さくなりません。',kept:'すでに十分小さいため元のままです',textKept:'文字・検索を維持',textLost:'文字選択不可（画像PDF）',images:'写真{n}点を最適化'},
 p2i:{screen:'画面用',screenHint:'軽い',standard:'標準',standardHint:'おすすめ',print:'印刷用',printHint:'最も鮮明',range:'変換するページ',rangeHint:'空欄は全ページ。例: 1,3-5',maxSide:'長辺のピクセルを直接指定',made:'{f} {n}枚',images:'画像{n}枚'}});
S.ko.edit={drop:'편집할 PDF를 여기에 놓으세요',dropHint:'글자·서명·이미지 추가, 지우기, 그리기, 도형 · 원본 글자와 검색은 그대로',tools:'편집 도구',color:'색',fontSize:'글자 크기',thickness:'굵기',bold:'굵게',undo:'되돌리기 (Ctrl+Z)',redo:'다시 실행 (Ctrl+Y)',deleteObject:'선택한 것 삭제 (Delete)',
 tool:{select:'선택',text:'글자',sign:'서명',image:'이미지',whiteout:'지우기',pen:'펜',highlight:'형광펜',rect:'사각형',ellipse:'원',line:'선',arrow:'화살표'},
 hint:{select:'추가한 것을 클릭해 옮기거나 크기를 바꾸세요. 방향키로 미세 이동, Delete로 삭제.',text:'글자를 넣을 곳을 클릭하고 입력하세요.',sign:'서명을 그리거나 입력하거나 이미지로 올리세요.',image:'넣을 이미지를 고르세요.',whiteout:'가릴 부분을 드래그하면 흰색으로 덮습니다. 아래 내용이 완전히 삭제되는 것은 아닙니다.',pen:'페이지 위에 자유롭게 그리세요.',highlight:'강조할 부분을 드래그하세요.',rect:'드래그해서 사각형을 그리세요.',ellipse:'드래그해서 원을 그리세요.',line:'드래그해서 선을 그리세요.',arrow:'드래그해서 화살표를 그리세요.'},
 changes:'추가한 항목 {n}개',save:'PDF 저장 · 다운로드',saved:'저장 완료',organize:'페이지 순서·회전·삭제',close:'다른 PDF 열기',prev:'이전 쪽',next:'다음 쪽',zoomIn:'확대',zoomOut:'축소',fit:'너비 맞춤',oneFile:'한 번에 한 파일만 편집합니다. 첫 번째 파일을 열었습니다.',
 sign:{title:'서명 만들기',draw:'그리기',type:'입력',upload:'이미지',clear:'지우기',placeholder:'이름을 입력하세요',removeWhite:'흰 배경을 투명하게',reuse:'이전 서명 다시 사용',cancel:'취소',use:'서명 넣기',empty:'서명을 먼저 만들어 주세요.'}};
S.en.edit={drop:'Drop the PDF you want to edit',dropHint:'Add text, signatures and images, whiteout, draw, shapes · original text and search are kept',tools:'Editing tools',color:'Colour',fontSize:'Font size',thickness:'Thickness',bold:'Bold',undo:'Undo (Ctrl+Z)',redo:'Redo (Ctrl+Y)',deleteObject:'Delete selection (Delete)',
 tool:{select:'Select',text:'Text',sign:'Sign',image:'Image',whiteout:'Whiteout',pen:'Pen',highlight:'Highlight',rect:'Rectangle',ellipse:'Ellipse',line:'Line',arrow:'Arrow'},
 hint:{select:'Click something you added to move or resize it. Arrow keys nudge, Delete removes.',text:'Click where the text should go and type.',sign:'Draw, type or upload your signature.',image:'Choose an image to place.',whiteout:'Drag over an area to cover it in white. The content underneath is covered, not securely removed.',pen:'Draw freely on the page.',highlight:'Drag over what you want to highlight.',rect:'Drag to draw a rectangle.',ellipse:'Drag to draw an ellipse.',line:'Drag to draw a line.',arrow:'Drag to draw an arrow.'},
 changes:'{n} item(s) added',save:'Save PDF · Download',saved:'Saved',organize:'Reorder, rotate or delete pages',close:'Open another PDF',prev:'Previous page',next:'Next page',zoomIn:'Zoom in',zoomOut:'Zoom out',fit:'Fit width',oneFile:'One file is edited at a time; the first one was opened.',
 sign:{title:'Create a signature',draw:'Draw',type:'Type',upload:'Image',clear:'Clear',placeholder:'Type your name',removeWhite:'Make the white background transparent',reuse:'Reuse previous signature',cancel:'Cancel',use:'Place signature',empty:'Create a signature first.'}};
S.ja.edit={drop:'編集するPDFをここにドロップ',dropHint:'文字・署名・画像の追加、消去、描画、図形 · 元の文字と検索はそのまま',tools:'編集ツール',color:'色',fontSize:'文字サイズ',thickness:'太さ',bold:'太字',undo:'元に戻す (Ctrl+Z)',redo:'やり直す (Ctrl+Y)',deleteObject:'選択を削除 (Delete)',
 tool:{select:'選択',text:'文字',sign:'署名',image:'画像',whiteout:'消去',pen:'ペン',highlight:'マーカー',rect:'四角形',ellipse:'円',line:'線',arrow:'矢印'},
 hint:{select:'追加したものをクリックして移動・サイズ変更。矢印キーで微調整、Deleteで削除。',text:'文字を入れたい場所をクリックして入力します。',sign:'署名を描く・入力する・画像で追加できます。',image:'配置する画像を選びます。',whiteout:'隠したい部分をドラッグすると白で覆います。下の内容が完全に削除されるわけではありません。',pen:'ページの上に自由に描けます。',highlight:'強調したい部分をドラッグします。',rect:'ドラッグして四角形を描きます。',ellipse:'ドラッグして円を描きます。',line:'ドラッグして線を描きます。',arrow:'ドラッグして矢印を描きます。'},
 changes:'追加した項目 {n}件',save:'PDFを保存 · ダウンロード',saved:'保存しました',organize:'ページの並べ替え・回転・削除',close:'別のPDFを開く',prev:'前のページ',next:'次のページ',zoomIn:'拡大',zoomOut:'縮小',fit:'幅に合わせる',oneFile:'一度に編集できるのは1ファイルです。最初のファイルを開きました。',
 sign:{title:'署名を作成',draw:'描く',type:'入力',upload:'画像',clear:'消去',placeholder:'名前を入力',removeWhite:'白い背景を透明にする',reuse:'前の署名を使う',cancel:'キャンセル',use:'署名を配置',empty:'先に署名を作成してください。'}};
S.ko.atlas={drop:'스프라이트 프레임을 여기에 놓으세요',dropHint:'PNG 여러 장 · 움직이는 GIF/APNG/WebP는 프레임으로 자동 분리',sheet:'시트',animation:'애니메이션 미리보기',frames:'프레임',outlines:'경계선 표시',fps:'초당 프레임(FPS)',sortName:'이름순',reverse:'순서 뒤집기',hint:'프레임을 끌어서 순서를 바꾸면 시트와 애니메이션이 바로 바뀝니다.',frameCount:'{n}프레임',efficiency:'공간 활용 {n}%',
 layout:'배치',layouts:{packed:'자동 포장',grid:'격자',row:'가로 한 줄',column:'세로 한 줄'},padding:'프레임 간격',format:'데이터 형식',trim:'투명 여백 잘라내기(트림)',pot:'2의 거듭제곱 크기 (256, 512…)',rotate:'공간 절약을 위해 90° 회전 허용',extrude:'가장자리 늘리기(px)',maxSize:'최대 크기',columns:'격자 열 수',pixelated:'도트를 선명하게 표시',add:'+ 프레임 추가',run:'시트 PNG + {f} 다운로드',cannot:'설정을 확인하세요',done:'ZIP으로 저장했습니다 ({size})'};
S.en.atlas={drop:'Drop sprite frames here',dropHint:'Many PNGs · animated GIF/APNG/WebP are split into frames',sheet:'Sheet',animation:'Animation preview',frames:'Frames',outlines:'Show outlines',fps:'Frames per second',sortName:'Sort by name',reverse:'Reverse',hint:'Drag frames to reorder; the sheet and the animation update immediately.',frameCount:'{n} frame(s)',efficiency:'{n}% of the area used',
 layout:'Layout',layouts:{packed:'Packed',grid:'Grid',row:'One row',column:'One column'},padding:'Spacing',format:'Data format',trim:'Trim transparent margins',pot:'Power-of-two size (256, 512…)',rotate:'Allow 90° rotation to save space',extrude:'Extrude edges (px)',maxSize:'Max size',columns:'Grid columns',pixelated:'Crisp pixels in previews',add:'+ Add frames',run:'Download sheet PNG + {f}',cannot:'Check the settings',done:'Saved as ZIP ({size})'};
S.ja.atlas={drop:'ここにスプライトのフレームをドロップ',dropHint:'複数のPNG · アニメGIF/APNG/WebPは自動でフレームに分割',sheet:'シート',animation:'アニメーションプレビュー',frames:'フレーム',outlines:'枠線を表示',fps:'毎秒フレーム数(FPS)',sortName:'名前順',reverse:'順番を反転',hint:'フレームをドラッグして並べ替えると、シートとアニメーションがすぐに変わります。',frameCount:'{n}フレーム',efficiency:'領域の{n}%を使用',
 layout:'配置',layouts:{packed:'自動パック',grid:'グリッド',row:'横一列',column:'縦一列'},padding:'フレーム間隔',format:'データ形式',trim:'透明な余白をトリム',pot:'2のべき乗サイズ (256, 512…)',rotate:'省スペースのため90°回転を許可',extrude:'端を引き伸ばす(px)',maxSize:'最大サイズ',columns:'グリッドの列数',pixelated:'プレビューをくっきり表示',add:'+ フレームを追加',run:'シートPNG + {f}をダウンロード',cannot:'設定を確認してください',done:'ZIPで保存しました（{size}）'};
Object.assign(S.ko.edit,{whole:'문서 전체에 넣기',apply:'모든 페이지에 적용',removeAll:'모두 제거',numbers:{title:'페이지 번호',position:'위치',format:'형식',start:'시작 번호',from:'몇 쪽부터',pos:{'bottom-center':'아래 가운데','bottom-right':'아래 오른쪽','bottom-left':'아래 왼쪽','top-center':'위 가운데','top-right':'위 오른쪽','top-left':'위 왼쪽'}},watermark:{title:'워터마크',text:'문구',sample:'대외비',opacity:'진하기',angle:'방향'}});
Object.assign(S.en.edit,{whole:'Add to the whole document',apply:'Apply to all pages',removeAll:'Remove all',numbers:{title:'Page numbers',position:'Position',format:'Format',start:'First number',from:'Start on page',pos:{'bottom-center':'Bottom centre','bottom-right':'Bottom right','bottom-left':'Bottom left','top-center':'Top centre','top-right':'Top right','top-left':'Top left'}},watermark:{title:'Watermark',text:'Text',sample:'CONFIDENTIAL',opacity:'Strength',angle:'Direction'}});
Object.assign(S.ja.edit,{whole:'文書全体に追加',apply:'全ページに適用',removeAll:'すべて削除',numbers:{title:'ページ番号',position:'位置',format:'形式',start:'開始番号',from:'何ページ目から',pos:{'bottom-center':'下・中央','bottom-right':'下・右','bottom-left':'下・左','top-center':'上・中央','top-right':'上・右','top-left':'上・左'}},watermark:{title:'透かし',text:'文字',sample:'社外秘',opacity:'濃さ',angle:'向き'}});
const PALETTE_NAMES={gameboy:'Game Boy',pico8:'PICO-8',sweetie16:'Sweetie 16',endesga32:'Endesga 32',nes:'NES',mono:'1-bit'};
S.ko.pixel={size:'도트 크기',colors:'색상 수',palette:'팔레트',auto:'이미지에서 자동 추출',custom:'직접 입력…',customHint:'한 줄에 색 하나 (#RRGGBB) 또는 GIMP 팔레트',exact:'정확한 크기 (px)',scale:'내보내기 배율',dither:'디더링',ditherNone:'없음',outline:'외곽선',trim:'투명 여백을 먼저 잘라내기',needPalette:'팔레트 색을 한 줄에 하나씩 입력하세요.',exported:'{w}×{h}로 저장',colorCount:'{n}색',palettes:PALETTE_NAMES};
S.en.pixel={size:'Sprite size',colors:'Colours',palette:'Palette',auto:'Extract from the image',custom:'Custom…',customHint:'One colour per line (#RRGGBB) or a GIMP palette',exact:'Exact size (px)',scale:'Export scale',dither:'Dithering',ditherNone:'None',outline:'Outline',trim:'Trim transparent margins first',needPalette:'Enter palette colours, one per line.',exported:'saved at {w}×{h}',colorCount:'{n} colours',palettes:PALETTE_NAMES};
S.ja.pixel={size:'ドットのサイズ',colors:'色数',palette:'パレット',auto:'画像から自動抽出',custom:'自分で入力…',customHint:'1行に1色（#RRGGBB）またはGIMPパレット',exact:'正確なサイズ (px)',scale:'書き出し倍率',dither:'ディザリング',ditherNone:'なし',outline:'アウトライン',trim:'先に透明な余白をトリム',needPalette:'パレットの色を1行に1つ入力してください。',exported:'{w}×{h}で保存',colorCount:'{n}色',palettes:PALETTE_NAMES};
S.ko.recipe={fit:'비율이 다를 때',noOptions:'이 도구는 설정 없이 바로 결과를 만듭니다.',files:'파일 {n}개',zipNote:'ZIP 안에 파일 {n}개'};
S.en.recipe={fit:'When the shape differs',noOptions:'This tool needs no settings.',files:'{n} files',zipNote:'{n} files inside the ZIP'};
S.ja.recipe={fit:'比率が違うとき',noOptions:'このツールは設定なしで結果を作ります。',files:'{n}個のファイル',zipNote:'ZIP内に{n}個のファイル'};
S.ko.bg={quality:'AI 품질',qualityBest:'고품질 (처음 한 번 190MB 받음)',qualityFast:'빠르게 (5MB 경량 모델)',noteQuick:'빠른 미리보기 · 고품질 결과로 곧 바뀝니다',bestFailed:'고품질 모델을 받지 못해 빠른 결과를 유지했습니다.',method:'지우는 방식',ai:'자동 (AI)',solid:'단색 배경',newBackground:'새 배경',none:'투명',white:'흰색',black:'검정',custom:'색 선택',blur:'원본 흐리게',color:'색',refine:'머리카락·경계를 원본 색에 맞춰 다듬기',cleanup:'경계에 남은 배경색 빼기',key:'지울 색',keyAuto:'가장자리에서 자동 감지',keyCustom:'직접 고르기',tolerance:'비슷한 색 허용 범위',trim:'피사체에 맞춰 여백 자르기',padding:'여백 (px)',format:'저장 형식',jpegHint:'JPG는 투명을 저장할 수 없어 흰 배경으로 채웁니다.',done:'배경 제거 완료',doneMany:'{n}장 배경 제거 완료',noteAi:'AI 피사체 인식',noteColor:'단색 배경 제거',noteEdited:'직접 다듬음',touchUp:'지우기·복원 브러시',erase:'지우기',restore:'복원',brush:'브러시 크기',undo:'되돌리기',reset:'처음으로',cancel:'취소',apply:'적용',brushHint:'흐리게 보이는 부분이 지워진 원본입니다. 복원으로 칠하면 되살아납니다. 확대하면 더 가는 붓으로 칠할 수 있습니다.',stage:{model:'AI 모델 받는 중 (처음 한 번)',prepare:'준비 중',find:'피사체 찾는 중',edges:'경계 다듬는 중'}};
S.en.bg={quality:'AI quality',qualityBest:'Best (one-time 190 MB download)',qualityFast:'Fast (5 MB light model)',noteQuick:'Quick preview · the high-quality result replaces it shortly',bestFailed:'The high-quality model could not be downloaded, so the quick result was kept.',method:'How to remove',ai:'Automatic (AI)',solid:'Solid backdrop',newBackground:'New background',none:'Transparent',white:'White',black:'Black',custom:'Pick a colour',blur:'Blur the original',color:'Colour',refine:'Follow hair and edges using the original colours',cleanup:'Remove backdrop colour left on edges',key:'Colour to remove',keyAuto:'Detect from the border',keyCustom:'Choose',tolerance:'Similar-colour range',trim:'Crop to the subject',padding:'Padding (px)',format:'Save as',jpegHint:'JPG cannot store transparency, so the background is filled white.',done:'Background removed',doneMany:'{n} backgrounds removed',noteAi:'AI subject detection',noteColor:'Solid backdrop removal',noteEdited:'touched up by hand',touchUp:'Erase / restore brush',erase:'Erase',restore:'Restore',brush:'Brush size',undo:'Undo',reset:'Start over',cancel:'Cancel',apply:'Apply',brushHint:'The faint area is the removed original; paint with Restore to bring it back. Zoom in for a finer brush.',stage:{model:'Getting the AI model (first time only)',prepare:'Preparing',find:'Finding the subject',edges:'Refining edges'}};
S.ja.bg={quality:'AIの品質',qualityBest:'高品質 (初回のみ190MBを取得)',qualityFast:'高速 (5MBの軽量モデル)',noteQuick:'クイックプレビュー · まもなく高品質の結果に置き換わります',bestFailed:'高品質モデルを取得できなかったため、クイック結果のままです。',method:'消し方',ai:'自動 (AI)',solid:'単色の背景',newBackground:'新しい背景',none:'透明',white:'白',black:'黒',custom:'色を選ぶ',blur:'元の背景をぼかす',color:'色',refine:'髪や輪郭を元の色に合わせて整える',cleanup:'輪郭に残った背景色を取り除く',key:'消す色',keyAuto:'ふちから自動検出',keyCustom:'自分で選ぶ',tolerance:'近い色の許容範囲',trim:'被写体に合わせて余白を切る',padding:'余白 (px)',format:'保存形式',jpegHint:'JPGは透明を保存できないため、白い背景で埋めます。',done:'背景を削除しました',doneMany:'{n}枚の背景を削除しました',noteAi:'AI被写体認識',noteColor:'単色背景の削除',noteEdited:'手作業で調整',touchUp:'消しゴム・復元ブラシ',erase:'消す',restore:'復元',brush:'ブラシサイズ',undo:'元に戻す',reset:'最初から',cancel:'キャンセル',apply:'適用',brushHint:'薄く見える部分が消された元画像です。復元で塗ると戻ります。拡大すると細いブラシで塗れます。',stage:{model:'AIモデルを取得中 (初回のみ)',prepare:'準備中',find:'被写体を検出中',edges:'輪郭を調整中'}};
S.ko.upscale={size:'얼마나 크게',method:'확대 방식',ai:'AI 선명하게',aiHint:'사진·일러스트',smooth:'부드럽게',smoothHint:'가장 빠름',pixel:'도트 그대로',pixelHint:'픽셀아트',tooLarge:'400만 화소가 넘는 이미지는 AI 대신 부드러운 확대로 처리했습니다.',noModel:'AI 모델을 받지 못해 부드러운 확대로 처리했습니다.',stage:{model:'AI 모델 준비 중 (5MB)',tiles:'선명하게 만드는 중 {a}/{b}',prepare:'확대 중'}};
S.en.upscale={size:'How much bigger',method:'Method',ai:'AI sharpen',aiHint:'photos · art',smooth:'Smooth',smoothHint:'fastest',pixel:'Keep pixels',pixelHint:'pixel art',tooLarge:'Images over 4 megapixels are enlarged with the smooth method instead of AI.',noModel:'The AI model could not be loaded, so the smooth method was used.',stage:{model:'Preparing the AI model (5 MB)',tiles:'Sharpening {a}/{b}',prepare:'Enlarging'}};
S.ja.upscale={size:'どれくらい大きく',method:'拡大方法',ai:'AIでくっきり',aiHint:'写真・イラスト',smooth:'なめらか',smoothHint:'最速',pixel:'ドットのまま',pixelHint:'ドット絵',tooLarge:'400万画素を超える画像はAIではなく、なめらかな拡大で処理しました。',noModel:'AIモデルを取得できなかったため、なめらかな拡大で処理しました。',stage:{model:'AIモデルを準備中 (5MB)',tiles:'くっきり処理中 {a}/{b}',prepare:'拡大中'}};
/** UI Lab (src/task/ui-lab.js, docs/UI-LAB.md). Export setup notes live here too, so the words
 * an engine user reads are translated like every other string on the page. */
S.ko.uiLab={drop:'패널·버튼·UI 시트를 놓으세요',dropHint:'PNG 한 장 · 9슬라이스, 버튼 상태, UI 아틀라스, 비트맵 폰트를 한곳에서',openCheck:'이미지 없이 점검만 하기',stages:'작업 단계',
 stage:{slice:'9슬라이스',states:'버튼 상태',atlas:'UI 아틀라스',font:'폰트',check:'점검'},needImage:'먼저 이미지를 추가하세요',needImageHint:'이 단계는 이미지가 필요합니다. 점검 단계는 이미지 없이도 씁니다.',saved:'ZIP으로 저장했습니다 ({size})',
 editor:'경계선 편집',stretchArea:'늘어나는 영역',guide:{left:'왼쪽',right:'오른쪽',top:'위',bottom:'아래'},guideHint:'점선 손잡이를 끌거나, 숫자 칸에서 화살표 키로 1px씩(Shift 10px) 조절하세요.',
 livePreview:'실제 크기 미리보기',previewNote:'내보내는 그림과 같은 방식으로 그립니다',dragResize:'모서리를 끌어 크기 조절',borders:'경계선 (px)',bordersLine:'원본 {w}×{h} 기준 왼쪽·오른쪽·위·아래',
 suggest:'경계선 자동 추천',suggestTitle:'추천값 (확인 후 적용)',suggestFrom:'{l} · {r} · {t} · {b} — 같은 열 {cols}개, 같은 행 {rows}개가 이어지는 구간에서 찾았습니다.',suggestWeak:'{l} · {r} · {t} · {b} — 반복되는 열·행이 뚜렷하지 않습니다. 직접 확인하세요.',accept:'적용',dismiss:'닫기',
 edgeMode:'가장자리 처리',mode:{stretch:'늘리기',tile:'타일 반복'},customSize:'직접 지정한 크기',integerScale:'정수 배율',zoom:'편집 확대',zoomFit:'맞춤',scaleHint:'정수 배율은 모서리를 그대로 n배로 그립니다. 흐려지지 않습니다.',
 exportSlice:'PNG + JSON + 설정 안내 받기',warn:{narrow:'{w}px는 좌우 경계선 합({need}px)보다 좁습니다. 모서리가 눌립니다.',short:'{h}px는 위아래 경계선 합({need}px)보다 낮습니다. 모서리가 눌립니다.',tileLimit:'타일 {tiles}개가 필요해 늘리기로 그렸습니다. 가운데 영역을 넓히세요.'},
 backToAtlas:'아틀라스로 돌아가기',editingElement:'요소 “{name}”의 경계선을 편집 중입니다.',
 variants:'상태 이미지',variantsNote:'정해진 픽셀 연산 결과입니다',state:{normal:'기본',hover:'호버',pressed:'누름',disabled:'비활성',focus:'포커스'},editingState:'선택한 상태의 설정',
 brightness:'밝기',contrast:'대비',saturation:'채도',opacity:'투명도',overlay:'겹칠 색',overlayAlpha:'겹치는 정도',offsetX:'가로 이동(px)',offsetY:'세로 이동(px)',outlineWidth:'외곽선(px)',outlineColor:'외곽선 색',
 resetState:'이 상태 초기화',stripNote:'묶음 시트는 상태마다 크기가 달라도 MaxRects로 배치하고 JSON에 좌표를 남깁니다.',exportStates:'낱장 5장 + 묶음 시트 + JSON',appliedList:'적용: {list}',appliedNone:'원본 그대로입니다.',
 statesReadme:'states/ 안의 PNG는 낱장, *-states.png는 묶음 시트입니다. states.json의 rect가 묶음 시트 좌표(왼쪽 위 기준)이고, state 항목에 사용한 연산값이 그대로 들어 있습니다. 엔진 리소스 파일은 만들지 않습니다.',
 atlasPreview:'아틀라스',detect:'요소 다시 찾기',elements:'요소',elementCount:'요소 {n}개',elementName:'요소 이름',setBorders:'9슬라이스 설정',noElements:'투명 배경에서 요소를 찾지 못했습니다. 병합 거리나 최소 영역을 조절하세요.',
 mergeDistance:'병합 거리(px)',minArea:'최소 픽셀 수',alphaThreshold:'알파 기준값',atlasHint:'알파가 기준값보다 큰 픽셀을 8방향으로 묶고, 병합 거리 안에 있는 상자를 하나로 합칩니다.',exportAtlas:'아틀라스 PNG + JSON',
 fontSheet:'글자 시트',fontSample:'폰트 자체 메트릭으로 그린 한 줄',fontMode:{grid:'고정 격자',measured:'폭 측정',ttf:'폰트 파일'},fontFile:'TTF·OTF 파일',fontFileHint:'글꼴 파일은 업로드되지 않고 이 브라우저에서만 쓰입니다.',fontLoaded:'{name} 불러왔습니다.',
 fontSize:'글자 크기(px)',glyphSpacing:'글자 간격(px)',baseline:'베이스라인',charset:'문자 집합',chars:'글자 순서',charsetBuilder:'문자 집합 만들기 · 고급',fromText:'내 텍스트',fromTextHint:'게임에 쓰는 문장을 붙여 넣으세요',
 preset:{text:'텍스트에 쓰인 글자',ascii:'ASCII',latin1:'Latin-1',ko:'텍스트의 한글만',ja:'텍스트의 일본어만'},charsetHint:'한글 11,172자 전체는 절대 자동으로 넣지 않습니다. 붙여 넣은 텍스트에 실제로 쓰인 글자만 모읍니다.',
 sdfOption:'SDF(거리장) 텍스처도 만들기 (베타)',sdfSpread:'스프레드(px)',sdfNote:'글자마다 정확한 유클리드 거리 변환을 계산합니다. MSDF는 아닙니다. 엔진에서 검증하지 않았습니다.',
 exportFont:'PNG + FNT + JSON 받기',glyphCount:'글자 {n}개 · {mode}',needChars:'글자 순서를 입력하세요.',needFontFile:'먼저 TTF·OTF 파일을 선택하세요.',
 fontNoteGrid:'모든 글자가 셀 전체를 쓰고 전진폭은 셀 너비와 같습니다.',fontNoteMeasured:'알파에서 각 글자의 실제 폭을 재어 전진폭과 오프셋을 넣었습니다. 커닝은 없습니다.',fontNoteTtf:'글꼴 파일을 캔버스로 그린 뒤 그 픽셀을 다시 측정했습니다. 전진폭은 글꼴이 알려 준 값입니다.',
 fontReadme:'font.png 옆에 font.fnt를 두세요. font.fnt는 BMFont 텍스트 형식이고, font.json은 같은 값을 담은 일반 JSON입니다. 커닝 쌍은 없습니다(비트맵 시트에서 만들 수 없습니다). 엔진 리소스 파일은 만들지 않으며, 엔진에서의 불러오기는 검증하지 않았습니다.',
 sdfReadme:'font-sdf.png는 거리값을 R·G·B에 담고 알파는 255로 둡니다(캔버스는 낮은 알파에서 색 바이트를 보존하지 않습니다). 128이 윤곽선이고 스프레드는 {spread}px입니다. 셰이더: {shader}',
 checks:'점검 항목',check:{glyphs:'빠진 글자',sizes:'해상도·앵커',text:'번역 넘침',contrast:'명암비'},
 glyphSource:'글자 목록 출처',glyphSourceLab:'이 랩의 폰트',glyphSourceFnt:'.fnt 파일',glyphSourceLabHint:'폰트 단계에서 만든 글자 목록과 비교합니다.',loadFnt:'.fnt 파일',fntHint:'BMFont 텍스트(.fnt)를 그대로 읽습니다.',fntLoaded:'{name} · 글자 {n}개',
 localeFile:'번역 파일 (.txt·.json·.csv·.po)',pasteText:'텍스트 붙여넣기',pasteHint:'게임에 나오는 문장을 붙여 넣으세요',exportMissing:'빠진 글자 목록 받기',ttfLimit:'TTF·OTF의 cmap 표는 읽지 않습니다. .fnt 또는 이 랩의 폰트와만 비교합니다.',
 glyphEmpty:'검사할 텍스트가 없습니다.',glyphNoFont:'비교할 글자 목록이 없습니다. 폰트 단계에서 글자를 만들거나 .fnt를 불러오세요.',missingCount:'빠진 글자 {n}개 · 검사한 글자 {used}종',missingNone:'빠진 글자가 없습니다. 검사한 글자 {used}종 모두 폰트에 있습니다.',
 character:'글자',count:'횟수',lines:'줄',glyphSummaryLine:'폰트 {have}자 · 텍스트 {used}종',
 screen:'해상도',aspect:'화면비',anchor:'앵커',anchorNote:'Godot의 anchor_left/top/right/bottom과 Unity RectTransform 프리셋의 계산을 그대로 흉내 낸 개념 시뮬레이션입니다. 엔진이 계산한 레이아웃이 아닙니다.',anchorLine:'화면 좌표 {x}, {y}',
 safeArea:'세이프 영역',safeNone:'표시하지 않음',safeCustom:'직접 입력',safe:{'title-safe':'타이틀 세이프 90%','action-safe':'액션 세이프 93%','action-safe-95':'액션 세이프 95%'},safeLine:'세이프 영역 {x}, {y} · {w}×{h}',insetX:'좌우 여백(px)',insetY:'위아래 여백(px)',
 scaleCompare:'배율 비교',scaleNote:'정수 배율은 픽셀이 딱 맞고, 1.25·1.5·1.75배는 맞지 않습니다',crisp:'선명',blurry:'흐림',
 boxW:'상자 너비(px)',boxH:'상자 높이(px)',wrapMode:'넘칠 때',wrap:{single:'한 줄 고정',wrap:'줄바꿈 허용',truncate:'잘라내기'},string:{ko:'한국어',en:'English',ja:'日本語'},
 sampleString:{ko:'게임 계속하기',en:'Continue playing',ja:'ゲームを続ける'},status:{fits:'들어갑니다',wrapped:'줄바꿈',clipped:'높이 초과',overflow:'넘침',truncated:'잘림'},linesShort:'줄',
 overflowN:'{n}개 넘침',overflowNone:'모두 들어갑니다',overflowLine:'상자 {w}×{h} · 글자 {size}px',overflowNote:'브라우저 글꼴로 측정한 값입니다. 게임 글꼴의 폭은 다를 수 있으니 폰트 단계의 글꼴로도 확인하세요.',
 foreground:'글자색',background:'배경색',boldText:'굵은 글씨',contrastSample:'버튼 글자 예시',contrastNeeded:'AA {aa}:1 · AAA {aaa}:1 기준 · 큰 글씨 {large}',largeYes:'해당',largeNo:'아님',uiComponent:'UI 요소 3:1',
 contrastNote:'WCAG 공식으로 계산한 참고값입니다. 무늬나 그라데이션 위의 글자는 픽셀마다 값이 달라집니다.',contrastLine:'{fg} / {bg}',
 setup:{title:'# 9슬라이스 설정 안내',numbers:'경계선(px): 왼쪽 {l} · 오른쪽 {r} · 위 {t} · 아래 {b}',
  godot1:'1. PNG를 프로젝트에 넣고 NinePatchRect의 texture로 지정합니다.',godot2:'2. patch_margin_left / right / top / bottom = {l} / {r} / {t} / {b}',
  godot3:'3. 버튼·패널 테마에는 StyleBoxTexture를 쓰고 texture_margin_left / right / top / bottom에 같은 값을 넣습니다. 타일 모드로 내보냈다면 axis_stretch_horizontal·vertical을 Tile로 바꿉니다.',
  unity1:'1. PNG를 가져와 Sprite Mode = Single, Mesh Type = Full Rect로 두고 Sprite Editor를 엽니다.',unity2:'2. Border 칸은 L, B, R, T 순서이고 원점이 왼쪽 아래입니다: {border}',
  unity3:'3. Image 컴포넌트의 Image Type을 Sliced(타일 모드는 Tiled)로 설정합니다.',normalized:'정규화 값 (0–1)',
  unverified:'이 안내는 이번 릴리스에서 Godot·Unity 안에서 직접 실행해 확인하지 않았습니다(UNVERIFIED). .tres·.meta 같은 엔진 리소스 파일은 만들지 않습니다.'}};
S.en.uiLab={drop:'Drop a panel, button or UI sheet',dropHint:'One PNG · nine-slice, button states, a UI atlas and bitmap fonts in one place',openCheck:'Just run the checks',stages:'Stages',
 stage:{slice:'9-Slice',states:'States',atlas:'Atlas',font:'Font',check:'Check'},needImage:'Add an image first',needImageHint:'This stage needs an image. The Check stage works without one.',saved:'Saved as ZIP ({size})',
 editor:'Border editor',stretchArea:'stretch area',guide:{left:'Left',right:'Right',top:'Top',bottom:'Bottom'},guideHint:'Drag a handle, or focus a number box and nudge with the arrow keys (Shift = 10px).',
 livePreview:'Live preview at real sizes',previewNote:'drawn by the same plan the export uses',dragResize:'drag the corner to resize',borders:'Borders (px)',bordersLine:'left · right · top · bottom on a {w}×{h} source',
 suggest:'Suggest borders',suggestTitle:'Suggestion — accept to apply',suggestFrom:'{l} · {r} · {t} · {b} — found from a run of {cols} identical columns and {rows} identical rows.',suggestWeak:'{l} · {r} · {t} · {b} — no clear repeating column or row. Check it by eye.',accept:'Accept',dismiss:'Dismiss',
 edgeMode:'Edges',mode:{stretch:'Stretch',tile:'Tile'},customSize:'Custom size',integerScale:'Integer scale',zoom:'Editor zoom',zoomFit:'Fit',scaleHint:'An integer scale draws the corners at exactly n× their pixels, so nothing is resampled.',
 exportSlice:'Download PNG + JSON + setup notes',warn:{narrow:'{w}px is narrower than left+right ({need}px): the corners are squashed.',short:'{h}px is shorter than top+bottom ({need}px): the corners are squashed.',tileLimit:'Tiling would need {tiles} tiles, so this is drawn stretched. Use a wider middle.'},
 backToAtlas:'Back to the atlas',editingElement:'Editing the borders of “{name}”.',
 variants:'State images',variantsNote:'the result of fixed pixel operations',state:{normal:'Normal',hover:'Hover',pressed:'Pressed',disabled:'Disabled',focus:'Focus'},editingState:'settings for the selected state',
 brightness:'Brightness',contrast:'Contrast',saturation:'Saturation',opacity:'Opacity',overlay:'Overlay colour',overlayAlpha:'Overlay amount',offsetX:'Offset X (px)',offsetY:'Offset Y (px)',outlineWidth:'Outline (px)',outlineColor:'Outline colour',
 resetState:'Reset this state',stripNote:'The strip packs the variants with MaxRects even when they differ in size, and the JSON carries every rect.',exportStates:'5 PNGs + strip + JSON',appliedList:'Applied: {list}',appliedNone:'Unchanged from the original.',
 statesReadme:'states/ holds one PNG per state and *-states.png is the packed strip. Every rect in states.json is a strip coordinate with a top-left origin, and each state carries the exact operation values used. No engine resource file is written.',
 atlasPreview:'Atlas',detect:'Detect again',elements:'Elements',elementCount:'{n} element(s)',elementName:'Element name',setBorders:'Set 9-slice',noElements:'No elements found on the transparent sheet. Adjust the merge distance or the minimum size.',
 mergeDistance:'Merge distance (px)',minArea:'Minimum pixels',alphaThreshold:'Alpha threshold',atlasHint:'Pixels above the alpha threshold are grouped 8-connected, then boxes within the merge distance become one element.',exportAtlas:'Atlas PNG + JSON',
 fontSheet:'Glyph sheet',fontSample:'One line drawn with the font’s own metrics',fontMode:{grid:'Fixed grid',measured:'Measured widths',ttf:'Font file'},fontFile:'TTF / OTF file',fontFileHint:'The font file is never uploaded; it is used in this browser only.',fontLoaded:'{name} loaded.',
 fontSize:'Font size (px)',glyphSpacing:'Glyph spacing (px)',baseline:'Baseline',charset:'Character set',chars:'Character order',charsetBuilder:'Character-set builder · advanced',fromText:'My text',fromTextHint:'Paste the strings your game shows',
 preset:{text:'Characters used in my text',ascii:'ASCII',latin1:'Latin-1',ko:'Korean characters in my text',ja:'Japanese characters in my text'},charsetHint:'All 11,172 Hangul syllables are never added for you: a preset collects only the characters your pasted text really uses.',
 sdfOption:'Also build an SDF texture (Beta)',sdfSpread:'Spread (px)',sdfNote:'An exact Euclidean distance transform per glyph. This is not MSDF, and it was not validated inside an engine.',
 exportFont:'Download PNG + FNT + JSON',glyphCount:'{n} glyph(s) · {mode}',needChars:'Enter the character order.',needFontFile:'Choose a TTF or OTF file first.',
 fontNoteGrid:'Every glyph is its whole cell and every advance is the cell width.',fontNoteMeasured:'Each glyph’s real width was measured from the alpha, giving its advance and offsets. There is no kerning.',fontNoteTtf:'The font file was drawn with canvas text and those pixels were measured again. Advances are the ones the font reported.',
 fontReadme:'Keep font.fnt next to font.png. font.fnt is the BMFont text format; font.json carries the same numbers as plain JSON. There are no kerning pairs (a bitmap sheet cannot provide them). No engine resource file is written, and importing into an engine was not verified.',
 sdfReadme:'font-sdf.png stores the distance in R, G and B with alpha left at 255 (a canvas does not preserve colour bytes under a low alpha). 128 is the contour and the spread is {spread}px. Shader: {shader}',
 checks:'Checks',check:{glyphs:'Missing glyphs',sizes:'Sizes & anchors',text:'Localisation',contrast:'Contrast'},
 glyphSource:'Glyph list from',glyphSourceLab:'This Lab’s font',glyphSourceFnt:'.fnt file',glyphSourceLabHint:'Compared against the characters built in the Font stage.',loadFnt:'.fnt file',fntHint:'A BMFont text file (.fnt) is read as it is.',fntLoaded:'{name} · {n} glyphs',
 localeFile:'Localisation file (.txt, .json, .csv, .po)',pasteText:'Paste text',pasteHint:'Paste the strings your game shows',exportMissing:'Download the missing list',ttfLimit:'The cmap table of a TTF or OTF is not read. Comparison is against a .fnt or this Lab’s font.',
 glyphEmpty:'No text to check yet.',glyphNoFont:'No glyph list to compare against. Build characters in the Font stage or load a .fnt.',missingCount:'{n} missing · {used} distinct characters checked',missingNone:'Nothing missing: all {used} distinct characters have a glyph.',
 character:'Character',count:'Count',lines:'Lines',glyphSummaryLine:'{have} glyphs in the font · {used} in the text',
 screen:'Resolution',aspect:'Aspect',anchor:'Anchor',anchorNote:'A conceptual simulation of the same arithmetic as Godot’s anchor_left/top/right/bottom and Unity’s RectTransform presets. No engine ran a layout pass.',anchorLine:'at {x}, {y} on screen',
 safeArea:'Safe area',safeNone:'Off',safeCustom:'Custom insets',safe:{'title-safe':'Title-safe 90%','action-safe':'Action-safe 93%','action-safe-95':'Action-safe 95%'},safeLine:'safe area {x}, {y} · {w}×{h}',insetX:'Inset left/right (px)',insetY:'Inset top/bottom (px)',
 scaleCompare:'Scale comparison',scaleNote:'integer scales land on whole pixels; 1.25/1.5/1.75 do not',crisp:'crisp',blurry:'soft',
 boxW:'Box width (px)',boxH:'Box height (px)',wrapMode:'When it does not fit',wrap:{single:'One line only',wrap:'Allow wrapping',truncate:'Truncate'},string:{ko:'한국어',en:'English',ja:'日本語'},
 sampleString:{ko:'게임 계속하기',en:'Continue playing',ja:'ゲームを続ける'},status:{fits:'fits',wrapped:'wraps',clipped:'too tall',overflow:'overflows',truncated:'truncated'},linesShort:' line(s)',
 overflowN:'{n} overflow',overflowNone:'All fit',overflowLine:'box {w}×{h} · text {size}px',overflowNote:'Measured with a browser font. Your game font has different widths, so check it with the font from the Font stage too.',
 foreground:'Text colour',background:'Background',boldText:'Bold text',contrastSample:'Button label sample',contrastNeeded:'AA needs {aa}:1, AAA {aaa}:1 · large text: {large}',largeYes:'yes',largeNo:'no',uiComponent:'UI 3:1',
 contrastNote:'The WCAG formula, as a reference number. Text over artwork or a gradient has a different ratio at every pixel.',contrastLine:'{fg} on {bg}',
 setup:{title:'# Nine-slice setup notes',numbers:'Borders in pixels: left {l} · right {r} · top {t} · bottom {b}',
  godot1:'1. Add the PNG to your project and set it as the texture of a NinePatchRect.',godot2:'2. patch_margin_left / right / top / bottom = {l} / {r} / {t} / {b}',
  godot3:'3. For a Button or Panel theme, use a StyleBoxTexture and put the same numbers in texture_margin_left / right / top / bottom. If you exported tile mode, set axis_stretch_horizontal and axis_stretch_vertical to Tile.',
  unity1:'1. Import the PNG, keep Sprite Mode = Single and Mesh Type = Full Rect, then open the Sprite Editor.',unity2:'2. The Border fields are in the order L, B, R, T with a bottom-left origin: {border}',
  unity3:'3. On an Image component set Image Type = Sliced (Tiled for tile mode).',normalized:'Normalised values (0–1)',
  unverified:'These steps were not run inside Godot or Unity for this release: treat them as UNVERIFIED setup notes. No .tres, .meta or other engine resource file is written.'}};
S.ja.uiLab={drop:'パネル・ボタン・UIシートをドロップ',dropHint:'PNG1枚 · 9スライス、ボタン状態、UIアトラス、ビットマップフォントを一か所で',openCheck:'画像なしでチェックだけ',stages:'ステージ',
 stage:{slice:'9スライス',states:'ボタン状態',atlas:'UIアトラス',font:'フォント',check:'チェック'},needImage:'まず画像を追加してください',needImageHint:'このステージには画像が必要です。チェックは画像なしでも使えます。',saved:'ZIPで保存しました（{size}）',
 editor:'境界線の編集',stretchArea:'伸びる領域',guide:{left:'左',right:'右',top:'上',bottom:'下'},guideHint:'ハンドルをドラッグ、または数値欄で矢印キーを使って1pxずつ（Shiftで10px）調整します。',
 livePreview:'実サイズのプレビュー',previewNote:'書き出しと同じ描画プランで描いています',dragResize:'角をドラッグしてサイズ変更',borders:'境界線 (px)',bordersLine:'元画像 {w}×{h} の左・右・上・下',
 suggest:'境界線を提案',suggestTitle:'提案（確認して適用）',suggestFrom:'{l} · {r} · {t} · {b} — 同一の列{cols}個・行{rows}個が続く区間から求めました。',suggestWeak:'{l} · {r} · {t} · {b} — 繰り返す列・行が明確ではありません。目で確認してください。',accept:'適用',dismiss:'閉じる',
 edgeMode:'辺の処理',mode:{stretch:'伸縮',tile:'タイル'},customSize:'任意のサイズ',integerScale:'整数倍',zoom:'編集倍率',zoomFit:'フィット',scaleHint:'整数倍では角をちょうどn倍で描くため、再サンプリングされません。',
 exportSlice:'PNG + JSON + 設定メモを取得',warn:{narrow:'{w}pxは左右の境界線の合計（{need}px）より狭いため、角が潰れます。',short:'{h}pxは上下の境界線の合計（{need}px）より低いため、角が潰れます。',tileLimit:'タイルが{tiles}枚必要になるため伸縮で描きました。中央領域を広げてください。'},
 backToAtlas:'アトラスに戻る',editingElement:'要素「{name}」の境界線を編集中です。',
 variants:'状態画像',variantsNote:'決まった画素処理の結果です',state:{normal:'通常',hover:'ホバー',pressed:'押下',disabled:'無効',focus:'フォーカス'},editingState:'選択中の状態の設定',
 brightness:'明度',contrast:'コントラスト',saturation:'彩度',opacity:'不透明度',overlay:'重ねる色',overlayAlpha:'重ねる強さ',offsetX:'横のずれ(px)',offsetY:'縦のずれ(px)',outlineWidth:'アウトライン(px)',outlineColor:'アウトラインの色',
 resetState:'この状態を初期化',stripNote:'まとめたシートはサイズが違ってもMaxRectsで配置し、JSONに座標を残します。',exportStates:'個別5枚 + まとめシート + JSON',appliedList:'適用: {list}',appliedNone:'元のままです。',
 statesReadme:'states/ には状態ごとのPNG、*-states.pngはまとめたシートです。states.jsonのrectはシート座標（左上原点）で、各stateに使った処理値がそのまま入っています。エンジンのリソースファイルは作りません。',
 atlasPreview:'アトラス',detect:'要素を再検出',elements:'要素',elementCount:'要素{n}個',elementName:'要素名',setBorders:'9スライスを設定',noElements:'透明シート上に要素が見つかりません。結合距離か最小サイズを調整してください。',
 mergeDistance:'結合距離(px)',minArea:'最小ピクセル数',alphaThreshold:'アルファのしきい値',atlasHint:'しきい値を超えるピクセルを8近傍で連結し、結合距離以内の矩形を1つの要素にまとめます。',exportAtlas:'アトラスPNG + JSON',
 fontSheet:'グリフシート',fontSample:'フォント自身のメトリクスで描いた1行',fontMode:{grid:'固定グリッド',measured:'幅を測定',ttf:'フォントファイル'},fontFile:'TTF・OTFファイル',fontFileHint:'フォントファイルはアップロードされず、このブラウザ内だけで使われます。',fontLoaded:'{name} を読み込みました。',
 fontSize:'文字サイズ(px)',glyphSpacing:'文字間隔(px)',baseline:'ベースライン',charset:'文字セット',chars:'文字の並び',charsetBuilder:'文字セット作成 · 詳細',fromText:'自分のテキスト',fromTextHint:'ゲームに出る文章を貼り付けてください',
 preset:{text:'テキストで使う文字',ascii:'ASCII',latin1:'Latin-1',ko:'テキスト中の韓国語',ja:'テキスト中の日本語'},charsetHint:'ハングル11,172字すべてを自動で入れることはありません。貼り付けたテキストで実際に使われている文字だけを集めます。',
 sdfOption:'SDF（距離場）テクスチャも作成（ベータ）',sdfSpread:'スプレッド(px)',sdfNote:'グリフごとに厳密なユークリッド距離変換を計算します。MSDFではなく、エンジン内での検証もしていません。',
 exportFont:'PNG + FNT + JSONを取得',glyphCount:'{n}文字 · {mode}',needChars:'文字の並びを入力してください。',needFontFile:'先にTTF・OTFファイルを選んでください。',
 fontNoteGrid:'すべての文字がセル全体を使い、送り幅はセル幅と同じです。',fontNoteMeasured:'各文字の実際の幅をアルファから測り、送り幅とオフセットにしました。カーニングはありません。',fontNoteTtf:'フォントファイルをCanvasで描画し、そのピクセルを測り直しました。送り幅はフォントが返した値です。',
 fontReadme:'font.pngの隣にfont.fntを置いてください。font.fntはBMFontテキスト形式、font.jsonは同じ値をそのまま持つJSONです。カーニングペアはありません（ビットマップシートからは作れません）。エンジンのリソースファイルは作らず、エンジンへの読み込みも検証していません。',
 sdfReadme:'font-sdf.pngは距離をR・G・Bに格納し、アルファは255のままです（Canvasは低いアルファで色バイトを保持しません）。128が輪郭、スプレッドは{spread}pxです。シェーダー: {shader}',
 checks:'チェック項目',check:{glyphs:'欠け文字',sizes:'解像度・アンカー',text:'翻訳のはみ出し',contrast:'コントラスト'},
 glyphSource:'文字一覧の取得元',glyphSourceLab:'このラボのフォント',glyphSourceFnt:'.fntファイル',glyphSourceLabHint:'フォントステージで作った文字と比較します。',loadFnt:'.fntファイル',fntHint:'BMFontテキスト(.fnt)をそのまま読みます。',fntLoaded:'{name} · {n}文字',
 localeFile:'翻訳ファイル (.txt・.json・.csv・.po)',pasteText:'テキストを貼り付け',pasteHint:'ゲームに出る文章を貼り付けてください',exportMissing:'欠け文字リストを取得',ttfLimit:'TTF・OTFのcmapテーブルは読みません。.fntまたはこのラボのフォントとだけ比較します。',
 glyphEmpty:'チェックするテキストがありません。',glyphNoFont:'比較する文字一覧がありません。フォントステージで文字を作るか、.fntを読み込んでください。',missingCount:'欠け{n}文字 · 検査した文字{used}種',missingNone:'欠けはありません。検査した{used}種すべてにグリフがあります。',
 character:'文字',count:'回数',lines:'行',glyphSummaryLine:'フォント{have}文字 · テキスト{used}種',
 screen:'解像度',aspect:'アスペクト',anchor:'アンカー',anchorNote:'Godotのanchor_left/top/right/bottomやUnityのRectTransformプリセットと同じ計算を再現した概念シミュレーションです。エンジンのレイアウト計算ではありません。',anchorLine:'画面座標 {x}, {y}',
 safeArea:'セーフエリア',safeNone:'表示しない',safeCustom:'任意の余白',safe:{'title-safe':'タイトルセーフ90%','action-safe':'アクションセーフ93%','action-safe-95':'アクションセーフ95%'},safeLine:'セーフエリア {x}, {y} · {w}×{h}',insetX:'左右の余白(px)',insetY:'上下の余白(px)',
 scaleCompare:'倍率の比較',scaleNote:'整数倍はピクセルが揃い、1.25・1.5・1.75倍は揃いません',crisp:'くっきり',blurry:'ぼやけ',
 boxW:'ボックス幅(px)',boxH:'ボックス高(px)',wrapMode:'収まらないとき',wrap:{single:'1行のみ',wrap:'折り返す',truncate:'切り詰める'},string:{ko:'한국어',en:'English',ja:'日本語'},
 sampleString:{ko:'게임 계속하기',en:'Continue playing',ja:'ゲームを続ける'},status:{fits:'収まる',wrapped:'折り返し',clipped:'高さ超過',overflow:'はみ出し',truncated:'切り詰め'},linesShort:'行',
 overflowN:'{n}件はみ出し',overflowNone:'すべて収まります',overflowLine:'ボックス {w}×{h} · 文字 {size}px',overflowNote:'ブラウザのフォントで測った値です。ゲームのフォントでは幅が異なるため、フォントステージのフォントでも確認してください。',
 foreground:'文字色',background:'背景色',boldText:'太字',contrastSample:'ボタン文字の例',contrastNeeded:'AAは{aa}:1、AAAは{aaa}:1が必要 · 大きい文字: {large}',largeYes:'該当',largeNo:'非該当',uiComponent:'UI要素 3:1',
 contrastNote:'WCAGの式で計算した参考値です。模様やグラデーションの上の文字は、ピクセルごとに比率が変わります。',contrastLine:'{fg} / {bg}',
 setup:{title:'# 9スライス設定メモ',numbers:'境界線(px): 左 {l} · 右 {r} · 上 {t} · 下 {b}',
  godot1:'1. PNGをプロジェクトに追加し、NinePatchRectのtextureに設定します。',godot2:'2. patch_margin_left / right / top / bottom = {l} / {r} / {t} / {b}',
  godot3:'3. ButtonやPanelのテーマではStyleBoxTextureを使い、texture_margin_left / right / top / bottomに同じ値を入れます。タイルモードで書き出した場合はaxis_stretch_horizontal・verticalをTileにします。',
  unity1:'1. PNGをインポートし、Sprite Mode = Single、Mesh Type = Full RectのままSprite Editorを開きます。',unity2:'2. Border欄はL, B, R, Tの順で、原点は左下です: {border}',
  unity3:'3. ImageコンポーネントのImage TypeをSliced（タイルモードならTiled）にします。',normalized:'正規化した値 (0–1)',
  unverified:'この手順は今回のリリースでGodotやUnity内で実行して確認していません（UNVERIFIED）。.tresや.metaなどのエンジンリソースファイルは作りません。'}};
export function ui(locale,key,vars={}){
 let v=key.split('.').reduce((o,k)=>o?.[k],S[locale]||S.en)??key.split('.').reduce((o,k)=>o?.[k],S.en)??key;
 return String(v).replace(/\{(\w+)\}/g,(_,k)=>vars[k]??'');
}
export const UI_LOCALES=Object.keys(S);
export const UI_STRINGS=S;
