import {zip} from '../core.js';
import {EFFECTS} from '../webtoon/effects.js';
import {download,toast,locale,onLocale,track} from './shell.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const L={
 en:{split:'Split',join:'Join',speed:'Speed lines',balloon:'Speech balloon',tone:'Screentone',width:'Width (px)',height:'Height (px)',count:'Ray count',inner:'Open centre (0–0.75)',cx:'Focus X (0–1)',cy:'Focus Y (0–1)',seed:'Seed',shape:'Shape',speech:'Speech',thought:'Thought',shout:'Shout',caption:'Caption',text:'Text (kept only in this tab)',fontSize:'Letter size',ppi:'Output pixels per inch (PPI)',lpi:'Tone lines per inch (LPI)',density:'Ink coverage (0–0.85)',angle:'Angle',dot:'Dots',line:'Lines',hint:'Original transparent overlays. Save SVG and a checked PNG, then place them over your own artwork in an editor. System font rendering can differ.',export:'Export SVG + PNG',working:'Rendering and reopening PNG locally…',verified:'The PNG is decoded again before download. SVG is generated from fixed shapes and escaped text; no external content is embedded.'},
 ko:{split:'분할',join:'합치기',speed:'집중선',balloon:'말풍선',tone:'스크린톤',width:'너비(px)',height:'높이(px)',count:'선 개수',inner:'비운 중심(0–0.75)',cx:'초점 X(0–1)',cy:'초점 Y(0–1)',seed:'시드',shape:'모양',speech:'말풍선',thought:'생각',shout:'외침',caption:'설명 상자',text:'대사(이 탭에만 보관)',fontSize:'글자 크기',ppi:'출력 해상도(PPI)',lpi:'스크린톤 선 수(LPI)',density:'잉크 면적(0–0.85)',angle:'각도',dot:'점',line:'선',hint:'독자적으로 만든 투명 오버레이입니다. SVG와 검사한 PNG를 저장해 그림 편집기에서 자신의 원고에 얹으세요. 시스템 글꼴은 달라질 수 있습니다.',export:'SVG + PNG 내보내기',working:'로컬에서 그린 뒤 PNG 재열기 중…',verified:'PNG를 내려받기 전에 다시 엽니다. SVG는 고정된 도형과 이스케이프한 글자로 만들며 외부 콘텐츠를 포함하지 않습니다.'},
 ja:{split:'分割',join:'結合',speed:'集中線',balloon:'吹き出し',tone:'スクリーントーン',width:'幅(px)',height:'高さ(px)',count:'線の数',inner:'中心の空き(0–0.75)',cx:'焦点X(0–1)',cy:'焦点Y(0–1)',seed:'シード',shape:'形',speech:'会話',thought:'思考',shout:'叫び',caption:'説明枠',text:'せりふ（このタブだけ）',fontSize:'文字サイズ',ppi:'出力解像度(PPI)',lpi:'線数(LPI)',density:'インク面積(0–0.85)',angle:'角度',dot:'点',line:'線',hint:'独自に作成した透明オーバーレイです。SVGと検証済みPNGを保存し、自分の原稿に重ねてください。システムフォントの表示は環境で異なります。',export:'SVG + PNGを書き出す',working:'端末内で描画しPNGを再読み込み中…',verified:'保存前にPNGを再読み込みします。SVGは固定の図形とエスケープ済み文字のみで作り、外部コンテンツは含みません。'}
};
const t=k=>L[locale()]?.[k]||L.en[k]||k;
export function mountEffects({el}){
 const q=new URL(location.href).searchParams,kind=['speed','balloon','tone'].includes(q.get('mode'))?q.get('mode'):'speed';
 const n=(key,fallback,min,max)=>{const v=Number(q.get(key));return q.has(key)&&Number.isFinite(v)?Math.min(max,Math.max(min,v)):fallback;};
 const shapes=kind==='tone'?['dot','line']:['speech','thought','shout','caption'];
 let o={kind,width:n('ew',800,64,4096),height:n('eh',600,64,4096),count:n('count',90,8,400),inner:n('inner',.18,0,.75),cx:n('cx',.5,0,1),cy:n('cy',.5,0,1),seed:n('seed',1,1,4294967295),shape:shapes.includes(q.get('shape'))?q.get('shape'):shapes[0],text:'',fontSize:n('fontSize',32,12,90),ppi:n('ppi',300,72,1200),lpi:n('lpi',60,10,150),density:n('density',.25,0,.85),angle:n('angle',45,-180,180)};
 let imageURL='',busy=false,nextId=0,pending=new Map();
 const worker=new Worker(new URL('../webtoon/worker.js',import.meta.url),{type:'module'});
 worker.onmessage=e=>{const {id,type,error}=e.data||{},p=pending.get(id);if(!p)return;if(type==='progress')return;pending.delete(id);type==='error'?p.reject(new Error(error)):p.resolve(e.data);};
 const field=(key,min,max,step=1)=>`<label>${t(key)}<input data-effect="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${o[key]}"></label>`;
 function saveURL(){const u=new URL(location.href);for(const key of ['ew','eh','count','inner','cx','cy','seed','shape','fontSize','ppi','lpi','density','angle'])u.searchParams.delete(key);u.searchParams.set('ew',o.width);u.searchParams.set('eh',o.height);for(const key of kind==='speed'?['count','inner','cx','cy','seed']:kind==='balloon'?['shape','fontSize']:['shape','ppi','lpi','density','angle'])u.searchParams.set(key,String(o[key]));history.replaceState({},'',u);}
 function render(){
  if(imageURL)URL.revokeObjectURL(imageURL);let error='';try{imageURL=URL.createObjectURL(new Blob([EFFECTS[kind](o)],{type:'image/svg+xml'}));}catch(e){imageURL='';error=e.message;}
  const tabs=`<nav class="webtoon-tabs" aria-label="Toolkit stages"><a href="?mode=split">${t('split')}</a><a href="?mode=join">${t('join')}</a>${['speed','balloon','tone'].map(k=>`<a href="?mode=${k}" aria-current="${kind===k?'page':'false'}">${t(k)}</a>`).join('')}</nav>`;
  const extra=kind==='speed'?`${field('count',8,400)}${field('inner',0,.75,.01)}${field('cx',0,1,.01)}${field('cy',0,1,.01)}${field('seed',1,4294967295)}`:kind==='balloon'?`<label>${t('shape')}<select data-effect="shape">${['speech','thought','shout','caption'].map(k=>`<option value="${k}" ${o.shape===k?'selected':''}>${t(k)}</option>`).join('')}</select></label><label>${t('text')}<textarea id="webtoonText" rows="3" maxlength="500">${esc(o.text)}</textarea></label>${field('fontSize',12,90)}`:`<label>${t('shape')}<select data-effect="shape">${['dot','line'].map(k=>`<option value="${k}" ${o.shape===k?'selected':''}>${t(k)}</option>`).join('')}</select></label>${field('ppi',72,1200)}${field('lpi',10,150)}${field('density',0,.85,.01)}${field('angle',-180,180)}`;
  el.innerHTML=`<div class="webtoon-work"><section class="webtoon-main">${tabs}<h2>${t(kind)}</h2><p class="webtoon-muted">${t('hint')}</p>${imageURL?`<div class="webtoon-effect-preview"><img src="${imageURL}" alt="${t(kind)}"></div>`:`<p role="alert">${esc(error)}</p>`}</section><aside class="webtoon-side">${field('width',64,4096)}${field('height',64,4096)}${extra}<p id="webtoonStatus" role="status" aria-live="polite">${busy?t('working'):''}</p><button class="primary" id="webtoonEffectRun" ${busy||error?'disabled':''}>${t('export')}</button><p class="webtoon-muted">${t('verified')}</p></aside></div>`;
 }
 async function run(){if(busy)return;busy=true;render();const id=++nextId;try{const result=await new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});worker.postMessage({id,action:'effect',options:o});});const [png,svg]=result.parts;
  const entries=[{name:`${kind}.png`,blob:png.blob},{name:`${kind}.svg`,blob:svg.blob},{name:'effect-report.json',blob:new Blob([JSON.stringify({tool:'Nerulio Webtoon/Manga Toolkit',effect:kind,width:png.width,height:png.height,pngBytes:png.bytes,svgBytes:svg.bytes,checkedAt:result.report.checked,scope:result.report.scope},null,2)],{type:'application/json'})}];
  download(await zip(entries),`webtoon-${kind}.zip`);track('webtoon_effect_export',{kind});
 }catch(e){toast(e.message,{error:true});}finally{busy=false;render();}}
 el.addEventListener('input',e=>{if(e.target.id==='webtoonText')o.text=e.target.value;});
 el.addEventListener('change',e=>{const x=e.target,k=x.dataset.effect;if(x.id==='webtoonText')o.text=x.value;else if(k){o[k]=x.tagName==='SELECT'?x.value:Number(x.value);saveURL();}render();});
 el.addEventListener('click',e=>{if(e.target.id==='webtoonEffectRun')run();});
 onLocale(render);render();return {add(){toast(t('hint'));}};
}
