import {zip} from '../core.js';
import {profile,PROFILES} from '../webtoon/specs.js';
import {suggestedCuts,validateCuts} from '../webtoon/geometry.js';
import {mountEffects} from './webtoon-effects.js';
import {text,toast,download,onLocale,locale,track} from './shell.js';
export const accept='image/png,image/jpeg,image/webp';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy={
 en:{split:'Split episode',join:'Join in order',files:'Source images',profile:'Export profile',height:'Target cut height (px)',heightHint:'A convenient cut target, not a Naver height rule.',format:'Output format',matte:'JPG background',cuts:'Cut after source row',addCut:'Add cut',undo:'Undo cut',remove:'Remove',up:'Move up',down:'Move down',preview:'Source preview',previewHint:'Lines are cut candidates. Review dialogue and panels before export; blank rows are not a narrative safety guarantee.',export:'Export checked ZIP',joinExport:'Join as PNG',cancel:'Cancel',scope:'Evidence scope',status:'Ready',checking:'Checking dimensions locally…',working:'Processing locally…',done:'Reopened {n} outputs · {mb} MB total',none:'Add local PNG, JPG or WebP artwork. Your files stay on this device.',limit:'Large images are refused before decode at 64 megapixels, 32,767 px on a side or 80 MB per input.',bytes:'WEBTOON 2 MB/file and 20 MB/episode are conservative export targets from French Creator Academy and a 2025 contest FAQ; verify the current dashboard.',verified:'Every output was decoded again in the worker; ZIP is built locally. Publisher acceptance is not verified.',order:'Order',dated:'Sources checked 2026-09-29',custom:'Custom: no publisher compatibility claim.'},
 ko:{split:'원고 분할',join:'순서대로 합치기',files:'원본 이미지',profile:'출력 프로필',height:'목표 절단 높이(px)',heightHint:'편의를 위한 높이입니다. 네이버의 공식 높이 제한이 아닙니다.',format:'출력 형식',matte:'JPG 배경색',cuts:'원본 행 다음에서 자르기',addCut:'절단선 추가',undo:'절단선 되돌리기',remove:'삭제',up:'위로',down:'아래로',preview:'원본 미리보기',previewHint:'선은 자를 위치입니다. 대사와 컷을 직접 확인하세요. 빈 행만으로 서사상 안전을 보장할 수 없습니다.',export:'검사한 ZIP 내보내기',joinExport:'PNG로 합치기',cancel:'취소',scope:'근거 범위',status:'준비',checking:'이 기기에서 크기 검사 중…',working:'이 기기에서 처리 중…',done:'출력 {n}개 재열기 완료 · 총 {mb} MB',none:'로컬 PNG/JPG/WebP 원고를 추가하세요. 파일은 이 기기를 떠나지 않습니다.',limit:'입력 파일당 64메가픽셀·한 변 32,767px·80MB 초과 이미지는 디코딩 전에 거부합니다.',bytes:'WEBTOON 2MB/파일·20MB/회차는 프랑스 Creator Academy 및 2025 대회 FAQ에 근거한 보수적 출력 목표입니다. 현재 업로드 화면을 확인하세요.',verified:'모든 출력을 워커에서 다시 열었습니다. ZIP은 로컬에서 만듭니다. 플랫폼 수락 여부는 미검증입니다.',order:'순서',dated:'출처 확인 2026-09-29',custom:'사용자 지정: 플랫폼 호환성을 주장하지 않습니다.'},
 ja:{split:'原稿を分割',join:'順番に結合',files:'元画像',profile:'出力プロファイル',height:'分割の目標高さ(px)',heightHint:'便宜上の目標です。Naverの公式高さ制限ではありません。',format:'出力形式',matte:'JPGの背景色',cuts:'元画像の行の後で切る',addCut:'分割線を追加',undo:'分割線を戻す',remove:'削除',up:'上へ',down:'下へ',preview:'元画像のプレビュー',previewHint:'線は候補です。せりふとコマを自分で確認してください。空白行だけで内容上の安全は保証できません。',export:'検証したZIPを書き出す',joinExport:'PNGとして結合',cancel:'キャンセル',scope:'根拠の範囲',status:'準備完了',checking:'端末内で寸法を確認中…',working:'端末内で処理中…',done:'{n}点を再読み込み · 合計{mb} MB',none:'ローカルのPNG/JPG/WebP原稿を追加してください。ファイルは端末外に出ません。',limit:'入力ごとに64メガピクセル・一辺32,767px・80MB超は復号前に拒否します。',bytes:'WEBTOONの2MB/枚・20MB/話はフランスのCreator Academyと2025年コンテストFAQによる保守的な出力目標です。現在の投稿画面を確認してください。',verified:'すべての出力をワーカーで再読み込みしました。ZIPは端末内で作成します。投稿先の受理は未検証です。',order:'順序',dated:'出典確認 2026-09-29',custom:'カスタム：投稿先との互換性は主張しません。'}
};
const t=(k)=>copy[locale()]?.[k]||copy.en[k]||k;
export function mount({el}){
 if(['speed','balloon','tone'].includes(new URL(location.href).searchParams.get('mode')))return mountEffects({el});
 let files=[],sizes=[],preview='',cuts=[],cutWarnings=[],cutHistory=[],job=0,busy=false,mode=new URL(location.href).searchParams.get('mode')==='join'?'join':'split';
 const url=new URL(location.href),q=url.searchParams;
 let preset=PROFILES[q.get('profile')]?q.get('profile'):'canvas',height=Math.min(10000,Math.max(128,Number(q.get('height'))||1280)),format=['png','jpeg'].includes(q.get('format'))?q.get('format'):'jpeg',matte=/^#[0-9a-f]{6}$/i.test(q.get('matte')||'')?q.get('matte'):'#ffffff';
 const worker=new Worker(new URL('../webtoon/worker.js',import.meta.url),{type:'module'});
 let awaiting=new Map();worker.onmessage=e=>{const {id,type,error}=e.data||{},p=awaiting.get(id);if(!p)return;if(type==='progress'){const out=el.querySelector('#webtoonStatus');if(out)out.textContent=`${t('working')} ${e.data.stage} ${e.data.done}/${e.data.total}`;return;}awaiting.delete(id);type==='error'?p.reject(new Error(error)):p.resolve(e.data);};
 function ask(action,payload={}){const id=++job;return {id,promise:new Promise((resolve,reject)=>{awaiting.set(id,{resolve,reject});worker.postMessage({id,action,...payload});})};}
 const release=()=>{if(preview)URL.revokeObjectURL(preview);preview='';};
 const syncURL=()=>{const u=new URL(location.href);for(const key of ['profile','height','format','matte','mode','cuts'])u.searchParams.delete(key);u.searchParams.set('profile',preset);u.searchParams.set('height',String(height));u.searchParams.set('format',format);u.searchParams.set('mode',mode);if(matte!=='#ffffff')u.searchParams.set('matte',matte);if(cuts.length)u.searchParams.set('cuts',cuts.join(','));history.replaceState({},'',u);};
 function render(){
  queueMicrotask(()=>{const tabs=el.querySelector('.webtoon-tabs');if(!tabs||tabs.querySelector('[data-effect-link]'))return;for(const [key,names] of [['speed',['집중선','Speed lines','集中線']],['balloon',['말풍선','Speech balloon','吹き出し']],['tone',['스크린톤','Screentone','スクリーントーン']]]){const a=document.createElement('a');a.dataset.effectLink=key;a.href='?mode='+key;a.textContent=names[{ko:0,en:1,ja:2}[locale()]||1];tabs.append(a);}});
  queueMicrotask(()=>{for(const input of el.querySelectorAll('[data-cut]')){const warning=cutWarnings[Number(input.dataset.cut)]||'manual',label=input.closest('label');if(label&&!label.querySelector('small')){const small=document.createElement('small');small.textContent=' · '+({ko:{candidate:'여백 후보',uncertain:'불확실',manual:'직접 지정'},en:{candidate:'gutter candidate',uncertain:'uncertain',manual:'manual'},ja:{candidate:'余白候補',uncertain:'不確実',manual:'手動'}}[locale()]||{})[warning];label.append(small);}}});
  const p=profile(preset),first=sizes[0];
  el.innerHTML=`<div class="webtoon-work"><section class="webtoon-main"><div class="webtoon-tabs" role="group" aria-label="Mode"><button data-mode="split" aria-pressed="${mode==='split'}">${t('split')}</button><button data-mode="join" aria-pressed="${mode==='join'}">${t('join')}</button></div><h2>${t('files')}</h2><p class="webtoon-muted">${t('none')}</p><ol class="webtoon-files">${files.map((f,i)=>`<li><span>${esc(f.name)}</span><small>${sizes[i]?`${sizes[i].width}×${sizes[i].height} · ${(f.size/1e6).toFixed(2)} MB`:''}</small><span class="webtoon-order"><button data-move="-1" data-index="${i}" aria-label="${t('up')} ${esc(f.name)}" ${i===0?'disabled':''}>↑</button><button data-move="1" data-index="${i}" aria-label="${t('down')} ${esc(f.name)}" ${i===files.length-1?'disabled':''}>↓</button><button data-remove="${i}" aria-label="${t('remove')} ${esc(f.name)}">×</button></span></li>`).join('')}</ol><button type="button" data-action="pick" class="ghost">+ ${text('add')}</button>
  ${preview?`<h2>${t('preview')}</h2><div class="webtoon-preview"><img src="${preview}" alt="${esc(files[0]?.name||'')}">${mode==='split'&&first?cuts.map((y,i)=>`<span class="webtoon-cut" style="top:${(y/first.height*100).toFixed(3)}%" aria-hidden="true">${i+1}</span>`).join(''):''}</div><p class="webtoon-muted">${t('previewHint')}</p>`:''}
  ${mode==='split'&&first?`<div class="webtoon-cuts"><h2>${t('cuts')}</h2>${cuts.map((y,i)=>`<label>${i+1}. <input data-cut="${i}" type="number" min="1" max="${first.height-1}" value="${y}" aria-label="${t('cuts')} ${i+1}"><button data-cut-remove="${i}" aria-label="${t('remove')} ${i+1}">×</button></label>`).join('')}<button data-add-cut="1" class="ghost">${t('addCut')}</button><button data-undo="1" class="ghost" ${cutHistory.length?'':'disabled'}>${t('undo')}</button></div>`:''}</section>
  <aside class="webtoon-side"><label>${t('profile')}<select id="webtoonProfile" ${mode==='join'?'disabled':''}>${Object.values(PROFILES).map(v=>`<option value="${v.id}" ${preset===v.id?'selected':''}>${v.label}</option>`).join('')}</select></label>${mode==='split'?`<label>${t('height')}<input id="webtoonHeight" type="number" min="128" max="10000" value="${height}"></label><p class="webtoon-muted">${t('heightHint')}</p><label>${t('format')}<select id="webtoonFormat" ${preset==='naver'?'disabled':''}><option value="jpeg" ${format==='jpeg'?'selected':''}>JPG</option><option value="png" ${format==='png'?'selected':''}>PNG</option></select></label><label>${t('matte')}<input id="webtoonMatte" type="color" value="${matte}"></label>`:''}<h3>${t('scope')}</h3><p>${esc(mode==='join'?t('custom'):p.scope)}</p><p class="webtoon-muted">${t('dated')}</p>${mode==='split'&&preset==='canvas'?`<p class="webtoon-warning">${t('bytes')}</p>`:''}${p.source&&mode==='split'?`<a href="${esc(p.source)}" target="_blank" rel="noopener">${esc(p.source)}</a>`:''}${p.bytesSource&&mode==='split'?`<a href="${esc(p.bytesSource)}" target="_blank" rel="noopener">${esc(p.bytesSource)}</a>`:''}<p class="webtoon-muted">${t('limit')}</p><p id="webtoonStatus" role="status" aria-live="polite">${busy?t('working'):t('status')}</p><button id="webtoonRun" class="primary" ${busy||!files.length?'disabled':''}>${mode==='join'?t('joinExport'):t('export')}</button><button id="webtoonCancel" class="ghost" ${busy?'':'hidden'}>${t('cancel')}</button><p class="webtoon-muted">${t('verified')}</p></aside></div>`;
 }
 function setCuts(next){cutHistory.push([...cuts]);if(cutHistory.length>30)cutHistory.shift();cuts=next;cutWarnings=cuts.map(()=>'manual');syncURL();render();}
 async function inspect(){release();sizes=[];render();if(!files.length)return;busy=true;const status=el.querySelector('#webtoonStatus');if(status)status.textContent=t('checking');try{const result=await ask('inspect',{files}).promise;sizes=result.sizes;preview=URL.createObjectURL(result.preview);const saved=(new URL(location.href).searchParams.get('cuts')||'').split(',').filter(Boolean).map(Number),outWidth=preset==='naver'?690:preset==='canvas'?Math.min(800,sizes[0].width):sizes[0].width,target=Math.max(1,Math.floor(height*sizes[0].width/outWidth));const auto=suggestedCuts(sizes[0].height,target,result.rowInk,{radius:Math.min(100,Math.floor(target*.1)),minPart:Math.min(64,Math.max(1,Math.floor(target*.2)))});try{validateCuts(sizes[0].height,saved);cuts=saved.length?saved:auto.cuts;cutWarnings=saved.length?saved.map(()=>'manual'):auto.warnings;}catch{cuts=auto.cuts;cutWarnings=auto.warnings;} }catch(e){toast(e.message,{error:true});files=[];sizes=[];}finally{busy=false;render();}}
 async function run(){if(busy||!files.length)return;busy=true;render();let current;try{current=ask(mode,{files,options:{profile:preset,height,format,matte,cuts}});el.querySelector('#webtoonCancel').onclick=()=>worker.postMessage({id:current.id,action:'cancel'});const {parts,report}=await current.promise;const width=Math.max(2,String(parts.length).length),entries=parts.map((p,i)=>({name:`episode-${String(i+1).padStart(width,'0')}.${p.format==='jpeg'?'jpg':'png'}`,blob:p.blob}));entries.push({name:'export-report.json',blob:new Blob([JSON.stringify({tool:'Nerulio Webtoon/Manga Toolkit',checkedAt:report.checked,profile:mode==='join'?'custom':preset,scope:report.scope,source:report.source,bytesSource:report.bytesSource||'',parts:parts.map((p,i)=>({name:entries[i].name,width:p.width,height:p.height,bytes:p.bytes,sourceY:p.sourceY,sourceHeight:p.sourceHeight})),total:report.total},null,2)],{type:'application/json'})});const archive=await zip(entries);download(archive,'webtoon-episode.zip');track('webtoon_export',{mode,count:parts.length});toast(t('done').replace('{n}',parts.length).replace('{mb}',(report.total/1e6).toFixed(2)));}catch(e){toast(e.message,{error:true});}finally{busy=false;render();}}
 el.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode){mode=b.dataset.mode;syncURL();render();return;}if(b.dataset.move){const i=Number(b.dataset.index),j=i+Number(b.dataset.move);[files[i],files[j]]=[files[j],files[i]];inspect();return;}if(b.dataset.remove!==undefined){files.splice(Number(b.dataset.remove),1);inspect();return;}if(b.dataset.cutRemove!==undefined){setCuts(cuts.filter((_,i)=>i!==Number(b.dataset.cutRemove)));return;}if(b.dataset.addCut){const max=sizes[0]?.height||0,y=Math.min(max-1,Math.max(1,Math.floor(max/2)));if(max>1&&!cuts.includes(y))setCuts([...cuts,y].sort((a,b)=>a-b));return;}if(b.dataset.undo){cuts=cutHistory.pop()||[];syncURL();render();return;}if(b.id==='webtoonRun')run();});
 el.addEventListener('change',e=>{const x=e.target;if(x.id==='webtoonProfile'){preset=x.value;format=profile(preset).format;cuts=[];syncURL();inspect();}else if(x.id==='webtoonHeight'){height=Math.min(10000,Math.max(128,Number(x.value)||1280));cuts=[];syncURL();inspect();}else if(x.id==='webtoonFormat'){format=x.value;syncURL();render();}else if(x.id==='webtoonMatte'){matte=x.value;syncURL();}else if(x.dataset.cut!==undefined){const next=[...cuts];next[Number(x.dataset.cut)]=Number(x.value);try{validateCuts(sizes[0].height,next);setCuts(next);}catch{toast('Invalid cut row',{error:true});render();}}});
 el.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='z'&&cutHistory.length){e.preventDefault();cuts=cutHistory.pop();syncURL();render();}});
 onLocale(()=>render());render();
 return {add(incoming){files.push(...incoming.filter(f=>/\.(png|jpe?g|webp)$/i.test(f.name)||['image/png','image/jpeg','image/webp'].includes(f.type)));inspect();}};
}
