import {preset,project,layer,validate,rng,WAVES,PRESET_NAMES} from './engine.js';
import {COPY,PRESET_LABELS,PARAMS,PARAM_NAMES} from './strings.js';
import {parseJsfxr,toJsfxrBase58,toJsfxrJSON} from './jsfxr-format.js';
import {zip} from '../core.js';
const locale=document.documentElement.lang in COPY?document.documentElement.lang:'en',c=COPY[locale],$=s=>document.querySelector(s),worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});let seq=0,waiting=new Map(),sound=preset('coin',1),rendered=null,legacy='',activePreset='coin',history=[],future=[],collection=[];let ctx=null,source=null,timer=0,selectedLayer=0,sampleCounter=0;
const COLLECTION_KEY='nerulio-sfx-collection-v1';
function loadCollection(){try{const raw=localStorage.getItem(COLLECTION_KEY);if(!raw||raw.length>2000000)return [];return JSON.parse(raw).slice(0,32).map(x=>({name:String(x.name).slice(0,60),sound:validate(x.sound)})).filter(x=>x.sound.layers.every(l=>l.kind!=='sample'));}catch{return [];}}
function saveCollection(){try{localStorage.setItem(COLLECTION_KEY,JSON.stringify(collection.filter(x=>x.sound.layers.every(l=>l.kind!=='sample'))));}catch{status(c.sampleTemporary,true);}}
worker.onmessage=({data:m})=>{const p=waiting.get(m.id);if(!p)return;waiting.delete(m.id);m.ok?p.resolve(m):p.reject(Error(m.error));};worker.onerror=e=>{for(const p of waiting.values())p.reject(Error(e.message));waiting.clear();};
function job(op,extra={},transfer=[]){const id=++seq;return new Promise((resolve,reject)=>{waiting.set(id,{resolve,reject});worker.postMessage({id,op,...extra},transfer);});}
function friendly(error){return error?.message==='SAMPLE_MEMORY_LIMIT'?c.sampleMemory:error?.message||String(error);}
function status(message,error=false){const el=$('#status');el.textContent=message;el.dataset.error=error?'1':'0';}
function push(){history.push(JSON.stringify({sound,legacy}));if(history.length>60)history.shift();future=[];}
function restore(json){const o=JSON.parse(json);sound=validate(o.sound);legacy=o.legacy||'';syncControls();schedule();}
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function syncControls(){$('#seed').value=sound.seed;$('#rate').value=sound.rate;$('#bpm').value=sound.bpm;$('#master').value=sound.master;$('#limiter').checked=sound.limiter;$('#foreign').value=legacy?toJsfxrJSON(parseJsfxr(legacy)):'';renderLayers();renderSequence();renderTimeline();renderCollection();}
function renderLayers(){const holder=$('#layers');holder.replaceChildren();sound.layers.forEach((x,i)=>{const section=document.createElement('section');section.className='sfx-layer';section.innerHTML=`<div class="sfx-section-head"><h4>${esc(c.layer)} ${i+1}</h4><button type="button" data-remove="${i}" ${sound.layers.length===1?'disabled':''}>${esc(c.delete)}</button></div><div class="sfx-settings"><label>${esc(c.wave)} <select data-layer="${i}" data-field="wave">${WAVES.map(w=>`<option value="${w}" ${x.wave===w?'selected':''}>${w}</option>`).join('')}</select></label><label>${esc(c.sample)} <select data-layer="${i}" data-field="kind"><option value="synth" ${x.kind==='synth'?'selected':''}>${esc(c.synth)}</option><option value="sample" ${x.kind==='sample'?'selected':''}>${esc(c.sample)} ${esc(x.sampleId||'—')}</option></select></label></div>${x.kind==='sample'?`<div class="sfx-settings"><label>${esc(c.trimStart)}<input type="number" min="0" max="180" step="0.001" data-layer="${i}" data-field="sampleStart" value="${x.sampleStart}"></label><label>${esc(c.trimEnd)}<input type="number" min="0" max="180" step="0.001" data-layer="${i}" data-field="sampleEnd" value="${x.sampleEnd}"></label><label><input type="checkbox" data-layer="${i}" data-field="sampleLoop" ${x.sampleLoop?'checked':''}>${esc(c.loopSample)}</label></div>`:''}<div class="sfx-knobs">${PARAMS.map(([key,min,max,step,unit])=>`<label>${esc(PARAM_NAMES[locale][key])} <span>${unit}</span><input type="number" data-layer="${i}" data-field="${key}" min="${min}" max="${max}" step="${step}" value="${x[key]}"></label>`).join('')}</div>`;holder.append(section);});}
function renderSequence(){$('#sequence').innerHTML=sound.sequence.map((s,i)=>`<div class="sfx-note"><label>${esc(c.layer)} <select data-note="${i}" data-field="layer">${sound.layers.map((_,j)=>`<option value="${j}" ${s.layer===j?'selected':''}>${j+1}</option>`).join('')}</select></label><label>${esc(c.time)} <input type="number" min="0" max="180" step="0.01" value="${s.at}" data-note="${i}" data-field="at"></label><label>${esc(c.pitch)} <input type="number" min="-48" max="48" step="1" value="${s.pitch}" data-note="${i}" data-field="pitch"></label><label>${esc(c.gain)} <input type="number" min="0" max="2" step="0.01" value="${s.gain}" data-note="${i}" data-field="gain"></label><button data-note-remove="${i}" type="button">${esc(c.delete)}</button></div>`).join('');}
function renderTimeline(){const step=60/sound.bpm/4;$('#timeline').innerHTML=`<div class="sfx-grid" role="group" aria-label="${esc(c.steps)}"><span></span>${Array.from({length:16},(_,i)=>`<span class="sfx-step-label">${i+1}</span>`).join('')}${Array.from({length:12},(_,row)=>{const pitch=6-row;return `<span class="sfx-row-label">${pitch>0?'+':''}${pitch}</span>`+Array.from({length:16},(_,col)=>{const at=col*step,on=sound.sequence.some(n=>n.layer===selectedLayer&&n.pitch===pitch&&Math.abs(n.at-at)<.001);return `<button type="button" data-step="${col}" data-tone="${pitch}" aria-pressed="${on}" aria-label="${esc(c.time)} ${at.toFixed(3)}; ${esc(c.pitch)} ${pitch}; ${esc(c.layer)} ${selectedLayer+1}" class="${on?'on':''}">${on?'●':'·'}</button>`;}).join('');}).join('')}</div>`;}
function renderCollection(){$('#collection').innerHTML=collection.map((p,i)=>`<div class="sfx-note"><button type="button" data-choose="${i}">${esc(p.name)} · #${p.sound.seed}</button><label>${esc(c.rename)}<input data-rename="${i}" maxlength="60" value="${esc(p.name)}"></label><button type="button" data-up="${i}" aria-label="${esc(c.up)} ${esc(p.name)}" ${i===0?'disabled':''}>↑</button><button type="button" data-down="${i}" aria-label="${esc(c.down)} ${esc(p.name)}" ${i===collection.length-1?'disabled':''}>↓</button><button type="button" data-collection-remove="${i}" aria-label="${esc(c.remove)} ${esc(p.name)}">×</button></div>`).join('');}
function graph(){const canvas=$('#wave'),g=canvas.getContext('2d'),w=canvas.width,h=canvas.height;g.fillStyle='#121d2c';g.fillRect(0,0,w,h);g.strokeStyle='#33506b';g.beginPath();g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke();if(!rendered)return;const {left,right}=rendered;g.strokeStyle='#77e6ce';g.lineWidth=1;g.beginPath();for(let x=0;x<w;x++){const a=Math.floor(x*left.length/w),b=Math.max(a+1,Math.floor((x+1)*left.length/w));let lo=1,hi=-1;for(let j=a;j<b;j++){const v=(left[j]+right[j])*.5;lo=Math.min(lo,v);hi=Math.max(hi,v);}g.moveTo(x,h/2-hi*h*.43);g.lineTo(x,h/2-lo*h*.43);}g.stroke();}
function metrics(m){const pct=x=>Number(x).toFixed(4);$('#metrics').textContent=`${c.duration}: ${m.duration.toFixed(3)} s · Peak ${pct(m.peak)} · RMS ${pct(m.rms)} · ${c.dc}: ${pct(m.dc)} · ${c.clip}: ${m.clippedSamples}`;}
async function redraw(){const requested=revision;try{if($('#status').dataset.error!=='1')status(c.processing);const m=await job('render',legacy?{legacy}:{project:sound});if(requested!==revision)return false;rendered=m;metrics(m.metrics);graph();if($('#status').dataset.error!=='1')status(c.ready);return true;}catch(e){if(requested===revision)status(`${c.error} ${e.message}`,true);return false;}}
let revision=0;
function schedule(){revision++;rendered=null;status(c.processing);clearTimeout(timer);timer=setTimeout(redraw,100);}
async function ensureRender(){clearTimeout(timer);for(let tries=0;tries<3&&!rendered;tries++)await redraw();if(!rendered)throw Error('Sound is not ready');}
function selectPreset(name){push();activePreset=name;sound=preset(name,Math.floor(Math.random()*4294967295));legacy='';syncControls();schedule();}
function download(bytes,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([bytes],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function exportAudio(){const format=$('#format').value,bits=Number($('#bits').value);status(c.processing);try{await ensureRender();const m=await job('export',{format,bits});download(m.bytes,`nerulio-sfx-${sound.seed}.${format}`,format==='mp3'?'audio/mpeg':format==='ogg'?'audio/ogg':'audio/wav');$('#formatStatus').textContent=`${c.verified}: ${format.toUpperCase()} · ${m.bytes.length} B`;status(c.ready);}catch(e){$('#formatStatus').textContent=`${c.unverified}: ${format.toUpperCase()}`;status(`${c.unsupported} ${e.message}`,true);}}
async function batch(){const count=Math.max(2,Math.min(32,Number($('#variants').value)||4)),base=sound.seed,format=$('#format').value,bits=Number($('#bits').value),entries=[];status(c.processing);try{for(let i=0;i<count;i++){const p=validate({...sound,seed:(base+i*104729)>>>0});await job('render',{project:p});const m=await job('export',{format,bits});entries.push({name:`sfx-${String(i+1).padStart(2,'0')}-seed-${p.seed}.${format}`,blob:new Blob([m.bytes])});}entries.push({name:'settings.json',blob:new Blob([JSON.stringify({version:1,format,bits,variations:count,baseSeed:base,project:sound},null,2)])});const archive=await zip(entries);download(archive,`nerulio-sfx-${base}-variants.zip`,'application/zip');status(c.ready);await redraw();}catch(e){status(`${c.error} ${e.message}`,true);}}
async function exportCollection(){if(!collection.length)return;const format=$('#format').value,bits=Number($('#bits').value),entries=[];status(c.processing);try{for(let i=0;i<collection.length;i++){const item=collection[i],p=validate(item.sound);await job('render',{project:p});const m=await job('export',{format,bits});entries.push({name:`${String(i+1).padStart(2,'0')}-${item.name.replace(/[^\w-]+/g,'-').slice(0,40)||'sound'}.${format}`,blob:new Blob([m.bytes])});}entries.push({name:'collection.json',blob:new Blob([JSON.stringify({format:'nerulio-sfx-collection',version:1,sounds:collection},null,2)])});download(await zip(entries),'nerulio-sfx-collection.zip','application/zip');status(c.ready);}catch(e){status(`${c.error} ${e.message}`,true);}finally{schedule();}}
function mutate(){push();const r=rng((sound.seed+Date.now())>>>0),x=sound.layers[Math.floor(r()*sound.layers.length)];for(const k of ['freq','slide','attack','decay','hold','release','lp','hp','gain'])x[k]=+(x[k]*(.82+r()*.36)).toFixed(4);sound.seed=(sound.seed+1)>>>0;legacy='';sound=validate(sound);syncControls();schedule();}
async function share(){try{await ensureRender();const copy=structuredClone(sound),omitted=copy.layers.some(x=>x.kind==='sample');for(const x of copy.layers)if(x.kind==='sample'){x.kind='synth';x.sampleId='';}const payload=btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(copy)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const u=new URL(location.href);u.searchParams.set('s',payload);await navigator.clipboard.writeText(u.href);status((omitted?c.sampleHint+' ':'')+u.href);}catch(e){status(e.message,true);}}
async function sampleFile(file){if(!file||file.size>16*1024*1024)throw Error('Sample file exceeds 16 MiB');const ac=new AudioContext();try{const buf=await ac.decodeAudioData(await file.arrayBuffer()),duration=Math.min(180,buf.duration),rate=sound.rate,n=Math.ceil(duration*rate),pcm=new Float32Array(n),channel=buf.getChannelData(0);for(let i=0;i<n;i++){const pos=i*buf.sampleRate/rate,j=Math.floor(pos),f=pos-j;pcm[i]=(channel[j]||0)*(1-f)+(channel[j+1]||0)*f;}const sampleId=`local-${++sampleCounter}`;await job('sample',{pcm,sampleId,rate},[pcm.buffer]);push();const x=sound.layers[selectedLayer]||sound.layers[0];x.kind='sample';x.sampleId=sampleId;x.sampleStart=0;x.sampleEnd=duration;x.sampleLoop=false;x.attack=0;x.decay=0;x.sustain=1;x.hold=Math.min(180,duration);x.release=0;legacy='';syncControls();schedule();}finally{await ac.close();}}
function wire(){document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>selectPreset(b.dataset.preset)));$('#generate').onclick=()=>selectPreset(activePreset);$('#mutate').onclick=mutate;$('#undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify({sound,legacy}));restore(history.pop());};$('#redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify({sound,legacy}));restore(future.pop());};$('#play').onclick=async()=>{try{await ensureRender();source?.stop();ctx||=new AudioContext();await ctx.resume();const b=ctx.createBuffer(2,rendered.left.length,rendered.rate);b.copyToChannel(rendered.left,0);b.copyToChannel(rendered.right,1);source=ctx.createBufferSource();source.buffer=b;source.connect(ctx.destination);source.start();}catch(e){status(e.message,true);}};$('#stop').onclick=()=>{source?.stop();source=null;};
 for(const id of ['seed','rate','master','limiter'])$('#'+id).addEventListener('change',()=>{push();sound.seed=(Number($('#seed').value)>>>0)||1;sound.rate=Number($('#rate').value);sound.master=Number($('#master').value);sound.limiter=$('#limiter').checked;legacy='';sound=validate(sound);syncControls();schedule();});
 $('#addLayer').onclick=()=>{if(sound.layers.length>=4)return;push();sound.layers.push(layer('sine',{freq:440,gain:.25}));syncControls();schedule();};$('#layers').addEventListener('change',e=>{const el=e.target,i=Number(el.dataset.layer),field=el.dataset.field;if(!field)return;push();sound.layers[i][field]=field==='wave'||field==='kind'?el.value:field==='sampleLoop'?el.checked:Number(el.value);legacy='';sound=validate(sound);syncControls();schedule();});$('#layers').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b||sound.layers.length<2)return;push();sound.layers.splice(Number(b.dataset.remove),1);sound.sequence=sound.sequence.filter(s=>s.layer<sound.layers.length);syncControls();schedule();});$('#layers').addEventListener('focusin',e=>{const n=Number(e.target.dataset.layer);if(Number.isInteger(n)&&n!==selectedLayer){selectedLayer=n;renderTimeline();}});
 $('#addNote').onclick=()=>{if(sound.sequence.length>=64)return;push();sound.sequence.push({layer:selectedLayer,at:Math.max(0,sound.sequence.length*60/sound.bpm/4),pitch:0,gain:1});renderSequence();renderTimeline();schedule();};$('#sequence').addEventListener('change',e=>{const el=e.target,i=Number(el.dataset.note),field=el.dataset.field;if(!field)return;push();sound.sequence[i][field]=Number(el.value);sound=validate(sound);renderSequence();renderTimeline();schedule();});$('#sequence').addEventListener('click',e=>{const el=e.target.closest('[data-note-remove]');if(!el)return;push();sound.sequence.splice(Number(el.dataset.noteRemove),1);renderSequence();renderTimeline();schedule();});
 $('#bpm').onchange=()=>{push();const previous=sound.bpm;sound.bpm=Math.max(40,Math.min(240,Number($('#bpm').value)||120));sound.sequence.forEach(n=>n.at=+(n.at*previous/sound.bpm).toFixed(5));sound=validate(sound);renderSequence();renderTimeline();schedule();};$('#timeline').onclick=e=>{const b=e.target.closest('[data-step]');if(!b)return;const at=Number(b.dataset.step)*60/sound.bpm/4,pitch=Number(b.dataset.tone),i=sound.sequence.findIndex(n=>n.layer===selectedLayer&&n.pitch===pitch&&Math.abs(n.at-at)<.001);if(i<0&&sound.sequence.length>=64)return;push();if(i>=0)sound.sequence.splice(i,1);else sound.sequence.push({layer:selectedLayer,at:+at.toFixed(5),pitch,gain:1});renderSequence();renderTimeline();schedule();};
 $('#sampleFile').onchange=async e=>{try{await sampleFile(e.target.files[0]);}catch(x){status(friendly(x),true);}e.target.value='';};addEventListener('drop',async e=>{if(!e.dataTransfer.files.length)return;e.preventDefault();try{await sampleFile(e.dataTransfer.files[0]);}catch(x){status(friendly(x),true);}});addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});addEventListener('paste',async e=>{const f=e.clipboardData?.files?.[0];if(!f)return;e.preventDefault();try{await sampleFile(f);}catch(x){status(friendly(x),true);}});
 $('#saveAudio').onclick=exportAudio;$('#batch').onclick=batch;$('#exportCollection').onclick=exportCollection;$('#keep').onclick=()=>{collection.push({name:activePreset,sound:structuredClone(sound)});if(collection.length>32)collection.shift();saveCollection();renderCollection();};$('#collection').onclick=e=>{const choose=e.target.closest('[data-choose]'),remove=e.target.closest('[data-collection-remove]'),up=e.target.closest('[data-up]'),down=e.target.closest('[data-down]');if(choose){push();sound=validate(collection[Number(choose.dataset.choose)].sound);legacy='';syncControls();schedule();}else if(remove){collection.splice(Number(remove.dataset.collectionRemove),1);saveCollection();renderCollection();}else if(up||down){const i=Number((up||down).dataset[up?'up':'down']),j=i+(up?-1:1);[collection[i],collection[j]]=[collection[j],collection[i]];saveCollection();renderCollection();}};$('#collection').addEventListener('change',e=>{const i=Number(e.target.dataset.rename);if(!Number.isInteger(i)||!collection[i])return;collection[i].name=e.target.value.trim().slice(0,60)||'Sound';saveCollection();e.target.closest('.sfx-note')?.querySelector('[data-choose]')?.replaceChildren(document.createTextNode(`${collection[i].name} · #${collection[i].sound.seed}`));});
 $('#saveProject').onclick=()=>download(new TextEncoder().encode(JSON.stringify({format:'nerulio-sfx',version:1,project:sound},null,2)),`nerulio-sfx-${sound.seed}.json`,'application/json');$('#projectFile').onchange=async e=>{try{const o=JSON.parse(await e.target.files[0].text());push();sound=validate(o.project||o);legacy='';syncControls();schedule();}catch(x){status(friendly(x),true);}e.target.value='';};$('#share').onclick=share;
 $('#useLegacy').onclick=()=>{try{push();legacy=toJsfxrJSON(parseJsfxr($('#foreign').value));$('#foreignStatus').textContent=c.legacy;schedule();}catch(x){status(friendly(x),true);}};$('#returnOwn').onclick=()=>{legacy='';$('#foreignStatus').textContent='';schedule();};$('#exportJsfxr').onclick=()=>{try{if(!legacy)throw Error(c.noJsfxr);const value=toJsfxrBase58(parseJsfxr(legacy));navigator.clipboard.writeText(value).then(()=>status(value));}catch(x){status(friendly(x),true);}};
 $('#format').onchange=()=>{$('#bits').disabled=$('#format').value!=='wav';$('#formatStatus').textContent=c.unverified;};}
try{const text=new URL(location.href).searchParams.get('s');if(text&&text.length<9000){const raw=atob(text.replace(/-/g,'+').replace(/_/g,'/')),bytes=Uint8Array.from(raw,ch=>ch.charCodeAt(0));sound=validate(JSON.parse(new TextDecoder().decode(bytes)));}}catch(e){status(e.message,true);}
collection=loadCollection();syncControls();wire();redraw();
