/** Character Counter Pro: definitions are deliberately explicit where sites disagree. */
const SRC={en:'[Unicode grapheme rules](https://www.unicode.org/reports/tr29/tr29-49.html) · [official twitter-text v3 config](https://github.com/twitter/twitter-text/blob/master/config/v3.json)',ko:'[유니코드 문자소 규칙](https://www.unicode.org/reports/tr29/tr29-49.html) · [공식 twitter-text v3 설정](https://github.com/twitter/twitter-text/blob/master/config/v3.json)',ja:'[Unicodeの書記素規則](https://www.unicode.org/reports/tr29/tr29-49.html) · [公式twitter-text v3設定](https://github.com/twitter/twitter-text/blob/master/config/v3.json)'};
export default {'character-counter':{
 type:'tool',intent:{primary:'count visible characters, words, lines, bytes and X post weight',secondary:['character count without spaces','Shift_JIS versus EUC-KR versus CP949','manuscript page estimate'],goal:'reproducible counts with clearly named definitions',input:'typed or pasted text, or a UTF-8 .txt/.md file up to 8 MiB',output:'local counts and estimates; no uploaded text',support:'full',evidence:['src/task/character-core.js','tests/character-counter.test.mjs','tests/character-counter-browser.py']},
 en:{answer:'Paste text to count grapheme clusters (what people usually see as characters), Unicode code points, UTF-16 units, words, sentences, lines, paragraphs and UTF-8 bytes. The X ordinary-post figure uses official twitter-text 3.1.0 with v3 weighting, so a URL or emoji need not cost the same as one plain letter. Shift_JIS, strict EUC-KR and CP949 counts are shown only if every character is encodable. The Japanese 400-cell and Korean 200-cell manuscript figures are arithmetic estimates, not publisher or job-board acceptance rules. Text is processed on your device.',
  concept:{title:'Which character definition?',body:['A combining accent can share one grapheme with its base letter, while an emoji can use several code points and UTF-16 units. The main number uses Unicode grapheme segmentation. The detail panel exposes the other definitions so a form limit can be matched to its own specification.','UTF-8 encodes all valid Unicode text. Legacy encodings cover different character sets: CP949 can encode some Korean syllables that strict EUC-KR cannot. An unencodable character makes that encoding’s byte total unavailable rather than silently replacing it.','Whitespace and line breaks are included in the full UTF-8 byte total. Some competing counters omit them; compare numbers only when the input and whitespace rule match.'],terms:[['Grapheme','A user-perceived character under Unicode text segmentation.'],['Code point','One Unicode scalar value; a visible symbol may contain several.'],['UTF-16 unit','One 16-bit storage unit; a supplementary code point needs two.']]},
  example:{title:'A multilingual example',lead:'For `A 한 😀` the spaces count in the full UTF-8 total.',lines:['Input: A 한 😀','Graphemes: 5','Code points: 5','UTF-16 units: 6','Full UTF-8 bytes: 10'],after:'The emoji cannot be encoded in Shift_JIS, strict EUC-KR or CP949, so those three byte totals are unavailable for this whole input.'},
  verify:{steps:['Paste a short test such as `A 한 😀` and compare its displayed UTF-8 bytes with a UTF-8 encoded file: the full text uses 10 bytes.','For X, test a URL and emoji against the official twitter-text v3 fixture set; this tool reports that precise rule and version.']},
  trouble:{rows:[['Another site shows fewer UTF-8 bytes','It may omit spaces and line breaks before encoding','Try `A B`: this tool reports 3 full UTF-8 bytes','Select the same whitespace definition before comparing'],['EUC-KR has no total but CP949 does','The input contains a CP949 extension character','Remove the marked unsupported characters one at a time','Use the destination’s specified encoding'],['One emoji seems to count as several units','The destination likely counts code points or UTF-16','Compare the detailed grapheme, code-point and UTF-16 rows','Use the row named by the destination'],['The X result differs from a post composer','Account privileges or platform-side rules may differ','Confirm this tool says twitter-text 3.1.0 / config v3','Check the live composer before publishing']]},
  alternatives:{rows:[['The destination form itself','Use its live limit when it publishes an exact rule or applies account-specific privileges.'],['A text editor with encoding selection','Use it to inspect the actual saved file bytes, including line-ending conversion.']]},limits:['Manuscript pages are a simple division of non-whitespace graphemes; punctuation and line placement are not modelled.','No Saramin or JobKorea compatibility claim is made because an official universal count rule was not verified.','The tool accepts UTF-8 text files; it does not auto-detect an uploaded legacy encoding.'],versions:{body:['Unicode grapheme segmentation follows the browser’s Intl.Segmenter. X uses the vendored official twitter-text 3.1.0 parser and its version-3 configuration. Legacy tables are generated from strict Python codecs and checked against GNU iconv.'],sources:[SRC.en]}},
 ko:{answer:'글을 붙여넣으면 보이는 글자에 가까운 문자소뿐 아니라 유니코드 코드 포인트, UTF-16 코드 단위, 단어, 문장, 줄, 문단, UTF-8 바이트를 각각 셉니다. X 일반 게시물 수치는 공식 twitter-text 3.1.0의 v3 가중치를 사용하므로 URL과 이모지는 글자 한 개와 다르게 계산될 수 있습니다. Shift_JIS·엄격한 EUC-KR·CP949 바이트는 모든 글자를 표현할 수 있을 때만 표시합니다. 한국 200칸·일본 400칸 원고지는 단순 분량 추정이며 채용 사이트나 출판사의 접수 기준이 아닙니다. 본문은 기기 안에서 처리합니다.',
  concept:{title:'무엇을 한 글자로 셀까?',body:['기본 글자 수는 유니코드 문자소 분할로 계산합니다. 결합 악센트는 앞 글자와 하나의 문자소가 될 수 있고, 이모지 하나는 코드 포인트와 UTF-16 단위를 여러 개 쓸 수 있습니다. 상세 결과에서 각각의 정의를 확인하세요.','UTF-8은 유효한 유니코드 글자를 모두 표현합니다. 기존 인코딩은 범위가 달라 CP949에서 되는 한국어 글자가 엄격한 EUC-KR에서는 안 될 수 있습니다. 표현할 수 없는 글자가 있으면 임의 대체 바이트를 더하지 않고 해당 합계를 숨깁니다.','전체 UTF-8 바이트에는 공백과 줄바꿈이 포함됩니다. 다른 사이트가 이를 빼고 계산한다면 같은 입력이어도 결과가 달라집니다.'],terms:[['문자소','사람이 한 글자로 보는 단위에 가까운 유니코드 분할.'],['코드 포인트','유니코드 값 하나. 보이는 기호 하나가 여러 값을 가질 수 있습니다.'],['UTF-16 단위','16비트 저장 단위. 보충 평면 글자는 두 단위를 씁니다.']]},
  example:{title:'여러 언어가 섞인 예',lead:'`A 한 😀`에는 공백 두 개가 있고 전체 UTF-8 바이트에 포함합니다.',lines:['입력: A 한 😀','문자소: 5','코드 포인트: 5','UTF-16 단위: 6','전체 UTF-8 바이트: 10'],after:'이모지는 Shift_JIS·엄격한 EUC-KR·CP949로 표현할 수 없으므로 이 입력 전체의 해당 바이트 합계는 표시하지 않습니다.'},verify:{steps:['`A 한 😀`을 붙여넣고 전체 UTF-8 바이트 10을 UTF-8 파일의 실제 바이트와 대조하세요.','X 수치는 URL과 이모지 예제를 공식 twitter-text v3 테스트 사례와 대조하세요.']},
  trouble:{rows:[['다른 사이트의 UTF-8 바이트가 적음','공백과 줄바꿈을 뺀 뒤 인코딩했을 수 있습니다','`A B`는 여기서 전체 3바이트입니다','동일한 공백 기준으로 비교하세요'],['EUC-KR 수치는 없고 CP949 수치는 있음','CP949 확장 글자가 포함되었습니다','지원되지 않는 글자를 하나씩 지워 확인하세요','제출처가 지정한 인코딩을 쓰세요'],['이모지 한 개가 여러 단위로 보임','제출처가 코드 포인트나 UTF-16을 셀 수 있습니다','상세 표의 세 글자 정의를 비교하세요','제출처가 명시한 정의를 쓰세요'],['X 작성기와 값이 다름','계정 권한 또는 플랫폼 규칙이 다를 수 있습니다','표시된 twitter-text 3.1.0 / v3을 확인하세요','게시 전 실제 작성기에서 확인하세요']]},alternatives:{rows:[['제출처 입력칸','계정별 권한이나 정확한 제한을 적용하는 실제 입력칸을 우선 확인하세요.'],['인코딩 선택 기능이 있는 텍스트 편집기','줄바꿈 변환까지 포함한 저장 파일의 실제 바이트를 검사할 때 씁니다.']]},limits:['원고지 수치는 공백 제외 문자소를 단순히 나눈 값이며 문장부호와 행 배치를 반영하지 않습니다.','공식적인 공통 규칙을 확인하지 못했으므로 사람인·잡코리아 호환을 주장하지 않습니다.','UTF-8 텍스트 파일만 열며 업로드된 기존 인코딩을 자동 판별하지 않습니다.'],versions:{body:['문자소 분할은 브라우저 Intl.Segmenter를 사용합니다. X는 포함된 공식 twitter-text 3.1.0 파서와 v3 설정을 사용합니다. 기존 인코딩 표는 Python의 엄격한 코덱으로 만들고 GNU iconv와 대조했습니다.'],sources:[SRC.ko]}},
 ja:{answer:'文章を貼り付けると、見た目の文字に近い書記素クラスタに加え、Unicodeコードポイント、UTF-16コード単位、単語、文、行、段落、UTF-8バイトを別々に数えます。Xの通常投稿の数値は公式twitter-text 3.1.0のv3重み付けを使うため、URLや絵文字は普通の1文字と同じとは限りません。Shift_JIS・厳密なEUC-KR・CP949のバイト数は全文字を符号化できる場合だけ表示します。日本語400字詰めと韓国語200字詰めは単純な分量目安で、出版社や求人サイトの受付規則ではありません。本文は端末内で処理します。',
  concept:{title:'何を1文字と数えるか',body:['主な文字数はUnicodeの書記素クラスタで数えます。結合アクセントは前の文字と1クラスタになり、絵文字1個に複数のコードポイントやUTF-16単位が必要な場合があります。詳細欄でそれぞれ確認できます。','UTF-8は有効なUnicode文字を表現できます。古い符号化方式の対象範囲は異なり、CP949で表現できる韓国語の音節が厳密なEUC-KRでは表現できない場合があります。対応しない文字があれば置換バイトを勝手に足さず、合計を表示しません。','全体のUTF-8バイト数には空白と改行が入ります。別のサイトが空白を除く場合、同じ文章でも結果は変わります。'],terms:[['書記素クラスタ','人が1文字と見る単位に近いUnicodeの分割。'],['コードポイント','Unicodeの値1個。1つの記号に複数含まれることがあります。'],['UTF-16単位','16ビットの保存単位。補助平面の文字には2個必要です。']]},
  example:{title:'多言語の例',lead:'`A 한 😀`の2つの空白も全体のUTF-8バイト数に含みます。',lines:['入力: A 한 😀','書記素: 5','コードポイント: 5','UTF-16単位: 6','全体のUTF-8バイト: 10'],after:'絵文字はShift_JIS・厳密なEUC-KR・CP949では表現できないため、この入力全体のそれらのバイト合計は表示しません。'},verify:{steps:['`A 한 😀`を貼り付け、全体のUTF-8が10バイトと表示されることを、UTF-8ファイルの実際のバイト数で確かめます。','XのURLと絵文字を公式twitter-text v3のテスト事例と比べます。']},
  trouble:{rows:[['別サイトのUTF-8バイト数が少ない','空白や改行を除いてから符号化している可能性があります','`A B`はここでは全体で3バイトです','同じ空白の定義で比べます'],['EUC-KRは合計がなくCP949はある','CP949の拡張文字が入っています','対応しない文字を1つずつ除いて確かめます','提出先指定の符号化を使います'],['絵文字1個が複数の単位になる','提出先はコードポイントまたはUTF-16を数えている可能性があります','詳細の3種類の文字数を比べます','提出先が指定する定義を使います'],['Xの投稿欄と数値が違う','アカウント権限やプラットフォーム側の規則が異なる場合があります','twitter-text 3.1.0 / v3という表示を確認します','投稿前に実際の投稿欄で確認します']]},alternatives:{rows:[['提出先の入力欄','アカウントごとの権限や正確な上限を適用する実際の欄を確認します。'],['文字コードを選べるテキストエディター','改行変換を含めた保存ファイルの実際のバイトを調べる場合に使います。']]},limits:['原稿用紙は空白を除く書記素数の単純な割り算で、句読点や行の配置を再現しません。','公式の共通規則を確認できなかったため、特定の求人サイトとの互換性は主張しません。','UTF-8テキストファイルのみ受け付け、古い文字コードの自動判定はしません。'],versions:{body:['書記素分割はブラウザのIntl.Segmenterを使います。Xは同梱の公式twitter-text 3.1.0パーサーとv3設定を使います。古い文字コードの表はPythonの厳密なコーデックから作り、GNU iconvと照合しました。'],sources:[SRC.ja]}}
}};
