/** Specific, indexable help for the original local pixel avatar composer. */
const SOURCES={
 en:['[Creative Commons CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/)','[MDN: image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering)'],
 ko:['[Creative Commons CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/)','[MDN: image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering)'],
 ja:['[Creative Commons CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/)','[MDN: image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering)'],
};
export default {
 'game/pixel-avatar-maker':{
  type:'tool',
  intent:{primary:'make a small pixel avatar from original parts and export a transparent profile PNG or animated GIF',secondary:['commercial-use rights for avatar parts','share a reproducible character link','keep hard pixel edges at 32, 48 and 64 pixels'],goal:'a coherent, reusable character image with exact integer pixel blocks and explicit part rights',input:'no file required; optional local PNG, JPEG or WebP background',output:'transparent or backed PNG at 32–4096 pixels, eight-frame GIF at 32–1024 pixels, or a local 1200 × 630 card',target:'game profiles, social avatars and character concepts',support:'full',evidence:['src/avatar/catalog.js','src/avatar/render.js','src/avatar/gif.js','docs/avatar-prototype/SOURCES.md','tests/avatar-prototype-oracle.py','tests/avatar-gif-oracle.py'],external:['Creative Commons CC0 1.0','MDN image-rendering']},
  en:{
   answer:'Nerulio Pixel Avatar Maker combines original CC0 face, hair, eye, outfit and accessory parts on a 16 × 16 logical grid. Choose each part or randomize unlocked categories, then save a transparent PNG, an eight-frame blinking GIF or a 1200 × 630 share card. Every PNG size is a whole-number enlargement of that grid: 32 px is 2×, 48 px is 3×, 64 px is 4× and 4096 px is 256×. The export is generated locally. A settings link reproduces the built-in parts, but cannot carry an optional local background image or a unique social preview.',
   concept:{title:'A tiny grid with deliberate silhouettes',body:['The 16 × 16 source is a constraint, so the round and angular jaws, open and sleepy eyes, two hair outlines and two outfits were checked as separate parts at 32, 48 and 64 pixels before the tool was built. Output sizes are integer multiples of 16. Enlarging one source pixel into a square block preserves the authored palette and does not invent blended edge colors.','Hair and outfit colors use authored four-shade ramps. A color choice changes the entire ramp, including shadow and highlight, rather than rotating every RGB channel. Random uses a recorded seed and can leave locked categories intact. Undo returns to the preceding selection; a settings link stores part identifiers and palette choices, not raster bytes.','A user-supplied background stays in the browser. It is cropped to a square and reduced to the same 16 px grid before being placed behind the character. The background may have its own copyright; the CC0 grant applies to the original character parts, not to images added by a user.'],terms:[['Logical pixel','One cell of the authored 16 × 16 source image.'],['Integer enlargement','Each logical pixel becomes a 2 × 2, 3 × 3 or larger block without fractional interpolation.'],['CC0','A public-domain dedication for the original parts, to the extent of the author’s rights.']]},
   example:{title:'One avatar at four output sizes',lead:'The approved original study is in `docs/avatar-prototype/output`. Four variants were independently reopened with Pillow and compared pixel-for-pixel with the browser renderer’s 16 px image.',lines:['16 × 16 logical source = 256 cells','32 × 32 PNG = each cell copied 2 × 2','48 × 48 PNG = each cell copied 3 × 3','64 × 64 PNG = each cell copied 4 × 4','4096 × 4096 PNG = each cell copied 256 × 256'],after:'The 48 px choice is deliberately a 3× enlargement of 16 px, not a blurred reduction of a 64 px preview. The browser GIF uses the exact colors in the logical frames and an eight-frame blink; its 256 px sample reopened as eight frames with 130 ms GIF delays and an infinite loop. GIF timing is in hundredths of a second.'},
   outputs:{rows:[['avatar-size.png','A square RGBA PNG at the chosen integer size, with a transparent or chosen background.'],['avatar-size.gif','Eight-frame blink GIF at up to 1024 px. GIF transparency is one bit, and a local photo background is reduced to 16 px first.'],['avatar-card.png','A 1200 × 630 PNG card saved locally for manual attachment to a post. It does not become the social preview of the settings link.']]},
   target:{steps:['Choose a face, hair, eyes and outfit. Use Random for a starting point, then lock a part you want to keep.','Select a PNG size for a game profile or sprite reference. Prefer 32, 48 or 64 px when the destination displays small avatars.','Download the PNG and reopen it in the destination application. For a social image, save the card and attach the file manually; X and LINE buttons share only the settings link.']},
   verify:{steps:['At 32 px, confirm that the hair silhouette, eyes and jaw are still distinct. If an icon is displayed smaller than 32 px by another site, inspect that site’s result.','Open the PNG in another viewer and check its dimensions and alpha channel. A checkerboard in this page is a preview, not a baked background.','Reload a copied settings URL: the built-in parts and colors should return. A local background should be absent, because the URL never contains local image bytes.','Open the GIF in a frame-aware viewer and check eight frames, blink change, loop and transparent corner.']},
   trouble:{rows:[['The avatar looks blurry after upload','The destination site smooths or downsizes the PNG','Compare the downloaded PNG at 100% with the site’s displayed thumbnail','Use a size matching the destination, or choose nearest-neighbor display if that site allows it'],['My uploaded background vanished from a shared link','A local image is intentionally excluded from the URL','Reload the link and look for the local-background label','Download a PNG or card and attach that file to the post'],['The social preview is generic','Static pages do not generate a new Open Graph image for each settings query','Compare the link preview with the downloaded card','Attach the card manually; the link still restores built-in settings'],['GIF colors or motion differ from a video','GIF is an indexed format and this tool offers a fixed eight-frame eye blink','Inspect frames and frame delays in a GIF viewer','Use PNG for a still image or export the GIF at a smaller integer size']]},
   alternatives:{rows:[['[[game/pixel-art-editor|Pixel Art Editor]]','Draw every pixel yourself when you need a shape outside the authored part catalog.'],['[[game/sprite-lab|Sprite Lab]]','Cut and animate a full game sprite sheet when you already have character frames.']]},
   limits:['The current catalog has two face, hair, eye and outfit families plus simple accessories. It does not synthesize new art with AI.','A static settings URL cannot produce a unique Open Graph image without an approved server-side renderer. X and LINE share the link; Kakao rich sharing needs an owner app key and registered domain.','The original parts are CC0 and may be used commercially, but a user-added background may have separate rights. CC0 does not give exclusive ownership or trademark clearance.','A browser or phone may run out of memory on 4096 px output. Use a smaller integer size if an export fails.'],
   versions:{body:['Part catalog v1, 16 × 16 logical grid. Browser PNG/GIF outputs and the original art oracle were checked on 2026-09-28. The platform sharing behavior is explained separately in the tool design document.'],sources:SOURCES.en}
  },
  ko:{
   answer:'Nerulio 픽셀 아바타 만들기는 직접 제작한 CC0 얼굴·머리·눈·의상·장신구를 16×16 논리 격자에서 조합합니다. 파츠를 직접 고르거나 잠그지 않은 범주만 랜덤으로 바꾼 뒤 투명 PNG, 8프레임 눈 깜박임 GIF, 1200×630 공유 카드를 저장하세요. PNG는 모두 정수 배율입니다. 32px는 2배, 48px는 3배, 64px는 4배, 4096px는 256배입니다. 출력은 기기 안에서 만들어집니다. 설정 링크는 기본 파츠를 복원하지만 선택한 로컬 배경이나 아바타별 SNS 미리보기는 담지 않습니다.',
   concept:{title:'작은 격자에서도 구분되는 형태',body:['원본이 16×16으로 작으므로 둥근 턱과 각진 턱, 또렷한 눈과 졸린 눈, 두 가지 머리 윤곽과 의상을 각각 32·48·64px에서 확인한 뒤 구현했습니다. 한 원본 픽셀을 정사각형 블록으로 확대하므로 경계에 혼합색을 새로 만들지 않습니다.','머리와 의상 색은 그림자·기본색·하이라이트가 묶인 네 단계 팔레트로 바뀝니다. 랜덤 조합은 시드를 기록하고 잠긴 범주는 보존합니다. 실행 취소는 직전 선택으로 돌아갑니다. 설정 링크에는 파츠 이름과 팔레트 선택만 있으며 이미지 바이트는 없습니다.','사용자가 추가한 배경은 브라우저에 남습니다. 정사각형으로 자르고 16px 격자로 축소한 뒤 캐릭터 뒤에 놓습니다. 배경의 저작권은 사용자에게 달려 있으며 CC0 선언은 원본 캐릭터 파츠에만 적용됩니다.'],terms:[['논리 픽셀','직접 그린 16×16 원본의 한 칸입니다.'],['정수 확대','원본 한 칸을 2×2·3×3 등의 블록으로 복제합니다.'],['CC0','제작자가 가진 권리 범위에서 원본 파츠를 퍼블릭 도메인에 제공하는 선언입니다.']]},
   example:{title:'하나의 아바타를 네 크기로',lead:'승인된 원본 시트는 `docs/avatar-prototype/output`에 있습니다. Pillow로 다시 연 네 변형의 16px 픽셀을 브라우저 렌더러와 바이트 단위로 비교했습니다.',lines:['16 × 16 원본 = 256칸','32 × 32 PNG = 각 칸을 2 × 2 복제','48 × 48 PNG = 각 칸을 3 × 3 복제','64 × 64 PNG = 각 칸을 4 × 4 복제','4096 × 4096 PNG = 각 칸을 256 × 256 복제'],after:'48px은 64px 미리보기를 흐리게 줄인 그림이 아니라 16px의 정확한 3배입니다. 256px GIF 표본은 독립 재열기에서 8프레임, 130ms 지연, 무한 반복을 확인했습니다. GIF 지연은 1/100초 단위입니다.'},
   outputs:{rows:[['avatar-size.png','선택한 정수 크기의 정사각형 RGBA PNG입니다. 투명 또는 선택 배경을 가집니다.'],['avatar-size.gif','최대 1024px의 8프레임 눈 깜박임 GIF입니다. 투명은 1비트이며 로컬 배경은 먼저 16px로 축소합니다.'],['avatar-card.png','직접 게시물에 첨부할 1200×630 PNG 카드입니다. 설정 링크의 SNS 미리보기가 되지는 않습니다.']]},
   target:{steps:['얼굴·머리·눈·의상을 선택합니다. 랜덤으로 시작하고 유지할 파츠는 잠급니다.','프로필이나 스프라이트 참고용 PNG 크기를 선택합니다. 작게 보일 곳이라면 32·48·64px 결과를 직접 확인합니다.','PNG를 받아 대상 앱에서 다시 엽니다. SNS 이미지는 카드를 별도로 첨부하세요. X와 LINE 버튼은 설정 링크만 공유합니다.']},
   verify:{steps:['32px에서도 머리 윤곽·눈·턱이 구분되는지 확인합니다. 다른 사이트가 더 작게 축소하면 그 사이트의 최종 표시를 확인합니다.','별도 이미지 뷰어에서 PNG 크기와 알파를 확인합니다. 이 페이지의 체크무늬는 미리보기일 뿐 파일 배경이 아닙니다.','설정 링크를 새로 열어 기본 파츠와 색이 복원되는지 확인합니다. 로컬 배경은 링크에 이미지 바이트가 없으므로 복원되지 않습니다.','프레임을 볼 수 있는 앱에서 GIF 8프레임·눈 깜박임·반복·투명 모서리를 확인합니다.']},
   trouble:{rows:[['업로드 후 아바타가 흐림','업로드 대상이 PNG를 부드럽게 축소합니다','다운로드한 PNG의 100% 보기와 대상 썸네일을 비교합니다','대상 표시 크기에 맞는 출력을 고르거나 대상의 nearest 표시 옵션을 사용합니다'],['공유 링크에서 배경이 사라짐','로컬 이미지는 URL에 넣지 않습니다','링크를 새로 열어 로컬 배경 표시를 확인합니다','PNG 또는 카드를 저장해 게시물에 파일로 첨부합니다'],['SNS 미리보기가 공통 이미지임','정적 페이지는 설정 쿼리별 Open Graph 이미지를 생성하지 않습니다','링크 미리보기와 내려받은 카드를 비교합니다','카드를 직접 첨부합니다. 링크로 기본 설정은 복원됩니다'],['GIF의 색이나 움직임이 영상과 다름','GIF는 인덱스 형식이며 여기서는 고정 8프레임 눈 깜박임입니다','GIF 뷰어에서 각 프레임과 지연을 봅니다','정지 그림은 PNG를 쓰고 GIF는 작은 정수 크기로 출력합니다']]},
   alternatives:{rows:[['[[game/pixel-art-editor|픽셀 아트 에디터]]','준비된 파츠에 없는 모양을 픽셀마다 직접 그리고 싶을 때 사용합니다.'],['[[game/sprite-lab|스프라이트 랩]]','이미 가진 게임 캐릭터 시트를 자르고 애니메이션으로 만들 때 사용합니다.']]},
   limits:['현재 카탈로그는 얼굴·머리·눈·의상 각 두 계열과 간단한 장신구를 제공합니다. AI로 새 그림을 합성하지 않습니다.','정적 설정 URL만으로 아바타별 Open Graph 이미지를 만들 수 없습니다. X·LINE은 링크만 공유하며 Kakao 카드에는 소유자의 앱 키와 등록 도메인이 필요합니다.','원본 파츠는 CC0로 상업적으로 쓸 수 있지만 추가한 배경에는 별도 권리가 있을 수 있습니다. CC0가 독점 소유권이나 상표 사용권을 주지는 않습니다.','4096px 출력은 메모리가 적은 브라우저나 휴대폰에서 실패할 수 있습니다. 이때는 작은 정수 크기를 사용하세요.'],
   versions:{body:['파츠 카탈로그 v1, 16×16 원본 격자. 브라우저 PNG·GIF와 원본 그림 오라클을 2026-09-28에 확인했습니다. 플랫폼별 공유 동작은 도구 설계 문서에 따로 정리했습니다.'],sources:SOURCES.ko}
  },
  ja:{
   answer:'Nerulioピクセルアバター作成では、オリジナルのCC0顔・髪・目・服・アクセサリーを16×16の論理グリッドで組み合わせます。パーツを選ぶか、固定していないカテゴリだけをランダムに変え、透明PNG、8フレームのまばたきGIF、1200×630の共有カードを保存できます。PNGは整数倍だけです。32pxは2倍、48pxは3倍、64pxは4倍、4096pxは256倍になります。出力は端末内で作られます。設定リンクは標準パーツを再現しますが、追加した端末の背景画像やアバター別のSNSプレビューは含みません。',
   concept:{title:'小さなグリッドでも読める形',body:['元画像は16×16なので、丸い顎と角ばった顎、開いた目と眠そうな目、二つの髪型と服を32・48・64pxで確認してから実装しました。元の1ピクセルを四角いブロックに拡大するため、縁に混色を作りません。','髪と服の色は影・基本色・ハイライトを含む4段階のパレットで変わります。ランダム作成はシードを記録し、固定したカテゴリを保ちます。元に戻す操作は直前の選択へ戻ります。設定リンクにはパーツIDと色の選択だけが入り、画像データは入りません。','追加した背景はブラウザに残ります。正方形に切り取り16pxグリッドへ縮小してキャラクターの後ろに置きます。その画像の権利は利用者が確認してください。CC0宣言はオリジナルのキャラクターパーツにだけ適用されます。'],terms:[['論理ピクセル','手作業で描いた16×16画像の1マスです。'],['整数拡大','元の1マスを2×2、3×3などのブロックへ複製します。'],['CC0','作者が持つ権利の範囲でオリジナルパーツをパブリックドメインへ提供する宣言です。']]},
   example:{title:'一つのアバターを四つの大きさへ',lead:'承認済みの原画は`docs/avatar-prototype/output`にあります。Pillowで開き直した四つの16px画像をブラウザの描画結果とバイト単位で比較しました。',lines:['16 × 16 原画 = 256マス','32 × 32 PNG = 各マスを2 × 2に複製','48 × 48 PNG = 各マスを3 × 3に複製','64 × 64 PNG = 各マスを4 × 4に複製','4096 × 4096 PNG = 各マスを256 × 256に複製'],after:'48pxは64pxプレビューをぼかして縮小した画像ではなく、16pxの正確な3倍です。256px GIFの試料は別ソフトで開き直して8フレーム、130msの遅延、無限ループを確認しました。GIFの遅延は1/100秒単位です。'},
   outputs:{rows:[['avatar-size.png','選んだ整数サイズの正方形RGBA PNG。透明または選んだ背景を持ちます。'],['avatar-size.gif','最大1024pxの8フレームまばたきGIF。透明は1ビットで、端末の背景は先に16pxへ縮小します。'],['avatar-card.png','投稿に手動で添付する1200×630 PNGカード。設定リンクのSNSプレビューにはなりません。']]},
   target:{steps:['顔・髪・目・服を選びます。ランダムで始め、残したいパーツを固定できます。','プロフィールやスプライト参照用のPNGサイズを選びます。小さく表示する場合は32・48・64pxを直接確認します。','PNGを保存して対象アプリで開き直します。SNS用画像はカードを別に添付してください。XとLINEのボタンは設定リンクだけを共有します。']},
   verify:{steps:['32pxでも髪の輪郭・目・顎を見分けられるか確認します。別サイトがさらに縮小するなら、その最終表示を確認します。','別の画像ビューアでPNGの大きさとアルファを調べます。このページの市松模様はプレビューだけで、画像に焼き込まれません。','設定リンクを再読み込みし、標準パーツと色が戻るか確認します。端末の背景は画像データがURLにないため戻りません。','フレームを見られるアプリでGIFの8フレーム、まばたき、ループ、透明な角を確認します。']},
   trouble:{rows:[['アップロード後にぼやける','投稿先がPNGを滑らかに縮小します','保存したPNGの100%表示と投稿先のサムネイルを比べます','表示サイズに合う出力を選ぶか、投稿先の最近傍表示を使います'],['共有リンクから背景が消えた','端末の画像はURLに入れません','リンクを再読み込みし背景の表示を調べます','PNGかカードを保存して投稿に画像として添付します'],['SNSプレビューが共通画像になる','静的ページは設定ごとのOpen Graph画像を生成しません','リンクプレビューと保存したカードを比べます','カードを手動で添付します。リンクは標準設定を再現できます'],['GIFの色や動きが動画と違う','GIFはインデックス形式で、このツールは固定8フレームのまばたきです','GIFビューアでフレームと遅延を調べます','静止画像はPNGを使い、GIFは小さめの整数サイズで保存します']]},
   alternatives:{rows:[['[[game/pixel-art-editor|ピクセルアートエディター]]','用意されたパーツにない形を1ピクセルずつ描きたい場合に使います。'],['[[game/sprite-lab|スプライトラボ]]','既存のゲームキャラクターシートを分割してアニメにしたい場合に使います。']]},
   limits:['現在のカタログは顔・髪・目・服をそれぞれ二系統と簡単なアクセサリーだけ提供します。AIで新しい絵を合成しません。','静的な設定URLだけではアバター別のOpen Graph画像を作れません。X・LINEはリンクだけ共有し、Kakaoカードには所有者のアプリキーと登録ドメインが必要です。','オリジナルパーツはCC0で商用利用できますが、追加した背景には別の権利があります。CC0は独占所有権や商標権を与えません。','4096px出力はメモリの少ないブラウザや携帯端末で失敗することがあります。その場合は小さい整数サイズを選んでください。'],
   versions:{body:['パーツカタログv1、16×16原画グリッド。ブラウザのPNG・GIFと原画のオラクルを2026-09-28に確認しました。各プラットフォームの共有動作は設計文書に記録しています。'],sources:SOURCES.ja}
  }
 }
};
