/** The single indexable photo-to-pixel intent page. The old /image-to-pixel-art/ URL is a
 * noindex alias with /pixel/ as canonical. Measurements: docs/PIXEL-CONVERTER-RESULTS.md. */
const sources={
 en:['[Aseprite: Exporting](https://www.aseprite.org/docs/exporting/)','[W3C: PNG specification](https://www.w3.org/TR/png-3/)','[W3C: GIF89a specification](https://www.w3.org/Graphics/GIF/spec-gif89a.txt)'],
 ko:['[Aseprite: Exporting](https://www.aseprite.org/docs/exporting/)','[W3C: PNG 사양](https://www.w3.org/TR/png-3/)','[W3C: GIF89a 사양](https://www.w3.org/Graphics/GIF/spec-gif89a.txt)'],
 ja:['[Aseprite: Exporting](https://www.aseprite.org/docs/exporting/)','[W3C: PNG仕様](https://www.w3.org/TR/png-3/)','[W3C: GIF89a仕様](https://www.w3.org/Graphics/GIF/spec-gif89a.txt)']
};
export default {
 pixel:{type:'conversion',intent:{primary:'convert a photograph into a small pixel art image',secondary:['choose pixel grid and palette','avoid blur and colour loss','export indexed or animated pixel art'],goal:'a deliberate small raster with visible square cells',input:'a photograph or other still image, or a GIF/APNG for the Studio',output:'a native-size PNG, optionally PNG-8, scaled PNG, .aseprite or GIF from the Studio',support:'partial',evidence:['tests/pixel-converter-browser.py and tests/pixel-converter-firefox.py','tests/pixel-converter-quality.py with two CC0 photographs','docs/PIXEL-CONVERTER-RESULTS.md']},
 en:{
  answer:'To turn a photograph into pixel art, choose the native output grid first, then reduce the colours and inspect the result at whole-number zoom. Nerulio’s quick converter on this page makes a square PNG; Pixel Studio opens from the link above for separate width and height, area-average or median cell sampling, a shared palette, dithering and animated exports. A 32 × 24 image has only 768 cells: a face or thin object may need a different crop or a larger grid. The source stays in the browser and is retained when Studio creates a new sprite.',
  concept:{body:['Downsampling replaces many source pixels with one output cell. Area-average (Box) uses the covered region and keeps broad colour and lightness; median can keep a thin edge more distinct but may shift an area’s tone. Nearest keeps a single sample and can miss small features. Pick the crop before reducing a photo.','Palette reduction then chooses at most the requested number of colours. Pixel Studio defaults to a Wu variance palette at 16 colours. Floyd–Steinberg and Atkinson spread quantisation error between cells; ordered Bayer and blue-noise masks vary the threshold spatially. Dither adds texture, so turn it off for a clean silhouette or flat icon.'],terms:[['Native grid','The actual PNG dimensions, for example 32 × 24; a large nearest-neighbour preview does not add detail.'],['Shared palette','One colour table used by every frame of a GIF/APNG import; it prevents frame-to-frame palette changes.']]},
  example:{lead:'A 1024 × 768 CC0 flower photo was converted to a 32 × 24 grid with 16 colours and no dither in Chromium. The area-average/Wu result was independently reopened as PNG and compared to a Box-resized reference:',lines:['1024 × 768 source → 32 × 24 output = 768 cells','16-colour Wu palette; Box sampler; dither off','RGB RMSE against Box reference: Nerulio 6.30','ImagePixel Original palette 7.97; Pixel Art Village auto 6.76'],after:'These are one-photo, matched-size measurements, not a ranking of artistic quality. The contact sheet shows the Box version keeps broad tones while thin stems are softer. On a second CC0 portrait at 32 × 21, Box/Wu had RMSE 5.25 versus 14.73 for Median/Wu against that same Box reference; inspect the silhouette too.'},
  mapping:{head:['Decision','Choice here','Effect'],rows:[['Canvas shape','Quick converter: square 8–512; Pixel Studio: separate width and height up to 512','Choose 32 × 24 for a 4:3 photo instead of stretching it to 32 × 32'],['Cell sampling','Box, median, nearest, mode or k-centroid in Studio','Box blends covered pixels; median can preserve some edges'],['Colours','Automatic or fixed palette; 2–256 colours in Studio','A smaller palette simplifies shading but can merge objects'],['Preview and size','Nearest preview; 2–16× nearest PNG export in Studio','The native cells stay unchanged; only the display or exported pixel blocks grow']]},
  outputs:{lead:'Save the smallest useful source first. Pixel Studio can also write the following files:',rows:[['PNG','True-colour native grid; reopen it to check the dimensions and pixels'],['PNG-8','Indexed palette PNG when that option is enabled; transparency has palette limits'],['.aseprite','Editable animated sprite; six-frame fixture reopened in Aseprite 1.3.18.6'],['GIF','Animated frames with a shared palette and finite loop choice; GIF has 1-bit transparency and limited colours']]},
  target:{title:'From photo to a usable game sprite',steps:['Open a JPG or PNG here; use the Studio link above when you need a rectangle or animation.','Crop or position the subject so it fills the intended 32 × 24 or 32 × 32 frame. Set width and height before choosing colours.','Start with Box sampling, Wu, 16 colours and no dither. Inspect small features, then compare median sampling or a larger grid if a feature disappears.','Apply as a new sprite, keep the source, and export the native PNG. Choose 2–16× nearest PNG only when a larger pixel-block image is required.']},
  verify:{lead:'Check both data and appearance:',steps:['Reopen the PNG and verify exact native dimensions and palette count; a 32 × 24 result is 768 pixels, not the enlarged preview size.','Compare at 1× and whole-number zoom. Look for lost eyes, outlines or thin stems; undo and change the crop, sampler or grid if they matter.','For GIF/APNG, step through every frame and check timing and the finite loop setting after export.']},
  trouble:{rows:[['Face or thin line disappears','Too few output cells or crop too wide','Compare 1× with the source and count cells across the feature','Tighten crop or increase width and height; try median sampling'],['Muddy colours','Palette too small or Box blending neighbouring colours','View a 1× preview with dither off','Increase colours or use a fixed palette matched to the scene'],['Noisy speckles','Dither strength too high for the target size','Toggle dither off and compare','Lower strength or use no dither'],['Animation flickers','Frames were reduced with different per-frame colours','Inspect successive frames and exported palette','Use Studio all-frame conversion with one shared palette']]},
  alternatives:{rows:[['Draw or touch up in [[game/pixel-art-editor|Pixel Editor]]','Use when a character needs deliberate anatomy or a strict silhouette; automatic conversion cannot make those choices'],['Recover enlarged dot art with [[game/fix-ai-pixel-art|Fix AI pixel art]]','Use when the input was already pixel art but has uneven blocks or anti-aliasing, rather than a photograph']]},
  limits:{items:['Automatic conversion does not draw missing details or guarantee a pleasing pixel-art style; the chosen crop and hand edits still matter.','The observed 4K conversion timing was measured in desktop Chromium. A 390 px emulated viewport is not a physical-phone performance guarantee; Studio guards mobile input separately.','Browser colour management, metadata and profiles are not promised to survive. GIF is palette-limited and can change colours on export.']},
  versions:{body:['Nerulio Pixel Studio was checked in Chromium 153 and Firefox 155 on CC0 photographs in 2026-09. PNG-8, GIF and .aseprite were independently reopened in the Chromium test; the Firefox gate covers photo PNG and source preservation. Two CC0 photo types and a 69-case restoration corpus were measured. Format behaviour follows the official PNG/GIF specifications and Aseprite export documentation.'],sources:sources.en}
 },
 ko:{
  answer:'사진을 도트 그림으로 바꾸려면 먼저 실제 출력 격자를 정하고 색을 줄인 다음 정수 배율로 확인하세요. 이 페이지의 빠른 변환기는 정사각형 PNG를 만듭니다. 위의 Pixel Studio 링크에서는 가로·세로를 따로 지정하고 면적 평균 또는 중앙값 샘플링, 공통 팔레트, 디더링과 애니메이션 출력을 쓸 수 있습니다. 32 × 24 이미지는 768칸뿐이라 얼굴이나 가는 물체가 사라지면 영역을 다시 잡거나 격자를 키워야 합니다. 원본은 브라우저에 남고 Studio가 새 스프라이트를 추가합니다.',
  concept:{body:['축소는 원본의 여러 픽셀을 결과 한 칸으로 합칩니다. 면적 평균(Box)은 넓은 색과 명암을 유지하고, 중앙값은 가는 윤곽을 더 뚜렷하게 남길 수 있지만 넓은 영역의 색이 바뀔 수 있습니다. 최근접은 원본 한 점만 골라 작은 요소를 놓치기도 합니다. 사진을 줄이기 전에 구도를 정하세요.','팔레트 축소는 요청한 수 이하의 색을 고릅니다. Pixel Studio 기본값은 16색 Wu 분산 팔레트입니다. Floyd–Steinberg·Atkinson은 색 오차를 이웃 칸에 퍼뜨리고 Bayer·블루 노이즈는 위치마다 임계값을 달리합니다. 디더링은 질감을 더하므로 단순한 아이콘은 끄고 비교하세요.'],terms:[['원본 격자','실제 PNG 크기입니다. 큰 최근접 미리보기는 디테일을 늘리지 않습니다.'],['공통 팔레트','GIF/APNG 입력의 모든 프레임이 한 색표를 공유해 프레임 간 색 변화를 줄입니다.']]},
  example:{lead:'CC0 꽃 사진 1024 × 768을 디더링 없이 32 × 24, 16색으로 변환했습니다. PNG를 독립 프로그램으로 다시 열고 Box 축소 참조와 비교했습니다:',lines:['1024 × 768 원본 → 32 × 24 출력 = 768칸','16색 Wu 팔레트, Box 샘플링, 디더링 끔','Box 참조 대비 RGB RMSE: Nerulio 6.30','ImagePixel Original 팔레트 7.97, Pixel Art Village 자동 6.76'],after:'같은 사진·크기로 맞춘 한 사례의 수치이며 예술적 품질 순위가 아닙니다. 접촉 시트에서 Box는 넓은 명암을 유지하지만 가는 줄기는 부드러워졌습니다. 다른 CC0 인물 사진 32 × 21에서는 같은 Box 참조 대비 Box/Wu 5.25, Median/Wu 14.73이었고 윤곽도 따로 봐야 합니다.'},
  mapping:{head:['결정','설정','영향'],rows:[['화면 비율','빠른 변환기: 정사각 8–512; Studio: 가로·세로 별도 최대 512','4:3 사진은 32 × 32로 늘리지 말고 32 × 24를 고를 수 있습니다'],['칸 샘플링','Studio의 Box·중앙값·최근접·최빈값·k-중심','Box는 영역을 평균내고 중앙값은 일부 경계를 남깁니다'],['색상','자동 또는 고정 팔레트; Studio 2–256색','색을 줄이면 단순해지지만 피사체가 합쳐질 수 있습니다'],['미리보기와 크기','최근접 미리보기; Studio 2–16배 최근접 PNG','원본 칸은 그대로이고 보이거나 저장되는 블록만 커집니다']]},
  outputs:{lead:'가장 작은 원본 크기 결과부터 저장하세요. Studio에는 다음 출력도 있습니다:',rows:[['PNG','실제 격자의 트루컬러 파일; 크기와 픽셀을 재열기로 확인'],['PNG-8','옵션을 켠 경우 인덱스 팔레트 PNG; 투명도에 팔레트 제약 있음'],['.aseprite','편집 가능한 애니메이션; 여섯 프레임 시험 파일을 Aseprite 1.3.18.6에서 다시 열어 확인'],['GIF','공통 팔레트와 반복 횟수 선택이 있는 애니메이션; 투명도는 1비트이며 색 수 제한 있음']]},
  target:{title:'사진에서 게임 스프라이트까지',steps:['여기서 JPG 또는 PNG를 엽니다. 직사각형이나 애니메이션은 위 Studio 링크를 사용하세요.','피사체가 32 × 24 또는 32 × 32 영역을 채우도록 구도를 잡고 색 수보다 먼저 가로·세로를 정합니다.','Box·Wu·16색·디더링 끔으로 시작해 작은 특징을 확인합니다. 사라지면 중앙값이나 큰 격자와 비교합니다.','새 스프라이트로 적용해 원본을 남기고 실제 격자 PNG를 저장합니다. 큰 블록 파일이 필요할 때만 2–16배 최근접 PNG를 고릅니다.']},
  verify:{lead:'데이터와 보이는 결과를 둘 다 확인하세요:',steps:['PNG를 다시 열어 실제 크기와 색 수를 봅니다. 32 × 24는 확대 미리보기가 아닌 768픽셀입니다.','1배와 정수 배율에서 눈·윤곽·가는 줄기를 원본과 비교합니다. 중요한 부분이 사라지면 실행 취소 후 구도·샘플러·격자를 바꿉니다.','GIF/APNG는 모든 프레임과 시간, 저장된 반복 횟수를 확인합니다.']},
  trouble:{rows:[['얼굴이나 가는 선이 사라짐','출력 칸이 적거나 구도가 너무 넓음','1배 결과와 원본을 비교하고 특징이 차지하는 칸을 세기','구도를 좁히거나 가로·세로 확대, 중앙값 시도'],['색이 탁함','팔레트가 작거나 Box가 인접 색을 합침','디더링을 끄고 1배로 보기','색 수를 늘리거나 장면에 맞는 고정 팔레트 선택'],['점이 너무 많음','디더링 강도가 목표 크기에 비해 높음','디더링을 꺼서 비교','강도를 낮추거나 디더링 끄기'],['애니메이션 색이 깜박임','프레임별 색 선택이 다름','연속 프레임과 출력 팔레트 확인','Studio에서 전체 프레임을 한 공통 팔레트로 변환']]},
  alternatives:{rows:[['[[game/pixel-art-editor|도트 에디터]]에서 직접 그리거나 손보기','캐릭터의 형태와 윤곽을 의도적으로 결정해야 할 때'],['[[game/fix-ai-pixel-art|확대 도트 복원]]','사진이 아니라 이미 도트였던 입력의 불균일한 블록이나 안티앨리어싱을 정리할 때']]},
  limits:{items:['자동 변환은 없어진 세부 형태를 그리지 못하며 보기 좋은 도트 양식을 보장하지 않습니다. 구도 선택과 수작업이 필요할 수 있습니다.','4K 변환 시간은 데스크톱 Chromium 측정입니다. 390px 가상 화면은 실제 휴대폰 성능 증거가 아니며 Studio에는 별도 모바일 입력 가드가 있습니다.','브라우저 색 관리·메타데이터·프로필 보존은 보장하지 않습니다. GIF는 팔레트 제한으로 저장 후 색이 달라질 수 있습니다.']},
  versions:{body:['2026년 9월 CC0 사진으로 Chromium 153·Firefox 155의 Pixel Studio를 확인했습니다. PNG-8·GIF·.aseprite는 Chromium 시험에서 독립 재열기했고 Firefox에서는 사진 PNG와 원본 보존을 확인했습니다. CC0 사진 두 종류와 도트 복원 69개도 측정했습니다. 형식 설명은 PNG·GIF 공식 사양과 Aseprite 문서를 따릅니다.'],sources:sources.ko}
 },
 ja:{
  answer:'写真をドット絵に変換するには、まず出力する実際のグリッドを決め、色数を減らして整数倍率で確認します。このページの簡易変換は正方形のPNGを作ります。上のPixel Studioリンクでは幅と高さを別々に指定し、面積平均または中央値のサンプリング、共通パレット、ディザリング、アニメーション出力を使えます。32 × 24は768セルしかありません。顔や細い物が消える場合は切り抜く範囲を変えるかグリッドを大きくしてください。元画像はブラウザに残り、Studioは新しいスプライトを追加します。',
  concept:{body:['縮小では元画像の複数ピクセルを出力の1セルにまとめます。面積平均（Box）は広い色と明暗を保ち、中央値は細い輪郭を残しやすい場合がありますが、広い領域の色が変わることもあります。ニアレストは1点だけを選び、小さな特徴を見落とす場合があります。縮小前に構図を決めます。','パレット削減は指定数以下の色を選びます。Pixel Studioの初期値は16色のWu分散パレットです。Floyd–SteinbergとAtkinsonは誤差を隣のセルに配り、Bayerとブルーノイズは位置ごとに閾値を変えます。ディザリングは模様も増やすため、単純なアイコンではオフとも比べてください。'],terms:[['ネイティブグリッド','PNGそのものの寸法です。大きなニアレスト表示で細部は増えません。'],['共通パレット','GIF/APNG入力の全フレームが一つの色表を共有し、フレームごとの色変化を抑えます。']]},
  example:{lead:'CC0の花の写真1024 × 768を、ディザリングなしで32 × 24・16色にしました。PNGを別のプログラムで開き、Box縮小の参照画像と比較しました:',lines:['1024 × 768 元画像 → 32 × 24 出力 = 768セル','16色Wuパレット、Boxサンプリング、ディザリングなし','Box参照に対するRGB RMSE: Nerulio 6.30','ImagePixel Originalパレット 7.97、Pixel Art Village自動 6.76'],after:'同じ写真・寸法で比較した一例で、芸術的な品質順位ではありません。コンタクトシートではBoxは広い明暗を保ちますが、細い茎は柔らかくなりました。別のCC0人物写真32 × 21では同じBox参照に対しBox/Wuは5.25、Median/Wuは14.73でした。輪郭は別に確認してください。'},
  mapping:{head:['決めること','設定','結果'],rows:[['画面比率','簡易変換: 正方形8–512; Studio: 幅と高さを個別に最大512','4:3写真を32 × 32に伸ばさず32 × 24にできます'],['セルのサンプリング','StudioのBox・中央値・ニアレスト・最頻値・k中心','Boxは領域を平均し、中央値は一部の輪郭を保ちます'],['色数','自動または固定パレット; Studioで2–256色','色を減らすと単純になりますが、物体が背景に溶けることもあります'],['表示と保存寸法','ニアレストの表示; Studioで2–16倍のPNG出力','元のセルは同じで表示または保存するブロックだけ大きくなります']]},
  outputs:{lead:'まず最小のネイティブ出力を保存します。Studioには次の形式もあります:',rows:[['PNG','実際のグリッドのフルカラー画像; 開き直して寸法と画素を確認'],['PNG-8','有効時にインデックスパレットで保存; 透過にはパレットの制約があります'],['.aseprite','編集可能なアニメーション; 6フレームの試験ファイルをAseprite 1.3.18.6で再読み込み'],['GIF','共通パレットと有限ループの選択があるアニメーション; 透過は1ビットで色数に制約があります']]},
  target:{title:'写真からゲーム用スプライトまで',steps:['ここでJPGまたはPNGを開きます。長方形やアニメーションには上のStudioリンクを使います。','被写体が32 × 24または32 × 32の枠を満たすよう構図を調整し、色数より先に幅と高さを決めます。','Box・Wu・16色・ディザリングなしから始め、細部を確認します。消える場合は中央値や大きなグリッドと比べます。','新しいスプライトとして適用し元画像を残してネイティブPNGを書き出します。大きなブロック画像が必要な時だけ2–16倍のニアレストPNGを選びます。']},
  verify:{lead:'データと見た目を両方確認します:',steps:['PNGを開き直し、実際の寸法と色数を確認します。32 × 24は拡大表示ではなく768画素です。','1倍と整数倍率で目・輪郭・細い茎を元画像と比較します。必要な部分が消えたら元に戻し、構図・サンプラー・グリッドを変えます。','GIF/APNGでは全フレーム、時間、書き出したループ回数を確認します。']},
  trouble:{rows:[['顔や細い線が消える','出力セルが少ない、または構図が広い','1倍画像と元画像を比べ特徴が何セルに収まるか数える','構図を狭めるか幅と高さを増やし、中央値も試す'],['色が濁る','色数が少ないかBoxが隣接色を混ぜる','ディザリングなしで1倍表示を確認','色数を増やすか場面に合う固定パレットを選ぶ'],['点が多すぎる','目標寸法に対してディザリングが強い','オフにして比較','強度を下げるかオフにする'],['アニメーションの色がちらつく','フレームごとに選ばれた色が異なる','連続フレームと出力パレットを確認','Studioで全フレームを一つの共通パレットで変換']]},
  alternatives:{rows:[['[[game/pixel-art-editor|ドット絵エディタ]]で描く・手直しする','キャラクターの形や輪郭を自分で決めたい場合'],['[[game/fix-ai-pixel-art|拡大ドット絵の修復]]','写真ではなく、すでにドット絵だった画像の不揃いなブロックやアンチエイリアスを直す場合']]},
  limits:{items:['自動変換は失われた細部を描き足せず、好みのドット絵表現も保証しません。構図の選択や手作業が必要なことがあります。','4K変換時間はデスクトップChromiumでの測定です。幅390pxの仮想画面は実機スマートフォンの性能証明ではありません。Studioには別のモバイル入力制限があります。','ブラウザの色管理、メタデータ、プロファイルの保存は保証しません。GIFはパレット制約により書き出し後に色が変わる場合があります。']},
  versions:{body:['2026年9月にCC0写真を使ってChromium 153とFirefox 155のPixel Studioを確認しました。PNG-8・GIF・.asepriteはChromium試験で別のプログラムから再読み込みし、Firefoxでは写真PNGと元画像の保持を確認しました。CC0写真2種類とドット修復69例も測定しました。形式の説明はPNG・GIFの公式仕様とAsepriteの文書に基づきます。'],sources:sources.ja}
 }
 }
};
