/** Intent content for the sprite → engine pages (docs/SEO-CONTENT-MODEL.md). Keys are canonical paths.
 * Nerulio behaviour: src/game/export/godot.js, src/game/aseprite.js, src/game/model.js, docs/STUDIO-PACK.md,
 * docs/STUDIO-SPRITE.md. Engine behaviour: the official docs cited in each page's `versions.sources`. */
const GODOT_DOCS=['[Godot 4.7 docs: AnimatedSprite2D](https://docs.godotengine.org/en/stable/classes/class_animatedsprite2d.html)','[Godot 4.7 docs: SpriteFrames](https://docs.godotengine.org/en/stable/classes/class_spriteframes.html)','[Godot 4.7 docs: 2D sprite animation](https://docs.godotengine.org/en/stable/tutorials/2d/2d_sprite_animation.html)'];
export default {
 'game/aseprite-to-godot':{
  type:'conversion',
  intent:{primary:'convert an .aseprite file into a working Godot 4 animated sprite',secondary:['keep tags and per-frame timing','pixel-art import settings in Godot','no Aseprite install or Godot plugin'],
   goal:'an AnimatedSprite2D in Godot 4 that plays every Aseprite tag at the timing drawn in Aseprite',input:'.aseprite / .ase file (tags optional; layers, slices optional)',output:'SpriteFrames .tres + packed PNG + AnimatedSprite2D .tscn + .png.import + README',target:'Godot 4 (verified 4.7.2)',support:'full',
   evidence:['src/game/export/godot.js','src/game/aseprite.js (tags → animations, fps from average duration)','docs/STUDIO-PACK.md (Godot 4.7.2 engine-verify runs)','docs/STUDIO-SPRITE.md §10 (231-file .aseprite corpus)'],
   external:['Godot 4.7 docs: SpriteFrames relative duration and FPS formula','AnimatedSprite2D properties and play()','Aseprite docs: tags, Export Sprite Sheet']},
  en:{
   answer:'An `.aseprite` file holds frames with their own durations in milliseconds, tags (named frame ranges with a direction and repeat count), layers and slices. Godot 4 cannot open it directly: it plays a `SpriteFrames` resource on an `AnimatedSprite2D`. Nerulio reads the file in your browser, turns every tag into a `SpriteFrames` animation with the same timing, packs the frames into one PNG and adds a ready scene. Copy the folder under `res://`, drop the `.tscn` into your scene, and the first tag plays with Nearest filtering. Godot 4 only (checked in 4.7.2).',
   concept:{title:'What is in an .aseprite file, and what Godot needs',body:[
    'Aseprite saves a whole animation document. Every frame has its own duration in milliseconds. Tags group a range of frames into a named animation (`walk` = frames 4–9) and say how it plays: forward, reverse or ping-pong, forever or a set number of times. Layers keep parts of the drawing apart, and slices mark rectangles such as a pivot point or a hit box.',
    'Godot 4 plays frame animation with an `AnimatedSprite2D` node that reads a `SpriteFrames` resource. Each animation in it has a name, a speed in frames per second, a loop flag and a list of frames; each frame is a texture plus a relative duration. Godot shows a frame for relative duration ÷ (FPS × speed scale) seconds, so milliseconds have to be converted, not copied.',
    'Nerulio picks each animation\'s FPS as 1000 ÷ the average frame duration of the tag and writes every frame\'s duration relative to it, so the playback time of every single frame matches Aseprite even when the durations differ inside one tag.'],
    terms:[['Tag','A named frame range in Aseprite with a direction (forward, reverse, ping-pong) and a repeat count.'],['SpriteFrames','The Godot resource that stores animations: name, speed (FPS), loop and frames.'],['AtlasTexture','A rectangle of a larger texture. Every exported frame is one, pointing into the packed PNG.'],['Relative duration','Godot\'s per-frame multiplier: 1.0 lasts one tick of the animation\'s FPS, 2.0 two ticks.']]},
   example:{title:'Example: a 32 × 32 hero with three tags',lead:'The .aseprite file has 16 frames and three tags. This is what the export writes into the SpriteFrames resource:',lines:[
    'Aseprite                                  Godot 4 SpriteFrames',
    'idle    frames 0–3    125 ms each   ∞     idle    8 FPS    1.0 × 4                       loop on',
    'walk    frames 4–9    100 ms each   ∞     walk    10 FPS   1.0 × 6                       loop on',
    'attack  frames 10–15  100,100,100,100,    attack  7.5 FPS  0.75, 0.75, 0.75, 0.75,        loop off',
    '                      150, 250 ms   ×1                     1.125, 1.875',
    '',
    'attack FPS  = 1000 / average(100,100,100,100,150,250) = 1000 / 133.3 = 7.5',
    'check       0.75 / 7.5 = 0.100 s    1.875 / 7.5 = 0.250 s   (same as Aseprite)'],
    after:'`attack` repeats once in Aseprite, so its loop flag is off: it plays once and stays on its last frame. In a script, play `idle` again from the node\'s `animation_finished` signal.'},
   mapping:{title:'What survives the conversion',head:['In Aseprite','In Nerulio','In Godot 4'],rows:[
    ['Frame pixels (visible layers)','Composited frame, packed into one PNG page','An `AtlasTexture` region of that PNG'],
    ['Frame duration (ms)','Kept per frame','Relative duration; the animation speed is 1000 ÷ the tag\'s average duration'],
    ['Tag','One animation of the same name','A `SpriteFrames` animation of the same name'],
    ['Direction reverse / ping-pong','Playback order written out (ping-pong: 0-1-2-3-2-1)','Frames listed in that order'],
    ['Repeat ∞','Loop','`loop = true`'],
    ['Repeat 1, 2, 3…','Plays that many times in the preview','`loop = false`: Godot plays it once (a repeat count is not stored)'],
    ['No tags at all','One animation `default` with every frame','Animation `default`'],
    ['Slice with a pivot','Frame pivot (default without one: bottom centre)','Node `offset` = −pivot of the first frame, `centered = false`'],
    ['Slices named hit / hurt …','Boxes per frame','Stored in the resource metadata `nerulio`, not as nodes'],
    ['Layers, blend modes, opacity','Kept in the Studio','Flattened: Godot receives the composited frame']],
    note:'Godot 4.7 also has a ping-pong loop mode of its own; the export does not depend on it because it writes the order frame by frame.'},
   outputs:{rows:[
    ['hero.tres','The `SpriteFrames` resource: animations, FPS, loop flags, relative durations, `AtlasTexture` regions and trim margins; metadata `nerulio` with pivots, boxes and collision polygons.'],
    ['hero.tscn','A scene with one `AnimatedSprite2D` using the resource: Nearest filtering, autoplay of the first tag, the pivot as offset.'],
    ['hero.png','The packed frames (more pages when the frames do not fit on one).'],
    ['hero.png.import','Import settings Godot reads: lossless, no mipmaps, Fix Alpha Border off, so faint pixels keep their colour.'],
    ['README-GODOT.md','These steps for this bundle.']]},
   target:{title:'Import it into Godot 4',steps:[
    'Unzip the bundle and copy the whole folder anywhere under `res://`, for example `res://characters/hero/`. The `.tres` finds the PNG by a relative path, so keep the files together.',
    'Let the FileSystem dock finish importing. Godot uses the shipped `hero.png.import`, so the atlas is imported lossless and without mipmaps.',
    'Drag `hero.tscn` into your scene, or select your own `AnimatedSprite2D` and load `hero.tres` into its Sprite Frames property.',
    'Choose the animation in the node\'s Animation property or in the SpriteFrames panel; the shipped scene autoplays the first tag.',
    'From a script, switch with `$Hero.play("walk")`. For a tag that does not loop, connect `animation_finished` and play `idle` again.',
    'For your own nodes, set Project Settings › Rendering › Textures › Canvas Textures › Default Texture Filter to Nearest once, or set the node\'s Texture › Filter to Nearest.']},
   verify:{steps:[
    'Run the scene: `walk` with six 100 ms frames should repeat every 0.6 s, the same as Aseprite\'s preview.',
    'Open the SpriteFrames panel: every animation has the frame count of its tag (a ping-pong tag shows the written-out order).',
    'Zoom the 2D viewport to 400 %: pixel edges stay square. Soft edges mean the node uses Linear filtering.',
    '`print($Hero.sprite_frames.get_meta("nerulio"))` lists the pivot and boxes of every frame.']},
   trouble:{rows:[
    ['The sprite looks blurry','Your node inherits the project\'s default Linear filter','Zoom in; check the node\'s Texture › Filter','Set Filter to Nearest on the node, or the project\'s Default Texture Filter to Nearest'],
    ['Faint pixels (glow, smoke) change colour','The PNG was imported with Godot\'s default Fix Alpha Border instead of the shipped `.png.import`','Import dock of the PNG: Fix Alpha Border is on','Keep `hero.png.import` next to the PNG, or turn Fix Alpha Border off and click Reimport'],
    ['A tag is missing','The file had no tags (everything became `default`), or the tag was renamed or removed before export','Look at the tag lanes on Nerulio\'s timeline before exporting','Add or fix the tag in Aseprite or on the timeline, then export again'],
    ['A play-once tag loops, or a looping tag stops','Repeat ∞ becomes loop on; any repeat count becomes loop off','SpriteFrames panel: the loop toggle of that animation','Change the repeat in the tag, or toggle Loop in Godot; use `animation_finished` for play-once tags'],
    ['The character jumps when the animation changes','Frames have different pivots, but a node has one offset (the first frame\'s pivot)','The export notes warn about differing pivots; every pivot is in `metadata/nerulio`','Use one pivot slice for all frames, or align pivots in Nerulio (see [[game/sprite-pivot-editor|the pivot editor]]) before export'],
    ['Timing is faster or slower than in Aseprite','The node\'s Speed Scale or a `play()` custom speed is not 1','Inspector: Speed Scale','Set Speed Scale to 1 and call `play()` without a custom speed'],
    ['Godot 3 cannot open the .tres','The resource uses the Godot 4 format with per-frame durations','—','Use Godot 4, or export a plain [[game/aseprite-to-sprite-sheet|PNG sprite sheet]] and build the frames by hand in Godot 3']]},
   alternatives:{rows:[
    ['Export a PNG sheet from Aseprite (File › Export Sprite Sheet) and use Add Frames from Sprite Sheet in Godot\'s SpriteFrames panel','One or two animations with even timing: no extra files, but you set each animation\'s FPS by hand and per-frame durations are lost. See [[game/godot-sprite-sheet|using a sprite sheet in Godot]].'],
    ['An .aseprite import plugin from the Godot Asset Library','You change the art often and want Godot to reimport on every save; such plugins call the Aseprite program, so it must be installed on every machine that imports.'],
    ['The same file for another engine','[[game/aseprite-to-unity|Aseprite to Unity]] or [[game/aseprite-to-phaser|Aseprite to Phaser]].']]},
   limits:['A repeat count above one is not stored: Godot plays such an animation once.','Layers arrive flattened; to animate parts separately in Godot, export them as separate files.','Hit and hurt boxes are data in the resource metadata; create the `Area2D` and `CollisionShape2D` nodes yourself.'],
   versions:{body:['Nerulio\'s bundle was loaded by Godot 4.7.2 in our verification runs: every animation\'s frame count, speed, loop and relative durations were read back and every frame was drawn at 1× and 4× and compared with the source. The .aseprite reader was checked on 231 real files that reopened in Aseprite 1.3.18 with the same tags, durations and pixels. What the steps above say about Godot follows the Godot 4.7 documentation.'],sources:[...GODOT_DOCS,'[Aseprite docs: Tags](https://www.aseprite.org/docs/tags/)']}
  },
  ko:{
   answer:'`.aseprite` 파일에는 프레임마다 밀리초 단위 길이, 태그(방향과 반복 횟수가 있는 이름 붙은 프레임 구간), 레이어, 슬라이스가 들어 있습니다. Godot 4는 이 파일을 직접 열지 못하고 `AnimatedSprite2D`에서 `SpriteFrames` 리소스를 재생합니다. Nerulio는 브라우저에서 파일을 읽어 태그마다 같은 타이밍의 `SpriteFrames` 애니메이션을 만들고, 프레임을 PNG 한 장에 패킹하고, 바로 쓸 수 있는 씬을 붙여 줍니다. 폴더를 `res://` 아래에 복사하고 `.tscn`을 씬에 넣으면 첫 태그가 Nearest 필터로 재생됩니다. Godot 4 전용이며 4.7.2에서 확인했습니다.',
   concept:{title:'.aseprite 파일에 든 것과 Godot가 필요로 하는 것',body:[
    'Aseprite는 애니메이션 문서 전체를 저장합니다. 프레임마다 길이(ms)가 따로 있고, 태그는 프레임 구간에 이름을 붙여 하나의 애니메이션으로 묶으며(`walk` = 4~9번 프레임) 재생 방식도 정합니다. 정방향·역방향·핑퐁, 무한 반복 또는 정해진 횟수입니다. 레이어는 그림의 부분을 나눠 두고, 슬라이스는 피벗 위치나 히트박스 같은 사각형을 표시합니다.',
    'Godot 4에서 프레임 애니메이션은 `AnimatedSprite2D` 노드가 `SpriteFrames` 리소스를 읽어 재생합니다. 애니메이션마다 이름, 초당 프레임 수(FPS), 반복 여부, 프레임 목록이 있고 프레임은 텍스처와 상대 길이로 이뤄집니다. Godot는 한 프레임을 상대 길이 ÷ (FPS × 속도 배율)초 동안 보여 주므로, 밀리초 값을 그대로 옮기면 안 되고 변환해야 합니다.',
    'Nerulio는 애니메이션의 FPS를 1000 ÷ 태그 안 프레임 길이의 평균으로 정하고 각 프레임의 길이를 그 기준에 대한 상대값으로 씁니다. 그래서 한 태그 안에서 길이가 제각각이어도 프레임 하나하나의 재생 시간이 Aseprite와 같습니다.'],
    terms:[['태그','Aseprite에서 방향(정방향·역방향·핑퐁)과 반복 횟수가 있는, 이름 붙은 프레임 구간.'],['SpriteFrames','애니메이션의 이름·속도(FPS)·반복·프레임을 저장하는 Godot 리소스.'],['AtlasTexture','큰 텍스처의 사각 영역. 내보낸 프레임 하나하나가 패킹된 PNG의 한 영역을 가리킵니다.'],['상대 길이','Godot의 프레임별 배수. 1.0은 애니메이션 FPS의 한 틱, 2.0은 두 틱 동안 표시됩니다.']]},
   example:{title:'예시: 태그 3개가 있는 32 × 32 캐릭터',lead:'프레임 16개와 태그 3개가 있는 .aseprite 파일을 내보내면 SpriteFrames에 다음 값이 들어갑니다.',lines:[
    'Aseprite                                  Godot 4 SpriteFrames',
    'idle    프레임 0–3    각 125 ms      ∞     idle    8 FPS    1.0 × 4                       loop on',
    'walk    프레임 4–9    각 100 ms      ∞     walk    10 FPS   1.0 × 6                       loop on',
    'attack  프레임 10–15  100,100,100,100,    attack  7.5 FPS  0.75, 0.75, 0.75, 0.75,        loop off',
    '                      150, 250 ms   ×1                     1.125, 1.875',
    '',
    'attack FPS = 1000 / 평균(100,100,100,100,150,250) = 1000 / 133.3 = 7.5',
    '검산        0.75 / 7.5 = 0.100초    1.875 / 7.5 = 0.250초   (Aseprite와 동일)'],
    after:'`attack`은 Aseprite에서 한 번만 재생하도록 되어 있어 반복이 꺼집니다. 한 번 재생된 뒤 마지막 프레임에 멈추므로, 스크립트에서 노드의 `animation_finished` 시그널을 받아 `idle`을 다시 재생하세요.'},
   mapping:{title:'변환 후에도 남는 것',head:['Aseprite','Nerulio','Godot 4'],rows:[
    ['프레임 픽셀(보이는 레이어)','합성한 프레임을 PNG 한 페이지에 패킹','그 PNG의 `AtlasTexture` 영역'],
    ['프레임 길이(ms)','프레임마다 유지','상대 길이. 애니메이션 속도는 1000 ÷ 태그의 평균 길이'],
    ['태그','같은 이름의 애니메이션 하나','같은 이름의 `SpriteFrames` 애니메이션'],
    ['방향: 역방향·핑퐁','재생 순서를 풀어서 기록(핑퐁: 0-1-2-3-2-1)','그 순서대로 나열된 프레임'],
    ['반복 ∞','반복 재생','`loop = true`'],
    ['반복 1, 2, 3…','미리보기에서 그 횟수만큼 재생','`loop = false`: Godot에서는 한 번 재생(반복 횟수는 저장되지 않음)'],
    ['태그가 하나도 없음','모든 프레임으로 된 애니메이션 `default` 하나','애니메이션 `default`'],
    ['피벗이 있는 슬라이스','프레임 피벗(없으면 기본값: 하단 중앙)','노드 `offset` = −첫 프레임 피벗, `centered = false`'],
    ['hit / hurt 등의 이름을 가진 슬라이스','프레임별 박스','리소스 메타데이터 `nerulio`에 저장(노드로 만들지 않음)'],
    ['레이어·블렌드 모드·불투명도','Studio에서는 유지','합쳐짐: Godot에는 합성된 프레임이 들어감']],
    note:'Godot 4.7에는 자체 핑퐁 반복 모드도 있지만, 내보내기는 순서를 프레임 단위로 직접 기록하므로 그 기능에 의존하지 않습니다.'},
   outputs:{rows:[
    ['hero.tres','`SpriteFrames` 리소스: 애니메이션, FPS, 반복 여부, 상대 길이, `AtlasTexture` 영역과 트림 여백, 피벗·박스·충돌 폴리곤이 든 메타데이터 `nerulio`.'],
    ['hero.tscn','이 리소스를 쓰는 `AnimatedSprite2D` 하나가 든 씬: Nearest 필터, 첫 태그 자동 재생, 피벗을 오프셋으로 설정.'],
    ['hero.png','패킹된 프레임(한 장에 다 들어가지 않으면 페이지가 늘어남).'],
    ['hero.png.import','Godot가 읽는 가져오기 설정: 무손실, 밉맵 없음, Fix Alpha Border 끔. 흐린 픽셀의 색이 바뀌지 않습니다.'],
    ['README-GODOT.md','이 번들에 맞춘 아래 단계 설명.']]},
   target:{title:'Godot 4로 가져오기',steps:[
    '번들 압축을 풀고 폴더째 `res://` 아래 아무 곳에나 복사합니다(예: `res://characters/hero/`). `.tres`가 상대 경로로 PNG를 찾으므로 파일을 한곳에 두세요.',
    '파일시스템 독이 가져오기를 끝낼 때까지 기다립니다. 함께 들어 있는 `hero.png.import` 설정대로 아틀라스가 무손실·밉맵 없이 들어옵니다.',
    '`hero.tscn`을 씬으로 끌어 놓거나, 직접 만든 `AnimatedSprite2D`를 선택해 Sprite Frames 속성에 `hero.tres`를 지정합니다.',
    '노드의 Animation 속성이나 SpriteFrames 패널에서 애니메이션을 고릅니다. 함께 온 씬은 첫 태그를 자동 재생합니다.',
    '스크립트에서는 `$Hero.play("walk")`로 바꿉니다. 반복하지 않는 태그라면 `animation_finished`를 연결해 `idle`을 다시 재생하세요.',
    '직접 만든 노드에는 프로젝트 설정 › Rendering › Textures › Canvas Textures › Default Texture Filter를 Nearest로 한 번 바꾸거나, 노드의 Texture › Filter를 Nearest로 설정합니다.']},
   verify:{steps:[
    '씬을 실행합니다. 100ms 프레임 6개로 된 `walk`는 Aseprite 미리보기처럼 0.6초마다 반복돼야 합니다.',
    'SpriteFrames 패널을 엽니다. 애니메이션마다 태그의 프레임 수와 같아야 합니다(핑퐁 태그는 풀어 쓴 순서로 보임).',
    '2D 뷰포트를 400%로 확대합니다. 픽셀 경계가 네모나게 유지돼야 하며, 흐리면 노드가 Linear 필터를 쓰는 것입니다.',
    '`print($Hero.sprite_frames.get_meta("nerulio"))`로 프레임마다 피벗과 박스가 나오는지 봅니다.']},
   trouble:{rows:[
    ['스프라이트가 흐리게 보임','노드가 프로젝트 기본 Linear 필터를 물려받음','확대해 보고 노드의 Texture › Filter 확인','노드의 Filter를 Nearest로, 또는 프로젝트의 Default Texture Filter를 Nearest로'],
    ['흐린 픽셀(빛, 연기)의 색이 바뀜','함께 온 `.png.import` 대신 Godot 기본값(Fix Alpha Border 켬)으로 가져옴','PNG의 Import 독에서 Fix Alpha Border가 켜져 있음','`hero.png.import`를 PNG 옆에 두거나, Fix Alpha Border를 끄고 Reimport'],
    ['태그 하나가 없음','파일에 태그가 없어 전부 `default`가 됐거나, 내보내기 전에 태그 이름이 바뀌거나 지워짐','내보내기 전에 Nerulio 타임라인의 태그 줄 확인','Aseprite나 타임라인에서 태그를 고친 뒤 다시 내보내기'],
    ['한 번만 나와야 할 태그가 반복되거나, 반복돼야 할 태그가 멈춤','반복 ∞는 반복 켬, 횟수를 정한 반복은 반복 끔이 됨','SpriteFrames 패널에서 해당 애니메이션의 반복 토글','태그의 반복 값을 바꾸거나 Godot에서 Loop를 전환. 한 번 재생 태그는 `animation_finished` 사용'],
    ['애니메이션이 바뀔 때 캐릭터가 튐','프레임마다 피벗이 다른데 노드의 오프셋은 하나(첫 프레임 피벗)','내보내기 안내에 피벗 불일치 경고가 뜸. 모든 피벗은 `metadata/nerulio`에 있음','모든 프레임에 같은 피벗 슬라이스를 쓰거나, 내보내기 전에 Nerulio에서 피벗을 맞추기([[game/sprite-pivot-editor|피벗 편집기]])'],
    ['Aseprite보다 빠르거나 느림','노드의 Speed Scale이나 `play()`의 사용자 속도가 1이 아님','인스펙터의 Speed Scale','Speed Scale을 1로 두고 `play()`를 사용자 속도 없이 호출'],
    ['Godot 3에서 .tres가 안 열림','프레임별 길이가 있는 Godot 4 형식 리소스','—','Godot 4를 쓰거나, [[game/aseprite-to-sprite-sheet|PNG 스프라이트 시트]]로 내보내 Godot 3에서 프레임을 직접 구성']]},
   alternatives:{rows:[
    ['Aseprite에서 PNG 시트로 내보내고(File › Export Sprite Sheet) Godot SpriteFrames 패널의 Add Frames from Sprite Sheet 사용','애니메이션이 한두 개이고 프레임 길이가 일정할 때. 파일은 적지만 애니메이션마다 FPS를 직접 정해야 하고 프레임별 길이는 사라집니다. [[game/godot-sprite-sheet|Godot에서 스프라이트 시트 쓰기]] 참고.'],
    ['Godot Asset Library의 .aseprite 가져오기 플러그인','그림을 자주 고치고 저장할 때마다 Godot가 다시 가져오게 하고 싶을 때. 이런 플러그인은 Aseprite 프로그램을 호출하므로 가져오는 모든 컴퓨터에 Aseprite가 설치돼 있어야 합니다.'],
    ['같은 파일을 다른 엔진으로','[[game/aseprite-to-unity|Aseprite를 Unity로]], [[game/aseprite-to-phaser|Aseprite를 Phaser로]].']]},
   limits:['반복 횟수가 2 이상이어도 저장되지 않으며 Godot에서는 한 번 재생됩니다.','레이어는 합쳐져서 들어갑니다. Godot에서 부분별로 움직이려면 부분마다 파일을 따로 내보내세요.','히트·허트 박스는 리소스 메타데이터로만 들어갑니다. `Area2D`와 `CollisionShape2D` 노드는 직접 만드세요.'],
   versions:{body:['검증 실행에서 Godot 4.7.2가 Nerulio 번들을 불러와 애니메이션마다 프레임 수·속도·반복·상대 길이를 다시 읽었고, 모든 프레임을 1배와 4배로 그려 원본과 비교했습니다. .aseprite 읽기는 실제 파일 231개로 확인했으며 Aseprite 1.3.18에서 같은 태그·길이·픽셀로 다시 열렸습니다. 위 단계의 Godot 동작은 Godot 4.7 공식 문서를 따릅니다.'],sources:[...GODOT_DOCS,'[Aseprite 문서: Tags](https://www.aseprite.org/docs/tags/)']}
  },
  ja:{
   answer:'`.aseprite`ファイルには、フレームごとのミリ秒単位の長さ、タグ（方向と繰り返し回数を持つ名前付きのフレーム範囲）、レイヤー、スライスが入っています。Godot 4はこのファイルを直接開けず、`AnimatedSprite2D`で`SpriteFrames`リソースを再生します。Nerulioはブラウザでファイルを読み、タグごとに同じタイミングの`SpriteFrames`アニメーションを作り、フレームを1枚のPNGにパックし、すぐ使えるシーンを添えます。フォルダーを`res://`以下にコピーして`.tscn`をシーンに置けば、最初のタグがNearestフィルターで再生されます。Godot 4専用で、4.7.2で確認しています。',
   concept:{title:'.asepriteの中身と、Godotに必要なもの',body:[
    'Asepriteはアニメーションの文書全体を保存します。フレームごとに長さ（ms）があり、タグはフレームの範囲に名前を付けて1つのアニメーションにまとめ（`walk` = 4〜9番）、再生方法も決めます。順方向・逆方向・ピンポン、無限ループか決まった回数かです。レイヤーは絵の部品を分け、スライスはピボット位置やヒットボックスなどの矩形を示します。',
    'Godot 4では、`AnimatedSprite2D`ノードが`SpriteFrames`リソースを読んでフレームアニメーションを再生します。アニメーションごとに名前・毎秒フレーム数（FPS）・ループの有無・フレーム一覧があり、フレームはテクスチャと相対的な長さで構成されます。Godotは1フレームを「相対の長さ ÷（FPS × 速度倍率）」秒表示するため、ミリ秒の値はそのまま写さず換算する必要があります。',
    'NerulioはアニメーションのFPSを「1000 ÷ タグ内のフレームの平均の長さ」とし、各フレームの長さをそれに対する相対値で書きます。そのため1つのタグの中で長さがばらばらでも、1フレームずつの表示時間がAsepriteと一致します。'],
    terms:[['タグ','Asepriteで方向（順・逆・ピンポン）と繰り返し回数を持つ、名前付きのフレーム範囲。'],['SpriteFrames','アニメーションの名前・速度（FPS）・ループ・フレームを保存するGodotのリソース。'],['AtlasTexture','大きなテクスチャの矩形領域。書き出したフレームはそれぞれパック済みPNGの1領域を指します。'],['相対の長さ','Godotのフレームごとの倍率。1.0はFPSの1ティック、2.0は2ティック表示されます。']]},
   example:{title:'例：タグが3つある32 × 32のキャラクター',lead:'16フレームとタグ3つを持つ.asepriteを書き出すと、SpriteFramesには次の値が入ります。',lines:[
    'Aseprite                                  Godot 4 SpriteFrames',
    'idle    フレーム0–3    各125 ms     ∞     idle    8 FPS    1.0 × 4                       loop on',
    'walk    フレーム4–9    各100 ms     ∞     walk    10 FPS   1.0 × 6                       loop on',
    'attack  フレーム10–15  100,100,100,100,   attack  7.5 FPS  0.75, 0.75, 0.75, 0.75,        loop off',
    '                      150, 250 ms   ×1                     1.125, 1.875',
    '',
    'attack FPS = 1000 / 平均(100,100,100,100,150,250) = 1000 / 133.3 = 7.5',
    '検算        0.75 / 7.5 = 0.100秒    1.875 / 7.5 = 0.250秒   （Asepriteと同じ）'],
    after:'`attack`はAsepriteで1回だけ再生する設定なので、ループはオフになります。再生後は最後のフレームで止まるため、スクリプトでノードの`animation_finished`シグナルを受けて`idle`を再生し直してください。'},
   mapping:{title:'変換後に残るもの',head:['Aseprite','Nerulio','Godot 4'],rows:[
    ['フレームのピクセル（表示中のレイヤー）','合成したフレームをPNG 1ページにパック','そのPNGの`AtlasTexture`領域'],
    ['フレームの長さ（ms）','フレームごとに保持','相対の長さ。アニメーション速度は1000 ÷ タグの平均の長さ'],
    ['タグ','同じ名前のアニメーション1つ','同じ名前の`SpriteFrames`アニメーション'],
    ['方向：逆方向・ピンポン','再生順を展開して記録（ピンポン：0-1-2-3-2-1）','その順に並んだフレーム'],
    ['繰り返し ∞','ループ','`loop = true`'],
    ['繰り返し 1、2、3…','プレビューではその回数再生','`loop = false`：Godotでは1回再生（回数は保存されない）'],
    ['タグが1つもない','全フレームのアニメーション`default`を1つ','アニメーション`default`'],
    ['ピボット付きのスライス','フレームのピボット（なければ既定値：下中央）','ノードの`offset` = −最初のフレームのピボット、`centered = false`'],
    ['hit / hurt などの名前のスライス','フレームごとのボックス','リソースのメタデータ`nerulio`に保存（ノードは作らない）'],
    ['レイヤー・合成モード・不透明度','Studioでは保持','統合：Godotには合成済みのフレームが入る']],
    note:'Godot 4.7には独自のピンポンループもありますが、書き出しは順序をフレーム単位で直接書くため、その機能には依存しません。'},
   outputs:{rows:[
    ['hero.tres','`SpriteFrames`リソース：アニメーション、FPS、ループ、相対の長さ、`AtlasTexture`領域とトリム余白、ピボット・ボックス・衝突ポリゴン入りのメタデータ`nerulio`。'],
    ['hero.tscn','このリソースを使う`AnimatedSprite2D`を1つ持つシーン：Nearestフィルター、最初のタグを自動再生、ピボットをオフセットに設定。'],
    ['hero.png','パック済みのフレーム（1枚に収まらなければページが増えます）。'],
    ['hero.png.import','Godotが読むインポート設定：可逆、ミップマップなし、Fix Alpha Borderオフ。薄いピクセルの色が変わりません。'],
    ['README-GODOT.md','このバンドル用の以下の手順。']]},
   target:{title:'Godot 4に取り込む',steps:[
    'バンドルを展開し、フォルダーごと`res://`以下の好きな場所にコピーします（例：`res://characters/hero/`）。`.tres`は相対パスでPNGを探すので、ファイルは一緒に置いてください。',
    'ファイルシステムドックのインポートが終わるのを待ちます。同梱の`hero.png.import`の設定で、アトラスは可逆・ミップマップなしで取り込まれます。',
    '`hero.tscn`をシーンにドラッグするか、自分の`AnimatedSprite2D`を選んでSprite Frames属性に`hero.tres`を読み込みます。',
    'ノードのAnimation属性かSpriteFramesパネルでアニメーションを選びます。同梱のシーンは最初のタグを自動再生します。',
    'スクリプトでは`$Hero.play("walk")`で切り替えます。ループしないタグは`animation_finished`をつないで`idle`を再生し直します。',
    '自分で作ったノードには、プロジェクト設定 › Rendering › Textures › Canvas Textures › Default Texture FilterをNearestに一度変えるか、ノードのTexture › FilterをNearestにします。']},
   verify:{steps:[
    'シーンを実行します。100msのフレーム6枚の`walk`は、Asepriteのプレビューと同じく0.6秒ごとに繰り返すはずです。',
    'SpriteFramesパネルを開きます。各アニメーションのフレーム数がタグと同じはずです（ピンポンのタグは展開した順で表示）。',
    '2Dビューポートを400%に拡大します。ピクセルの境界が四角いままなら正常で、ぼやける場合はノードがLinearフィルターです。',
    '`print($Hero.sprite_frames.get_meta("nerulio"))`でフレームごとのピボットとボックスが出るか確認します。']},
   trouble:{rows:[
    ['スプライトがぼやける','ノードがプロジェクト既定のLinearフィルターを継承している','拡大して、ノードのTexture › Filterを確認','ノードのFilterをNearestに、またはプロジェクトのDefault Texture FilterをNearestに'],
    ['薄いピクセル（光・煙）の色が変わる','同梱の`.png.import`ではなく、Godot既定のFix Alpha Borderオンで取り込んだ','PNGのインポートドックでFix Alpha Borderがオン','`hero.png.import`をPNGの隣に置くか、Fix Alpha Borderを切って再インポート'],
    ['タグが1つない','ファイルにタグがなく全部`default`になった、または書き出し前にタグ名を変えた・消した','書き出し前にNerulioのタイムラインのタグ行を確認','Asepriteかタイムラインでタグを直して書き出し直す'],
    ['1回だけのはずのタグがループする／ループのはずが止まる','繰り返し∞はループオン、回数指定はループオフになる','SpriteFramesパネルでそのアニメーションのループ切り替え','タグの繰り返しを変えるか、GodotでLoopを切り替える。1回再生のタグは`animation_finished`を使う'],
    ['アニメーションが切り替わるときにキャラが跳ねる','フレームごとにピボットが違うが、ノードのオフセットは1つ（最初のフレームのピボット）','書き出し時の注意にピボット不一致の警告が出る。全ピボットは`metadata/nerulio`にある','全フレームで同じピボットのスライスを使うか、書き出し前にNerulioでピボットをそろえる（[[game/sprite-pivot-editor|ピボットエディター]]）'],
    ['Asepriteより速い・遅い','ノードのSpeed Scaleや`play()`のカスタム速度が1でない','インスペクターのSpeed Scale','Speed Scaleを1にし、`play()`はカスタム速度なしで呼ぶ'],
    ['Godot 3で.tresが開けない','フレームごとの長さを持つGodot 4形式のリソース','—','Godot 4を使うか、[[game/aseprite-to-sprite-sheet|PNGのスプライトシート]]で書き出してGodot 3で手作業でフレームを組む']]},
   alternatives:{rows:[
    ['AsepriteでPNGシートを書き出し（File › Export Sprite Sheet）、GodotのSpriteFramesパネルでAdd Frames from Sprite Sheetを使う','アニメーションが1〜2個で長さが均一なとき。ファイルは少なくて済みますが、FPSはアニメーションごとに手で設定し、フレームごとの長さは失われます。[[game/godot-sprite-sheet|Godotでスプライトシートを使う]]も参照。'],
    ['Godot Asset Libraryの.asepriteインポートプラグイン','絵を頻繁に直し、保存のたびにGodotに再インポートさせたいとき。こうしたプラグインはAsepriteのプログラムを呼び出すため、取り込むすべてのPCにAsepriteが必要です。'],
    ['同じファイルを別のエンジンで','[[game/aseprite-to-unity|AsepriteをUnityへ]]、[[game/aseprite-to-phaser|AsepriteをPhaserへ]]。']]},
   limits:['2回以上の繰り返し回数は保存されず、Godotでは1回再生になります。','レイヤーは統合されて入ります。Godotで部品ごとに動かすなら、部品ごとに別ファイルで書き出してください。','ヒット・ハートボックスはリソースのメタデータとしてだけ入ります。`Area2D`と`CollisionShape2D`のノードは自分で作ってください。'],
   versions:{body:['検証の実行では、Godot 4.7.2がNerulioのバンドルを読み込み、アニメーションごとのフレーム数・速度・ループ・相対の長さを読み戻し、全フレームを1倍と4倍で描画して元画像と比較しました。.asepriteの読み込みは実在の231ファイルで確認し、Aseprite 1.3.18で同じタグ・長さ・ピクセルのまま開き直せました。上の手順のGodotの動作はGodot 4.7の公式ドキュメントに基づきます。'],sources:[...GODOT_DOCS,'[Asepriteドキュメント：Tags](https://www.aseprite.org/docs/tags/)']}
  }
 }
};
