/** Store art export intent page. Platform documents checked 2026-09-28. */
const sources=[
 '[Steam store graphical assets](https://partner.steamgames.com/doc/store/assets/standard)',
 '[Steam library graphical assets](https://partner.steamgames.com/doc/store/assets/libraryassets)',
 '[itch.io cover images](https://itch.io/docs/creators/getting-started)',
 '[Google Play graphics](https://support.google.com/googleplay/android-developer/answer/9866151)',
 '[Apple Xcode app icon setup](https://developer.apple.com/documentation/xcode/configuring-your-app-icon)'
];
export default {'game/store-art-pack':{
 type:'tool',intent:{primary:'prepare a locally rendered, individually cropped game store art ZIP',goal:'review separate Steam, itch.io, Google Play and Xcode icon source images before submitting them to each platform',input:'key art PNG, JPEG or WebP, optional transparent PNG logo and original gameplay screenshots',output:'dimensioned PNG or JPEG files, unmodified gameplay captures and a JSON checklist in one ZIP',support:'partial',evidence:['docs/TOOL-STORE-ART-PACK.md','src/store-art/spec.js','src/store-art/render.js','tests/store-art-browser.py']},
 en:{answer:'Upload key art and an optional transparent logo, then adjust the focal point and logo position for each store slot. The tool renders separate Steam, itch.io, Google Play and Apple Xcode icon source files in a browser worker and packages them with a checklist. Steam gameplay screenshots must come from your real game; this tool carries your selected captures without inventing or retouching them. Platform acceptance still requires your visual and policy review.',concept:{body:['One crop cannot preserve the focal point across a wide library hero, tall capsule and square mobile icon. Each slot has its own crop, zoom and logo controls. Pixel mode uses nearest sampling and integer enlargement where output size permits.','The Steam library hero is art without baked text; its transparent logo is a separate PNG. The itch banner size in this tool is a custom suggestion. The Apple 1024 square is an Xcode asset source, not a standalone App Store Connect upload.']},example:{lead:'With 3840 × 2160 art and a transparent title mark, choose Steam and review the 920 × 430 header, 462 × 174 small capsule and 3840 × 1240 library hero independently. At 120 × 45, check whether the small capsule still shows the title clearly.',lines:['Input: 3840 × 2160 CC0 art + transparent PNG logo','Steam small: 462 × 174 PNG → display 120 × 45','Steam hero: 3840 × 1240 artwork, separate logo PNG'],after:'Add five actual 1920 × 1080 game captures. They are copied into the ZIP unchanged; the checklist flags missing or undersized captures.'},verify:{steps:['Open each exported image and check pixel dimensions, alpha where needed and Google Play icon size at most 1024 KB.','Review the 462 × 174 capsule at Steam’s 120 × 45 display size and confirm its title remains readable.','Compare screenshots with your game and review each platform’s current artwork rules before submission.']},trouble:{rows:[['Title too small','A single wide composition was reused','Inspect the 120 × 45 preview','Increase logo width or recompose the small capsule'],['Subject clipped','Crop focal point is off center','Select that slot and move its focal sliders','Adjust its focal point and zoom'],['Pixel edges blurry','The image was reduced or scaled nonintegrally','Read the ZIP checklist warning','Use larger pixel source art or a suitable output size']]},alternatives:{rows:[['Manual art editor','Choose this for detailed paintover, hand lettering or platform-specific illustration']]},limits:{items:['This exporter does not certify approval by Steam, itch.io, Google or Apple. It cannot judge trademark rights or artwork policy from pixels.','A typed title is a visible placeholder when no transparent logo is supplied; inspect all resulting images.']},versions:{body:'Official platform documents reviewed 2026-09-28. Required sizes and recommendations are distinguished in the ZIP checklist.',sources}},
 ko:{answer:'키아트와 선택적인 투명 로고를 넣고 스토어 이미지마다 초점·확대·로고 위치를 따로 맞춥니다. 브라우저 워커가 Steam, itch.io, Google Play, Apple Xcode용 아이콘 소스를 각각 만들고 점검 목록과 함께 ZIP으로 묶습니다. Steam 게임 화면은 직접 실행한 실제 캡처를 넣어야 하며, 이 도구는 장면을 만들거나 바꾸지 않습니다. 각 플랫폼의 최종 심사 여부는 별도 확인이 필요합니다.',concept:{body:['가로로 긴 라이브러리 배경, 세로 캡슐, 정사각 아이콘에 하나의 자르기를 그대로 쓰면 주제가 잘릴 수 있습니다. 각 규격에 독립적인 초점·확대·로고 위치가 있습니다. 도트 모드는 가능한 경우 정수 배율 nearest를 씁니다.','Steam 라이브러리 hero에는 글자를 넣지 않고 투명 로고를 별도 PNG로 출력합니다. itch 배너 크기는 사용자 정의 제안입니다. Apple의 1024 정사각형은 Xcode용 소스이며 App Store Connect에 단독 업로드하는 파일이 아닙니다.']},example:{lead:'3840 × 2160 키아트와 투명 로고를 넣고 Steam의 920 × 430 헤더, 462 × 174 작은 캡슐, 3840 × 1240 라이브러리 hero의 구도를 따로 확인합니다.',lines:['입력: 3840 × 2160 CC0 키아트 + 투명 PNG 로고','Steam 작은 캡슐: 462 × 174 PNG → 표시 120 × 45','Steam hero: 3840 × 1240 그림, 별도 로고 PNG'],after:'작은 캡슐은 120 × 45 표시 크기로 줄여 제목을 읽을 수 있는지 확인합니다. 실제 게임 화면 5장을 넣으면 원본 그대로 ZIP에 복사됩니다.'},verify:{steps:['출력 이미지를 열어 규격, 알파, Google Play 아이콘의 1024 KB 이하 용량을 확인합니다.','작은 캡슐을 120 × 45로 줄여 제목 가독성을 점검합니다.','게임 캡처의 진위를 확인하고 각 플랫폼의 현재 그림 규칙을 다시 확인합니다.']},trouble:{rows:[['제목이 작음','가로 그림 하나를 반복 사용','120 × 45 크기로 보기','작은 캡슐의 로고 폭을 키우기'],['주제가 잘림','초점 위치가 빗나감','해당 규격의 슬라이더 확인','초점과 확대값 조정'],['도트 경계가 흐림','축소 또는 비정수 배율','ZIP 점검 목록 확인','더 큰 원본이나 맞는 규격 사용']]},alternatives:{rows:[['수동 이미지 편집기','세밀한 채색·손글씨·규격별 새 일러스트가 필요할 때']]},limits:{items:['이 도구는 스토어 승인을 보증하지 않으며 상표권과 이미지 정책을 자동 판정하지 않습니다.','투명 로고 없이 입력한 제목은 임시 합성입니다. 결과를 직접 확인하세요.']},versions:{body:'플랫폼 공식 문서를 2026-09-28에 확인했습니다. 필수와 권장을 ZIP 점검 목록에서 구분합니다.',sources}},
 ja:{answer:'キーアートと任意の透過ロゴを入れ、ストア画像ごとに注目位置、拡大率、ロゴ位置を調整します。ブラウザーのワーカーがSteam、itch.io、Google Play、AppleのXcode用アイコン素材を個別に生成し、確認用JSONとともにZIPにまとめます。Steamのゲーム画面には実際のゲームから撮った画像を使ってください。この道具は場面を作成・改変しません。各ストアでの受理は別途確認が必要です。',concept:{body:['横長のライブラリー画像、縦長のカプセル、正方形アイコンに同じ切り抜きを使うと主題が欠けます。規格ごとに注目位置、拡大率、ロゴ位置を保存します。ドットモードは可能な出力で整数倍率のnearestを使います。','Steamのライブラリーheroには文字を焼き込まず、透過ロゴを別のPNGで出力します。itchバナーの寸法は独自の提案です。Appleの1024正方形はXcode用の素材であり、App Store Connectへの単体アップロード用ではありません。']},example:{lead:'3840 × 2160の絵と透過ロゴでSteamを選び、920 × 430のヘッダー、462 × 174の小型画像、3840 × 1240のライブラリーheroを別々に調整します。',lines:['入力: 3840 × 2160 CC0アート + 透過PNGロゴ','Steam小型画像: 462 × 174 PNG → 表示120 × 45','Steam hero: 3840 × 1240の絵、別のロゴPNG'],after:'小型画像を120 × 45で表示して題名が読めるか確認します。実際のゲーム画面5枚は元ファイルのままZIPへ入ります。'},verify:{steps:['出力画像を開き、寸法、透過の有無、Google Playアイコンが1024 KB以内か確認します。','小型画像を120 × 45で表示して題名の読みやすさを確かめます。','ゲーム画面と実物を照合し、各ストアの現行規則を確認します。']},trouble:{rows:[['題名が小さい','横長の構図を流用','120 × 45で見る','小型画像のロゴ幅を増やす'],['主題が切れる','注目位置のずれ','規格のスライダーを見る','位置と拡大率を調整'],['ドットの縁がぼける','縮小または非整数倍率','ZIPの確認記録を見る','大きい原画か合う出力規格を使う']]},alternatives:{rows:[['画像編集ソフト','細かな描き直し、手書き文字、ストア専用の絵が必要な場合']]},limits:{items:['この道具はストアでの承認を保証せず、商標権や画像方針を画素から判定できません。','透過ロゴなしで入力した題名は仮の合成です。出力を目視してください。']},versions:{body:'公式文書を2026-09-28に確認しました。必須条件と推奨事項をZIPの確認記録に分けて示します。',sources}}
}};
