/** Creator guide for the one Webtoon/Manga Toolkit route. Dates and scopes are explicit. */
const NAVER='[Naver Help: Challenge Comics upload](https://help.naver.com/service/5635/contents/18779?lang=ko&osType=COMMONOS)';
const CANVAS='[WEBTOON: long image notice](https://www.webtoons.com/en/notice/detail?noticeNo=1766)';
const FR='[WEBTOON French Creator Academy](https://www.webtoons.com/fr/creators101/webtoon-academy)';
const POSTYPE='[Postype image help](https://help.postype.com/hc/ko/articles/360012345374-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%82%BD%EC%9E%85%ED%95%98%EA%B3%A0-%ED%8E%B8%EC%A7%91%ED%95%98%EA%B8%B0)';
export default {'image/webtoon-manga-toolkit':{
 type:'tool',intent:{primary:'split a long original comic into numbered upload images or join panels in reading order',secondary:['Naver Challenge Comics 690 px width','WEBTOON CANVAS 800 by 1280 pixel cuts','Postype image limits','make original comic speed lines, speech bubbles and screentones'],goal:'numbered PNG/JPG images in a ZIP with source-scoped constraints and a JSON report',input:'one or more local PNG, JPG or WebP still images',output:'ZIP of JPG/PNG slices or joined PNG, plus a report; original effect PNG and SVG',support:'partial',evidence:['src/webtoon/geometry.js','src/webtoon/specs.js','src/webtoon/worker.js','tests/webtoon-geometry.test.mjs','tests/webtoon-browser.py: CC0 strip Pillow/ZIP reparse']},
 en:{
  answer:'Use this toolkit when you own a long comic page or ordered panels and need upload-sized image files. It cuts at exact source rows, numbers each piece, reopens the encoded files and includes their dimensions and bytes in a ZIP report. Naver Challenge Comics has a documented 690 px width and JPG/GIF format; this tool exports JPG for that profile. WEBTOON has an 800×1280 splitting notice. Its 2 MB per image and 20 MB episode figures are conservative export targets from regional guidance and a 2025 contest FAQ, not a permanent universal upload promise. Postype allows PNG/JPG up to 10,000 px per side and 50 MB per image. Inspect every proposed cut around dialogue before posting.',
  concept:{title:'Why a comic needs cuts you can inspect',body:['A vertical episode has reading rhythm: a blank gutter may mark a scene break, while white inside a panel or speech balloon can look just as empty to software. The default cut height produces predictable files. You can edit the source row of each cut and undo changes. The red preview lines are locations, not a claim that the narrative remains intact.','The worker checks image dimensions before full decoding and refuses an input above 64 megapixels, 32,767 px on a side or 80 MB. It processes one source and output tile at a time and decodes each encoded output again. JPG flattens transparency onto the chosen matte. A ZIP report records source rows so you can check coverage.'],terms:[['Source row','A horizontal coordinate in the original image. Cuts at rows 1280 and 2560 create ranges 0–1279, 1280–2559 and 2560 onward.'],['Upload target','A conservative pixel or byte budget for export. The publisher may change its uploader or use a different regional workflow.'],['PPI / LPI','Output pixels per inch divided by screentone lines per inch gives the dot-cell pitch in pixels. A 300 PPI output at 60 LPI has a 5 px pitch.']]},
  example:{title:'Worked example: one 800×3000 page',lead:'A CC0 test page 800 px wide and 3000 px tall uses two cuts at source rows 1280 and 2560.',lines:['Piece 01: rows 0–1279 = 800×1280 px','Piece 02: rows 1280–2559 = 800×1280 px','Piece 03: rows 2560–2999 = 800×440 px','Height check: 1280 + 1280 + 440 = 3000, with no skipped or repeated source rows'],after:'Check a 100% seam view at both cuts. For a comic with speech or faces at either line, change the row even if the dimensions already satisfy an export profile.'},
  verify:{steps:['Open the ZIP in another program, count the numbered files and reopen each image. Compare the dimensions and actual bytes with export-report.json.','Check that sourceY and sourceHeight cover every input row in order. For JPEG, inspect the visible seam and any flattened transparency rather than claiming pixel-for-pixel preservation.','Preview the complete episode in reading order and inspect speech, faces and gutters at actual size before using a publisher dashboard.']},
  trouble:{rows:[['A dialogue bubble is cut','An even-height target crosses the panel','Zoom to each red cut line','Change the source row and export again'],['The JPG has a white area where transparency was','JPG has no alpha channel','Compare the input and the chosen matte colour','Choose PNG where that profile permits it, or set an intended JPG matte'],['The page is refused before import','Dimensions or file bytes exceed the worker memory budget','Read the exact size in the error','Split the page in a drawing app before loading it here'],['A file misses the byte target','Detailed art stays large after JPEG quality reduction','Read the per-file message and ZIP report','Shorten the slice or use a smaller custom width, then visually inspect the result']]},
  alternatives:{rows:[['The publisher’s current upload dashboard','Use it to verify current rules and acceptance; this toolkit cannot approve an episode on behalf of a platform.'],['A layered drawing app','Use it when you need to rearrange panels, redraw speech or preserve editable layers. The toolkit operates on flattened still images.']]},
  limits:['The cut line cannot identify every face, speech balloon or story beat; manual review is necessary.','No Kakao or Lezhin upload dimensions are claimed. Their public submission pages did not establish a self-publishing raster rule.','A 64 MP input limit and browser codecs can reject very long pages; this does not mean the publisher disallows them.','Speed lines, balloons and screentones are original SVG/PNG overlays; printing and platform acceptance require independent review.'],
  versions:{body:['Publisher pages checked 2026-09-29. Naver Help refers specifically to Challenge Comics: 690 px exact width, JPG/GIF, 5 MB each and 50 MB total; it does not state a maximum height. The general WEBTOON notice describes 800×1280 slicing. The French Creator Academy lists 2 MB per image and 20 MB per episode; a 2025 competition FAQ has a narrower contest scope, so those bytes are treated as conservative targets. Postype Help states PNG/JPG, at most 10,000 px per side and 50 MB per image; its 700 px figure is display width. Platform upload acceptance and search demand are unverified.'],sources:[NAVER,CANVAS,FR,POSTYPE]}
 },
 ko:{
  answer:'직접 만든 긴 만화 원고나 순서가 정해진 컷을 업로드용 이미지로 나눌 때 쓰세요. 원본 행에서 정확히 자르고 번호를 붙이며, 인코딩한 파일을 다시 연 뒤 크기·바이트를 ZIP 보고서에 기록합니다. 네이버 도전만화 도움말에는 너비 690px, JPG/GIF가 명시되어 있고 이 도구의 해당 프로필은 JPG로 저장합니다. WEBTOON의 일반 공지는 800×1280px 분할을 설명합니다. 2MB/이미지·20MB/회차는 지역별 안내와 2025년 대회 FAQ에 근거한 보수적 출력 목표이며 보편적인 영구 업로드 규칙이라고 단정하지 않습니다. Postype은 PNG/JPG, 한 변 10,000px 이하, 파일당 50MB 이하입니다. 게시 전에 대사가 걸린 모든 분할선을 직접 확인하세요.',
  concept:{title:'분할선을 직접 확인해야 하는 이유',body:['세로 만화에는 읽는 리듬이 있습니다. 빈 여백은 장면 전환일 수도 있지만, 하얀 패널 내부나 말풍선도 컴퓨터에는 똑같이 비어 보일 수 있습니다. 기본 높이는 예측 가능한 파일을 만들기 위한 값입니다. 원본의 행 번호를 바꾸고 되돌릴 수 있습니다. 붉은 미리보기 선은 위치 표시이며 서사적으로 안전하다는 판정이 아닙니다.','워커는 전체 디코딩 전에 이미지 크기를 확인하고 6,400만 화소, 한 변 32,767px, 입력 파일당 80MB를 넘으면 거부합니다. 원본과 조각을 순서대로 처리하며 인코딩한 결과를 다시 엽니다. JPG는 투명 부분을 선택한 배경색으로 채웁니다. ZIP 보고서에는 원본 행 범위를 적어 빠진 줄을 검사할 수 있습니다.'],terms:[['원본 행','원본 이미지의 가로줄 번호입니다. 1280과 2560에서 자르면 0–1279, 1280–2559, 2560 이후 범위가 됩니다.'],['출력 목표','내보낼 때 적용하는 보수적 크기·용량입니다. 플랫폼 화면이나 지역별 작업 방식은 달라질 수 있습니다.'],['PPI / LPI','출력 인치당 픽셀을 스크린톤 인치당 선 수로 나누면 셀 간격(px)이 됩니다. 300 PPI, 60 LPI는 5px 간격입니다.']]},
  example:{title:'계산 예시: 800×3000 원고 한 장',lead:'CC0 시험 원고의 너비가 800px, 높이가 3000px일 때 원본 1280행과 2560행에서 자릅니다.',lines:['1번: 0–1279행 = 800×1280px','2번: 1280–2559행 = 800×1280px','3번: 2560–2999행 = 800×440px','높이 검사: 1280 + 1280 + 440 = 3000, 빠지거나 겹친 행 없음'],after:'두 경계를 100% 크기로 확인하세요. 대사나 얼굴이 걸리면 규격을 만족해도 절단 행을 바꿔야 합니다.'},
  verify:{steps:['ZIP을 다른 프로그램에서 열어 번호가 붙은 파일 수를 세고 각 이미지를 다시 여세요. 크기와 실제 바이트를 export-report.json과 비교하세요.','sourceY와 sourceHeight가 입력의 모든 행을 순서대로 덮는지 확인하세요. JPG는 손실 방식이므로 픽셀 동일성을 주장하지 말고 경계와 투명 배경 처리를 눈으로 확인하세요.','전체 회차를 읽는 순서대로 미리 보고, 플랫폼 업로드 전에 대사·얼굴·여백을 실제 크기로 확인하세요.']},
  trouble:{rows:[['말풍선이 잘림','목표 높이가 패널을 가로지름','붉은 분할선을 확대해 확인','원본 행 번호를 바꾸고 다시 저장'],['JPG의 투명 부분이 흰색이 됨','JPG에는 알파 채널이 없음','원본과 선택한 배경색 비교','프로필이 허용하면 PNG 선택, 아니면 의도한 배경색 지정'],['이미지를 열기 전에 거부됨','크기나 파일 용량이 워커의 메모리 예산을 넘음','오류에 적힌 크기 확인','그림 프로그램에서 먼저 분할'],['파일이 용량 목표를 넘음','세부가 많은 원고가 JPEG 압축 후에도 큼','파일별 메시지와 ZIP 보고서 확인','조각을 짧게 하거나 사용자 지정 너비를 줄인 뒤 육안 검사']]},
  alternatives:{rows:[['플랫폼의 현재 업로드 화면','현재 규칙과 접수 여부를 확인할 때 사용합니다. 이 도구는 플랫폼을 대신해 회차를 승인하지 못합니다.'],['레이어를 다루는 그림 프로그램','컷을 재배치하거나 대사를 다시 그리고 편집 가능한 레이어를 보존해야 할 때 사용합니다. 이 도구는 평면 정지 이미지를 처리합니다.']]},
  limits:['절단선은 모든 얼굴·말풍선·이야기 흐름을 판단하지 못합니다. 사람의 검토가 필요합니다.','카카오·레진 업로드 픽셀 규격은 주장하지 않습니다. 공개 제출 안내에서 자가 업로드 래스터 규칙을 확인하지 못했습니다.','6,400만 화소 제한과 브라우저 코덱 때문에 아주 긴 원고를 거부할 수 있습니다. 플랫폼의 제한을 뜻하지는 않습니다.','집중선·말풍선·스크린톤은 독자 제작 SVG/PNG 오버레이입니다. 인쇄·플랫폼 접수는 별도 확인이 필요합니다.'],
  versions:{body:['플랫폼 공식 문서 확인일은 2026-09-29입니다. 네이버 도움말은 도전만화에 한해 정확한 너비 690px, JPG/GIF, 파일당 5MB와 총 50MB를 적으며 높이 상한은 명시하지 않습니다. WEBTOON 일반 공지는 800×1280px 분할을 설명합니다. 프랑스 Creator Academy의 파일당 2MB와 회차당 20MB는 2025년 대회 FAQ의 좁은 범위와 구분해 보수적 목표로 다룹니다. Postype은 PNG/JPG, 한 변 10,000px 이하, 파일당 50MB 이하이고 700px은 표시 너비입니다. 실제 업로드 수락과 검색 수요는 미검증입니다.'],sources:[NAVER,CANVAS,FR,POSTYPE]}
 },
 ja:{
  answer:'自分で制作した縦長の漫画原稿や順序の決まったコマを投稿用画像に分けるときに使います。元画像の行で正確に切り、番号を付け、保存画像を再読み込みして寸法とバイト数をZIPの報告書に記録します。Naverの挑戦漫画向けヘルプには幅690pxとJPG/GIFが明記され、このプロファイルはJPGを出力します。WEBTOONの一般告知は800×1280pxでの分割を説明します。画像ごと2MBとエピソードごと20MBは地域別案内と2025年コンテストFAQによる保守的な出力目標であり、恒久的な共通投稿規則とは断定しません。PostypeはPNG/JPG、一辺10,000px以内、1ファイル50MB以内です。投稿前にせりふにかかる分割線を確認してください。',
  concept:{title:'分割位置を目で確認する理由',body:['縦読み漫画には読む間合いがあります。白い余白は場面転換かもしれませんが、白いコマの内部や吹き出しも機械には同じ空白に見えます。標準の高さは予測しやすいファイルを作るための値です。元画像の行番号を編集して元に戻せます。赤い線は場所の表示であり、物語上の安全判定ではありません。','ワーカーは画像全体の復号前に寸法を調べ、6,400万画素、一辺32,767px、入力1枚80MBを超えると拒否します。元画像と出力を順に処理し、保存結果を再読み込みします。JPGでは透明部分を指定色で塗ります。ZIPの報告書には元画像の行範囲を記録し、欠落を確認できます。'],terms:[['元画像の行','原稿の横一行の番号です。1280と2560で切ると0–1279、1280–2559、2560以降に分かれます。'],['出力目標','保存時に使う保守的な寸法・容量です。地域や投稿画面の仕様は変わり得ます。'],['PPI / LPI','出力のインチ当たり画素数をトーンのインチ当たり線数で割るとセル間隔がpx単位で求まります。300 PPI、60 LPIは5pxです。']]},
  example:{title:'計算例：800×3000の原稿',lead:'CC0の試験原稿を幅800px、高さ3000pxとし、元画像の1280行と2560行で切ります。',lines:['1枚目：0–1279行 = 800×1280px','2枚目：1280–2559行 = 800×1280px','3枚目：2560–2999行 = 800×440px','高さの確認：1280 + 1280 + 440 = 3000、欠落も重複もなし'],after:'二つの境界を100%の大きさで確認してください。せりふや顔にかかるなら、寸法を満たしていても行を変えてください。'},
  verify:{steps:['ZIPを別のプログラムで開き、連番の画像数を数えて一枚ずつ再読み込みします。寸法と実際のバイト数をexport-report.jsonと比較します。','sourceYとsourceHeightが入力の全行を順序どおり覆うか確認します。JPGは非可逆なので画素一致を主張せず、境界と透明部分の塗りを目で確認します。','エピソード全体を読む順に見て、投稿画面に進む前にせりふ・顔・余白を実寸で確かめます。']},
  trouble:{rows:[['吹き出しが切れる','目標高さがコマを横切る','赤い分割線を拡大して見る','元画像の行番号を変えて再出力'],['JPGの透明部分が白くなる','JPGにアルファチャンネルがない','元画像と選択した背景色を比較','許されるプロファイルならPNGにするか、意図した背景色を指定'],['画像を開く前に拒否される','寸法やバイト数がワーカーのメモリ予算を超える','エラーに表示された寸法を確認','描画ソフトで先に分割'],['容量目標に届かない','細部が多くJPEG圧縮後も大きい','ファイル別メッセージとZIP報告書を確認','分割を短くするかカスタム幅を下げ、目で確認']]},
  alternatives:{rows:[['投稿先の現在のアップロード画面','現行の規則と受理を確認するときに使います。このツールは投稿先を代理して作品を承認できません。'],['レイヤーを扱う描画ソフト','コマの並べ直し、せりふの描き直し、編集可能なレイヤーの保持が必要なときに使います。このツールは平面の静止画を処理します。']]},
  limits:['分割線はすべての顔・吹き出し・物語の流れを判断できません。人の確認が必要です。','Kakao・Lezhinの投稿用ピクセル規格は主張しません。公開提出案内からセルフ投稿の画像規則は確認できませんでした。','6,400万画素の上限とブラウザのコーデックにより長い原稿を拒否する場合があります。投稿先の制限を意味しません。','集中線・吹き出し・スクリーントーンは独自制作のSVG/PNGオーバーレイです。印刷と投稿受理は別途確認が必要です。'],
  versions:{body:['投稿先の公式資料を確認した日は2026-09-29です。Naverの案内は挑戦漫画に限り、幅690px、JPG/GIF、各5MB、合計50MBを示しますが、高さの上限は記していません。WEBTOONの一般告知は800×1280px分割を説明します。フランスのCreator Academyの各2MB・話全体20MBは、2025年大会FAQの狭い範囲と区別して保守的な目標として扱います。PostypeはPNG/JPG、一辺10,000px以内、各50MB以内で、700pxは表示幅です。実際の投稿受理と検索需要は未検証です。'],sources:[NAVER,CANVAS,FR,POSTYPE]}
 }
}};
