#!/usr/bin/env node
/** Seed data → one SQL file for Cloudflare D1:
 *   node tools/platform/export-sql.mjs dist-seed.sql
 *   npx wrangler d1 execute nerulio --remote --file dist-seed.sql
 * Builds a fresh database (migrations + every seed file through the ingest pipeline, never the
 * sample boards), then writes INSERT statements for the platform graph tables in dependency order.
 * The D1 schema itself comes from `wrangler d1 migrations apply`, not from this file.
 * Rows are INSERT OR IGNORE: re-running never deletes or overwrites (collector and community data
 * written since stays); later seed changes go through the ingest pipeline, not this file. */
import {writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {D1Shim} from '../../tests/d1-shim.mjs';
import {seedDatabase} from './seed-db.mjs';

/** Graph tables written by seed import, parents before children. */
export const SEED_TABLES=Object.freeze(['sources','snapshots','entities','entity_redirects','entity_aliases','relations','facts','fact_conflicts','changes','versions','events','event_entities','availability','compatibility']);
const lit=(/** @type {unknown} */ v)=>v===null||v===undefined?'NULL':typeof v==='number'||typeof v==='bigint'?String(v):`'${String(v).replace(/'/g,"''")}'`;

/** @param {any} db D1Shim @returns {string} */
export function dumpSql(db){
 const out=['-- Nerulio 2.0 seed data (generated by tools/platform/export-sql.mjs). Apply after migrations.','PRAGMA defer_foreign_keys=ON;'];
 for(const t of SEED_TABLES){
  const rows=db.raw.prepare(`SELECT * FROM ${t}`).all();
  if(!rows.length)continue;
  const cols=Object.keys(rows[0]);
  for(let i=0;i<rows.length;i+=100){
   const chunk=rows.slice(i,i+100);
   out.push(`INSERT OR IGNORE INTO ${t} (${cols.join(',')}) VALUES\n${chunk.map(r=>`(${cols.map(c=>lit(r[c])).join(',')})`).join(',\n')};`);
  }
 }
 // The FTS index is rebuilt from the rows rather than copied.
 const docs=db.raw.prepare('SELECT doc_key,kind,vertical,locale,title,body FROM search_docs').all();
 out.push("DELETE FROM search_docs WHERE doc_key LIKE 'entity:%';");
 for(let i=0;i<docs.length;i+=100)out.push(`INSERT INTO search_docs (doc_key,kind,vertical,locale,title,body) VALUES\n${docs.slice(i,i+100).map(r=>`(${['doc_key','kind','vertical','locale','title','body'].map(c=>lit(r[c])).join(',')})`).join(',\n')};`);
 return out.join('\n')+'\n';
}

if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const file=process.argv[2]||'dist-seed.sql';
 const db=D1Shim.migrated();
 const r=await seedDatabase(db);
 const sql=dumpSql(db);
 writeFileSync(file,sql);
 console.log(`${r.entities} entities → ${file} (${(sql.length/1048576).toFixed(1)} MB)`);
}
