/** Texture workspace copy (ko/en/ja), merged into the Studio strings under `tex` (and
 * `group.texture`); tests/studio-texture.test.mjs checks key and placeholder parity.
 * Heuristics say they are approximations or guesses with a confidence — never "AI". */
import {STUDIO_STRINGS} from '../../strings.js';
export const TEX_STRINGS={
en:{
 menu:'Texture',noImage:'Open a sprite or a texture (File › Import, or drop a PNG) to make its normal map.',
 panel:{normal:'Normal map',light:'Lighting',maps:'Maps & channels',check:'Check',export:'Export',frames:'Frames',preview3d:'3D preview'},
 tool:{light:'Lights',lightHint:'drag a light; click to move the selected one there; Shift+click adds one; Alt+click removes',brush:'Height brush',brushHint:'paint relief on the height map; Alt inverts raise/lower; [ ] size'},
 view:{albedo:'Albedo',height:'Height',normal:'Normal',lit:'Lit',ao:'AO',maps:'Maps'},
 hud:{label:'Texture view',compare:'Compare',tile:'Tile 3×3',sheet:'Sheet',convWarn:'Normal map reads as {conv} — check'},
 split:{flat:'flat',lit:'lit'},
 status:{working:'Making the maps…',ready:'{w}×{h} · maps in {ms} ms',pixel:'x {x} y {y} · height {h} px · normal {n}'},
 conf:{high:'high confidence',medium:'medium confidence',low:'low confidence',none:'cannot tell'},
 normal:{sourceTitle:'Source',source:'Normal map',generate:'Generate from the picture',useMap:'Use {name}',importedHint:'An imported normal map is shown and exported as it is (flipped to OpenGL if you confirm it is DirectX, see Check). Generation settings are hidden.',kindTitle:'This picture is'},
 kind:{sprite:'Sprite',texture:'Tileable texture',spriteHint:'has a silhouette: the relief rises from its edge (bevel); kernels stop at each frame',textureHint:'fills the picture and repeats: no bevel, kernels wrap around, so the tiled map has no seam',suggestedSprite:'Suggested: it has transparent pixels. Change it if that is wrong.',suggestedTexture:'Suggested: it has no transparent pixels. Change it if that is wrong.'},
 bevel:{title:'Bevel from the silhouette',width:'Width',depth:'Height',shape:'Profile',metric:'Distance'},
 shape:{round:'Round',linear:'Linear',smooth:'Smooth',concave:'Cove',step:'Ledge'},
 metric:{euclidean:'Round',chebyshev:'Square',manhattan:'Diamond',euclideanHint:'true distance: round shoulders',chebyshevHint:'chessboard distance: square rings (pixel-art outlines)',manhattanHint:'city-block distance: diamond rings'},
 luma:{title:'Detail from brightness',approx:'Approximation: brightness is paint, not shape. It adds small relief; the bevel and your brush strokes carry the form.',depth:'Height',detail:'Ignore shading wider than',detailHint:'brightness changes wider than this (a dark cloak, a lit side) are not read as relief',smooth:'Smooth',invert:'Dark is high'},
 hmap:{title:'Height map',source:'Height from',none:'None',depth:'Height of white',hint:'A Height/Displacement map of the same size; 16-bit files keep all 16 bits.'},
 nrm:{title:'Normal map',strength:'Strength',kernel:'Kernel',edge:'Edges',convention:'Green'},
 kernel:{central:'Pixel',centralHint:'no smoothing: a one-pixel ledge stays one pixel (pixel art)'},
 edge:{clamp:'Clamp',tile:'Wrap',mirror:'Mirror',clampHint:'the border pixel repeats (sprites)',tileHint:'samples wrap to the opposite side: a tileable texture gets no seam',mirrorHint:'the picture is reflected at the border'},
 conv:{opengl:'OpenGL (Y+)',directx:'DirectX (Y−)',openglHint:'green up: Godot, Unity, Blender',directxHint:'green down: Unreal',title:'Normal map convention',verdict:'{name} reads as {conv}.',cannot:'Cannot tell which convention {name} uses.',
  reason:{'no-signal':'The pixels carry no signal either way.','tests-disagree':'The two tests disagree.','too-small':'Too few usable pixels.','no-mixed-slopes':'The surface has no diagonal relief (straight grooves or ramps look the same both ways).'},
  curl:'Integrability test: ρ = {rho}, {agree}% of the signal agrees, {n} of {b} regions informative',sil:'Silhouette test: green ρ = {rho}, red ρ = {red} over {n} edge pixels',nothing:'no verdict',
  nameSays:'The file name also says {conv}.',nameDisagrees:'The file name says {conv}: check the preview before choosing.',declare:'It is {conv}',redFlipped:'Red also looks flipped (X−, right-facing edges point left): every engine would light this map mirrored left↔right. The verdict above is about green only.',redFixed:'Red is inverted on load (you confirmed it was X−); the checks above still describe the file as imported.',flipRed:'Flip red (X−)',declared:'Confirmed as {conv}: lit and exported as such (DirectX is flipped to OpenGL for Godot and Unity).',notApplied:'Nothing is changed until you confirm the convention.',
  selfHint:'This picture is itself a normal map. Use it as the normal map of its albedo (Normal map › Source) to light it.',notNormal:'These pixels do not look like a normal map (vectors are not unit length).',running:'Measuring…',generated:'Generated maps are written as {conv}; nothing to detect.'},
 brush:{title:'Height brush',use:'Use (B)',size:'Size',strength:'Strength',hard:'Hardness',count:'{n} stroke(s)',hint:'Paint on the canvas. Each stroke is one undo step and stays inside the frame it starts in.',imported:'The brush paints height; an imported normal map has none. Switch the source to Generate.',
  mode:{raise:'Raise',lower:'Lower',smooth:'Smooth',flatten:'Flatten',erase:'Erase'}},
 pixel:{title:'Pixel-art normals',hint:'Snaps every pixel to a few directions and tilts, like hand-painted pixel-art normals. Pixels stay crisp.',directions:'Directions',tiers:'Tilt steps'},
 light:{lights:'Lights',n:'Light {n}',enabled:'On',pick:'Select a light in the list or on the canvas (Lights tool, L).',hint:'Positions are in frame pixels, so every frame of an animation is lit alike. Height is how far the light is in front of the picture.',selected:'Light {n}',color:'Colour',energy:'Energy',height:'Height',heightHint:'z in pixels: low grazes the relief, high lights it from the front',radius:'Radius',falloff:'Falloff',x:'X',y:'Y',max:'At most {n} lights.',
  ambientTitle:'Ambient',ambient:'Ambient colour',ambientHint:'Multiplies the unlit picture (Godot: CanvasModulate).',specTitle:'Specular',specStrength:'Strength',shininess:'Shininess',specHint:'Godot draws specular only with a specular map; exported as one when above 0.',
  rimTitle:'Rim light (preview only)',rimStrength:'Strength',rimColor:'Colour',rimPower:'Tightness',rimHint:'A preview aid: no engine draws a rim light from a normal map without a custom shader, so it is not exported.'},
 falloff:{smooth:'Smooth',linear:'Linear',quadratic:'Quadratic',constant:'None'},
 maps:{title:'Show',show:'Map',addTitle:'Add to project',addNormal:'Normal map',addHeight:'Height (16-bit)',addAO:'AO',addThis:'{name}',addHint:'Adds the map as an image next to the picture (undoable).'},
 map:{ao:'AO',cavity:'Cavity',curvature:'Curvature',roughness:'Roughness ≈',specular:'Specular ≈',aoTitle:'Ambient occlusion',aoRadius:'Radius',aoPower:'Contrast',aoHint:'Estimated from the height field (how much sky each pixel sees), not ray-traced.',approx:'Approximation from the albedo brightness: a starting point to paint over, not a measured material.',fromHeight:'Computed from the height field.'},
 set:{title:'Material set',hint:'Maps of the same size and name belong together (by file name). Correct any role here.',none:'No other maps of this picture in the project.',role:'Role of {name}',set:'set',byName:'by name'},
 role:{albedo:'Albedo',normal:'Normal',height:'Height',roughness:'Roughness',smoothness:'Smoothness',metallic:'Metallic',ao:'AO',orm:'Packed (ORM/mask)',emission:'Emission',opacity:'Opacity',specular:'Specular',unknown:'—'},
 pack:{title:'Channel pack',preset:'Engine layout',zero:'0 (black)',one:'255 (white)',genAO:'Generated AO',genHeight:'Generated height',genRough:'Roughness ≈ (from albedo)',genSpec:'Specular ≈ (from albedo)',gray:'grey',invert:'invert',make:'Pack and download',hint:'Bytes are copied exactly (no colour conversion). The packed image is also added to the project.',missing:'A source map is not available.',done:'Packed {name}.'},
 unpack:{title:'Channel unpack',hint:'Splits the open picture into four exact greyscale PNGs (R, G, B, A).',go:'Unpack {name}'},
 seam:{title:'Seams (tileable)',roll:'Wrap test ({edge}): border differs by {b} on average, {m} at most (0 = seamless).',rollOk:'✓ Wrap-correct: the map is identical however the texture is shifted.',rollBad:'The border is computed differently from the inside: choose Wrap for a tileable texture.',albedo:'Albedo seam ratio {r} (1 ≈ no visible seam).',albedoOk:'The albedo itself tiles.',albedoBad:'The albedo itself shows a seam where it repeats; the normal map cannot hide that.',running:'Measuring…',hint:'The wrap test generates the map again from the texture shifted by half and compares.'},
 mip:{title:'Mipmaps of the normal map',hint:'Averaged as vectors and renormalised, as an engine should: a plain colour average would flatten the lighting at a distance.',show:'Show mipmaps',refresh:'Refresh'},
 export:{targets:'Targets',target:{godot:'Godot 4',unity:'Unity 6 (URP 2D)',generic:'PNG set + JSON'},verified:'✓ verified in {engine}',unverified:'UNVERIFIED in an engine render',plain:'plain files',
  what:{godot:'CanvasTexture, Sprite2D, PointLight2D, CanvasModulate, animation',unity:'Secondary Texture _NormalMap + Editor importer + Light2D helper',generic:'albedo, normal (OpenGL + DirectX), 16-bit height, AO, manifest'},
  options:'Options',height16:'16-bit height map',ao:'Ambient occlusion',bleed:'Bleed albedo edges (px)',bleedHint:'Copies edge colours into transparent pixels so filtering and mipmaps do not darken the outline (0 = the albedo PNG stays byte-identical).',
  go:'Export ZIP',quick:'Normal map PNG · {conv}',none:'Choose at least one target.',done:'Exported {n} files.',hint:'Everything is made in this browser; nothing is uploaded.',notReady:'The maps are not ready yet.'},
 frames:{none:'This picture has no frames. Cut frames in the Sprite workspace to light an animation.',tag:'Animation',all:'All frames',play:'Play',pause:'Pause',hint:', and . step frames'},
 p3d:{label:'3D preview of the material',noGL:'WebGL2 is not available: no 3D preview.',shape:'Shape',sphere:'Sphere',plane:'Plane',auto:'Turn',rough:'Roughness',metal:'Metallic',constant:'constant',generated:'generated',generatedAO:'generated AO',hint:'Drag to turn. Missing maps are constants.'},
 cmd:{kind:'Picture kind',bevel:'Bevel',luma:'Brightness detail',hmap:'Height map',strength:'Normal strength',kernel:'Kernel',edge:'Edge mode',convention:'Normal convention',pixel:'Pixel-art normals',source:'Normal map source',paint:'Paint height ({mode})',clearPaint:'Clear painted height',addLight:'Add light',removeLight:'Remove light',moveLight:'Move light',light:'Edit light',lightHeight:'Light height',scene:'Lighting',compare:'Compare lit / flat',tile:'Tile preview 3×3',scope:'Whole sheet',export:'Export…',smaller:'Smaller brush / lower light',bigger:'Bigger brush / higher light',ao:'AO settings',role:'Map role',declare:'Normal map convention',flipRed:'Flip red channel'},
 toast:{added:'Added {n} image(s) to the project.'}
},
ko:{
 menu:'텍스처',noImage:'노멀 맵을 만들 스프라이트나 텍스처를 여세요 (파일 › 가져오기, 또는 PNG를 끌어다 놓기).',
 panel:{normal:'노멀 맵',light:'조명',maps:'맵과 채널',check:'검사',export:'내보내기',frames:'프레임',preview3d:'3D 미리보기'},
 tool:{light:'조명',lightHint:'조명을 끌어 옮기기, 클릭하면 선택한 조명을 그곳으로, Shift+클릭으로 추가, Alt+클릭으로 삭제',brush:'높이 브러시',brushHint:'높이 맵에 굴곡을 칠합니다. Alt는 올리기/내리기를 바꿉니다. [ ]로 크기'},
 view:{albedo:'알베도',height:'높이',normal:'노멀',lit:'조명',ao:'AO',maps:'맵'},
 hud:{label:'텍스처 보기',compare:'비교',tile:'3×3 타일',sheet:'시트',convWarn:'노멀 맵이 {conv}로 읽힘 — 검사'},
 split:{flat:'평면',lit:'조명'},
 status:{working:'맵을 만드는 중…',ready:'{w}×{h} · 맵 {ms} ms',pixel:'x {x} y {y} · 높이 {h} px · 노멀 {n}'},
 conf:{high:'신뢰도 높음',medium:'신뢰도 보통',low:'신뢰도 낮음',none:'판단 불가'},
 normal:{sourceTitle:'소스',source:'노멀 맵',generate:'그림에서 생성',useMap:'{name} 사용',importedHint:'가져온 노멀 맵은 그대로 표시하고 내보냅니다 (검사에서 DirectX로 확인하면 OpenGL로 뒤집습니다). 생성 설정은 숨겨집니다.',kindTitle:'이 그림은'},
 kind:{sprite:'스프라이트',texture:'타일 텍스처',spriteHint:'실루엣이 있습니다: 가장자리에서 굴곡이 올라옵니다(베벨). 커널은 프레임마다 멈춥니다',textureHint:'그림 전체를 채우고 반복됩니다: 베벨 없음, 커널이 반대편으로 이어져 타일링해도 이음새가 없습니다',suggestedSprite:'추정: 투명 픽셀이 있습니다. 틀리면 바꾸세요.',suggestedTexture:'추정: 투명 픽셀이 없습니다. 틀리면 바꾸세요.'},
 bevel:{title:'실루엣에서 베벨',width:'너비',depth:'높이',shape:'단면',metric:'거리'},
 shape:{round:'둥글게',linear:'직선',smooth:'부드럽게',concave:'오목',step:'단'},
 metric:{euclidean:'원형',chebyshev:'사각',manhattan:'마름모',euclideanHint:'실제 거리: 둥근 어깨',chebyshevHint:'체스판 거리: 사각형 고리 (픽셀아트 외곽선)',manhattanHint:'맨해튼 거리: 마름모 고리'},
 luma:{title:'밝기에서 디테일',approx:'근사치: 밝기는 모양이 아니라 칠입니다. 작은 굴곡만 더하고, 형태는 베벨과 브러시가 만듭니다.',depth:'높이',detail:'이보다 넓은 명암 무시',detailHint:'이보다 넓은 밝기 변화(어두운 망토, 밝은 한쪽 면)는 굴곡으로 읽지 않습니다',smooth:'부드럽게',invert:'어두운 곳이 높음'},
 hmap:{title:'높이 맵',source:'높이 소스',none:'없음',depth:'흰색의 높이',hint:'같은 크기의 Height/Displacement 맵. 16비트 파일은 16비트를 모두 씁니다.'},
 nrm:{title:'노멀 맵',strength:'강도',kernel:'커널',edge:'가장자리',convention:'초록'},
 kernel:{central:'픽셀',centralHint:'스무딩 없음: 1픽셀 턱은 1픽셀로 남습니다 (픽셀아트)'},
 edge:{clamp:'고정',tile:'반복',mirror:'반사',clampHint:'가장자리 픽셀을 반복 (스프라이트)',tileHint:'반대편 픽셀을 샘플링: 타일 텍스처에 이음새가 생기지 않습니다',mirrorHint:'가장자리에서 그림을 반사'},
 conv:{opengl:'OpenGL (Y+)',directx:'DirectX (Y−)',openglHint:'초록이 위: Godot, Unity, Blender',directxHint:'초록이 아래: Unreal',title:'노멀 맵 규약',verdict:'{name}은(는) {conv}로 읽힙니다.',cannot:'{name}이(가) 어떤 규약인지 판단할 수 없습니다.',
  reason:{'no-signal':'픽셀에 어느 쪽 신호도 없습니다.','tests-disagree':'두 검사가 서로 다릅니다.','too-small':'쓸 수 있는 픽셀이 너무 적습니다.','no-mixed-slopes':'대각선 굴곡이 없습니다 (곧은 홈이나 경사는 양쪽이 같아 보입니다).'},
  curl:'적분 가능성 검사: ρ = {rho}, 신호의 {agree}%가 일치, {b}개 영역 중 {n}개 유효',sil:'실루엣 검사: 초록 ρ = {rho}, 빨강 ρ = {red}, 가장자리 {n}픽셀',nothing:'판정 없음',
  nameSays:'파일 이름도 {conv}입니다.',nameDisagrees:'파일 이름은 {conv}입니다: 고르기 전에 미리보기를 확인하세요.',declare:'{conv}입니다',redFlipped:'빨강(R)도 뒤집힌 것으로 보입니다 (X−, 오른쪽 가장자리가 왼쪽을 향함): 어느 엔진에서든 좌우가 반대로 조명됩니다. 위 판정은 초록(G)에 대한 것입니다.',redFixed:'불러올 때 빨강을 뒤집습니다 (X−로 확인하셨습니다). 위 검사는 불러온 원본 파일 기준입니다.',flipRed:'빨강 뒤집기 (X−)',declared:'{conv}로 확인됨: 그대로 조명하고 내보냅니다 (Godot·Unity용으로 DirectX는 OpenGL로 뒤집습니다).',notApplied:'규약을 확인하기 전에는 아무것도 바꾸지 않습니다.',
  selfHint:'이 그림 자체가 노멀 맵입니다. 조명을 보려면 알베도의 노멀 맵으로 쓰세요 (노멀 맵 › 소스).',notNormal:'이 픽셀은 노멀 맵처럼 보이지 않습니다 (벡터 길이가 1이 아님).',running:'측정 중…',generated:'생성한 맵은 {conv}로 씁니다. 판별할 것이 없습니다.'},
 brush:{title:'높이 브러시',use:'사용 (B)',size:'크기',strength:'강도',hard:'경도',count:'획 {n}개',hint:'캔버스에 칠하세요. 한 획이 한 번의 실행 취소 단위이며, 시작한 프레임 안에만 칠해집니다.',imported:'브러시는 높이를 칠합니다. 가져온 노멀 맵에는 높이가 없으니 소스를 생성으로 바꾸세요.',
  mode:{raise:'올리기',lower:'내리기',smooth:'부드럽게',flatten:'평평하게',erase:'지우기'}},
 pixel:{title:'픽셀아트 노멀',hint:'손으로 칠한 픽셀아트 노멀처럼 모든 픽셀을 몇 가지 방향과 기울기로 맞춥니다. 픽셀은 선명하게 유지됩니다.',directions:'방향',tiers:'기울기 단계'},
 light:{lights:'조명',n:'조명 {n}',enabled:'켜기',pick:'목록이나 캔버스에서 조명을 고르세요 (조명 도구, L).',hint:'위치는 프레임 픽셀 기준이라 애니메이션의 모든 프레임이 똑같이 비춰집니다. 높이는 조명이 그림 앞쪽으로 떨어진 거리입니다.',selected:'조명 {n}',color:'색',energy:'세기',height:'높이',heightHint:'픽셀 단위 z: 낮으면 굴곡을 스치듯, 높으면 정면에서 비춥니다',radius:'반경',falloff:'감쇠',x:'X',y:'Y',max:'조명은 최대 {n}개입니다.',
  ambientTitle:'주변광',ambient:'주변광 색',ambientHint:'조명이 없는 그림에 곱해집니다 (Godot: CanvasModulate).',specTitle:'스페큘러',specStrength:'강도',shininess:'광택',specHint:'Godot는 스페큘러 맵이 있을 때만 스페큘러를 그립니다. 0보다 크면 맵으로 내보냅니다.',
  rimTitle:'림 라이트 (미리보기 전용)',rimStrength:'강도',rimColor:'색',rimPower:'좁기',rimHint:'미리보기 보조 기능입니다. 커스텀 셰이더 없이 노멀 맵만으로 림 라이트를 그리는 엔진은 없어서 내보내지 않습니다.'},
 falloff:{smooth:'부드럽게',linear:'직선',quadratic:'제곱',constant:'없음'},
 maps:{title:'보기',show:'맵',addTitle:'프로젝트에 추가',addNormal:'노멀 맵',addHeight:'높이 (16비트)',addAO:'AO',addThis:'{name}',addHint:'맵을 그림 옆에 이미지로 추가합니다 (실행 취소 가능).'},
 map:{ao:'AO',cavity:'캐비티',curvature:'곡률',roughness:'러프니스 ≈',specular:'스페큘러 ≈',aoTitle:'앰비언트 오클루전',aoRadius:'반경',aoPower:'대비',aoHint:'높이 필드에서 추정합니다 (각 픽셀이 보는 하늘의 양). 레이 트레이싱이 아닙니다.',approx:'알베도 밝기에서 얻은 근사치: 위에 덧칠할 출발점이지 측정된 재질이 아닙니다.',fromHeight:'높이 필드에서 계산했습니다.'},
 set:{title:'재질 세트',hint:'같은 크기·이름의 맵은 한 세트입니다 (파일 이름 기준). 역할은 여기서 고칠 수 있습니다.',none:'프로젝트에 이 그림의 다른 맵이 없습니다.',role:'{name}의 역할',set:'지정',byName:'이름 기준'},
 role:{albedo:'알베도',normal:'노멀',height:'높이',roughness:'러프니스',smoothness:'스무스니스',metallic:'메탈릭',ao:'AO',orm:'패킹 (ORM/마스크)',emission:'이미션',opacity:'불투명도',specular:'스페큘러',unknown:'—'},
 pack:{title:'채널 패킹',preset:'엔진 배치',zero:'0 (검정)',one:'255 (흰색)',genAO:'생성한 AO',genHeight:'생성한 높이',genRough:'러프니스 ≈ (알베도에서)',genSpec:'스페큘러 ≈ (알베도에서)',gray:'회색',invert:'반전',make:'패킹하고 다운로드',hint:'바이트를 그대로 복사합니다 (색 변환 없음). 패킹한 이미지는 프로젝트에도 추가됩니다.',missing:'소스 맵을 쓸 수 없습니다.',done:'{name}을(를) 패킹했습니다.'},
 unpack:{title:'채널 분리',hint:'열린 그림을 정확한 그레이스케일 PNG 네 장(R, G, B, A)으로 나눕니다.',go:'{name} 분리'},
 seam:{title:'이음새 (타일)',roll:'반복 검사 ({edge}): 가장자리 차이 평균 {b}, 최대 {m} (0 = 이음새 없음).',rollOk:'✓ 반복 정확: 텍스처를 어떻게 밀어도 맵이 똑같습니다.',rollBad:'가장자리가 안쪽과 다르게 계산됩니다: 타일 텍스처에는 반복을 고르세요.',albedo:'알베도 이음새 비율 {r} (1 ≈ 보이는 이음새 없음).',albedoOk:'알베도 자체가 타일링됩니다.',albedoBad:'알베도 자체가 반복되는 곳에 이음새가 보입니다. 노멀 맵으로는 숨길 수 없습니다.',running:'측정 중…',hint:'반복 검사는 텍스처를 절반 밀어 맵을 다시 만든 뒤 비교합니다.'},
 mip:{title:'노멀 맵 밉맵',hint:'엔진이 해야 하듯 벡터로 평균 내고 다시 정규화합니다. 단순 색 평균은 멀리서 조명을 평평하게 만듭니다.',show:'밉맵 보기',refresh:'새로 고침'},
 export:{targets:'대상',target:{godot:'Godot 4',unity:'Unity 6 (URP 2D)',generic:'PNG 세트 + JSON'},verified:'✓ {engine}에서 검증',unverified:'엔진 렌더로 미검증 (UNVERIFIED)',plain:'일반 파일',
  what:{godot:'CanvasTexture, Sprite2D, PointLight2D, CanvasModulate, 애니메이션',unity:'Secondary Texture _NormalMap + 에디터 임포터 + Light2D 도우미',generic:'알베도, 노멀 (OpenGL + DirectX), 16비트 높이, AO, 매니페스트'},
  options:'옵션',height16:'16비트 높이 맵',ao:'앰비언트 오클루전',bleed:'알베도 가장자리 번짐 (px)',bleedHint:'가장자리 색을 투명 픽셀로 복사해 필터링과 밉맵이 외곽선을 어둡게 하지 않게 합니다 (0 = 알베도 PNG가 바이트 그대로).',
  go:'ZIP 내보내기',quick:'노멀 맵 PNG · {conv}',none:'대상을 하나 이상 고르세요.',done:'파일 {n}개를 내보냈습니다.',hint:'모든 작업은 이 브라우저에서 이뤄지며 업로드하지 않습니다.',notReady:'맵이 아직 준비되지 않았습니다.'},
 frames:{none:'이 그림에는 프레임이 없습니다. 애니메이션을 비추려면 스프라이트 작업 공간에서 프레임을 자르세요.',tag:'애니메이션',all:'모든 프레임',play:'재생',pause:'일시 정지',hint:', 와 . 로 프레임 이동'},
 p3d:{label:'재질 3D 미리보기',noGL:'WebGL2를 쓸 수 없어 3D 미리보기가 없습니다.',shape:'모양',sphere:'구',plane:'평면',auto:'회전',rough:'러프니스',metal:'메탈릭',constant:'상수',generated:'생성됨',generatedAO:'생성한 AO',hint:'끌어서 돌리세요. 없는 맵은 상수입니다.'},
 cmd:{kind:'그림 종류',bevel:'베벨',luma:'밝기 디테일',hmap:'높이 맵',strength:'노멀 강도',kernel:'커널',edge:'가장자리 방식',convention:'노멀 규약',pixel:'픽셀아트 노멀',source:'노멀 맵 소스',paint:'높이 칠하기 ({mode})',clearPaint:'칠한 높이 지우기',addLight:'조명 추가',removeLight:'조명 삭제',moveLight:'조명 이동',light:'조명 편집',lightHeight:'조명 높이',scene:'조명 설정',compare:'조명/평면 비교',tile:'3×3 타일 미리보기',scope:'시트 전체',export:'내보내기…',smaller:'브러시 작게 / 조명 낮게',bigger:'브러시 크게 / 조명 높게',ao:'AO 설정',role:'맵 역할',declare:'노멀 맵 규약',flipRed:'빨강 채널 뒤집기'},
 toast:{added:'이미지 {n}개를 프로젝트에 추가했습니다.'}
},
ja:{
 menu:'テクスチャ',noImage:'法線マップを作るスプライトかテクスチャを開いてください（ファイル › 読み込み、または PNG をドロップ）。',
 panel:{normal:'法線マップ',light:'ライティング',maps:'マップとチャンネル',check:'チェック',export:'書き出し',frames:'フレーム',preview3d:'3D プレビュー'},
 tool:{light:'ライト',lightHint:'ライトをドラッグ、クリックで選択中のライトを移動、Shift+クリックで追加、Alt+クリックで削除',brush:'高さブラシ',brushHint:'高さマップに起伏を描きます。Alt で上げる/下げるを反転。[ ] でサイズ'},
 view:{albedo:'アルベド',height:'高さ',normal:'法線',lit:'ライティング',ao:'AO',maps:'マップ'},
 hud:{label:'テクスチャ表示',compare:'比較',tile:'3×3 タイル',sheet:'シート',convWarn:'法線マップは {conv} と読めます — チェック'},
 split:{flat:'フラット',lit:'ライト'},
 status:{working:'マップを作成中…',ready:'{w}×{h} · マップ {ms} ms',pixel:'x {x} y {y} · 高さ {h} px · 法線 {n}'},
 conf:{high:'信頼度 高',medium:'信頼度 中',low:'信頼度 低',none:'判定できません'},
 normal:{sourceTitle:'ソース',source:'法線マップ',generate:'画像から生成',useMap:'{name} を使う',importedHint:'読み込んだ法線マップはそのまま表示・書き出しします（チェックで DirectX と確認すると OpenGL に反転）。生成設定は隠れます。',kindTitle:'この画像は'},
 kind:{sprite:'スプライト',texture:'タイル テクスチャ',spriteHint:'シルエットがあります：縁から起伏が立ち上がります（ベベル）。カーネルはフレームごとに止まります',textureHint:'画像全体を埋めて繰り返します：ベベルなし、カーネルが反対側へ回り込むので、タイルしても継ぎ目がありません',suggestedSprite:'推定：透明ピクセルがあります。違う場合は変更してください。',suggestedTexture:'推定：透明ピクセルがありません。違う場合は変更してください。'},
 bevel:{title:'シルエットからベベル',width:'幅',depth:'高さ',shape:'断面',metric:'距離'},
 shape:{round:'丸',linear:'直線',smooth:'なめらか',concave:'凹',step:'段'},
 metric:{euclidean:'円',chebyshev:'四角',manhattan:'ひし形',euclideanHint:'実距離：丸い肩',chebyshevHint:'チェス盤距離：四角いリング（ピクセルアートの輪郭）',manhattanHint:'マンハッタン距離：ひし形のリング'},
 luma:{title:'明るさからディテール',approx:'近似：明るさは形ではなく塗りです。小さな起伏を足すだけで、形はベベルとブラシが作ります。',depth:'高さ',detail:'これより広い陰影は無視',detailHint:'これより広い明るさの変化（暗いマント、明るい片側）は起伏として読みません',smooth:'なめらか',invert:'暗い所が高い'},
 hmap:{title:'高さマップ',source:'高さの元',none:'なし',depth:'白の高さ',hint:'同じサイズの Height/Displacement マップ。16 ビットのファイルは 16 ビットすべてを使います。'},
 nrm:{title:'法線マップ',strength:'強さ',kernel:'カーネル',edge:'端',convention:'緑'},
 kernel:{central:'ピクセル',centralHint:'平滑化なし：1 ピクセルの段は 1 ピクセルのまま（ピクセルアート）'},
 edge:{clamp:'クランプ',tile:'ラップ',mirror:'ミラー',clampHint:'端のピクセルを繰り返す（スプライト）',tileHint:'反対側をサンプリング：タイル テクスチャに継ぎ目が出ません',mirrorHint:'端で画像を反射'},
 conv:{opengl:'OpenGL (Y+)',directx:'DirectX (Y−)',openglHint:'緑が上：Godot、Unity、Blender',directxHint:'緑が下：Unreal',title:'法線マップの規約',verdict:'{name} は {conv} と読めます。',cannot:'{name} の規約は判定できません。',
  reason:{'no-signal':'どちらの信号もありません。','tests-disagree':'2 つの検査が一致しません。','too-small':'使えるピクセルが少なすぎます。','no-mixed-slopes':'斜めの起伏がありません（まっすぐな溝や傾斜はどちらでも同じに見えます）。'},
  curl:'可積分性検査：ρ = {rho}、信号の {agree}% が一致、{b} 領域中 {n} が有効',sil:'シルエット検査：緑 ρ = {rho}、赤 ρ = {red}、縁 {n} ピクセル',nothing:'判定なし',
  nameSays:'ファイル名も {conv} です。',nameDisagrees:'ファイル名は {conv} です：選ぶ前にプレビューを確認してください。',declare:'{conv} です',redFlipped:'赤（R）も反転しているようです（X−、右向きの縁が左を向いています）：どのエンジンでも左右が逆に照らされます。上の判定は緑（G）についてのものです。',redFixed:'読み込み時に赤を反転します（X− と確認済み）。上の検査は読み込んだ元のファイルについてです。',flipRed:'赤を反転（X−）',declared:'{conv} と確認済み：そのまま照明・書き出しします（Godot・Unity 向けに DirectX は OpenGL へ反転）。',notApplied:'規約を確認するまで何も変更しません。',
  selfHint:'この画像自体が法線マップです。照明するにはアルベドの法線マップとして使ってください（法線マップ › ソース）。',notNormal:'このピクセルは法線マップに見えません（ベクトル長が 1 ではない）。',running:'測定中…',generated:'生成したマップは {conv} で書き出します。判定の必要はありません。'},
 brush:{title:'高さブラシ',use:'使う (B)',size:'サイズ',strength:'強さ',hard:'硬さ',count:'ストローク {n}',hint:'キャンバスに描いてください。1 ストロークが 1 回の取り消し単位で、描き始めたフレームの中だけに描かれます。',imported:'ブラシは高さを描きます。読み込んだ法線マップには高さがないので、ソースを生成に切り替えてください。',
  mode:{raise:'上げる',lower:'下げる',smooth:'なめらか',flatten:'平らに',erase:'消す'}},
 pixel:{title:'ピクセルアート法線',hint:'手描きのピクセルアート法線のように、各ピクセルを少数の方向と傾きにそろえます。ピクセルはくっきりしたままです。',directions:'方向',tiers:'傾きの段数'},
 light:{lights:'ライト',n:'ライト {n}',enabled:'オン',pick:'リストかキャンバスでライトを選んでください（ライト ツール、L）。',hint:'位置はフレームのピクセル単位なので、アニメーションの全フレームが同じように照らされます。高さはライトが画像の手前にある距離です。',selected:'ライト {n}',color:'色',energy:'強さ',height:'高さ',heightHint:'ピクセル単位の z：低いと起伏をかすめ、高いと正面から照らします',radius:'半径',falloff:'減衰',x:'X',y:'Y',max:'ライトは最大 {n} 個です。',
  ambientTitle:'環境光',ambient:'環境光の色',ambientHint:'照明のない画像に掛けられます（Godot：CanvasModulate）。',specTitle:'スペキュラー',specStrength:'強さ',shininess:'光沢',specHint:'Godot はスペキュラーマップがあるときだけスペキュラーを描きます。0 より大きいとマップとして書き出します。',
  rimTitle:'リムライト（プレビューのみ）',rimStrength:'強さ',rimColor:'色',rimPower:'狭さ',rimHint:'プレビュー用の補助です。カスタムシェーダーなしに法線マップだけでリムライトを描くエンジンはないため、書き出しません。'},
 falloff:{smooth:'なめらか',linear:'直線',quadratic:'二乗',constant:'なし'},
 maps:{title:'表示',show:'マップ',addTitle:'プロジェクトに追加',addNormal:'法線マップ',addHeight:'高さ（16 ビット）',addAO:'AO',addThis:'{name}',addHint:'マップを画像の隣に追加します（取り消し可能）。'},
 map:{ao:'AO',cavity:'キャビティ',curvature:'曲率',roughness:'ラフネス ≈',specular:'スペキュラー ≈',aoTitle:'アンビエントオクルージョン',aoRadius:'半径',aoPower:'コントラスト',aoHint:'高さフィールドから推定（各ピクセルが見る空の量）。レイトレースではありません。',approx:'アルベドの明るさからの近似：上から塗るための出発点で、測定した材質ではありません。',fromHeight:'高さフィールドから計算しました。'},
 set:{title:'マテリアル セット',hint:'同じサイズ・名前のマップは 1 セットです（ファイル名による）。役割はここで直せます。',none:'プロジェクトにこの画像の他のマップはありません。',role:'{name} の役割',set:'指定',byName:'名前から'},
 role:{albedo:'アルベド',normal:'法線',height:'高さ',roughness:'ラフネス',smoothness:'スムースネス',metallic:'メタリック',ao:'AO',orm:'パック（ORM/マスク）',emission:'エミッション',opacity:'不透明度',specular:'スペキュラー',unknown:'—'},
 pack:{title:'チャンネル パック',preset:'エンジンの配置',zero:'0（黒）',one:'255（白）',genAO:'生成した AO',genHeight:'生成した高さ',genRough:'ラフネス ≈（アルベドから）',genSpec:'スペキュラー ≈（アルベドから）',gray:'グレー',invert:'反転',make:'パックしてダウンロード',hint:'バイトをそのままコピーします（色変換なし）。パックした画像はプロジェクトにも追加されます。',missing:'元のマップが使えません。',done:'{name} をパックしました。'},
 unpack:{title:'チャンネル分解',hint:'開いている画像を正確なグレースケール PNG 4 枚（R、G、B、A）に分けます。',go:'{name} を分解'},
 seam:{title:'継ぎ目（タイル）',roll:'ラップ検査（{edge}）：端の差 平均 {b}、最大 {m}（0 = 継ぎ目なし）。',rollOk:'✓ ラップ正確：テクスチャをどうずらしてもマップは同一です。',rollBad:'端が内側と違う方法で計算されています：タイル テクスチャにはラップを選んでください。',albedo:'アルベドの継ぎ目比 {r}（1 ≈ 見える継ぎ目なし）。',albedoOk:'アルベド自体がタイルします。',albedoBad:'アルベド自体の繰り返し部分に継ぎ目が見えます。法線マップでは隠せません。',running:'測定中…',hint:'ラップ検査はテクスチャを半分ずらしてマップを作り直し、比較します。'},
 mip:{title:'法線マップのミップマップ',hint:'エンジンがすべきようにベクトルとして平均し、再正規化します。単純な色の平均は遠くで照明を平らにします。',show:'ミップマップを表示',refresh:'更新'},
 export:{targets:'対象',target:{godot:'Godot 4',unity:'Unity 6（URP 2D）',generic:'PNG セット + JSON'},verified:'✓ {engine} で検証済み',unverified:'エンジン描画で未検証（UNVERIFIED）',plain:'通常ファイル',
  what:{godot:'CanvasTexture、Sprite2D、PointLight2D、CanvasModulate、アニメーション',unity:'Secondary Texture _NormalMap + エディター インポーター + Light2D ヘルパー',generic:'アルベド、法線（OpenGL + DirectX）、16 ビット高さ、AO、マニフェスト'},
  options:'オプション',height16:'16 ビット高さマップ',ao:'アンビエントオクルージョン',bleed:'アルベドの縁のにじみ（px）',bleedHint:'縁の色を透明ピクセルへコピーし、フィルタリングやミップマップで輪郭が暗くならないようにします（0 = アルベド PNG はバイト単位で同一）。',
  go:'ZIP を書き出し',quick:'法線マップ PNG · {conv}',none:'対象を 1 つ以上選んでください。',done:'{n} ファイルを書き出しました。',hint:'すべてこのブラウザ内で処理し、アップロードしません。',notReady:'マップの準備がまだです。'},
 frames:{none:'この画像にはフレームがありません。アニメーションを照らすにはスプライト ワークスペースでフレームを切り出してください。',tag:'アニメーション',all:'全フレーム',play:'再生',pause:'一時停止',hint:', と . でフレーム移動'},
 p3d:{label:'マテリアルの 3D プレビュー',noGL:'WebGL2 が使えないため 3D プレビューはありません。',shape:'形',sphere:'球',plane:'平面',auto:'回転',rough:'ラフネス',metal:'メタリック',constant:'定数',generated:'生成',generatedAO:'生成した AO',hint:'ドラッグで回転。ないマップは定数です。'},
 cmd:{kind:'画像の種類',bevel:'ベベル',luma:'明るさのディテール',hmap:'高さマップ',strength:'法線の強さ',kernel:'カーネル',edge:'端の扱い',convention:'法線の規約',pixel:'ピクセルアート法線',source:'法線マップのソース',paint:'高さを描く（{mode}）',clearPaint:'描いた高さを消す',addLight:'ライトを追加',removeLight:'ライトを削除',moveLight:'ライトを移動',light:'ライトを編集',lightHeight:'ライトの高さ',scene:'ライティング',compare:'ライト/フラットを比較',tile:'3×3 タイル プレビュー',scope:'シート全体',export:'書き出し…',smaller:'ブラシを小さく / ライトを低く',bigger:'ブラシを大きく / ライトを高く',ao:'AO 設定',role:'マップの役割',declare:'法線マップの規約',flipRed:'赤チャンネルを反転'},
 toast:{added:'画像 {n} 枚をプロジェクトに追加しました。'}
}};
export const TEX_GROUP={en:'Texture',ko:'텍스처',ja:'テクスチャ'};
for(const l of Object.keys(TEX_STRINGS)){if(!STUDIO_STRINGS[l])continue;STUDIO_STRINGS[l].tex=TEX_STRINGS[l];STUDIO_STRINGS[l].group={...(STUDIO_STRINGS[l].group||{}),texture:TEX_GROUP[l]};}
