import {COPY} from './strings.js';
const locale=document.documentElement.lang in COPY?document.documentElement.lang:'en',c=COPY[locale],$=s=>document.querySelector(s),worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});
let seq=0,waiting=new Map(),duration=0,peaks=null,fileName='audio',previewUrl='',drag=null;
const editIds=['start','end','fadeIn','fadeOut','speed','pitch','target','silence','snap'];let history=[],historyIndex=-1;
function snapshot(){return Object.fromEntries(editIds.map(id=>[id,$('#'+id).type==='checkbox'?$('#'+id).checked:$('#'+id).value]));}
function historyButtons(){$('#undo').disabled=historyIndex<=0;$('#redo').disabled=historyIndex<0||historyIndex>=history.length-1;}
function recordEdit(){if(!duration)return;const state=snapshot();if(JSON.stringify(state)===JSON.stringify(history[historyIndex]))return;history=history.slice(0,historyIndex+1);history.push(state);historyIndex=history.length-1;historyButtons();}
function restoreEdit(index){if(index<0||index>=history.length)return;historyIndex=index;for(const [id,value] of Object.entries(history[index])){const input=$('#'+id);if(input.type==='checkbox')input.checked=value;else input.value=value;}historyButtons();redraw();}
const status=(message,error=false)=>{$('#status').textContent=message;$('#status').toggleAttribute('data-error',error);};
function errorText(error){const m=String(error.message||error);if(m.includes('under 128 MiB'))return c.fileLimit;if(m.includes('96 MiB mobile memory'))return c.decodedLimit;if(m.includes('Output exceeds the 3 minute'))return c.outputLimit;if(m.includes('Unsupported duration, channel count'))return c.unsupportedFile;return `${c.error} ${m}`;}
worker.onmessage=({data:m})=>{if(m.type==='progress'){status(`${c.busy} ${m.seconds.toFixed(1)} ${c.secs}`);return;}const request=waiting.get(m.id);if(!request)return;waiting.delete(m.id);m.type==='error'?request.reject(Error(m.message)):request.resolve(m);};
worker.onerror=e=>{for(const request of waiting.values())request.reject(Error(e.message));waiting.clear();status(c.error+' '+e.message,true);};
function job(type,extra={}){const id=++seq;return new Promise((resolve,reject)=>{waiting.set(id,{resolve,reject});worker.postMessage({id,type,...extra});});}
function busy(active){for(const id of ['file','analyze','preview','save'])$('#'+id).disabled=active||(id!=='file'&&!duration);}
function fmt(value,digits=1){return Number.isFinite(value)?new Intl.NumberFormat(locale,{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(value):'—';}
function showMeter(m){for(const [id,value] of [['lufs',m.integrated],['momentary',m.momentary],['shortTerm',m.shortTerm]])$('#'+id).textContent=value===null?c.unknown:`${fmt(value)} LUFS`;$('#peak').textContent=m.samplePeak===null?'—':`${fmt(m.samplePeak)} dBFS`;}
function settings(){const start=Number($('#start').value),end=Number($('#end').value),fadeIn=Number($('#fadeIn').value),fadeOut=Number($('#fadeOut').value),speed=Number($('#speed').value),semitones=Number($('#pitch').value),rawTarget=$('#target').value;
 if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end>duration+.001||end-start<.01||!Number.isFinite(fadeIn)||!Number.isFinite(fadeOut)||fadeIn<0||fadeOut<0||!Number.isFinite(speed)||speed<.5||speed>2||!Number.isFinite(semitones)||Math.abs(semitones)>12)throw Error(c.uncertain+' — '+c.selection);
 return {start,end,fadeIn,fadeOut,speed,semitones,removeSilence:$('#silence').checked,snapToZero:$('#snap').checked,targetLufs:rawTarget===''?null:Number(rawTarget)};}
function viewport(){const zoom=Number($('#zoom').value)||1,length=duration/zoom,start=zoom===1?0:Math.min(Math.max(0,Number($('#start').value)||0),Math.max(0,duration-length));return {start,end:start+length};}
function redraw(){const canvas=$('#wave'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.fillStyle='#0a1425';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#314a62';ctx.beginPath();ctx.moveTo(0,h/2+.5);ctx.lineTo(w,h/2+.5);ctx.stroke();if(!peaks||!duration)return;
 const view=viewport(),a=Number($('#start').value),b=Number($('#end').value),x=t=>(t-view.start)/(view.end-view.start)*w;
 ctx.fillStyle='#1e4858';ctx.fillRect(Math.max(0,x(a)),0,Math.max(0,Math.min(w,x(b))-Math.max(0,x(a))),h);
 ctx.strokeStyle='#7ee2cd';ctx.lineWidth=2;ctx.beginPath();for(let px=0;px<w;px++){const t=view.start+(px+.5)/w*(view.end-view.start),index=Math.min(peaks.length/2-1,Math.floor(t/duration*(peaks.length/2))),lo=peaks[index*2],hi=peaks[index*2+1];ctx.moveTo(px+.5,h/2-hi*h*.43);ctx.lineTo(px+.5,h/2-lo*h*.43);}ctx.stroke();
 ctx.strokeStyle='#e9ba68';for(const t of [a,b]){const xx=x(t);if(xx>=0&&xx<=w){ctx.beginPath();ctx.moveTo(xx+.5,0);ctx.lineTo(xx+.5,h);ctx.stroke();}}
}
async function load(file){if(!file)return;try{for(const request of waiting.values())request.reject(Error('Replaced by a new file'));waiting.clear();duration=0;peaks=null;history=[];historyIndex=-1;historyButtons();fileName=file.name.replace(/\.[^.]+$/,'').replace(/[^\p{L}\p{N}_-]+/gu,'-').slice(0,70)||'audio';$('#tempo').textContent=$('#key').textContent=$('#confidence').textContent='—';$('#analysisNote').textContent=$('#alternatives').textContent='';for(const id of ['lufs','momentary','shortTerm','peak'])$('#'+id).textContent='—';busy(true);status(c.busy);const result=await job('load',{file});duration=result.duration;peaks=result.peaks;$('#fileInfo').textContent=`${file.name} · ${fmt(duration)} ${c.secs} · ${result.rate.toLocaleString(locale)} Hz · ${result.channels} ch`;$('#start').value='0';$('#end').value=String(duration);$('#start').max=$('#end').max=String(duration);$('#zoom').value='1';$('#fadeIn').value='0.1';$('#fadeOut').value='0.1';$('#speed').value='1';$('#pitch').value='0';$('#target').value='';$('#silence').checked=false;$('#snap').checked=true;recordEdit();busy(false);status(c.loaded);redraw();}
 catch(error){status(errorText(error),true);busy(false);redraw();}}
async function analyzeFile(){try{busy(true);status(c.busy);const m=await job('analyze');const t=m.result.tempo,k=m.result.key;$('#tempo').textContent=t.bpm===null?c.unknown:`${fmt(t.bpm)} BPM`;$('#key').textContent=k.key||c.unknown;const confidence=Math.min(t.confidence,k.confidence);$('#confidence').textContent=`${fmt(confidence*100,0)}%`;
  $('#analysisNote').textContent=[t.reason==='half-double'?c.halfDouble:t.reason?c.uncertain:'',k.reason?c.low:''].filter(Boolean).join(' ');$('#alternatives').textContent=t.candidates.length?`${c.alternatives}: ${t.candidates.map(v=>fmt(v)).join(' / ')} BPM`:'';
  showMeter(m.meter);status(c.loaded);
 }catch(error){status(errorText(error),true);}finally{busy(false);}}
async function render(format,play){try{const state=settings();busy(true);status(c.busy);const m=await job('render',{settings:state,format});const type={wav:'audio/wav',ogg:'audio/ogg',mp3:'audio/mpeg'}[format],url=URL.createObjectURL(new Blob([m.bytes],{type}));if(play){if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=url;$('#player').src=url;$('#player').play().catch(()=>{});$('#stop').disabled=false;}else{const link=document.createElement('a');link.href=url;link.download=`${fileName}-edited.${format}`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}status(`${c.done} ${fmt(m.duration,2)} ${c.secs}${m.peakProtection?.appliedDb<-.01?' '+c.peakProtected:''}`);showMeter(m.meter);}
 catch(error){status(errorText(error),true);}finally{busy(false);}}
$('#file').addEventListener('change',e=>{load(e.target.files?.[0]);e.target.value='';});
const dropzone=$('#dropzone');dropzone.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();dropzone.querySelector('.al-file').dataset.hover='1';}});dropzone.addEventListener('dragleave',()=>delete dropzone.querySelector('.al-file').dataset.hover);dropzone.addEventListener('drop',e=>{e.preventDefault();delete dropzone.querySelector('.al-file').dataset.hover;load(e.dataTransfer.files?.[0]);});
addEventListener('paste',e=>{const file=e.clipboardData?.files?.[0];if(file){e.preventDefault();load(file);}});
$('#analyze').onclick=analyzeFile;$('#preview').onclick=()=>render('wav',true);$('#save').onclick=()=>render($('#format').value,false);$('#stop').onclick=()=>{$('#player').pause();$('#player').currentTime=0;};
$('#undo').onclick=()=>restoreEdit(historyIndex-1);$('#redo').onclick=()=>restoreEdit(historyIndex+1);
for(const id of editIds)$('#'+id).addEventListener('change',recordEdit);
addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.altKey||e.key.toLowerCase()!=='z'||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault();restoreEdit(historyIndex+(e.shiftKey?1:-1));});
for(const id of ['start','end','zoom'])$('#'+id).addEventListener('input',redraw);
$('#wave').addEventListener('pointerdown',e=>{if(!duration)return;const rect=e.currentTarget.getBoundingClientRect(),view=viewport(),time=view.start+Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width))*(view.end-view.start);drag=Math.min(time,Math.max(0,duration-.01));e.currentTarget.setPointerCapture(e.pointerId);$('#start').value=String(drag);$('#end').value=String(Math.min(duration,drag+.01));redraw();});
$('#wave').addEventListener('pointermove',e=>{if(drag===null)return;const rect=e.currentTarget.getBoundingClientRect(),view=viewport(),time=view.start+Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width))*(view.end-view.start);$('#start').value=String(Math.max(0,Math.min(drag,time,duration-.01)));$('#end').value=String(Math.min(duration,Math.max(drag+.01,time)));redraw();});
for(const event of ['pointerup','pointercancel'])$('#wave').addEventListener(event,()=>{if(drag!==null)recordEdit();drag=null;});
redraw();
