// @ts-check
/** Helpers shared by the AI-vertical adapters (status feeds, changelogs, GitHub releases).
 * Pure functions only — no network. This folder has no index.js, so collect.mjs does not treat
 * it as an adapter. */

/** @param {()=>number} now */
export const isoDay=now=>new Date(now()).toISOString().slice(0,10);

/** ISO timestamp at second precision ("2026-09-22T02:35:23Z") — the event validator accepts
 * `YYYY-MM-DDTHH:MM(:SS)?(Z|±HH:MM)` without fractional seconds. Returns undefined when unparsable. */
export function isoSec(/** @type {unknown} */ s){
 if(typeof s!=='string'&&typeof s!=='number')return undefined;
 const d=new Date(s);if(Number.isNaN(d.getTime()))return undefined;
 return d.toISOString().replace(/\.\d{3}Z$/,'Z');
}

const NAMED={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};
/** Decode XML/HTML character references (named subset + numeric). */
export function decodeEntities(/** @type {string} */ s){
 return String(s).replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi,(m,k)=>{
  if(k[0]==='#'){const n=k[1]==='x'||k[1]==='X'?parseInt(k.slice(2),16):parseInt(k.slice(1),10);return Number.isFinite(n)&&n>0&&n<0x110000?String.fromCodePoint(n):m;}
  return NAMED[/** @type {keyof typeof NAMED} */(k.toLowerCase())]??m;
 });
}
/** Unwrap CDATA, else decode entities. */
export function xmlText(/** @type {string|undefined} */ s){
 if(s==null)return '';
 const c=/^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/.exec(s);
 return c?c[1]:decodeEntities(s);
}
/** HTML → plain text (block tags become newlines). */
export function stripTags(/** @type {string} */ html){
 return decodeEntities(String(html).replace(/<(br|\/p|\/li|\/div|\/h\d)\b[^>]*>/gi,'\n').replace(/<[^>]*>/g,'')).replace(/[ \t]+/g,' ').replace(/\n\s*\n+/g,'\n').trim();
}
/** Markdown inline → plain text: links keep their label, code/bold/italic markers dropped. */
export function mdPlain(/** @type {string} */ s){
 return String(s).replace(/!\[[^\]]*\]\([^)]*\)/g,'').replace(/\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\*\*|__|`/g,'').replace(/(^|\s)[*_](\S[^*_]*?)[*_](?=\s|$|[.,;:])/g,'$1$2').replace(/\s+/g,' ').trim();
}
/** First sentence (or the whole string), clipped to `max` characters on a word boundary. */
export function headline(/** @type {string} */ s,max=160){
 const t=String(s).trim();const m=/^(.+?[.!?])(\s|$)/.exec(t);let h=m&&m[1].length>=20?m[1]:t;
 if(h.length>max){h=h.slice(0,max-1);const i=h.lastIndexOf(' ');h=(i>max*0.6?h.slice(0,i):h).replace(/[\s,;:·-]+$/,'')+'…';}
 return h;
}

/** Array of `{atom entry}` objects: {id,title,link,published,updated,summary,content}. Tolerant, regex-based
 * (the feeds are machine-generated by Atlassian Statuspage / incident.io). */
export function parseAtom(/** @type {string} */ xml){
 const out=[];const tag=(/** @type {string} */ block,/** @type {string} */ name)=>{const m=new RegExp(`<${name}\\b[^>]*>([\\s\\S]*?)</${name}>`).exec(block);return m?m[1]:undefined;};
 for(const m of String(xml).matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/g)){
  const b=m[1];const link=/<link\b[^>]*href="([^"]+)"/.exec(b);
  out.push({id:xmlText(tag(b,'id')).trim(),title:xmlText(tag(b,'title')).trim(),link:link?decodeEntities(link[1]):'',published:xmlText(tag(b,'published')).trim()||undefined,updated:xmlText(tag(b,'updated')).trim()||undefined,summary:xmlText(tag(b,'summary')),content:xmlText(tag(b,'content'))});
 }
 return out;
}

const esc=(/** @type {string} */ s)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
/**
 * Build a matcher that finds seed entities named in free text. Terms = names.en, aliases and the
 * `api_model_id` fact. Boundaries stop "Claude Opus 5" from matching inside "Claude Opus 5.5".
 * @param {any[]} targets ctx.targets @param {{types?:string[],minLength?:number}} [o]
 * @returns {(text:string)=>string[]}
 */
export function entityMatcher(targets,o={}){
 const types=o.types,min=o.minLength??4;
 /** @type {{id:string,re:RegExp}[]} */const rules=[];
 for(const t of targets||[]){
  if(types&&!types.includes(t.type))continue;
  const terms=new Set([t.names?.en,...(t.aliases||[]),t.facts?.api_model_id].filter(x=>typeof x==='string'&&x.trim().length>=min).map(x=>x.trim()));
  // …nor "GPT-6 Astra" inside "GPT-6 Astra Pro" (a different variant): common variant suffix words block a match.
  for(const term of terms)rules.push({id:t.id,re:new RegExp(`(?<![A-Za-z0-9._-])${esc(term)}(?![A-Za-z0-9]|[._-][A-Za-z0-9]|\\s+(?:Pro|mini|nano|Instant|Thinking|Lite|Flash|Max|Turbo|Preview|Codex|Image|Live|TTS)\\b)`,'i')});
 }
 return text=>{const s=String(text||'');const ids=new Set();for(const r of rules)if(!ids.has(r.id)&&r.re.test(s))ids.add(r.id);return [...ids];};
}
/** Model entity ids whose api_model_id (or id key) equals one of `apiIds`. */
export function modelsByApiId(/** @type {any[]} */ targets,/** @type {string[]} */ apiIds){
 const want=new Set(apiIds.map(x=>x.toLowerCase()));const ids=new Set();
 for(const t of targets||[])if(t.type==='model'){
  const api=String(t.facts?.api_model_id||'').toLowerCase(),key=String(t.id).slice(6);
  if(want.has(api)||want.has(key))ids.add(t.id);
 }
 return [...ids];
}
/** Backticked identifiers in markdown (`gemini-3.8-live`). */
export const codeSpans=(/** @type {string} */ md)=>[...String(md).matchAll(/`([A-Za-z0-9][A-Za-z0-9._:/-]{1,80})`/g)].map(m=>m[1]);

/** 'release' when the text announces a launch/GA, else 'update'. */
export function changeKind(/** @type {string} */ text){
 return /\b(released|launch(ed|ing)|introduc(ed|ing)|now (generally )?available|generally available|\(GA\)|is now GA)\b/i.test(text)?'release':'update';
}
/** Keep events whose `starts` is within `days` of now (and not in the future by more than a day). */
export function withinDays(/** @type {string|undefined} */ iso,/** @type {number} */ days,/** @type {number} */ nowMs){
 if(!iso)return false;const t=Date.parse(iso.length===10?iso+'T00:00:00Z':iso);
 return Number.isFinite(t)&&t>=nowMs-days*864e5&&t<=nowMs+864e5;
}
export const MONTHS=['january','february','march','april','may','june','july','august','september','october','november','december'];
/** "September 22, 2026" | "Sep 22, 2026" → "2026-09-22" (undefined when not a date). */
export function parseLongDate(/** @type {string} */ s){
 const m=/^\s*([A-Za-z]+)\.?\s+(\d{1,2}),?\s+(\d{4})\s*$/.exec(s);if(!m)return undefined;
 const mi=MONTHS.findIndex(x=>x.startsWith(m[1].toLowerCase().slice(0,3)));if(mi<0)return undefined;
 return `${m[3]}-${String(mi+1).padStart(2,'0')}-${m[2].padStart(2,'0')}`;
}
/** Only ids that exist in `known` (a Set) — or all ids when `known` is empty (unit tests, partial runs). */
export const onlyKnown=(/** @type {string[]} */ ids,/** @type {Set<string>} */ known)=>known.size?ids.filter(i=>known.has(i)):ids;
