// @ts-check
import {defineVertical,prop,COMMON_PROPS} from './_define.js';
const USD={unit:'USD'};
export default defineVertical({
 id:'ai',icon:'spark',maturity:'LIVE',
 label:{en:'AI',ko:'AI'},
 tagline:{en:'Models, plans, features and what changed',ko:'모델·요금제·기능, 그리고 무엇이 바뀌었는지'},
 hubTypes:['model','feature','plan','service','provider','runtime'],
 types:{
  provider:{label:{en:'Provider',ko:'제공사'},plural:{en:'Providers',ko:'제공사'},icon:'building',props:['hq_country','homepage'],sections:['overview','services','models','changes','community'],indexMin:3},
  service:{label:{en:'Service',ko:'서비스'},plural:{en:'Services',ko:'서비스'},icon:'app',props:['release_date','platforms','homepage','status_page'],sections:['overview','plans','features','availability','incidents','changes','community'],indexMin:3},
  plan:{label:{en:'Plan',ko:'요금제'},plural:{en:'Plans',ko:'요금제'},icon:'tag',props:['price_monthly','price_yearly','price_note','seats_min'],sections:['overview','pricing','models','features','changes','community'],indexMin:2},
  model:{label:{en:'Model',ko:'모델'},plural:{en:'Models',ko:'모델'},icon:'cube',props:['status','release_date','context_window','max_output','knowledge_cutoff','input_modalities','output_modalities','api_input_price','api_output_price','api_cached_input_price','open_weights','parameters_b','active_parameters_b','license','deprecation_date','api_model_id'],sections:['overview','availability','pricing','local','hardware','changes','community'],reportKinds:['benchmark','issue'],tools:['vram-fit'],indexMin:3},
  feature:{label:{en:'Feature',ko:'기능'},plural:{en:'Features',ko:'기능'},icon:'bolt',props:['status','release_date','homepage'],sections:['overview','availability','rollout','changes','community'],reportKinds:['issue'],indexMin:2},
  runtime:{label:{en:'Local runtime',ko:'로컬 실행기'},plural:{en:'Local runtimes',ko:'로컬 실행기'},icon:'terminal',props:['latest_version','os_support','gpu_backends','homepage'],sections:['overview','versions','changes','community'],indexMin:2},
 },
 properties:{
  ...COMMON_PROPS,
  hq_country:prop({en:'Headquarters',ko:'본사'},'text',{volatility:'static'}),
  platforms:prop({en:'Platforms',ko:'플랫폼'},'list',{volatility:'medium'}),
  status_page:prop({en:'Status page',ko:'상태 페이지'},'url',{volatility:'slow'}),
  price_monthly:prop({en:'Monthly price',ko:'월 요금'},'money',{volatility:'fast',group:'pricing'}),
  price_yearly:prop({en:'Yearly price',ko:'연 요금'},'money',{volatility:'fast',group:'pricing'}),
  price_note:prop({en:'Pricing note',ko:'요금 참고'},'text',{volatility:'fast',group:'pricing'}),
  seats_min:prop({en:'Minimum seats',ko:'최소 인원'},'number',{volatility:'medium',group:'pricing'}),
  context_window:prop({en:'Context window',ko:'컨텍스트 길이'},'tokens',{unit:'tokens',volatility:'medium',group:'specs'}),
  max_output:prop({en:'Max output',ko:'최대 출력'},'tokens',{unit:'tokens',volatility:'medium',group:'specs'}),
  knowledge_cutoff:prop({en:'Knowledge cutoff',ko:'학습 데이터 기준일'},'date',{volatility:'static',group:'specs'}),
  input_modalities:prop({en:'Input',ko:'입력'},'list',{volatility:'medium',group:'specs'}),
  output_modalities:prop({en:'Output',ko:'출력'},'list',{volatility:'medium',group:'specs'}),
  api_input_price:prop({en:'API input price (per 1M tokens)',ko:'API 입력 가격 (100만 토큰당)'},'money',{...USD,volatility:'fast',group:'pricing'}),
  api_output_price:prop({en:'API output price (per 1M tokens)',ko:'API 출력 가격 (100만 토큰당)'},'money',{...USD,volatility:'fast',group:'pricing'}),
  api_cached_input_price:prop({en:'API cached input (per 1M tokens)',ko:'API 캐시 입력 (100만 토큰당)'},'money',{...USD,volatility:'fast',group:'pricing'}),
  open_weights:prop({en:'Open weights',ko:'가중치 공개'},'bool',{volatility:'static',group:'local'}),
  parameters_b:prop({en:'Parameters',ko:'파라미터 수'},'number',{unit:'B',volatility:'static',group:'local'}),
  active_parameters_b:prop({en:'Active parameters (MoE)',ko:'활성 파라미터 (MoE)'},'number',{unit:'B',volatility:'static',group:'local'}),
  license:prop({en:'License',ko:'라이선스'},'text',{volatility:'slow',group:'local'}),
  deprecation_date:prop({en:'Deprecation date',ko:'지원 종료일'},'date',{volatility:'medium'}),
  api_model_id:prop({en:'API model id',ko:'API 모델 ID'},'text',{volatility:'medium'}),
  latest_version:prop({en:'Latest version',ko:'최신 버전'},'text',{volatility:'fast'}),
  os_support:prop({en:'OS',ko:'운영체제'},'list',{volatility:'slow'}),
  gpu_backends:prop({en:'GPU backends',ko:'GPU 백엔드'},'list',{volatility:'slow'}),
 },
});
