"""Generate deterministic browser encoding tables from Python codecs.

The table is checked separately against GNU iconv by the test suite. A zero entry means
unrepresentable (U+0000 is handled separately); entries are big-endian 1 or 2 bytes.
"""
import base64
import pathlib
import struct

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / 'src' / 'task' / 'character-encoding-tables.js'
CODECS = [('shift_jis', 'shift_jis'), ('euc_kr', 'euc_kr'), ('cp949', 'cp949')]

parts = ["/* Generated by tools/character-encodings.py from Python strict codecs. Do not edit. */"]
for key, codec in CODECS:
    values = []
    for cp in range(0x10000):
        if 0xD800 <= cp <= 0xDFFF:
            values.append(0)
            continue
        try:
            raw = chr(cp).encode(codec, 'strict')
            values.append(int.from_bytes(raw, 'big') if len(raw) <= 2 else 0)
        except UnicodeEncodeError:
            values.append(0)
    raw = struct.pack('<65536H', *values)
    b64 = base64.b64encode(raw).decode('ascii')
    parts.append(f"export const {key.upper()} = '{b64}';")
OUT.write_text('\n'.join(parts) + '\n', encoding='utf-8')
print(f'{OUT}: {OUT.stat().st_size} bytes')
