"""Regenerate first-party examples with actual engines, and localized social PNGs.
Run npm run build and serve dist on 4173 first. No user inputs or network images.
Only development requires Playwright; deployment copies committed PNG assets.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import base64,json,os
ROOT=Path(__file__).resolve().parents[1]
with sync_playwright() as pw:
    browser=pw.chromium.launch(headless=True)
    page=browser.new_page()
    page.goto(os.environ.get('TEST_URL','http://127.0.0.1:4173')+'/en/',wait_until='networkidle')
    data=page.evaluate('''async()=>{
      const Im=await import('/src/image.js'),R=await import('/src/recipes.js');
      const {INTENTS}=await import('/src/intents.js'),{TOOLS}=await import('/src/tool-registry.js');
      // Catalog entries whose page is a Lab, not a recipe, have no runRecipe id: social cards only.
      const {TASK_TOOLS}=await import('/src/task/registry.js'),recipeTool=id=>TOOLS[id]&&(TASK_TOOLS[id]?.module??'recipe')==='recipe';
      const {t}=await import('/src/i18n.js'),{BRAND}=await import('/src/brand.js');
      const source=Im.canvas(96,64),ctx=source.getContext('2d');
      ctx.fillStyle='#ef4444';ctx.fillRect(12,12,24,36);ctx.fillStyle='#2563eb';ctx.fillRect(52,20,28,32);
      ctx.fillStyle='#fff';ctx.fillRect(19,21,5,5);ctx.fillRect(59,27,5,5);
      const files=[],examples={};
      const store=(c,file)=>{files.push({file,data:c.toDataURL('image/png').split(',')[1]});return {file:file.split('/').pop(),width:c.width,height:c.height};};
      for(const [id,intent] of Object.entries(INTENTS)){
        if(id==='home'||!['image','pixel'].includes(intent.editor)||id==='heic')continue;
        let input=Im.copy(source),out=null,recipe=null;
        if(['remove-bg','logo-bg','margin-crop'].includes(id)){const x=input.getContext('2d');x.globalCompositeOperation='destination-over';x.fillStyle='#fff';x.fillRect(0,0,96,64);x.globalCompositeOperation='source-over';}
        const blob=await Im.blobOf(input),items=[{name:'geometric-sample.png',blob}];
        if(!recipeTool(id)&&TOOLS[id]){Im.release(input);continue;}
        if(TOOLS[id]){
          const o=R.defaults(id);o.cellW=32;o.cellH=32;o.chars='ABCDEF';o.baseline=26;o.columns=2;o.longSide=320;
          if(id==='marketplace-pack'){o.platform='custom';o.width=320;o.height=240;}
          if(id==='mask-packer')o.mapping=[0,0,0,'one'];
          if(id==='palette-swap'){o.from='#ef4444';o.to='#22c55e';}
          if(['sprite-sheet-maker','frame-normalize'].includes(id))items.push({...items[0]});
          const rects=id==='sprite-slicer'?await R.detect(input,o):[];
          recipe=await R.runRecipe(id,{source:input,items,options:o,rects});out=recipe.canvas;
        }else if(id==='upscale')out=Im.resize(input,192,128,false);
        else if(id==='resize')out=Im.resize(input,48,32,false);
        else if(id==='crop')out=Im.crop(input,{x:.125,y:.125,w:.75,h:.75});
        else if(id==='remove-bg')out=await Im.processPixels(input,'remove',{color:[255,255,255],tolerance:24});
        else if(id==='pixel'){const c=Im.pixelBase(input,32,'contain',true);out=await Im.processPixels(c,'pixel',{colors:8,dither:0,outline:0});Im.release(c);}
        else if(['compress','convert'].includes(id)){const r=await Im.encode(input,{format:'webp',quality:.65,kb:0});out=await Im.decode(r.blob);}
        else out=Im.resize(input,72,48,false);
        examples[id]={before:store(input,`examples/${id}-original-example.png`),after:store(out,`examples/${id}-processed-example.png`)};
        Im.release(input);Im.release(out);
      }
      for(const locale of ['en','ko','ja'])for(const id of Object.keys(INTENTS)){
        const c=Im.canvas(1200,630),x=c.getContext('2d');x.fillStyle='#f5f7fa';x.fillRect(0,0,1200,630);
        x.fillStyle='#2563eb';x.fillRect(60,65,72,8);x.fillStyle='#172b4d';x.font='bold 54px "Malgun Gothic", "Noto Sans CJK JP", sans-serif';
        const title=t(`intent.${id}.title`,{},locale),words=title.split(' ');let line='',y=190;
        for(const word of words){if(x.measureText(line+' '+word).width>1050&&line){x.fillText(line,60,y);y+=76;line=word;}else line+=(line?' ':'')+word;}x.fillText(line,60,y);
        x.font='28px "Malgun Gothic", sans-serif';x.fillStyle='#52647c';x.fillText({en:'Processed locally in your browser',ko:'브라우저에서 내 기기로 처리',ja:'ブラウザでローカル処理'}[locale],60,370);
        x.fillStyle='#2563eb';x.font='bold 34px sans-serif';x.fillText(BRAND.name,60,545);store(c,`social/${locale}-${id}.png`);Im.release(c);
      }
      Im.release(source);return {files,examples};
    }''')
    for item in data['files']:
        target=ROOT/'assets'/item['file'];target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(base64.b64decode(item['data']))
    (ROOT/'src/example-data.js').write_text('// Generated by tools/generate-examples.py; actual engine output from first-party geometric samples.\nexport const EXAMPLES = '+json.dumps(data['examples'],ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
    print('Generated',len(data['examples']),'before/after pairs and',len(data['files']),'PNG assets')
    browser.close()
