import {parsePalette} from './pixel-engine.js';
import {imageLabel} from './image-controls.js';
import {appendOperation,retainedBlobBytes} from './image-document.js';
import {BRAND} from './brand.js';
import {track} from './analytics.js';
import {authorize} from './entitlement.js';
import {mediaExportTool} from './quota.js';
import {Experience} from './experience.js';
import {t} from './i18n.js';
import {LIMITS,clamp,integer,dimensions,bytes,safeName,stem,typeOf,route,zip,inversePoint} from './core.js';
import * as Im from './image.js';
import {PDFWorkspace} from './pdf.js';
import {pdfLabel,readPDFOptions} from './pdf-controls.js';
import {mediaLabel,readMediaOptions} from './media-controls.js';
import * as Media from './media.js';
import {icon,button,esc,initTooltips} from './ui.js';
const $=s=>document.querySelector(s),root=new URL('../',import.meta.url),initial=route(location.pathname,location.search);
const names={get image(){return t('이미지 편집');},get pdf(){return t('PDF 편집');},get pixel(){return t('kit.game');},get media(){return t('미디어 편집');}},kickers={image:'IMAGE STUDIO',pdf:'PDF STUDIO',pixel:'PIXEL STUDIO',media:'MEDIA STUDIO'};
const S={editor:initial.editor,tool:initial.tool,images:[],index:0,c:null,pixel:null,pdf:new PDFWorkspace(),media:null,busy:false,abort:null,view:0,crop:{x:.1,y:.1,w:.8,h:.8},pointer:null,markImage:null,
 export:{format:initial.format,kb:initial.kb||(/compress/.test(location.pathname)&&initial.editor==='image'?500:0),quality:92,width:0,shrink:false,bg:'#ffffff',all:false},
 pix:{n:initial.n,colors:16,dither:0,palette:[],paletteText:'',ditherMode:'floyd-steinberg',fit:'contain',trim:true,outline:0},pdfExport:{range:'',format:initial.pdfFormat,raster:false,optimize:location.pathname.includes('/pdf/compress'),splitMode:'single'},mediaExport:{format:initial.mediaFormat,start:0,end:0,width:0,mode:'precise',preset:'balanced'}};
let messageTimer;const file=()=>S.images[S.index],ready=()=>S.editor==='pdf'?S.pdf.pages.length:S.editor==='media'?S.media:!!S.c;
const UX=new Experience({root,state:S,file,ready,refresh,paint,task,applyImage:setImage,generatePixel,typeOf,message,help,readExport,saveImages,onAction,dialog,check});
function message(text,error=false){clearTimeout(messageTimer);$('#message').textContent=text;$('#message').classList.toggle('error',error);$('#message').hidden=false;if(!error)messageTimer=setTimeout(()=>$('#message').hidden=true,6500);}
function check(signal=S.abort?.signal){if(signal?.aborted)throw new DOMException(t("취소했습니다."),'AbortError');}
async function task(label,fn){if(S.busy)return;S.busy=true;S.abort=new AbortController();const signal=S.abort.signal;document.body.classList.add('busy');$('#workspace').setAttribute('aria-busy','true');$('#languageSelect').disabled=true;$('#message').hidden=true;$('#progress').hidden=false;const progress=t=>$('#progressText').textContent=t;progress(label);try{await fn(progress,signal);check(signal);if(S.runIntent)track('tool_success',{intent:S.runIntent});}catch(e){if(S.runIntent)track('tool_error',{intent:S.runIntent,error_code:e.name==='AbortError'?'cancelled':'processing_failed'});message(e.name==='AbortError'?t("작업을 취소했어요."):e.message||String(e),e.name!=='AbortError');}finally{S.runIntent=null;S.busy=false;S.abort=null;document.body.classList.remove('busy');$('#workspace').setAttribute('aria-busy','false');$('#progress').hidden=true;refresh();await paint().catch(e=>message(e.message,true));}}
function switchEditor(editor,push=true){if(S.busy)return;S.editor=editor;S.tool='';if(push){const paths={image:'image/editor/',pdf:'pdf/editor/',pixel:'pixel/',media:'media/'};history.pushState({},'',new URL(paths[editor],root));}refresh();paint().catch(e=>message(e.message,true));if(editor==='pixel'&&S.c&&!S.pixel)task(t("도트 에셋 만드는 중…"),updatePixel);}
function refresh(){
 $('#navigation').innerHTML=['image','pdf','pixel','media'].map(n=>button(`editor:${n}`,n,names[n],'')).join('')+'<span class="nav-separator"></span>'+button('share','share',t("설정 링크 복사"))+button('clear','trash',t("작업실 비우기"));
 // Explicitly set state instead of relying on duplicate HTML attributes.
 $('#navigation').querySelectorAll('[data-action^="editor:"]').forEach(b=>{const on=b.dataset.action===`editor:${S.editor}`;b.classList.toggle('active',on);b.setAttribute('aria-current',on?'page':'false');});
 $('#editorTitle').textContent=names[S.editor];$('#editorKicker').textContent=kickers[S.editor];document.title=`${names[S.editor]} · ${BRAND.name}`;
 $('#topActions').innerHTML=button('undo','undo',t("되돌리기"),ready()?'':'disabled')+button('open','plus',t("파일 추가"))+`<button class="export-button" data-action="export" ${ready()?'':'disabled'}>${icon('download',18)}${t('저장')}</button>`;
 const b=(t,i,l)=>button(`tool:${t}`,i,l);
 if(S.editor==='image')$('#toolDock').innerHTML=b('crop','crop',t("자르기"))+b('resize','resize',t("크기 변경"))+button('rotate','rotate',t("90° 회전"))+b('background','background',t("배경 제거"))+b('upscale','upscale',t("2× · 4× 확대"))+button('editor:pixel','pixel',t("도트화로 보내기"))+b('more','sliders',t("추가 이미지 도구"));
 else if(S.editor==='pdf')$('#toolDock').innerHTML=button('pdf:left','left',t("페이지 앞으로 이동"))+button('pdf:right','right',t("페이지 뒤로 이동"))+button('pdf:rotate','rotate',t("페이지 회전"))+button('pdf:remove','trash',t("페이지 삭제"))+b('text','text',t("글자 추가"))+b('pen','pen',t("그리기 · 서명"))+b('more','sliders',t("페이지 · 주석 도구"));
 else if(S.editor==='pixel')$('#toolDock').innerHTML=[16,32,64,128].map(n=>`<button class="chip ${S.pix.n===n?'selected':''}" data-action="size:${n}" aria-label="${t("pixel.dimensions",{size:n})}">${n}</button>`).join('')+b('pixel','sliders',t("색상 · 디더링 · 사용자 크기"))+button('pixel:pack','pack',t("16·32·64·128 크기 세트"));
 else $('#toolDock').innerHTML=button('media:frame','image',t("현재 장면을 이미지로"))+b('export','scissors',t("구간 자르기 · 저장"))+button('media:audio','audio',t("오디오 추출"))+button('media:gif','media',t("짧은 GIF 만들기"));
 $('#toolDock').querySelectorAll('[data-action^="tool:"]').forEach(b=>b.classList.toggle('active',b.dataset.action===`tool:${S.tool}`));
 $('#emptyTitle').textContent={image:t("파일을 놓으면, 시작돼요."),pdf:t("페이지를 한곳에, 간단하게."),pixel:t("작은 픽셀로, 새롭게."),media:t("필요한 순간만, 가볍게.")}[S.editor];$('#emptySubtitle').textContent={image:'PNG · JPG · WebP · HEIC',pdf:t("PDF · 여러 이미지"),pixel:t("이미지 → 16 · 32 · 64 · 128px"),media:t("MP4 · WebM · 오디오")}[S.editor];
 $('#fileInput').accept=S.editor==='pdf'?'.pdf,image/png,image/jpeg,image/webp':S.editor==='media'?'video/*,audio/*':S.editor==='pixel'?'image/png,image/jpeg,image/webp,image/avif,.heic,.heif':'image/*,.heic,.heif,.pdf,video/*,audio/*';
 renderPanel();renderStrip();UX.render();
}
async function paint(){const version=++S.view,has=!!ready();$('#emptyState').hidden=has;$('#canvasWrap').hidden=!has||S.editor==='media';$('#video').hidden=!has||S.editor!=='media';$('#stageBadge').hidden=!has;$('#stage').classList.toggle('pixel-mode',(S.editor==='pixel'||UX.kit.pixelView)&&!UX.original&&(!!UX.preview()||!!S.pixel));$('#cropBox').hidden=!(has&&S.editor==='image'&&S.tool==='crop');
 if(!has){$('#documentInfo').textContent=t("원본은 그대로, 작업은 내 기기에서.");return;}
 if(S.editor==='media'){const m=S.media;$('#documentInfo').textContent=t("{0} · {1}초 · {2}", {0: safeName(m.file.name), 1: m.duration.toFixed(1), 2: bytes(m.file.size)});$('#stageBadge').textContent=m.w?`${m.w} × ${m.h}`:t("오디오 파일");return;}
 let source=S.editor==='pdf'?await S.pdf.render():UX.result&&UX.original?S.c:UX.preview()||(S.editor==='pixel'&&S.pixel?S.pixel:S.c);const temporary=S.editor==='pdf';if(version!==S.view){if(temporary)Im.release(source);return;}if(!source)return;
 const bounds=$('#stage').getBoundingClientRect(),maxW=Math.max(50,bounds.width-52),maxH=Math.max(50,bounds.height-52),isPixel=(S.editor==='pixel'||UX.kit.pixelView)&&!UX.original&&(!!UX.preview()||!!S.pixel),scale=Math.min(isPixel?16:1,maxW/source.width,maxH/source.height),w=Math.max(1,Math.round(source.width*scale)),h=Math.max(1,Math.round(source.height*scale)),view=$('#preview');view.width=isPixel?source.width:w;view.height=isPixel?source.height:h;view.style.width=`${w}px`;view.style.height=`${h}px`;$('#canvasWrap').style.width=`${w}px`;$('#canvasWrap').style.height=`${h}px`;view.getContext('2d').drawImage(isPixel?source:Im.previewProxy(source),0,0,view.width,view.height);
 $('#stageBadge').textContent=S.editor==='pdf'?`${S.pdf.selected+1} / ${S.pdf.pages.length}`:`${source.width} × ${source.height}${isPixel?t(" · 실제 에셋 크기"):''}`;
 $('#documentInfo').textContent=S.editor==='pdf'?t("{0}페이지 · 원본 글자 직접 수정은 지원하지 않아요.", {0: S.pdf.pages.length}):`${safeName(file()?.name||'image')} · ${source.width} × ${source.height}${isPixel?' · PNG':` · ${bytes(file()?.blob.size||0)}`}`;
 if(temporary){const p=S.pdf.current();if(!p.thumb){const t=Im.resize(source,Math.max(1,Math.round(source.width*100/source.height)),100);p.thumb=t.toDataURL();Im.release(t);renderStrip();}Im.release(source);}drawCrop();}
function drawCrop(){const r=S.crop;for(const [k,size] of [['x',S.c?.width],['y',S.c?.height],['w',S.c?.width],['h',S.c?.height]]){const input=$('#crop-'+k);if(input&&document.activeElement!==input)input.value=Math.round(r[k]*size);}Object.assign($('#cropBox').style,{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'});}
function renderStrip(){const el=$('#fileStrip');if(S.editor==='media'||!ready()){el.hidden=true;return;}const pdf=S.editor==='pdf',items=pdf?S.pdf.pages:S.images;el.hidden=items.length<2&&!pdf;el.innerHTML=items.map((f,i)=>`<button class="thumb ${i===(pdf?S.pdf.selected:S.index)?'active':''}" data-action="select:${i}" aria-label="${pdf?t("{0}페이지", {0: i+1}):esc(f.name)}" ${pdf?'draggable="true"':''} data-index="${i}">${f.thumb?`<img src="${f.thumb}" alt="" loading="lazy" decoding="async">`:icon(pdf?'pdf':'image',26)}<span>${i+1}</span></button>`).join('');}
const field=(label,html)=>`<label class="field"><span>${label}</span>${html}</label>`,number=(id,v,min=1,max=65535)=>`<input id="${id}" type="number" min="${min}" max="${max}" value="${v}">`,select=(id,items,v)=>`<select id="${id}">${items.map(([k,t])=>`<option value="${k}" ${String(k)===String(v)?'selected':''}>${t}</option>`).join('')}</select>`,act=(action,label,cls='primary')=>`<button class="${cls}" data-action="${action}">${label}</button>`,hint=(s,w=false)=>`<p class="hint ${w?'warning':''}">${s}</p>`,checkbox=(id,text,on=false)=>`<label class="checks"><input type="checkbox" id="${id}" ${on?'checked':''}>${text}</label>`;
function renderPanel(){const el=$('#panel');el.hidden=!S.tool;if(!S.tool)return;let title='',html='';
 if(S.tool==='export'){
 title=t("저장");if(S.editor==='image'){const e=S.export;html=field(t("형식"),select('outFormat',[['auto','Auto · PNG / JPEG / WebP'],['png',t("PNG · 투명 배경")],['jpeg',t("JPG · 사진")],['webp',t("WebP · 웹용")],...(S.imageFormats?.includes('avif')?[['avif','AVIF']]:[])],e.format))+field(t("품질 · JPG / WebP"),`<input id="quality" type="range" min="25" max="100" value="${e.quality}" aria-label="${t('출력 품질')}">`)+field(t("목표 용량 · 0은 제한 없음"),number('targetKB',e.kb,0,32768))+field(t("최대 너비 · 0은 현재 크기"),number('outWidth',e.width,0,65535))+field(t("JPG 배경색"),`<input id="exportBg" type="color" value="${e.bg}">`)+checkbox('allowShrink',t("용량이 넘으면 추가 축소 허용"),e.shrink)+(S.images.length>1?checkbox('exportAll',t("모든 이미지에 저장 설정 적용 · ZIP"),e.all):'')+act('image:save',t("내 기기에 저장"))+hint(t("JPG는 투명 영역을 배경색으로 합칩니다. 재인코딩 시 원본 메타데이터·색상 프로필은 유지되지 않을 수 있어요."));}
 else if(S.editor==='pixel')html=field(t("PNG 크기"),select('pixelScale',[[1,t("1× · 실제 도트 에셋")],[2,t("2× · 정수배 확대")],[4,t("4× · 정수배 확대")]],1))+act('pixel:save',t("PNG 저장"))+act('pixel:pack',t("16 · 32 · 64 · 128 세트"),'secondary')+act('pixel:to-image',t("이미지 편집기로 보내기"),'secondary')+hint(t("작은 원본 에셋은 1×로 저장하세요. 확대 저장은 새 디테일을 만들지 않습니다."));
 else if(S.editor==='pdf'){const e=S.pdfExport;html=field(t("형식"),select('pdfFormat',[['pdf','PDF'],['jpeg',t("JPG · 페이지별")],['png',t("PNG · 페이지별")]],e.format))+field(t("페이지 · 비우면 전체"),`<input id="pdfRange" placeholder="1, 3-5" value="${esc(e.range)}">`)+act('pdf:current',t("현재 페이지만 선택"),'secondary')+checkbox('optimizePdf',pdfLabel('optimize'),e.optimize)+hint(pdfLabel('preserveNote'))+`<details><summary>${imageLabel('advanced')}</summary>`+field(pdfLabel('split'),select('pdfSplit',['single','each','every','odd-even','groups'].map(k=>[k,pdfLabel(k==='odd-even'?'odd':k)]),e.splitMode||'single'))+field('N',number('pdfEvery',e.every||1,1,10000))+field('1-3; 5; 7-9',`<input id="pdfGroups" value="${esc(e.groups||'')}">`)+field(pdfLabel('maxSide'),number('pdfMaxSide',e.maxSide||2400,100,16384))+'</details>'+checkbox('rasterPdf',t("이미지 기반 용량 축소 저장"),e.raster)+hint(t("용량 축소를 선택하면 페이지 전체가 이미지가 됩니다. 글자 검색·선택, 벡터 선명도, 양식, 기존 서명을 유지하지 않아요. 크기 감소도 보장되지 않습니다."),true)+act('pdf:save',t("선택한 페이지 저장"));}
 else{const e=S.mediaExport;html=`<div class="row">${field(t("시작 · 초"),`<input id="mediaStart" type="number" min="0" step="0.001" value="${e.start}">`)}${field(t("끝 · 초"),`<input id="mediaEnd" type="number" min="0" step="0.001" value="${e.end}">`)}</div>`+field(t("저장 형식"),select('mediaFormat',[...(S.media?.mp4||S.media?.videoCodec==='avc'?[['mp4','MP4 · H.264']]:[]),['webm','WebM'],['mp3','MP3'],['wav','WAV'],['gif','GIF']],e.format))+field(mediaLabel('mode'),select('mediaMode',['precise','fast','compatibility'].map(k=>[k,mediaLabel(k)]),e.mode||'precise'))+field(mediaLabel('preset'),select('mediaPreset',['best','balanced','small'].map(k=>[k,mediaLabel(k)]),e.preset||'balanced'))+field(t("영상 최대 너비"),select('mediaWidth',[[0,mediaLabel('original')],[3840,'4K'],[2560,'1440p'],[1920,'1080p'],[1280,'720p'],[854,'480p'],[640,'640px']],e.width))+`<details><summary>${mediaLabel('advanced')}</summary>`+field(mediaLabel('codec'),select('mediaCodec',[['auto','Auto'],...(S.media?.codecs||[]).map(k=>[k,k==='avc'?'H.264':k.toUpperCase()])],e.codec||'auto'))+field('FPS',select('mediaFps',[[0,mediaLabel('original')],[60,'60'],[30,'30'],[24,'24']],e.fps||0))+field(mediaLabel('target'),number('mediaTarget',e.targetMB||0,0,100000))+field(mediaLabel('bitrate'),number('mediaBitrate',(e.bitrate||0)/1000,0,200000))+field(mediaLabel('audio'),select('mediaAudio',[96,128,192,256,320].map(k=>[k,k]),e.audioBitrate||192))+field(mediaLabel('rate'),select('mediaRate',[[0,mediaLabel('original')],[44100,'44100 Hz'],[48000,'48000 Hz']],e.sampleRate||0))+field('GIF · px',number('gifWidth',e.gifWidth||640,16,4096))+field('GIF · FPS',number('gifFps',e.gifFps||12,1,60))+field('GIF · colors',number('gifColors',e.gifColors||256,2,256))+field('GIF · dither',select('gifDither',[[0,'0'],[.5,'50%'],[1,'100%']],e.gifDither||0))+'</details>'+act('media:set-start',t("현재 시점을 시작으로"),'secondary')+act('media:save',t("구간 저장"))+hint(mediaLabel('note'));}

 }else if(S.editor==='image'){
 if(S.tool==='crop'){title=t("자르기");html='<div class="chips">'+[['free',t("자유")],['1','1:1'],['1.333333','4:3'],['1.777778','16:9']].map(([v,t])=>`<button class="chip" data-action="crop-preset:${v}">${t}</button>`).join('')+'</div>'+hint(t("이미지 위에서 드래그해 영역을 선택하세요."))+['x','y','w','h'].map((k,i)=>field(['X · px','Y · px',t('너비 · px'),t('높이 · px')][i],number('crop-'+k,Math.round(S.crop[k]*(i%2?S.c?.height||1:S.c?.width||1)),i<2?0:1))).join('')+act('crop-reset',imageLabel('resetCrop'),'secondary')+hint(imageLabel('keyboard'))+act('image:crop',t("선택 영역 적용"));}
 if(S.tool==='resize'){title=t("크기 변경");html=field(t("너비 · px"),number('resizeW',initial.w||S.c?.width||1080))+field(t("높이 · px"),number('resizeH',initial.h||S.c?.height||1080))+checkbox('ratioLock',t("원본 비율 유지"),true)+`<details><summary>${imageLabel('advanced')}</summary>${field(imageLabel('percent'),number('resize-percent',100,.01,10000))}${field(imageLabel('longSide'),number('resize-long',Math.max(S.c?.width||1080,S.c?.height||1080)))}${field(imageLabel('megapixels'),'<input id="resize-mp" type="number" min="0.001" step="0.1" value="'+((S.c?.width||1080)*(S.c?.height||1080)/1e6).toFixed(3)+'">')}</details>`+act('image:resize',t("크기 적용"));}
 if(S.tool==='background'){title=t("배경 제거");html=field(t("제거할 단색"),`<input id="removeColor" type="color" value="#ffffff">`)+field(t("비슷한 색 허용 범위"),`<input id="tolerance" type="range" min="0" max="180" value="40" aria-label="${t('색상 허용 범위')}">`)+act('image:remove',t("단색 배경 제거"))+hint(t("가장자리와 연결된 비슷한 색만 지워요. 흰 배경의 로고·상품 이미지에 적합합니다."))+act('image:portrait',t("AI 인물 배경 제거"),'secondary')+hint(imageLabel("matteNote"));}
 if(S.tool==='upscale'){title=t("크게, 더 선명하게");html=field(t("배율"),select('scale',[[2,'2×'],[4,'4×']],2))+field(t("방식"),select('scaleMode',[['smooth',t("부드럽게 · 사진 / 일러스트")],['sr',imageLabel('sr')],['pixel',t("픽셀 유지 · 도트 이미지")]],'smooth'))+act('image:upscale',t("확대 적용"))+hint(imageLabel("resampling"));}
 if(S.tool==='more'){title=t("추가 도구");html=act('image:flip',t("좌우 반전"),'secondary')+act('image:trim',t("투명 여백 잘라내기"),'secondary')+act('image:outline',t("1px 외곽선 추가"),'secondary')+field(t("새 배경색"),`<input id="fillColor" type="color" value="#ffffff">`)+act('image:fill',t("배경색 적용"),'secondary')+act('image:to-pdf',t("이 이미지를 PDF에 추가"),'secondary')+act('image:reset',t("원본으로 되돌리기"),'secondary');}
 }else if(S.editor==='pixel'){title=t("도트 에셋");html=field('N × N · 8–512px',number('pixelN',S.pix.n,8,512))+field(t("팔레트"),select('pixelColors',[[0,t("제한 없음")],[8,t("8색")],[16,t("16색")],[32,t("32색")],[64,t("64색")]],S.pix.colors))+field(t("디더링"),select('pixelDither',[[0,t("없음")],[.5,t("약하게")],[1,t("강하게")]],S.pix.dither))+field(t("이미지 배치"),select('pixelFit',[['contain',t("비율 유지 · 여백")],['cover',t("가득 채우기 · 자르기")]],S.pix.fit))+checkbox('pixelTrim',t("투명 여백 자동 제거"),S.pix.trim)+field(t("외곽선"),select('pixelOutline',[[0,t("없음")],[1,'1px'],[2,'2px']],S.pix.outline))+`<details><summary>${imageLabel('advanced')}</summary>${field(imageLabel('ditherMode'),select('pixelDitherMode',[['floyd-steinberg','Floyd–Steinberg'],['ordered','Bayer 4×4']],S.pix.ditherMode||'floyd-steinberg'))}${field(imageLabel('palette'),'<textarea id="pixelPalette" rows="4" maxlength="8192" spellcheck="false">'+esc(S.pix.paletteText||'')+'</textarea>')}</details>`+act('pixel:apply',t("도트화 적용"))+hint(t("원본의 색·형태를 픽셀로 단순화합니다. 새 애니메이션이나 손으로 그린 도트를 생성하는 AI는 아닙니다. 외곽선 색은 팔레트에 별도로 추가돼요."));}
 else if(S.editor==='pdf'){
 if(S.tool==='text'){title=t("글자 추가");html=field(t("내용"),`<textarea id="markText" placeholder="${t('여기에 입력하세요')}"></textarea>`)+field(t("크기"),number('markSize',20,8,120))+field(t("색상"),`<input id="markColor" type="color" value="#182a43">`)+hint(t("페이지에서 원하는 위치를 누르세요. 추가한 글자는 PDF 글자 객체로 저장되며, 기존 본문을 수정하지 않습니다."));}
 if(S.tool==='pen'){title=t("그리기 · 서명");html=field(t("도구"),select('penMode',[['pen',t("펜 · 서명 그리기")],['highlight',t("형광 표시")],['rect',t("사각형")]],'pen'))+field(t("굵기"),number('markSize',3,1,40))+field(t("색상"),`<input id="markColor" type="color" value="#3182f6">`)+hint(t("페이지 위에 그려주세요. 서명은 그림이며 인증서 기반 전자서명이 아닙니다. 표시를 덮는 것은 보안용 마스킹이 아닙니다."));}
 if(S.tool==='more'){title=t("페이지와 주석");html=act('pdf:duplicate',t("페이지 복제"),'secondary')+act('pdf:overlay',t("이미지 / 서명 이미지 추가"),'secondary')+act('pdf:clear-marks',t("현재 페이지의 추가 표시 지우기"),'secondary')+act('open',t("PDF / 이미지 더 추가"),'secondary')+hint(t("썸네일을 드래그하거나 화살표로 순서를 바꿔요. 합치기는 파일 추가로, 분할은 저장할 페이지 범위로 처리합니다."));}
 }
 el.innerHTML=`<div class="panel-header"><h2>${title||t("설정")}</h2>${button('close-panel','close',t("설정 닫기"))}</div>${html}`;
}
function readExport(){S.export={format:$('#outFormat').value,kb:integer($('#targetKB').value,0,32768,t("목표 KB")),quality:integer($('#quality').value,25,100,t("품질")),width:integer($('#outWidth').value,0,65535,t("최대 너비")),shrink:$('#allowShrink').checked,bg:$('#exportBg').value,all:$('#exportAll')?.checked||false};return S.export;}
function imageMemory(){return retainedBlobBytes(S.images);}
async function setImage(c,remember=true,operation=null){UX.invalidate();const f=file();if(!f){Im.release(c);throw Error(t("이미지를 먼저 추가하세요."));}try{const blob=operation?appendOperation(f.blob,operation):await Im.blobOf(c);check();if(remember){f.history.push(f.blob);while(f.history.length>(operation?50:4))f.history.shift();}f.blob=blob;for(const other of S.images){while(other.history.length&&imageMemory()>Math.max(LIMITS.totalBytes,S.images.reduce((n,f)=>n+f.original.size,0)*2))other.history.shift();}Im.release(S.c);S.c=c;c=null;Im.release(S.pixel);S.pixel=null;const thumb=Im.resize(S.c,96,Math.max(1,Math.round(96*S.c.height/S.c.width)));f.thumb=thumb.toDataURL();Im.release(thumb);}finally{Im.release(c);}}
async function generatePixel(progress=()=>{},signal=S.abort?.signal,options=S.pix){if(!S.c)throw Error(t("이미지를 먼저 추가하세요."));const base=await Im.pixelBaseQuality(S.c,options.n,options.fit,options.trim,{progress,signal});try{const result=await Im.processPixels(base,'pixel',{colors:options.colors,dither:options.dither,outline:options.outline,palette:options.palette,ditherMode:options.ditherMode},progress,signal);check(signal);return result;}finally{Im.release(base);}}
async function updatePixel(progress,signal){const result=await generatePixel(progress,signal);Im.release(S.pixel);S.pixel=result;}
async function loadFiles(list){const files=[...list];if(!files.length||S.busy||!UX.acceptsFiles(files))return;await task(t("파일을 여는 중…"),async(progress,signal)=>{const kinds=files.map(typeOf);if(kinds.some(k=>!k))throw Error(t("지원하는 이미지·PDF·영상·오디오 파일을 선택하세요."));const detected=kinds[0];if(S.editor==='pdf'&&kinds.every(k=>k==='pdf'||k==='image')){}else if(detected==='pdf')S.editor='pdf';else if(detected==='media')S.editor='media';else if(!['image','pixel'].includes(S.editor))S.editor='image';
 if(S.editor==='pdf'){if(kinds.some(k=>k==='media'))throw Error(t("PDF 편집에는 PDF와 이미지만 추가할 수 있어요."));await S.pdf.add(files,progress,signal);check(signal);for(const p of S.pdf.pages.slice(0,10)){if(p.thumb)continue;const c=await S.pdf.render(p,150);p.thumb=c.toDataURL();Im.release(c);check(signal);}message(t("페이지를 추가했어요. 원본의 전자서명·대화형 양식은 저장 시 유지되지 않습니다."));}
 else if(S.editor==='media'){if(files.length!==1)throw Error(t("미디어는 한 파일씩 선택하세요."));if(S.media){$('#video').pause();URL.revokeObjectURL(S.media.url);S.media=null;}S.media=await Media.openMedia($('#video'),files[0],signal);S.mediaExport.end=Math.min(10,S.media.duration);S.mediaExport.start=0;}
 else{if(kinds.some(k=>k!=='image'))throw Error(t("이미지와 다른 종류의 파일은 따로 선택하세요."));if(S.images.length+files.length>LIMITS.files)throw Error(t("한 작업에는 이미지 {0}장까지 추가할 수 있어요.",{0:LIMITS.files}));S.imageFormats=await Im.availableFormats();const first=S.images.length;for(const f of files){check(signal);if(f.type==='image/gif'||/\.gif$/i.test(f.name))throw Error(t("애니메이션 GIF 입력은 아직 지원하지 않습니다. 정지 PNG로 변환해 주세요."));progress(t("{0} 여는 중…", {0: f.name}));const c=await Im.decode(f);try{const t=Im.resize(c,96,Math.max(1,Math.round(96*c.height/c.width)));S.images.push({name:f.name,original:f,blob:f,thumb:t.toDataURL(),history:[]});Im.release(t);}finally{Im.release(c);}}
 S.index=first;Im.release(S.c);S.c=await Im.decode(file().blob);Im.release(S.pixel);S.pixel=null;if(S.editor==='pixel')await updatePixel(progress,signal);}
 UX.afterInput();track('file_selected',{count:files.length,file_kind:kinds.every(k=>k===kinds[0])?kinds[0]:'mixed'});
 });}
function dialog(title,content){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=content;$('#helpDialog').showModal();}
function help(privacy=false){
 S.helpPrivacy=privacy;
 if(privacy){dialog(t('내 파일은, 내 기기에.'),['privacy.local','privacy.network','privacy.storage','privacy.limits','privacy.unsupported'].map(k=>`<p>${esc(t(k))}</p>`).join('')+`<p><a href="${document.documentElement.lang}/privacy/" target="_blank" rel="noopener">${esc(t('shell.privacy'))} ↗</a></p>`);return;}
 dialog(t('필요한 것만, 간단하게.'),`<div class="help-grid">${Object.entries(names).map(([k,v])=>`<button data-action="help-editor:${k}">${icon(k)}${esc(v)}</button>`).join('')}</div><p>${esc(t('help.drop'))}</p>${checkbox('showLabels',t('아이콘 옆에 도구 이름 표시'),document.body.classList.contains('show-labels'))}<p>${esc(t('help.tooltips'))}</p><p><strong>Ctrl / ⌘ + Z</strong> ${esc(t('되돌리기'))} · <strong>Esc</strong> ${esc(t('설정 닫기'))}</p>`);
}
async function saveImages(progress,signal){const e=S.export,items=e.all?S.images:[file()],entries=[];let missed=0,total=0;for(let i=0;i<items.length;i++){check(signal);const f=items[i];progress(t("{0} / {1} 이미지 저장 중…", {0: i+1, 1: items.length}));const c=f===file()?S.c:await Im.decode(f.blob);try{const result=await Im.encode(c,{...e,quality:e.quality/100,allowShrink:e.shrink,signal,progress},()=>check(signal));if(!result.met){missed++;continue;}total+=result.blob.size;entries.push({name:`${stem(f.name)}-edited.${result.format==='jpeg'?'jpg':result.format}`,blob:result.blob});}finally{if(c!==S.c)Im.release(c);}}
 check(signal);if(!entries.length)throw Error(t("목표 용량을 만족하지 못했습니다. 목표를 늘리거나 추가 축소를 허용하세요."));if(entries.length===1&&!e.all)Im.download(entries[0].blob,entries[0].name);else Im.download(await zip(entries),BRAND.name.toLowerCase()+'-images.zip');message(missed?t("{0}장 저장 · 목표 미달 {1}장은 제외했습니다.", {0: entries.length, 1: missed}):t("{0}장 저장했어요. {1}", {0: entries.length, 1: bytes(entries.reduce((n,e)=>n+e.blob.size,0))}),missed>0);}
async function pixelPack(progress,signal){if(!S.c)throw Error(t("이미지를 먼저 추가하세요."));const entries=[];for(const n of[16,32,64,128]){check(signal);progress(t("{0} × {1} 도트 에셋 만드는 중…", {0: n, 1: n}));const c=await generatePixel(progress,signal,{...S.pix,n});try{entries.push({name:`${stem(file().name)}-${n}.png`,blob:await Im.blobOf(c)});}finally{Im.release(c);}}check(signal);Im.download(await zip(entries),BRAND.name.toLowerCase()+'-pixel-pack.zip');message(t("실제 16·32·64·128px PNG 세트를 저장했어요."));}
function runTask(label,fn){S.runIntent=UX.id;track('tool_run');return task(label,fn);}
/** Heavy editor actions pass the Free daily-limit check before any local work starts. */
async function meteredTask(toolId,label,fn,options){if(S.busy||!await authorize(toolId,options))return;return runTask(label,fn);}
async function onAction(action){if(S.busy&&action!=='cancel')return;
 if(await UX.action(action))return;
 if(action.startsWith('editor:'))return switchEditor(action.split(':')[1]);
 if(action.startsWith('help-editor:')){$('#helpDialog').close();return switchEditor(action.split(':')[1]);}
 if(action==='open')return $('#fileInput').click();if(action==='help')return help();if(action==='privacy')return help(true);if(action==='close-dialog')return $('#helpDialog').close();if(action==='cancel')return S.abort?.abort();if(action==='close-panel'){S.tool='';refresh();return paint();}
 if(action==='export'){S.tool=S.tool==='export'?'':'export';refresh();return paint();}
 if(action.startsWith('tool:')){const next=action.slice(5);S.tool=S.tool===next?'':next;refresh();return paint();}
 if(action==='share'){const paths={image:'image/editor/',pdf:'pdf/editor/',pixel:'pixel/',media:'media/'},url=new URL(paths[S.editor],root);if(S.editor==='pixel')url.searchParams.set('n',S.pix.n);if(S.tool)url.searchParams.set('tool',S.tool);if(S.editor==='image'){url.searchParams.set('format',S.export.format);if(S.export.kb)url.searchParams.set('kb',S.export.kb);}try{await navigator.clipboard.writeText(url.href);message(t("파일이 아닌 도구·설정 링크를 복사했어요."));}catch{dialog(t("링크 복사"),`<p>${t("share.noFiles")}</p><input style="width:100%" readonly value="${esc(url.href)}">`);}return;}
 if(action==='clear'){if((S.images.length||S.pdf.pages.length||S.media)&&!confirm(t("저장하지 않은 작업을 비울까요? 원본 파일은 삭제되지 않습니다.")))return;await task(t("작업실 비우는 중…"),async()=>{Im.release(S.c);Im.release(S.pixel);S.c=S.pixel=null;UX.invalidate();S.images=[];S.index=0;await S.pdf.clear();if(S.media){$('#video').pause();$('#video').removeAttribute('src');$('#video').load();URL.revokeObjectURL(S.media.url);S.media=null;}S.tool='';});return;}
 if(action==='sample'){const c=Im.canvas(720,560),ctx=c.getContext('2d');ctx.fillStyle='#eef3ff';ctx.fillRect(0,0,720,560);ctx.fillStyle='#dbe8fd';ctx.beginPath();ctx.ellipse(360,453,156,24,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff9269';ctx.beginPath();ctx.roundRect(257,271,206,178,[20,20,70,70]);ctx.fill();ctx.fillStyle='#f77857';ctx.fillRect(253,271,214,34);ctx.strokeStyle='#398770';ctx.lineWidth=13;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(360,284);ctx.bezierCurveTo(350,240,385,190,366,135);ctx.stroke();for(const [x,y,a]of[[325,226,-.8],[395,181,.5],[337,150,-.65]]){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillStyle='#56ae85';ctx.beginPath();ctx.ellipse(0,0,49,22,0,0,Math.PI*2);ctx.fill();ctx.restore();}ctx.fillStyle='#dfebfd';ctx.beginPath();ctx.arc(495,119,29,0,Math.PI*2);ctx.fill();const blob=await Im.blobOf(c);Im.release(c);return loadFiles([new File([blob],'little-plant.png',{type:'image/png'})]);}
 if(action.startsWith('select:')){const i=Number(action.split(':')[1]);if(S.editor==='pdf'){S.pdf.selected=i;refresh();return paint();}return task(t("이미지 여는 중…"),async(p,s)=>{for(const f of S.images)if(f!==file())f.history=[];S.index=i;Im.release(S.c);S.c=await Im.decode(file().blob);Im.release(S.pixel);S.pixel=null;if(S.editor==='pixel')await updatePixel(p,s);});}
 if(action==='undo'){if(S.editor==='pdf'){S.pdf.undo();refresh();return paint();}if(!file()?.history.length)return message(t("되돌릴 편집이 없어요."));return task(t("되돌리는 중…"),async(p,s)=>{const previous=file().history.at(-1),c=await Im.decode(previous,{signal:s,progress:p});check(s);file().history.pop();file().blob=previous;UX.invalidate();Im.release(S.c);S.c=c;Im.release(S.pixel);S.pixel=null;if(S.editor==='pixel')await updatePixel(p,s);});}
 if(action==='crop-reset'){S.crop={x:0,y:0,w:1,h:1};drawCrop();return;}
 if(action.startsWith('crop-preset:')){if(!S.c)return;const v=action.split(':')[1];if(v==='free')S.crop={x:.1,y:.1,w:.8,h:.8};else{const ratio=Number(v);let w=S.c.width*.8,h=w/ratio;if(h>S.c.height*.8){h=S.c.height*.8;w=h*ratio;}S.crop={x:(1-w/S.c.width)/2,y:(1-h/S.c.height)/2,w:w/S.c.width,h:h/S.c.height};}drawCrop();return;}
 if(action==='rotate'||action==='image:flip')return runTask(t("이미지 회전 중…"),()=>{if(!S.c)throw Error(t("이미지를 먼저 추가하세요."));return setImage(Im.rotate(S.c,action==='image:flip'),true,{type:'rotate',flip:action==='image:flip'});});
 if(action==='image:crop')return runTask(t("자르는 중…"),async()=>{if(!S.c)throw Error(t("이미지를 먼저 추가하세요."));await setImage(Im.crop(S.c,S.crop),true,{type:'crop',rect:{...S.crop}});S.tool='';});
 if(action==='image:resize'){if(!S.c)return message(t("이미지를 먼저 추가하세요."));const w=integer($('#resizeW').value,1,65535,t("너비")),h=integer($('#resizeH').value,1,65535,t("높이"));return runTask(t("크기를 바꾸는 중…"),async(p,s)=>setImage(await Im.resizeQuality(S.c,w,h,{signal:s,progress:p}),true,{type:'resize',width:w,height:h}));}
 if(action==='image:upscale'){if(!S.c)return message(t("이미지를 먼저 추가하세요."));const scale=Number($('#scale').value),mode=$('#scaleMode').value;return meteredTask('upscale',t("이미지를 확대하는 중…"),async(p,s)=>setImage(await Im.upscale(S.c,scale,mode,{signal:s,progress:p})));}
 if(action==='image:remove'){if(!S.c)return message(t("이미지를 먼저 추가하세요."));const hex=$('#removeColor').value,color=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)),tolerance=Number($('#tolerance').value);return runTask(t("단색 배경을 분리하는 중…"),async(p,s)=>setImage(await Im.processPixels(S.c,'remove',{color,tolerance},p,s)));}
 if(action==='image:portrait'){if(!S.c)return message(t("이미지를 먼저 추가하세요."));return meteredTask('remove-bg',t("인물 모델 준비 중…"),async(p,s)=>setImage(await Im.processPixels(S.c,'portrait',{},p,s)),{background:'portrait'});}
 if(action==='image:outline'){if(!S.c)return;return runTask(t("외곽선을 만드는 중…"),async(p,s)=>setImage(await Im.processPixels(S.c,'outline',{radius:1},p,s)));}
 if(action==='image:trim'){if(!S.c)return;return runTask(t("여백을 정리하는 중…"),async(p,s)=>setImage(await Im.trimAsync(S.c,{signal:s,progress:p}),true,{type:'trim'}));}
 if(action==='image:fill'){if(!S.c)return;const color=$('#fillColor').value;return runTask(t("배경색 적용 중…"),()=>setImage(Im.background(S.c,color),true,{type:'fill',color}));}
 if(action==='image:reset'){if(!file())return;return runTask(t("원본을 여는 중…"),async()=>setImage(await Im.decode(file().original)));}
 if(action==='image:save'){readExport();return runTask(t("저장 파일을 만드는 중…"),saveImages);}
 if(action==='image:to-pdf'){if(!S.c)return;return runTask(t("PDF 페이지를 만드는 중…"),async(p,s)=>{const blob=await Im.blobOf(S.c);await S.pdf.add([new File([blob],`${stem(file().name)}.png`,{type:'image/png'})],p,s);S.editor='pdf';S.tool='';});}
 if(action.startsWith('size:')){S.pix.n=Number(action.split(':')[1]);if(!S.c){refresh();return;}return task(t("도트화하는 중…"),updatePixel);}
 if(action==='pixel:apply'){S.pix={palette:parsePalette($('#pixelPalette').value),paletteText:$('#pixelPalette').value,ditherMode:$('#pixelDitherMode').value,n:integer($('#pixelN').value,8,512,'N'),colors:Number($('#pixelColors').value),dither:Number($('#pixelDither').value),fit:$('#pixelFit').value,trim:$('#pixelTrim').checked,outline:Number($('#pixelOutline').value)};return runTask(t("도트화하는 중…"),updatePixel);}
 if(action==='pixel:pack')return runTask(t("도트 세트를 만드는 중…"),pixelPack);
 if(action==='pixel:save'){const scale=Number($('#pixelScale')?.value||1);return task(t("도트 에셋 저장 중…"),async(p,s)=>{if(!S.pixel)await updatePixel(p,s);const c=Im.resize(S.pixel,S.pixel.width*scale,S.pixel.height*scale,true);try{Im.download(await Im.blobOf(c),`${stem(file().name)}-${S.pix.n}px-${scale}x.png`);}finally{Im.release(c);}});}
 if(action==='pixel:to-image')return task(t("이미지 편집기로 보내는 중…"),async(p,s)=>{if(!S.pixel)await updatePixel(p,s);const c=Im.copy(S.pixel);await setImage(c);S.editor='image';S.tool='';});
 if(action==='pdf:current'){S.pdfExport.range=String(S.pdf.selected+1);$('#pdfRange').value=S.pdfExport.range;return;}
 if(action==='pdf:overlay'){if(!S.pdf.current())return message(t("PDF 파일을 먼저 추가하세요."));return $('#overlayInput').click();}
 if(action==='pdf:save'){S.pdfExport=readPDFOptions();return runTask(t("PDF 저장 준비 중…"),async(p,s)=>{const e=S.pdfExport;if(e.format==='pdf'&&e.splitMode!=='single'){const entries=await S.pdf.split({...e,mode:e.splitMode,every:e.splitMode==='each'?1:e.every},p,s);check(s);Im.download(await zip(entries,{signal:s}),BRAND.name.toLowerCase()+'-split.zip');}else if(e.format==='pdf'){const blob=await S.pdf.export(e,p,s);check(s);Im.download(blob,BRAND.name.toLowerCase()+'-edited.pdf');message(t("PDF를 저장했어요. {0}{1}", {0: bytes(blob.size), 1: e.raster?t(" · 페이지를 이미지로 변환한 사본"):''}));}else{const entries=await S.pdf.imageExports(e,p,s);check(s);if(entries.length===1)Im.download(entries[0].blob,entries[0].name);else Im.download(await zip(entries),BRAND.name.toLowerCase()+'-pages.zip');}});}
 if(action.startsWith('pdf:')){if(!S.pdf.current())return;const cmd=action.split(':')[1];if(cmd==='left')S.pdf.move(-1);if(cmd==='right')S.pdf.move(1);if(['rotate','remove','duplicate'].includes(cmd))S.pdf[cmd]();if(cmd==='clear-marks'){S.pdf.snapshot();S.pdf.current().marks=[];}for(const p of S.pdf.pages)p.thumb=null;refresh();return paint();}
 if(action==='media:audio'||action==='media:gif'){S.mediaExport.format=action==='media:audio'?'mp3':'gif';if(action==='media:gif'&&S.media)S.mediaExport.end=Math.min(S.mediaExport.start+4,S.media.duration);S.tool='export';refresh();return;}
 if(action==='media:set-start'){if(!S.media)return;S.mediaExport.start=Number($('#video').currentTime.toFixed(1));S.mediaExport.end=Math.min(S.media.duration,S.mediaExport.start+5);renderPanel();return;}
 if(action==='media:frame')return runTask(t("장면을 저장하는 중…"),async(p,s)=>{if(!S.media)throw Error(t("영상을 먼저 추가하세요."));const c=await Media.frame($('#video'),$('#video').currentTime,s);try{Im.download(await Im.blobOf(c),`${stem(S.media.file.name)}-frame.png`);}finally{Im.release(c);}});
 if(action==='media:save'){S.mediaExport=readMediaOptions();return meteredTask(mediaExportTool(S.mediaExport.format),t("미디어를 저장하는 중…"),async(p,s)=>{if(!S.media)throw Error(t("미디어 파일을 먼저 추가하세요."));const e=S.mediaExport,blob=e.format==='gif'?await Media.exportGif($('#video'),S.media,e.start,e.end,p,s,e):['mp3','wav'].includes(e.format)?await Media.exportAudio(S.media,e.start,e.end,e.format,p,s,e):await Media.exportVideo($('#video'),S.media,e.start,e.end,e.width,p,s,e);check(s);Im.download(blob,`${stem(S.media.file.name)}-clip.${e.format}`);setTimeout(()=>Media.releaseOutput(blob),60000);message(t("{0} 저장했어요.", {0: bytes(blob.size)}));});}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled){if(b.tagName==='A'){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();}onAction(b.dataset.action).catch(err=>message(err.message,true));}});
$('#fileInput').addEventListener('change',async e=>{const files=[...e.target.files];e.target.value='';await loadFiles(files);});
$('#overlayInput').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f||!S.pdf.current())return;await task(t("이미지 표시를 추가하는 중…"),async()=>{const image=await Im.decode(f),p=S.pdf.current(),w=Math.min(.5,.5*p.logicalH/p.logicalW*image.width/image.height),h=w*p.logicalW/p.logicalH*image.height/image.width;S.pdf.mark({type:'image',image,x:.15,y:.15,w,h});p.thumb=null;});});
$('#panel').addEventListener('input',e=>{if(S.editor==='image'&&S.tool==='resize'&&$('#ratioLock')?.checked&&S.c){if(e.target.id==='resizeW')$('#resizeH').value=Math.max(1,Math.round(Number(e.target.value)*S.c.height/S.c.width));if(e.target.id==='resizeH')$('#resizeW').value=Math.max(1,Math.round(Number(e.target.value)*S.c.width/S.c.height));}});
$('#helpDialog').addEventListener('change',e=>{if(e.target.id==='showLabels')document.body.classList.toggle('show-labels',e.target.checked);});
let dragDepth=0;document.addEventListener('dragenter',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();dragDepth++;if(!S.busy)$('#dropOverlay').hidden=false;}});document.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files'))e.preventDefault();});document.addEventListener('dragleave',()=>{dragDepth--;if(dragDepth<=0)$('#dropOverlay').hidden=true;});document.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();dragDepth=0;$('#dropOverlay').hidden=true;loadFiles(e.dataTransfer.files);}});
$('#fileStrip').addEventListener('dragstart',e=>{const el=e.target.closest('[data-index]');if(el&&S.editor==='pdf')e.dataTransfer.setData('application/x-fileforge-page',el.dataset.index);});$('#fileStrip').addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('application/x-fileforge-page'))e.preventDefault();});$('#fileStrip').addEventListener('drop',e=>{const i=e.dataTransfer.getData('application/x-fileforge-page'),target=e.target.closest('[data-index]');if(i!==''&&target&&S.editor==='pdf'&&!S.busy){e.preventDefault();e.stopPropagation();S.pdf.reorder(Number(i),Number(target.dataset.index));refresh();paint().catch(err=>message(err.message,true));}});
function point(e){const r=$('#preview').getBoundingClientRect();return [clamp((e.clientX-r.left)/r.width,0,1),clamp((e.clientY-r.top)/r.height,0,1)];}
$('#canvasWrap').addEventListener('pointerdown',e=>{if(S.busy||!ready())return;const [x,y]=point(e),view=$('#preview'),ctx=view.getContext('2d');if(S.editor==='image'&&S.tool==='crop'){e.preventDefault();$('#canvasWrap').setPointerCapture(e.pointerId);S.pointer={mode:'crop',x,y};S.crop={x,y,w:0,h:0};drawCrop();return;}
 if(S.editor!=='pdf')return;const p=S.pdf.current(),[bx,by]=inversePoint(x,y,p.angle);if(S.tool==='text'){const text=$('#markText').value;if(!text.trim())return message(t("추가할 글자를 먼저 입력하세요."));S.pdf.mark({type:'text',text:text.slice(0,2000),x:bx,y:by,size:Number($('#markSize').value)||20,color:$('#markColor').value});p.thumb=null;paint().catch(err=>message(err.message,true));return;}
 if(S.tool==='pen'){e.preventDefault();$('#canvasWrap').setPointerCapture(e.pointerId);S.pointer={mode:'pen',type:$('#penMode').value,screen:[[x,y]],points:[[bx,by]],size:Number($('#markSize').value)||3,color:$('#markColor').value,base:ctx.getImageData(0,0,view.width,view.height)};return;}
 if(!S.tool){for(let i=p.marks.length-1;i>=0;i--){const m=p.marks[i];if(m.type==='pen')continue;const w=m.w||(m.text?.split('\n').reduce((a,t)=>Math.max(a,t.length),0)||1)*(m.size||20)*.7/p.logicalW,h=m.h||(m.text?.split('\n').length||1)*(m.size||20)*1.35/p.logicalH;if(bx>=m.x&&bx<=m.x+w&&by>=m.y&&by<=m.y+h){S.pdf.snapshot();$('#canvasWrap').setPointerCapture(e.pointerId);S.pointer={mode:'move',mark:m,ox:m.x,oy:m.y,x:bx,y:by,nx:m.x,ny:m.y};break;}}}
});
$('#canvasWrap').addEventListener('pointermove',e=>{const d=S.pointer;if(!d)return;const [x,y]=point(e);if(d.mode==='crop'){S.crop={x:Math.min(x,d.x),y:Math.min(y,d.y),w:Math.abs(x-d.x),h:Math.abs(y-d.y)};drawCrop();return;}const p=S.pdf.current(),[bx,by]=inversePoint(x,y,p.angle);if(d.mode==='move'){d.nx=clamp(d.ox+bx-d.x,0,.98);d.ny=clamp(d.oy+by-d.y,0,.98);return;}d.points.push([bx,by]);d.screen.push([x,y]);const v=$('#preview'),ctx=v.getContext('2d');ctx.putImageData(d.base,0,0);ctx.save();ctx.strokeStyle=d.color;ctx.fillStyle=d.color;ctx.lineWidth=Math.max(1,d.size*v.width/p.logicalW);ctx.lineCap='round';ctx.lineJoin='round';if(d.type==='pen'){ctx.beginPath();d.screen.forEach(([x,y],i)=>i?ctx.lineTo(x*v.width,y*v.height):ctx.moveTo(x*v.width,y*v.height));ctx.stroke();}else{const [sx,sy]=d.screen[0];if(d.type==='highlight'){ctx.globalAlpha=.3;ctx.fillRect(sx*v.width,sy*v.height,(x-sx)*v.width,(y-sy)*v.height);}else ctx.strokeRect(sx*v.width,sy*v.height,(x-sx)*v.width,(y-sy)*v.height);}ctx.restore();});
function endPointer(){const d=S.pointer;if(!d)return;S.pointer=null;if(d.mode==='crop'){if(S.crop.w<.01||S.crop.h<.01)S.crop={x:.1,y:.1,w:.8,h:.8};drawCrop();return;}if(d.mode==='move'){d.mark.x=d.nx;d.mark.y=d.ny;}else if(d.points.length>1){const xs=d.points.map(p=>p[0]),ys=d.points.map(p=>p[1]);S.pdf.mark({type:d.type,points:d.points,x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys),color:d.color,size:d.size});}S.pdf.current().thumb=null;paint().catch(err=>message(err.message,true));}
$('#canvasWrap').addEventListener('pointerup',endPointer);$('#canvasWrap').addEventListener('pointercancel',endPointer);
document.addEventListener('keydown',e=>{if(S.busy)return;if(e.key==='Escape'){S.tool='';S.pointer=null;refresh();paint().catch(()=>{});}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();onAction('undo').catch(err=>message(err.message,true));}});
window.addEventListener('popstate',()=>UX.popstate().catch(err=>message(err.message,true)));
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>paint().catch(()=>{}),100);});
window.addEventListener('beforeunload',e=>{if(S.busy){e.preventDefault();e.returnValue='';}});
$('#helpButton').innerHTML=icon('help');initTooltips();refresh();paint().catch(err=>message(err.message,true));

$('#panel').addEventListener('input',e=>{
 if(!S.c)return;const id=e.target.id;
 if(id.startsWith('crop-')){
  const x=clamp(Number($('#crop-x').value)||0,0,S.c.width-1),y=clamp(Number($('#crop-y').value)||0,0,S.c.height-1);
  S.crop={x:x/S.c.width,y:y/S.c.height,w:clamp(Number($('#crop-w').value)||1,1,S.c.width-x)/S.c.width,h:clamp(Number($('#crop-h').value)||1,1,S.c.height-y)/S.c.height};drawCrop();
 }
 if(['resize-percent','resize-long','resize-mp'].includes(id)){
  const value=e.target.valueAsNumber;if(!(value>0))return;
  const ratio=id==='resize-percent'?value/100:id==='resize-long'?value/Math.max(S.c.width,S.c.height):Math.sqrt(value*1e6/(S.c.width*S.c.height));
  $('#resizeW').value=Math.max(1,Math.round(S.c.width*ratio));$('#resizeH').value=Math.max(1,Math.round(S.c.height*ratio));
 }
});
$('#canvasWrap').tabIndex=0;
$('#canvasWrap').addEventListener('keydown',e=>{
 if(S.busy||S.tool!=='crop'||!S.c||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;
 e.preventDefault();const step=e.shiftKey?10:1,dx=(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0)/S.c.width,dy=(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)/S.c.height;
 if(e.altKey){S.crop.w=clamp(S.crop.w+dx,1/S.c.width,1-S.crop.x);S.crop.h=clamp(S.crop.h+dy,1/S.c.height,1-S.crop.y);}
 else{S.crop.x=clamp(S.crop.x+dx,0,1-S.crop.w);S.crop.y=clamp(S.crop.y+dy,0,1-S.crop.h);}drawCrop();
});
// Files carried over from the home directory or another tool (src/task/handoff.js); local only.
import('./task/handoff.js').then(m=>m.takeFiles()).then(files=>{if(files.length)loadFiles(files);}).catch(()=>{});
