import {LIMITS,clamp,integer,dimensions,bytes,safeName,stem,typeOf,route,zip,inversePoint} from './core.js';
import * as Im from './image.js';
import {PDFWorkspace} from './pdf.js';
import * as Media from './media.js';
import {icon,button,esc,initTooltips} from './ui.js';
const $=s=>document.querySelector(s),root=new URL('../',import.meta.url),initial=route(location.pathname,location.search);
const names={image:'이미지 편집',pdf:'PDF 편집',pixel:'도트화',media:'미디어 편집'},kickers={image:'IMAGE STUDIO',pdf:'PDF STUDIO',pixel:'PIXEL STUDIO',media:'MEDIA STUDIO'};
const S={editor:initial.editor,tool:initial.tool,images:[],index:0,c:null,pixel:null,pdf:new PDFWorkspace(),media:null,busy:false,abort:null,view:0,crop:{x:.1,y:.1,w:.8,h:.8},pointer:null,markImage:null,
 export:{format:initial.format,kb:initial.kb||(/compress/.test(location.pathname)&&initial.editor==='image'?500:0),quality:92,width:0,shrink:false,bg:'#ffffff',all:false},
 pix:{n:initial.n,colors:16,dither:0,fit:'contain',trim:true,outline:0},pdfExport:{range:'',format:initial.pdfFormat,raster:initial.pdfRaster},mediaExport:{format:initial.mediaFormat,start:0,end:0,width:1280}};
let messageTimer;const file=()=>S.images[S.index],ready=()=>S.editor==='pdf'?S.pdf.pages.length:S.editor==='media'?S.media:!!S.c;
function message(text,error=false){clearTimeout(messageTimer);$('#message').textContent=text;$('#message').classList.toggle('error',error);$('#message').hidden=false;if(!error)messageTimer=setTimeout(()=>$('#message').hidden=true,6500);}
function check(signal=S.abort?.signal){if(signal?.aborted)throw new DOMException('취소했습니다.','AbortError');}
async function task(label,fn){if(S.busy)return;S.busy=true;S.abort=new AbortController();const signal=S.abort.signal;document.body.classList.add('busy');$('#workspace').setAttribute('aria-busy','true');$('#message').hidden=true;$('#progress').hidden=false;const progress=t=>$('#progressText').textContent=t;progress(label);try{await fn(progress,signal);check(signal);}catch(e){message(e.name==='AbortError'?'작업을 취소했어요.':e.message||String(e),e.name!=='AbortError');}finally{S.busy=false;S.abort=null;document.body.classList.remove('busy');$('#workspace').setAttribute('aria-busy','false');$('#progress').hidden=true;refresh();await paint().catch(e=>message(e.message,true));}}
function switchEditor(editor,push=true){if(S.busy)return;S.editor=editor;S.tool='';if(push){const paths={image:'image/editor/',pdf:'pdf/editor/',pixel:'pixel/',media:'media/'};history.pushState({},'',new URL(paths[editor],root));}refresh();paint().catch(e=>message(e.message,true));if(editor==='pixel'&&S.c&&!S.pixel)task('도트 에셋 만드는 중…',updatePixel);}
function refresh(){
 $('#navigation').innerHTML=['image','pdf','pixel','media'].map(n=>button(`editor:${n}`,n,names[n],'')).join('')+'<span class="nav-separator"></span>'+button('share','share','설정 링크 복사')+button('clear','trash','작업실 비우기');
 // Explicitly set state instead of relying on duplicate HTML attributes.
 $('#navigation').querySelectorAll('[data-action^="editor:"]').forEach(b=>{const on=b.dataset.action===`editor:${S.editor}`;b.classList.toggle('active',on);b.setAttribute('aria-current',on?'page':'false');});
 $('#editorTitle').textContent=names[S.editor];$('#editorKicker').textContent=kickers[S.editor];document.title=`${names[S.editor]} · FileForge`;
 $('#topActions').innerHTML=button('undo','undo','되돌리기',ready()?'':'disabled')+button('open','plus','파일 추가')+`<button class="export-button" data-action="export" ${ready()?'':'disabled'}>${icon('download',18)}저장</button>`;
 const b=(t,i,l)=>button(`tool:${t}`,i,l);
 if(S.editor==='image')$('#toolDock').innerHTML=b('crop','crop','자르기')+b('resize','resize','크기 변경')+button('rotate','rotate','90° 회전')+b('background','background','배경 제거')+b('upscale','upscale','2× · 4× 확대')+button('editor:pixel','pixel','도트화로 보내기')+b('more','sliders','추가 이미지 도구');
 else if(S.editor==='pdf')$('#toolDock').innerHTML=button('pdf:left','left','페이지 앞으로 이동')+button('pdf:right','right','페이지 뒤로 이동')+button('pdf:rotate','rotate','페이지 회전')+button('pdf:remove','trash','페이지 삭제')+b('text','text','글자 추가')+b('pen','pen','그리기 · 서명')+b('more','sliders','페이지 · 주석 도구');
 else if(S.editor==='pixel')$('#toolDock').innerHTML=[16,32,64,128].map(n=>`<button class="chip ${S.pix.n===n?'selected':''}" data-action="size:${n}" aria-label="${n}×${n} 도트">${n}</button>`).join('')+b('pixel','sliders','색상 · 디더링 · 사용자 크기')+button('pixel:pack','pack','16·32·64·128 크기 세트');
 else $('#toolDock').innerHTML=button('media:frame','image','현재 장면을 이미지로')+b('export','scissors','구간 자르기 · 저장')+button('media:audio','audio','오디오 추출')+button('media:gif','media','짧은 GIF 만들기');
 $('#toolDock').querySelectorAll('[data-action^="tool:"]').forEach(b=>b.classList.toggle('active',b.dataset.action===`tool:${S.tool}`));
 $('#emptyTitle').textContent={image:'파일을 놓으면, 시작돼요.',pdf:'페이지를 한곳에, 간단하게.',pixel:'작은 픽셀로, 새롭게.',media:'필요한 순간만, 가볍게.'}[S.editor];$('#emptySubtitle').textContent={image:'PNG · JPG · WebP · HEIC',pdf:'PDF · 여러 이미지',pixel:'이미지 → 16 · 32 · 64 · 128px',media:'MP4 · WebM · 오디오'}[S.editor];
 $('#fileInput').accept=S.editor==='pdf'?'.pdf,image/png,image/jpeg,image/webp':S.editor==='media'?'video/*,audio/*':S.editor==='pixel'?'image/png,image/jpeg,image/webp,image/avif,.heic,.heif':'image/*,.heic,.heif,.pdf,video/*,audio/*';
 renderPanel();renderStrip();
}
async function paint(){const version=++S.view,has=!!ready();$('#emptyState').hidden=has;$('#canvasWrap').hidden=!has||S.editor==='media';$('#video').hidden=!has||S.editor!=='media';$('#stageBadge').hidden=!has;$('#stage').classList.toggle('pixel-mode',S.editor==='pixel'&&!!S.pixel);$('#cropBox').hidden=!(has&&S.editor==='image'&&S.tool==='crop');
 if(!has){$('#documentInfo').textContent='원본은 그대로, 작업은 내 기기에서.';return;}
 if(S.editor==='media'){const m=S.media;$('#documentInfo').textContent=`${safeName(m.file.name)} · ${m.duration.toFixed(1)}초 · ${bytes(m.file.size)}`;$('#stageBadge').textContent=m.w?`${m.w} × ${m.h}`:'오디오 파일';return;}
 let source=S.editor==='pdf'?await S.pdf.render():S.editor==='pixel'&&S.pixel?S.pixel:S.c;const temporary=S.editor==='pdf';if(version!==S.view){if(temporary)Im.release(source);return;}if(!source)return;
 const bounds=$('#stage').getBoundingClientRect(),maxW=Math.max(50,bounds.width-52),maxH=Math.max(50,bounds.height-52),isPixel=S.editor==='pixel'&&!!S.pixel,scale=Math.min(isPixel?16:1,maxW/source.width,maxH/source.height),w=Math.max(1,Math.round(source.width*scale)),h=Math.max(1,Math.round(source.height*scale)),view=$('#preview');view.width=isPixel?source.width:w;view.height=isPixel?source.height:h;view.style.width=`${w}px`;view.style.height=`${h}px`;$('#canvasWrap').style.width=`${w}px`;$('#canvasWrap').style.height=`${h}px`;view.getContext('2d').drawImage(source,0,0,view.width,view.height);
 $('#stageBadge').textContent=S.editor==='pdf'?`${S.pdf.selected+1} / ${S.pdf.pages.length}`:`${source.width} × ${source.height}${isPixel?' · 실제 에셋 크기':''}`;
 $('#documentInfo').textContent=S.editor==='pdf'?`${S.pdf.pages.length}페이지 · 원본 글자 직접 수정은 지원하지 않아요.`:`${safeName(file()?.name||'image')} · ${source.width} × ${source.height}${isPixel?' · PNG':` · ${bytes(file()?.blob.size||0)}`}`;
 if(temporary){const p=S.pdf.current();if(!p.thumb){const t=Im.resize(source,Math.max(1,Math.round(source.width*100/source.height)),100);p.thumb=t.toDataURL();Im.release(t);renderStrip();}Im.release(source);}drawCrop();}
function drawCrop(){const r=S.crop;Object.assign($('#cropBox').style,{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'});}
function renderStrip(){const el=$('#fileStrip');if(S.editor==='media'||!ready()){el.hidden=true;return;}const pdf=S.editor==='pdf',items=pdf?S.pdf.pages:S.images;el.hidden=items.length<2&&!pdf;el.innerHTML=items.map((f,i)=>`<button class="thumb ${i===(pdf?S.pdf.selected:S.index)?'active':''}" data-action="select:${i}" aria-label="${pdf?`${i+1}페이지`:esc(f.name)}" ${pdf?'draggable="true"':''} data-index="${i}">${f.thumb?`<img src="${f.thumb}" alt="">`:icon(pdf?'pdf':'image',26)}<span>${i+1}</span></button>`).join('');}
const field=(label,html)=>`<label class="field"><span>${label}</span>${html}</label>`,number=(id,v,min=1,max=8192)=>`<input id="${id}" type="number" min="${min}" max="${max}" value="${v}">`,select=(id,items,v)=>`<select id="${id}">${items.map(([k,t])=>`<option value="${k}" ${String(k)===String(v)?'selected':''}>${t}</option>`).join('')}</select>`,act=(action,label,cls='primary')=>`<button class="${cls}" data-action="${action}">${label}</button>`,hint=(s,w=false)=>`<p class="hint ${w?'warning':''}">${s}</p>`,checkbox=(id,text,on=false)=>`<label class="checks"><input type="checkbox" id="${id}" ${on?'checked':''}>${text}</label>`;
function renderPanel(){const el=$('#panel');el.hidden=!S.tool;if(!S.tool)return;let title='',html='';
 if(S.tool==='export'){
 title='저장';if(S.editor==='image'){const e=S.export;html=field('형식',select('outFormat',[['png','PNG · 투명 배경'],['jpeg','JPG · 사진'],['webp','WebP · 웹용']],e.format))+field('품질 · JPG / WebP',`<input id="quality" type="range" min="25" max="100" value="${e.quality}" aria-label="출력 품질">`)+field('목표 용량 · 0은 제한 없음',number('targetKB',e.kb,0,32768))+field('최대 너비 · 0은 현재 크기',number('outWidth',e.width,0,8192))+field('JPG 배경색',`<input id="exportBg" type="color" value="${e.bg}">`)+checkbox('allowShrink','용량이 넘으면 추가 축소 허용',e.shrink)+(S.images.length>1?checkbox('exportAll','모든 이미지에 저장 설정 적용 · ZIP',e.all):'')+act('image:save','내 기기에 저장')+hint('JPG는 투명 영역을 배경색으로 합칩니다. 재인코딩 시 원본 메타데이터·색상 프로필은 유지되지 않을 수 있어요.');}
 else if(S.editor==='pixel')html=field('PNG 크기',select('pixelScale',[[1,'1× · 실제 도트 에셋'],[2,'2× · 정수배 확대'],[4,'4× · 정수배 확대']],1))+act('pixel:save','PNG 저장')+act('pixel:pack','16 · 32 · 64 · 128 세트','secondary')+act('pixel:to-image','이미지 편집기로 보내기','secondary')+hint('작은 원본 에셋은 1×로 저장하세요. 확대 저장은 새 디테일을 만들지 않습니다.');
 else if(S.editor==='pdf'){const e=S.pdfExport;html=field('형식',select('pdfFormat',[['pdf','PDF'],['jpeg','JPG · 페이지별'],['png','PNG · 페이지별']],e.format))+field('페이지 · 비우면 전체',`<input id="pdfRange" placeholder="1, 3-5" value="${esc(e.range)}">`)+act('pdf:current','현재 페이지만 선택','secondary')+checkbox('rasterPdf','이미지 기반 용량 축소 저장',e.raster)+hint('용량 축소를 선택하면 페이지 전체가 이미지가 됩니다. 글자 검색·선택, 벡터 선명도, 양식, 기존 서명을 유지하지 않아요. 크기 감소도 보장되지 않습니다.',true)+act('pdf:save','선택한 페이지 저장');}
 else{const e=S.mediaExport;html=`<div class="row">${field('시작 · 초',`<input id="mediaStart" type="number" min="0" step="0.1" value="${e.start}">`)}${field('끝 · 초',`<input id="mediaEnd" type="number" min="0" step="0.1" value="${e.end}">`)}</div>`+field('저장 형식',select('mediaFormat',[['webm','WebM · 영상'],['mp3','MP3 · 오디오'],['wav','WAV · 오디오'],['gif','GIF · 최대 8초']],e.format))+field('영상 최대 너비',select('mediaWidth',[[1280,'1280px'],[854,'854px'],[640,'640px']],e.width))+act('media:set-start','현재 시점을 시작으로','secondary')+act('media:save','구간 저장')+hint('영상은 최대 120초를 실시간 WebM으로 기록합니다. 탭을 열린 상태로 유지하세요. MP4 출력·프레임 단위 정밀 자르기는 지원하지 않아요.',true);}
 }else if(S.editor==='image'){
 if(S.tool==='crop'){title='자르기';html='<div class="chips">'+[['free','자유'],['1','1:1'],['1.333333','4:3'],['1.777778','16:9']].map(([v,t])=>`<button class="chip" data-action="crop-preset:${v}">${t}</button>`).join('')+'</div>'+hint('이미지 위에서 드래그해 영역을 선택하세요.')+act('image:crop','선택 영역 적용');}
 if(S.tool==='resize'){title='크기 변경';html=field('너비 · px',number('resizeW',initial.w||S.c?.width||1080))+field('높이 · px',number('resizeH',initial.h||S.c?.height||1080))+checkbox('ratioLock','원본 비율 유지',true)+act('image:resize','크기 적용');}
 if(S.tool==='background'){title='배경 제거';html=field('제거할 단색',`<input id="removeColor" type="color" value="#ffffff">`)+field('비슷한 색 허용 범위',`<input id="tolerance" type="range" min="0" max="180" value="40" aria-label="색상 허용 범위">`)+act('image:remove','단색 배경 제거')+hint('가장자리와 연결된 비슷한 색만 지워요. 흰 배경의 로고·상품 이미지에 적합합니다.')+act('image:portrait','AI 인물 배경 제거','secondary')+hint('인물 전용 · 첫 사용 시 라이브러리와 모델 다운로드. 기기에 따라 오래 걸릴 수 있으며 취소할 수 있어요. 일반 사물 전용 AI 모델은 아닙니다.');}
 if(S.tool==='upscale'){title='크게, 더 선명하게';html=field('배율',select('scale',[[2,'2×'],[4,'4×']],2))+field('방식',select('scaleMode',[['smooth','부드럽게 · 사진 / 일러스트'],['pixel','픽셀 유지 · 도트 이미지']],'smooth'))+act('image:upscale','확대 적용')+hint('일반 보간 확대입니다. AI가 디테일을 복원하는 기능이 아니에요. 최대 1,600만 픽셀까지 지원합니다.',true);}
 if(S.tool==='more'){title='추가 도구';html=act('image:flip','좌우 반전','secondary')+act('image:trim','투명 여백 잘라내기','secondary')+act('image:outline','1px 외곽선 추가','secondary')+field('새 배경색',`<input id="fillColor" type="color" value="#ffffff">`)+act('image:fill','배경색 적용','secondary')+act('image:to-pdf','이 이미지를 PDF에 추가','secondary')+act('image:reset','원본으로 되돌리기','secondary');}
 }else if(S.editor==='pixel'){title='도트 에셋';html=field('N × N · 8–512px',number('pixelN',S.pix.n,8,512))+field('팔레트',select('pixelColors',[[0,'제한 없음'],[8,'8색'],[16,'16색'],[32,'32색'],[64,'64색']],S.pix.colors))+field('디더링',select('pixelDither',[[0,'없음'],[.5,'약하게'],[1,'강하게']],S.pix.dither))+field('이미지 배치',select('pixelFit',[['contain','비율 유지 · 여백'],['cover','가득 채우기 · 자르기']],S.pix.fit))+checkbox('pixelTrim','투명 여백 자동 제거',S.pix.trim)+field('외곽선',select('pixelOutline',[[0,'없음'],[1,'1px'],[2,'2px']],S.pix.outline))+act('pixel:apply','도트화 적용')+hint('원본의 색·형태를 픽셀로 단순화합니다. 새 애니메이션이나 손으로 그린 도트를 생성하는 AI는 아닙니다. 외곽선 색은 팔레트에 별도로 추가돼요.');}
 else if(S.editor==='pdf'){
 if(S.tool==='text'){title='글자 추가';html=field('내용',`<textarea id="markText" placeholder="여기에 입력하세요"></textarea>`)+field('크기',number('markSize',20,8,120))+field('색상',`<input id="markColor" type="color" value="#182a43">`)+hint('페이지에서 원하는 위치를 누르세요. 추가한 글자는 이미지 주석으로 저장되며, 기존 본문을 수정하지 않습니다.');}
 if(S.tool==='pen'){title='그리기 · 서명';html=field('도구',select('penMode',[['pen','펜 · 서명 그리기'],['highlight','형광 표시'],['rect','사각형']],'pen'))+field('굵기',number('markSize',3,1,40))+field('색상',`<input id="markColor" type="color" value="#3182f6">`)+hint('페이지 위에 그려주세요. 서명은 그림이며 인증서 기반 전자서명이 아닙니다. 표시를 덮는 것은 보안용 마스킹이 아닙니다.');}
 if(S.tool==='more'){title='페이지와 주석';html=act('pdf:duplicate','페이지 복제','secondary')+act('pdf:overlay','이미지 / 서명 이미지 추가','secondary')+act('pdf:clear-marks','현재 페이지의 추가 표시 지우기','secondary')+act('open','PDF / 이미지 더 추가','secondary')+hint('썸네일을 드래그하거나 화살표로 순서를 바꿔요. 합치기는 파일 추가로, 분할은 저장할 페이지 범위로 처리합니다.');}
 }
 el.innerHTML=`<div class="panel-header"><h2>${title||'설정'}</h2>${button('close-panel','close','설정 닫기')}</div>${html}`;
}
function readExport(){S.export={format:$('#outFormat').value,kb:integer($('#targetKB').value,0,32768,'목표 KB'),quality:integer($('#quality').value,25,100,'품질'),width:integer($('#outWidth').value,0,8192,'최대 너비'),shrink:$('#allowShrink').checked,bg:$('#exportBg').value,all:$('#exportAll')?.checked||false};return S.export;}
function imageMemory(){const unique=new Set();for(const f of S.images){unique.add(f.original);unique.add(f.blob);for(const b of f.history)unique.add(b);}return [...unique].reduce((n,b)=>n+b.size,0);}
async function setImage(c,remember=true){const f=file();if(!f){Im.release(c);throw Error('이미지를 먼저 추가하세요.');}try{const blob=await Im.blobOf(c);check();if(blob.size>LIMITS.imageBytes)throw Error('편집 결과가 32MB를 초과했습니다. 크기를 먼저 줄이세요.');if(remember){f.history.push(f.blob);while(f.history.length>4||f.history.reduce((n,b)=>n+b.size,0)>32*1024**2)f.history.shift();}f.blob=blob;for(const other of S.images){while(other.history.length&&imageMemory()>LIMITS.totalBytes)other.history.shift();}Im.release(S.c);S.c=c;c=null;Im.release(S.pixel);S.pixel=null;const thumb=Im.resize(S.c,96,Math.max(1,Math.round(96*S.c.height/S.c.width)));f.thumb=thumb.toDataURL();Im.release(thumb);}finally{Im.release(c);}}
async function generatePixel(progress=()=>{},signal=S.abort?.signal,options=S.pix){if(!S.c)throw Error('이미지를 먼저 추가하세요.');const base=Im.pixelBase(S.c,options.n,options.fit,options.trim);try{const result=await Im.processPixels(base,'pixel',{colors:options.colors,dither:options.dither,outline:options.outline},progress,signal);check(signal);return result;}finally{Im.release(base);}}
async function updatePixel(progress,signal){const result=await generatePixel(progress,signal);Im.release(S.pixel);S.pixel=result;}
async function loadFiles(list){const files=[...list];if(!files.length||S.busy)return;await task('파일을 여는 중…',async(progress,signal)=>{const kinds=files.map(typeOf);if(kinds.some(k=>!k))throw Error('지원하는 이미지·PDF·영상·오디오 파일을 선택하세요.');const detected=kinds[0];if(S.editor==='pdf'&&kinds.every(k=>k==='pdf'||k==='image')){}else if(detected==='pdf')S.editor='pdf';else if(detected==='media')S.editor='media';else if(!['image','pixel'].includes(S.editor))S.editor='image';
 if(S.editor==='pdf'){if(kinds.some(k=>k==='media'))throw Error('PDF 편집에는 PDF와 이미지만 추가할 수 있어요.');await S.pdf.add(files,progress,signal);check(signal);for(const p of S.pdf.pages.slice(0,10)){if(p.thumb)continue;const c=await S.pdf.render(p,150);p.thumb=c.toDataURL();Im.release(c);check(signal);}message('페이지를 추가했어요. 원본의 전자서명·대화형 양식은 저장 시 유지되지 않습니다.');}
 else if(S.editor==='media'){if(files.length!==1)throw Error('미디어는 한 파일씩 선택하세요.');if(S.media){$('#video').pause();URL.revokeObjectURL(S.media.url);S.media=null;}S.media=await Media.openMedia($('#video'),files[0],signal);S.mediaExport.end=Math.min(10,S.media.duration);S.mediaExport.start=0;}
 else{if(kinds.some(k=>k!=='image'))throw Error('이미지와 다른 종류의 파일은 따로 선택하세요.');if(S.images.length+files.length>LIMITS.files)throw Error('한 작업에는 이미지 24장까지 추가할 수 있어요.');if(imageMemory()+files.reduce((n,f)=>n+f.size,0)>LIMITS.totalBytes)throw Error('이미지는 총 128MB 이하로 선택하세요.');const first=S.images.length;for(const f of files){check(signal);if(f.type==='image/gif'||/\.gif$/i.test(f.name))throw Error('애니메이션 GIF 입력은 아직 지원하지 않습니다. 정지 PNG로 변환해 주세요.');progress(`${f.name} 여는 중…`);const c=await Im.decode(f);try{const t=Im.resize(c,96,Math.max(1,Math.round(96*c.height/c.width)));S.images.push({name:f.name,original:f,blob:f,thumb:t.toDataURL(),history:[]});Im.release(t);}finally{Im.release(c);}}
 S.index=first;Im.release(S.c);S.c=await Im.decode(file().blob);Im.release(S.pixel);S.pixel=null;if(S.editor==='pixel')await updatePixel(progress,signal);}
 });}
function dialog(title,content){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=content;$('#helpDialog').showModal();}
function help(privacy=false){if(privacy){dialog('내 파일은, 내 기기에.',`<p>파일의 편집 처리는 이 브라우저 안에서 수행하며, 선택한 파일을 서버로 업로드하는 코드는 없습니다.</p><p>PDF·HEIC·MP3·AI 기능은 필요한 라이브러리나 모델을 외부 CDN/Hugging Face에서 내려받습니다. 해당 서비스에는 IP 주소 등 일반적인 접속 정보가 전달될 수 있어요. 완전한 무통신·오프라인 서비스는 아닙니다.</p><p>이 버전에는 광고·분석·계정·서버 저장 기능이 없습니다. 새로고침하면 작업을 잃을 수 있으니 결과를 저장하세요.</p><p>이미지 최대 16MP, 총 24장/128MB. PDF 100페이지. 미디어 128MB/10분 입력, 구간 120초, GIF 8초. 브라우저·기기마다 코덱과 성능이 다릅니다.</p><p>PDF 기존 텍스트 직접 수정, OCR, 인증서 서명, 보안 마스킹, AI 디테일 복원 확대는 지원하지 않습니다.</p>`);return;}dialog('필요한 것만, 간단하게.',`<div class="help-grid">${Object.entries(names).map(([k,v])=>`<button data-action="help-editor:${k}">${icon(k)}${v}</button>`).join('')}</div><p>파일을 놓거나 ＋를 누르세요. 이미지 편집 → 도트화로 이동해도 같은 이미지를 이어서 사용할 수 있어요.</p>${checkbox('showLabels','아이콘 옆에 도구 이름 표시',document.body.classList.contains('show-labels'))}<p>마우스를 올리거나 키보드로 선택하면 설명이 나옵니다. 휴대폰에서는 길게 누르거나 이름 표시를 켜세요.</p><p><strong>Ctrl / ⌘ + Z</strong> 되돌리기 · <strong>Esc</strong> 설정 닫기</p>`);}
async function saveImages(progress,signal){const e=S.export,items=e.all?S.images:[file()],entries=[];let missed=0,total=0;for(let i=0;i<items.length;i++){check(signal);const f=items[i];progress(`${i+1} / ${items.length} 이미지 저장 중…`);const c=f===file()?S.c:await Im.decode(f.blob);try{const result=await Im.encode(c,{...e,quality:e.quality/100,allowShrink:e.shrink},()=>check(signal));if(!result.met){missed++;continue;}total+=result.blob.size;if(total>LIMITS.totalBytes)throw Error('결과 합계가 128MB를 넘어요. 나누어 저장하세요.');entries.push({name:`${stem(f.name)}-edited.${e.format==='jpeg'?'jpg':e.format}`,blob:result.blob});}finally{if(c!==S.c)Im.release(c);}}
 check(signal);if(!entries.length)throw Error('목표 용량을 만족하지 못했습니다. 목표를 늘리거나 추가 축소를 허용하세요.');if(entries.length===1&&!e.all)Im.download(entries[0].blob,entries[0].name);else Im.download(await zip(entries),'fileforge-images.zip');message(missed?`${entries.length}장 저장 · 목표 미달 ${missed}장은 제외했습니다.`:`${entries.length}장 저장했어요. ${bytes(entries.reduce((n,e)=>n+e.blob.size,0))}`,missed>0);}
async function pixelPack(progress,signal){if(!S.c)throw Error('이미지를 먼저 추가하세요.');const entries=[];for(const n of[16,32,64,128]){check(signal);progress(`${n} × ${n} 도트 에셋 만드는 중…`);const c=await generatePixel(progress,signal,{...S.pix,n});try{entries.push({name:`${stem(file().name)}-${n}.png`,blob:await Im.blobOf(c)});}finally{Im.release(c);}}check(signal);Im.download(await zip(entries),'fileforge-pixel-pack.zip');message('실제 16·32·64·128px PNG 세트를 저장했어요.');}
async function onAction(action){if(S.busy&&action!=='cancel')return;
 if(action.startsWith('editor:'))return switchEditor(action.split(':')[1]);
 if(action.startsWith('help-editor:')){$('#helpDialog').close();return switchEditor(action.split(':')[1]);}
 if(action==='open')return $('#fileInput').click();if(action==='help')return help();if(action==='privacy')return help(true);if(action==='close-dialog')return $('#helpDialog').close();if(action==='cancel')return S.abort?.abort();if(action==='close-panel'){S.tool='';refresh();return paint();}
 if(action==='export'){S.tool=S.tool==='export'?'':'export';refresh();return paint();}
 if(action.startsWith('tool:')){const next=action.slice(5);S.tool=S.tool===next?'':next;refresh();return paint();}
 if(action==='share'){const paths={image:'image/editor/',pdf:'pdf/editor/',pixel:'pixel/',media:'media/'},url=new URL(paths[S.editor],root);if(S.editor==='pixel')url.searchParams.set('n',S.pix.n);if(S.tool)url.searchParams.set('tool',S.tool);if(S.editor==='image'){url.searchParams.set('format',S.export.format);if(S.export.kb)url.searchParams.set('kb',S.export.kb);}try{await navigator.clipboard.writeText(url.href);message('파일이 아닌 도구·설정 링크를 복사했어요.');}catch{dialog('링크 복사',`<p>선택한 파일은 포함되지 않아요.</p><input style="width:100%" readonly value="${esc(url.href)}">`);}return;}
 if(action==='clear'){if((S.images.length||S.pdf.pages.length||S.media)&&!confirm('저장하지 않은 작업을 비울까요? 원본 파일은 삭제되지 않습니다.'))return;await task('작업실 비우는 중…',async()=>{Im.release(S.c);Im.release(S.pixel);S.c=S.pixel=null;S.images=[];S.index=0;await S.pdf.clear();if(S.media){$('#video').pause();$('#video').removeAttribute('src');$('#video').load();URL.revokeObjectURL(S.media.url);S.media=null;}S.tool='';});return;}
 if(action==='sample'){const c=Im.canvas(720,560),ctx=c.getContext('2d');ctx.fillStyle='#eef3ff';ctx.fillRect(0,0,720,560);ctx.fillStyle='#dbe8fd';ctx.beginPath();ctx.ellipse(360,453,156,24,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff9269';ctx.beginPath();ctx.roundRect(257,271,206,178,[20,20,70,70]);ctx.fill();ctx.fillStyle='#f77857';ctx.fillRect(253,271,214,34);ctx.strokeStyle='#398770';ctx.lineWidth=13;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(360,284);ctx.bezierCurveTo(350,240,385,190,366,135);ctx.stroke();for(const [x,y,a]of[[325,226,-.8],[395,181,.5],[337,150,-.65]]){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillStyle='#56ae85';ctx.beginPath();ctx.ellipse(0,0,49,22,0,0,Math.PI*2);ctx.fill();ctx.restore();}ctx.fillStyle='#dfebfd';ctx.beginPath();ctx.arc(495,119,29,0,Math.PI*2);ctx.fill();const blob=await Im.blobOf(c);Im.release(c);return loadFiles([new File([blob],'little-plant.png',{type:'image/png'})]);}
 if(action.startsWith('select:')){const i=Number(action.split(':')[1]);if(S.editor==='pdf'){S.pdf.selected=i;refresh();return paint();}return task('이미지 여는 중…',async(p,s)=>{for(const f of S.images)if(f!==file())f.history=[];S.index=i;Im.release(S.c);S.c=await Im.decode(file().blob);Im.release(S.pixel);S.pixel=null;if(S.editor==='pixel')await updatePixel(p,s);});}
 if(action==='undo'){if(S.editor==='pdf'){S.pdf.undo();refresh();return paint();}if(!file()?.history.length)return message('되돌릴 편집이 없어요.');return task('되돌리는 중…',async(p,s)=>{const previous=file().history.pop(),c=await Im.decode(previous);await setImage(c,false);if(S.editor==='pixel')await updatePixel(p,s);});}
 if(action.startsWith('crop-preset:')){if(!S.c)return;const v=action.split(':')[1];if(v==='free')S.crop={x:.1,y:.1,w:.8,h:.8};else{const ratio=Number(v);let w=S.c.width*.8,h=w/ratio;if(h>S.c.height*.8){h=S.c.height*.8;w=h*ratio;}S.crop={x:(1-w/S.c.width)/2,y:(1-h/S.c.height)/2,w:w/S.c.width,h:h/S.c.height};}drawCrop();return;}
 if(action==='rotate'||action==='image:flip')return task('이미지 회전 중…',()=>{if(!S.c)throw Error('이미지를 먼저 추가하세요.');return setImage(Im.rotate(S.c,action==='image:flip'));});
 if(action==='image:crop')return task('자르는 중…',async()=>{if(!S.c)throw Error('이미지를 먼저 추가하세요.');await setImage(Im.crop(S.c,S.crop));S.tool='';});
 if(action==='image:resize'){if(!S.c)return message('이미지를 먼저 추가하세요.');const w=integer($('#resizeW').value,1,8192,'너비'),h=integer($('#resizeH').value,1,8192,'높이');return task('크기를 바꾸는 중…',()=>setImage(Im.resize(S.c,w,h)));}
 if(action==='image:upscale'){if(!S.c)return message('이미지를 먼저 추가하세요.');const scale=Number($('#scale').value),nearest=$('#scaleMode').value==='pixel';return task('이미지를 확대하는 중…',()=>setImage(Im.resize(S.c,S.c.width*scale,S.c.height*scale,nearest)));}
 if(action==='image:remove'){if(!S.c)return message('이미지를 먼저 추가하세요.');const hex=$('#removeColor').value,color=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)),tolerance=Number($('#tolerance').value);return task('단색 배경을 분리하는 중…',async(p,s)=>setImage(await Im.processPixels(S.c,'remove',{color,tolerance},p,s)));}
 if(action==='image:portrait'){if(!S.c)return message('이미지를 먼저 추가하세요.');if(S.c.width*S.c.height>4_000_000)return message('AI 인물 제거는 먼저 400만 픽셀 이하로 크기를 줄여 주세요.',true);return task('인물 모델 준비 중…',async(p,s)=>setImage(await Im.processPixels(S.c,'portrait',{},p,s)));}
 if(action==='image:outline'){if(!S.c)return;return task('외곽선을 만드는 중…',async(p,s)=>setImage(await Im.processPixels(S.c,'outline',{radius:1},p,s)));}
 if(action==='image:trim'){if(!S.c)return;return task('여백을 정리하는 중…',()=>setImage(Im.trim(S.c)));}
 if(action==='image:fill'){if(!S.c)return;const color=$('#fillColor').value;return task('배경색 적용 중…',()=>setImage(Im.background(S.c,color)));}
 if(action==='image:reset'){if(!file())return;return task('원본을 여는 중…',async()=>setImage(await Im.decode(file().original)));}
 if(action==='image:save'){readExport();return task('저장 파일을 만드는 중…',saveImages);}
 if(action==='image:to-pdf'){if(!S.c)return;return task('PDF 페이지를 만드는 중…',async(p,s)=>{const blob=await Im.blobOf(S.c);await S.pdf.add([new File([blob],`${stem(file().name)}.png`,{type:'image/png'})],p,s);S.editor='pdf';S.tool='';});}
 if(action.startsWith('size:')){S.pix.n=Number(action.split(':')[1]);if(!S.c){refresh();return;}return task('도트화하는 중…',updatePixel);}
 if(action==='pixel:apply'){S.pix={n:integer($('#pixelN').value,8,512,'N'),colors:Number($('#pixelColors').value),dither:Number($('#pixelDither').value),fit:$('#pixelFit').value,trim:$('#pixelTrim').checked,outline:Number($('#pixelOutline').value)};return task('도트화하는 중…',updatePixel);}
 if(action==='pixel:pack')return task('도트 세트를 만드는 중…',pixelPack);
 if(action==='pixel:save'){const scale=Number($('#pixelScale')?.value||1);return task('도트 에셋 저장 중…',async(p,s)=>{if(!S.pixel)await updatePixel(p,s);const c=Im.resize(S.pixel,S.pixel.width*scale,S.pixel.height*scale,true);try{Im.download(await Im.blobOf(c),`${stem(file().name)}-${S.pix.n}px-${scale}x.png`);}finally{Im.release(c);}});}
 if(action==='pixel:to-image')return task('이미지 편집기로 보내는 중…',async(p,s)=>{if(!S.pixel)await updatePixel(p,s);const c=Im.copy(S.pixel);await setImage(c);S.editor='image';S.tool='';});
 if(action==='pdf:current'){S.pdfExport.range=String(S.pdf.selected+1);$('#pdfRange').value=S.pdfExport.range;return;}
 if(action==='pdf:overlay'){if(!S.pdf.current())return message('PDF 파일을 먼저 추가하세요.');return $('#overlayInput').click();}
 if(action==='pdf:save'){S.pdfExport={range:$('#pdfRange').value,format:$('#pdfFormat').value,raster:$('#rasterPdf').checked};return task('PDF 저장 준비 중…',async(p,s)=>{const e=S.pdfExport;if(e.format==='pdf'){const blob=await S.pdf.export(e,p,s);check(s);Im.download(blob,'fileforge-edited.pdf');message(`PDF를 저장했어요. ${bytes(blob.size)}${e.raster?' · 페이지를 이미지로 변환한 사본':''}`);}else{const entries=await S.pdf.imageExports(e,p,s);check(s);if(entries.length===1)Im.download(entries[0].blob,entries[0].name);else Im.download(await zip(entries),'fileforge-pages.zip');}});}
 if(action.startsWith('pdf:')){if(!S.pdf.current())return;const cmd=action.split(':')[1];if(cmd==='left')S.pdf.move(-1);if(cmd==='right')S.pdf.move(1);if(['rotate','remove','duplicate'].includes(cmd))S.pdf[cmd]();if(cmd==='clear-marks'){S.pdf.snapshot();S.pdf.current().marks=[];}for(const p of S.pdf.pages)p.thumb=null;refresh();return paint();}
 if(action==='media:audio'||action==='media:gif'){S.mediaExport.format=action==='media:audio'?'mp3':'gif';if(action==='media:gif'&&S.media)S.mediaExport.end=Math.min(S.mediaExport.start+4,S.media.duration);S.tool='export';refresh();return;}
 if(action==='media:set-start'){if(!S.media)return;S.mediaExport.start=Number($('#video').currentTime.toFixed(1));S.mediaExport.end=Math.min(S.media.duration,S.mediaExport.start+5);renderPanel();return;}
 if(action==='media:frame')return task('장면을 저장하는 중…',async(p,s)=>{if(!S.media)throw Error('영상을 먼저 추가하세요.');const c=await Media.frame($('#video'),$('#video').currentTime,s);try{Im.download(await Im.blobOf(c),`${stem(S.media.file.name)}-frame.png`);}finally{Im.release(c);}});
 if(action==='media:save'){S.mediaExport={start:Number($('#mediaStart').value),end:Number($('#mediaEnd').value),format:$('#mediaFormat').value,width:Number($('#mediaWidth').value)};return task('미디어를 저장하는 중…',async(p,s)=>{if(!S.media)throw Error('미디어 파일을 먼저 추가하세요.');const e=S.mediaExport,blob=e.format==='gif'?await Media.exportGif($('#video'),S.media,e.start,e.end,p,s):['mp3','wav'].includes(e.format)?await Media.exportAudio(S.media,e.start,e.end,e.format,p,s):await Media.exportVideo($('#video'),S.media,e.start,e.end,e.width,p,s);check(s);Im.download(blob,`${stem(S.media.file.name)}-clip.${e.format}`);message(`${bytes(blob.size)} 저장했어요.`);});}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)onAction(b.dataset.action).catch(err=>message(err.message,true));});
$('#fileInput').addEventListener('change',async e=>{const files=[...e.target.files];e.target.value='';await loadFiles(files);});
$('#overlayInput').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f||!S.pdf.current())return;await task('이미지 표시를 추가하는 중…',async()=>{const image=await Im.decode(f),p=S.pdf.current(),w=Math.min(.5,.5*p.logicalH/p.logicalW*image.width/image.height),h=w*p.logicalW/p.logicalH*image.height/image.width;S.pdf.mark({type:'image',image,x:.15,y:.15,w,h});p.thumb=null;});});
$('#panel').addEventListener('input',e=>{if(S.editor==='image'&&S.tool==='resize'&&$('#ratioLock')?.checked&&S.c){if(e.target.id==='resizeW')$('#resizeH').value=Math.max(1,Math.round(Number(e.target.value)*S.c.height/S.c.width));if(e.target.id==='resizeH')$('#resizeW').value=Math.max(1,Math.round(Number(e.target.value)*S.c.width/S.c.height));}});
$('#helpDialog').addEventListener('change',e=>{if(e.target.id==='showLabels')document.body.classList.toggle('show-labels',e.target.checked);});
let dragDepth=0;document.addEventListener('dragenter',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();dragDepth++;if(!S.busy)$('#dropOverlay').hidden=false;}});document.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files'))e.preventDefault();});document.addEventListener('dragleave',()=>{dragDepth--;if(dragDepth<=0)$('#dropOverlay').hidden=true;});document.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();dragDepth=0;$('#dropOverlay').hidden=true;loadFiles(e.dataTransfer.files);}});
$('#fileStrip').addEventListener('dragstart',e=>{const el=e.target.closest('[data-index]');if(el&&S.editor==='pdf')e.dataTransfer.setData('application/x-fileforge-page',el.dataset.index);});$('#fileStrip').addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('application/x-fileforge-page'))e.preventDefault();});$('#fileStrip').addEventListener('drop',e=>{const i=e.dataTransfer.getData('application/x-fileforge-page'),target=e.target.closest('[data-index]');if(i!==''&&target&&S.editor==='pdf'&&!S.busy){e.preventDefault();e.stopPropagation();S.pdf.reorder(Number(i),Number(target.dataset.index));refresh();paint().catch(err=>message(err.message,true));}});
function point(e){const r=$('#preview').getBoundingClientRect();return [clamp((e.clientX-r.left)/r.width,0,1),clamp((e.clientY-r.top)/r.height,0,1)];}
$('#canvasWrap').addEventListener('pointerdown',e=>{if(S.busy||!ready())return;const [x,y]=point(e),view=$('#preview'),ctx=view.getContext('2d');if(S.editor==='image'&&S.tool==='crop'){e.preventDefault();$('#canvasWrap').setPointerCapture(e.pointerId);S.pointer={mode:'crop',x,y};S.crop={x,y,w:0,h:0};drawCrop();return;}
 if(S.editor!=='pdf')return;const p=S.pdf.current(),[bx,by]=inversePoint(x,y,p.angle);if(S.tool==='text'){const text=$('#markText').value;if(!text.trim())return message('추가할 글자를 먼저 입력하세요.');S.pdf.mark({type:'text',text:text.slice(0,2000),x:bx,y:by,size:Number($('#markSize').value)||20,color:$('#markColor').value});p.thumb=null;paint().catch(err=>message(err.message,true));return;}
 if(S.tool==='pen'){e.preventDefault();$('#canvasWrap').setPointerCapture(e.pointerId);S.pointer={mode:'pen',type:$('#penMode').value,screen:[[x,y]],points:[[bx,by]],size:Number($('#markSize').value)||3,color:$('#markColor').value,base:ctx.getImageData(0,0,view.width,view.height)};return;}
 if(!S.tool){for(let i=p.marks.length-1;i>=0;i--){const m=p.marks[i];if(m.type==='pen')continue;const w=m.w||(m.text?.split('\n').reduce((a,t)=>Math.max(a,t.length),0)||1)*(m.size||20)*.7/p.logicalW,h=m.h||(m.text?.split('\n').length||1)*(m.size||20)*1.35/p.logicalH;if(bx>=m.x&&bx<=m.x+w&&by>=m.y&&by<=m.y+h){S.pdf.snapshot();$('#canvasWrap').setPointerCapture(e.pointerId);S.pointer={mode:'move',mark:m,ox:m.x,oy:m.y,x:bx,y:by,nx:m.x,ny:m.y};break;}}}
});
$('#canvasWrap').addEventListener('pointermove',e=>{const d=S.pointer;if(!d)return;const [x,y]=point(e);if(d.mode==='crop'){S.crop={x:Math.min(x,d.x),y:Math.min(y,d.y),w:Math.abs(x-d.x),h:Math.abs(y-d.y)};drawCrop();return;}const p=S.pdf.current(),[bx,by]=inversePoint(x,y,p.angle);if(d.mode==='move'){d.nx=clamp(d.ox+bx-d.x,0,.98);d.ny=clamp(d.oy+by-d.y,0,.98);return;}d.points.push([bx,by]);d.screen.push([x,y]);const v=$('#preview'),ctx=v.getContext('2d');ctx.putImageData(d.base,0,0);ctx.save();ctx.strokeStyle=d.color;ctx.fillStyle=d.color;ctx.lineWidth=Math.max(1,d.size*v.width/p.logicalW);ctx.lineCap='round';ctx.lineJoin='round';if(d.type==='pen'){ctx.beginPath();d.screen.forEach(([x,y],i)=>i?ctx.lineTo(x*v.width,y*v.height):ctx.moveTo(x*v.width,y*v.height));ctx.stroke();}else{const [sx,sy]=d.screen[0];if(d.type==='highlight'){ctx.globalAlpha=.3;ctx.fillRect(sx*v.width,sy*v.height,(x-sx)*v.width,(y-sy)*v.height);}else ctx.strokeRect(sx*v.width,sy*v.height,(x-sx)*v.width,(y-sy)*v.height);}ctx.restore();});
function endPointer(){const d=S.pointer;if(!d)return;S.pointer=null;if(d.mode==='crop'){if(S.crop.w<.01||S.crop.h<.01)S.crop={x:.1,y:.1,w:.8,h:.8};drawCrop();return;}if(d.mode==='move'){d.mark.x=d.nx;d.mark.y=d.ny;}else if(d.points.length>1){const xs=d.points.map(p=>p[0]),ys=d.points.map(p=>p[1]);S.pdf.mark({type:d.type,points:d.points,x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys),color:d.color,size:d.size});}S.pdf.current().thumb=null;paint().catch(err=>message(err.message,true));}
$('#canvasWrap').addEventListener('pointerup',endPointer);$('#canvasWrap').addEventListener('pointercancel',endPointer);
document.addEventListener('keydown',e=>{if(S.busy)return;if(e.key==='Escape'){S.tool='';S.pointer=null;refresh();paint().catch(()=>{});}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();onAction('undo').catch(err=>message(err.message,true));}});
window.addEventListener('popstate',()=>{if(S.busy){message('진행 중인 작업을 먼저 취소하세요.');return;}const r=route(location.pathname,location.search);S.editor=r.editor;S.tool=r.tool;S.pix.n=r.n;S.export.format=r.format;S.export.kb=r.kb;refresh();paint().catch(err=>message(err.message,true));});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>paint().catch(()=>{}),100);});
window.addEventListener('beforeunload',e=>{if(S.busy){e.preventDefault();e.returnValue='';}});
$('#helpButton').innerHTML=icon('help');initTooltips();refresh();paint().catch(err=>message(err.message,true));
