import {capabilitySummary} from './capabilities.js';
import {capabilityGuide} from './capability-copy.js';
import {brandCopy} from './brand.js';
import {exampleHTML} from './examples.js';
import {TOOLS} from './tool-registry.js';
import {INTENTS} from './intents.js';
import {LANDINGS,LANDING_PATHS,landingText} from './landings.js';
import {t} from './i18n.js';
import {esc} from './ui.js';

export const labels=brandCopy({
 en:{related:'Related tools',how:'How it works',formats:'Supported formats',features:'What this tool does',limits:'Before you export',faq:'Frequently asked questions',about:'About',privacy:'Privacy',terms:'Terms',contact:'Contact',home:'Open {brand}',ad:'Advertisement',language:'Language',saved:'Keep your original file. Export your result before reloading or closing this tab.',uploadQ:'Are my files uploaded?',uploadA:'{brand} processes selected files on your device and has no file-upload API. Optional engines and models are downloaded from third parties; those requests expose connection information such as your IP address.',resultQ:'Will my work be saved automatically?',resultA:'No. Images and editing state stay in this tab; media output can use local temporary storage. Changing language preserves your work; reloading, closing the tab, or following a link to another page can clear it.'},
 ko:{related:'관련 도구',how:'사용 방법',formats:'지원 형식',features:'이 도구로 할 수 있는 일',limits:'저장 전에 확인하세요',faq:'자주 묻는 질문',about:'소개',privacy:'개인정보처리방침',terms:'이용약관',contact:'문의',home:'{brand} 열기',ad:'광고',language:'언어',saved:'원본 파일은 따로 보관하고, 새로고침하거나 탭을 닫기 전에 결과를 저장하세요.',uploadQ:'파일이 서버에 업로드되나요?',uploadA:'선택한 파일은 사용자 기기에서 처리하며, {brand}에는 파일 업로드 API가 없습니다. 일부 엔진과 모델은 외부에서 내려받으므로 IP 주소 등 연결 정보가 해당 서비스에 전달됩니다.',resultQ:'작업이 자동 저장되나요?',resultA:'아니요. 이미지와 편집 상태는 이 탭에 있고 미디어 결과는 기기 내 임시 저장소를 사용할 수 있습니다. 언어를 바꿔도 작업은 유지되지만 새로고침, 탭 닫기, 다른 페이지로 이동하면 사라질 수 있습니다.'},
 ja:{related:'関連ツール',how:'使い方',formats:'対応形式',features:'このツールでできること',limits:'書き出す前に',faq:'よくある質問',about:'{brand}について',privacy:'プライバシー',terms:'利用規約',contact:'お問い合わせ',home:'{brand}を開く',ad:'広告',language:'言語',saved:'元のファイルは保管し、再読み込みやタブを閉じる前に結果を書き出してください。',uploadQ:'ファイルはアップロードされますか？',uploadA:'選択したファイルはお使いの端末で処理します。{brand}にファイル送信用APIはありません。一部のエンジンやモデルは外部から取得するため、IPアドレスなどの接続情報は配信元に伝わります。',resultQ:'作業は自動保存されますか？',resultA:'いいえ。画像と編集状態はこのタブに保持され、メディア出力は端末の一時保存を利用する場合があります。言語を変えても作業は残りますが、再読み込み、タブを閉じる操作、別のページへの移動で失われることがあります。'}
});

// Each tuple is [steps separated by |, feature, limitation, specific question, answer].
// Copy describes the actual Canvas / PDF / MediaRecorder implementations.
export const guides={
 home:[
 ['Choose Image, PDF, Pixelize or Media|Open a file or try the image sample|Edit, check the preview and export','Four editors share one simple workspace without an account.','Optional PDF, HEIC, MP3 and portrait tools need an internet connection.','Which tool should I start with?','Use Image for photos, PDF for pages, Pixelize for small PNG assets and Media for short clips.'],
 ['이미지·PDF·도트화·미디어 중 도구 선택|파일을 열거나 이미지 샘플로 시작|편집 후 미리보기를 확인하고 저장','계정 없이 네 가지 편집기를 한 작업실에서 사용합니다.','PDF·HEIC·MP3·인물 제거는 외부 엔진이나 모델 다운로드가 필요합니다.','어떤 도구를 고르면 되나요?','사진은 이미지, 문서는 PDF, 작은 PNG 에셋은 도트화, 짧은 영상은 미디어 편집기로 시작하세요.'],
 ['画像・PDF・ピクセル化・メディアを選ぶ|ファイルを開くか画像サンプルを試す|プレビューを確認して書き出す','アカウントなしで使える、4つの編集ツールです。','PDF・HEIC・MP3・人物切り抜きには外部データの取得が必要です。','どのツールから始めればよいですか？','写真は画像、文書はPDF、小さなPNG素材はピクセル化、短い動画はメディアを選んでください。']],
 image:[
 ['Open an image|Choose crop, resize, rotate or background tools|Select an export format and save','Combine several edits before exporting a new copy.','Images are limited to 32 MB each; dimensions cannot exceed 8192 per side or 16 million pixels.','Does editing overwrite my original?','No. Export creates a new file. Keep the original for future edits.'],
 ['이미지 열기|자르기·크기·회전·배경 도구 선택|저장 형식을 정하고 내보내기','여러 편집을 이어서 적용한 뒤 새 파일로 저장합니다.','이미지당 32MB, 한 변 8192px, 총 1,600만 픽셀 이하를 지원합니다.','원본 파일이 덮어써지나요?','아니요. 새 파일로 내보냅니다. 이후 편집을 위해 원본을 보관하세요.'],
 ['画像を開く|切り抜き・サイズ・回転・背景のツールを選ぶ|保存形式を選んで書き出す','複数の編集を組み合わせ、新しいファイルとして保存できます。','画像は1枚32MB、各辺8192px、合計1600万画素までです。','元のファイルは上書きされますか？','いいえ。別のファイルとして書き出します。再編集に備えて元画像も保管してください。']],
 upscale:[
 ['Open a small image|Choose 2× or 4× and smooth or pixel scaling|Enlarge, compare with the original and download','Canvas resampling increases the pixel dimensions; pixel mode keeps hard edges.','This is not AI restoration. It cannot reconstruct missing detail; output is capped at 16 million pixels.','Will a blurry face become sharp?','Not reliably. Enlargement adds pixels, not recovered detail. Compare the preview before downloading.'],
 ['작은 이미지 열기|2배·4배와 부드럽게·픽셀 유지 방식 선택|확대 후 원본과 비교하고 다운로드','Canvas 리샘플링으로 크기를 늘리며, 픽셀 유지 방식은 경계를 또렷하게 확대합니다.','AI 복원이 아니며 사라진 디테일을 되살리지 않습니다. 출력은 1,600만 픽셀 이하입니다.','흐릿한 얼굴도 선명해지나요?','보장할 수 없습니다. 픽셀 수를 늘리는 기능이므로 원본과 결과를 비교하세요.'],
 ['小さな画像を開く|2倍・4倍と補間方法を選ぶ|拡大して元画像と比較し、ダウンロード','Canvasで画素数を増やします。ピクセルモードは輪郭をくっきり保ちます。','AI復元ではなく、失われた細部は復元できません。出力は1600万画素までです。','ぼやけた顔も鮮明になりますか？','保証できません。画素数を増やす機能なので、元画像と比較して判断してください。']],
 'remove-bg':[
 ['Open an image|Choose solid background or experimental portrait mode|Adjust tolerance if needed, preview and save PNG','Solid mode removes matching color regions connected to the image border. Portrait mode runs a downloaded model locally.','Portrait mode targets people, not arbitrary objects, and accepts at most 4 million pixels. Hair and transparent objects may need another editor.','Why does white inside the subject remain?','Solid mode follows connected regions from the border, helping preserve enclosed areas. Similar-colored subject edges can still be removed.'],
 ['이미지 열기|단색 배경 또는 실험적 인물 모드 선택|필요하면 허용 오차를 조정하고 PNG 저장','단색 모드는 가장자리와 연결된 유사 색상을 지웁니다. 인물 모드는 모델을 내려받아 기기에서 실행합니다.','인물 모드는 일반 물체용이 아니며 400만 픽셀 이하입니다. 머리카락·반투명 물체는 추가 보정이 필요할 수 있습니다.','피사체 안의 흰색이 남는 이유는 무엇인가요?','가장자리에서 연결된 영역만 따라 지워 내부를 보호합니다. 다만 피사체 가장자리 색이 배경과 비슷하면 함께 지워질 수 있습니다.'],
 ['画像を開く|単色背景または実験的な人物モードを選ぶ|必要に応じて許容差を調整しPNGで保存','単色モードは画像の端につながる近い色を消します。人物モードはモデルを取得し端末で実行します。','人物モードは一般物体向けではなく、400万画素までです。髪や半透明部分は追加の修正が必要な場合があります。','被写体の中の白色が残るのはなぜですか？','端からつながる領域だけを消すためです。ただし背景に近い色の輪郭は一緒に消えることがあります。']],
 compress:[
 ['Open an image|Choose a target size and JPG or WebP; adjust export settings if needed|Compress, inspect the measured size and download','A bounded quality search attempts to meet your selected size. Optional shrinking can reduce dimensions.','Not every target is reachable. PNG ignores lossy quality settings; already compressed files may become larger.','Why can I not reach 200 KB?','Try WebP or JPG, reduce dimensions, or allow shrinking. Check small text and edges for quality loss.'],
 ['이미지 열기|목표 용량과 JPG·WebP를 고르고 저장 설정 확인|압축 후 실제 크기를 확인하고 다운로드','품질을 단계적으로 조정해 목표 용량을 시도하며, 선택하면 해상도도 줄입니다.','모든 목표를 달성할 수는 없습니다. PNG에는 손실 품질 조절이 적용되지 않고 결과가 더 커질 수도 있습니다.','200KB까지 줄어들지 않는 이유는 무엇인가요?','WebP·JPG로 바꾸거나 해상도를 낮추고 크기 축소를 허용해 보세요. 작은 글자와 경계의 손상도 확인하세요.'],
 ['画像を開く|目標容量とJPG・WebPを選び、保存設定を確認|圧縮後の実際の容量を確認して保存','品質を段階的に調整して目標容量を試します。任意で画像サイズも縮小できます。','すべての目標に届くわけではありません。PNGには非可逆圧縮の品質設定が効かず、容量が増える場合もあります。','200KBまで小さくならないのはなぜですか？','WebP・JPGへの変更やサイズ縮小を試してください。細かい文字や輪郭の劣化も確認しましょう。']],
 convert:[
 ['Open an image|Select PNG, JPG or WebP|Convert and download the new file','Re-encodes the image into the selected format rather than renaming its extension.','JPG has no transparency. Canvas export does not promise preservation of metadata, color profiles or animation.','Which format keeps a transparent background?','Choose PNG or WebP. JPG flattens transparency onto the selected background color.'],
 ['이미지 열기|PNG·JPG·WebP 중 선택|변환 후 새 파일 다운로드','확장자만 바꾸지 않고 선택한 형식으로 다시 인코딩합니다.','JPG는 투명도를 지원하지 않습니다. 메타데이터·색상 프로필·애니메이션 보존도 보장하지 않습니다.','투명 배경을 유지하려면 어떤 형식이 좋나요?','PNG 또는 WebP를 선택하세요. JPG는 선택한 배경색으로 투명 영역을 채웁니다.'],
 ['画像を開く|PNG・JPG・WebPから選ぶ|変換したファイルを保存','拡張子を変えるだけでなく、選んだ形式で再エンコードします。','JPGは透過非対応です。メタデータ・カラープロファイル・アニメーションの保持は保証しません。','透明な背景を残すには？','PNGまたはWebPを選んでください。JPGでは透明部分が指定した背景色になります。']],
 heic:[
 ['Open a single-photo HEIC or HEIF file|Keep JPG selected or choose another output|Convert and download','Uses browser decoding when available, otherwise downloads the HEIC decoder.','Multi-image HEIC files are not supported. HDR appearance and metadata may change.','Does HEIC conversion need the internet?','It may need a first-time decoder download from jsDelivr. The photo is decoded on your device.'],
 ['사진 한 장이 담긴 HEIC·HEIF 열기|JPG 기본값을 쓰거나 다른 형식 선택|변환 후 다운로드','브라우저 디코딩을 먼저 시도하고 필요하면 HEIC 디코더를 내려받습니다.','여러 사진이 담긴 HEIC는 지원하지 않습니다. HDR 표현과 메타데이터가 달라질 수 있습니다.','HEIC 변환에 인터넷이 필요한가요?','jsDelivr에서 디코더를 처음 내려받아야 할 수 있습니다. 사진 디코딩은 기기에서 진행합니다.'],
 ['写真1枚のHEIC・HEIFを開く|JPGのまま、または別の形式を選ぶ|変換して保存','ブラウザで読めない場合はHEICデコーダーを取得します。','複数画像入りHEICは非対応です。HDRの見え方やメタデータが変わる場合があります。','ネット接続は必要ですか？','初回にjsDelivrからデコーダーを取得する場合があります。写真の処理は端末内で行います。']],
 crop:[
 ['Drop an image|The crop box is already placed: drag it, or pick an aspect ratio or platform size|Check the result size and download','Frames an exact pixel rectangle, with 90° turns, mirroring, straightening, a circle or rounded shape and an optional exact output size.','Cropping reduces dimensions and cannot reveal content outside the original image. Straightening and scaling to an exact size resample the picture.','Can I crop several images the same way?','Yes. Drop them all and use "Apply this crop to all"; every file keeps its own box and they can be saved together as a ZIP.'],
 ['이미지 놓기|이미 놓인 영역을 끌어 옮기거나 비율·플랫폼 규격 선택|결과 크기를 확인하고 다운로드','픽셀 단위로 정확한 영역을 잘라내고, 90° 회전·반전·수평 맞추기·원형·둥근 모서리·정확한 출력 크기도 함께 지정합니다.','자른 만큼 해상도가 줄어듭니다. 원본 바깥의 내용을 만들지는 못하며, 수평 맞추기와 정확한 크기 조정은 픽셀을 다시 계산합니다.','여러 장을 같은 영역으로 자를 수 있나요?','네. 여러 장을 놓고 "이 영역을 모든 파일에 적용"을 누르면 됩니다. 파일별 영역은 따로 기억되고 ZIP으로 한 번에 받을 수 있습니다.'],
 ['画像をドロップ|すでに置かれた範囲をドラッグ、または比率・各サービスの規格を選ぶ|出力サイズを確認して保存','ピクセル単位で正確な範囲を切り抜き、90°回転・反転・水平調整・円形・角丸・正確な出力サイズも指定できます。','切り抜いた分だけ画像サイズが小さくなります。元画像の外側は生成できず、水平調整と正確なサイズ指定では画素を再計算します。','複数の画像を同じ範囲で切り抜けますか？','はい。まとめてドロップし「この範囲をすべてのファイルに適用」を押します。ファイルごとの範囲は個別に保持され、ZIPで一括保存できます。']],
 resize:[
 ['Open an image|Enter width and height; keep aspect ratio when appropriate|Resize, check dimensions and download','Sets exact output dimensions for thumbnails and size-constrained forms.','Changing the aspect ratio can stretch the picture. Maximum output is 8192 per side and 16 million pixels.','Why does the height change when I type a width?','The aspect-ratio lock keeps the proportions of the source image. Turn it off only for deliberate stretching.'],
 ['이미지 열기|너비·높이를 입력하고 필요하면 비율 유지|크기를 바꾼 뒤 치수를 확인하고 저장','썸네일이나 제출 양식에 맞는 출력 치수를 지정합니다.','비율을 바꾸면 이미지가 늘어날 수 있습니다. 한 변 8192px, 총 1,600만 픽셀까지입니다.','너비를 바꾸면 높이도 바뀌는 이유는 무엇인가요?','비율 잠금이 원본 비율을 유지하기 때문입니다. 의도적으로 늘릴 때만 해제하세요.'],
 ['画像を開く|幅と高さを入力し、必要に応じて比率を固定|変更後の寸法を確認して保存','サムネイルや提出フォーム向けに出力寸法を指定できます。','比率を変えると画像が伸びます。各辺8192px、合計1600万画素までです。','幅を入力すると高さも変わるのはなぜですか？','縦横比の固定が元画像の比率を保つためです。意図的に変形するときだけ解除してください。']],
 pixel:[
 ['Open an image|Choose a grid size, palette and dithering|Generate and download the native PNG','Produces a real N×N asset, with optional transparent trim and outline.','Small grids discard detail. This is an automatic pixel conversion, not hand-drawn pixel art.','Is the large preview the downloaded resolution?','No. The preview is enlarged with sharp pixels; the native asset uses the selected 8–512 grid size.'],
 ['이미지 열기|격자 크기·팔레트·디더링 선택|생성 후 원본 크기 PNG 다운로드','실제 N×N 에셋을 만들고 투명 여백 정리와 외곽선을 선택할 수 있습니다.','작은 격자는 세부 정보를 잃습니다. 손으로 그린 도트가 아닌 자동 변환입니다.','큰 미리보기 크기로 저장되나요?','아니요. 미리보기만 또렷하게 확대하며 실제 에셋은 선택한 8~512 격자 크기입니다.'],
 ['画像を開く|グリッド・色数・ディザを選ぶ|生成して実寸のPNGを保存','実際のN×N素材を作り、透明余白の整理や輪郭線を追加できます。','小さなグリッドでは細部が失われます。手描きではなく自動変換です。','大きなプレビューと同じ解像度で保存されますか？','いいえ。表示だけをくっきり拡大しています。実寸は選んだ8〜512のグリッドです。']],
 pdf:[
 ['Add PDF files or images|Arrange pages and add text, drawings or image overlays|Choose pages and export PDF','Page-level editing and visual annotations share one workspace.','No existing-text editing, OCR, secure redaction or certificate signing. Forms are flattened and signatures are not preserved.','Can I hide confidential text with a rectangle?','No. An overlay is not secure redaction; underlying text may remain in the PDF. Use a dedicated redaction tool.'],
 ['PDF 또는 이미지 추가|페이지 정리 후 글자·그림·이미지 덧붙이기|페이지 범위를 골라 PDF 저장','페이지 편집과 시각적 주석을 한곳에서 작업합니다.','기존 본문 수정·OCR·보안 마스킹·인증서 서명은 지원하지 않습니다. 양식은 평면화되고 서명은 보존되지 않습니다.','사각형으로 개인정보를 가려도 되나요?','아니요. 덧붙인 도형 아래 원문이 남을 수 있습니다. 보안 삭제 전용 도구를 사용하세요.'],
 ['PDFまたは画像を追加|ページを整理して文字・図・画像を重ねる|ページ範囲を選びPDFで保存','ページ編集と見た目の注釈を一つの作業画面で行えます。','既存本文の編集・OCR・安全な墨消し・証明書署名は非対応です。フォームは平面化し、署名は保持しません。','四角形で機密情報を隠せますか？','安全な墨消しにはなりません。下の原文が残る場合があるため、専用ツールを使ってください。']],
 'pdf-merge':[
 ['Add the PDFs to combine|Check and reorder the page thumbnails|Export all pages as one PDF', 'Combines pages from several documents in the order shown.', 'No fixed page or file-size cap; capacity depends on device memory (a 320-page document is tested). Form fields become static; signatures are not preserved.', 'Can I change the order after adding files?', 'Yes. Move pages with the controls or drag thumbnails, then check the order before exporting.'],
 ['합칠 PDF 추가|페이지 썸네일을 확인하고 순서 정리|전체 페이지를 하나의 PDF로 저장', '여러 문서의 페이지를 화면에 보이는 순서대로 합칩니다.', '페이지 수·파일 크기에 고정 상한은 없고 기기 메모리에 따릅니다(320페이지 문서로 검증). 양식은 정적 표시로 바뀌고 서명은 보존되지 않습니다.', '추가 후 순서를 바꿀 수 있나요?', '네. 페이지 이동 버튼이나 썸네일 드래그로 정리한 뒤 저장 전에 순서를 확인하세요.'],
 ['結合するPDFを追加|サムネイルでページ順を確認・変更|全ページを一つのPDFとして保存', '複数文書のページを画面の順にまとめます。', 'ページ数・ファイルサイズに固定の上限はなく、端末メモリに依存します（320ページの文書で検証）。フォームは静的な表示となり署名は保持しません。', '追加した後に順番を変えられますか？', 'はい。移動ボタンやサムネイルのドラッグで並べ替え、保存前に確認してください。']],
 'pdf-split':[
 ['Open a PDF|Enter page numbers such as 1,3-5|Export the selection as a new PDF','Extracts a selected set of pages into one new document.','This does not automatically create one file per page. The original remains unchanged.','How do I make two separate PDFs?','Export one range, then change the range and export again. Page numbers refer to the current arranged document.'],
 ['PDF 열기|1,3-5처럼 페이지 범위 입력|선택한 페이지를 새 PDF로 저장','원하는 페이지 묶음을 하나의 문서로 추출합니다.','페이지마다 개별 파일을 자동 생성하지 않습니다. 원본은 바뀌지 않습니다.','PDF 두 개로 나누려면 어떻게 하나요?','첫 범위를 저장한 뒤 범위를 바꿔 다시 저장하세요. 번호는 현재 정리된 문서 기준입니다.'],
 ['PDFを開く|1,3-5のようにページ範囲を入力|選択ページを新しいPDFで保存','必要なページの組み合わせを一つの文書に取り出します。','1ページずつ自動で別ファイルにはしません。元ファイルは変更しません。','二つのPDFに分けるには？','一つ目の範囲を保存し、範囲を変えてもう一度保存します。番号は現在の並び順に対応します。']],
 'pdf-compress':[
 ['Drop a PDF|Pick Light, Recommended or Strong|Compare the result and download','Resamples each image to the resolution the page actually shows it at, trims embedded fonts to the characters in use and merges identical objects, all while text and search stay intact.','Files that are already optimised barely shrink, and the original is returned whenever the result would be larger. Grayscale and the raster mode are irreversible; raster output loses selectable text.','Does the text survive compression?','Yes. Only the images are re-encoded and the fonts are reduced to the glyphs the document draws, unless you switch on the raster mode, which is labelled as removing text.'],
 ['PDF 놓기|약하게·권장·강하게 중 선택|결과를 비교하고 저장','사진은 페이지에 실제로 보이는 크기에 맞춰 다시 압축하고, 글꼴은 쓰이는 글자만 남기고, 똑같은 객체는 하나로 합칩니다. 글자와 검색은 그대로입니다.','이미 최적화된 파일은 거의 줄지 않고, 결과가 더 커지면 원본을 그대로 돌려줍니다. 흑백 변환과 이미지화는 되돌릴 수 없고, 이미지화는 글자 선택을 잃습니다.','압축해도 글자가 남나요?','남습니다. 사진만 다시 압축하고 글꼴은 문서가 쓰는 글자만 남깁니다. 글자를 잃는 이미지화 모드는 따로 표시해 두었습니다.'],
 ['PDFをドロップ|弱め・おすすめ・強めを選ぶ|結果を比べて保存','写真はページに実際に表示される大きさに合わせて再圧縮し、フォントは使う文字だけを残し、同じ内容の重複は1つにまとめます。文字と検索はそのままです。','すでに最適化されたファイルはほとんど縮まず、結果が大きくなる場合は元のファイルを返します。モノクロ化と画像化は元に戻せず、画像化は文字選択を失います。','圧縮しても文字は残りますか？','残ります。写真だけを再圧縮し、フォントは文書が使う文字だけを残します。文字を失う画像化モードは別に明記しています。']],
 'pdf-protect':[
 ['Drop the PDFs|Type the password twice|Protect and download','Writes a real AES-256 (revision 6) open password, and lets printing, copying and editing be allowed or refused separately under Advanced.','Nothing is stored or sent anywhere, so a forgotten password cannot be recovered. Existing digital signatures are not carried over, and the protected file is slightly larger.','Can a forgotten password be recovered?','No. The password only ever exists in this browser tab, so the copy you remember is the only one.'],
 ['PDF 놓기|암호를 두 번 입력|암호를 걸고 저장','실제 AES-256(리비전 6) 열기 암호를 걸고, 인쇄·복사·편집 허용을 고급 설정에서 따로 정할 수 있습니다.','암호는 어디에도 저장·전송되지 않으므로 잊으면 복구할 수 없습니다. 기존 전자서명은 유지되지 않고, 결과 파일은 조금 커집니다.','잊어버린 암호를 찾을 수 있나요?','찾을 수 없습니다. 암호는 이 브라우저 탭 안에서만 존재하므로 기억하는 것이 유일한 사본입니다.'],
 ['PDFをドロップ|パスワードを2回入力|保護して保存','本物のAES-256（リビジョン6）の開くパスワードを設定し、印刷・コピー・編集の許可は詳細設定で個別に選べます。','パスワードはどこにも保存・送信されないため、忘れると復元できません。既存の電子署名は引き継がれず、保護後のファイルは少し大きくなります。','忘れたパスワードは復元できますか？','できません。パスワードはこのブラウザのタブ内にだけ存在するため、記憶しているものが唯一の控えです。']],
 'pdf-unlock':[
 ['Drop the protected PDFs|Enter the password you were given|Remove it and download','Removes AES-256, AES-128 and RC4 open passwords, and the owner restrictions on printing and copying disappear with them.','It never guesses or breaks an unknown password. Certificate-based and custom security handlers are not supported, and the result is rebuilt with a plain cross-reference table.','Does it work without knowing the password?','No. The correct password is required, and the tool is only for documents you are entitled to open.'],
 ['암호가 걸린 PDF 놓기|받은 암호를 입력|암호를 지우고 저장','AES-256·AES-128·RC4 열기 암호를 제거하고, 인쇄·복사를 막던 소유자 제한도 함께 사라집니다.','모르는 암호를 추측하거나 뚫지 않습니다. 인증서 기반이나 사용자 정의 보안 핸들러는 지원하지 않고, 결과는 일반 상호 참조 표로 다시 씁니다.','암호를 몰라도 되나요?','안 됩니다. 올바른 암호가 필요하며, 열 권한이 있는 문서에만 사용하세요.'],
 ['保護されたPDFをドロップ|受け取ったパスワードを入力|解除して保存','AES-256・AES-128・RC4の開くパスワードを解除し、印刷やコピーを止めていた所有者制限も一緒に外れます。','未知のパスワードを推測したり破ったりはしません。証明書ベースや独自のセキュリティハンドラには対応せず、結果は通常の相互参照表で書き直します。','パスワードを知らなくても使えますか？','使えません。正しいパスワードが必要で、開く権限のある文書にだけ使ってください。']],
 'jpg-to-pdf':[
 ['Add photos|Arrange the pages|Export as PDF','Places each image on an A4-sized page with margins while keeping its proportions.','It does not recognize text in scanned photos. Images can be scaled down to fit the page.','Will the photo fill the whole page?','No. The image is fitted inside margins without stretching or cropping.'],
 ['사진 추가|페이지 순서 정리|PDF로 저장','사진 비율을 유지하며 여백이 있는 A4 페이지에 한 장씩 배치합니다.','스캔 사진 속 글자를 인식하지 않습니다. 페이지에 맞게 이미지가 축소될 수 있습니다.','사진이 페이지 전체를 채우나요?','아니요. 늘리거나 자르지 않고 여백 안에 맞춥니다.'],
 ['写真を追加|ページ順を整理|PDFとして保存','写真の比率を保ち、余白付きのA4ページに1枚ずつ配置します。','写真内の文字認識はしません。ページに合わせて縮小する場合があります。','写真はページ全体を埋めますか？','いいえ。引き伸ばしや切り抜きをせず、余白の内側に収めます。']],
 'pdf-to-jpg':[
 ['Open a PDF|Select pages and JPG or PNG output|Export the rendered page images','Renders pages, including visible annotations, as images.','Rendered images do not retain selectable text or vector detail at arbitrary zoom.','Can I choose only a few pages?','Yes. Enter a range such as 2-4 in export settings before saving.'],
 ['PDF 열기|페이지 범위와 JPG·PNG 선택|렌더링된 페이지 이미지 저장','보이는 주석을 포함한 페이지를 이미지로 만듭니다.','선택 가능한 글자나 확대해도 선명한 벡터 특성은 유지되지 않습니다.','일부 페이지만 고를 수 있나요?','네. 저장 설정에 2-4 같은 범위를 입력하세요.'],
 ['PDFを開く|ページ範囲とJPG・PNGを選ぶ|描画したページ画像を保存','表示されている注釈も含めてページを画像にします。','選択可能な文字や、自由に拡大できるベクター情報は残りません。','一部のページだけ選べますか？','はい。保存設定で2-4のように範囲を指定してください。']],
 media:[
 ['Open a supported video or audio file|Choose a frame, GIF, audio or video export|Set the interval and save', 'Reads the file in ranges and processes it with WebCodecs on your device.', 'No fixed size or duration cap; hour-long files over 500 MB are tested. Codec support depends on your browser. A real-time compatibility mode (up to 10 minutes) is used only without WebCodecs.', 'Can I export MP4?', 'Yes, when your browser can encode H.264, which is detected automatically. Otherwise video is saved as WebM. Audio can be WAV or MP3; animations use GIF.'],
 ['지원되는 영상·음성 열기|프레임·GIF·오디오·영상 저장 선택|구간을 지정하고 저장', '파일을 필요한 부분만 읽어 기기에서 WebCodecs로 처리합니다.', '크기·길이에 고정 상한이 없으며 500MB가 넘는 1시간 파일로 검증했습니다. 코덱 지원은 브라우저마다 다릅니다. WebCodecs가 없을 때만 최대 10분의 실시간 호환 모드를 씁니다.', 'MP4로 저장할 수 있나요?', '네. 브라우저가 H.264 인코딩을 지원하면 자동으로 감지해 MP4로 저장하고, 아니면 WebM으로 저장합니다. 음성은 WAV·MP3, 움직이는 이미지는 GIF입니다.'],
 ['対応する動画・音声を開く|フレーム・GIF・音声・動画の保存を選ぶ|区間を指定して保存', 'ファイルを必要な部分だけ読み込み、端末上のWebCodecsで処理します。', 'サイズ・長さに固定の上限はなく、500MBを超える1時間のファイルで検証しています。コーデック対応はブラウザによって異なります。WebCodecsがない場合のみ最大10分の実時間互換モードを使います。', 'MP4で保存できますか？', 'はい。ブラウザがH.264のエンコードに対応していれば自動で検出してMP4で保存し、そうでなければWebMで保存します。音声はWAV・MP3、アニメーションはGIFです。']],
 'video-trim':[
 ['Open a video|Set start and end times|Choose Fast cut or Precise and save', 'Fast cut copies the selected range without re-encoding; Precise re-encodes for exact start and end times.', 'No fixed duration cap in Fast or Precise mode. Fast cut shrinks inward to keyframes. Only the compatibility recorder, used without WebCodecs, records in real time for up to 10 minutes.', 'Why did export stop when I changed tabs?', 'Only the compatibility recorder needs a visible tab; it stops on hidden tabs to avoid inaccurate output. Fast and Precise modes keep running.'],
 ['영상 열기|시작·끝 시간 지정|빠른 자르기 또는 정밀 모드로 저장', '빠른 자르기는 재인코딩 없이 구간을 복사하고, 정밀 모드는 정확한 시작·끝을 위해 재인코딩합니다.', '빠른·정밀 모드에는 길이 상한이 없습니다. 빠른 자르기는 구간 안쪽 키프레임에 맞춰집니다. WebCodecs가 없을 때 쓰는 호환 녹화만 최대 10분 실시간 녹화입니다.', '탭을 바꾸니 저장이 중단되는 이유는 무엇인가요?', '호환 녹화만 탭이 보여야 합니다. 부정확한 결과를 막기 위해 숨겨진 탭에서는 멈춥니다. 빠른·정밀 모드는 계속 진행됩니다.'],
 ['動画を開く|開始・終了時刻を指定|高速カットまたは精密モードで保存', '高速カットは再エンコードせずに区間をコピーし、精密モードは正確な開始・終了のため再エンコードします。', '高速・精密モードに長さの上限はありません。高速カットは区間内側のキーフレームに合わせます。WebCodecsがない場合の互換録画のみ最大10分の実時間録画です。', 'タブを変えると保存が止まるのはなぜですか？', '互換録画のみタブの表示が必要で、不正確な出力を避けるため非表示のタブでは停止します。高速・精密モードは継続します。']],
 'video-frame':[
 ['Open a video|Move playback to the desired moment|Save the current frame as PNG','Extracts a still image from a browser-decoded frame.','The longest output side is limited to 1920 pixels. Audio-only files have no video frame.','Is this the original full-resolution frame?','Only when within the output limit. Larger frames are scaled down while keeping their proportions.'],
 ['영상 열기|원하는 시점으로 재생 위치 이동|현재 장면을 PNG로 저장','브라우저가 읽은 영상 프레임을 정지 이미지로 꺼냅니다.','긴 변은 최대 1920px입니다. 음성 전용 파일에는 영상 프레임이 없습니다.','원본 해상도로 추출되나요?','제한 안에서는 그렇습니다. 더 큰 프레임은 비율을 유지해 축소합니다.'],
 ['動画を開く|必要な場面に再生位置を合わせる|現在のフレームをPNGで保存','ブラウザが読み込んだフレームを静止画として取り出します。','長辺は最大1920pxです。音声のみのファイルにはフレームがありません。','元の解像度で取り出せますか？','出力上限内なら可能です。それより大きい場合は比率を保って縮小します。']],
 'video-mp3':[
 ['Open a video with audio or an audio file|Choose a start and end time|Export MP3 and download', 'Reads the audio track in ranges and encodes MP3 on your device.', 'No fixed source size or interval cap. The compatibility mode decodes the whole source in memory and supports sources up to 20 minutes. The browser must decode the source codec.', 'Can a silent video produce an MP3?', 'No. There must be a decodable audio track.'],
 ['소리가 있는 영상 또는 음성 파일 열기|시작·끝 시간 선택|MP3로 변환하고 다운로드', '오디오 트랙을 필요한 부분만 읽어 기기에서 MP3로 인코딩합니다.', '원본 크기·구간 길이에 고정 상한이 없습니다. 호환 모드는 원본 전체를 메모리에서 디코딩하므로 20분 이하 파일만 지원합니다. 브라우저가 원본 오디오 코덱을 지원해야 합니다.', '소리 없는 영상도 MP3가 되나요?', '아니요. 읽을 수 있는 오디오 트랙이 필요합니다.'],
 ['音声付き動画または音声を開く|開始・終了時刻を選ぶ|MP3に変換して保存', '音声トラックを必要な部分だけ読み込み、端末でMP3にエンコードします。', '元ファイルのサイズ・区間の長さに固定の上限はありません。互換モードは元ファイル全体をメモリでデコードするため20分以下に限ります。ブラウザが元の音声コーデックに対応する必要があります。', '無音の動画からもMP3を作れますか？', 'いいえ。読み取れる音声トラックが必要です。']],
 'video-gif':[
 ['Open a video|Choose a segment|Set width, frame rate and colors, then create the GIF', 'Decodes frames with WebCodecs and builds an adaptive palette for each frame; 640 px wide at 12 fps by default, adjustable up to 60 fps.', 'GIF has at most 256 colors per frame and no audio, and long clips make large files. Frames are written to temporary storage as they are encoded. The compatibility mode without WebCodecs is limited to 20 seconds, 8 fps and 480 px.', 'Why is the animation less smooth than my video?', 'The default of 12 fps keeps files small. Raise the frame rate in the GIF settings, or export video for full smoothness.'],
 ['영상 열기|구간 선택|폭·프레임 수·색상 수를 정하고 GIF 만들기', 'WebCodecs로 프레임을 디코딩하고 프레임마다 적응형 팔레트를 만듭니다. 기본값은 폭 640px·12fps이며 최대 60fps까지 조절할 수 있습니다.', 'GIF는 프레임당 최대 256색이고 소리가 없으며, 긴 구간은 파일이 커집니다. 인코딩하면서 임시 저장소에 바로 씁니다. WebCodecs가 없는 호환 모드는 20초·8fps·480px까지입니다.', '원본보다 움직임이 끊겨 보이는 이유는 무엇인가요?', '기본값 12fps는 파일 크기를 줄이기 위한 것입니다. GIF 설정에서 프레임 수를 올리거나, 부드러운 움직임이 필요하면 영상으로 저장하세요.'],
 ['動画を開く|区間を選ぶ|幅・フレームレート・色数を決めてGIFを作成', 'WebCodecsでフレームをデコードし、フレームごとに適応パレットを作ります。既定は幅640px・12fpsで、最大60fpsまで調整できます。', 'GIFはフレームごとに最大256色で音声はなく、長い区間はファイルが大きくなります。エンコードしながら一時保存領域に書き込みます。WebCodecsがない互換モードは20秒・8fps・480pxまでです。', '動きが元動画より滑らかでないのはなぜですか？', '既定の12fpsはファイルを小さく保つためです。GIF設定でフレームレートを上げるか、滑らかな動きが必要なら動画で保存してください。']],
 'video-compress':[
 ['Open a video|Select a short interval and smaller output width|Record WebM and compare the actual size','Reduces output dimensions and uses a resolution-based recording bitrate.','No target-size guarantee. Export is WebM, not MP4, and a small original can become larger.','How can I make the output smaller?','Reduce the width or interval length, then inspect the result. More compression can remove fine detail.'],
 ['영상 열기|짧은 구간과 작은 출력 너비 선택|WebM 녹화 후 실제 용량 비교','출력 해상도를 줄이고 해상도에 따른 비트레이트로 녹화합니다.','목표 용량은 보장하지 않습니다. MP4가 아닌 WebM이며 작은 원본은 더 커질 수도 있습니다.','더 작게 만들려면 어떻게 하나요?','너비나 구간 길이를 줄이고 결과를 확인하세요. 세부 묘사가 손상될 수 있습니다.'],
 ['動画を開く|短い区間と小さめの出力幅を選ぶ|WebMで録画し実際の容量を比較','解像度を下げ、出力サイズに応じたビットレートで録画します。','目標容量は保証しません。MP4ではなくWebMで、小さい元動画より容量が増える場合もあります。','さらに小さくするには？','幅や区間を減らし、結果を確認してください。細部が失われる場合があります。']]
};

export function guide(id,locale){
 const current=capabilityGuide(id,locale);if(current)return current;
 if(TOOLS[id]){const d=TOOLS[id],i={ko:0,en:1,ja:2}[locale];return [
  ["이미지 넣기|필요한 설정을 조정하고 결과 확인|다운로드로 새 파일 저장","Add images|Adjust settings and review the result|Download a new file","画像を追加|設定を調整して結果を確認|新しいファイルを保存"][i],d.description[i],d.limit[i],
  ["이 도구의 한계는 무엇인가요?","What are this tool’s limitations?","このツールにはどのような制限がありますか？"][i],d.limit[i]];}
 return guides[id][{en:0,ko:1,ja:2}[locale]];
}
export function formats(id,locale){
 if(TOOLS[id]){const output={refiner:'PNG / ZIP','palette-swap':'PNG','logo-bg':'PNG','texture-map':'PNG','texture-lab':'PNG / JSON / ZIP','channel-unpacker':'PNG (ZIP)','normal-map-converter':'PNG','pbr-texture-validator':'JSON','texture-edge-bleed':'PNG','mask-packer':'PNG','margin-crop':'PNG','marketplace-pack':'JPG + JSON (ZIP)','print-pack':'JPG + JSON (ZIP)','bitmap-font':'PNG + FNT + JSON (ZIP)','favicon-pack':'ICO + PNG + HTML + Webmanifest (ZIP)'}[id]||'PNG + JSON (ZIP)';return 'PNG / JPG / WebP / AVIF / HEIC → '+output+' — '+{ko:'입력 디코딩은 브라우저 지원과 추가 엔진 사용 여부에 따라 다릅니다.',en:'Input decoding depends on browser support and optional engines.',ja:'入力のデコードはブラウザ対応と追加エンジンに依存します。'}[locale];}
 const editor=INTENTS[id].editor;
 const mediaOutput={'video-mp3':'MP3 / WAV','video-gif':'GIF','video-frame':'PNG','video-trim':'MP4 / WebM','video-compress':'MP4 / WebM',media:'MP4 / WebM / GIF / PNG / WAV / MP3'};
 const values=editor==='pdf'?(id==='jpg-to-pdf'?'JPG / PNG / WebP → PDF':id==='pdf-to-jpg'?'PDF → JPG / PNG':id==='pdf'?'PDF / JPG / PNG / WebP → PDF / JPG / PNG':'PDF → PDF'):editor==='media'?`MP4 / WebM / MOV${['media','video-mp3'].includes(id)?' / MP3 / WAV / OGG / M4A':''} → ${mediaOutput[id]}`:id==='home'?'PNG / JPG / WebP / PDF / MP4 / WebM / WAV':id==='heic'?'HEIC / HEIF → JPG / PNG / WebP':`PNG / JPG / WebP / AVIF / HEIC → ${['pixel','upscale','resize','remove-bg'].includes(id)?'PNG':'PNG / JPG / WebP'}`;
 const note={en:'Input decoding and output encoding depend on browser support.',ko:'입력·출력 지원은 브라우저에 따라 다릅니다.',ja:'読み込み・書き出しはブラウザの対応状況によります。'}[locale];
 return values+' — '+note+(editor==='image'||editor==='pixel'?' '+{en:'Animated inputs are rejected; select a still frame first.',ko:'움직이는 입력은 거부합니다. 먼저 정지 프레임을 선택하세요.',ja:'アニメーション入力は非対応です。静止フレームを選択してください。'}[locale]:'');
}
export function footer(locale){const l=labels[locale];return `<footer class="site-footer"><nav aria-label="${esc(l.about)}">${['about','privacy','terms','contact'].map(p=>`<a href="${locale}/${p}/" target="_blank" rel="noopener">${esc(l[p])}</a>`).join('')}<a href="assets/vendor/NOTICES.txt" target="_blank" rel="noopener">${esc({ko:'오픈소스 라이선스',en:'Open-source licenses',ja:'オープンソースライセンス'}[locale])}</a></nav><p>${esc(l.saved)}</p></footer>`;}
const POPULAR={ko:'자주 하는 작업',en:'Popular tasks',ja:'よく使う作業'};
/** Task-specific copy for a landing page, then links to sibling tasks of the same tool. */
function landingHTML(id,locale,path){
 const land=landingText(path,locale),tasks=LANDING_PATHS.filter(p=>LANDINGS[p].intent===id&&p!==path);
 const intro=land?`<h2>${esc(land.title)}</h2>${land.intro.map(p=>`<p>${esc(p)}</p>`).join('')}`:'';
 const links=tasks.length?`<nav class="landing-links" aria-label="${esc(POPULAR[locale])}"><h3>${esc(POPULAR[locale])}</h3>${tasks.map(p=>`<a href="${locale}/${p}/">${esc(landingText(p,locale).title)}</a>`).join('')}</nav>`:'';
 return {intro,links};
}
export function toolContent(id,locale,path=''){
 const capability=capabilitySummary(id,locale),landing=landingHTML(id,locale,path);
 const l=labels[locale],g=guide(id,locale),related=INTENTS[id].next.length?INTENTS[id].next:['upscale','pdf-merge','pixel','media'];
 const faq=[[g[3],g[4]],[l.uploadQ,l.uploadA],[l.resultQ,l.resultA]];
 return `<section class="reading-content"><nav class="related-tools" aria-label="${esc(l.related)}"><h2>${esc(l.related)}</h2>${related.slice(0,3).map(n=>`<a href="${locale}/${INTENTS[n].path}/" data-action="intent:${n}">${esc(t(`intent.${n}.title`,{},locale))}</a>`).join('')}</nav><article>${landing.intro}${exampleHTML(id,locale)}<h2>${esc(t(`intent.${id}.title`,{},locale))}</h2><p>${esc(t(`intent.${id}.description`,{},locale))}</p><h3>${esc(l.how)}</h3><ol>${g[0].split('|').map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h3>${esc(l.formats)}</h3><p>${esc(formats(id,locale))}</p><h3>${esc(l.features)}</h3><p>${esc(g[1])}</p><h3>${esc(capability.title)}</h3><p data-capability="${id}">${esc(capability.text)}</p><h3>${esc(l.limits)}</h3><p>${esc(g[2])}</p>${landing.links}</article><!--ad:content-1--><section class="faq"><h2>${esc(l.faq)}</h2>${faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section><!--ad:content-2--></section>${footer(locale)}`;
}
