// Generated by tools/generate-examples.py; actual engine output from first-party geometric samples.
export const EXAMPLES = {
  "refiner": {
    "before": {
      "file": "refiner-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "refiner-processed-example.png",
      "width": 32,
      "height": 32
    }
  },
  "sprite-slicer": {
    "before": {
      "file": "sprite-slicer-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "sprite-slicer-processed-example.png",
      "width": 24,
      "height": 36
    }
  },
  "frame-normalize": {
    "before": {
      "file": "frame-normalize-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "frame-normalize-processed-example.png",
      "width": 68,
      "height": 40
    }
  },
  "sprite-sheet-maker": {
    "before": {
      "file": "sprite-sheet-maker-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "sprite-sheet-maker-processed-example.png",
      "width": 136,
      "height": 40
    }
  },
  "palette-swap": {
    "before": {
      "file": "palette-swap-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "palette-swap-processed-example.png",
      "width": 96,
      "height": 64
    }
  },
  "marketplace-pack": {
    "before": {
      "file": "marketplace-pack-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "marketplace-pack-processed-example.png",
      "width": 320,
      "height": 240
    }
  },
  "print-pack": {
    "before": {
      "file": "print-pack-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "print-pack-processed-example.png",
      "width": 213,
      "height": 320
    }
  },
  "logo-bg": {
    "before": {
      "file": "logo-bg-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "logo-bg-processed-example.png",
      "width": 96,
      "height": 64
    }
  },
  "bitmap-font": {
    "before": {
      "file": "bitmap-font-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "bitmap-font-processed-example.png",
      "width": 96,
      "height": 64
    }
  },
  "mask-packer": {
    "before": {
      "file": "mask-packer-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "mask-packer-processed-example.png",
      "width": 96,
      "height": 64
    }
  },
  "atlas-padding": {
    "before": {
      "file": "atlas-padding-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "atlas-padding-processed-example.png",
      "width": 108,
      "height": 72
    }
  },
  "texture-map": {
    "before": {
      "file": "texture-map-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "texture-map-processed-example.png",
      "width": 96,
      "height": 64
    }
  },
  "tile-helper": {
    "before": {
      "file": "tile-helper-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "tile-helper-processed-example.png",
      "width": 32,
      "height": 32
    }
  },
  "scan-split": {
    "before": {
      "file": "scan-split-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "scan-split-processed-example.png",
      "width": 48,
      "height": 64
    }
  },
  "margin-crop": {
    "before": {
      "file": "margin-crop-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "margin-crop-processed-example.png",
      "width": 84,
      "height": 56
    }
  },
  "favicon-pack": {
    "before": {
      "file": "favicon-pack-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "favicon-pack-processed-example.png",
      "width": 16,
      "height": 16
    }
  },
  "image": {
    "before": {
      "file": "image-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "image-processed-example.png",
      "width": 72,
      "height": 48
    }
  },
  "upscale": {
    "before": {
      "file": "upscale-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "upscale-processed-example.png",
      "width": 192,
      "height": 128
    }
  },
  "remove-bg": {
    "before": {
      "file": "remove-bg-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "remove-bg-processed-example.png",
      "width": 96,
      "height": 64
    }
  },
  "compress": {
    "before": {
      "file": "compress-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "compress-processed-example.png",
      "width": 96,
      "height": 64
    }
  },
  "convert": {
    "before": {
      "file": "convert-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "convert-processed-example.png",
      "width": 96,
      "height": 64
    }
  },
  "crop": {
    "before": {
      "file": "crop-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "crop-processed-example.png",
      "width": 72,
      "height": 48
    }
  },
  "resize": {
    "before": {
      "file": "resize-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "resize-processed-example.png",
      "width": 48,
      "height": 32
    }
  },
  "pixel": {
    "before": {
      "file": "pixel-original-example.png",
      "width": 96,
      "height": 64
    },
    "after": {
      "file": "pixel-processed-example.png",
      "width": 32,
      "height": 32
    }
  }
};
