import {inspectImage} from './image-container.js';
import {track} from './analytics.js';
import {t, getLocale} from './i18n.js';
import {LIMITS,dimensions,fit,clamp,quantize,removeConnected,addOutline,gif} from './core.js';
export function canvas(w,h){dimensions(w,h);const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(!ctx){c.width=c.height=1;throw Error('This browser could not allocate the image. Close other files or use a smaller output.');}return c;}
export const copy=c=>{const o=canvas(c.width,c.height);o.getContext('2d').drawImage(c,0,0);return o;};
const proxies=new WeakMap();
export const release=c=>{if(c){const proxy=proxies.get(c);if(proxy){proxy.width=proxy.height=1;proxies.delete(c);}c.width=1;c.height=1;}};
export function previewProxy(c){if(Math.max(c.width,c.height)<=1920)return c;let p=proxies.get(c);if(!p){const scale=1920/Math.max(c.width,c.height);p=resize(c,Math.max(1,Math.round(c.width*scale)),Math.max(1,Math.round(c.height*scale)));proxies.set(c,p);}return p;}
export function blobOf(c,type='image/png',quality=.92){return new Promise((resolve,reject)=>c.toBlob(b=>b&&b.type===type?resolve(b):reject(Error(t("브라우저가 이 출력 형식을 지원하지 않습니다. PNG 또는 JPG를 선택하세요."))),type,quality));}
export function download(blob,name,{measure=true}={}){if(measure)track('download');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30_000);}
const scriptLoads=new Map();
export function script(url){if(scriptLoads.has(url))return scriptLoads.get(url);const p=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.crossOrigin='anonymous';const timer=setTimeout(()=>{s.remove();scriptLoads.delete(url);reject(Error(t("추가 기능 다운로드 시간 초과. 연결을 확인한 뒤 다시 시도하세요.")));},45_000);s.onload=()=>{clearTimeout(timer);resolve();};s.onerror=()=>{clearTimeout(timer);s.remove();scriptLoads.delete(url);reject(Error(t("추가 기능을 불러오지 못했습니다. 인터넷 연결이나 콘텐츠 차단 설정을 확인하세요.")));};document.head.append(s);});scriptLoads.set(url,p);return p;}
function headerSize(b){const v=new DataView(b.buffer,b.byteOffset,b.byteLength),str=(a,n)=>String.fromCharCode(...b.slice(a,a+n));if(b.length>24&&str(1,3)==='PNG')return [v.getUint32(16),v.getUint32(20)];if(b.length>30&&str(0,4)==='RIFF'&&str(8,4)==='WEBP'){const t=str(12,4);if(t==='VP8X')return [1+b[24]+(b[25]<<8)+(b[26]<<16),1+b[27]+(b[28]<<8)+(b[29]<<16)];if(t==='VP8 ')return [v.getUint16(26,true)&16383,v.getUint16(28,true)&16383];if(t==='VP8L'){const n=v.getUint32(21,true);return [(n&16383)+1,((n>>>14)&16383)+1];}}if(b[0]===255&&b[1]===216){let i=2;while(i+8<b.length){if(b[i]!==255){i++;continue;}const m=b[i+1];if(m===218||m===217)break;const len=v.getUint16(i+2);if(len<2)break;if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(m))return [v.getUint16(i+7),v.getUint16(i+5)];i+=len+2;}}return null;}
export async function decode(file,options={}){if(file.document){const {renderDocument}=await import('./image-document.js');return renderDocument(file,options);}if(/\.svg$/i.test(file.name||'')||file.type==='image/svg+xml')throw Error(t("SVG 입력은 아직 지원하지 않습니다. PNG 또는 JPG를 선택하세요."));const container=await inspectImage(file);if(container.animation)throw Error('Animated or multi-frame input is not supported by this still-image tool. Export a single frame first.');const h=headerSize(new Uint8Array(await file.slice(0,524288).arrayBuffer()));if(h)dimensions(...h);let bitmap;try{bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});}catch{if(!/\.hei[cf]$/i.test(file.name||'')&&!/hei[cf]/i.test(file.type))throw Error(t("이미지를 열 수 없습니다. 정지 PNG·JPG·WebP·AVIF 파일을 선택하세요."));await script('https://cdn.jsdelivr.net/npm/heic2any@0.0.4/dist/heic2any.min.js');const converted=await window.heic2any({blob:file,toType:'image/png'});if(Array.isArray(converted)&&converted.length!==1)throw Error(t("여러 장이 들어 있는 HEIC는 지원하지 않습니다. 단일 사진을 선택하세요."));bitmap=await createImageBitmap(Array.isArray(converted)?converted[0]:converted);}try{dimensions(bitmap.width,bitmap.height);const c=canvas(bitmap.width,bitmap.height);c.getContext('2d').drawImage(bitmap,0,0);return c;}finally{bitmap.close();}}
export function resize(c,w,h,nearest=false){const o=canvas(w,h),ctx=o.getContext('2d');ctx.imageSmoothingEnabled=!nearest;ctx.imageSmoothingQuality='high';ctx.drawImage(c,0,0,w,h);return o;}
/** Async export-quality path. Synchronous resize is reserved for small UI proxies / nearest pixel art. */
export async function resizeQuality(c,w,h,options={}){if(options.nearest)return resize(c,w,h,true);const {resample}=await import('./resample.js');return resample(c,w,h,options);}
export async function upscale(c,scale,mode,options={}){if(mode==='sr'){const {superResolve}=await import('./super-resolution.js');return superResolve(c,scale,options);}return resizeQuality(c,c.width*scale,c.height*scale,{...options,nearest:mode==='pixel'});}
export function rotate(c,flip=false){const o=canvas(flip?c.width:c.height,flip?c.height:c.width),ctx=o.getContext('2d');if(flip){ctx.translate(o.width,0);ctx.scale(-1,1);}else{ctx.translate(o.width,0);ctx.rotate(Math.PI/2);}ctx.drawImage(c,0,0);return o;}
export function crop(c,r){const x=Math.min(c.width-1,Math.round(clamp(r.x,0,1)*c.width)),y=Math.min(c.height-1,Math.round(clamp(r.y,0,1)*c.height)),w=Math.max(1,Math.min(c.width-x,Math.round(r.w*c.width))),h=Math.max(1,Math.min(c.height-y,Math.round(r.h*c.height)));const o=canvas(w,h);o.getContext('2d').drawImage(c,x,y,w,h,0,0,w,h);return o;}
export function trim(c){const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let l=c.width,t=c.height,r=-1,b=-1;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(d[(y*c.width+x)*4+3]>8){l=Math.min(l,x);t=Math.min(t,y);r=Math.max(r,x);b=Math.max(b,y);}return r<0?copy(c):crop(c,{x:l/c.width,y:t/c.height,w:(r-l+1)/c.width,h:(b-t+1)/c.height});}
export function background(c,color){const o=canvas(c.width,c.height),ctx=o.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,o.width,o.height);ctx.drawImage(c,0,0);return o;}
export async function trimAsync(c,options={}){const {imageBounds}=await import('./image-bounds.js'),r=await imageBounds(c,options);return r?crop(c,{x:r.x/c.width,y:r.y/c.height,w:r.w/c.width,h:r.h/c.height}):copy(c);}
export function pixelBase(c,n,mode='contain',trimFirst=true){let src=c;if(trimFirst)src=trim(c);const o=canvas(n,n),ctx=o.getContext('2d'),f=fit(src.width,src.height,n,n,mode==='cover');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(src,f.x,f.y,f.w,f.h);if(src!==c)release(src);return o;}
export async function fitQuality(source,w,h,mode='contain',bg=null,options={}){
 let cropped=null,scaled=null,out=null;
 try{
  if(mode==='cover'){
   const ratio=w/h,sw=Math.min(source.width,source.height*ratio),sh=Math.min(source.height,source.width/ratio);
   cropped=crop(source,{x:(source.width-sw)/2/source.width,y:(source.height-sh)/2/source.height,w:sw/source.width,h:sh/source.height});
   scaled=await resizeQuality(cropped,w,h,options);
  }else{const f=fit(source.width,source.height,w,h);scaled=await resizeQuality(source,Math.max(1,Math.round(f.w)),Math.max(1,Math.round(f.h)),options);}
  out=canvas(w,h);const ctx=out.getContext('2d');if(bg){ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);}ctx.drawImage(scaled,Math.round((w-scaled.width)/2),Math.round((h-scaled.height)/2));const result=out;out=null;return result;
 }finally{release(cropped);release(scaled);release(out);}
}
export async function pixelBaseQuality(source,n,mode='contain',trimFirst=true,options={}){
 let cropped;
 try{if(trimFirst){const {imageBounds}=await import('./image-bounds.js'),b=await imageBounds(source,options);if(b&&(b.w!==source.width||b.h!==source.height))cropped=crop(source,{x:b.x/source.width,y:b.y/source.height,w:b.w/source.width,h:b.h/source.height});}
  return await fitQuality(cropped||source,n,n,mode,null,options);
 }finally{release(cropped);}
}
export async function encode(c,options={},check=()=>{}){const {compress}=await import('./compression.js');return compress(c,options,check);}
let currentWorker=null;
export function runWorker(kind,payload,progress=()=>{},signal,reload){return new Promise((resolve,reject)=>{let worker=null,done=false,fallbackStarted=false;const finish=(err,value)=>{if(done)return;done=true;worker?.terminate();if(currentWorker===worker)currentWorker=null;signal?.removeEventListener('abort',stop);err?reject(err):resolve(value);},stop=()=>finish(new DOMException(t("취소했습니다."),'AbortError'));
 const fallback=async()=>{if(done||fallbackStarted)return;fallbackStarted=true;worker?.terminate();if(kind==='portrait')return finish(Error(t("AI 작업용 Worker를 시작할 수 없습니다. HTTPS 주소와 브라우저 설정을 확인하세요.")));if(['remove','outline'].includes(kind)&&payload.w*payload.h>4_000_000)return finish(Error(t("이 브라우저의 호환 모드는 400만 픽셀 이하에서 지원합니다. 크기를 먼저 줄이세요.")));progress(t("호환 모드에서 처리 중…"));await new Promise(r=>setTimeout(r,0));if(done)return;try{if(payload.data?.byteLength===0&&reload)payload.data=reload();let result;if(kind==='pixel'){result=quantize(payload.data,payload.w,payload.h,payload.colors,payload.dither,payload);if(payload.outline)result=addOutline(result,payload.w,payload.h,payload.outline);}else if(kind==='remove')result=removeConnected(payload.data,payload.w,payload.h,payload.color,payload.tolerance);else if(kind==='outline')result=addOutline(payload.data,payload.w,payload.h,payload.radius);else if(kind==='gif')result=gif(payload.frames,payload.w,payload.h,payload.delay,payload);else throw Error(t("지원하지 않는 작업입니다."));if(signal?.aborted)stop();else finish(null,result);}catch(e){finish(e);}};
 signal?.addEventListener('abort',stop,{once:true});if(signal?.aborted)return stop();
 try{worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});currentWorker=worker;worker.onmessage=e=>{if(e.data.progress!==undefined)progress(e.data.progress);else if(e.data.error)finish(Error(e.data.error));else finish(null,e.data.result);};worker.onerror=fallback;
 // Transfer pixel ownership. Reload from the unchanged source only on startup failure.
 worker.postMessage({kind,...payload,locale:getLocale()},payload.data?.buffer?[payload.data.buffer]:[]);
 }catch{fallback();}
 });}
export async function processPixels(c,kind,options,progress,signal){if(kind==='outline'){const {outlineTiled}=await import('./image-tiles.js');return outlineTiled(c,{...options,progress,signal});}if(kind==='portrait'||kind==='general'){const {removeBackground}=await import('./matting.js');return removeBackground(c,{...options,progress,signal});}const data=c.getContext('2d').getImageData(0,0,c.width,c.height);const result=await runWorker(kind,{data:data.data,w:c.width,h:c.height,...options},progress,signal,()=>c.getContext('2d').getImageData(0,0,c.width,c.height).data);const o=canvas(c.width,c.height);o.getContext('2d').putImageData(new ImageData(result instanceof Uint8ClampedArray?result:new Uint8ClampedArray(result),c.width,c.height),0,0);return o;}

export async function availableFormats(){return (await import('./compression.js')).supportedFormats();}
