import {t} from './i18n.js';
import {modernMedia,releaseOutput,clearExpiredMedia} from './media-modern.js';
export {releaseOutput};
const mediaFiles=new WeakMap();
import {LIMITS,fit,clamp} from './core.js';
import {canvas,blobOf,release,runWorker} from './image.js';
export function wait(el,event,signal,ms=20000){return new Promise((resolve,reject)=>{const finish=(e)=>{clearTimeout(timer);el.removeEventListener(event,ok);el.removeEventListener('error',bad);signal?.removeEventListener('abort',stop);e?reject(e):resolve();},ok=()=>finish(),bad=()=>finish(Error(t("이 브라우저가 파일의 코덱을 지원하지 않거나 파일이 손상되었습니다."))),stop=()=>finish(new DOMException(t("취소했습니다."),'AbortError')),timer=setTimeout(()=>finish(Error(t("미디어 읽기 시간이 초과되었습니다."))),ms);el.addEventListener(event,ok,{once:true});el.addEventListener('error',bad,{once:true});signal?.addEventListener('abort',stop,{once:true});if(signal?.aborted)stop();});}
export async function openMedia(video,file,signal){clearExpiredMedia();const url=URL.createObjectURL(file);let metadata;try{try{metadata=await modernMedia('probe',file,{},()=>{},signal);}catch(e){if(signal?.aborted)throw e;}const ready=wait(video,'loadeddata',signal,metadata?5000:20000);video.src=url;video.load();try{await ready;}catch(e){if(!metadata||signal?.aborted)throw e;}if(!metadata){if(!Number.isFinite(video.duration)||video.duration<=0)throw Error('Cannot read the media duration. Try a supported MP4 or WebM file.');metadata={duration:video.duration,w:video.videoWidth,h:video.videoHeight,codecs:[],mp4:false};}mediaFiles.set(video,file);return {file,url,...metadata};}catch(e){video.removeAttribute('src');video.load();URL.revokeObjectURL(url);throw e;}}
export async function seek(video,t,signal){video.pause();t=clamp(t,0,Math.max(0,video.duration-.04));if(Math.abs(video.currentTime-t)>.01){const p=wait(video,'seeked',signal);video.currentTime=t;await p;}return video.currentTime;}
async function legacyFrame(video,time,signal,max=Infinity){if(!video.videoWidth)throw Error(t("오디오 파일에는 영상 프레임이 없습니다."));await seek(video,time,signal);const s=Math.min(1,max/Math.max(video.videoWidth,video.videoHeight)),c=canvas(Math.round(video.videoWidth*s),Math.round(video.videoHeight*s));c.getContext('2d').drawImage(video,0,0,c.width,c.height);return c;}
/** Compatibility (MediaRecorder / AudioContext / seek) fallbacks only; the WebCodecs path streams to
 * OPFS and has no duration cap. Audio fallback decodes the entire source to PCM, so it is bounded by
 * source duration (20 min stereo ≈ 460 MB of float PCM), not by file size. */
export const COMPAT=Object.freeze({seconds:600,audioSourceSeconds:1200,gifSeconds:20,gifSide:480});
export function interval(info,start,end,max=COMPAT.seconds){start=Number(start);end=Number(end);if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end>info.duration+.02||end<=start)throw Error(t("시작·끝 시간을 확인하세요."));if(end-start>max)throw Error(t("한 번에 {0}초 이하 구간을 저장하세요.", {0: max}));return {start,end};}
async function legacyGif(v,info,start,end,progress,signal){interval(info,start,end,COMPAT.gifSeconds);if(!info.w)throw Error(t("영상 파일을 선택하세요."));const frames=[];let w,h;try{for(let time=start;time<end;time+=1/8){if(signal?.aborted)throw new DOMException(t("취소했습니다."),'AbortError');const c=await legacyFrame(v,time,signal,COMPAT.gifSide);w=c.width;h=c.height;frames.push(c.getContext('2d').getImageData(0,0,w,h).data);release(c);progress(t("GIF 장면 {0}%", {0: (100*(time-start)/(end-start)).toFixed(0)}));}const data=await runWorker('gif',{frames,w,h,delay:125},progress,signal);return new Blob([data],{type:'image/gif'});}finally{await seek(v,start).catch(()=>{});}}
async function legacyAudio(info,start,end,format,progress,signal){interval(info,start,end);if(!(info.duration<=COMPAT.audioSourceSeconds))throw Error(t("호환 모드 오디오 추출은 원본 전체를 메모리에서 디코딩하므로 {0}분 이하 파일만 지원합니다. 정밀 모드를 사용하세요.",{0:COMPAT.audioSourceSeconds/60}));const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error(t("이 브라우저는 오디오 디코딩을 지원하지 않습니다."));const context=new Audio();try{progress(t("기기에서 오디오를 읽는 중…"));const audio=await context.decodeAudioData(await info.file.arrayBuffer());if(signal?.aborted)throw new DOMException(t("취소했습니다."),'AbortError');if(end>audio.duration+.1)throw Error(t("선택 구간이 오디오 길이를 벗어납니다."));const rate=audio.sampleRate,from=Math.floor(start*rate),to=Math.min(audio.length,Math.ceil(end*rate)),channels=Array.from({length:Math.min(audio.numberOfChannels,2)},(_,i)=>audio.getChannelData(i).slice(from,to));if(!channels.length)throw Error(t("오디오 트랙이 없습니다."));const data=await new Promise((resolve,reject)=>{const worker=new Worker(new URL('./audio-worker.js',import.meta.url));let done=false;const finish=(err,out)=>{if(done)return;done=true;worker.terminate();signal?.removeEventListener('abort',stop);err?reject(err):resolve(out);},stop=()=>finish(new DOMException(t("취소했습니다."),'AbortError'));worker.onmessage=e=>{if(e.data.progressKey)progress(t(e.data.progressKey,e.data.params));else if(e.data.progress)progress(e.data.progress);else if(e.data.error)finish(Error(e.data.error));else finish(null,e.data.result);};worker.onerror=()=>finish(Error(t("오디오 인코더를 불러오지 못했습니다. WAV 저장 또는 인터넷 연결을 확인하세요.")));signal?.addEventListener('abort',stop,{once:true});worker.postMessage({format,rate,channels},channels.map(c=>c.buffer));});return new Blob([data],{type:format==='mp3'?'audio/mpeg':'audio/wav'});}finally{await context.close();}}
async function legacyVideo(v,info,start,end,width,progress,signal){interval(info,start,end);if(!info.w)throw Error(t("영상 파일을 선택하세요."));if(!window.MediaRecorder||!v.captureStream)throw Error(t("이 브라우저는 로컬 영상 저장을 지원하지 않습니다. Chrome 또는 Edge에서 시도하세요."));const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error(t("WebM 인코더가 없습니다."));await seek(v,start,signal);const s=Math.min(1,width/info.w),c=canvas(Math.round(info.w*s),Math.round(info.h*s)),ctx=c.getContext('2d');ctx.drawImage(v,0,0,c.width,c.height);const stream=c.captureStream(24),source=v.captureStream();for(const t of source.getAudioTracks())stream.addTrack(t);const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:Math.max(400000,Math.round(c.width*c.height*2.8))}),chunks=[];let raf,total=0,stopped=false;const previousMuted=v.muted;v.muted=true;try{return await new Promise((resolve,reject)=>{const cleanup=()=>{cancelAnimationFrame(raf);signal?.removeEventListener('abort',abort);document.removeEventListener('visibilitychange',visibility);v.pause();},fail=e=>{if(stopped)return;stopped=true;cleanup();if(recorder.state!=='inactive')recorder.stop();reject(e);},abort=()=>fail(new DOMException(t("취소했습니다."),'AbortError')),visibility=()=>{if(document.hidden)fail(Error(t("정확한 저장을 위해 탭을 열린 상태로 유지하세요. 저장을 중단했습니다.")));};recorder.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);total+=e.data.size;if(total>LIMITS.totalBytes)fail(Error(t("출력이 128MB를 초과했습니다. 구간을 줄이세요.")));}};recorder.onerror=()=>fail(Error(t("영상 저장 중 오류가 발생했습니다.")));recorder.onstop=()=>{if(stopped)return;stopped=true;cleanup();resolve(new Blob(chunks,{type:'video/webm'}));};const draw=()=>{if(stopped)return;ctx.drawImage(v,0,0,c.width,c.height);progress(t("실시간 저장 {0}%", {0: Math.min(100,100*(v.currentTime-start)/(end-start)).toFixed(0)}));if(v.currentTime>=end-.03||v.ended){recorder.stop();return;}raf=requestAnimationFrame(draw);};signal?.addEventListener('abort',abort,{once:true});document.addEventListener('visibilitychange',visibility);if(signal?.aborted)return abort();recorder.start(250);v.play().then(draw).catch(fail);});}finally{v.muted=previousMuted;for(const t of stream.getTracks())t.stop();for(const t of source.getTracks())t.stop();release(c);}}

export async function frame(video,time,signal,max=Infinity,format='png'){const file=mediaFiles.get(video);if(file){try{const result=await modernMedia('frame',file,{time,format,width:Number.isFinite(max)?max:undefined},()=>{},signal),bitmap=await createImageBitmap(result.blob),c=canvas(bitmap.width,bitmap.height);c.getContext('2d').drawImage(bitmap,0,0);bitmap.close();c.processingReport=result.report;return c;}catch(e){if(signal?.aborted)throw e;}}return legacyFrame(video,time,signal,max);}
export async function exportVideo(v,info,start,end,width,progress,signal,options={}){if(options.mode==='compatibility'&&options.format&&options.format!=='webm')throw Error('Compatibility recording exports WebM. Select WebM or use Precise/Fast mode.');if(options.mode==='compatibility'){const blob=await legacyVideo(v,info,start,end,width||1280,progress,signal);info.lastReport={engine:'Compatibility MediaRecorder',mode:'realtime',format:'webm',originalBytes:info.file.size,outputBytes:blob.size};return blob;}const result=await modernMedia('convert',info.file,{...options,start,end,width,format:options.format||'webm'},progress,signal);info.lastReport=result.report;return result.blob;}
export async function exportAudio(info,start,end,format,progress,signal,options={}){if(options.mode==='compatibility'){const blob=await legacyAudio(info,start,end,format,progress,signal);info.lastReport={engine:'Compatibility AudioContext / lamejs',format,originalBytes:info.file.size,outputBytes:blob.size};return blob;}const result=await modernMedia('convert',info.file,{...options,start,end,format},progress,signal);info.lastReport=result.report;return result.blob;}
export async function exportGif(v,info,start,end,progress,signal,options={}){if(options.mode==='compatibility'){const blob=await legacyGif(v,info,start,end,progress,signal);info.lastReport={engine:'Compatibility HTML video / GIF',format:'gif',originalBytes:info.file.size,outputBytes:blob.size};return blob;}const result=await modernMedia('gif',info.file,{...options,start,end,width:options.gifWidth||640,fps:options.gifFps||12,colors:options.gifColors||256,dither:options.gifDither||0},progress,signal);info.lastReport=result.report;return result.blob;}
