// PDF parsing, object copying, font embedding and serialization stay off the UI thread.
import * as L from '../assets/vendor/pdf-lib-1.17.1/pdf-lib.esm.min.js';
const documents=new Map();
let activeJob=0,requestSerial=0;const imageRequests=new Map();
function encodeOnMain(blob,maxSide,quality){const requestId=++requestSerial;return new Promise((resolve,reject)=>{imageRequests.set(requestId,{resolve,reject});postMessage({id:activeJob,imageRequest:{requestId,blob,maxSide,quality}});});}
const tick=()=>new Promise(r=>setTimeout(r,0));
async function load(source){if(documents.has(source.id))return documents.get(source.id);const doc=await L.PDFDocument.load(await source.file.arrayBuffer(),{updateMetadata:false});documents.set(source.id,doc);return doc;}
function metadata(page){const b=page.getCropBox(),rotation=((page.getRotation().angle%360)+360)%360,userUnit=page.node.lookupMaybe(L.PDFName.of('UserUnit'),L.PDFNumber)?.asNumber()||1;return {...b,rotation,userUnit,logicalW:(rotation%180?b.height:b.width)*userUnit,logicalH:(rotation%180?b.width:b.height)*userUnit};}
function point(p,u,v){const b=p.box,r=p.rotation;if(r===90)return {x:b.x+v*b.width,y:b.y+u*b.height};if(r===180)return {x:b.x+(1-u)*b.width,y:b.y+v*b.height};if(r===270)return {x:b.x+(1-v)*b.width,y:b.y+(1-u)*b.height};return {x:b.x+u*b.width,y:b.y+(1-v)*b.height};}
function color(hex='#172b4d'){return L.rgb(parseInt(hex.slice(1,3),16)/255,parseInt(hex.slice(3,5),16)/255,parseInt(hex.slice(5,7),16)/255);}
let cjkBytes;
async function fontFor(out,text,fonts){try{fonts.latin||=await out.embedFont(L.StandardFonts.Helvetica);fonts.latin.encodeText(text);return fonts.latin;}catch{if(!fonts.cjk){await import('../assets/vendor/pdf-lib-fontkit-1.1.1/fontkit.umd.min.js');out.registerFontkit(globalThis.fontkit);if(!cjkBytes){const response=await fetch('https://cdn.jsdelivr.net/gh/notofonts/noto-cjk@f8d157532fbfaeda587e826d4cd5b21a49186f7c/Sans/OTF/Korean/NotoSansCJKkr-Regular.otf');if(!response.ok)throw Error('Cannot download annotation font. Check the connection and retry.');cjkBytes=await response.arrayBuffer();}fonts.cjk=await out.embedFont(cjkBytes,{subset:true});}fonts.cjkCharacters||=new Set(fonts.cjk.getCharacterSet());for(const ch of text){if(ch!=='\n'&&!fonts.cjkCharacters.has(ch.codePointAt(0)))throw Error(`Annotation font does not contain ${ch}. Choose a supported character.`);}return fonts.cjk;}}
async function marks(out,page,p,fonts){for(const m of p.marks){const size=(m.size||3)/(p.box.userUnit||1),c=color(m.color);if(m.type==='pen'){for(let i=1;i<m.points.length;i++)page.drawLine({start:point(p,...m.points[i-1]),end:point(p,...m.points[i]),thickness:size,color:c,lineCap:L.LineCapStyle.Round});}else if(m.type==='rect'||m.type==='highlight'){page.drawRectangle({...point(p,m.x,m.y+m.h),width:m.w*p.logicalW/(p.box.userUnit||1),height:m.h*p.logicalH/(p.box.userUnit||1),rotate:L.degrees(p.rotation),...(m.type==='highlight'?{color:c,opacity:.3,borderWidth:0}:{borderColor:c,borderWidth:size})});}else if(m.type==='text'){const font=await fontFor(out,m.text||'',fonts),s=(m.size||20)/(p.box.userUnit||1);for(const [i,line] of (m.text||'').split('\n').entries())page.drawText(line,{...point(p,m.x,m.y+((m.size||20)*(.85+i*1.35))/p.logicalH),size:s,font,color:c,rotate:L.degrees(p.rotation)});}else if(m.type==='image'&&m.blob){const img=await out.embedPng(await m.blob.arrayBuffer());page.drawImage(img,{...point(p,m.x,m.y+m.h),width:m.w*p.logicalW/(p.box.userUnit||1),height:m.h*p.logicalH/(p.box.userUnit||1),rotate:L.degrees(p.rotation)});}}}
async function optimizeImages(doc,quality,maxSide,progress){let optimized=0,saved=0,skipped=[];const objects=doc.context.enumerateIndirectObjects();for(let i=0;i<objects.length;i++){const [ref,stream]=objects[i];if(!(stream instanceof L.PDFRawStream))continue;const d=stream.dict,get=k=>d.get(L.PDFName.of(k))?.toString();if(get('Subtype')!=='/Image'||get('Filter')!=='/DCTDecode'||get('ColorSpace')!=='/DeviceRGB'||get('BitsPerComponent')!=='8'||['SMask','Mask','Decode','DecodeParms'].some(k=>d.has(L.PDFName.of(k))))continue;let bitmap;try{const original=new Blob([stream.contents],{type:'image/jpeg'});let encoded;if(typeof OffscreenCanvas==='undefined')encoded=await encodeOnMain(original,maxSide,quality);else{bitmap=await createImageBitmap(original);const scale=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height)),c=new OffscreenCanvas(Math.max(1,Math.round(bitmap.width*scale)),Math.max(1,Math.round(bitmap.height*scale)));try{c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);encoded={blob:await c.convertToBlob({type:'image/jpeg',quality}),width:c.width,height:c.height};}finally{c.width=c.height=1;}}const {blob,width,height}=encoded;if(blob.size<stream.contents.length*.95){const dict=d.clone(doc.context);dict.set(L.PDFName.of('Width'),L.PDFNumber.of(width));dict.set(L.PDFName.of('Height'),L.PDFNumber.of(height));dict.set(L.PDFName.of('Length'),L.PDFNumber.of(blob.size));doc.context.assign(ref,L.PDFRawStream.of(dict,new Uint8Array(await blob.arrayBuffer())));saved+=stream.contents.length-blob.size;optimized++;}}catch(e){if(skipped.length<3)skipped.push(e.message);}finally{bitmap?.close();}progress(`Optimizing embedded images · ${i+1} / ${objects.length}`);await tick();}return {optimizedImages:optimized,imageBytesSaved:saved,skippedImageErrors:skipped};}
self.onmessage=async({data:{id,action,payload}})=>{if(action==='imageEncoded'){const request=imageRequests.get(payload.requestId);imageRequests.delete(payload.requestId);if(request)payload.error?request.reject(Error(payload.error)):request.resolve(payload);return;}activeJob=id;const progress=message=>postMessage({id,progress:message});try{let result;if(action==='add'){const doc=await load(payload);if(!doc.getPageCount())throw Error('The PDF has no pages.');let flattened=false;if(doc.getForm().getFields().length){doc.getForm().flatten();flattened=true;}const file=flattened?new Blob([await doc.save()],{type:'application/pdf'}):payload.file;result={pages:doc.getPages().map(metadata),file,flattened};}else if(action==='export'){const out=await L.PDFDocument.create(),fonts={},copied=new Map();for(const src of new Map(payload.pages.map(p=>[p.source.id,p.source])).values()){const indices=[...new Set(payload.pages.filter(p=>p.source.id===src.id).map(p=>p.index))],source=await load(src),pages=await out.copyPages(source,indices);indices.forEach((index,i)=>copied.set(src.id+':'+index,pages[i]));}for(let i=0;i<payload.pages.length;i++){const p=payload.pages[i],key=p.source.id+':'+p.index;let page=copied.get(key);if(page)copied.delete(key);else [page]=await out.copyPages(await load(p.source),[p.index]);out.addPage(page);page.setRotation(L.degrees((p.rotation+p.angle)%360));await marks(out,page,p,fonts);progress(`Writing PDF page ${i+1} / ${payload.pages.length}`);await tick();}let report={mode:payload.optimize?'preserve-compress':'preserve',pages:payload.pages.length,textPreserved:true,searchPreserved:true,vectorsPreserved:true};if(payload.optimize)Object.assign(report,await optimizeImages(out,payload.quality||.8,payload.maxSide||2400,progress));if(payload.removeMetadata){out.setTitle('');out.setAuthor('');out.setSubject('');out.setKeywords([]);out.setProducer('');out.setCreator('');}const blob=new Blob([await out.save({useObjectStreams:true})],{type:'application/pdf'});result={blob,report:{...report,outputBytes:blob.size}};}else if(action==='clear'){documents.clear();cjkBytes=null;result=true;}else throw Error('Unknown PDF operation.');postMessage({id,result});}catch(e){postMessage({id,error:e.message});}};

