import {t} from './i18n.js';
import {LIMITS,parsePages,fit,clamp} from './core.js';
import {canvas,blobOf,decode,release,script} from './image.js';
let dependencies;
async function libraries(){if(!dependencies)dependencies=(async()=>{await script('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js');const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.mjs';return {lib:window.PDFLib,pdfjs};})().catch(e=>{dependencies=null;throw Error(t("PDF 엔진을 불러오지 못했습니다. 인터넷 연결을 확인하세요. {0}", {0: e.message}));});return dependencies;}
export function drawMarks(ctx,marks,w,h,logicalW){const scale=w/logicalW;ctx.save();for(const m of marks){ctx.strokeStyle=m.color||'#172b4d';ctx.fillStyle=m.color||'#172b4d';ctx.lineWidth=(m.size||3)*scale;ctx.lineCap='round';ctx.lineJoin='round';if(m.type==='text'){ctx.font=`600 ${(m.size||20)*scale}px system-ui, sans-serif`;ctx.textBaseline='top';const lines=(m.text||'').split('\n');lines.forEach((t,i)=>ctx.fillText(t,m.x*w,m.y*h+i*(m.size||20)*1.35*scale));}else if(m.type==='pen'){ctx.beginPath();m.points.forEach(([x,y],i)=>i?ctx.lineTo(x*w,y*h):ctx.moveTo(x*w,y*h));ctx.stroke();}else if(m.type==='highlight'){ctx.globalAlpha=.3;ctx.fillRect(m.x*w,m.y*h,m.w*w,m.h*h);ctx.globalAlpha=1;}else if(m.type==='rect'){ctx.strokeRect(m.x*w,m.y*h,m.w*w,m.h*h);}else if(m.type==='image'&&m.image){ctx.drawImage(m.image,m.x*w,m.y*h,m.w*w,m.h*h);}}ctx.restore();}
export class PDFWorkspace{
 constructor(){this.pages=[];this.sources=[];this.selected=0;this.history=[];this.inputBytes=0;}
 snapshot(){this.history.push(this.pages.map(p=>({...p,marks:p.marks.map(m=>({...m,points:m.points?.map(p=>[...p])}))})));if(this.history.length>15)this.history.shift();}
 undo(){if(this.history.length){this.pages=this.history.pop();this.selected=clamp(this.selected,0,Math.max(0,this.pages.length-1));return true;}return false;}
 async add(files,progress=()=>{},signal){const {lib,pdfjs}=await libraries();for(const f of files){if(signal?.aborted)throw new DOMException(t("취소했습니다."),'AbortError');if(f.size>LIMITS.imageBytes||this.inputBytes+f.size>LIMITS.totalBytes)throw Error(t("PDF/이미지는 파일당 32MB, 총 128MB까지 열 수 있습니다."));progress(t("{0} 여는 중…", {0: f.name}));let raw;if(f.type==='application/pdf'||/\.pdf$/i.test(f.name)){raw=await f.arrayBuffer();}else{const image=await decode(f);try{const d=await lib.PDFDocument.create(),png=await d.embedPng(await (await blobOf(image)).arrayBuffer()),page=d.addPage([595.28,841.89]),r=fit(image.width,image.height,547.28,793.89);page.drawImage(png,{x:24+r.x,y:24+r.y,width:r.w,height:r.h});raw=await d.save();}finally{release(image);}}
 const writer=await lib.PDFDocument.load(raw,{updateMetadata:false});if(this.pages.length+writer.getPageCount()>LIMITS.pages)throw Error(t("저사양 보호: 한 작업은 100페이지 이하로 나누어 주세요."));if(!writer.getPageCount())throw Error(t("페이지가 없는 PDF입니다."));
 // Work on flattened field appearances; form interactivity/signatures are not preserved.
 try{if(writer.getForm().getFields().length){writer.getForm().flatten();raw=await writer.save();}}catch{throw Error(t("이 PDF의 양식은 안전하게 가져올 수 없습니다. 원본 PDF 뷰어에서 인쇄용 사본을 만든 뒤 사용하세요."));}
 const reader=await pdfjs.getDocument({data:new Uint8Array(raw).slice(),isEvalSupported:false,stopAtErrors:true}).promise,src={writer,reader,name:f.name};this.sources.push(src);this.snapshot();for(let i=0;i<writer.getPageCount();i++){const p=await reader.getPage(i+1),v=p.getViewport({scale:1});if(v.width>8192||v.height>8192||v.width*v.height>LIMITS.pixels)throw Error(t("비정상적으로 큰 PDF 페이지는 지원하지 않습니다."));this.pages.push({id:crypto.randomUUID(),source:src,index:i,angle:0,rotation:p.rotate,logicalW:v.width,logicalH:v.height,marks:[]});}this.inputBytes+=f.size;}}
 current(){return this.pages[this.selected];}
 move(delta){const i=this.selected,j=clamp(i+delta,0,this.pages.length-1);if(i===j)return;this.snapshot();const [p]=this.pages.splice(i,1);this.pages.splice(j,0,p);this.selected=j;}
 reorder(from,to){if(from===to||!this.pages[from]||!this.pages[to])return;this.snapshot();const[p]=this.pages.splice(from,1);this.pages.splice(to,0,p);this.selected=to;}
 rotate(){if(!this.current())return;this.snapshot();this.current().angle=(this.current().angle+90)%360;}
 duplicate(){if(!this.current()||this.pages.length>=LIMITS.pages)return;this.snapshot();const p=this.current();this.pages.splice(this.selected+1,0,{...p,id:crypto.randomUUID(),marks:p.marks.map(m=>({...m,points:m.points?.map(p=>[...p])}))});this.selected++;}
 remove(){if(!this.current())return;this.snapshot();this.pages.splice(this.selected,1);this.selected=Math.min(this.selected,Math.max(0,this.pages.length-1));}
 mark(m){if(!this.current())return;this.snapshot();this.current().marks.push(m);}
 async render(p=this.current(),max=1000,marks=true){if(!p)return null;const pg=await p.source.reader.getPage(p.index+1),v=pg.getViewport({scale:Math.min(2,max/Math.max(p.logicalW,p.logicalH))}),c=canvas(Math.max(1,Math.round(v.width)),Math.max(1,Math.round(v.height)));try{await pg.render({canvasContext:c.getContext('2d'),viewport:v,background:'#ffffff'}).promise;if(marks)drawMarks(c.getContext('2d'),p.marks,c.width,c.height,p.logicalW);if(!p.angle)return c;const out=canvas(p.angle%180?c.height:c.width,p.angle%180?c.width:c.height),ctx=out.getContext('2d');ctx.translate(out.width/2,out.height/2);ctx.rotate(p.angle*Math.PI/180);ctx.drawImage(c,-c.width/2,-c.height/2);release(c);return out;}catch(e){release(c);throw e;}}
 async export({range='',raster=false,quality=.75}={},progress=()=>{},signal){if(!this.pages.length)throw Error(t("PDF 파일을 먼저 추가하세요."));const {lib}=await libraries(),out=await lib.PDFDocument.create(),indices=parsePages(range,this.pages.length);for(let i=0;i<indices.length;i++){if(signal?.aborted)throw new DOMException(t("취소했습니다."),'AbortError');progress(t("{0} / {1}페이지 저장 중…", {0: i+1, 1: indices.length}));const p=this.pages[indices[i]];if(raster){const c=await this.render(p,1440);try{const img=await out.embedJpg(await (await blobOf(c,'image/jpeg',quality)).arrayBuffer()),w=p.angle%180?p.logicalH:p.logicalW,h=p.angle%180?p.logicalW:p.logicalH,page=out.addPage([w,h]);page.drawImage(img,{x:0,y:0,width:w,height:h});}finally{release(c);}}else{const [page]=await out.copyPages(p.source.writer,[p.index]);out.addPage(page);page.setRotation(lib.degrees((p.rotation+p.angle)%360));if(p.marks.length){const scale=Math.min(2,2048/Math.max(p.logicalW,p.logicalH)),c=canvas(Math.round(p.logicalW*scale),Math.round(p.logicalH*scale));try{drawMarks(c.getContext('2d'),p.marks,c.width,c.height,p.logicalW);const img=await out.embedPng(await (await blobOf(c)).arrayBuffer()),b=page.getCropBox(),r=((p.rotation%360)+360)%360;let x=b.x,y=b.y;if(r===90){x+=b.width;}else if(r===180){x+=b.width;y+=b.height;}else if(r===270){y+=b.height;}page.drawImage(img,{x,y,width:p.logicalW,height:p.logicalH,rotate:lib.degrees(r)});}finally{release(c);}}}await new Promise(r=>setTimeout(r,0));}return new Blob([await out.save({useObjectStreams:true})],{type:'application/pdf'});}
 async imageExports({range='',format='jpeg'}={},progress=()=>{},signal){const indices=parsePages(range,this.pages.length),entries=[];let total=0;for(let i=0;i<indices.length;i++){if(signal?.aborted)throw new DOMException(t("취소했습니다."),'AbortError');progress(t("{0} / {1}페이지 이미지 변환 중…", {0: i+1, 1: indices.length}));const c=await this.render(this.pages[indices[i]],1600);try{const blob=await blobOf(c,`image/${format}`,.9);total+=blob.size;if(total>LIMITS.totalBytes)throw Error(t("결과가 128MB를 넘습니다. 페이지 범위를 나누세요."));entries.push({name:`page-${String(indices[i]+1).padStart(3,'0')}.${format==='jpeg'?'jpg':format}`,blob});}finally{release(c);}}return entries;}
 async clear(){for(const src of this.sources)await src.reader.destroy();for(const p of this.pages)for(const m of p.marks)if(m.image)release(m.image);this.pages=[];this.sources=[];this.history=[];this.selected=0;this.inputBytes=0;}
}
