import {t} from './i18n.js';
import {LIMITS,parsePages,fit,clamp} from './core.js';
import {canvas,blobOf,decode,release,script} from './image.js';
import {PDFWorkerClient} from './pdf-rpc.js';
let dependencies;
async function libraries(){if(!dependencies)dependencies=Promise.all([import('../assets/vendor/pdf-lib-1.17.1/pdf-lib.esm.min.js'),import('../assets/vendor/pdfjs-dist-6.3.289/pdf.mjs')]).then(([lib,pdfjs])=>{pdfjs.GlobalWorkerOptions.workerSrc=new URL('../assets/vendor/pdfjs-dist-6.3.289/pdf.worker.mjs',import.meta.url).href;return {lib,pdfjs};}).catch(e=>{dependencies=null;throw e;});return dependencies;}
async function readerFor(file,pdfjs,signal){
 const initial=new Uint8Array(await file.slice(0,65536).arrayBuffer());let task;
 class Range extends pdfjs.PDFDataRangeTransport{constructor(){super(file.size,initial,true);this.closed=false;}requestDataRange(begin,end){file.slice(begin,end).arrayBuffer().then(bytes=>{if(!this.closed)this.onDataRange(begin,new Uint8Array(bytes));}).catch(()=>task?.destroy());}abort(){this.closed=true;}}
 task=pdfjs.getDocument({range:new Range(),disableAutoFetch:true,disableStream:true,isEvalSupported:false,stopAtErrors:true,cMapUrl:new URL('../assets/vendor/pdfjs-dist-6.3.289/cmaps/',import.meta.url).href,cMapPacked:true,standardFontDataUrl:new URL('../assets/vendor/pdfjs-dist-6.3.289/standard_fonts/',import.meta.url).href,wasmUrl:new URL('../assets/vendor/pdfjs-dist-6.3.289/wasm/',import.meta.url).href,iccUrl:new URL('../assets/vendor/pdfjs-dist-6.3.289/iccs/',import.meta.url).href});
 const abort=()=>task.destroy();signal?.addEventListener('abort',abort,{once:true});try{if(signal?.aborted)throw new DOMException('Canceled','AbortError');return await task.promise;}finally{signal?.removeEventListener('abort',abort);}
}
/** A rectangle in unrotated page fractions, expressed in the fractions of the rotated render. */
export function displayBox({x,y,w,h},angle=0){
 const a=((angle%360)+360)%360;
 return a===90?{x:1-y-h,y:x,w:h,h:w}:a===180?{x:1-x-w,y:1-y-h,w,h}:a===270?{x:y,y:1-x-w,w:h,h:w}:{x,y,w,h};
}
export function drawMarks(ctx,marks,w,h,logicalW){const scale=w/logicalW;ctx.save();for(const m of marks){ctx.strokeStyle=m.color||'#172b4d';ctx.fillStyle=m.color||'#172b4d';ctx.lineWidth=(m.size||3)*scale;ctx.lineCap='round';ctx.lineJoin='round';if(m.type==='redact'){ctx.fillStyle='#000000';ctx.fillRect(m.x*w,m.y*h,m.w*w,m.h*h);}else if(m.type==='fill'){ctx.globalAlpha=m.opacity??1;ctx.fillRect(m.x*w,m.y*h,m.w*w,m.h*h);ctx.globalAlpha=1;}else if(m.type==='ellipse'){ctx.beginPath();ctx.ellipse((m.x+m.w/2)*w,(m.y+m.h/2)*h,Math.abs(m.w*w/2),Math.abs(m.h*h/2),0,0,Math.PI*2);if(m.fill){ctx.fillStyle=m.fill;ctx.fill();}ctx.stroke();}else if(m.type==='line'){const ax=m.x*w,ay=m.y*h,bx=(m.x+m.w)*w,by=(m.y+m.h)*h;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);if(m.arrow){const ang=Math.atan2(by-ay,bx-ax),len=Math.max(8,(m.size||3)*4)*scale;for(const d of [-.45,.45]){ctx.moveTo(bx,by);ctx.lineTo(bx-len*Math.cos(ang+d),by-len*Math.sin(ang+d));}}ctx.stroke();}else if(m.type==='text'){ctx.font=`${m.bold?700:400} ${(m.size||20)*scale}px Helvetica, Arial, system-ui, sans-serif`;ctx.textBaseline='top';const lines=(m.text||'').split('\n');ctx.save();ctx.globalAlpha=m.opacity??1;ctx.translate(m.x*w,m.y*h+(m.size||20)*.85*scale);ctx.rotate((m.angle||0)*Math.PI/180);lines.forEach((t,i)=>ctx.fillText(t,0,(i*1.35-.85)*(m.size||20)*scale));ctx.restore();}else if(m.type==='pen'){ctx.beginPath();m.points.forEach(([x,y],i)=>i?ctx.lineTo(x*w,y*h):ctx.moveTo(x*w,y*h));ctx.stroke();}else if(m.type==='highlight'){ctx.globalAlpha=.3;ctx.fillRect(m.x*w,m.y*h,m.w*w,m.h*h);ctx.globalAlpha=1;}else if(m.type==='rect'){ctx.strokeRect(m.x*w,m.y*h,m.w*w,m.h*h);}else if(m.type==='image'&&m.image){ctx.drawImage(m.image,m.x*w,m.y*h,m.w*w,m.h*h);}}ctx.restore();}
export class PDFWorkspace{
 constructor(){this.pages=[];this.sources=[];this.selected=0;this.history=[];this.inputBytes=0;this.worker=new PDFWorkerClient();this.lastReport=null;}
 snapshot(){this.history.push(this.pages.map(p=>({...p,marks:p.marks.map(m=>({...m,points:m.points?.map(p=>[...p])}))})));if(this.history.length>15)this.history.shift();}
 undo(){if(this.history.length){this.pages=this.history.pop();this.selected=clamp(this.selected,0,Math.max(0,this.pages.length-1));return true;}return false;}
 async add(files,progress=()=>{},signal,{keepForms=false}={}){const {lib,pdfjs}=await libraries();for(const f of files){if(signal?.aborted)throw new DOMException('Canceled','AbortError');progress(`Opening ${f.name}`);let file=f;
 if(!(f.type==='application/pdf'||/\.pdf$/i.test(f.name))){const image=await decode(f);try{const d=await lib.PDFDocument.create(),png=await d.embedPng(await (await blobOf(image)).arrayBuffer()),page=d.addPage([595.28,841.89]),r=fit(image.width,image.height,547.28,793.89);page.drawImage(png,{x:24+r.x,y:24+r.y,width:r.w,height:r.h});file=new Blob([await d.save()],{type:'application/pdf'});}finally{release(image);}}
 const id=crypto.randomUUID(),result=await this.worker.run('add',{id,file,keepForms},progress,signal),reader=await readerFor(result.file,pdfjs,signal),src={id,file:result.file,reader,name:f.name,flattened:result.flattened,fields:result.fields||[]};this.snapshot();this.sources.push(src);
 for(let i=0;i<result.pages.length;i++){const box=result.pages[i];this.pages.push({id:crypto.randomUUID(),source:src,index:i,angle:0,rotation:box.rotation,logicalW:box.logicalW,logicalH:box.logicalH,box,marks:[]});}this.inputBytes+=f.size;}}
 current(){return this.pages[this.selected];}
 move(delta){const i=this.selected,j=clamp(i+delta,0,this.pages.length-1);if(i===j)return;this.snapshot();const [p]=this.pages.splice(i,1);this.pages.splice(j,0,p);this.selected=j;}
 reorder(from,to){if(from===to||!this.pages[from]||!this.pages[to])return;this.snapshot();const[p]=this.pages.splice(from,1);this.pages.splice(to,0,p);this.selected=to;}
 rotate(){if(!this.current())return;this.snapshot();this.current().angle=(this.current().angle+90)%360;}
 duplicate(){if(!this.current())return;this.snapshot();const p=this.current();this.pages.splice(this.selected+1,0,{...p,id:crypto.randomUUID(),marks:p.marks.map(m=>({...m,points:m.points?.map(p=>[...p])}))});this.selected++;}
 remove(){if(!this.current())return;this.snapshot();this.pages.splice(this.selected,1);this.selected=Math.min(this.selected,Math.max(0,this.pages.length-1));}
 mark(m){if(!this.current())return;this.snapshot();this.current().marks.push(m);}
 async render(p=this.current(),max=1000,marks=true,signal){if(!p)return null;const pg=await p.source.reader.getPage(p.index+1),v=pg.getViewport({scale:max/Math.max(p.logicalW,p.logicalH)}),c=canvas(Math.max(1,Math.round(v.width)),Math.max(1,Math.round(v.height)));try{const task=pg.render({canvasContext:c.getContext('2d'),viewport:v,background:'#ffffff'}),abort=()=>task.cancel();signal?.addEventListener('abort',abort,{once:true});try{if(signal?.aborted)abort();await task.promise;}finally{signal?.removeEventListener('abort',abort);pg.cleanup();}if(marks)drawMarks(c.getContext('2d'),p.marks,c.width,c.height,p.logicalW);if(!p.angle)return c;const out=canvas(p.angle%180?c.height:c.width,p.angle%180?c.width:c.height),ctx=out.getContext('2d');ctx.translate(out.width/2,out.height/2);ctx.rotate(p.angle*Math.PI/180);ctx.drawImage(c,-c.width/2,-c.height/2);release(c);return out;}catch(e){release(c);throw e;}}
 async export({range='',raster=false,optimize=false,quality=.8,maxSide=2400,dpi=144,grayscale=false,grayLimits=null,removeMetadata=false,fields=null,flatten=false}={},progress=()=>{},signal){if(!this.pages.length)throw Error(t("PDF 파일을 먼저 추가하세요."));const indices=parsePages(range,this.pages.length);
 if(!raster){const pages=[];for(const index of indices){const p=this.pages[index],marks=[];for(const m of p.marks){const copy={...m};delete copy.image;if(m.image)copy.blob=await blobOf(m.image);marks.push(copy);}
  // A page carrying a redaction is rendered here, with the black boxes already burnt in, so the
  // worker never sees the content underneath them. Only those pages lose their native objects.
  let flatten,flattenSize;
  if(p.marks.some(m=>m.type==='redact')){
   progress(t("{0} / {1}페이지 이미지 변환 중…",{0:pages.length+1,1:indices.length}));
   const c=await this.render(p,Math.max(1400,maxSide),true,signal),rotW=p.angle%180?p.logicalH:p.logicalW,rotH=p.angle%180?p.logicalW:p.logicalH;
   let out=c;
   try{
    if(p.crop){const box=displayBox(p.crop,p.angle);out=canvas(Math.max(1,Math.round(c.width*box.w)),Math.max(1,Math.round(c.height*box.h)));
     out.getContext('2d').drawImage(c,box.x*c.width,box.y*c.height,box.w*c.width,box.h*c.height,0,0,out.width,out.height);
     flattenSize={width:rotW*box.w,height:rotH*box.h};}
    else flattenSize={width:rotW,height:rotH};
    flatten=await blobOf(out,'image/jpeg',Math.max(.72,quality));
   }finally{if(out!==c)release(out);release(c);}
  }
  pages.push({...p,source:{id:p.source.id,file:p.source.file},marks,thumb:undefined,flatten,flattenSize});}
 const result=await this.worker.run('export',{pages,optimize,quality,maxSide,dpi,grayscale,grayLimits,removeMetadata,fields,flatten},progress,signal);this.lastReport={...result.report,originalBytes:this.inputBytes,formsFlattened:this.sources.some(s=>s.flattened),signaturesPreserved:false};return result.blob;}
 const {lib}=await libraries(),out=await lib.PDFDocument.create();for(let i=0;i<indices.length;i++){if(signal?.aborted)throw new DOMException('Canceled','AbortError');progress(`Rasterizing page ${i+1} / ${indices.length}`);const p=this.pages[indices[i]],c=await this.render(p,maxSide,true,signal);try{const img=await out.embedJpg(await (await blobOf(c,'image/jpeg',quality)).arrayBuffer()),page=out.addPage([p.angle%180?p.logicalH:p.logicalW,p.angle%180?p.logicalW:p.logicalH]);page.drawImage(img,{x:0,y:0,width:page.getWidth(),height:page.getHeight()});}finally{release(c);}await new Promise(r=>setTimeout(r,0));}
 const blob=new Blob([await out.save({useObjectStreams:true,updateMetadata:!removeMetadata})],{type:'application/pdf'});this.lastReport={mode:'raster',pages:indices.length,textPreserved:false,searchPreserved:false,vectorsPreserved:false,outputBytes:blob.size,originalBytes:this.inputBytes};return blob;}
 async split({mode='each',every=1,groups='',...options}={},progress=()=>{},signal){const n=this.pages.length,ranges=mode==='groups'?groups.split(';').map(s=>s.trim()).filter(Boolean):mode==='odd-even'?[Array.from({length:Math.ceil(n/2)},(_,i)=>i*2+1).join(','),Array.from({length:Math.floor(n/2)},(_,i)=>i*2+2).join(',')].filter(Boolean):Array.from({length:Math.ceil(n/Math.max(1,Math.floor(every)))},(_,i)=>{const a=i*Math.max(1,Math.floor(every))+1;return `${a}-${Math.min(n,a+Math.max(1,Math.floor(every))-1)}`;});if(!ranges.length)throw Error('Enter page groups separated by semicolons.');const entries=[];for(let i=0;i<ranges.length;i++){const blob=await this.export({...options,range:ranges[i]},progress,signal);entries.push({name:`part-${String(i+1).padStart(3,'0')}.pdf`,blob});}return entries;}
 async imageExports({range='',format='jpeg',maxSide=2400}={},progress=()=>{},signal){const indices=parsePages(range,this.pages.length),entries=[];let total=0;for(let i=0;i<indices.length;i++){if(signal?.aborted)throw new DOMException(t("취소했습니다."),'AbortError');progress(t("{0} / {1}페이지 이미지 변환 중…", {0: i+1, 1: indices.length}));const c=await this.render(this.pages[indices[i]],maxSide,true,signal);try{const blob=await blobOf(c,`image/${format}`,.9);total+=blob.size;entries.push({name:`page-${String(indices[i]+1).padStart(3,'0')}.${format==='jpeg'?'jpg':format}`,blob});}finally{release(c);}}return entries;}
 async clear(){this.worker.close();await Promise.allSettled(this.sources.map(s=>s.reader.loadingTask.destroy()));const images=new Set([...this.pages,...this.history.flat()].flatMap(p=>p.marks.map(m=>m.image)).filter(Boolean));for(const image of images)release(image);this.pages=[];this.sources=[];this.history=[];this.selected=0;this.inputBytes=0;}
}

