import {labels,footer} from './content.js';
import {esc} from './ui.js';
export const POLICY_ROUTES=['about','privacy','terms','contact'];
export const ISSUES_URL='https://github.com/2009seungbin-stack/my-first-repo/issues';
export const policies={
 en:{
 about:[['A small workspace for your files','FileForge is a browser-based collection of file tools. It aims to make common edits simple without accounts or a file-upload workflow. Selected images, PDFs and media are processed on your device.'],['Four editors','Image Editor crops, resizes, converts and removes backgrounds. PDF Editor combines and rearranges pages and adds visual annotations. Pixelize produces small PNG assets. Media Editor extracts frames, GIFs and audio and records short WebM clips.'],['Practical limits','Ordinary enlargement uses resampling, not AI restoration. Experimental portrait removal downloads an AI model and runs it locally. Browser codecs, device memory and source files affect what works. See each tool’s guide before exporting.']],
 privacy:[['Your selected files','FileForge has no API for uploading your selected images, PDFs, video or audio to a FileForge server. The application reads files in browser memory and generates downloads locally. It does not create an account or save your editing project on a server. Reloading or closing the tab clears the in-memory workspace.'],['Requests beyond your device','Opening the site sends ordinary web requests to the hosting provider, which can process IP addresses, request URLs and browser information for delivery and security. Optional PDF, HEIC and MP3 engines download from jsDelivr. Portrait removal downloads Transformers.js and model/runtime files from jsDelivr and Hugging Face, including their delivery domains. Providers receive connection information; saying that no data ever leaves your device would be inaccurate. Selected file bytes are not sent by FileForge’s application code.'],['Device storage','Your manually chosen language is stored under fileforge.language.v1 in localStorage. Automatic mode removes that preference. Browser caches and model libraries may retain downloaded libraries or models; browser site-data controls can clear them. Files and results are not intentionally persisted as an editing project.'],['Analytics and advertising','This repository includes no analytics tracker. The advertising status of this build is stated below. When the operator enables Google AdSense, Google and its partners can make network requests and use cookies or similar storage for advertising, measurement and fraud prevention, subject to applicable consent settings. Advertising does not require uploading the file you edit. The operator must configure Google Privacy & Messaging or a Google-certified CMP where required; this site does not imitate a certified consent system.'],['Questions and public reports','Use the Contact page for the public GitHub Issues channel. Do not post private documents, personal information or confidential screenshots. GitHub handles information you submit there under its own policies.']],
 terms:[['Use and responsibility','Use files you own or have permission to process. You remain responsible for your input and how you use the output. FileForge is provided as available, without a promise of uninterrupted operation or accurate, complete results. Nothing here limits rights that cannot be excluded under applicable law.'],['Always keep originals','Keep a backup and inspect the exported file before relying on it. Image compression and conversion may lose detail, transparency, animation, metadata or color information. Canvas enlargement cannot recover missing detail. Solid background removal and experimental portrait AI may remove parts of a subject or leave unwanted pixels.'],['PDF limitations','PDF tools work with pages and visual overlays, not existing text editing, OCR, secure redaction or certificate signatures. Forms may be flattened and signatures are not preserved. Drawing over text is not secure deletion. Image-based PDF output loses text selection and search; confirm readability and page order after export.'],['Media and device limits','Media support depends on browser codecs. Video export records WebM in real time and is not a frame-accurate or lossless cut. Audio/GIF output can lose quality and files may grow. Memory limits and interrupted downloads can cause failure. No target file size or processing speed is guaranteed.'],['Third-party components','Optional engines and models have their own licenses and availability. Advertising, if enabled, is separate from editing and never a condition of downloading your result. Contact the project through the Contact page to report reproducible problems.']],
 contact:[['Report a problem or suggest an improvement','The public FileForge repository accepts GitHub Issues. Reading reports is public; creating an issue generally requires a GitHub account. This is a public support channel, not a private document-transfer service.'],['What to include','Describe the tool URL, browser/version, expected result and steps to reproduce. Include a non-sensitive sample only if you have permission to publish it. Never post personal files, passwords or confidential documents.'],['Response expectations','No response time is promised. No support email address has been supplied for this project. Use the verified issue channel below.']]
 },
 ko:{
 about:[['내 파일을 위한 작은 작업실','FileForge는 브라우저에서 쓰는 파일 도구 모음입니다. 계정이나 파일 업로드 절차 없이 자주 하는 편집을 단순하게 만드는 것이 목적입니다. 선택한 이미지·PDF·미디어는 사용자 기기에서 처리합니다.'],['네 가지 편집기','이미지 편집기는 자르기·크기 변경·변환·배경 제거를 제공합니다. PDF 편집기는 페이지를 합치고 정리하며 시각적 주석을 추가합니다. 도트화는 작은 PNG 에셋을 만들고, 미디어 편집기는 프레임·GIF·오디오 추출과 짧은 WebM 녹화를 지원합니다.'],['현실적인 기능 범위','일반 확대는 AI 복원이 아닌 리샘플링입니다. 실험적 인물 제거만 AI 모델을 내려받아 기기에서 실행합니다. 브라우저 코덱, 메모리, 원본 파일에 따라 동작이 달라지므로 각 도구의 안내를 확인하세요.']],
 privacy:[['선택한 파일의 처리','FileForge에는 선택한 이미지·PDF·영상·음성을 FileForge 서버에 올리는 API가 없습니다. 브라우저 메모리에서 파일을 읽고 기기에서 다운로드 결과를 만듭니다. 계정을 만들거나 편집 프로젝트를 서버에 저장하지 않습니다. 새로고침하거나 탭을 닫으면 메모리의 작업이 사라집니다.'],['외부 네트워크 요청','사이트 접속 시 호스팅 제공자에게 일반적인 웹 요청이 전송됩니다. 제공자는 전송·보안을 위해 IP 주소, 요청 URL, 브라우저 정보 등을 처리할 수 있습니다. PDF·HEIC·MP3 엔진은 jsDelivr에서, 인물 제거용 Transformers.js와 모델·실행 파일은 jsDelivr 및 Hugging Face와 관련 배포 도메인에서 내려받습니다. 이때 연결 정보가 전달되므로 어떤 데이터도 인터넷으로 나가지 않는다고 할 수는 없습니다. FileForge 애플리케이션 코드는 선택한 파일 내용 자체를 전송하지 않습니다.'],['기기 내 저장','직접 선택한 언어를 localStorage의 fileforge.language.v1에 저장합니다. 자동 감지를 선택하면 이 설정을 지웁니다. 브라우저 캐시나 모델 라이브러리가 내려받은 엔진·모델을 보관할 수 있으며 브라우저의 사이트 데이터 삭제로 정리할 수 있습니다. 파일과 결과를 편집 프로젝트로 영구 저장하지는 않습니다.'],['분석과 광고','이 저장소에는 분석 추적기가 없습니다. 현재 빌드의 광고 상태는 아래에 표시합니다. 운영자가 Google AdSense를 켜면 Google과 파트너가 적용되는 동의 설정에 따라 광고·측정·부정행위 방지를 위한 네트워크 요청과 쿠키 또는 유사 저장소를 사용할 수 있습니다. 광고에 편집 중인 파일 업로드가 필요한 것은 아닙니다. 운영자는 필요한 지역에 Google Privacy & Messaging 또는 Google 인증 CMP를 구성해야 하며, 이 사이트는 인증 동의 시스템을 흉내 내지 않습니다.'],['문의와 공개 제보','문의 페이지의 GitHub Issues는 공개 채널입니다. 개인 문서·개인정보·비밀 화면을 올리지 마세요. GitHub에 직접 제출한 정보에는 GitHub의 정책이 적용됩니다.']],
 terms:[['이용과 책임','소유하거나 처리 권한이 있는 파일을 사용하세요. 입력 파일과 결과 사용에 대한 책임은 사용자에게 있습니다. FileForge는 제공 가능한 상태로 제공되며 중단 없는 동작이나 결과의 정확성·완전성을 보장하지 않습니다. 적용 법률상 배제할 수 없는 권리를 제한하지 않습니다.'],['원본 보관과 결과 확인','백업을 보관하고 결과를 사용하기 전에 내보낸 파일을 확인하세요. 이미지 압축·변환은 세부 묘사, 투명도, 애니메이션, 메타데이터, 색상 정보를 잃을 수 있습니다. 일반 확대는 사라진 정보를 복원하지 않으며 배경 제거와 실험적 인물 AI는 피사체 일부를 지우거나 배경을 남길 수 있습니다.'],['PDF 제한','페이지와 시각적 덧붙이기를 편집하며 기존 본문 수정·OCR·보안 마스킹·인증서 서명은 지원하지 않습니다. 양식이 평면화되고 서명은 보존되지 않습니다. 글자 위를 덮는 것은 보안 삭제가 아닙니다. 이미지 기반 출력은 글자 선택·검색을 잃으므로 가독성과 페이지 순서를 다시 확인하세요.'],['미디어와 기기 제한','코덱 지원은 브라우저에 따라 다릅니다. 영상은 실시간 WebM 녹화이며 정밀한 프레임 컷이나 무손실 처리가 아닙니다. 음성·GIF도 품질 손실이나 용량 증가가 가능합니다. 메모리 한계나 다운로드 중단으로 실패할 수 있으며 목표 용량이나 처리 속도를 보장하지 않습니다.'],['외부 구성 요소','선택 기능의 엔진·모델에는 별도 라이선스와 제공 조건이 있습니다. 광고가 켜져도 편집과 분리되며 결과 다운로드의 조건이 되지 않습니다. 재현 가능한 문제는 문의 페이지를 통해 알려주세요.']],
 contact:[['문제 제보와 개선 제안','FileForge 공개 저장소의 GitHub Issues를 사용합니다. 제보는 공개되며 새 이슈 작성에는 일반적으로 GitHub 계정이 필요합니다. 비공개 문서를 전달하는 채널이 아닙니다.'],['알려주시면 좋은 정보','도구 URL, 브라우저와 버전, 기대한 결과, 재현 순서를 적어 주세요. 공개 권한이 있는 비민감 샘플만 첨부하고 개인 파일·비밀번호·기밀 문서는 올리지 마세요.'],['응답 안내','응답 기한은 보장하지 않습니다. 프로젝트에 별도 지원 이메일은 제공되지 않았으므로 아래 이슈 채널을 이용해 주세요.']]
 },
 ja:{
 about:[['ファイルのための小さな作業場','FileForgeはブラウザで使えるファイルツール集です。アカウント登録やアップロードの手間をかけず、よくある編集を簡単にすることを目指しています。選択した画像・PDF・メディアは端末で処理します。'],['4つの編集ツール','画像エディターは切り抜き・サイズ変更・変換・背景削除、PDFエディターはページ結合・整理・見た目の注釈、ピクセル化は小さなPNG素材の作成に対応します。メディアエディターではフレーム・GIF・音声の抽出と短いWebM録画ができます。'],['機能の範囲','通常の拡大はAI復元ではなく補間処理です。実験的な人物切り抜きはAIモデルを取得して端末で実行します。コーデック、メモリ、元ファイルで結果が変わるため、各ツールの説明を確認してください。']],
 privacy:[['選択したファイル','FileForgeには画像・PDF・動画・音声をFileForgeサーバーへ送るAPIはありません。ブラウザのメモリで読み込み、端末で保存用ファイルを作ります。アカウントやサーバー上の編集プロジェクトは作りません。再読み込みやタブを閉じる操作でメモリ上の作業は消えます。'],['外部への通信','サイトへのアクセスではホスティング事業者に通常のウェブリクエストを送ります。配信や安全確保のため、IPアドレス、リクエストURL、ブラウザ情報などが処理される場合があります。PDF・HEIC・MP3のエンジンはjsDelivrから、人物用のTransformers.jsやモデル・実行ファイルはjsDelivrとHugging Faceおよび関連配信ドメインから取得します。接続情報が伝わるため、データが一切外部へ出ないとはいえません。FileForgeのアプリケーションコードは選択したファイルの内容自体を送信しません。'],['端末への保存','手動で選んだ言語をlocalStorageのfileforge.language.v1に保存します。自動検出に戻すと削除します。ブラウザキャッシュやモデルライブラリが取得済みデータを保持する場合があり、ブラウザのサイトデータ設定で消去できます。ファイルや編集結果を永続的なプロジェクトとして保存することはありません。'],['解析と広告','このリポジトリに解析トラッカーは含まれません。このビルドの広告状態は下に表示します。運営者がGoogle AdSenseを有効にすると、同意設定に従い、Googleとパートナーが広告・測定・不正防止の通信やCookieなどを使用する場合があります。広告のために編集中のファイルをアップロードする必要はありません。必要な地域では運営者がGoogle Privacy & MessagingまたはGoogle認定CMPを設定する必要があります。このサイトは認定同意システムを模倣しません。'],['お問い合わせと公開報告','お問い合わせページのGitHub Issuesは公開窓口です。個人文書、個人情報、機密画面を投稿しないでください。GitHubへ直接送信した情報には同社のポリシーが適用されます。']],
 terms:[['利用と責任','所有するか処理する権限のあるファイルを使用してください。入力と出力の利用は利用者の責任です。FileForgeは提供可能な状態で提供され、中断のない動作や結果の正確性・完全性を保証しません。適用法上排除できない権利は制限しません。'],['元ファイルの保管','バックアップを保管し、出力ファイルを確認してから利用してください。画像の圧縮・変換で細部、透明度、アニメーション、メタデータ、色情報が失われる場合があります。通常の拡大は欠けた情報を復元しません。背景削除や実験的な人物AIは被写体を消したり背景を残したりする場合があります。'],['PDFの制限','ページと見た目の重ね合わせを編集します。既存本文の編集、OCR、安全な墨消し、証明書署名は非対応です。フォームは平面化される場合があり、署名は保持しません。文字を覆っても安全な削除にはなりません。画像化すると文字選択・検索を失うため、読みやすさとページ順を確認してください。'],['メディアと端末の制限','コーデック対応はブラウザ次第です。動画は実時間のWebM録画で、精密なフレーム編集や無劣化処理ではありません。音声・GIFも画質や音質の劣化、容量増加が起こり得ます。メモリ制限や取得中断で失敗する場合があり、目標容量や処理速度を保証しません。'],['外部コンポーネント','追加エンジンやモデルにはそれぞれライセンスと提供条件があります。広告を有効にしても編集とは分離され、結果の保存条件にはなりません。再現できる問題はお問い合わせページから報告してください。']],
 contact:[['不具合の報告・改善の提案','FileForgeの公開リポジトリにあるGitHub Issuesをご利用ください。投稿は公開され、新しいIssueの作成には通常GitHubアカウントが必要です。非公開文書の送付窓口ではありません。'],['お知らせいただきたいこと','ツールのURL、ブラウザとバージョン、期待した結果、再現手順を記載してください。公開権限のある機密性のないサンプルだけを添付し、個人ファイル・パスワード・機密文書は投稿しないでください。'],['返信について','返信までの時間は保証しません。このプロジェクトには別のサポートメールアドレスが提供されていないため、下のIssue窓口をご利用ください。']]
 }
};
export function policyContent(page,locale,ads=false){
 const l=labels[locale];
 const status=ads?{en:'Google AdSense is enabled in this build. Ad delivery depends on account approval, configured units and consent.',ko:'이 빌드에는 Google AdSense가 활성화되어 있습니다. 실제 노출은 계정 승인·광고 단위·동의 설정에 따라 달라집니다.',ja:'このビルドではGoogle AdSenseが有効です。配信はアカウント承認、広告枠、同意設定によります。'}:{en:'Google AdSense is disabled in this build. No Google advertising script or ad units are loaded.',ko:'이 빌드에서는 Google AdSense가 비활성화되어 광고 스크립트와 광고 단위를 불러오지 않습니다.',ja:'このビルドではGoogle AdSenseが無効で、Google広告スクリプトや広告枠は読み込みません。'};
 return `<a class="policy-home" href="${locale}/">← ${esc(l.home)}</a><h1>${esc(l[page])}</h1>${policies[locale][page].map(([h,p])=>`<section><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('')}${page==='privacy'?`<p class="ad-status">${esc(status[locale])}</p><p><a href="https://policies.google.com/technologies/ads" rel="noopener" target="_blank">Google · ${esc(l.privacy)}</a></p>`:''}${page==='contact'?`<p><a href="${ISSUES_URL}" target="_blank" rel="noopener">GitHub Issues ↗</a></p>`:''}`;
}
export {footer};
