import {brandCopy} from './brand.js';
import {labels,footer} from './content.js';
import {esc} from './ui.js';
export const POLICY_ROUTES=['about','privacy','terms','contact'];
export const ISSUES_URL='https://github.com/2009seungbin-stack/my-first-repo/issues';
export const policies=brandCopy({
 en:{
 about:[['A small workspace for your files','{brand} is a browser-based collection of file tools. It aims to make common edits simple without accounts or a file-upload workflow. Selected images, PDFs and media are processed on your device.'],['Four editors','Image Editor crops, resizes, converts and removes backgrounds. PDF Editor combines and rearranges pages and adds visual annotations. Pixelize produces small PNG assets. Media Editor extracts frames, GIFs and audio and exports MP4/WebM clips when the required codecs are available.'],['Practical limits','Ordinary enlargement uses resampling, not AI restoration. Experimental super-resolution and general background removal download models and run locally. Browser codecs, device memory and source files affect what works. See each tool’s guide before exporting.']],
 privacy:[['Your selected files','{brand} has no API for uploading your selected images, PDFs, video or audio to a {brand} server. The application reads files in browser memory and generates downloads locally. It does not create an account or save your editing project on a server. Reloading or closing the tab clears the in-memory workspace.'],['Requests beyond your device','Opening the site sends ordinary web requests to the hosting provider, which can process IP addresses, request URLs and browser information for delivery and security. Pinned PDF and media engines are served by this site on demand. HEIC, annotation fonts, ONNX Runtime and public AI weights may download from jsDelivr and Hugging Face, including their delivery domains. Providers receive connection information; saying that no data ever leaves your device would be inaccurate. Selected file bytes are not sent by {brand}’s application code.'],['Device storage','Your manually chosen language is stored under fileforge.language.v1 in localStorage. Automatic mode removes that preference. Favorite tool IDs and the three most recent tool IDs are stored under fileforge.tools.v1; this does not include filenames or file contents. Browser caches and model libraries may retain downloaded libraries or models; browser site-data controls can clear them. Editing projects are not saved. When you drop files on the home page or continue from one tool to another, the files are parked in this browser’s IndexedDB (nerulio-handoff) so the next page can open them; they are deleted as soon as that page takes them, or ignored after two minutes, and are never uploaded. Media output may be written to origin-private temporary storage on this device. Discarding results removes it; interrupted jobs can remain until browser site data is cleared, or until cleanup of files older than seven days on the next media use.'],['Analytics and advertising','Analytics is off by default. A configured adapter can receive allowlisted tool events, language, device class and a coarse traffic-source category; filenames and file contents are excluded. The advertising status of this build is stated below. When the operator enables Google AdSense, Google and its partners can make network requests and use cookies or similar storage for advertising, measurement and fraud prevention, subject to applicable consent settings. Advertising does not require uploading the file you edit. The operator must configure Google Privacy & Messaging or a Google-certified CMP where required; this site does not imitate a certified consent system.'],['Questions and public reports','Use the Contact page for the public GitHub Issues channel. Do not post private documents, personal information or confidential screenshots. GitHub handles information you submit there under its own policies.']],
 terms:[['Use and responsibility','Use files you own or have permission to process. You remain responsible for your input and how you use the output. {brand} is provided as available, without a promise of uninterrupted operation or accurate, complete results. Nothing here limits rights that cannot be excluded under applicable law.'],['Always keep originals','Keep a backup and inspect the exported file before relying on it. Image compression and conversion may lose detail, transparency, animation, metadata or color information. Canvas enlargement cannot recover missing detail. Solid background removal and experimental portrait AI may remove parts of a subject or leave unwanted pixels.'],['PDF limitations','PDF tools work with pages and visual overlays, not existing text editing, OCR, secure redaction or certificate signatures. Forms may be flattened and signatures are not preserved. Drawing over text is not secure deletion. Image-based PDF output loses text selection and search; confirm readability and page order after export.'],['Media and device limits','Media support depends on browser codecs. Fast cut remuxes at inner keyframes; precise mode re-encodes. The separately selected compatibility mode records in real time. Audio/GIF output can lose quality and files may grow. Memory limits and interrupted downloads can cause failure. No target file size or processing speed is guaranteed.'],['Third-party components','Optional engines and models have their own licenses and availability. Advertising, if enabled, is separate from editing and never a condition of downloading your result. Contact the project through the Contact page to report reproducible problems.']],
 contact:[['Report a problem or suggest an improvement','The public {brand} repository accepts GitHub Issues. Reading reports is public; creating an issue generally requires a GitHub account. This is a public support channel, not a private document-transfer service.'],['What to include','Describe the tool URL, browser/version, expected result and steps to reproduce. Include a non-sensitive sample only if you have permission to publish it. Never post personal files, passwords or confidential documents.'],['Response expectations','No response time is promised. No support email address has been supplied for this project. Use the verified issue channel below.']]
 },
 ko:{
 about:[['내 파일을 위한 작은 작업실','{brand}는 브라우저에서 쓰는 파일 도구 모음입니다. 계정이나 파일 업로드 절차 없이 자주 하는 편집을 단순하게 만드는 것이 목적입니다. 선택한 이미지·PDF·미디어는 사용자 기기에서 처리합니다.'],['네 가지 편집기','이미지 편집기는 자르기·크기 변경·변환·배경 제거를 제공합니다. PDF 편집기는 페이지를 합치고 정리하며 시각적 주석을 추가합니다. 도트화는 작은 PNG 에셋을 만들고, 미디어 편집기는 프레임·GIF·오디오 추출과 지원 코덱에 따른 MP4·WebM 내보내기를 지원합니다.'],['현실적인 기능 범위','일반 확대는 AI 복원이 아닌 리샘플링입니다. 실험적 초해상도·일반 배경 제거는 모델을 내려받아 기기에서 실행합니다. 브라우저 코덱, 메모리, 원본 파일에 따라 동작이 달라지므로 각 도구의 안내를 확인하세요.']],
 privacy:[['선택한 파일의 처리','{brand}에는 선택한 이미지·PDF·영상·음성을 {brand} 서버에 올리는 API가 없습니다. 브라우저 메모리에서 파일을 읽고 기기에서 다운로드 결과를 만듭니다. 계정을 만들거나 편집 프로젝트를 서버에 저장하지 않습니다. 새로고침하거나 탭을 닫으면 메모리의 작업이 사라집니다.'],['외부 네트워크 요청','사이트 접속 시 호스팅 제공자에게 일반적인 웹 요청이 전송됩니다. 제공자는 전송·보안을 위해 IP 주소, 요청 URL, 브라우저 정보 등을 처리할 수 있습니다. 고정 버전의 PDF·미디어 엔진은 이 사이트에서 필요할 때 내려받습니다. HEIC·주석 글꼴·ONNX Runtime·공개 AI 가중치는 jsDelivr·Hugging Face 및 관련 배포 도메인에서 받을 수 있습니다. 이때 연결 정보가 전달되므로 어떤 데이터도 인터넷으로 나가지 않는다고 할 수는 없습니다. {brand} 애플리케이션 코드는 선택한 파일 내용 자체를 전송하지 않습니다.'],['기기 내 저장','직접 선택한 언어를 localStorage의 fileforge.language.v1에 저장합니다. 자동 감지를 선택하면 이 설정을 지웁니다. 즐겨찾기 도구 ID와 최근 도구 ID 3개는 fileforge.tools.v1에 저장하며 파일명이나 파일 내용은 포함하지 않습니다. 브라우저 캐시나 모델 라이브러리가 내려받은 엔진·모델을 보관할 수 있으며 브라우저의 사이트 데이터 삭제로 정리할 수 있습니다. 편집 프로젝트를 저장하지 않습니다. 홈에 파일을 놓거나 한 도구에서 다른 도구로 이어서 작업할 때는 다음 페이지가 열 수 있도록 파일을 이 브라우저의 IndexedDB(nerulio-handoff)에 잠시 둡니다. 다음 페이지가 가져가는 즉시 삭제하고, 2분이 지나면 사용하지 않으며, 업로드하지 않습니다. 미디어 결과는 기기의 브라우저 전용 임시 저장소에 기록될 수 있습니다. 결과를 버리면 삭제하며, 비정상 종료로 남은 파일은 브라우저 사이트 데이터 삭제 또는 다음 미디어 사용 시 7일이 지난 파일 정리로 제거합니다.'],['분석과 광고','분석 전송은 기본적으로 꺼져 있습니다. 운영자가 어댑터를 연결하면 허용된 도구 이벤트·언어·기기 구분·유입 분류만 전달하며 파일명과 파일 내용은 제외합니다. 현재 빌드의 광고 상태는 아래에 표시합니다. 운영자가 Google AdSense를 켜면 Google과 파트너가 적용되는 동의 설정에 따라 광고·측정·부정행위 방지를 위한 네트워크 요청과 쿠키 또는 유사 저장소를 사용할 수 있습니다. 광고에 편집 중인 파일 업로드가 필요한 것은 아닙니다. 운영자는 필요한 지역에 Google Privacy & Messaging 또는 Google 인증 CMP를 구성해야 하며, 이 사이트는 인증 동의 시스템을 흉내 내지 않습니다.'],['문의와 공개 제보','문의 페이지의 GitHub Issues는 공개 채널입니다. 개인 문서·개인정보·비밀 화면을 올리지 마세요. GitHub에 직접 제출한 정보에는 GitHub의 정책이 적용됩니다.']],
 terms:[['이용과 책임','소유하거나 처리 권한이 있는 파일을 사용하세요. 입력 파일과 결과 사용에 대한 책임은 사용자에게 있습니다. {brand}는 제공 가능한 상태로 제공되며 중단 없는 동작이나 결과의 정확성·완전성을 보장하지 않습니다. 적용 법률상 배제할 수 없는 권리를 제한하지 않습니다.'],['원본 보관과 결과 확인','백업을 보관하고 결과를 사용하기 전에 내보낸 파일을 확인하세요. 이미지 압축·변환은 세부 묘사, 투명도, 애니메이션, 메타데이터, 색상 정보를 잃을 수 있습니다. 일반 확대는 사라진 정보를 복원하지 않으며 배경 제거와 실험적 인물 AI는 피사체 일부를 지우거나 배경을 남길 수 있습니다.'],['PDF 제한','페이지와 시각적 덧붙이기를 편집하며 기존 본문 수정·OCR·보안 마스킹·인증서 서명은 지원하지 않습니다. 양식이 평면화되고 서명은 보존되지 않습니다. 글자 위를 덮는 것은 보안 삭제가 아닙니다. 이미지 기반 출력은 글자 선택·검색을 잃으므로 가독성과 페이지 순서를 다시 확인하세요.'],['미디어와 기기 제한','코덱 지원은 브라우저에 따라 다릅니다. 빠른 자르기는 범위 안의 키프레임으로 재포장하고 정밀 모드는 재인코딩합니다. 별도 호환 모드만 실시간 녹화입니다. 음성·GIF도 품질 손실이나 용량 증가가 가능합니다. 메모리 한계나 다운로드 중단으로 실패할 수 있으며 목표 용량이나 처리 속도를 보장하지 않습니다.'],['외부 구성 요소','선택 기능의 엔진·모델에는 별도 라이선스와 제공 조건이 있습니다. 광고가 켜져도 편집과 분리되며 결과 다운로드의 조건이 되지 않습니다. 재현 가능한 문제는 문의 페이지를 통해 알려주세요.']],
 contact:[['문제 제보와 개선 제안','{brand} 공개 저장소의 GitHub Issues를 사용합니다. 제보는 공개되며 새 이슈 작성에는 일반적으로 GitHub 계정이 필요합니다. 비공개 문서를 전달하는 채널이 아닙니다.'],['알려주시면 좋은 정보','도구 URL, 브라우저와 버전, 기대한 결과, 재현 순서를 적어 주세요. 공개 권한이 있는 비민감 샘플만 첨부하고 개인 파일·비밀번호·기밀 문서는 올리지 마세요.'],['응답 안내','응답 기한은 보장하지 않습니다. 프로젝트에 별도 지원 이메일은 제공되지 않았으므로 아래 이슈 채널을 이용해 주세요.']]
 },
 ja:{
 about:[['ファイルのための小さな作業場','{brand}はブラウザで使えるファイルツール集です。アカウント登録やアップロードの手間をかけず、よくある編集を簡単にすることを目指しています。選択した画像・PDF・メディアは端末で処理します。'],['4つの編集ツール','画像エディターは切り抜き・サイズ変更・変換・背景削除、PDFエディターはページ結合・整理・見た目の注釈、ピクセル化は小さなPNG素材の作成に対応します。メディアエディターではフレーム・GIF・音声の抽出と対応コーデックでMP4・WebMを書き出せます。'],['機能の範囲','通常の拡大はAI復元ではなく補間処理です。実験的な超解像・一般背景除去はモデルを取得し端末で実行します。コーデック、メモリ、元ファイルで結果が変わるため、各ツールの説明を確認してください。']],
 privacy:[['選択したファイル','{brand}には画像・PDF・動画・音声を{brand}サーバーへ送るAPIはありません。ブラウザのメモリで読み込み、端末で保存用ファイルを作ります。アカウントやサーバー上の編集プロジェクトは作りません。再読み込みやタブを閉じる操作でメモリ上の作業は消えます。'],['外部への通信','サイトの配信ではホスティング事業者に通常の接続情報が送られます。PDF・メディアエンジンは必要時にこのサイトから取得します。HEIC・注釈フォント・ONNX Runtime・公開AIモデルはjsDelivrやHugging Faceから取得する場合があります。選択ファイルの内容は送信しません。'],['端末への保存','言語・お気に入り・最近使ったツールをlocalStorageに保存します。公開モデルはキャッシュされる場合があります。ホームにファイルを置いたとき、またはツールから別のツールへ続けるときは、次のページが開けるようファイルをこのブラウザのIndexedDB（nerulio-handoff）に一時的に置きます。次のページが受け取るとすぐ削除し、2分を過ぎたものは使わず、アップロードはしません。メディア出力は端末内の一時保存を利用し、結果を破棄すると削除します。異常終了後はサイトデータ削除、または次回使用時に7日以上経過したファイルの整理で削除します。'],['解析と広告','解析送信は初期状態で無効です。運営者がアダプターを接続した場合、許可されたツールイベント・言語・端末区分・流入分類のみを渡し、ファイル名と内容は除外します。このビルドの広告状態は下に表示します。運営者がGoogle AdSenseを有効にすると、同意設定に従い、Googleとパートナーが広告・測定・不正防止の通信やCookieなどを使用する場合があります。広告のために編集中のファイルをアップロードする必要はありません。必要な地域では運営者がGoogle Privacy & MessagingまたはGoogle認定CMPを設定する必要があります。このサイトは認定同意システムを模倣しません。'],['お問い合わせと公開報告','お問い合わせページのGitHub Issuesは公開窓口です。個人文書、個人情報、機密画面を投稿しないでください。GitHubへ直接送信した情報には同社のポリシーが適用されます。']],
 terms:[['利用と責任','所有するか処理する権限のあるファイルを使用してください。入力と出力の利用は利用者の責任です。{brand}は提供可能な状態で提供され、中断のない動作や結果の正確性・完全性を保証しません。適用法上排除できない権利は制限しません。'],['元ファイルの保管','バックアップを保管し、出力ファイルを確認してから利用してください。画像の圧縮・変換で細部、透明度、アニメーション、メタデータ、色情報が失われる場合があります。通常の拡大は欠けた情報を復元しません。背景削除や実験的な人物AIは被写体を消したり背景を残したりする場合があります。'],['PDFの制限','ページと見た目の重ね合わせを編集します。既存本文の編集、OCR、安全な墨消し、証明書署名は非対応です。フォームは平面化される場合があり、署名は保持しません。文字を覆っても安全な削除にはなりません。画像化すると文字選択・検索を失うため、読みやすさとページ順を確認してください。'],['メディアと端末の制限','高速カットは範囲内のキーフレームで再格納し、精密モードは再エンコードします。互換モードのみリアルタイム録画です。コーデック対応・品質・容量・速度は端末と元ファイルに依存します。'],['外部コンポーネント','追加エンジンやモデルにはそれぞれライセンスと提供条件があります。広告を有効にしても編集とは分離され、結果の保存条件にはなりません。再現できる問題はお問い合わせページから報告してください。']],
 contact:[['不具合の報告・改善の提案','{brand}の公開リポジトリにあるGitHub Issuesをご利用ください。投稿は公開され、新しいIssueの作成には通常GitHubアカウントが必要です。非公開文書の送付窓口ではありません。'],['お知らせいただきたいこと','ツールのURL、ブラウザとバージョン、期待した結果、再現手順を記載してください。公開権限のある機密性のないサンプルだけを添付し、個人ファイル・パスワード・機密文書は投稿しないでください。'],['返信について','返信までの時間は保証しません。このプロジェクトには別のサポートメールアドレスが提供されていないため、下のIssue窓口をご利用ください。']]
 }
});
/** Privacy text for builds with accounts (SERVICE_API=on). Replaces the "no account" first
 * section and adds exactly what the control plane stores. Default builds are unchanged. */
export const SERVICE_PRIVACY=brandCopy({
 en:[['Your selected files','{brand} has no API for uploading your selected images, PDFs, video or audio. Files are read in browser memory and results are generated on your device, on both Free and Pro. Editing projects, files and results are never stored on a {brand} server. Reloading or closing the tab clears the in-memory workspace.'],
  ['Accounts, daily limits and Pro','{brand} Free needs no account. To apply the free daily limit for heavy tools, the site sets an HttpOnly cookie (nerulio_anon) with a random identifier. When you run a heavy tool, only the tool name and a random operation id are sent to the {brand} service on Cloudflare — never file contents, file names, sizes or results. A per-day usage counter is kept for up to 7 days and per-operation records for up to 3 days. To limit automated abuse, a keyed hash of your network address that changes every day may also be counted; it cannot be turned back into your address. Signing in with Google stores your Google account identifier, e-mail address and name, and a hashed session token (cookie nerulio_session, 30 days). Pro payments are handled by the payment provider; {brand} stores the subscription status, period end and the provider’s customer and subscription identifiers, never card details. Cloudflare Turnstile may be shown to suspicious traffic and is governed by Cloudflare’s privacy policy. If the service cannot be reached, a small counter (nerulio.grace.v1) in localStorage allows a few heavy jobs so tools keep working.']],
 ko:[['선택한 파일의 처리','{brand}에는 선택한 이미지·PDF·영상·음성을 업로드하는 API가 없습니다. Free와 Pro 모두 브라우저 메모리에서 파일을 읽고 기기에서 결과를 만듭니다. 편집 프로젝트·파일·결과를 {brand} 서버에 저장하지 않습니다. 새로고침하거나 탭을 닫으면 메모리의 작업이 사라집니다.'],
  ['계정, 하루 제한과 Pro','{brand} Free는 계정이 필요 없습니다. 무거운 도구의 하루 무료 제한을 적용하기 위해 임의 식별자를 담은 HttpOnly 쿠키(nerulio_anon)를 설정합니다. 무거운 도구를 실행할 때 Cloudflare의 {brand} 서비스에는 도구 이름과 임의의 작업 ID만 보내며, 파일 내용·파일명·크기·결과는 보내지 않습니다. 날짜별 사용 횟수는 최대 7일, 작업별 기록은 최대 3일 보관합니다. 자동화된 남용을 막기 위해 매일 바뀌는 키로 만든 네트워크 주소 해시를 함께 집계할 수 있으며, 이 값으로 주소를 되돌릴 수 없습니다. Google로 로그인하면 Google 계정 식별자·이메일·이름과 해시한 세션 토큰(쿠키 nerulio_session, 30일)을 저장합니다. Pro 결제는 결제 대행사가 처리하며 {brand}는 구독 상태·기간 종료일·대행사의 고객/구독 식별자만 저장하고 카드 정보는 저장하지 않습니다. 의심스러운 요청에는 Cloudflare Turnstile이 표시될 수 있으며 Cloudflare의 개인정보 정책이 적용됩니다. 서비스에 연결할 수 없을 때 도구가 계속 동작하도록 localStorage의 작은 카운터(nerulio.grace.v1)로 소수의 무거운 작업을 허용합니다.']],
 ja:[['選択したファイル','{brand}には画像・PDF・動画・音声をアップロードするAPIはありません。FreeでもProでも、ブラウザのメモリで読み込み、端末で結果を作ります。編集プロジェクト・ファイル・結果を{brand}のサーバーに保存しません。再読み込みやタブを閉じる操作でメモリ上の作業は消えます。'],
  ['アカウント、1日の上限とPro','{brand} Freeにアカウントは不要です。重いツールの無料上限を適用するため、ランダムな識別子を含むHttpOnly Cookie（nerulio_anon）を設定します。重いツールの実行時にCloudflare上の{brand}サービスへ送るのはツール名とランダムな処理IDだけで、ファイル内容・ファイル名・サイズ・結果は送りません。日ごとの使用回数は最大7日、処理ごとの記録は最大3日保存します。自動化された濫用を防ぐため、毎日変わる鍵で作ったネットワークアドレスのハッシュを集計する場合がありますが、元のアドレスには戻せません。Googleでログインすると、Googleアカウント識別子・メール・名前と、ハッシュ化したセッショントークン（Cookie nerulio_session、30日）を保存します。Proの支払いは決済事業者が処理し、{brand}はサブスクリプションの状態・期間終了日・事業者の顧客/サブスクリプション識別子のみを保存し、カード情報は保存しません。不審なアクセスにはCloudflare Turnstileが表示される場合があり、Cloudflareのプライバシーポリシーが適用されます。サービスに接続できない場合は、localStorageの小さなカウンター（nerulio.grace.v1）で少数の重い処理を許可します。']]
});
function sections(page,locale,service){
 if(!(service&&page==='privacy'))return policies[locale][page];
 const [files,account]=SERVICE_PRIVACY[locale];
 return [files,account,...policies[locale].privacy.slice(1)];
}
/** Shown when the deployment enables Cloudflare Web Analytics (CF_WEB_ANALYTICS=on). */
export const WEB_ANALYTICS_NOTE=brandCopy({
 en:'This site counts visits with Cloudflare Web Analytics. It sets no cookies and uses no local storage; Cloudflare receives the page address, referrer and browser/device information and reports them only in aggregate. Your files are never sent.',
 ko:'이 사이트는 Cloudflare Web Analytics로 방문 수를 집계합니다. 쿠키나 로컬 저장소를 쓰지 않으며, Cloudflare는 페이지 주소·유입 경로·브라우저/기기 정보를 받아 합계로만 보고합니다. 편집하는 파일은 전송되지 않습니다.',
 ja:'このサイトはCloudflare Web Analyticsで訪問数を集計します。Cookieやローカルストレージは使わず、Cloudflareはページのアドレス・参照元・ブラウザ/端末情報を受け取り、集計値としてのみ報告します。編集中のファイルは送信されません。'
});
export function policyContent(page,locale,ads=false,service=false,analytics=false){
 const l=labels[locale];
 const status=ads?{en:'Google AdSense is enabled in this build. Ad delivery depends on account approval, configured units and consent.',ko:'이 빌드에는 Google AdSense가 활성화되어 있습니다. 실제 노출은 계정 승인·광고 단위·동의 설정에 따라 달라집니다.',ja:'このビルドではGoogle AdSenseが有効です。配信はアカウント承認、広告枠、同意設定によります。'}:{en:'Google AdSense is disabled in this build. No Google advertising script or ad units are loaded.',ko:'이 빌드에서는 Google AdSense가 비활성화되어 광고 스크립트와 광고 단위를 불러오지 않습니다.',ja:'このビルドではGoogle AdSenseが無効で、Google広告スクリプトや広告枠は読み込みません。'};
 return `<a class="policy-home" href="${locale}/">← ${esc(l.home)}</a><h1>${esc(l[page])}</h1>${sections(page,locale,service).map(([h,p])=>`<section><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('')}${page==='privacy'&&analytics?`<p class="analytics-status">${esc(WEB_ANALYTICS_NOTE[locale])}</p>`:''}${page==='privacy'?`<p class="ad-status">${esc(status[locale])}</p><p><a href="https://policies.google.com/technologies/ads" rel="noopener" target="_blank">Google · ${esc(l.privacy)}</a></p>`:''}${page==='contact'?`<p><a href="${ISSUES_URL}" target="_blank" rel="noopener">GitHub Issues ↗</a></p>`:''}`;
}
export {footer};
