export const SEARCH_TERMS = Object.freeze({
 'remove-bg':['remove bg','background remover','transparent background','배경 제거','누끼','背景削除'],
 'logo-bg':['white background remover','transparent logo','로고 배경','白背景'],
 pixel:['pixelate','pixel art','pixel converter','도트','ピクセルアート'],
 refiner:['pixel art converter','game asset','pixelize','게임 에셋','ゲーム素材'],
 'margin-crop':['transparent trim','crop whitespace','여백 제거','余白削除'],
 'favicon-pack':['favicon maker','brand icon','파비콘','ファビコン'],
 'frame-normalize':['sprite normalizer','normalize frames','프레임 정렬'],
 'print-pack':['print ratio resizer','etsy print','인쇄 비율'],
 'texture-lab':['pbr texture','texture channels','orm texture','텍스처','펌리새','テクスチャ'],
 'channel-unpacker':['unpack channels','orm split','mask map split','채널 분리','チャンネル分離'],
 'normal-map-converter':['opengl directx normal','flip green channel','normal map convert','노멀 방향','ノーマル変換'],
 'pbr-texture-validator':['pbr check','texture set validator','power of two check','텍스처 점검','PBR点検'],
 'texture-edge-bleed':['alpha bleed','edge padding','dilate texture','가장자리 번짐','エッジにじみ'],
 'pixel-lab':['pixel lab','sprite palette','palette lock','animation palette','픽셀 랩','도트 팔레트','ドットパレット'],
 'palette-extractor':['palette extractor','extract palette','gpl palette','lospec palette','팔레트 추출','パレット抽出'],
 'palette-swap-ramp':['palette swap ramp','team colors','recolor sprite','색 교체','チームカラー'],
 'pixel-art-cleanup':['pixel art cleanup','remove anti aliasing','stray pixels','안티에일리어싱 제거','アンチエイリアス除去'],
 'pixel-perfect-checker':['pixel perfect checker','pixel size detect','downscale pixel art','도트 크기 확인','ドットサイズ判定'],
});
